### ISSUE TITLE
Missing stack trace invoking node10.x Lambda

### ISSUE THREAD

**Issue by ghost** [aws/aws-sam-cli#1232]
### Description

When I invoke a simple Lambda that throws an error using the node10.x runtime, SAM CLI gives me the `errorType` and `errorMessage` but no `trace`. If I run the same Lambda using the AWS Lambda Console, I see all three. Additionally, if I run the Lambda using SAM CLI and the nodejs8.10 runtime, I see the `stackTrace`.

### Steps to reproduce

1. `$ sam init`
1. Edit `hello-world/app.js` to contain just:
    ```bash
    exports.lambdaHandler = async (event, context) => {
      throw new Error('oh no')
    };
    ```
1. `$ sam --debug local invoke HelloWorldFunction --event event.json`

### Observed result

```
2019-06-18 16:07:58 Using SAM Template at /Users/nick/work/sam-test/sam-app/template.yaml
2019-06-18 16:07:58 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-06-18 16:07:58 Changing event name from before-call.apigateway to before-call.api-gateway
2019-06-18 16:07:58 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-06-18 16:07:58 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-06-18 16:07:58 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-06-18 16:07:58 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-06-18 16:07:58 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-06-18 16:07:58 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-06-18 16:07:58 Changing event name from before-call.apigateway to before-call.api-gateway
2019-06-18 16:07:58 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-06-18 16:07:58 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-06-18 16:07:58 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-06-18 16:07:58 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-06-18 16:07:58 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-06-18 16:07:58 local invoke command is called
2019-06-18 16:07:58 No Parameters detected in the template
2019-06-18 16:07:58 2 resources found in the template
2019-06-18 16:07:58 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2019-06-18 16:07:58 Trying paths: ['/Users/nick/.docker/config.json', '/Users/nick/.dockercfg']
2019-06-18 16:07:58 Found file at path: /Users/nick/.docker/config.json
2019-06-18 16:07:58 Found 'auths' section
2019-06-18 16:07:58 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-06-18 16:07:58 Found 'credsStore' section
2019-06-18 16:07:58 http://localhost:None "GET /v1.35/_ping HTTP/1.1" 200 2
2019-06-18 16:07:58 Trying paths: ['/Users/nick/.docker/config.json', '/Users/nick/.dockercfg']
2019-06-18 16:07:58 Found file at path: /Users/nick/.docker/config.json
2019-06-18 16:07:58 Found 'auths' section
2019-06-18 16:07:58 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-06-18 16:07:58 Found 'credsStore' section
2019-06-18 16:07:58 Found one Lambda function with name 'HelloWorldFunction'
2019-06-18 16:07:58 Invoking app.lambdaHandler (nodejs10.x)
2019-06-18 16:07:58 No environment variables found for function 'HelloWorldFunction'
2019-06-18 16:07:58 Environment variables overrides data is standard format
2019-06-18 16:07:58 Loading AWS credentials from session with profile 'None'
2019-06-18 16:07:58 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-06-18 16:07:58 Changing event name from before-call.apigateway to before-call.api-gateway
2019-06-18 16:07:58 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-06-18 16:07:58 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-06-18 16:07:58 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-06-18 16:07:58 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-06-18 16:07:58 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-06-18 16:07:58 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-06-18 16:07:58 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-06-18 16:07:58 Looking for credentials via: env
2019-06-18 16:07:58 Looking for credentials via: assume-role
2019-06-18 16:07:58 Looking for credentials via: shared-credentials-file
2019-06-18 16:07:58 Found credentials in shared credentials file: ~/.aws/credentials
2019-06-18 16:07:58 Resolving code path. Cwd=/Users/nick/work/sam-test/sam-app, CodeUri=hello-world/
2019-06-18 16:07:58 Resolved absolute path to code is /Users/nick/work/sam-test/sam-app/hello-world
2019-06-18 16:07:58 Code /Users/nick/work/sam-test/sam-app/hello-world is not a zip/jar file
2019-06-18 16:07:58 Skipping building an image since no layers were defined
2019-06-18 16:07:58 Trying paths: ['/Users/nick/.docker/config.json', '/Users/nick/.dockercfg']
2019-06-18 16:07:58 Found file at path: /Users/nick/.docker/config.json
2019-06-18 16:07:58 Found 'auths' section
2019-06-18 16:07:58 Auth data for https://index.docker.io/v1/ is absent. Client might be using a credentials store instead.
2019-06-18 16:07:58 Found 'credsStore' section
2019-06-18 16:07:58 http://localhost:None "GET /v1.35/images/lambci/lambda:nodejs10.x/json HTTP/1.1" 200 None
2019-06-18 16:07:58 Looking for auth config
2019-06-18 16:07:58 Using credentials store "osxkeychain"
2019-06-18 16:07:58 Looking for auth entry for 'https://index.docker.io/v1/'
2019-06-18 16:07:58 Found auth config
2019-06-18 16:08:00 http://localhost:None "POST /v1.35/images/create?tag=nodejs10.x&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:nodejs10.x Docker container image......
2019-06-18 16:08:00 Mounting /Users/nick/work/sam-test/sam-app/hello-world as /var/task:ro,delegated inside runtime container
2019-06-18 16:08:00 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-06-18 16:08:00 http://localhost:None "GET /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/json HTTP/1.1" 200 None
2019-06-18 16:08:00 http://localhost:None "GET /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/json HTTP/1.1" 200 None
2019-06-18 16:08:00 http://localhost:None "POST /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/start HTTP/1.1" 204 0
2019-06-18 16:08:00 Starting a timer for 3 seconds for function 'HelloWorldFunction'
2019-06-18 16:08:00 http://localhost:None "GET /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/json HTTP/1.1" 200 None
2019-06-18 16:08:00 http://localhost:None "POST /containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
START RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Version: $LATEST
END RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72
REPORT RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72	Duration: 16.57 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 44 MB
{
  "errorType": "Error",
  "errorMessage": "oh no"
}
2019-06-18 16:08:01 http://localhost:None "GET /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07/json HTTP/1.1" 200 None
2019-06-18 16:08:01 http://localhost:None "DELETE /v1.35/containers/b36211ac250647db0ed3c240f279767e6e84bbc3b3bd9666cc2ec3c524003a07?v=False&link=False&force=True HTTP/1.1" 204 0
```

### Expected result

As above, but with a `trace` element. On the AWS Lambda Console, the output is as follows:

```
{
  "errorType": "Error",
  "errorMessage": "oh no",
  "trace": [
    "Error: oh no",
    "    at Runtime.exports.handler (/var/task/index.js:2:9)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:63:25)",
    "    at process._tickCallback (internal/process/next_tick.js:68:7)"
  ]
}
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.14.5
2. `sam --version`: `SAM CLI, version 0.17.0`  (from Homebrew)

**Comment by TheSriram** [comment]
This could be because our code looks for `stackTrace` instead of `trace`, when checking if a lambda response is actually an error.

https://github.com/awslabs/aws-sam-cli/blob/8c34a9fa3421bd5e5705276515dbea7f5a855378/samcli/local/services/base_local_service.py#L135

**Comment by sriram-mv** [comment]
I tried to repro this and with the latest images, "trace" is being returned for nodejs10.x

Closing this issue.
