### ISSUE TITLE
Lambda failing to invoke in debug mode using layers

### ISSUE THREAD

**Issue by wizage** [aws/aws-sam-cli#1462]
### Description

When using Lambda layers I can invoke using: 
```
sam local invoke "HelloWorldFunction" -e event.json
```
This invoke works without any problems.

When invoking with debugging enabled though it can't find the layers:
```
sam local invoke "HelloWorldFunction" -e event.json -d 5858
```

### Steps to reproduce

Developing a workshop so step by step walk-through of how I setup layers can be found here: https://github.com/wizage/Lambda-Layers-Workshop

After the adding layers to your functions section is where this is failing.

### Observed result

<details> 
  <summary>Without debug port open results (--debug)</summary>

  ```bash
  sam-app $ sam local invoke "HelloWorldFunction" -e event.json --debug
  Using SAM Template at /Users/sampatze/Documents/Projects/sam-app/template.yaml
  Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
  local invoke command is called
  No Parameters detected in the template
  3 resources found in the template
  Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
  Found one Lambda function with name 'HelloWorldFunction'
  Invoking app.lambdaHandler (nodejs10.x)
  No environment variables found for function 'HelloWorldFunction'
  Environment variables overrides data is standard format
  Loading AWS credentials from session with profile 'None'
  2019-10-14 17:43:45 Found credentials in shared credentials file: ~/.aws/credentials
  Resolving code path. Cwd=/Users/sampatze/Documents/Projects/sam-app, CodeUri=hello-world/
  Resolved absolute path to code is /Users/sampatze/Documents/Projects/sam-app/hello-world
  Code /Users/sampatze/Documents/Projects/sam-app/hello-world is not a zip/jar file
  HelloWorldDepLayer is a local Layer in the template
  Resolving code path. Cwd=/Users/sampatze/Documents/Projects/sam-app, CodeUri=dependencies/
  Building image...
  Requested to skip pulling images ...

  Mounting /Users/sampatze/Documents/Projects/sam-app/hello-world as /var/task:ro,delegated inside runtime container
  Starting a timer for 3 seconds for function 'HelloWorldFunction'
  START RequestId: f9d58855-dfc1-1fd3-8912-96446a2fbc59 Version: $LATEST
  END RequestId: f9d58855-dfc1-1fd3-8912-96446a2fbc59
  REPORT RequestId: f9d58855-dfc1-1fd3-8912-96446a2fbc59	Duration: 170.59 ms	Billed Duration: 200 ms	Memory Size: 128 MB	Max Memory Used: 47 MB	
  Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 3532, 'exitReason': 'success', 'exitCode': 0, 'requestId': '3c4ebc83-19eb-4062-8f0e-502ca9730f6b', 'installationId': 'a77afc37-597e-4da3-b1ad-eecb16e38bd2', 'sessionId': '633b098b-a5ad-4378-a20c-3cbc90c1841e', 'executionEnvironment': 'CLI', 'pyversion': '3.7.4', 'samcliVersion': '0.22.0'}}]}
  Telemetry response: 200
  {"statusCode":200,"body":"{\"message\":\"Today is Tuesday\",\"location\":\"72.21.198.64\"}"}
  ```

</details>

<details>

  <summary>With debug port open results (--debug)</summary>

  ```bash
  sam-app $ sam local invoke "HelloWorldFunction" -e event.json -d 5858 --debug
  Using SAM Template at /Users/sampatze/Documents/Projects/sam-app/template.yaml
  Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
  local invoke command is called
  No Parameters detected in the template
  3 resources found in the template
  Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
  Found one Lambda function with name 'HelloWorldFunction'
  Invoking app.lambdaHandler (nodejs10.x)
  No environment variables found for function 'HelloWorldFunction'
  Environment variables overrides data is standard format
  Loading AWS credentials from session with profile 'None'
  2019-10-14 17:47:17 Found credentials in shared credentials file: ~/.aws/credentials
  Resolving code path. Cwd=/Users/sampatze/Documents/Projects/sam-app, CodeUri=hello-world/
  Resolved absolute path to code is /Users/sampatze/Documents/Projects/sam-app/hello-world
  Code /Users/sampatze/Documents/Projects/sam-app/hello-world is not a zip/jar file
  HelloWorldDepLayer is a local Layer in the template
  Resolving code path. Cwd=/Users/sampatze/Documents/Projects/sam-app, CodeUri=dependencies/
  Building image...
  Requested to skip pulling images ...

  Mounting /Users/sampatze/Documents/Projects/sam-app/hello-world as /var/task:ro,delegated inside runtime container
  Setting up SIGTERM interrupt handler
  Debugger listening on ws://0.0.0.0:5858/ab84b9ae-3004-4e4e-836b-74419b9f30b5
  For help, see: https://nodejs.org/en/docs/inspector
  Debugger attached.
  2019-10-15T00:47:26.052Z	undefined	ERROR	Uncaught Exception	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'moment'","stack":["Runtime.ImportModuleError: Error: Cannot find module 'moment'","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:45:30)","    at Module._compile (internal/modules/cjs/loader.js:775:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)","    at Module.load (internal/modules/cjs/loader.js:653:32)","    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)","    at Function.Module._load (internal/modules/cjs/loader.js:585:3)","    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)","    at startup (internal/bootstrap/node.js:283:19)"]}
  START RequestId: 4981a986-1c64-18d4-ca71-07a7b14b8466 Version: $LATEST
  END RequestId: 4981a986-1c64-18d4-ca71-07a7b14b8466
  REPORT RequestId: 4981a986-1c64-18d4-ca71-07a7b14b8466	Init Duration: 5960.94 ms	Duration: 0.00 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 53 MB	
  {
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'moment'"
  }
  Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 8803, 'exitReason': 'success', 'exitCode': 0, 'requestId': '3739d0f3-d06b-45ae-96f5-9ae4d1f71a09', 'installationId': 'a77afc37-597e-4da3-b1ad-eecb16e38bd2', 'sessionId': 'd10d3ddd-c284-456f-b57c-0b07eddcdaba', 'executionEnvironment': 'CLI', 'pyversion': '3.7.4', 'samcliVersion': '0.22.0'}}]}
  Telemetry response: 200
  ```

</details>

Please provide command output with `--debug` flag set.

### Expected result

I expect to see the same result that the non-debug SAM local provides.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 10.14.6
2. `sam --version`: `SAM CLI, version 0.22.0`

`Add --debug flag to command you are running`

**Comment by SamuelCook** [comment]
Also affects SAM CLI version 0.30.0.

**Comment by mrunalshah6** [comment]
As far as I know SAM local doesn't support Lambda layers. You can trick SAM into building your layer by using guidelines from this website
https://bryson3gps.wordpress.com/2018/12/06/trick-sam-into-building-your-lambda-layers/

**Comment by timoschilling** [comment]
SAM CLI supports layers since v0.8.1 https://github.com/awslabs/aws-sam-cli/releases/tag/v0.8.1

**Comment by CoshUS** [comment]
Unable to reproduce this issue with the latest version (1.12.0). Can you try again with 1.12.0? If the issue persists, can you provide your template file?

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.
