### ISSUE TITLE
Sam Package

### ISSUE THREAD

**Issue by mobermeier15** [aws/aws-sam-cli#1951]
Getting this error upon running the following command on Amazon EC2 with Amazon Linux 2.  Client was just installed today so it is the latest. The OS also updated today. 

sam package \
--template-file template.yaml \
--output-template-file packaged.yml \
--s3-bucket ******(removed bucket name)

Any assistance with this is much appreciated. 

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.47.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/package/command.py", line 100, in cli
    ctx.profile,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/package/command.py", line 130, in do_cli
    package_context.run()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/package/package_context.py", line 95, in run
    exported_str = self._export(self.template_file, self.use_json)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/commands/package/package_context.py", line 110, in _export
    exported_template = template.export()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 639, in export
    self.template_dict = self.export_metadata(self.template_dict)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.47.0/libexec/lib/python3.7/site-packages/samcli/lib/package/artifact_exporter.py", line 594, in export_metadata
    if "Metadata" not in template_dict:
TypeError: argument of type 'NoneType' is not iterable

**Comment by jfuss** [comment]
@mobermeier15 What is the content's for `template.yaml`? From the error, it seems like that might be an empty file?

**Comment by mobermeier15** [comment]
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    photo_processor
    Sample SAM Template for photo_processor
Parameters:
    S3UserfilesBucketArn:
        Type: String
    
Globals:
    Function:
        Timeout: 10
Resources:
    PhotoProcessorFunctionIamRole: 
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                    - 
                        Effect: Allow
                        Principal:
                            Service: [lambda.amazonaws.com]
                        Action: ["sts:AssumeRole"]
            ManagedPolicyArns: ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
            Path: "/"
            Policies: 
                - 
                    PolicyName: "AllPrivsForPhotoAlbumUserfilesBucket"
                    PolicyDocument: 
                        Version: "2012-10-17"
                        Statement: 
                            -
                                Effect: "Allow"
                                Action: "s3:*"
                                Resource: !Join ["/", [!Ref S3UserfilesBucketArn, "*"]]
    PhotoProcessorFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.lambda_handler
            Role: !GetAtt PhotoProcessorFunctionIamRole.Arn
            Runtime: nodejs8.10
            Environment:
                Variables:
                    THUMBNAIL_WIDTH: 80
                    THUMBNAIL_HEIGHT: 80
    BucketPermission:
        Type: AWS::Lambda::Permission
        Properties:
            Action: 'lambda:InvokeFunction'
            FunctionName: !Ref PhotoProcessorFunction
            Principal: s3.amazonaws.com
            SourceAccount: !Ref "AWS::AccountId"
            SourceArn: !Ref S3UserfilesBucketArn
Outputs:
    PhotoProcessorFunction:
      Description: "Photo Processor Lambda Function ARN"
      Value: !GetAtt PhotoProcessorFunction.Arn
    PhotoProcessorFunctionIamRole:
      Description: "IAM Role created for Photo Processor function"
      Value: !GetAtt PhotoProcessorFunctionIamRole.Arn

**Comment by mobermeier15** [comment]
is the content of the yaml file. I also confirmed its UTF-8

**Comment by sriram-mv** [comment]
does running sam validate on the template return that its a valid template?

**Comment by sriram-mv** [comment]
@mobermeier15 I'm closing this issue, Please re-open if you still see this issue.

**Comment by tj** [comment]
I get this as well. It would be great to write SAM in something more robust and portable (Rust, Go, etc), Python always causes issues with its weird versioning as well

**Comment by tj** [comment]
FWIW I updated to 1.4.0 and it's giving me the same error

**Comment by tj** [comment]
I think I found it, I'm generating a template, and Go outputs `null` for nil slices, so it was `Layers: null` for a Lambda function. It validates as ok though, so something funky in the logic there, it would be nice if the validation was performed when packaging as well (if it's not already).

**Comment by AllanOricil** [comment]
Please, reopen this. It is not related to the template. It is very weird, after I build again this error started to happen. No clue what is causing it. But there is a bug...
