### ISSUE TITLE
Error with packaging when deploying from a non-C: drive

### ISSUE THREAD

**Issue by guevaraf** [aws/aws-sam-cli#2020]
**Describe the bug**
When running the command pattern "AWS: Deploy SAM Application" it fails on step Building function '[function name]' because of a script pointing to C: mount while the project is on a D: folder. We get error 'ValueError: path is on mount 'C:', start on mount 'd:''.

**To Reproduce**
1. Create a folder in D: or any drive other than C:
2. Create a workspace there
3. Create SAM application using command 'AWS: Create new SAM application'
4. Detect SAM CLI using command 'AWS: Detect SAM CLI'
5. Run locally the application to check it compiles and runs successfully
6. Try to deploy the application using command 'AWS: Deploy SAM application'

**Expected behavior**
SAM Application is successfully deployed.

**Screenshots**
- Please see the full console dump in the Additional context section -

**Computer (please complete the following information):**

- Windows Version: Windows 10 Pro v. 1903 x64
- Visual Studio Version: 1.45.1
- AWS Toolkit for Visual Studio Version: 1.10.0
- SAM Version: 0.52.0

**Additional context**
Full console dump:
```
Starting SAM Application deployment...
Building SAM Application...
Error with child process: Building function 'CronLFunction'
,Running NodejsNpmBuilder:NpmPack
,Running NodejsNpmBuilder:CopyNpmrc
,Running NodejsNpmBuilder:CopySource
,Running NodejsNpmBuilder:NpmInstall
,Running NodejsNpmBuilder:CleanUpNpmrc
,Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 96, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 129, in cli
    mode,
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 195, in do_cli
    modified_template = builder.update_template(ctx.template_dict, ctx.original_template_path, artifacts)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 161, in update_template
    artifact_relative_path = os.path.relpath(built_artifacts[logical_id], original_dir)
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\ntpath.py", line 562, in relpath
ValueError: path is on mount 'C:', start on mount 'd:'
An error occurred while deploying a SAM Application. Check the logs for more information by running the "View AWS Toolkit Logs" command from the Command Palette.
```

**Comment by guevaraf** [comment]
I created this issue first in VS Code AWS toolkit but it seems is aws-sam-cli related. Also, there is a similar issue #1336 but solves it in a different part.
