### ISSUE TITLE
SAM CLI integration has trouble with WSL 

### ISSUE THREAD

**Issue by jcogilvie** [aws/aws-sam-cli#2056]
### Description

Right off the bat, I'm not sure if this is a bug with `aws-sam-cli` or with the integration for JetBrains, but it could be fixed at either level, so here goes:  when I try to run from within WSL (1), the shared drives don't mount.  Now, docker has a well-known problem around mounting shared drives, but that doesn't seem to be the issue here.  The issue is in windows-land, docker linux-izes your mount paths, and then they sort of work for mounting if they are a direct translation:  i.e., `C:\foo\bar` is straightforward enough to translate to `/c/foo/bar` and docker can mount that.  But it doesn't know that in WSL-land, `/home/` actually maps back to the host OS as `/c/Users/me/AppData/Local/Packages/[my-wsl-distro]/rootDrive/home/`.  Somebody needs to perform this transform as a matter of course in order for build and/or debug to work from a container.

### Steps to reproduce

- 
- WSL Debian with:
    - python 3.7 on the path
    - IntelliJ Ultimate 2020.x
        - updated AWS plugin
        - project dir under /home/ somewhere
    - Any old lambda function (hello world works just fine)
        - requirements.txt exists and has stuff in it (my module uses boto3)
        - build with container

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A sample Lambda Safe Deployment Application

Resources:
  pollS3:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/main/python/my-module.lambda_handler
      CodeUri: .
      Runtime: python3.7
      Timeout: 300
      MemorySize: 128
```

### Observed result

```
/home/jogilvie/.local/bin/sam build pollS3 --template /home/jogilvie/workspace/project/template.yaml --build-dir /home/jogilvie/workspace/project/.aws-sam/build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='pollS3' and CodeUri='.'
No Parameters detected in the template
Building function 'pollS3'

Fetching lambci/lambda:build-python3.7 Docker container image......
Mounting /home/jogilvie/workspace/project as /tmp/samcli/source:ro,delegated inside runtime container  # HERE BE DRAGONS
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 135, in build_dependencies
    raise RequirementsFileNotFoundError(requirements_path)
aws_lambda_builders.workflows.python_pip.packager.RequirementsFileNotFoundError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Requirements file not found: /tmp/samcli/source/requirements.txt
Builder workflow failed
Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
    requirements_path=self.manifest_path,
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 135, in build_dependencies
    raise RequirementsFileNotFoundError(requirements_path)
aws_lambda_builders.workflows.python_pip.packager.RequirementsFileNotFoundError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Requirements file not found: /tmp/samcli/source/requirements.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/var/lang/lib/python3.7/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 6542, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': 'a77457de-0dbb-4bbe-bcab-290edceb37e2', 'installationId': '4aecf77a-d1d9-46e1-b061-2ba7f57547b5', 'sessionId': 'dc226991-1b52-41df-a16f-492cc40c2cc5', 'executionEnvironment': 'CLI', 'pyversion': '3.7.3', 'samcliVersion': '0.53.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - Requirements file not found: /tmp/samcli/source/requirements.txt

```

If I don't build with a container, I can make it work, but then when the time comes to invoke I get an equivalent error there.  

### Expected result

I expected the config to work.  Somebody's gotta tell docker where these files really live.  If I re-clone the repo on the windows side of things, I am successfully able to build and invoke.

I can sort of hack around it in a couple of ways to make things almost-work, but not all the way:   I can put the --build-dir and --base-dir somewhere outside of WSL (under /c/something) and docker reads them fine, but it's super frowned upon to write to host dirs from inside WSL, and permission errors abound.  

And even if I manage to get that all hacked together, I can't overwrite the template file path that the IntelliJ code passes into `local invoke`.  And then even once I get that all sorted (this is definitely an IntelliJ issue but I'm putting it here for future googlers) when IJ tries to mount its debugger config inside the docker container, it has the same translation issue (because my IntelliJ runs inside WSL with an x server), meaning the running code can't find the debugger config and is therefore un-debuggable (although you could theoretically reinterpret the path for this, too, which would fix it).

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Windows 10 Pro 10.0.18363, WSL Debian from the app store
2. `sam --version`: SAM CLI, version 0.53.0

**Comment by jcogilvie** [comment]
Definitely related to https://github.com/awslabs/aws-sam-cli/issues/1145 but I'm not sure that issue adequately captures what's going wrong.

**Comment by sriram-mv** [comment]
This is the mechanism we have in place currently to change paths:

https://github.com/awslabs/aws-sam-cli/blob/ee91629e289eaa634809e6d691ce701426bab318/samcli/local/docker/utils.py#L11

We look at the os.name, but clearly on windows it looks like you could be operating in the WSL or in a normal windows prompt, wonder if python exposes something that we can look at.

**Comment by jfuss** [comment]
Given age and no recent activity, I am assuming this has been solved or no longer an issue. 

Please open a new issue if something is still incorrect here. WSL should work with SAM CLI out of the box.
