### ISSUE TITLE
Expose Docker error messages to SAM output

### ISSUE THREAD

**Issue by pcolazurdo** [aws/aws-sam-cli#2086]
I couldn't find anything specific like this problem
### Describe your idea/feature/enhancement

SAM CLI should have an option to expose Docker error messages directly into the console. I spent +1 hours trying to figure out an error that was reported like this:

```
Mounting /home/ec2-user/environment/StartSessionLogger/start_session_logger as /tmp/samcli/source:ro,delegated inside runtime container
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 11, in <module>
    load_entry_point('aws-sam-cli==0.53.0', 'console_scripts', 'sam')()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.53.0/libexec/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
...
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/0.53.0/libexec/lib/python3.7/site-packages/samcli/local/docker/container.py", line 197, in wait_for_logs
    raise RuntimeError("Container does not exist. Cannot get logs for this container")
RuntimeError: Container does not exist. Cannot get logs for this container
```

I only found the issue when I run ```docker run -it --rm lambci/lambda:build-python3.7 ``` - With this, the problem was clear as I got: 

```
docker: failed to register layer: Error processing tar file(exit status 1): write /usr/lib/clang/3.6.2/include/arm_neon.h: no space left on device.
```

### Proposal

I don't think this should add any option, as the docker error message should be visible by default.

A possible suggestion: **sam --debug** could expose the exact command that has been run to try to start docker so the user could reproduce that manually

Hope this helps to make this great product even better

**Comment by pcolazurdo** [comment]
Just to add some details: I've been researching how this errors could be exposed in SAM and it seems there is an underlying issue with how this information is surfaced through the docker API - I've commented on [issue](https://github.com/docker/docker-py/issues/2503) to see what recommendations we get from the Docker team.

**Comment by what-name** [comment]
The command `sam build --use-container --debug` returns the final output of the Docker container like this
```
sam build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='SamTutorialFunction' and CodeUri='Lambda/'
No Parameters detected in the template
Building function 'SamTutorialFunction'

Fetching lambci/lambda:build-python3.8 Docker container image......
Mounting /Users/kn/Desktop/quipiSamTest/Lambda as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource succeeded
#### THIS BELOW
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
Build inside container was successful. Copying artifacts from container to host
Copying from container: /tmp/samcli/artifacts/. -> /<myFullPathHere>/.aws-sam/build/SamTutorialFunction
Build inside container succeeded
```

If it fails, does it not return the full error message at the `Build inside container returned response: xyz` line?

**Comment by pcolazurdo** [comment]
No, as the machine runs out of disk space even before the image is downloaded the output is not very clear. I guess the challenge is that the docker python API doesn't expose a specific error for this particular case: https://github.com/docker/docker-py/issues/2503

Example output
```
sam build -u --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
Building resource 'HelloWorldFunction'

Fetching lambci/lambda:build-python3.8 Docker container image...............................................................
Mounting /home/ec2-user/environment/sam-app/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Container was not created. Skipping deletion
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 3802, 'exitReason': 'RuntimeError', 'exitCode': 255, 'requestId': 'dc9c68df-974c-4165-a19f-8143c679dcef', 'installationId': '07ca921e-fd00-45a0-b48e-67da950576be', 'sessionId': '798a11f3-c489-4cfc-9359-4270c3da1988', 'executionEnvironment': 'CLI', 'pyversion': '3.6.10', 'samcliVersion': '0.38.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/telemetry/metrics.py", line 93, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/telemetry/metrics.py", line 62, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/build/command.py", line 127, in cli
    mode,
  File "/usr/local/lib/python3.6/site-packages/samcli/commands/build/command.py", line 192, in do_cli
    artifacts = builder.build()
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/build/app_builder.py", line 104, in build
    lambda_function.runtime)
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/build/app_builder.py", line 195, in _build_function
    runtime)
  File "/usr/local/lib/python3.6/site-packages/samcli/lib/build/app_builder.py", line 267, in _build_function_on_container
    container.wait_for_logs(stdout=stdout_stream, stderr=stderr_stream)
  File "/usr/local/lib/python3.6/site-packages/samcli/local/docker/container.py", line 197, in wait_for_logs
    raise RuntimeError("Container does not exist. Cannot get logs for this container")
RuntimeError: Container does not exist. Cannot get logs for this container
```

**Comment by pcolazurdo** [comment]
Closing as many things have changed since this issue was open - not sure is needed anymore
