### ISSUE TITLE
Error building app with M2Crypto package

### ISSUE THREAD

**Issue by Barlog951** [aws/aws-sam-cli#2118]
I'm trying to create lambda function and I need to have M2Crypto package for that

when I run the command `sam build --debug --use-container`
I end up with this error

It looks like sam have problem build sdist version

Is there some workaround for this?

Thanks :)

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
No Parameters detected in the template
Building function 'HelloWorldFunction'

Fetching lambci/lambda:build-python3.8 Docker container image......
Mounting /Users/Dodko/DEV/python/aha_cookie/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {m2crypto==0.36.0(sdist)}
initial compatible: set()
initial incompatible: {m2crypto==0.36.0(sdist)}
Downloading missing wheels: {m2crypto==0.36.0(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch m2crypto==0.36.0
compatible wheels after second download pass: set()
Build missing wheels from sdists (C compiling True): {m2crypto==0.36.0(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.36.0.tar.gz
compatible after building wheels (no C compiling): set()
Build missing wheels from sdists (C compiling False): {m2crypto==0.36.0(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.36.0.tar.gz
compatible after building wheels (C compiling): set()
Final compatible: set()
Final incompatible: set()
Final missing wheels: {m2crypto==0.36.0(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.36.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.36.0(sdist)}
Builder workflow failed
Traceback (most recent call last):
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.36.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.36.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/root/.local/pipx/venvs/aws-lambda-builders/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {m2crypto==0.36.0(sdist)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {m2crypto==0.36.0(sdist)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 12281, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': 'fc5f7c67-7ce2-42df-b55e-0035c7645b49', 'installationId': '4592a069-129f-4e49-a53a-4d54d8390214', 'sessionId': '4fad0311-71ae-4d51-961f-44b7b28d7f4f', 'executionEnvironment': 'CLI', 'pyversion': '3.7.8', 'samcliVersion': '0.53.0'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {m2crypto==0.36.0(sdist)}
```

**Comment by morefaey** [comment]
@Barlog951 - Could you please reproduce this using 1.1.0 (after we released GA), and with different python version that is different from Python 3.8?
As M@Crypto is not supported with Python 3.8: https://gitlab.com/m2crypto/m2crypto/-/blob/master/setup.py#L391
