### ISSUE TITLE
Enable AWS SSO support by bumping boto3 to 1.14.x

### ISSUE THREAD

**Issue by benkehoe** [aws/aws-sam-cli#2129]
With version 1.14.0, boto3 added support for loading credentials cached by `aws sso login` with the AWS CLI v2. By bumping SAM CLI's pinned boto3 version, SAM can deploy using AWS SSO-authenticated users.

**Comment by awood45** [comment]
PR #2113 was opened to do this for a different reason. I'm re-running the test suite against the latest `develop` branch changes, and if it looks good we can merge that today.

**Comment by awood45** [comment]
New PR is #2130

**Comment by awood45** [comment]
Merged and pending release.

**Comment by MinCheTsai** [comment]
We are using AWS SSO and sam can't package & deploy, waiting for release. 👍 👍 👍 🔥 🔥 🔥

**Comment by mndeveci** [comment]
Resolving this since it is released with [1.1.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.1.0)

**Comment by dinkzilla** [comment]
This is working for our Linux users, but Windows users on our team are still not able to deploy using SAM. Getting: 
`Error: Failed to create managed resources: unable to locate credentials.`
aws-cli's were updated using the msi earlier today.

**Comment by lmayorga1980** [comment]
I have the issue after sso login and trying to deploy a SAML CLI app.

```
2021-09-15 11:06:09,498 | Unable to export
Traceback (most recent call last):
  File "DIR\venv\lib\site-packages\samcli\lib\package\packageable_resources.py", line 126, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File DIRvenv\lib\site-packages\samcli\lib\package\packageable_resources.py", line 148, in do_export
    uploaded_url = upload_local_artifacts(
  File DIRvenv\lib\site-packages\samcli\lib\package\utils.py", line 171, in upload_local_artifacts
    return zip_and_upload(local_path, uploader, extension)
  File "DIR\venv\lib\site-packages\samcli\lib\package\utils.py", line 189, in zip_and_upload
    return uploader.upload_with_dedup(zip_file, precomputed_md5=md5_hash, extension=extension)
  File "DIR\venv\lib\site-packages\samcli\lib\package\s3_uploader.py", line 143, in upload_with_dedup
    return self.upload(file_name, remote_path)
  File "DIR\venv\lib\site-packages\samcli\lib\package\s3_uploader.py", line 122, in upload
    raise ex
  File "DIR\venv\lib\site-packages\samcli\lib\package\s3_uploader.py", line 114, in upload
    future.result()
  File "DIR\venv\lib\site-packages\s3transfer\futures.py", line 106, in result
    return self._coordinator.result()
  File "DIR\venv\lib\site-packages\s3transfer\futures.py", line 265, in result
    raise self._exception
  File "DIR\venv\lib\site-packages\s3transfer\tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "DIR\venv\lib\site-packages\s3transfer\tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "DIR\venv\lib\site-packages\s3transfer\upload.py", line 694, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "DIR\venv\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "DIR\venv\lib\site-packages\botocore\client.py", line 691, in _make_api_call
    http, parsed_response = self._make_request(
  File "DIR\venv\lib\site-packages\botocore\client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "DIR\venv\lib\site-packages\botocore\endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "DIR\venv\lib\site-packages\botocore\endpoint.py", line 132, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "DIR\venv\lib\site-packages\botocore\endpoint.py", line 115, in create_request
    self._event_emitter.emit(event_name, request=request,
  File "DIR\venv\lib\site-packages\botocore\hooks.py", line 357, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "DIR\venv\lib\site-packages\botocore\hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "DIR\venv\lib\site-packages\botocore\hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "DIR\venv\lib\site-packages\botocore\signers.py", line 90, in handler
    return self.sign(operation_name, request)
  File "DIR\venv\lib\site-packages\botocore\signers.py", line 154, in sign
    auth = self.get_auth_instance(**kwargs)
  File "DIR\venv\lib\site-packages\botocore\signers.py", line 234, in get_auth_instance
    frozen_credentials = self._credentials.get_frozen_credentials()
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 620, in get_frozen_credentials
    self._refresh()
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 515, in _refresh
    self._protected_refresh(is_mandatory=is_mandatory_refresh)
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 531, in _protected_refresh
    metadata = self._refresh_using()
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 672, in fetch_credentials
    return self._get_cached_credentials()
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 682, in _get_cached_credentials
    response = self._get_credentials()
  File "DIR\venv\lib\site-packages\botocore\credentials.py", line 2045, in _get_credentials
    response = client.get_role_credentials(**kwargs)
  File "DIR\venv\lib\site-packages\botocore\client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "DIR\venv\lib\site-packages\botocore\client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ForbiddenException) when calling the GetRoleCredentials operation: No access
```

My current `pip` setup:

```
$ pip list
Package                 Version
----------------------- ---------
arrow                   1.1.1
astroid                 2.7.3
atomicwrites            1.4.0
attrs                   21.2.0
aws-lambda-builders     1.6.0
aws-sam-cli             1.31.0
aws-sam-translator      1.38.0
backports.zoneinfo      0.2.1
binaryornot             0.4.4
boto                    2.49.0
boto3                   1.18.42
botocore                1.21.42
certifi                 2021.5.30
cffi                    1.14.6
cfn-lint                0.54.1
chardet                 4.0.0
chevron                 0.14.0
click                   7.1.2
cloudpickle             2.0.0
colorama                0.4.4
configparser            5.0.2
cookiecutter            1.7.3
cryptography            2.8
dateparser              1.0.0
docker                  4.2.2
doit                    0.33.1
fido2                   0.8.1
Flask                   1.1.4
idna                    2.10
iniconfig               1.1.1
isort                   5.9.3
itsdangerous            1.1.0
Jinja2                  2.11.3
jinja2-time             0.2.0
jmespath                0.10.0
jsonpatch               1.32
jsonpointer             2.1
jsonschema              3.2.0
junit-xml               1.9
lazy-object-proxy       1.6.0
lxml                    4.6.3
MarkupSafe              2.0.1
mccabe                  0.6.1
networkx                2.6.3
packaging               21.0
pip                     21.2.3
platformdirs            2.3.0
pluggy                  1.0.0
poyo                    0.5.0
py                      1.10.0
pycparser               2.20
pyenv-win               2.64.11
pylint                  2.10.2
pyOpenSSL               19.1.0
pyparsing               2.4.7
pypiwin32               223
pyrsistent              0.18.0
pytest                  6.2.5
python-dateutil         2.8.2
python-slugify          5.0.2
pytz                    2021.1
pywin32                 301
PyYAML                  5.4.1
regex                   2021.8.28
requests                2.25.1
requests-negotiate-sspi 0.5.2
s3transfer              0.5.0
serverlessrepo          0.1.10
setuptools              57.4.0
six                     1.16.0
text-unidecode          1.3
toml                    0.10.2
tomlkit                 0.7.2
tzdata                  2021.1
tzlocal                 3.0
urllib3                 1.26.6
watchdog                2.1.2
websocket-client        1.2.1
Werkzeug                1.0.1
wheel                   0.37.0
wrapt                   1.12.1
```

The `~/.aws/credentials` does not exist and the `~/.aws/config` has the right profile from my SAML CLI

`sam deploy --debug --no-fail-on-empty-changeset --s3-bucket MY-BUCKET --stack-name MY-STACK --profile PROFILE-IN-CONFIG --region us-east-1  --capabilities CAPABILITY_NAMED_IAM`

**Comment by benkehoe** [comment]
@lmayorga1980 you've got a different issue. Note the error message: `botocore.exceptions.ClientError: An error occurred (ForbiddenException) when calling the GetRoleCredentials operation: No access` SAM is correctly picking up the AWS SSO configuration from `PROFILE-IN-CONFIG`, but either your configuration is correct and you don't have access to the account and role you've configured, or your configuration is incorrect (e.g., a typo in `sso_role_name`)

**Comment by lmayorga1980** [comment]
That worked. wrong `sso_role_name`
