### ISSUE TITLE
Failure to install AWS-SAM-CLI v.1.2.0 on a Amazon Linux 2 instance.

### ISSUE THREAD

**Issue by pcolazurdo** [aws/aws-sam-cli#2217]
### Description

Failure to install AWS-SAM-CLI v.1.2.0 on a Amazon Linux 2 instance.

### Steps to reproduce

I followed https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

```
$ brew install aws-sam-cli
Warning: aws/tap/aws-sam-cli 1.2.0 already installed
$ sam --version --debug
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==1.2.0' distribution was not found and is required by the application
```
### Observed result

Trying to run with --debug gives me the same as above

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Amazon Linux release 2 (Karoo)
2. `sam --version`: 1.2.0
3. HomeBrew: Homebrew 2.5.0 / Homebrew/linuxbrew-core (git revision d52011; last commit 2020-09-12)

**Comment by wchengru** [comment]
Similar issue is also mentioned in #2214 
Force reinstall python3.7 may resolve this: https://github.com/aws/aws-sam-cli/issues/2214#issuecomment-691518624
Root cause of it is under investigation.

**Comment by pcolazurdo** [comment]
Thanks. I can confirm that this workaround worked fine. I'll try to dissect the problem and share my findings

**Comment by brainstorm** [comment]
Seems to be failing with [miniconda](https://docs.conda.io/en/latest/miniconda.html) python environments too:

```
(base) [ec2-user@ip-10-2-5-171 ~]$ sam
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'aws-sam-cli==1.2.0' distribution was not found and is required by the application
(base) [ec2-user@ip-10-2-5-171 ~]$ which python
~/.miniconda3/bin/python
```

**Comment by brainstorm** [comment]
Actually, sorry, none of the python venvs matter because the python interpreter sh-bang is hardcoded to linuxbrew:

```
#!/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.2.0/libexec/bin/python3.7
```

**Comment by mndeveci** [comment]
We just introduced a new binary installer for linux starting from 1.18 version, can you check if that resolves this issue?
Thanks!

**Comment by brainstorm** [comment]
Thanks! Works well for me 👍

**Comment by mndeveci** [comment]
Resolving this now since we have alternative way of installing SAM CLI on linux environment.
Please feel free to re-open this or create a new issue if you are facing some problems for installing SAM CLI on linux.
