### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by sky-lord1** [aws/aws-sam-cli#2257]
OSError: [Errno 36] File name too long

### Description

Not able to download and call the layer locally.

### Steps to reproduce
sam local start-api --docker-network host --profile myprofile --force-image-build

### Observed result

Downloading arn:aws:lambda:us-west-1:xx:layer:xx  [####################################]  11586500/11586500
2020-09-28 12:02:02 Exception on /chat/get-contacts [POST]

`Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/app.py", line 2317, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1840, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1743, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1838, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/flask/app.py", line 1824, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/apigw/local_apigw_service.py", line 203, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/commands/local/lib/local_lambda.py", line 101, in invoke
    self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/runtime.py", line 77, in invoke
    debug_options=debug_context,
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 72, in __init__
    image = LambdaContainer._get_image(image_builder, runtime, layers, debug_options)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_container.py", line 176, in _get_image
    return image_builder.build(runtime, layers, is_debug)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/docker/lambda_image.py", line 101, in build
    downloaded_layers = self.layer_downloader.download_all(layers, self.force_image_build)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/layers/layer_downloader.py", line 72, in download_all
    layer_dirs.append(self.download(layer, force))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/layers/layer_downloader.py", line 111, in download
    progressbar_label="Downloading {}".format(layer.layer_arn),
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/zip.py", line 185, in unzip_from_uri
    unzip(layer_zip_path, unzip_output_dir, permission=0o700)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/zip.py", line 103, in unzip
    extracted_path = _extract(file_info, output_dir, zip_ref)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.3.0/libexec/lib/python3.7/site-packages/samcli/local/lambdafn/zip.py", line 78, in _extract
    os.symlink(source, link_name)
OSError: [Errno 36] File name too long: '#!/usr/bin/env node\n// Standalone semver comparison program.\n// Exits successfully and prints matching version(s)`

### Expected result

Run API without errors. Layer to be available for all lambda function API invocations.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 18.04.5 LTS
2. `sam --version`: version 1.3.0

**Comment by aahung** [comment]
It looks like the exception was thrown from your application (the handler of your `POST /chat/get-contacts`), which is caused by `os.symlink(source, link_name)`, where either `source` or `link_name` is somehow file content rather than the file path.

**Comment by aahung** [comment]
Hope this can help you to pinpoint the problem. Feel free to re-open if you believe it is a sam-cli issue.

**Comment by dkossako** [comment]
I've got the same issue, it looks like aws sam tries to create alias, but instead of taking source file name, it takes its content:

```
$ sam local invoke --layer-cache-basedir /tmp
Invoking index.handler (nodejs14.x)
arn:aws:lambda:us-west-2:397511479707:layer:auth-layer:33 is already cached. Skipping download
arn:aws:lambda:us-west-2:397511479707:layer:api-layer:28 is already cached. Skipping download
Downloading arn:aws:lambda:us-west-2:397511479707:layer:internal-layer  [####################################]  31885718/31885718
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 157, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 83, in cli
    do_cli(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 221, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 90, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers, architecture)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 223, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 130, in build
    downloaded_layers = self.layer_downloader.download_all(layers, self.force_image_build)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 77, in download_all
    layer_dirs.append(self.download(layer, force))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 112, in download
    unzip_from_uri(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 181, in unzip_from_uri
    unzip(layer_zip_path, unzip_output_dir, permission=0o700)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 99, in unzip
    extracted_path = _extract(file_info, output_dir, zip_ref)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 76, in _extract
    os.symlink(source, link_name)
OSError: [Errno 36] File name too long: '#!/usr/bin/env node\n"use strict";\n\nvar log = require("npmlog");\nvar _ = require("lodash");\nvar BuildSystem = require("../").BuildSystem;\nvar util = require("util");\nvar version = require("../package").version;\nvar logLevels = ["silly", "verbose", "info", "http", "warn", "error"];\n\nvar npmConfigData = require("rc")("npm");\nfor (var key of _.keys(npmConfigData)) {\n    if (_.startsWith(key, "cmake_js_")) {\n        var option = key.substr(9);\n        if (option.length === 1) {\n            process.argv.push("-" + option);\n        }\n        else {\n            process.argv.push("--" + option);\n        }\n        if (npmConfigData[key]) {\n            process.argv.push(npmConfigData[key]);\n        }\n    }\n}\n\nconsole.log(process.argv);\n\nvar yargs = require("yargs")\n    .usage("CMake.js " + version + "\\n\\nUsage: $0 [<command>] [options]")\n    .version(function () {\n        return version;\n    })\n    .command("install", "Install Node.js/io.js distribution files if needed")\n    .command("configure", "Configure CMake project")\n    .command("print-configure", "Print the configuration command")\n    .command("build", "Build the project (will configure first if required)")\n    .command("print-build", "Print the build command")\n    .command("clean", "Clean the project directory")\n    .command("print-clean", "Print the clean command")\n    .command("reconfigure", "Clean the project directory then configure the project")\n    .command("rebuild", "Clean the project directory then build the project")\n    .command("compile", "Build the project, and if build fails, try a full rebuild")\n    .options({\n        h: {\n            alias: "help",\n            demand: false,\n            describe: "show this screen",\n            type: "boolean"\n        },\n        l: {\n            alias: "log-level",\n            demand: false,\n            describe: "set log level (" + logLevels.join(", ") + "), default is info",\n            type: "string"\n        },\n        d: {\n            alias: "directory",\n            demand: false,\n            describe: "specify CMake project\'s directory (where CMakeLists.txt located)",\n            type: "string"\n        },\n        D: {\n            alias: "debug",\n            demand: false,\n            describe: "build debug configuration",\n            type: "boolean"\n        },\n        c: {\n            alias: "cmake-path",\n            demand: false,\n            describe: "path of CMake executable",\n            type: "string"\n        },\n        m: {\n            alias: "prefer-make",\n            demand: false,\n            describe: "use Unix Makefiles even if Ninja is available (Posix)",\n            type: "boolean"\n        },\n        x: {\n            alias: "prefer-xcode",\n            demand: false,\n            describe: "use Xcode instead of Unix Makefiles",\n            type: "boolean"\n        },\n        g: {\n            alias: "prefer-gnu",\n            demand: false,\n            describe: "use GNU compiler instead of default CMake compiler, if available (Posix)",\n            type: "boolean"\n        },\n        G: {\n            alias: "generator",\n            demand: false,\n            describe: "use specified generator",\n            type: "string"\n        },\n        t: {\n            alias: "toolset",\n            demand: false,\n            describe: "use specified toolset",\n            type: "string"\n        },\n        A: {\n            alias: "platform",\n            demand: false,\n            describe: "use specified platform name",\n            type: "string"\n        },\n        T: {\n            alias: "target",\n            demand: false,\n            describe: "only build the specified target",\n            type: "string"\n        },\n        C: {\n            alias: "prefer-clang",\n            demand: false,\n            describe: "use Clang compiler instead of default CMake compiler, if available (Posix)",\n            type: "boolean"\n        },\n        cc: {\n            demand: false,\n            describe: "use the specified C compiler",\n            type: "string"\n        },\n        cxx: {\n            demand: false,\n            describe: "use the specified C++ compiler",\n            type: "string"\n        },\n        r: {\n            alias: "runtime",\n            demand: false,\n            describe: "the runtime to use",\n            type: "string"\n        },\n        v: {\n            alias: "runtime-version",\n            demand: false,\n            describe: "the runtime version to use",\n            type: "string"\n        },\n        a: {\n            alias: "arch",\n            demand: false,\n            describe: "the architecture to build in",\n            type: "string"\n        },\n        "CD": {\n            demand: false,\n            describe: "Custom argument passed to CMake in format: -D<your-arg-here>",\n            type: "string"\n        },\n        i: {\n            alias: "silent",\n            describe: "Prevents CMake.js to print to the stdio",\n            type: "boolean"\n        },\n        O: {\n          alias: "out",\n          describe: "Specify the output directory to compile to, default is projectRoot/build",\n          type: "string"\n        }\n    });\nvar argv = yargs.argv;\n\n// If help, then print and exit:\n\nif (argv.h) {\n    console.info(yargs.help());\n    process.exit(0);\n}\n\n// Setup log level:\n\nif (argv.l && _.includes(logLevels, argv.l)) {\n    log.level = argv.l;\n    log.resume();\n}\n\nlog.silly("CON", "argv:");\nlog.silly("CON", util.inspect(argv));\n\nlog.verbose("CON", "Parsing arguments");\n\n// Extract custom cMake options\nvar customOptions = {};\n_.keys(argv).forEach(function (key) {\n    if (argv[key] && _.startsWith(key, "CD")) {\n        customOptions[key.substr(2)] = argv[key];\n    }\n});\n\nvar options = {\n    directory: argv.directory || null,\n    debug: argv.debug,\n    cmakePath: argv.c || null,\n    generator: argv.G,\n    toolset: argv.t,\n    platform: argv.A,\n    target: argv.T,\n    preferMake: argv.m,\n    preferXcode: argv.x,\n    preferGnu: argv.g,\n    preferClang: argv.C,\n    cCompilerPath: argv.cc,\n    cppCompilerPath: argv.cxx,\n    runtime: argv.r,\n    runtimeVersion: argv.v,\n    arch: argv.a,\n    cMakeOptions: customOptions,\n    silent: argv.i,\n    out: argv.O\n};\n\nlog.verbose("CON", "options:");\nlog.verbose("CON", util.inspect(options));\n\nvar command = _.first(argv._) || "build";\n\nlog.verbose("CON", "Running command: " + command);\n\nvar buildSystem = new BuildSystem(options);\n\nfunction ifCommand(c, f) {\n    if (c === command) {\n        f();\n        return true;\n    }\n    return false;\n}\n\nfunction exitOnError(promise) {\n    promise.catch(function () {\n        process.exit(1);\n    });\n}\n\nfunction install() {\n    exitOnError(buildSystem.install());\n}\nfunction configure() {\n    exitOnError(buildSystem.configure());\n}\nfunction printConfigure() {\n    exitOnError(buildSystem.getConfigureCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction build() {\n    exitOnError(buildSystem.build());\n}\nfunction printBuild() {\n    exitOnError(buildSystem.getBuildCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction clean() {\n    exitOnError(buildSystem.clean());\n}\nfunction printClean() {\n    exitOnError(buildSystem.getCleanCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction reconfigure() {\n    exitOnError(buildSystem.reconfigure());\n}\nfunction rebuild() {\n    exitOnError(buildSystem.rebuild());\n}\nfunction compile() {\n    exitOnError(buildSystem.compile());\n}\n\nvar done = ifCommand("install", install);\ndone = done || ifCommand("configure", configure);\ndone = done || ifCommand("print-configure", printConfigure);\ndone = done || ifCommand("build", build);\ndone = done || ifCommand("print-build", printBuild);\ndone = done || ifCommand("clean", clean);\ndone = done || ifCommand("print-clean", printClean);\ndone = done || ifCommand("reconfigure", reconfigure);\ndone = done || ifCommand("rebuild", rebuild);\ndone = done || ifCommand("compile", compile);\n\nif (!done) {\n    if (command) {\n        log.error("COM", "Unknown command: " + command);\n        process.exit(1);\n    }\n    else {\n        build();\n    }\n}\n' -> '/tmp/internal-layer-26-cb6d0eae23/nodejs/node_modules/.bin/cmake-js'
```
