### ISSUE TITLE
pip builder failing to build layer

### ISSUE THREAD

**Issue by jbpratt** [aws/aws-sam-cli#2268]
### Description

Revisiting an old project for maintanence, it seems it is failing to build the layer but I can't determine the cause. This may simply be an issue with my set up, but I do not believe I am having this issue else where (as of yesterday)

### Steps to reproduce
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources:
  SharedDepLayer:
    Type: "AWS::Serverless::LayerVersion"
    Metadata:
      BuildMethod: python3.8
    Properties:
      CompatibleRuntimes:
        - python3.8
      ContentUri: shared/
      Description: dependency
      LayerName: shared

  CancelFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: cancel/
      Role: !GetAtt LambdaExecRole.Arn

  CreateFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: create/
      Role: !GetAtt LambdaExecRole.Arn
```

```
 >sam build --template-file "template.cfn.yaml"
Building function 'CancelFunction'
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
Building function 'CreateFunction'
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
Building layer 'SharedDepLayer'
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Command errored out with exit status 128: git clone -q https://bitbucket..... /tmp/pip-download-co748v56/.... Check the logs for full command output.

 >sam --version
SAM CLI, version 1.3.2
 >python --version
Python 3.8.5
```

### Observed result

<details>

```

>sam --debug build --debug --template-file "template.cfn.yaml"
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
No Parameters detected in the template
8 resources found in the template
Found Serverless function with name='CancelFunction' and CodeUri='cancel/'
Found Serverless function with name='CreateFunction' and CodeUri='create/'
No Parameters detected in the template
Building function 'CancelFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource succeeded
Building function 'CreateFunction'
Loading workflow module 'aws_lambda_builders.workflows'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource succeeded
Building layer 'SharedDepLayer'
Loading workflow module 'aws_lambda_builders.workflows'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /home/jbpratt/projects/work/x/shared/requirements.txt --dest /tmp/tmptcx9i1h2
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 204, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(scratch_directory, requirements_filepath)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 228, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 310, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 600, in download_all_dependencies
    raise PackageDownloadError(error)
aws_lambda_builders.workflows.python_pip.packager.PackageDownloadError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Command errored out with exit status 128: git clone -q https://bitbucket..... /tmp/pip-download-t2earlpm/.... Check the logs for full command output.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/home/jbpratt/.local/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Command errored out with exit status 128: git clone -q https://bitbucket.... /tmp/pip-download-t2earlpm/.... Check the logs for full command output.


Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 993, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'requestId': '4ace198d-a748-4971-aa77-f7acfc4b7793', 'installationId': '6a175b4b-2582-4383-a90a-915453a15582', 'sessionId': 'a097987f-b80f-4f74-85d2-a4888bec1a1c', 'executionEnvironment': 'CLI', 'pyversion': '3.8.5', 'samcliVersion': '1.3.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Command errored out with exit status 128: git clone -q https://bitbucket.... /tmp/pip-download-t2earlpm/... Check the logs for full command output.
```
</details>

### Expected result

`success :)`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux 5.8.12-arch1-1
2. `sam --version`:
```
 >sam --version
SAM CLI, version 1.3.2
 >python --version
Python 3.8.5
 >pip --version
pip 20.2.3 from /home/jbpratt/.local/lib/python3.8/site-packages/pip (python 3.8)
```

I quickly dug into https://github.com/pypa/pip/issues/5599 but I'm not sure what the fix is exactly. The only other issue I could find similar to this is #1144

**Comment by jbpratt** [comment]
Going to go ahead and close this, I can only reproduce this with one of my projects (even recreating virtual envs)

**Comment by HoiDam** [comment]
dafuq?

**Comment by jbpratt** [comment]
@HoiDam I think I just had a mess of an environment and some things got mixed up. I have no idea how to about about reproducing it.

**Comment by jmcgrath207** [comment]
I had the same error as @jbpratt 
@HoiDam 

```
(venv) [john@xps normalized-log-process]$ sam  build 
Building codeuri: sam/ runtime: python3.8 metadata: {} functions: ['NormalizedLogsLambda']
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Cannot install -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt (line 1) and -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt (line 10) because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```


 When I ran `pip download -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt --dest /tmp/tmp_1pgk9ab` It made more sense since it appears sam supresses the `The conflict is caused by:` part.


## Real error.

```
(venv) [john@xps pipeline]$ pip download -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt --dest /tmp/tmp_1pgk9ab
.....
ERROR: Cannot install -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt (line 1) and -r /home/john/PycharmProjects/pipeline/normalized-log-process/sam/requirements.txt (line 10) because these package versions have conflicting dependencies.

The conflict is caused by:
    aiobotocore 0.12.0 depends on botocore<1.15.16 and >=1.15.3
    boto3 1.14.12 depends on botocore<1.18.0 and >=1.17.12

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

Why this is complaining now is my guess is the new pip version. Cause I haven't changed my requirements.txt for months. However once I fixed the conflicting deps it went away.
