### ISSUE TITLE
Refresh of downloaded docker images broke build

### ISSUE THREAD

**Issue by matlik** [aws/aws-sam-cli#2271]
### Description

It appears that `sam local start-lambda` does not ensure reproducible behavior, and I believe this is due to the use of `amazon/aws-sam-cli-emulation-image-java11:latest` when building the (appropriately versioned) `amazon/aws-sam-cli-emulation-image-java11:rapid-1.1.0` docker image.

Our integrated testing framework executes `sam local start-lambda` using version 1.1.0, and had been working fine for weeks. When developers on Windows cleared their docker images using `docker system prune -a` to reclaim hard drive space, the next execution of the build failed. This issue does not effect developers on Linux.

This may be 2 different issues.

1. Behavior is not reproducible due to use of `latest` 
2. Something changed to break building the `amazon/aws-sam-cli-emulation-image-java11:rapid-X.Y.Z` image on Windows (and docker?)

### Steps to reproduce

We are running `sam local start-lambda` with a Java application inside of a docker container. When on Windows

* Ensure Docker Desktop is installed and listening to on a TCP socket
* Add volume `-v /c/temp:/run/desktop/mnt/host/c/tmp`
* In the container, the TEMPDIR ENV is set to `/run/desktop/mnt/host/c/tmp`
* In the container, the DOCKER_HOST ENV is set to `tcp://host.docker.internal:2375`
* Build using the Git Bash shell, not the WSL Linux instances, as WSL Linux does not mount with deterministically mapped mounts allowing for accurate TEMPDIR mapping of shared files across all "systems" (host machine, SAM docker image, lambda docker image launched by SAM) to have matching paths.

### Observed result

```docker.trip-processor-infrastructure - STDERR: Found one Lambda function with name 'TfpTripProcessorSetupFunction'
docker.trip-processor-infrastructure - STDERR: Invoking com.vnomicscorp.LambdaMethodHandler::handleRequest (java11)
docker.trip-processor-infrastructure - STDERR: Environment variables overrides data is standard format
docker.trip-processor-infrastructure - STDERR: Loading AWS credentials from session with profile 'None'
docker.trip-processor-infrastructure - STDERR: Resolving code path. Cwd=/app/.aws-sam/build, CodeUri=TfpTripProcessorSetupFunction.zip
docker.trip-processor-infrastructure - STDERR: Resolved absolute path to code is /app/.aws-sam/build/TfpTripProcessorSetupFunction.zip
docker.trip-processor-infrastructure - STDERR: Decompressing /app/.aws-sam/build/TfpTripProcessorSetupFunction.zip
docker.trip-processor-infrastructure - STDERR: Image was not found.
docker.trip-processor-infrastructure - STDERR: Building image...2020-10-01 21:10:34 Exception on /2015-03-31/functions/TfpTripProcessorSetupFunction/invocations [POST]
docker.trip-processor-infrastructure - STDERR: Traceback (most recent call last):
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2317, in wsgi_app
docker.trip-processor-infrastructure - STDERR:     response = self.full_dispatch_request()
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1840, in full_dispatch_request
docker.trip-processor-infrastructure - STDERR:     rv = self.handle_user_exception(e)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1743, in handle_user_exception
docker.trip-processor-infrastructure - STDERR:     reraise(exc_type, exc_value, tb)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 36, in reraise
docker.trip-processor-infrastructure - STDERR:     raise value
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1838, in full_dispatch_request
docker.trip-processor-infrastructure - STDERR:     rv = self.dispatch_request()
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1824, in dispatch_request
docker.trip-processor-infrastructure - STDERR:     return self.view_functions[rule.endpoint](**req.view_args)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/lambda_service/local_lambda_invoke_service.py", line 151, in _invoke_request_handler
docker.trip-processor-infrastructure - STDERR:     self.lambda_runner.invoke(function_name, request_data, stdout=stdout_stream_writer, stderr=self.stderr)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 100, in invoke
docker.trip-processor-infrastructure - STDERR:     self.local_runtime.invoke(config, event, debug_context=self.debug_context, stdout=stdout, stderr=stderr)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 69, in invoke
docker.trip-processor-infrastructure - STDERR:     container = LambdaContainer(
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 72, in __init__
docker.trip-processor-infrastructure - STDERR:     image = LambdaContainer._get_image(image_builder, runtime, layers, debug_options)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 176, in _get_image
docker.trip-processor-infrastructure - STDERR:     return image_builder.build(runtime, layers, is_debug)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 125, in build
docker.trip-processor-infrastructure - STDERR:     self._build_image(base_image, image_tag, downloaded_layers, is_debug_go, stream=stream_writer)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 202, in _build_image
docker.trip-processor-infrastructure - STDERR:     resp_stream = self.docker_client.api.build(
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/docker/api/build.py", line 263, in build
docker.trip-processor-infrastructure - STDERR:     response = self._post(
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 46, in inner
docker.trip-processor-infrastructure - STDERR:     return f(self, *args, **kwargs)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 226, in _post
docker.trip-processor-infrastructure - STDERR:     return self.post(url, **self._set_request_timeout(kwargs))
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 578, in post
docker.trip-processor-infrastructure - STDERR:     return self.request('POST', url, data=data, json=json, **kwargs)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 516, in request
docker.trip-processor-infrastructure - STDERR:     prep = self.prepare_request(req)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 449, in prepare_request
docker.trip-processor-infrastructure - STDERR:     p.prepare(
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 317, in prepare
docker.trip-processor-infrastructure - STDERR:     self.prepare_body(data, files, json)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 477, in prepare_body
docker.trip-processor-infrastructure - STDERR:     length = super_len(data)
docker.trip-processor-infrastructure - STDERR:   File "/usr/local/lib/python3.8/site-packages/requests/utils.py", line 124, in super_len
docker.trip-processor-infrastructure - STDERR:     total_length = os.fstat(fileno).st_size
docker.trip-processor-infrastructure - STDERR: FileNotFoundError: [Errno 2] No such file or directory
docker.trip-processor-infrastructure - STDERR: 2020-10-01 21:10:34 172.27.0.16 - - [01/Oct/2020 21:10:34] "POST /2015-03-31/functions/TfpTripProcessorSetupFunction/invocations HTTP/1.1" 500 -
```

### Expected result

Building with our SAM CLI version pinned to 1.1.0 should behave the same way today as it did 4 weeks ago (before the release of 1.2.0) even when re-creating the available list of docker containers cached in the local docker repository.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows with Docker Desktop 2.3.0.4 configured to use WSL and TCP connection to docker host
2. `sam --version`: SAM CLI, version 1.1.0

### Work-around

We found that we can `docker save...` and `docker load...` the `amazon/aws-sam-cli-emulation-image-java11:rapid-X.Y.Z` image from a functioning Linux build into a windows machine and bring our automated tests back into working order.

**Comment by matlik** [comment]
Please note that upgrading to use the latest version of the SAM CLI, currently 1.4.0, does not resolve this issue. I am speculating that the breaking change for us was introduced with 1.2.0, and it broke 1.1.0 as well.

**Comment by sriram-mv** [comment]
Closing this issue as it is over 2 years old and we don't see this behavior on the latest AWS SAM CLI versions. Please re-open if that is the case.
