### ISSUE TITLE
Fn::FindInMap stopped working on sam-cli 1.6.2

### ISSUE THREAD

**Issue by ivieira** [aws/aws-sam-cli#2293]
### Description

The sam cli throws an exception when run `sam build`.
### Steps to reproduce

1. Use parameters, mapping and FindInMap in template.yaml
```AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

Globals:
  Function:
    Timeout: 20

Parameters:
  Env:
    Type: String
    AllowedValues:
      - Dev
      - Hml
      - Prd

Mappings:
  Name:
    Dev:
      HelloWorld: HelloWorld_Dev
    Hml:
      HelloWorld: HelloWorld_Hml
    Prd:
      HelloWorld: HelloWorld_Prd

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java11
      MemorySize: 512
      FunctionName: !FindInMap [Name, !Ref Env, HelloWorld]
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```
2. Run `sam build --debug`

### Observed result

```
❯ sam build --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Collected default values for parameters: {}
Unable to resolve property FunctionName: {'Fn::FindInMap': ['Name', {'Ref': 'Env'}, 'HelloWorld']}. Leaving as is.
Unable to resolve property Value: {'Fn::GetAtt': ['HelloWorldFunction', 'Arn']}. Leaving as is.
2 resources found in the template
Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
Collected default values for parameters: {}
Unable to resolve property FunctionName: {'Fn::FindInMap': ['Name', {'Ref': 'Env'}, 'HelloWorld']}. Leaving as is.
Unable to resolve property Value: {'Fn::GetAtt': ['HelloWorldFunction', 'Arn']}. Leaving as is.
Instantiating build definitions
Same build definition found, adding function (Previous: BuildDefinition(java11, HelloWorldFunction, 8e937d8c-2bdb-4413-9100-a1c3331b76a0, {}, []), Current: BuildDefinition(java11, HelloWorldFunction, 40014e94-34a7-4ce2-aa98-649c359b37bf, {}, []), Function: Function(name='HelloWorldFunction', functionname={'Fn::FindInMap': ['Name', {'Ref': 'Env'}, 'HelloWorld']}, runtime='java11', memory=512, timeout=20, handler='helloworld.App::handleRequest', codeuri='HelloWorldFunction', environment={'Variables': {'PARAM1': 'VALUE'}}, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata=None))
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 90, 'exitReason': 'ValueError', 'exitCode': 255, 'requestId': 'b0d1c26d-c5e6-4e2d-bf3b-6be2c6bbfd2f', 'installationId': '0fcc8de8-1135-4b43-afd3-fd3737254594', 'sessionId': '39e1065a-d7b0-4428-989c-5c0494ff0883', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.6.2', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 120, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 198, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 117, in build
    result = self._build_functions()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 149, in _build_functions
    build_graph = self._get_build_graph()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 142, in _get_build_graph
    build_graph.clean_redundant_functions_and_update(not self._is_building_specific_resource)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 110, in clean_redundant_functions_and_update
    self._write()
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 142, in _write
    build_definition_as_table = _build_definition_to_toml_table(build_definition)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/samcli/lib/build/build_graph.py", line 38, in _build_definition_to_toml_table
    toml_table[FUNCTIONS_FIELD] = \
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/tomlkit/items.py", line 1012, in __setitem__
    value = item(value)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/tomlkit/items.py", line 62, in item
    i = item(_v)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/tomlkit/items.py", line 70, in item
    a.append(v)
  File "/usr/local/Cellar/aws-sam-cli/1.6.2/libexec/lib/python3.8/site-packages/tomlkit/items.py", line 805, in append
    raise ValueError("Array has mixed types elements")
ValueError: Array has mixed types elements
```

### Expected result

I'm expecting a build successful message

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Catalina 10.15.7
2. `sam --version`: SAM CLI, version 1.6.2

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
A fix has been released with [SAM CLI v1.7.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.7.0).
