### ISSUE TITLE
sam build --use-container --debug fails to build on windows 10

### ISSUE THREAD

**Issue by marafee1243** [aws/aws-sam-cli#2310]
### Description

I am trying to build sam build on Windows 10. I get the error.

### Steps to reproduce

```
sam build --use-container --debug
```

### Observed result

```
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
3 resources found in the template
Found Serverless function with name='ManagementSystemFunction' and CodeUri='./'
No Parameters detected in the template
Instantiating build definitions
Same build definition found, adding function (Previous: BuildDefinition(nodejs12.x, ./, ac62b5a9-9b98-44c9-aa63-1c467598f5d4, {}, []), Current: BuildDefinition(nodejs12.x, ./, 0015e3ba-40a9-4dda-8eea-18aabced81d4, {}, []), Function: Function(name='ManagementSystemFunction', functionname='ManagementSystem', runtime='nodejs12.x', memory=None, timeout=300, handler='index.handler', codeuri='./', environment=None, rolearn=None, layers=[], events={'MSStatusEvent': {'Type': 'Api', 'Properties': {'Path': '/status', 'Method': 'ANY', 'Cors': {'Origin': '*', 'Headers': '*', 'AllowCredentials': False}, 'RestApiId': 'ServerlessRestApi'}}, 'MSAuthJwtLoginEvent': {'Type': 'Api', 'Properties': {'Path': '/auth/jwt/login', 'Method': 'ANY', 'Cors': {'Origin': '*', 'Headers': '*', 'AllowCredentials': False}, 'RestApiId': 'ServerlessRestApi'}}, 'MSAuthJwtVerifyEvent': {'Type': 'Api', 'Properties': {'Path': '/auth/jwt/verify', 'Method': 'ANY', 'Cors': {'Origin': '*', 'Headers': '*', 'AllowCredentials': False}, 'RestApiId': 'ServerlessRestApi'}}}, metadata=None))
Building codeuri: ./ runtime: nodejs12.x metadata: {} functions: ['ManagementSystemFunction']
Building to following folder C:\Users\XFREEU~1\AppData\Local\Temp\tmpqr0ge173

Fetching amazon/aws-sam-cli-build-image-nodejs12.x Docker container image......
Mounting D:\PROJECTS\abc\management-system as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Running workflow 'NodejsNpmBuilder'
Running NodejsNpmBuilder:NpmPack
NODEJS packaging file:/tmp/samcli/source to /tmp/samcli/scratch
executing NPM: ['npm', 'pack', '-q', 'file:/tmp/samcli/source']
NODEJS packed to managementsystembackendapi-1.0.0.tgz
NODEJS extracting to /tmp/samcli/scratch/unpacked
NodejsNpmBuilder:NpmPack succeeded
Running NodejsNpmBuilder:CopyNpmrc
NodejsNpmBuilder:CopyNpmrc succeeded
Running NodejsNpmBuilder:CopySource
NodejsNpmBuilder:CopySource succeeded
Running NodejsNpmBuilder:NpmInstall
NODEJS installing in: /tmp/samcli/artifacts
executing NPM: ['npm', 'install', '-q', '--no-audit', '--no-save', '--production', '--unsafe-perm']
NodejsNpmBuilder:NpmInstall succeeded
Running NodejsNpmBuilder:CleanUpNpmrc
NodejsNpmBuilder:CleanUpNpmrc succeeded
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
Build inside container was successful. Copying artifacts from container to host
Copying from container: /tmp/samcli/artifacts/. -> C:\Users\XFREEU~1\AppData\Local\Temp\tmpqr0ge173
Build inside container succeeded
Copying artifacts from C:\Users\XFREEU~1\AppData\Local\Temp\tmpqr0ge173 to D:\PROJECTS\abc\management-system\.aws-sam\build\ManagementSystemFunction
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 30354, 'exitReason': 'OSError', 'exitCode': 255, 'requestId': '272a7886-fb56-43f1-bc2e-22cd17bac3ff', 'installationId': '345fc7ce-8b9e-4bd3-836f-783f0b2bceec', 'sessionId': '64de8378-173e-42e5-80f4-5c909d340e95', 'executionEnvironment': 'CLI', 'pyversion': '3.8.6', 'samcliVersion': '1.6.2'}}]}    
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 120, in cli
    do_cli(
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 198, in do_cli
    artifacts = builder.build()
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 117, in build
    result = self._build_functions()
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 169, in _build_functions
    osutils.copytree(temporary_build_dir, artifacts_dir)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 155, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 155, in copytree
    copytree(new_source, new_destination, ignore=ignore)
  File "D:\xPrograms\AWS_SAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 157, in copytree
    shutil.copy2(new_source, new_destination)
  File "shutil.py", line 432, in copy2
  File "shutil.py", line 261, in copyfile
OSError: [Errno 22] Invalid argument: 'C:\\Users\\XFREEU~1\\AppData\\Local\\Temp\\tmpqr0ge173\\node_modules\\.bin\\detect-libc'
```

### Expected result

I think, it should have build without any erros.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.6.2

**Comment by prenx4x** [comment]
can you provide us with the package.json for your application so that we can reproduce this issue?

**Comment by CoshUS** [comment]
Closing.
Feel free to reopen is there is further information or issue.

**Comment by rottama** [comment]
I had the same issue, drove me nuts, seemed to be an intermittent issue, with deferred feedback from config settings, i.e. things would run smoothly, after a reboot the build would suddenly stop working.

Disabled telemetry: 

`setx SAM_CLI_TELEMETRY 0`

and restarted the IDE. Build is working again... for now.

**Comment by NaokiFujikawa** [comment]
> can you provide us with the package.json for your application so that we can reproduce this issue?

It seems to occur when there is a CodeUri with the same value.
detect-lib is sym-link file. 
It seems there is a problem with symlink copy.

[hello-world.zip](https://github.com/aws/aws-sam-cli/files/6667795/hello-world.zip)

**Comment by ksmoore17** [comment]
Same issue occurs with python virtual environments (`venv/bin/python` is a symlink). It would be nice to be able to list specific paths to include/exclude.

```
Build Failed
Running CustomMakeBuilder:CopySource
Error: CustomMakeBuilder:CopySource - [Errno 2] No such file or directory: '/tmp/samcli/source/.venv/bin/python'
```

Same issue as #1755
