### ISSUE TITLE
Unable to call sam deploy without setting --capabilities parameter. No way to set it to no capabilities

### ISSUE THREAD

**Issue by hauboldj** [aws/aws-sam-cli#2332]
### Description
There is no way to use `sam deploy` with out specifying the `--capabilities` parameter. I'm deploying a template without IAM roles or transformations. I also want to prevent future developers from adding IAM roles (this template will be deployed via a CI process).

Similar issue previously raise here: https://github.com/aws/aws-sam-cli/issues/1675

I'm using `sam deploy` (instead of aws cloudformation deploy) in this case to maintain consistency in the CI process between different repos in this project.

### Steps to reproduce

```
sam deploy \
		--template-file artifacts/template.packaged.yaml \
		--stack-name temp-test-stack- \
		--no-fail-on-empty-changeset

	Deploying with following values
	===============================
	Stack name                 : temp-test-stack-
	Region                     : None
	Confirm changeset          : False
	Deployment s3 bucket       : None
	Capabilities               : null
	Parameter overrides        : {}

Initiating deployment
=====================
Error: Failed to create changeset for the stack: temp-test-stack-, Parameter validation failed:
Invalid type for parameter Capabilities, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
```
### Observed result

```
sam deploy \
		--template-file artifacts/template.packaged.yaml \
		--stack-name temp-test-stack- \
		--no-fail-on-empty-changeset \
		--debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
Property Command.ScriptLocation of GlueJobOne resource is not a URL

	Deploying with following values
	===============================
	Stack name                 : temp-test-stack-
	Region                     : None
	Confirm changeset          : False
	Deployment s3 bucket       : None
	Capabilities               : null
	Parameter overrides        : {}

Initiating deployment
=====================
Collected default values for parameters: {'Connection': 'Redshift_dev'}
2 resources found in the template
Unable to create changeset
Traceback (most recent call last):
  File "/Users/jhaubold/.local/pipx/venvs/aws-sam-cli/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 191, in _create_change_set
    resp = self._client.create_change_set(**kwargs)
  File "/Users/jhaubold/.local/pipx/venvs/aws-sam-cli/lib/python3.8/site-packages/botocore/client.py", line 337, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/jhaubold/.local/pipx/venvs/aws-sam-cli/lib/python3.8/site-packages/botocore/client.py", line 628, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/Users/jhaubold/.local/pipx/venvs/aws-sam-cli/lib/python3.8/site-packages/botocore/client.py", line 676, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/Users/jhaubold/.local/pipx/venvs/aws-sam-cli/lib/python3.8/site-packages/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid type for parameter Capabilities, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 1119, 'exitReason': 'ChangeSetError', 'exitCode': 1, 'requestId': 'f2b90bae-f2cc-4ec3-8d6a-3afc88aace34', 'installationId': '29c26046-4bba-4617-868e-69cb0355ae81', 'sessionId': '51978bcb-3869-408a-952e-456cc9a5072a', 'executionEnvironment': 'CLI', 'pyversion': '3.8.1', 'samcliVersion': '1.6.2'}}]}
HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create changeset for the stack: temp-test-stack-, Parameter validation failed:
Invalid type for parameter Capabilities, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
```
### Expected result
I expect to be able to deploy a stack with no capabilities set.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS
2.
```
$ sam --version
SAM CLI, version 1.6.2
```

**Comment by adamwshero** [comment]
I will post this here since I ran into this discussion trying to solve for it and so someone may also find this helpful. If you instead run
aws cloudformation deploy --stack-name my-stack-name --template-file my_template.yaml --s3-bucket my_bucket --s3-prefix my_prefix

AWS CLI will actually tell you which capability you need. In my case, I needed both CAPABILITY_AUTO_EXPAND and CAPABILITY_IAM. Then you can go back and package your template with SAM and run the following SAM Build command

sam deploy --template-file my_teamplate.yaml --s3-bucket my_bucket --stack-name my_stack_name --capabilities CAPABILITY_AUTO_EXPAND CAPABILITY_IAM

Cheers,
Adam
