### ISSUE TITLE
sam deploy --guided without running build first crashes for Image based apps

### ISSUE THREAD

**Issue by sriram-mv** [aws/aws-sam-cli#2437]
### Description:

running `sam deploy --guided` without `sam build` causes a crash, as the deploy guided is looking for an non existent resource to get a valid image repository for. 

### Steps to reproduce:
sam init
sam deploy --guided

### Observed result:

```

Configuring SAM deploy
======================

	Looking for config file [samconfig.toml] :  Not found

	Setting default arguments for 'sam deploy'
	=========================================
	Stack Name [sam-app]:
	AWS Region [us-east-1]:
	Image Repository []: asdfr
Traceback (most recent call last):
  File "/Users/srirammv/workspace/1.13.1_env/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/lib/telemetry/metrics.py", line 100, in wrapped
    return func(*args, **kwargs)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 211, in cli
    config_env,
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/commands/deploy/command.py", line 265, in do_cli
    guided_context.run()
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 300, in run
    self.guided_prompts(_parameter_override_keys)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 113, in guided_prompts
    parameter_overrides=sanitize_parameter_overrides(input_parameter_overrides)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/commands/deploy/guided_context.py", line 277, in prompt_image_repository
    tag = tag_translation(image)
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/lib/package/image_utils.py", line 29, in tag_translation
    if is_ecr_url(image):
  File "/Users/srirammv/workspace/1.13.1_env/lib/python3.7/site-packages/samcli/lib/package/utils.py", line 45, in is_ecr_url
    re.match("(^[a-zA-Z0-9][a-zA-Z0-9-_]*).dkr.ecr.([a-zA-Z0-9][a-zA-Z0-9-_]*).amazonaws.com(.cn)?/.*", url)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/re.py", line 175, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
```

### Expected result:

sam deploy --guided should not crash

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac Os
2. `sam --version`: 1.13

**Comment by mndeveci** [comment]
This has been released with [v1.14](https://github.com/aws/aws-sam-cli/releases/tag/v1.14.0)
