### ISSUE TITLE
Adding LambdaInsightsExtension results in timeout with 'sam local invoke'

### ISSUE THREAD

**Issue by mvanbaak** [aws/aws-sam-cli#2469]
### Description:

After following the steps about enabling lambda insights, local execution of the lambda functions is no longer possible.
As soon as one adds the Layer to the template, the functions time out. Removing the layer makes them work again.

### Steps to reproduce:

Add the following to either the function, or the Globals->Function part of the template:
```yaml
Layers:
  - Fn::Sub: "arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:12"
```

### Observed result:

```
2020-12-09 18:18:40,546 | Resolving code path. Cwd=/Users/mvanbaak/dev/x/backend-api/.aws-sam/build, CodeUri=YEventsFunction
2020-12-09 18:18:40,547 | Resolved absolute path to code is /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction
2020-12-09 18:18:40,547 | Code /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction is not a zip/jar file
2020-12-09 18:18:40,547 | arn:aws:lambda:eu-central-1:580247275435:layer:LambdaInsightsExtension:12 is already cached. Skipping download
2020-12-09 18:18:40,585 | Requested to skip pulling images ...

2020-12-09 18:18:40,585 | Mounting /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction as /var/task:ro,delegated inside runtime container
2020-12-09 18:18:41,054 | Starting a timer for 20 seconds for function 'YEventsFunction'
START RequestId: c3840afc-5659-4b27-9300-2d2f5001cf58 Version: $LATEST
[INFO]  2020-12-09T17:18:47.465Z                initializing xray middleware

2020-12-09 18:18:51,055 | Function 'YEventsFunction' timed out after 20 seconds
2020-12-09 18:18:51,814 | Container was not created. Skipping deletion
2020-12-09 18:18:51,814 | No response from invoke container for YEventsFunction
Done.
```

### Expected result:

```

2020-12-09 18:26:44,594 | Resolving code path. Cwd=/Users/mvanbaak/dev/x/backend-api/.aws-sam/build, CodeUri=YEventsFunction
2020-12-09 18:26:44,594 | Resolved absolute path to code is /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction
2020-12-09 18:26:44,594 | Code /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction is not a zip/jar file
2020-12-09 18:26:44,630 | Requested to skip pulling images ...

2020-12-09 18:26:44,631 | Mounting /Users/mvanbaak/dev/x/backend-api/.aws-sam/build/YEventsFunction as /var/task:ro,delegated inside runtime container
2020-12-09 18:26:45,083 | Starting a timer for 20 seconds for function 'YEventsFunction'
START RequestId: 5dbc8420-3405-4a54-a32f-59667f370e64 Version: $LATEST
[INFO]  2020-12-09T17:26:51.164Z                initializing xray middleware

... lambda function debug output ...

END RequestId: 5dbc8420-3405-4a54-a32f-59667f370e64
REPORT RequestId: 5dbc8420-3405-4a54-a32f-59667f370e64  Init Duration: 0.30 ms  Duration: 10545.23 ms   Billed Duration: 10600 ms       Memory Size: 192 MB     Max Memory Used: 192 MB
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: mac os 11.0.1 (20B29)
2. `sam --version`: SAM CLI, version 1.13.1

`Add --debug flag to command you are running`

**Comment by TLaue** [comment]
I am seeing the same issue. I have to deactivate this layer in order to run my lambda function locally.

**Comment by ulfbrehmer** [comment]
Same here. Breaks local dev loop. If not fixed, we will have to choose between having lambda insights and being able to develop locally.

**Comment by sapessi** [comment]
Thanks for raising this issue. We are investigating and will update this issue as soon as we have news. Are you interested in testing the data gathering or would it be ok if the function executed correctly and no (Insights) data was collected from the local execution?

**Comment by mvanbaak** [comment]
Personally, I dont need data collection of local executions. Just being able to test locally without having to disable the lambda layer would be a win :)

**Comment by jaredcnance** [comment]
A new version of the Lambda Insights Extension has been released which should resolve this issue: `arn:aws:lambda:<region>:580247275435:layer:LambdaInsightsExtension:14`.

**Comment by sapessi** [comment]
Closing this issue since the new version of the extension image addresses the problem.

**Comment by mvanbaak** [comment]
Just to confirm this fixed the problem on our end yes. Thanks a lot.

**Comment by iRoachie** [comment]
Hey question @sapessi, this seems to fail using `sam local start-api`. Tried with both layer versions 14 and 16.

```bash
START RequestId: 20d47312-ce5f-4bfb-9e3d-9df2ee5e43d4 Version: $LATEST
thread 'meter_probe' panicked at 'Unable to read /proc for agent process: InternalError(bug at /local/p4clients/pkgbuild-DbvKa/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.119.0/AL2012/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-895cc363aacb953e/procfs-0.7.9/src/process/stat.rs:300 (please report this procfs bug)
Internal Unwrap Error: Internal error: bug at /local/p4clients/pkgbuild-DbvKa/workspace/build/AWSLogsLambdaInsights/AWSLogsLambdaInsights-1.0.119.0/AL2012/DEV.STD.PTHREAD/build/private/cargo-home/registry/src/-895cc363aacb953e/procfs-0.7.9/src/lib.rs:285 (please report this procfs bug)
Internal Unwrap Error: NoneError)', src/inputs/memory.rs:59:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'attempt to divide by zero', src/inputs/memory.rs:44:32
END RequestId: 20d47312-ce5f-4bfb-9e3d-9df2ee5e43d4
```

**Comment by frenayj** [comment]
Got the same as @iRoachie on an M1 Apple Silicon

**Comment by frenayj** [comment]
I'd be interested to know if you found a workaround @iRoachie as this seems to still be a problem with version 16.

**Comment by iRoachie** [comment]
Yes, i did find a workaround.

For starters, I have an Environment parameter in my template (I do this all the time not just for workaround):

```yaml
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
```

I then create a Condition:

```yaml
Conditions:
  UseLambdaInsights: !Or
    - !Equals [!Ref Environment, staging]
    - !Equals [!Ref Environment, prod]
```

Having both of these I use the condition to include the layer or not:

```yaml
Globals:
  Function:
    Runtime: nodejs14.x
    Architectures:
      - x86_64
    Timeout: 10
    Handler: index.handler
    Layers:
      - !If [
          UseLambdaInsights,
          'arn:aws:lambda:us-east-1:580247275435:layer:LambdaInsightsExtension:16',
          !Ref AWS::NoValue,
        ]
```
