### ISSUE TITLE
"sam package --use-json" throws TypeError if `AWSTemplateFormatVersion` value is not in quotes.

### ISSUE THREAD

**Issue by brysontyrrell** [aws/aws-sam-cli#2476]
### Description:

This is a default behavior of PyYAML.

If the template format version is defined as:

```yaml
AWSTemplateFormatVersion: 2010-09-09
```

And we attempt to use the `--use-json` option of `sam package`:

```text
TypeError: Object of type date is not JSON serializable
```

PyYAML loads it as a date object. The workaround is to wrap the value in quotes:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
```

I've tested a fix that overrides the constructor for timestamps to strings.

```python
# samcli/yamlhelper.py

import yaml
import yaml.constructor
from yaml.resolver import ScalarNode, SequenceNode

TAG_STR = "tag:yaml.org,2002:str"

yaml.constructor.SafeConstructor.yaml_constructors['tag:yaml.org,2002:timestamp'] = \
    yaml.constructor.SafeConstructor.yaml_constructors[TAG_STR]
```

I can open a PR if this seems like a valid solution.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.0
2. `sam --version`: 1.13.2

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
I can reproduce this issue using the following steps
- initiate any new project using `sam init`
- Update the template to be something like the following
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.7
```
(`AWSTemplateFormatVersion: 2010-09-09`) is a valid YAML format
- run `sam package --use-json --resolve-s3`
```
% sam package --resolve-s3

	Looking for resources needed for deployment: Found!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-iucm54o5o7dc
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-iucm54o5o7dc/cde64eac299c9ccdc66ce13145f47e1c
      Handler: app.lambda_handler
      Runtime: python3.7

melasmar@8c8590b3cc8a sam-app % sam package --use-json --resolve-s3

	Looking for resources needed for deployment: Found!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-iucm54o5o7dc
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.15.0', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/cli_validation/image_repository_validation.py", line 76, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 63, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/package/command.py", line 156, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/package/command.py", line 216, in do_cli
    package_context.run()
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/package/package_context.py", line 120, in run
    exported_str = self._export(self.template_file, self.use_json)
  File "/usr/local/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/package/package_context.py", line 138, in _export
    exported_str = json.dumps(exported_template, indent=4, ensure_ascii=False)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 431, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type date is not JSON serializable
```
Although if we removed the option `--use-json` it will run successfully
```
% sam package --resolve-s3 

	Looking for resources needed for deployment: Found!

		Managed S3 bucket: aws-sam-cli-managed-default-samclisourcebucket-iucm54o5o7dc
		A different default S3 bucket can be set in samconfig.toml
		Or by specifying --s3-bucket explicitly.
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://aws-sam-cli-managed-default-samclisourcebucket-iucm54o5o7dc/cde64eac299c9ccdc66ce13145f47e1c
      Handler: app.lambda_handler
      Runtime: python3.7
```

**Comment by moelasmar** [comment]
Thanks @ brysontyrrell for raising this issue, feel free to raise a PR to fix it.

**Comment by spalladino** [comment]
Starting with the latest SAM version (1.37.0), we've started seeing this error from plain `sam deploy` commands (without the `use-json` option). In our case, the date field causing issues was the `Version` identifier from `PolicyDocument`, and wrapping it in quotes solved the issue.

**Comment by sriram-mv** [comment]
Tracking in https://github.com/aws/aws-sam-cli/issues/4735, closing this issue.
