### ISSUE TITLE
Receiving Docker TLSParameterError in WSL

### ISSUE THREAD

**Issue by rupe120** [aws/aws-sam-cli#2553]
### Description:
I'm suddenly receiving `docker.errors.TLSParameterError: If using TLS, the base_url argument must be provided.` errors when I try to do anything with SAM in Ubuntu under Windows 10 WSL 2. 

I upgraded to 1.15.0 but that didn't help

### Steps to reproduce:
Run any command

### Observed result:
2021-01-26 11:08:25,760 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-01-26 11:08:25,866 | 'build' command is called
2021-01-26 11:08:25,900 | Collected default values for parameters: {'Environment': 'dev'}
2021-01-26 11:08:25,952 | Unable to resolve property TERMS_TO_CRAWL_QUEUE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:TermsToCrawlQueueRef'})]). Leaving as is.
2021-01-26 11:08:25,952 | Unable to resolve property JOB_STATE_TABLE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorJobStateTableName'})]). Leaving as is.
2021-01-26 11:08:25,952 | Unable to resolve property ORCHESTRAION_CONFIG_TABLE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorConfigTableName'})]). Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property ECS_CLUSTER_NAME: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ClusterName'})]). Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property ECS_SERVICE_NAME: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ServiceName'})]). Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property Resource: {'Fn::Join': ['', [OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorJobStateTableArn'})]), '*']]}. Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property Resource: {'Fn::Join': ['', [OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorConfigTableArn'})]), '*']]}. Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property Resource: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:TermsToCrawlQueueArn'})]). Leaving as is.
2021-01-26 11:08:25,953 | Unable to resolve property Resource: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ServiceRef'})]). Leaving as is.
2021-01-26 11:08:25,954 | 9 resources found in the template
2021-01-26 11:08:25,954 | Found Serverless function with name='SearchManagerFunction' and CodeUri='search_manager/'
2021-01-26 11:08:25,954 | Collected default values for parameters: {'Environment': 'dev'}
2021-01-26 11:08:25,996 | Unable to resolve property TERMS_TO_CRAWL_QUEUE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:TermsToCrawlQueueRef'})]). Leaving as is.
2021-01-26 11:08:25,997 | Unable to resolve property JOB_STATE_TABLE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorJobStateTableName'})]). Leaving as is.
2021-01-26 11:08:25,997 | Unable to resolve property ORCHESTRAION_CONFIG_TABLE: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorConfigTableName'})]). Leaving as is.
2021-01-26 11:08:25,997 | Unable to resolve property ECS_CLUSTER_NAME: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ClusterName'})]). Leaving as is.
2021-01-26 11:08:25,997 | Unable to resolve property ECS_SERVICE_NAME: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ServiceName'})]). Leaving as is.
2021-01-26 11:08:25,998 | Unable to resolve property Resource: {'Fn::Join': ['', [OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorJobStateTableArn'})]), '*']]}. Leaving as is.
2021-01-26 11:08:25,998 | Unable to resolve property Resource: {'Fn::Join': ['', [OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:SearchOrchestratorConfigTableArn'})]), '*']]}. Leaving as is.
2021-01-26 11:08:25,998 | Unable to resolve property Resource: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${SharedStackName}:TermsToCrawlQueueArn'})]). Leaving as is.
2021-01-26 11:08:25,998 | Unable to resolve property Resource: OrderedDict([('Fn::ImportValue', {'Fn::Sub': '${FargateStackName}:ServiceRef'})]). Leaving as is.
2021-01-26 11:08:26,016 | Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 255, 'exitReason': 'TLSParameterError', 'exitCode': 255, 'requestId': '40d04cab-d5bf-4d39-92c5-0bdd20604581', 'installationId': '622e15ae-40b9-4320-9dc8-9c1ddd8ac61d', 'sessionId': 'f1596416-7381-4649-b5c7-c9cd5171f295', 'executionEnvironment': 'CLI', 'pyversion': '3.8.7', 'samcliVersion': '1.15.0'}}]}
2021-01-26 11:08:26,408 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.15.0', 'console_scripts', 'sam')())
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 148, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 114, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 155, in cli
    do_cli(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 229, in do_cli
    builder = ApplicationBuilder(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 98, in __init__
    self._docker_client = docker_client if docker_client else docker.from_env()
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/docker/client.py", line 84, in from_env
    return cls(
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/docker/client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.15.0/libexec/lib/python3.8/site-packages/docker/api/client.py", line 109, in __init__
    raise TLSParameterError(
docker.errors.TLSParameterError: If using TLS, the base_url argument must be provided.. TLS configurations should map the Docker CLI client configurations. See https://docs.docker.com/engine/articles/https/ for API details.

### Expected result:
A successful SAM build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows Version	10.0.18363 Build 18363
2. WSL:   NAME                   STATE           VERSION
* Ubuntu-20.04           Running         2
  docker-desktop         Running         2
  docker-desktop-data    Running         2
3. `sam --version`: SAM CLI, version 1.15.0

`Add --debug flag to command you are running`

**Comment by rupe120** [comment]
Apparently an update to Windows Docker Desktop disabled the WSL integration. I had to flip the switch back on again. Though that didn't immediately resolve the issue, after an apt-get update and upgrade everything is running normally again
