### ISSUE TITLE
VSCode cannot debug nodejs12 based lambda function due to wrong NODE_PATH in image

### ISSUE THREAD

**Issue by huanghe73** [aws/aws-sam-cli#2573]
### Description:

Use VSCode to debug a nodejs12 based lambda function, while installing `aws-sdk` as `devDependencies` instead of `dependencies`. Error is `asws-sdk` not found. Actually `aws-sdk` shall be part of lambda docker image.

### Steps to reproduce:

1. A clean AWS SAM installation. No image has been built. Or use `docker rmi <aws lambda local image name>` to remove all built images.
2. Create a sam project using `sam init`
3. Open with VSCode
4. Create a `launch.json` file with `AWS SAM: Debug Lambda Function Locally`
5. Edit `app.js` to add below code to the first line:
  ```javascript
  const AWS = require('aws-sdk');
  ```
6. Run VSCode debugger

### Observed result:

Error:

```
Debugger attached.
2021-01-30T16:35:58.426Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'aws-sdk'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'aws-sdk'","Require stack:","- /var/task/app.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:996:14)","    at Object..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}
```

This issue is caused by below code:

`/home/linuxbrew/.linuxbrew/Cellar/aws-sam-cli/1.16.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_debug_settings.py`

Line 103 and line 116:
```Javascript
"NODE_PATH": "/opt/nodejs/node_modules:/opt/nodejs/node10/node_modules:/var/runtime/node_module",
```

`var/runtime/node_module` shall be `var/runtime/node_modules`. There is an 's' at the end.

### Expected result:

Debug shall be good.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 WSL2 Ubuntu
2. `sam --version`: 1.16.0

**Comment by aahung** [comment]
@huanghe73 Thanks for reporting this and your investigation!
