### ISSUE TITLE
local start-api unable to parse RouteKey of Websocket function 

### ISSUE THREAD

**Issue by sgbasaraner** [aws/aws-sam-cli#2610]
### Description:

sam local start-api throws a ValueError since it tries to parse its RouteKey as regular http api as far as I can understand.

### Steps to reproduce:

Add a websocket api to template.yaml

### Observed result:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 33, in <module>
    sys.exit(load_entry_point('aws-sam-cli==1.17.0', 'console_scripts', 'sam')())
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/commands/local/start_api/cli.py", line 86, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/commands/local/start_api/cli.py", line 173, in do_cli
    service = LocalApiService(lambda_invoke_context=invoke_context, port=port, host=host, static_dir=static_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_api_service.py", line 37, in __init__
    self.api_provider = ApiProvider(
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/api_provider.py", line 41, in __init__
    self.api = self._extract_api(self.resources)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/api_provider.py", line 70, in _extract_api
    provider.extract_resources(resources, collector, cwd=self.cwd)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/cfn_api_provider.py", line 69, in extract_resources
    self._extract_cfn_gateway_v2_route(resources, logical_id, resource, collector)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/cfn_api_provider.py", line 263, in _extract_cfn_gateway_v2_route
    method, path = self._parse_route_key(route_key)
  File "/usr/local/Cellar/aws-sam-cli/1.17.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/cfn_api_provider.py", line 422, in _parse_route_key
    [method, path] = route_key.split()
ValueError: not enough values to unpack (expected 2, got 1)

### Expected result:

Start the local api.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Catalina
2. `sam --version`: SAM CLI, version 1.17.0
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by sriram-mv** [comment]
@sgbasaraner could you share your template?

**Comment by sgbasaraner** [comment]
If I comment out the parts between ### CHAT-START and ### CHAT-END `sam local start-api` works. `sam deploy` works either way. So far I tried 3 sam versions (1.17.0, 1.13.2 and 1.18.1), only 1.13.2 can run this template without this problem.

@sriram-mv here the template is, as far as I can understand it tries to parse websocket api route keys like '$disconnect'. I hope that helps.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zapi
  
  Sample SAM Template for zapi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Runtime: go1.x

Parameters:
  DomainName:
    Type: String
    Default: api.denemeapp.com
  HostedZoneName:
    Type: String
    Default: denemeapp.com. # don't miss the  dot at the end

  
Resources:
  # Queues
  ZAnalyticsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      QueueName: "zanalytics-queue.fifo"
      VisibilityTimeout: 300
  # Network resources
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.1.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value:  !Join ['', [!Ref "AWS::StackName", "-VPC" ]]
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    # Notice how you can't attach an IGW to a VPC unless both are created:
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.10.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list       
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-A
  PublicSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.20.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Public-B
  PrivateSubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.50.0/24
      AvailabilityZone: !Select [ 0, !GetAZs ]    # Get the first AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-A
  PrivateSubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.60.0/24
      AvailabilityZone: !Select [ 1, !GetAZs ]    # Get the second AZ in the list 
      Tags:
      - Key: Name
        Value: !Sub ${AWS::StackName}-Private-B
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Public
  PublicRoute1:   # Public route table has direct routing to IGW:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: Private
  PrivateRoute1:            # Private route table can access web via NAT (created below)
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      # Route traffic through the NAT Gateway:
      NatGatewayId: !Ref NATGateway
  NATGateway:
   Type: AWS::EC2::NatGateway
   Properties:
     AllocationId: !GetAtt ElasticIPAddress.AllocationId
     SubnetId: !Ref PublicSubnetA
     Tags:
     - Key: Name
       Value: !Sub NAT-${AWS::StackName}
  ElasticIPAddress:
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
  # Attach the public subnets to public route tables,
  # and attach the private subnets to private route tables:   
  PublicSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetA
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnetB
      RouteTableId: !Ref PublicRouteTable
  PrivateSubnetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetA
      RouteTableId: !Ref PrivateRouteTable
  PrivateSubnetBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnetB
      RouteTableId: !Ref PrivateRouteTable
### CHAT-START 
  ChatWebSocketApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: ChatWebSocketApi
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  RequestAuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/chatauth
      Handler: chatauth
      Policies:
        - AWSLambdaFullAccess
        - CloudWatchLogsFullAccess
  RequestAuthorizer:
    Type: "AWS::ApiGatewayV2::Authorizer"
    Properties:
      Name: RequestAuthorizer
      ApiId: !Ref ChatWebSocketApi
      AuthorizerType: REQUEST
      AuthorizerUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestAuthorizerFunction.Arn}/invocations
      IdentitySource:
        - "route.request.header.authorization"
  RequestAuthorizerFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ChatWebSocketApi
      - RequestAuthorizerFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref RequestAuthorizerFunction
      Principal: apigateway.amazonaws.com
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $connect
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref RequestAuthorizer
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ConnectInteg
  ConnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnConnectFunction.Arn}/invocations
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: $disconnect
      AuthorizationType: NONE
      OperationName: DisconnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref DisconnectInteg
  DisconnectInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      Description: Disconnect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${OnDisconnectFunction.Arn}/invocations
  SendRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref ChatWebSocketApi
      RouteKey: sendmessage
      AuthorizationType: NONE
      OperationName: SendRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref SendInteg
  SendInteg:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref ChatWebSocketApi
      Description: Send Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessageFunction.Arn}/invocations
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - SendRoute
    - DisconnectRoute
    Properties:
      ApiId: !Ref ChatWebSocketApi
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref ChatWebSocketApi
### CHAT-END
  # Aliasing to wsapi.denemeapp.com
  WebSocketApiDomainName:
    Type: AWS::ApiGatewayV2::DomainName
    Properties: 
      DomainName: 'wsapi.denemeapp.com'
      DomainNameConfigurations: 
        - EndpointType: 'REGIONAL'
          CertificateArn: arn:aws:acm:eu-west-1:887035379092:certificate/7f3db6d2-1abf-44e8-9b61-2407c370b1d7
  WebSocketMapping:
    Type: AWS::ApiGatewayV2::ApiMapping
    Properties: 
      ApiId: !Ref ChatWebSocketApi
      DomainName: !Ref WebSocketApiDomainName
      Stage: 'Prod'
  DNSRecord:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneName: !Ref HostedZoneName
        TTL: '900'
        ResourceRecords:
          - !GetAtt [ WebSocketApiDomainName, RegionalDomainName ]
        Name: 'wsapi.denemeapp.com'
        Type: CNAME
  UserConnectionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "UserID"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "UserID"
        KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      SSESpecification:
        SSEEnabled: True
      TableName: "user_connections"
  OnConnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/onconnect
      Handler: onconnect
      Environment:
        Variables:
          TABLE_NAME: "user_connections"
      Policies:
      - DynamoDBCrudPolicy:
          TableName: "user_connections"
  OnConnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ChatWebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnConnectFunction
      Principal: apigateway.amazonaws.com
  OnDisconnectFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/ondisconnect
      Handler: ondisconnect
      Environment:
        Variables:
          TABLE_NAME: "user_connections"
      Policies:
      - DynamoDBCrudPolicy:
          TableName: "user_connections"
  OnDisconnectPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ChatWebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref OnDisconnectFunction
      Principal: apigateway.amazonaws.com
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/sendmessage
      Handler: sendmessage
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Environment:
        Variables:
          TABLE_NAME: "user_connections"
          SOCKETID: !Ref ChatWebSocketApi
      Policies:
      - DynamoDBCrudPolicy:
          TableName: "user_connections"
      - Statement:
        - Effect: Allow
          Action:
          - 'execute-api:ManageConnections'
          Resource:
          - !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ChatWebSocketApi}/*'
  SendMessagePermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - ChatWebSocketApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref SendMessageFunction
      Principal: apigateway.amazonaws.com

  # API Declaration
  Zapi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: LambdaTokenAuthorizer
        Authorizers:
          LambdaTokenAuthorizer:
            FunctionPayloadType: TOKEN
            FunctionArn: !GetAtt AuthorizerFunction.Arn
            Identity:
              Header: Authorization
              ValidationExpression: ^Bearer [-0-9a-zA-z\.]*$
  # Aliasing to api.denemeapp.com
  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: arn:aws:acm:us-east-1:887035379092:certificate/e2d6dd2f-1ee5-4022-868f-f6aa4b6f5b64
      DomainName: !Ref DomainName

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref Zapi
      Stage: Prod

  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt APIDomainName.DistributionDomainName
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
  # API Functions
  PinFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/pin
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: pin
      Events:
        GetPins:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin
            Method: GET
        GetSinglePin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}
            Method: GET
        DeletePin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}
            Method: DELETE
        CreatePin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/
            Method: PUT
        AnswerPin:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/answer
            Method: POST
  ProfileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/profile
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: profile
      Events:
        GetTopProfiles:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /user
            Method: GET
        GetUserPosts:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /user/{userId}/posts
            Method: GET
        GetProfileInfo:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /user/{userId}/profile
            Method: GET
        UpdateProfileInfo:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /user/{userId}/profile
            Method: POST
  LikeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/like
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: like
      Events:
        GetCommentLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /comment/{commentId}/like
            Method: GET
        CreateCommentLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /comment/{commentId}/like
            Method: PUT
        DeleteCommentLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /comment/{commentId}/like/
            Method: DELETE
        GetPinLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/like
            Method: GET
        CreatePinLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/like
            Method: PUT
        DeletePinLike:
          Type: Api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/like/
            Method: DELETE
  CommentFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/comment
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: comment
      Events:
        GetComment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment
            Method: GET
        GetChildren:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment/{commentId}
            Method: GET
        UpdateComment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment/{commentId}
            Method: POST
        DeleteComment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment/{commentId}
            Method: DELETE
        CreateComment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment
            Method: PUT
        CreateChildComment:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /pin/{pinId}/comment/{commentId}
            Method: PUT
  # HTTP API for messages, not websocket
  FetchMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/fetchmessage
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: fetchmessage
      Events:
        FetchConversations:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /conversations
            Method: GET
        FetchMessages:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /messages/{conversationId}
            Method: GET
  UserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/user
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: user
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Auth:
              Authorizer: 'NONE'
            Path: /user
            Method: PUT
  LoginFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/login
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: login
      Events:
        StartSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Auth:
              Authorizer: 'NONE'
            Path: /login
            Method: POST
        RefreshSession:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Auth:
              Authorizer: 'NONE'
            Path: /login/refresh
            Method: POST
  UploadRequestFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: core/cmd/upload
      Handler: upload
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Timeout: 3
      Environment:
        Variables:
          UploadBucket: "cf-cdn-bucket"
      Policies:
        - S3WritePolicy:
            BucketName: "cf-cdn-bucket"
      Events:
        GetUploadURL:
            Type: Api
            Properties:
              RestApiId: !Ref Zapi
              Path: /uploadURL
              Method: POST
  EmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - SESCrudPolicy:
            IdentityName: denemeapp.com
      CodeUri: core/cmd/email
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: email
      Events:
        ValidateEmail:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Auth:
              Authorizer: 'NONE'
            Path: /email/validate/{email}/{code}
            Method: GET
        RequestValidation:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /email/validate
            Method: POST
  AuthorizerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/auth
      Handler: auth
  # Function to read analytics queue
  AnalyticsProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/analyticsprocessor
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: analyticsprocessor
      Events:
        MySQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ZAnalyticsQueue.Arn
            BatchSize: 9 # TODO: increase/experiment with batch size
  SearchFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/search
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: search
      Events:
        SearchEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /search
            Method: GET
  TagFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: core/cmd/tag
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: tag
      Events:
        GetTags:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            RestApiId: !Ref Zapi
            Path: /hashtag
            Method: GET
  EngagementUpdater:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: core/cmd/engagementupdater
      VpcConfig:
        SecurityGroupIds:
          - !GetAtt VPC.DefaultSecurityGroup
        SubnetIds:
          - !Ref PrivateSubnetA
          - !Ref PrivateSubnetB
      Handler: engagementupdater
      Events:
        UpdateEngagementsScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(2 minutes) # TODO: decrease/experiment with frequency

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ZAPI:
    Description: "API"
    Value: !Ref Zapi
  DropPhotoFunctionAPI:
    Description: "API Gateway endpoint URL for Prod environment for DropPhotoFunction"
    Value: !Sub "https://${Zapi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  VPC:
    Description: VPC of the base network
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC
  WebSocketURI:
    Description: "The WSS Protocol URI to connect to"
    Value: !Join [ '', [ 'wss://', !Ref ChatWebSocketApi, '.execute-api.',!Ref 'AWS::Region','.amazonaws.com/',!Ref 'Stage'] ]

```

**Comment by stevenyap** [comment]
I have the same exact issue too.

```
  # does not work
  RouteConnect:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - IntegrationConnect
    Properties:
      ApiId: !Ref WebsocketGateway
      RouteKey: $connect
      AuthorizationType: NONE
      Target: !Sub 'integrations/${IntegrationConnect}'

  # works but can't deploy
  RouteConnect:
    Type: AWS::ApiGatewayV2::Route
    DependsOn:
      - IntegrationConnect
    Properties:
      ApiId: !Ref WebsocketGateway
      RouteKey: 'POST /connect'
      AuthorizationType: NONE
      Target: !Sub 'integrations/${IntegrationConnect}'
```

**Comment by sgbasaraner** [comment]
@sriram-mv  can we remove blocked tag from this?

**Comment by xiaohk** [comment]
Have the same issue here... Any suggestions?

**Comment by xiaohk** [comment]
I just found out that sam-cli does not support testing Websocket locally
https://github.com/aws/aws-sam-cli/issues/896
