### ISSUE TITLE
aws_lambda_builders not intcluded in 1.18.0 native linux installer

### ISSUE THREAD

**Issue by CoSeeWolf** [aws/aws-sam-cli#2614]
### Description:
`sam build` fails on version 1.18.0 that has been installed using native linux installer with the following error:
```
Build Failed
Error: JavaGradleWorkflow:GradleBuild - [Errno 2] No such file or directory: '/usr/local/aws-sam-cli/1.18.0/dist/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle'
```

### Steps to reproduce:
Download the latest [SAM CLI zip](https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip)  and install it on an Ubuntu 20.04 using the install shell script. Notice that `sam --version` works fine and delivers `SAM CLI, version 1.18.0`.

Then try to build any lambda (in my case a trivial Hello-World Java lambda).

### Observed result:

Checking the dist directory under `/usr/local/aws-sam-cli/1.18.0/dist` shows only these directories:
```
.
├── boto3
├── botocore
├── certifi
├── importlib_metadata-1.6.0-py3.7.egg-info
├── include
├── jsonschema
├── jsonschema-3.2.0-py3.7.egg-info
├── lib
├── markupsafe
├── pytz
├── regex
├── samcli
├── samtranslator
├── _struct
├── text_unidecode
└── zlib

```
Also, `find /usr/local/aws-sam-cli/1.18.0 -iname *builders*` does not yield any results.

Detailed output:
```
user@machine:~/git/[...]/.aws-sam$ sam build --template temp-template.yaml --debug
2021-02-11 10:40:12,490 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-02-11 10:40:12,575 | 'build' command is called
2021-02-11 10:40:12,577 | No Parameters detected in the template
2021-02-11 10:40:12,596 | 1 resources found in the template
2021-02-11 10:40:12,596 | Found Serverless function with name='Function' and CodeUri='[...]'
2021-02-11 10:40:12,596 | No Parameters detected in the template
2021-02-11 10:40:12,615 | Instantiating build definitions
2021-02-11 10:40:12,617 | Same function build definition found, adding function (Previous: BuildDefinition(java11, [...], Zip, , eaa4e8fe-575c-4aac-bca8-fe104cc3aaad, {}, []), Current: BuildDefinition(java11, [...], Zip, , a976a6d7-7615-4a9d-b51c-5f10e9866151, {}, []), Function: Function(name='Function', functionname='Function', runtime='java11', memory=128, timeout=300, handler='some.package.TestLambda', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='[...]', environment=None, rolearn=None, layers=[], events=None, metadata=None, inlinecode=None, codesign_config_arn=None))
2021-02-11 10:40:12,618 | Building codeuri: [...] runtime: java11 metadata: {} functions: ['Function']
2021-02-11 10:40:12,618 | Building to following folder [...]/.aws-sam/.aws-sam/build/Function
2021-02-11 10:40:12,618 | Looking for a supported build workflow in following directories: ['[...]', '[...]']
2021-02-11 10:40:12,619 | Loading workflow module 'aws_lambda_builders.workflows'
2021-02-11 10:40:12,621 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-02-11 10:40:12,623 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-02-11 10:40:12,623 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-02-11 10:40:12,624 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-02-11 10:40:12,625 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-02-11 10:40:12,626 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-02-11 10:40:12,627 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-02-11 10:40:12,628 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-02-11 10:40:12,629 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-02-11 10:40:12,629 | Found workflow 'JavaGradleWorkflow' to support capabilities 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-02-11 10:40:13,104 | Running workflow 'JavaGradleWorkflow'
2021-02-11 10:40:13,105 | Running JavaGradleWorkflow:GradleBuild
2021-02-11 10:40:13,105 | JavaGradleWorkflow:GradleBuild failed
Traceback (most recent call last):
  File "aws_lambda_builders/workflows/java_gradle/actions.py", line 39, in _copy_init_script
  File "aws_lambda_builders/workflows/java_gradle/utils.py", line 25, in copy
  File "shutil.py", line 266, in copy2
  File "shutil.py", line 120, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/aws-sam-cli/1.18.0/dist/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 269, in run
  File "aws_lambda_builders/workflows/java_gradle/actions.py", line 28, in execute
  File "aws_lambda_builders/workflows/java_gradle/actions.py", line 41, in _copy_init_script
aws_lambda_builders.actions.ActionFailedError: [Errno 2] No such file or directory: '/usr/local/aws-sam-cli/1.18.0/dist/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle'

Build Failed
2021-02-11 10:40:13,109 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'a9af0b93-03ec-4fef-93b8-b1c90a99a099', 'installationId': '41de99ac-c102-4b20-9d1e-3891e197eb4a', 'sessionId': '05bcfa01-b5e7-4a31-92bd-18d807b21df7', 'executionEnvironment': 'CLI', 'pyversion': '3.7.9', 'samcliVersion': '1.18.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 616, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2021-02-11 10:40:13,731 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: JavaGradleWorkflow:GradleBuild - [Errno 2] No such file or directory: '/usr/local/aws-sam-cli/1.18.0/dist/aws_lambda_builders/workflows/java_gradle/resources/lambda-build-init.gradle'

```

### Expected result:
Files for the registered workflows should be included in `dist` directory.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubtunu 20.4
2. `sam --version`: 1.18.0
3. AWS region: eu-west-1

**Comment by CoshUS** [comment]
Addressed in SAM CLI 1.18.1 patch release.
