### ISSUE TITLE
M2Crypto Fails to Install When Building Python 3.8

### ISSUE THREAD

**Issue by alliefitter** [aws/aws-sam-cli#2701]
### Description:
M2Crypto fails to install using `sam build --use-container`. The issue seems to be a missing (or possibly outdated. I can't tell as `--debug` doesn't log output from pip) OS dependency for `openssl-devel` or possibly one of its dependencies. Building the dockerfile below with `docker build . -t amazon/aws-sam-cli-build-image-python3.8:latest`, and then running `sam build --use-container --skip-pull-image` does install M2Crypto successfully. Also, note that it also fails to install when specifying Python 3.7 and 3.6 as requested in [this comment](https://github.com/aws/aws-sam-cli/issues/2118#issuecomment-683148115)
``` 
FROM amazon/aws-sam-cli-build-image-python3.8:latest

RUN yum install openssl-devel -y

ENTRYPOINT ["/lambda-entrypoint.sh"]
```

I've seen in other issues that y'all are reluctant to allow users to specify their own build image, but that would seem to be simplest solution to this problem. 

### Steps to reproduce:
Create the below files and run `sam build --use-container`

template.yml
```
Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: test.run
      CodeUri: .
      Runtime: python3.8
```

test.py
```
def run(event, context):
    print('Foooooooo')

```

requirements.txt
```
M2Crypto
```

### Observed result:
```
$ sam build --use-container --debug
Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
'build' command is called
Starting Build inside a container
No Parameters detected in the template
1 resources found in the template
Found Serverless function with name='Function' and CodeUri='.'
No Parameters detected in the template
Building function 'Function'

Fetching amazon/aws-sam-cli-build-image-python3.8 Docker container image......
Mounting /home/afitter/PycharmProjects/mdm/block/apple-device-management/scheduled-tasks-worker as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {m2crypto==0.37.1(sdist), parameterized==0.8.1(wheel)}
initial compatible: {parameterized==0.8.1(wheel)}
initial incompatible: {m2crypto==0.37.1(sdist)}
Downloading missing wheels: {m2crypto==0.37.1(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch m2crypto==0.37.1
compatible wheels after second download pass: {parameterized==0.8.1(wheel)}
Build missing wheels from sdists (C compiling True): {m2crypto==0.37.1(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.37.1.tar.gz
compatible after building wheels (no C compiling): {parameterized==0.8.1(wheel)}
Build missing wheels from sdists (C compiling False): {m2crypto==0.37.1(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.37.1.tar.gz
compatible after building wheels (C compiling): {parameterized==0.8.1(wheel)}
Final compatible: {parameterized==0.8.1(wheel)}
Final incompatible: set()
Final missing wheels: {m2crypto==0.37.1(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.37.1(sdist)}
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}
Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}"}}

Build Failed
Sending Telemetry: {'metrics': [{'commandRun': {'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 6381, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'requestId': '1c2eabae-192a-46f0-b706-84fb43965766', 'installationId': '32536af7-e4a1-4794-bab4-8524ff851412', 'sessionId': 'da02fb30-072c-4d4b-bb38-b06a0b538d8f', 'executionEnvironment': 'CLI', 'pyversion': '3.8.5', 'samcliVersion': '1.3.2'}}]}
Telemetry response: 200
Error: PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}
```

### Expected result:
M2Crypto should successfully install.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. `sam --version`: SAM CLI, version 1.3.2
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by alliefitter** [comment]
I noticed when trying to fix some problems in PyCharm that my version sam was really out of date. Updated it to 1.20.0 and was still able to reproduce the issue.
```
$ sam --version
SAM CLI, version 1.20.0
$ sam build --use-container --debug
2021-03-11 15:06:11,004 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-03-11 15:06:11,045 | 'build' command is called
2021-03-11 15:06:11,045 | Starting Build inside a container
2021-03-11 15:06:11,046 | No Parameters detected in the template
2021-03-11 15:06:11,067 | 1 stacks found in the template
2021-03-11 15:06:11,067 | No Parameters detected in the template
2021-03-11 15:06:11,086 | 1 resources found in the stack 
2021-03-11 15:06:11,086 | No Parameters detected in the template
2021-03-11 15:06:11,103 | No Parameters detected in the template
2021-03-11 15:06:11,120 | Found Serverless function with name='Function' and CodeUri='.'
2021-03-11 15:06:11,120 | No Parameters detected in the template
2021-03-11 15:06:11,139 | Instantiating build definitions
2021-03-11 15:06:11,141 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, ., Zip, , c533d5f9-de15-4f3e-b470-4ba5fbdce0ec, {}, {}, []), Current: BuildDefinition(python3.8, ., Zip, , 7144721b-e1fe-43fd-adfe-3a899f2120ec, {}, {}, []), Function: Function(name='Function', functionname='Function', runtime='python3.8', memory=128, timeout=300, handler='test.run', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='.', environment=None, rolearn=None, layers=[], events=None, metadata=None, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-03-11 15:06:11,142 | Building codeuri: . runtime: python3.8 metadata: {} functions: ['Function']
2021-03-11 15:06:11,142 | Building to following folder /tmp/.aws-sam/build/Function

Fetching amazon/aws-sam-cli-build-image-python3.8 Docker container image......
2021-03-11 15:06:11,968 | Mounting /tmp as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {m2crypto==0.37.1(sdist), parameterized==0.8.1(wheel)}
initial compatible: {parameterized==0.8.1(wheel)}
initial incompatible: {m2crypto==0.37.1(sdist)}
Downloading missing wheels: {m2crypto==0.37.1(sdist)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch m2crypto==0.37.1
compatible wheels after second download pass: {parameterized==0.8.1(wheel)}
Build missing wheels from sdists (C compiling True): {m2crypto==0.37.1(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.37.1.tar.gz
compatible after building wheels (no C compiling): {parameterized==0.8.1(wheel)}
Build missing wheels from sdists (C compiling False): {m2crypto==0.37.1(sdist)}
calling pip wheel --no-deps --wheel-dir /tmp/samcli/scratch /tmp/samcli/scratch/M2Crypto-0.37.1.tar.gz
compatible after building wheels (C compiling): {parameterized==0.8.1(wheel)}
Final compatible: {parameterized==0.8.1(wheel)}
Final incompatible: set()
Final missing wheels: {m2crypto==0.37.1(sdist)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.37.1(sdist)}
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {m2crypto==0.37.1(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}
2021-03-11 15:06:16,800 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}"}}

Build Failed
2021-03-11 15:06:17,055 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '48f71d78-ae8e-4ff4-b2c1-62104a07935a', 'installationId': '32536af7-e4a1-4794-bab4-8524ff851412', 'sessionId': 'e93bb638-20db-45a9-8dc4-b65a5ff2a0fb', 'executionEnvironment': 'CLI', 'pyversion': '3.7.10', 'samcliVersion': '1.20.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 6050, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2021-03-11 15:06:17,376 | Telemetry response: 200
Error: PythonPipBuilder:ResolveDependencies - {m2crypto==0.37.1(sdist)}
```

**Comment by wchengru** [comment]
We are supporting customized build image from 1.22.0:
`sam build --use-container --build-image {your image}`
Please refer to:  https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html
