### ISSUE TITLE
Template with conditional nested stacks fails to build

### ISSUE THREAD

**Issue by sbutler** [aws/aws-sam-cli#2752]
### Description:

A SAM template with a conditional nested stack will fail to build, with an error message similar to `IsADirectoryError: [Errno 21] Is a directory: '/Users/myuser/Desktop/sam-app'`

### Steps to reproduce:

Create a new SAM App:

```
$ sam init
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1
What package type would you like to use?
	1 - Zip (artifact is a zip uploaded to S3)	
	2 - Image (artifact is an image uploaded to an ECR image repository)
Package type: 1

Which runtime would you like to use?
	1 - nodejs14.x
	2 - python3.8
	3 - ruby2.7
	4 - go1.x
	5 - java11
	6 - dotnetcore3.1
	7 - nodejs12.x
	8 - nodejs10.x
	9 - python3.7
	10 - python3.6
	11 - python2.7
	12 - ruby2.5
	13 - java8.al2
	14 - java8
	15 - dotnetcore2.1
Runtime: 2

Project name [sam-app]: 

Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates

AWS quick start application templates:
	1 - Hello World Example
	2 - EventBridge Hello World
	3 - EventBridge App from scratch (100+ Event Schemas)
	4 - Step Functions Sample App (Stock Trader)
	5 - Elastic File System Sample App
Template selection: 1
```

Then modify the template.yaml file:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app

Parameters:
  MyTemplateURL:
    Type: String
    Default: ""

Conditions:
  HasMyTemplate: !Not [ !Equals [ !Ref MyTemplateURL, "" ] ]

Resources:
  MyTemplate:
    Type: AWS::CloudFormation::Stack
    Condition: HasMyTemplate
    Properties:
      Parameters:
        Foo: 1
      TemplateURL: !Ref MyTemplateURL
```

Then run `sam build`.

### Observed result:

```
$ sam build --debug
2021-03-22 15:03:02,524 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-03-22 15:03:02,524 | Using config file: samconfig.toml, config environment: default
2021-03-22 15:03:02,524 | Expand command line arguments to:
2021-03-22 15:03:02,524 | --template_file=/Users/myuser/Desktop/sam-app/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2021-03-22 15:03:02,573 | 'build' command is called
2021-03-22 15:03:02,576 | Collected default values for parameters: {'MyTemplateURL': ''}
2021-03-22 15:03:02,596 | 1 stacks found in the template
2021-03-22 15:03:02,596 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'bf16823d-fe25-4a8b-9b57-b9d92ded2c3b', 'installationId': 'c9d431ee-5729-431b-80bd-43229e1b585c', 'sessionId': '83ccaa4c-cf7c-4643-a881-0fbe42d26f98', 'executionEnvironment': 'CLI', 'pyversion': '3.8.8', 'samcliVersion': '1.21.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 71, 'exitReason': 'IsADirectoryError', 'exitCode': 255}}]}
2021-03-22 15:03:02,900 | Telemetry response: 200
Traceback (most recent call last):
  File "/Users/myuser/.local/aws/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/commands/build/command.py", line 190, in cli
    do_cli(
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/commands/build/command.py", line 254, in do_cli
    with BuildContext(
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 76, in __enter__
    self._stacks, remote_stack_full_paths = SamLocalStackProvider.get_stacks(
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 230, in get_stacks
    current = SamLocalStackProvider(
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 64, in __init__
    self._extract_stacks()
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 116, in _extract_stacks
    stack = SamLocalStackProvider._convert_cfn_stack_resource(
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 182, in _convert_cfn_stack_resource
    template_dict=get_template_data(template_url),
  File "/Users/myuser/.local/aws/lib/python3.8/site-packages/samcli/commands/_utils/template.py", line 48, in get_template_data
    with open(template_file, "r", encoding="utf-8") as fp:
IsADirectoryError: [Errno 21] Is a directory: '/Users/myuser/Desktop/sam-app'
```

### Expected result:

The app to ignore the conditional template and build.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.2.3
2. SAM CLI, version 1.21.1
3. AWS region: us-east-2

**Comment by sbutler** [comment]
I've temporarily worked around the issue by doing this in my template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: sam-app

Parameters:
  MyTemplateURL:
    Type: String
    Default: "https://example.org/template.yaml"

Conditions:
  HasMyTemplate: !Not [ !Equals [ !Ref MyTemplateURL, "https://example.org/template.yaml" ] ]

Resources:
  MyTemplate:
    Type: AWS::CloudFormation::Stack
    Condition: HasMyTemplate
    Properties:
      Parameters:
        Foo: 1
      TemplateURL: !Ref MyTemplateURL
```

SAM's non-support for remote templates causes it to skip the nested stack, and CloudFormation itself properly handles the condition.

**Comment by aahung** [comment]
#1079

**Comment by mndeveci** [comment]
Resolving this for the sake of duplicate issue here: https://github.com/aws/aws-sam-cli/issues/1079
