### ISSUE TITLE
Sam build failed after Boto3 upgrade 1.17.37

### ISSUE THREAD

**Issue by HAK-CODE** [aws/aws-sam-cli#2767]
### Description:
Sam build starting to fail after upgrade Boto3 version from 1.17.36 --> 1.17.37 

### Steps to reproduce:
1. Create a SAM application using python3.8 and add boto3==1.17.37 in requirements.txt
2. run sam build --debug

### Observed result:
```
2021-03-26 03:00:46,562 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-03-26 03:00:46,587 | Running workflow 'PythonPipBuilder'
2021-03-26 03:00:46,588 | Running PythonPipBuilder:ResolveDependencies
2021-03-26 03:00:46,615 | calling pip download -r /home/hak/Desktop/iot-services/event-parser-iot-core/src/requirements.txt --dest /tmp/tmpzz2s_8_2
2021-03-26 03:00:52,829 | PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 269, in run
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 204, in build_site_packages
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 228, in _download_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 311, in _download_all_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 311, in <setcomp>
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 417, in __init__
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 459, in _calculate_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 519, in get_package_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 502, in _generate_egg_info
IndexError: list index out of range

Build Failed
```

### Expected result:
Build should succeed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux, Ubuntu 20.04.2 LTS
2. `sam --version`: 1.21.1
3. AWS region: Ohio

**Comment by HAK-CODE** [comment]
https://github.com/boto/boto3/issues/2802

**Comment by moelasmar** [comment]
I was not able to reproduce the issue

I tested the following steps:
```
$ sam init --name test --runtime python3.8 --dependency-manager pip --app-template hello-world
$ cd test
$ echo $'requests\nboto3==1.17.36' > hello_world/requirements.txt
2021-03-28 22:08:23,148 | Final incompatible: set()
2021-03-28 22:08:23,148 | Final missing wheels: set()
2021-03-28 22:08:23,897 | PythonPipBuilder:ResolveDependencies succeeded
2021-03-28 22:08:23,898 | Running PythonPipBuilder:CopySource
2021-03-28 22:08:23,905 | PythonPipBuilder:CopySource succeeded
.....
Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

$ echo $'requests\nboto3==1.17.37' > hello_world/requirements.txt 
$ sam build --debug
.....
2021-03-28 22:09:39,067 | Final incompatible: set()
2021-03-28 22:09:39,067 | Final missing wheels: set()
2021-03-28 22:09:39,485 | PythonPipBuilder:ResolveDependencies succeeded
2021-03-28 22:09:39,485 | Running PythonPipBuilder:CopySource
2021-03-28 22:09:39,489 | PythonPipBuilder:CopySource succeeded

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```
environment details:
SAM CLI, version 1.21.1
Ubuntu 18.04.5 LTS
Python 3.8

**Comment by moelasmar** [comment]
could you please try the same steps on a clean project, and let us know the exact steps to reproduce the issue.

**Comment by HAK-CODE** [comment]
So yeah I cleaned the project and rebuild it and it's working fine.
