### ISSUE TITLE
Getting java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by SHxKM** [aws/aws-sam-cli#2798]
### Description:
I'm getting a java.lang.OutOfMemoryError upon running `sam local start-lambda` and `cfn-test`.

### Steps to reproduce:
1. Install 1.22 SAM CLI
2. Run cfn test on a custom resource project in Java 8

### Observed result:

Identifying information obfuscated:

```
Invoking com.comp.product.subproduct.HandlerWrapper::handleRequest (java8)
Decompressing /Users/user/development/repo/comp-product-subproduct/target/comp-product-subproduct-handler-1.0-SNAPSHOT.jar
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-java8:rapid-1.22.0.

Mounting /private/var/folders/gq/57xs6vj148b94dc95gw5m2980000gp/T/tmpuowwvm2n as /var/task:ro,delegated inside runtime container
START RequestId: 52c299e4-a665-4a10-8b51-a00b4dce066a Version: $LATEST
java.lang.OutOfMemoryError: Metaspace
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at org.everit.json.schema.loader.EnumSchemaExtractor.extract(SchemaExtractor.java:175)
        at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
        at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:397)
        at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:361)
        at org.everit.json.schema.loader.SchemaLoader$$Lambda$80/1513712028.apply(Unknown Source)
        at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:435)
        at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:439)
        at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)
        at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)
        at org.everit.json.schema.loader.ObjectSchemaLoader$$Lambda$103/2114889273.apply(Unknown Source)
        at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)
        at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)
        at org.everit.json.schema.loader.JsonObject$$Lambda$104/1504109395.accept(Unknown Source)
        at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
        at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)
        at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)
        at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)
        at org.everit.json.schema.loader.ObjectSchemaLoader$$Lambda$102/1468177767.accept(Unknown Source)
        at java.util.Optional.ifPresent(Optional.java:159)
        at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)
java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
        at software.amazon.cloudformation.LambdaWrapper.writeResponse(LambdaWrapper.java:382)
        at software.amazon.cloudformation.LambdaWrapper.handleRequest(LambdaWrapper.java:240)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

Exception in thread "main" java.lang.Error: java.lang.OutOfMemoryError: Metaspace
        at lambdainternal.AWSLambda.<clinit>(AWSLambda.java:65)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at lambdainternal.LambdaRTEntry.main(LambdaRTEntry.java:150)
Caused by: java.lang.OutOfMemoryError: Metaspace
END RequestId: 52c299e4-a665-4a10-8b51-a00b4dce066a
REPORT RequestId: 52c299e4-a665-4a10-8b51-a00b4dce066a  Init Duration: 0.35 ms  Duration: 6072.06 ms    Billed Duration: 6100 ms        Memory Size: 128 MB     Max Memory Used: 128 MB
2021-04-09 01:17:14 127.0.0.1 - - [09/Apr/2021 01:17:14] "POST /2015-03-31/functions/TypeFunction/invocations HTTP/1.1" 200 -
Invoking com.comp.product.subproduct.HandlerWrapper::handleRequest (java8)
```

### Expected result:
The lambda is run. It runs normally and successfully in production.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 
2. `sam --version`: 1.22
3. AWS region: us-east-1

**Comment by aahung** [comment]
> Memory Size: 128 MB     Max Memory Used: 128 MB

It could be caused by function's MemorySize is too small or there is a memory leak in your function's code. Try to increase the "MemorySize" and re-open if it doesn't solve the problem.
