### ISSUE TITLE
vscode interactive lambda debug for target="code" assumes incorrect Logical id

### ISSUE THREAD

**Issue by richbon75** [aws/aws-sam-cli#2830]
### Description:
When trying to launch a lambda function in a debug session in VSCode when using the `target="code"` configuration, sam seems to be incorrectly applying the Logical Id naming convention rules to the projectRoot folder name, throwing error "Logical ids must be alphanumeric" if the projectRoot folder name contains underscores (a common Python naming convention), even though the projectRoot folder is *not* the function's Logical Id.

Running `sam build`, `sam local invoke`, or `sam deploy` at the command line for this project does *not* throw this error and completes successfully.

This definitely seems like new behavior.  I have a whole repo of lambda functions that I can no longer launch locally in a debugger in their current configuration.

### Steps to reproduce:

project directory contents:
```
.vscode/
  launch.json
say_hello/
  __init__.py        <--- empty file
  app.py
  requirements.txt   <--- empty file
template.yaml
```

**_say_hello/app.py_**
```
def lambda_handler(event, context):
    name = event.get('name', 'World')
    return {"message": f"Hello {name}!"}
```

**_template.yaml_**
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A demonstration

Globals:
  Function:
    Runtime: python3.8

Resources:

  sayHello:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: say_hello
      Description: Demonstration
      CodeUri: say_hello/
      Handler: app.lambda_handler
```

**_.vscode/launch.json_**
```
{
  "configurations": [
    {
      "type": "aws-sam",
      "request": "direct-invoke",
      "name": "sambug:sayHello",
      "invokeTarget": {
        "target": "code",
        "projectRoot": "say_hello",
        "lambdaHandler": "app.lambda_handler"
      },
      "lambda": {
        "runtime": "python3.8",
        "payload": {
          "json": {
            "name": "Alice"
          }
        },
        "environmentVariables": {}
      }
    }
  ]
}
```

### Observed result:

Attempting to launch the above debug configuration results in this output:

```
2021-04-26 13:09:47 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
2021-04-26 13:09:47 [INFO]: Building SAM application...
2021-04-26 13:09:47 [INFO]: Running command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkh06oCX/output --template /Users/richbon/Documents/coding/sambug/say_hello/app___vsctk___template.yaml --base-dir /Users/richbon/Documents/coding/sambug/say_hello --manifest /tmp/aws-toolkit-vscode/vsctkh06oCX/debug-requirements.txt]
2021-04-26 13:09:48 [INFO]: Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 78, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 147, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('say_hello', 'Logical ids must be alphanumeric.')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 152, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 121, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 190, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 254, in do_cli
    with BuildContext(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 76, in __enter__
    self._stacks, remote_stack_full_paths = SamLocalStackProvider.get_stacks(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 230, in get_stacks
    current = SamLocalStackProvider(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 51, in __init__
    self._template_dict = self.get_template(
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_base_provider.py", line 171, in get_template
    template_dict = SamTranslatorWrapper(template_dict, parameter_values=parameters_values).run_plugins()
  File "/usr/local/Cellar/aws-sam-cli/1.21.1/libexec/lib/python3.8/site-packages/samcli/lib/samlib/wrapper.py", line 80, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('say_hello', 'Logical ids must be alphanumeric.')] ('say_hello', 'Logical ids must be alphanumeric.')

2021-04-26 13:09:48 [WARN]: "sam build" failed: /Users/richbon/Documents/coding/sambug/say_hello/app___vsctk___template.yaml
2021-04-26 13:09:48 [INFO]: Starting SAM application locally
2021-04-26 13:09:48 [INFO]: AWS.running.command
Error: [InvalidResourceException('say_hello', 'Logical ids must be alphanumeric.')] ('say_hello', 'Logical ids must be alphanumeric.')
```

### Expected result:

I expected this to run successfully, and I'm very sure it used to.  It looks like sam is treating the projectRoot value ("say_hello") as a Logical Id, which it is not, and it gets upset about the underscore.

Even though the debugger won't run it, I can still `sam build`, `sam local invoke`, and `sam deploy` the function with this configuration.

For fun I tried to add an `"logicalId": "sayHello"` entry to the `invokeTarget` dictionary, but it didn't help and I got the same error.

_**I can make it run successfully in the interactive debugger if I make the projectRoot folder name conform to the Logical Id naming rules and remove the underscore**_, which involves doing these three things:

- Rename the `say_hello` folder to `sayhello`
- Modify `template.yaml` to say: `CodeUri: sayhello/`
- Modify `.vscode/launch.json` to say: `"projectRoot":"sayhello"`

The resulting successful run looks like this:
```
2021-04-26 13:16:56 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
2021-04-26 13:16:56 [INFO]: Building SAM application...
2021-04-26 13:16:56 [INFO]: Running command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctk61oq4r/output --template /Users/richbon/Documents/coding/sambug/sayhello/app___vsctk___template.yaml --base-dir /Users/richbon/Documents/coding/sambug/sayhello --manifest /tmp/aws-toolkit-vscode/vsctk61oq4r/debug-requirements.txt]
2021-04-26 13:16:57 [INFO]: Building codeuri: /Users/richbon/Documents/coding/sambug/sayhello runtime: python3.8 metadata: {} functions: ['sayhello']

2021-04-26 13:16:57 [INFO]: Running PythonPipBuilder:ResolveDependencies

2021-04-26 13:16:59 [INFO]: Running PythonPipBuilder:CopySource

2021-04-26 13:16:59 [INFO]: 
Build Succeeded

2021-04-26 13:16:59 [INFO]: 
Built Artifacts  : ../../../../../private/tmp/aws-toolkit-vscode/vsctk61oq4r/output
Built Template   : ../../../../../private/tmp/aws-toolkit-vscode/vsctk61oq4r/output/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke -t ../../../../../private/tmp/aws-toolkit-vscode/vsctk61oq4r/output/template.yaml
[*] Deploy: sam deploy --guided --template-file ../../../../../private/tmp/aws-toolkit-vscode/vsctk61oq4r/output/template.yaml
    

2021-04-26 13:17:00 [INFO]: Build complete.
2021-04-26 13:17:00 [INFO]: Starting SAM application locally
2021-04-26 13:17:00 [INFO]: AWS.running.command
Invoking app.lambda_handler (python3.8)
Ignoring unrecognized arguments: ['/tmp/lambci_debug_files/py_debug_wrapper.py', '--listen', '0.0.0.0:5858', '--wait-for-client', '--log-to-stderr']. Only "-delveAPI" is supported.
Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-python3.8:rapid-1.21.1.

Mounting /tmp/aws-toolkit-vscode/vsctk61oq4r/output/sayhello as /var/task:ro,delegated inside runtime container
START RequestId: 7154612b-89eb-4329-b853-0cf259b59eb0 Version: $LATEST
Prepending Lambda task root to path: /var/task
Starting debugger...
Debugger waiting for client...
2021-04-26 13:17:02 [INFO]: Attaching debugger to SAM application...
{"message": "Hello Alice!"}END RequestId: 7154612b-89eb-4329-b853-0cf259b59eb0
REPORT RequestId: 7154612b-89eb-4329-b853-0cf259b59eb0	Init Duration: 0.10 ms	Duration: 1313.83 ms	Billed Duration: 1400 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
2021-04-26 13:17:02 [INFO]: Debugger attached

Command stopped: "sam local invoke"
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 10.15.7
2. `sam --version`:  SAM CLI, version 1.21.1
  (after writing this up, I realized SAM 1.23.0 was available.  I installed it and still saw the same behavior.)
3. AWS region: us-east-1
4. VSCode: Version: 1.55.2

`Add --debug flag to command you are running`

**Comment by JadenSimon** [comment]
Fixed with https://github.com/aws/aws-toolkit-vscode/pull/1687
