### ISSUE TITLE
Stack error AttributeError: 'collections.OrderedDict' object has no attribute 'startswith' for cdk generated template

### ISSUE THREAD

**Issue by stmfcgcg** [aws/aws-sam-cli#2832]
### Description:
I have large project made up of 50 lambas in nested stacks. I have generated the template.yml from a cdk project (see attached template.yml). When I run 'sam local start-api' the application does not run and displays a stack trace (see attachment)

### Steps to reproduce:
run 'sam local start-api' with the attached template.yml

### Observed result:
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/local/start_api/cli.py", line 92, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/local/start_api/cli.py", line 161, in do_cli
    with InvokeContext(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 190, in __enter__
    self._stacks = self._get_stacks()
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/commands/local/cli_common/invoke_context.py", line 403, in _get_stacks
    stacks, _ = SamLocalStackProvider.get_stacks(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 230, in get_stacks
    current = SamLocalStackProvider(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 64, in __init__
    self._extract_stacks()
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 116, in _extract_stacks
    stack = SamLocalStackProvider._convert_cfn_stack_resource(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 168, in _convert_cfn_stack_resource
    if SamLocalStackProvider.is_remote_url(template_url):
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 250, in is_remote_url
    return any([url.startswith(prefix) for prefix in ["s3://", "http://", "https://"]])
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_stack_provider.py", line 250, in <listcomp>
    return any([url.startswith(prefix) for prefix in ["s3://", "http://", "https://"]])
AttributeError: 'collections.OrderedDict' object has no attribute 'startswith'

see attachment for full output with --debug enabled

### Expected result:
The API gateway to be running locally

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac Catalina 10.15.7
2. `sam --version`: 1.23.0
3. AWS region: US-west-2

[error.txt](https://github.com/aws/aws-sam-cli/files/6382719/error.txt)
[template.yml.txt](https://github.com/aws/aws-sam-cli/files/6382729/template.yml.txt)

**Comment by awood45** [comment]
We have a new release that may help with this - give it a try: https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/

**Comment by stmfcgcg** [comment]
Thanks for the response @awood45 
This does get me further, I no longer have that error. Unfortunately I now have a different one

> Error: Template does not have any APIs connected to Lambda functions

According to this stackoverflow Q there should be an Events section in template.yml and mine does not have one:

https://stackoverflow.com/questions/50680191/aws-sam-template-does-not-have-any-apis-connected-to-lambda-functions

I do have 40+ lambdas hooked upto the API gateway but none of them are in the root stack, they are all in the nested stacks (the root stack does not inherit for NestedStack, but all the children do)

**Comment by awood45** [comment]
Can you possibly share more of the relevant parts of your CDK app definition? It's somewhat difficult to debug from the generated YAML.

**Comment by aahung** [comment]
From the error message, it looks like a bug in SAM CLI where `_convert_cfn_stack_resource()` assumes `"AWS::CloudFormation::Stack" always have a string `TemplateURL`, which is not the case in CDK generated files.

**Comment by aahung** [comment]
If the templates is generated from CDK, you can use `sam-beta-cdk` to run `sam-beta-cdk build` and `sam-beta-cdk local invoke/start-api/start-lambda` directly on the CDK app.

**Comment by mgrandis** [comment]
Released in [1.24.0](https://github.com/aws/aws-sam-cli/releases/tag/v1.24.0)
