### ISSUE TITLE
sam build/deploy always result in a new changeset when using AWS::ServerlessLayerVersion

### ISSUE THREAD

**Issue by asgarciap** [aws/aws-sam-cli#2847]
### Description:

I have a AWS::ServerlessLayerVersion in my template as follow:

```
  SharedLibsLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      ContentUri: shared/
      CompatibleRuntimes:
        - python3.8
    Metadata:
      BuildMethod: python3.8
```
My `shared` directory contains a .py file and a requirements.txt with some common dependencies for my lambdas.
Now, everytime I run sam build & sam deploy I get a changeset with a LayerVersion + Lambdas modification eventhough I havent change anything in my shared layer directory and/or my lambdas source code.

```
CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                                  LogicalResourceId                                          ResourceType                                               Replacement
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                                      SharedLibsLayerc514ada812                                  AWS::Lambda::LayerVersion                                  N/A
* Modify                                                   ApiDeployment                                              AWS::ApiGateway::RestApi                                   False
* Modify                                                   MyFunctionFunction                                         AWS::Lambda::Function                                      False
* Modify                                                   MySecondFunction                                           AWS::Lambda::Function                                      False
- Delete                                                   SharedLibsLayer782226972b                                  AWS::Lambda::LayerVersion                                  N/A
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

### Steps to reproduce:

```
sam build --use-container --parallel --debug
sam deploy ...

```

### Observed result:

```
--- Logging error ---
Traceback (most recent call last):
  File "logging/__init__.py", line 1025, in emit
  File "logging/__init__.py", line 869, in format
  File "logging/__init__.py", line 608, in format
  File "logging/__init__.py", line 369, in getMessage
  File "samcli/lib/build/build_graph.py", line 353, in __str__
AttributeError: 'NoneType' object has no attribute 'name'
Call stack:
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/build/command.py", line 227, in cli
  File "samcli/commands/build/command.py", line 315, in do_cli
  File "samcli/lib/build/app_builder.py", line 139, in build
  File "samcli/lib/build/app_builder.py", line 204, in _get_build_graph
  File "samcli/lib/build/build_graph.py", line 232, in put_layer_build_definition
  File "logging/__init__.py", line 1366, in debug
  File "logging/__init__.py", line 1514, in _log
  File "logging/__init__.py", line 1524, in handle
  File "logging/__init__.py", line 1586, in callHandlers
  File "logging/__init__.py", line 894, in handle
  File "logging/__init__.py", line 1033, in emit
Message: 'Same Layer build definition found, adding layer (Previous: %s, Current: %s, Layer: %s)'
Arguments: (<samcli.lib.build.build_graph.LayerBuildDefinition object at 0x7f2dd0efa490>, <samcli.lib.build.build_graph.LayerBuildDefinition object at 0x7f2dd0f4ec90>, <samcli.lib.providers.provider.LayerVersion object at 0x7f2dd0f14550>)
```

### Expected result:

Since there is no change I expect an empty changeset in cloudformation

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WSL2
2. `sam --version`: SAM CLI, version 1.23.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by asgarciap** [comment]
I just rechecked this isssue and turnsout there was a dependency that was always downloading a .so file with different checksum, that is the reason the deploy command always resulted in a new changeset since the md5sum directory was different. There is some issue there but is not related with sam for sure. 
The error shown in the description is related with the #2666 issue.
So closing this one.
