### ISSUE TITLE
sam build fails for SQLAlchemy package

### ISSUE THREAD

**Issue by vganesh76** [aws/aws-sam-cli#2865]
**sam build fails when I include SQLAlchemy in requirements.txt. (Fails only for SQLAlchemy)**

requirements.txt:
boto3
botocore
psycopg2-binary
SQLAlchemy

Runtime: python3.8
SAM CLI, version 1.23.0

**Build Error:**

2021-05-09 20:54:40,223 | Final compatible: {s3transfer==0.4.2(wheel), botocore==1.20.69(wheel), six==1.16.0(wheel), python-dateutil==2.8.1(wheel), urllib3==1.26.4(wheel), jmespath==0.10.0(wheel), boto3==1.17.69(wheel), sqlalchemy==1.4.14(wheel), psycopg2-binary==2.8.6(wheel)}
2021-05-09 20:54:40,223 | Final incompatible: {greenlet==1.1.0(wheel), psycopg2-binary==2.8.6(wheel)}
2021-05-09 20:54:40,223 | Final missing wheels: {greenlet==1.1.0(wheel)}
2021-05-09 20:54:40,976 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/Cellar/aws-sam-cli/1.23.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {greenlet==1.1.0(wheel)}

**1. OS: Mac
2. `sam --version`: 1.23.0
3. AWS region: us-east-1**

**Comment by ricardoinacio** [comment]
This is happening to me as well.

**Comment by mgrandis** [comment]
1.24 was released to address this issue.
