### ISSUE TITLE
NameError: name 'NpipeHTTPAdapter' is not defined.  Install pypiwin32 package to enable npipe:// support

### ISSUE THREAD

**Issue by liamjc22** [aws/aws-sam-cli#2899]
### Description:

- sam build command is not working. 
- fails to get definition for NpipeHTTPAdapter (```AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py```)
- Files work with the command on other devices but is not working for mine. 
- Docker and Python are installed correctly
- Downloaded  SAM CLI through .msi
- Tried multiple versions with different combinations e.g. : ```pip install -Iv pywin32==227```

Still receiving the same ```NameError: name 'NpipeHTTPAdapter' is not defined```

Here is the same issue (was closed but not working):
#1480 
Commented but no reply so I am creating new.

**Tried:**
-  Python 2.7, 3.8, 
- multiple versions of pywin32 and pypiwin32, 
- installing via command line and .msi, and followed the instructions about 10 times. 
- installing via conda
- `docker run -it --rm python:2.7` command for docker terminal

This issue is still not fixed with no viable workaround currently. 
Sad because I cannot test Lambda locally. 
Please help :( 

### Steps to reproduce:

```
sam build
or
sam local start-api
```

### sam build
```
sam build --debug
2021-05-21 18:24:49,186 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-21 18:24:49,187 | Using config file: samconfig.toml, config environment: default
2021-05-21 18:24:49,187 | Expand command line arguments to:
2021-05-21 18:24:49,188 | --template_file=C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2021-05-21 18:24:49,493 | 'build' command is called
2021-05-21 18:24:49,503 | Collected default values for parameters: {}
2021-05-21 18:24:49,562 | 4 stacks found in the template
2021-05-21 18:24:49,562 | Collected default values for parameters: {}
2021-05-21 18:24:49,587 | 4 resources found in the stack 
2021-05-21 18:24:49,588 | Collected default values for parameters: {}
2021-05-21 18:24:49,615 | Found Serverless function with name='helloFromLambdaFunction' and CodeUri='./'
2021-05-21 18:24:49,616 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:24:49,617 | Found Serverless function with name='testFn' and CodeUri='./'
2021-05-21 18:24:49,617 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:24:49,619 | Found Serverless function with name='RDSGeneralQueryParser' and CodeUri='./'
2021-05-21 18:24:49,620 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:24:49,621 | Found Serverless function with name='getTopics' and CodeUri='./'
2021-05-21 18:24:49,622 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:24:49,623 | Collected default values for parameters: {}
2021-05-21 18:24:49,652 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '7d984b75-7169-4b3b-8af8-85375b9a659a', 'installationId': '8f72c1de-376f-4cde-bd12-a4b1facc4850', 'sessionId': 'b45d3a8a-3f4d-4a42-8e13-49b36ac49eb4', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 464, 'exitReason': 'DockerException', 'exitCode': 255}}]}
2021-05-21 18:24:50,162 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 210, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 296, in do_cli
    builder = ApplicationBuilder(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 122, in __init__
    self._docker_client = docker_client if docker_client else docker.from_env()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 84, in from_env
    return cls(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 158, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```

###  sam local start-api
```
sam local start-api    
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>   
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__       
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\start_api\cli.py", line 92, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\start_api\cli.py", line 161, in do_cli      
    with InvokeContext(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\cli_common\invoke_context.py", line 220, in 
__enter__
    self._container_manager = self._get_container_manager(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\cli_common\invoke_context.py", line 527, in 
_get_container_manager
    return ContainerManager(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 39, in __init__
    self.docker_client = docker_client or docker.from_env()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 84, in from_env
    return cls(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 158, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
PS C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda> sam local start-api --debug
2021-05-21 18:39:44,451 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-05-21 18:39:44,453 | Using config file: samconfig.toml, config environment: default
2021-05-21 18:39:44,453 | Expand command line arguments to:
2021-05-21 18:39:44,454 | --template_file=C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml --host=127.0.0.1 --port=3000 --static_dir=public --layer_cache_basedir=C:\Users\Liam\AppData\Roaming\AWS SAM\layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2021-05-21 18:39:45,047 | local start-api command is called
2021-05-21 18:39:45,061 | Collected default values for parameters: {}
2021-05-21 18:39:45,124 | 4 stacks found in the template
2021-05-21 18:39:45,125 | Collected default values for parameters: {}
2021-05-21 18:39:45,162 | 4 resources found in the stack 
2021-05-21 18:39:45,164 | Collected default values for parameters: {}
2021-05-21 18:39:45,225 | Found Serverless function with name='helloFromLambdaFunction' and CodeUri='./'
2021-05-21 18:39:45,226 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:39:45,228 | Found Serverless function with name='testFn' and CodeUri='./'
2021-05-21 18:39:45,229 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:39:45,229 | Found Serverless function with name='RDSGeneralQueryParser' and CodeUri='./'
2021-05-21 18:39:45,230 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:39:45,233 | Found Serverless function with name='getTopics' and CodeUri='./'
2021-05-21 18:39:45,235 | --base-dir is not presented, adjusting uri ./ relative to C:\Users\Liam\Documents\~~Projects~~\pollarBack\lambda\pollar-lambda\template.yml
2021-05-21 18:39:45,239 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '9b6d456b-d1cc-4d63-8d33-b56b6d9d721b', 'installationId': '8f72c1de-376f-4cde-bd12-a4b1facc4850', 'sessionId': 'ed953a3f-3207-4503-8ebd-404af2c2f3c4', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local start-api', 'duration': 785, 'exitReason': 'DockerException', 'exitCode': 255}}]}
2021-05-21 18:39:45,743 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 154, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\start_api\cli.py", line 92, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\start_api\cli.py", line 161, in do_cli      
    with InvokeContext(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\cli_common\invoke_context.py", line 220, in 
__enter__
    self._container_manager = self._get_container_manager(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\cli_common\invoke_context.py", line 527, in 
_get_container_manager
    return ContainerManager(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 39, in __init__
    self.docker_client = docker_client or docker.from_env()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 84, in from_env
    return cls(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 40, in __init__
    self.api = APIClient(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 158, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support
```

### Expected result:

Not an error
Aka sam to build

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10, JavaScript, Python, VSCode
2. `sam --version`:
3. AWS region: us-east-1

### Versions
```
python --version
Python 3.8.10

sam --version
SAM CLI, version 1.23.0

docker --version
Docker version 20.10.6, build 370c289
```

```
pip install pypiwin32   
     Requirement already satisfied: pypiwin32 in c:\users\liam\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (223)
     Requirement already satisfied: pywin32>=223 in c:\users\liam\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from pypiwin32) (300)
```

```
pip install pywin32  
     Requirement already satisfied: pywin32 in c:\users\liam\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (300)
```

```
pip freeze                                                   
     pypiwin32==223
     pywin32==300
```

`Add --debug flag to command you are running`

**Comment by mgrandis** [comment]
Hi Liam,
Have you tried running: `python <path-to-python-env>\Scripts\pywin32_postinstall.py -install`?
Found a https://github.com/twosixlabs/armory/issues/156

**Comment by liamjc22** [comment]
@mgrandis Thanks! I did try that before, but after a few days I managed to solve my issue along with your help...

**Basically, the Microsoft store was causing the issues**. 
To fix:
-  Uninstall python 
-  Go to 'App execution aliases' in windows 10 settings and turn off app installer for python and python3
- ![image](https://user-images.githubusercontent.com/46904239/119699723-740a6000-be20-11eb-8be5-608ec911d9bc.png)

- download python from official [website](https://www.python.org/downloads/windows/)
- make sure python path is in windows env vars [link](https://datatofish.com/add-python-to-windows-path/)
- download pywin32 from [link](https://github.com/mhammond/pywin32/releases)
- open new cmd and make sure you can run ```python --version```
- then follow @mgrandis 's comment or go to the ```<path-to-python-env>\Scripts\``` and  run ```python pywin32_postinstall.py -install```
- That's it! ``sam build``` command should work now!
