### ISSUE TITLE
Unable to build due to dependency failure

### ISSUE THREAD

**Issue by HAK-CODE** [aws/aws-sam-cli#2901]
### Description:
As numpy upgrade to 1.20.3 result in failure of build which used by pandas i tried both solution wheel installation and --user-container

### Steps to reproduce:

1. put pandas==1.2.3 in requirements.txt
2. sam buld --debug or sam build --use-container --debug

### Observed result:
```
2021-05-23 14:35:13,278 | Final incompatible: {numpy==1.20.3(wheel)}
2021-05-23 14:35:13,278 | Final missing wheels: {numpy==1.20.3(wheel)}
2021-05-23 14:35:14,615 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 42, in execute
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {numpy==1.20.3(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 269, in run
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
aws_lambda_builders.actions.ActionFailedError: {numpy==1.20.3(wheel)}

Build Failed
2021-05-23 14:35:14,623 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '5842da28-b67f-420b-8a97-c13e98c1862a', 'installationId': '1394d9aa-9786-4772-ae00-94c8594ffed9', 'sessionId': 'a36590aa-9127-46e9-9e6b-345b0279aabd', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 8961, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2021-05-23 14:35:15,697 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {numpy==1.20.3(wheel)}
```

### Expected result:
build successful

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04.2 LTS
2. `sam --version`: 1.23.0
3. AWS region: us-east-2

**Comment by aahung** [comment]
duplicate #2888
