### ISSUE TITLE
Failed to build python project

### ISSUE THREAD

**Issue by etishka** [aws/aws-sam-cli#2905]
### Description:
Python project is not compiled with error

requirements.txt
```
boto3==1.17.80
mysql-connector-python==8.0.25
backports.zoneinfo==0.2.1
```

sam build output:

```
Build Failed
Error: PythonPipBuilder:ResolveDependencies - {protobuf==3.17.1(wheel)}
```

### Steps to reproduce:
Create python app with requirements above, execute `sam build`

### Observed result:
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch
Full dependency closure: {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), protobuf==3.17.1(wheel), six==1.16.0(wheel)}
initial compatible: {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), six==1.16.0(wheel)}
initial incompatible: {protobuf==3.17.1(wheel)}
Downloading missing wheels: {protobuf==3.17.1(wheel)}
calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/samcli/scratch protobuf==3.17.1
compatible wheels after second download pass: {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), six==1.16.0(wheel)}
Build missing wheels from sdists (C compiling True): set()
compatible after building wheels (no C compiling): {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), six==1.16.0(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), six==1.16.0(wheel)}
Final compatible: {mysql-connector-python==8.0.25(wheel), backports-zoneinfo==0.2.1(wheel), six==1.16.0(wheel)}
Final incompatible: {protobuf==3.17.1(wheel)}
Final missing wheels: {protobuf==3.17.1(wheel)}
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {protobuf==3.17.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {protobuf==3.17.1(wheel)}
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute
    package_builder.build_dependencies(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 137, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 207, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {protobuf==3.17.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 45, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {protobuf==3.17.1(wheel)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: PythonPipBuilder:ResolveDependencies - {protobuf==3.17.1(wheel)}
2021-05-25 22:41:14,155 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "PythonPipBuilder:ResolveDependencies - {protobuf==3.17.1(wheel)}"}}

Build Failed
2021-05-25 22:41:14,625 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '531bd81d-eaa2-478d-89c7-db3bd31f6c8b', 'installationId': '2f130e36-2831-40bf-8baa-f6faa95024d4', 'sessionId': '65e6d0b7-d43a-4c24-9017-45d9703275a4', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.23.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam build', 'duration': 26421, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2021-05-25 22:41:15,277 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - {protobuf==3.17.1(wheel)}

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: BigSur 11.2.3 (20D91)
2. `sam --version`: SAM CLI, version 1.23.0
3. AWS region: us-east-1

**Comment by aahung** [comment]
duplicate: #2888
