### ISSUE TITLE
custom docker image does not work with sam local invoke

### ISSUE THREAD

**Issue by ryanjfrizzell** [aws/aws-sam-cli#2925]
### Description:
Much of what we're seeing here is described here: https://github.com/aws/aws-sam-cli/issues/294

We're trying to use sam to develop a lambda which uses a custom docker image. We want to build that image and then use that image in ```sam local invoke```. Sam however just ignore our image entirely. 

### Steps to reproduce:
1. Use sam init to create a new project: 

```
sam init
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1
What package type would you like to use?
	1 - Zip (artifact is a zip uploaded to S3)
	2 - Image (artifact is an image uploaded to an ECR image repository)
Package type: 2

Which base image would you like to use?
	1 - amazon/nodejs14.x-base
	2 - amazon/nodejs12.x-base
	3 - amazon/nodejs10.x-base
	4 - amazon/python3.8-base
	5 - amazon/python3.7-base
	6 - amazon/python3.6-base
	7 - amazon/python2.7-base
	8 - amazon/ruby2.7-base
	9 - amazon/ruby2.5-base
	10 - amazon/go1.x-base
	11 - amazon/java11-base
	12 - amazon/java8.al2-base
	13 - amazon/java8-base
	14 - amazon/dotnet5.0-base
	15 - amazon/dotnetcore3.1-base
	16 - amazon/dotnetcore2.1-base
Base image: 8

Project name [sam-app]: sam-test

Cloning app templates from https://github.com/aws/aws-sam-cli-app-templates

    -----------------------
    Generating application:
    -----------------------
    Name: sam-test
    Base Image: amazon/ruby2.7-base
    Dependency Manager: bundler
    Output Directory: .

    Next steps can be found in the README file at ./sam-test/README.md
```

2. modify template.yaml, and code,  to use a "custom docker image" (git diff here to show what we did):

```
diff --git a/hello_world/Dockerfile b/hello_world/Dockerfile
index 6e5dd23..0bfe605 100644
--- a/hello_world/Dockerfile
+++ b/hello_world/Dockerfile
@@ -1,8 +1,10 @@
 FROM public.ecr.aws/lambda/ruby:2.7
-
 COPY app.rb Gemfile ./
-
+RUN yum install -y amazon-linux-extras && \ 
+  yum makecache && \
+  yum install -y postgresql-devel postgresql-libs makecache && \
+  yum groupinstall "development tools" -y
 RUN bundle install
-
+RUN ruby -e "require 'pg'; puts('yay')" # to test that we can load the pg gem
 # Command can be overwritten by providing a different command in the template directly.
-CMD ["app.lambda_handler"]
\ No newline at end of file
+CMD ["app.lambda_handler"]
diff --git a/hello_world/Gemfile b/hello_world/Gemfile
index 8ba70fa..ed6c42c 100644
--- a/hello_world/Gemfile
+++ b/hello_world/Gemfile
@@ -1,5 +1,6 @@
 source "https://rubygems.org"
 
 gem "httparty"
+gem "pg"
 
 ruby '~> 2.7.0'
diff --git a/hello_world/app.rb b/hello_world/app.rb
index e2a102f..4ace352 100644
--- a/hello_world/app.rb
+++ b/hello_world/app.rb
@@ -1,5 +1,6 @@
 # require 'httparty'
 require 'json'
+require 'pg'
 
 def lambda_handler(event:, context:)
   # Sample pure Lambda function
diff --git a/template.yaml b/template.yaml
index ca26662..d6f0565 100644
--- a/template.yaml
+++ b/template.yaml
@@ -22,7 +22,7 @@ Resources:
             Path: /hello
             Method: get
     Metadata:
-      DockerTag: ruby2.7-v1
+      DockerTag: customImage
       DockerContext: ./hello_world
       Dockerfile: Dockerfile
 

```

3. run `sam build` (output reduced slightly here)

```
Setting DockerBuildArgs: {} for HelloWorldFunction function
Step 1/6 : FROM public.ecr.aws/lambda/ruby:2.7
 ---> 4aa0e4a2d2fb
Step 2/6 : COPY app.rb Gemfile ./
 ---> 90d9eecc7d6c
Step 3/6 : RUN yum install -y amazon-linux-extras &&   yum makecache &&   yum install -y postgresql-devel postgresql-libs makecache &&   yum groupinstall "development tools" -y
.
.
.
Post-install message from httparty:
When you HTTParty, you must party hard!
 ---> 6d13885ed82d
Step 5/6 : RUN ruby -e "require 'pg'; puts('yay')" # to test that we can load the pg gem
 ---> Running in 9e7b9efb9788
yay
 ---> 709a4cf96cbc
Step 6/6 : CMD ["app.lambda_handler"]
 ---> Running in e235bc420711
 ---> 7bd421f2e727
Successfully built 7bd421f2e727
Successfully tagged helloworldfunction:customImage

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
```

4. try to run `sam local invoke --debug` and cry in your cheerios because it uses some other image. 

```
2021-06-02 13:56:53,860 | Found one Lambda function with name 'HelloWorldFunction'
2021-06-02 13:56:53,860 | Invoking Container created from helloworldfunction:customImage
2021-06-02 13:56:53,860 | No environment variables found for function 'HelloWorldFunction'
2021-06-02 13:56:53,860 | Environment variables overrides data is standard format
2021-06-02 13:56:53,860 | Loading AWS credentials from session with profile 'None'
2021-06-02 13:56:55,897 | Code None is not a zip/jar file
2021-06-02 13:56:55,905 | Image was not found.
Building image..........
2021-06-02 13:56:57,571 | Skip pulling image and use local one: helloworldfunction:rapid-1.21.1.

2021-06-02 13:56:59,162 | Starting a timer for 3 seconds for function 'HelloWorldFunction'
START RequestId: 3fc518df-f3b1-410f-b0bf-8d605fb78148 Version: $LATEST
Init error when loading handler app.lambda_handler
{
  "errorMessage": "cannot load such file -- pg",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/task/app.rb:3:in `<top (required)>'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
  ]
}
time="2021-06-02T19:56:59.446" level=panic msg="ReplyStream not available"
2021/06/02 19:56:59 http: panic serving 127.0.0.1:42998: &{0xc0000f4000 map[] 2021-06-02 19:56:59.4467819 +0000 UTC m=+0.299775101 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 38 [running]:
net/http.(*conn).serve.func1(0xc0002081e0)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc0001120e0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc0000f4000, 0xc0001140f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000112070, 0xc000000000, 0xc00008f588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000f4000, 0xc000000000, 0xc00008f588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
go.amzn.com/lambda/rapi/rendering.RenderInteropError(0x9097c0, 0xc000126000, 0xc00012e100, 0x902b60, 0xc0001220a0)
	/LambdaRuntimeLocal/lambda/rapi/rendering/rendering.go:292 +0x9a
go.amzn.com/lambda/rapi/handler.(*initErrorHandler).ServeHTTP(0xc000096fe0, 0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/handler/initerror.go:52 +0x519
net/http.HandlerFunc.ServeHTTP(0xc0000ac640, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000bc600, 0x9097c0, 0xc000126000, 0xc00012e100)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000096f70, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.RuntimeReleaseMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:100 +0xea
net/http.HandlerFunc.ServeHTTP(0xc0000ac440, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AccessLogMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:77 +0x170
net/http.HandlerFunc.ServeHTTP(0xc0000ac460, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AppCtxMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e000)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:66 +0x77
net/http.HandlerFunc.ServeHTTP(0xc000099410, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000bc600, 0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x118
net/http.HandlerFunc.ServeHTTP(0xc0000ac6a0, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000bc5a0, 0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000097000, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000bc5a0, 0x9097c0, 0xc000126000, 0xc000236300)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2b2
net/http.serverHandler.ServeHTTP(0xc0001900e0, 0x9097c0, 0xc000126000, 0xc000236300)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0002081e0, 0x90a800, 0xc000220240)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
/var/runtime/lib/lambda_server.rb:85:in `rescue in send_init_error': end of file reached (LambdaErrors::LambdaRuntimeInitError)
	from /var/runtime/lib/lambda_server.rb:78:in `send_init_error'
	from /var/runtime/lib/runtime.rb:80:in `rescue in <main>'
	from /var/runtime/lib/runtime.rb:46:in `<main>'
/var/lang/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
	from /var/lang/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
	from /var/lang/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	from /var/lang/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	from /var/lang/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1506:in `send_entity'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1294:in `post'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:502:in `block in post'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:933:in `start'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:606:in `start'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:500:in `post'
	from /var/runtime/lib/lambda_server.rb:79:in `send_init_error'
	from /var/runtime/lib/runtime.rb:80:in `rescue in <main>'
	from /var/runtime/lib/runtime.rb:46:in `<main>'
/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- pg (LoadError)
```

### Observed result:

```
2021-06-02 13:56:53,860 | Found one Lambda function with name 'HelloWorldFunction'
2021-06-02 13:56:53,860 | Invoking Container created from helloworldfunction:customImage
2021-06-02 13:56:53,860 | No environment variables found for function 'HelloWorldFunction'
2021-06-02 13:56:53,860 | Environment variables overrides data is standard format
2021-06-02 13:56:53,860 | Loading AWS credentials from session with profile 'None'
2021-06-02 13:56:55,897 | Code None is not a zip/jar file
2021-06-02 13:56:55,905 | Image was not found.
Building image..........
2021-06-02 13:56:57,571 | Skip pulling image and use local one: helloworldfunction:rapid-1.21.1.

2021-06-02 13:56:59,162 | Starting a timer for 3 seconds for function 'HelloWorldFunction'
START RequestId: 3fc518df-f3b1-410f-b0bf-8d605fb78148 Version: $LATEST
Init error when loading handler app.lambda_handler
{
  "errorMessage": "cannot load such file -- pg",
  "errorType": "Init<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/task/app.rb:3:in `<top (required)>'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
  ]
}
time="2021-06-02T19:56:59.446" level=panic msg="ReplyStream not available"
2021/06/02 19:56:59 http: panic serving 127.0.0.1:42998: &{0xc0000f4000 map[] 2021-06-02 19:56:59.4467819 +0000 UTC m=+0.299775101 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 38 [running]:
net/http.(*conn).serve.func1(0xc0002081e0)
	/usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc0001120e0)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc0000f4000, 0xc0001140f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000112070, 0xc000000000, 0xc00008f588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000f4000, 0xc000000000, 0xc00008f588, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
go.amzn.com/lambda/rapi/rendering.RenderInteropError(0x9097c0, 0xc000126000, 0xc00012e100, 0x902b60, 0xc0001220a0)
	/LambdaRuntimeLocal/lambda/rapi/rendering/rendering.go:292 +0x9a
go.amzn.com/lambda/rapi/handler.(*initErrorHandler).ServeHTTP(0xc000096fe0, 0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/handler/initerror.go:52 +0x519
net/http.HandlerFunc.ServeHTTP(0xc0000ac640, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000bc600, 0x9097c0, 0xc000126000, 0xc00012e100)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000096f70, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.RuntimeReleaseMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:100 +0xea
net/http.HandlerFunc.ServeHTTP(0xc0000ac440, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AccessLogMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e100)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:77 +0x170
net/http.HandlerFunc.ServeHTTP(0xc0000ac460, 0x9097c0, 0xc000126000, 0xc00012e100)
	/usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AppCtxMiddleware.func1.1(0x9097c0, 0xc000126000, 0xc00012e000)
	/LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:66 +0x77
net/http.HandlerFunc.ServeHTTP(0xc000099410, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000bc600, 0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x118
net/http.HandlerFunc.ServeHTTP(0xc0000ac6a0, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000bc5a0, 0x9097c0, 0xc000126000, 0xc00012e000)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc000097000, 0x9097c0, 0xc000126000, 0xc00012e000)
	/usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000bc5a0, 0x9097c0, 0xc000126000, 0xc000236300)
	/go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2b2
net/http.serverHandler.ServeHTTP(0xc0001900e0, 0x9097c0, 0xc000126000, 0xc000236300)
	/usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0002081e0, 0x90a800, 0xc000220240)
	/usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2962 +0x35c
/var/runtime/lib/lambda_server.rb:85:in `rescue in send_init_error': end of file reached (LambdaErrors::LambdaRuntimeInitError)
	from /var/runtime/lib/lambda_server.rb:78:in `send_init_error'
	from /var/runtime/lib/runtime.rb:80:in `rescue in <main>'
	from /var/runtime/lib/runtime.rb:46:in `<main>'
/var/lang/lib/ruby/2.7.0/net/protocol.rb:225:in `rbuf_fill': end of file reached (EOFError)
	from /var/lang/lib/ruby/2.7.0/net/protocol.rb:191:in `readuntil'
	from /var/lang/lib/ruby/2.7.0/net/protocol.rb:201:in `readline'
	from /var/lang/lib/ruby/2.7.0/net/http/response.rb:42:in `read_status_line'
	from /var/lang/lib/ruby/2.7.0/net/http/response.rb:31:in `read_new'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1528:in `block in transport_request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1519:in `catch'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1519:in `transport_request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1492:in `request'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1506:in `send_entity'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:1294:in `post'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:502:in `block in post'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:933:in `start'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:606:in `start'
	from /var/lang/lib/ruby/2.7.0/net/http.rb:500:in `post'
	from /var/runtime/lib/lambda_server.rb:79:in `send_init_error'
	from /var/runtime/lib/runtime.rb:80:in `rescue in <main>'
	from /var/runtime/lib/runtime.rb:46:in `<main>'
/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- pg (LoadError)
```

### Expected result:
we'd expect this like in the `sam local invoke` output: 

```
Skip pulling image and use local one: helloworldfunction:rapid-1.21.1.
```

to look something more like: 

```
using local image: helloworldfunction:customImage
```

the expectation here is that the custom image is used to run the lambda not the defaut. no level of searching or other flags like `--skip-pull-image` seems to get us past this.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 11.3.1
2. `sam --version`: SAM CLI, version 1.21.1
3. AWS region: n/a 

`Add --debug flag to command you are running`

**Comment by c2tarun** [comment]
Hi @ryanjfrizzell,

Thanks for reporting this issue. However, in your logs I see that the new image with your tag is actually the one used for local invocation:

```
2021-06-02 13:56:53,860 | Found one Lambda function with name 'HelloWorldFunction'
2021-06-02 13:56:53,860 | Invoking Container created from helloworldfunction:customImage    <----
2021-06-02 13:56:53,860 | No environment variables found for function 'HelloWorldFunction'
```

The rapid image log is slightly misleading. We use your image to build another image which has RAPID within it. This acts as glue between SAM CLI and Runtime. The reason you see `Skip pulling image and use local one` log is because we build the image locally but the code that try to use the image first checks image is available on local or not. Once it detects it skip pulling log is emitted.

I tried the changes similar to yours (just in node project) and it worked fine for me.

```
diff --git a/hello-world/Dockerfile b/hello-world/Dockerfile
index 37f0cd0..5d1884a 100644
--- a/hello-world/Dockerfile
+++ b/hello-world/Dockerfile
@@ -2,6 +2,7 @@ FROM public.ecr.aws/lambda/nodejs:14
 
 COPY app.js package.json ./
 
+RUN yum install -y amazon-linux-extras
 RUN npm install
 
 # Command can be overwritten by providing a different command in the template directly.
diff --git a/hello-world/package.json b/hello-world/package.json
index 2baf0ac..a77d689 100644
--- a/hello-world/package.json
+++ b/hello-world/package.json
@@ -7,7 +7,8 @@
   "author": "SAM CLI",
   "license": "MIT",
   "dependencies": {
-    "axios": "^0.21.1"
+    "axios": "^0.21.1",
+    "lodash": "^4.17.21"
   },
   "scripts": {
     "test": "mocha tests/unit/"
diff --git a/template.yaml b/template.yaml
index d476ea2..19438ad 100644
--- a/template.yaml
+++ b/template.yaml
@@ -22,7 +22,7 @@ Resources:
             Path: /hello
             Method: get
     Metadata:
-      DockerTag: nodejs14.x-v1
+      DockerTag: customImage
       DockerContext: ./hello-world
       Dockerfile: Dockerfile
```

Please let me know if you have more questions regarding this.

Thanks

**Comment by ryanjfrizzell** [comment]
hi @c2tarun thank you for taking the time to look at this. I think we're probably doing something wrong at this point, the intention is to be able to test using postgres libraries (in ruby in this case, but the same issue works for python). If we run our custom image outside of sam everything works fine, however local invoke raises exceptions because the lambda (inside sam cannot find the postgres libraries).

this is not an issue for nodejs since the nodejs postgres libraries do not require system libraries to function. We were trying to use the Dockerfile (which sam kindly templated out for us) to include the postgres libraries. I think the key here is going to be to move the .so libraries needed to build postgres libs into /var/lib/task? inside the docker image, but I'm not 100% on that.

**Comment by mndeveci** [comment]
Hi @ryanjfrizzell ,

I was able to re-produce the issue by running same template as you mentioned. When I was trying to find the issue, I also tested without even adding the `pg` to the dependencies, by removing 1st line comment in `app.rb` which imports another dependency (`require 'httparty'`) and that one also fails. I tried to deploy both functions and I wasn't able to run the function on my account as well.

I will raise the issue with Lambda team, but can you also confirm that these are not working on your work machine?

**Comment by ryanjfrizzell** [comment]
thx @mndeveci for reproducing. Regarding this statement, "but can you also confirm that these are not working on your work machine?"  ... we've tried this on a number of machines and can't seem to get it working correctly (with docker).

**Comment by ryanjfrizzell** [comment]
just to follow up on this we ended up using lambda layers (for now to address this), here is a sample of our makefile from our lambda layer (which gets PG working for now). However , we still can't seem to get this working with container images. 


```
SHELL := /bin/bash
PGVERSION := 11.10
BP := $(ARTIFACTS_DIR)
PGSOURCE := postgresql-$(PGVERSION)
.PHONY: build-RubyDependencyLayer
.ONESHELL:

build-RubyDependencyLayer:

	yum install -y amazon-linux-extras tree
	yum makecache
	yum install -y postgresql-devel postgresql-libs
	curl -O https://ftp.postgresql.org/pub/source/v11.10/postgresql-11.10.tar.gz
	tar -xvzf $(PGSOURCE).tar.gz
	(cd $(PGSOURCE) && ./configure --prefix=$(BP) --without-readline && $(MAKE) -C . MAKELEVEL=0 all && $(MAKE) install)
	bundle config --local build.pg --with-pg-config=$(BP)/bin/pg_config
	bundle config --local silence_root_warning true
	bundle config --local path $(ARTIFACTS_DIR)
	bundle install
	mkdir $(ARTIFACTS_DIR)/ruby/gems
	mv $(ARTIFACTS_DIR)/ruby/2.7.0 $(ARTIFACTS_DIR)/ruby/gems
```

**Comment by jfuss** [comment]
@ryanjfrizzell The issue seems to be where the gems get installed by default. This PR to our examples should be enough and has some context. https://github.com/aws/aws-sam-cli-app-templates/pull/123

Can you try setting `ENV GEM_HOME=${LAMBDA_TASK_ROOT}` in the Dockerfile?

**Comment by moelasmar** [comment]
Hello @ryanjfrizzell 
Please reopen the issue if you still have any questions or any other issues.
