### ISSUE TITLE
When specififying a custom template name sam package/deploy will fail with an ImageUri error

### ISSUE THREAD

**Issue by glnds** [aws/aws-sam-cli#2928]
### Description:
if you specify a custom template name using `sam package` or `sam deploy` the command fails with the following error:
```
Error: Unable to upload artifact None referenced by ImageUri parameter of ProbeLdapFunction resource.
Image not found for ImageUri parameter of ProbeLdapFunction resource.
```

### Steps to reproduce:
When runnining
```
 sam package --template-file some-template.yaml --output-template-file packaged-template.yml --image-repository 555555555.dkr.ecr.eu-west-1.amazonaws.com/some-repo 
```
Specifying a `--template-file` is crucial.

### Observed result:
```
2021-06-03 13:35:53,030 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-03 13:35:53,030 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-03 13:35:53,031 | Sending Telemetry: {'metrics': [{'templateWarning': {'requestId': 'd3d83f6b-3696-460a-b9c0-58eb172f1a3c', 'installationId': '45daf819-9413-4ba3-b26a-d3daa84603db', 'sessionId': '31123d7c-7ff3-45c6-8cd3-881e723953c7', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.24.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'warningName': 'CodeDeployWarning', 'warningCount': 0}}]}
2021-06-03 13:35:53,674 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2021-06-03 13:35:53,675 | Sending Telemetry: {'metrics': [{'templateWarning': {'requestId': '837dbf7c-63cc-44ab-8942-db57f32a979e', 'installationId': '45daf819-9413-4ba3-b26a-d3daa84603db', 'sessionId': '31123d7c-7ff3-45c6-8cd3-881e723953c7', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.24.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'warningName': 'CodeDeployConditionWarning', 'warningCount': 0}}]}
2021-06-03 13:35:54,274 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2021-06-03 13:35:54,274 | Using config file: samconfig.toml, config environment: default
2021-06-03 13:35:54,274 | Expand command line arguments to:
2021-06-03 13:35:54,274 | --template_file=/Users/glnds/source/dpg/iocrowd/woodwing-monitoring/cfn-serverless.yaml --output_template_file=packaged-template.yml --image_repository=5555555.dkr.ecr.eu-west-1.amazonaws.com//some-repo
2021-06-03 13:35:54,591 | Unable to export
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.24.0/libexec/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 223, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.24.0/libexec/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 236, in do_export
    uploaded_url = upload_local_image_artifacts(
  File "/usr/local/Cellar/aws-sam-cli/1.24.0/libexec/lib/python3.8/site-packages/samcli/lib/package/utils.py", line 113, in upload_local_image_artifacts
    raise ImageNotFoundError(property_name=property_name, resource_id=resource_id)
samcli.commands.package.exceptions.ImageNotFoundError: Image not found for ImageUri parameter of ProbeLdapFunction resource.

2021-06-03 13:35:54,593 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '75c3c734-c70b-4e35-bc4e-4a1067e489e3', 'installationId': '45daf819-9413-4ba3-b26a-d3daa84603db', 'sessionId': '31123d7c-7ff3-45c6-8cd3-881e723953c7', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.24.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 1562, 'exitReason': 'ExportFailedError', 'exitCode': 1}}]}
2021-06-03 13:35:55,198 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Unable to upload artifact None referenced by ImageUri parameter of ProbeLdapFunction resource.
Image not found for ImageUri parameter of ProbeLdapFunction resource.
```

I noticed the following when running the sam commands which most likely gives a very good indication of the problem:
- When you run `sam build` WITHOUT a custom template name a new `template.yaml` is generated under `.aws-sam/build/`. Such a file is NOT generated if you use a custom template name.
- This newly generated template contains the extra line `ImageUri: lambdafunction:sometag`, which obviously is crucial in this flow.
- The commands `sam package` and `sam deploy` seems to use the generated template file under `.aws-sam/build/` instead of the original template. (make sense of course). With a custom template name such a generated file is NOT in place.

### Expected result:
To yield `packaged-template.yaml`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Big Sur
2. `sam --version`: 1.24.0 and with samdev (commit e8d8a1ef85d4db5883929821c5eb8e54b813afb6)
3. AWS region: eur-west-1

**Comment by sriram-mv** [comment]
Hey @glnds! Thanks for the report.

Just so I understand this correctly. you can still have a custom template file say `custom.yaml` and go about doing a build.

`sam build --template-file custom.yaml` -> This will generate a new .aws-sam/build/template.yaml

At this point you can directly call package/deploy without specifying a template-file.

`sam package --output-template-file packaged.yaml --image-repository <>` should continue to work, since if a template file is not specified, sam package will resolve looking into the internal build dir first, followed by a default template.yaml file.

Is the issue that sam build does not allow you to name your output template file?

**Comment by tahoward** [comment]
I ran into this issue as well, except with `sam local start-api --template <template_file_path>`.

As a SAM CLI noob it wasn't clear to me that explicitly specifying the template path is unnecessary after performing `sam build` until I read https://github.com/aws/aws-sam-cli/issues/2928#issuecomment-854104189

Maybe there needs to be some more wordage around this? It's a great feature but at least for me went against my intuition.

**Comment by glnds** [comment]
@sriram-mv my apologies for the late reply. Somehow I overlooked your comment. Re-reading my initial report I realize I forgot to mention one crucial detail: this is only the case if you specify `PackageType: Image`.

If that property is specified it's impossible to run `sam package` with a custom template name.

For example:
```
  ProbeLdapFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      FunctionName: probe-ldap-cfn
      Description: Lambda function to probe lDAP
      PackageType: Image
      Timeout: 10
      MemorySize: 128
      Role: !GetAtt ProbeLdapFunctionRole.Arn
      VpcConfig:
        SecurityGroupIds:
          - !Ref ProbeLdapFunctionSecurityGroup
        SubnetIds: !Ref PrivateSubnetIdsParam
      Events:
        ProbeEveryMinute:
          Type: Schedule
          Properties:
            Schedule: "rate(1 minute)"
```

**Comment by qingchm** [comment]
@glnds If I understand your issue correctly, here are two things that I want to clarify to make you unblocked! 1. You can always run package without build, but for image type if you want that you would need to have an ImageUri ready before hand. If you don't have a URI ready please always use build before package. 2. The desired flow of your package --template-file custom-template --ouput-template-file custom-output-template can be replaced by build --template-file custom-template + package --output-template-file custom-output-template so I think there should be nothing blocking you right now! Feel free to reopen this issue or reach out if you have any further questions! @tahoward Also thanks for your input! We will try to improve our docs gradually!
