### ISSUE TITLE
verify crashes with 'NoneType' object has no attribute 'get' when attempting to use an explicit HttpApi

### ISSUE THREAD

**Issue by Fitzsimmons** [aws/aws-sam-cli#2931]
### Description:

I'm trying to experiment with using an explicit HttpApi instead of the implicit one inserted by SAM. Unfortunately it crashes when I validate. (I get similar but less informative errors when I try to deploy or launch it locally as well.)

### Steps to reproduce:

Start with a standard Hello World template and simply add a HttpApi and reference it.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyApi:
    Type: Aws::Serverless::HttpApi

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: ruby2.7
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref MyApi
            Path: /hello
            Method: get
```

Then run `sam validate`.

### Observed result:

`sam validate` crashes:

```
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/validate/validate.py", line 37, in cli
  File "samcli/commands/validate/validate.py", line 59, in do_cli
  File "samcli/commands/validate/lib/sam_template_validator.py", line 68, in is_valid
  File "samtranslator/translator/translator.py", line 133, in translate
  File "samtranslator/model/sam_resources.py", line 192, in to_cloudformation
  File "samtranslator/model/sam_resources.py", line 621, in _generate_event_resources
  File "samtranslator/model/eventsources/push.py", line 1039, in to_cloudformation
  File "samtranslator/model/eventsources/push.py", line 1052, in _get_permissions
  File "samtranslator/model/eventsources/push.py", line 1064, in _get_permission
AttributeError: 'NoneType' object has no attribute 'get'
[10742] Failed to execute script __main__
```

### Expected result:

`template.yaml is a valid SAM Template`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

I have isolated the problem to `ApiId: !Ref MyApi`. Removing this line will no longer crash. However that's not useful for making any progress on my project to use an explict HttpApi.

1. OS: Linux
2. `sam --version`: `SAM CLI, version 1.23.0` - currently one version behind to work around #2927
3. AWS region: us-east-2

**Comment by c2tarun** [comment]
Hi @Fitzsimmons,

Sorry the error message is not very descriptive. Problem with the given template is that it has an AWS Resources with no Properties. I simply added tag to your resource and it passed my `sam validate` command:

```
Resources:
  MyApi:
    Type: Aws::Serverless::HttpApi
    Properties:
      Tags:
        Key: Value

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello-world/
      Handler: app.lambda_handler
      Runtime: nodejs14.x
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Method: get
            Path: /hello
            ApiId: !Ref MyApi
```

This is certainly an edge case which we missed and that is why the non helpful error message. We'll work on fixing it in validate but for now I'll mark this issue as resolved. Please feel free to re-open the issue if you have more questions.

Thanks
