### ISSUE TITLE
Lambda container's /var/task folder is empty - Cannot find module 'main'

### ISSUE THREAD

**Issue by abecks** [aws/aws-sam-cli#2955]
### Description:
When running `sam local start-api -t .sam-build/template.yaml --static-dir \"\" --warm-containers LAZY -n server/.env.json` the Docker container does not load the source code into the /var/task directory, and thus results in a `Cannot find module 'main'` error.

If I change the build output directory from `.aws-sam` it will work temporarily, but eventually stop working and I haven't been able to figure out what causes it. Does the SAM tool ignore loading files from a SAM build?

### Steps to reproduce:

template.yaml contains:

```
  FrontendLambda:
    Name: Frontend
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: main.handler
      Runtime: nodejs12.x
      Tracing: Active
      MemorySize: 128
      Role: !Ref lambdaExecutionRole
      AutoPublishAlias: FrontendLambdaAlias
      DeploymentPreference:
        Enabled: true
        Type: AllAtOnce
```

1. Build with `sam build -u -t iac/template.yaml`
2. Run with `sam local start-api -t .aws-sam/build/template.yaml --static-dir \"\" --warm-containers LAZY -n server/.env.json`

For me this results in the empty `/var/task` folder in the Lambda container and the `Cannot find module 'main'` error.

But if we change the build directory:

3. Build with `sam build -u -t iac/template.yaml -b .sam-build`
4. Run with `sam local start-api -t .sam-build/template.yaml --static-dir \"\" --warm-containers LAZY -n server/.env.json`

Works the first time it is ran, and then if you run `sam local start-api` again, it will fail with the same error.

And I should note skipping steps 3 and 4 and simply renaming the folder works as well.

Really clueless as to how to provide more information on this, would love to be pointed in the right direction.

### Observed result:

This was ran with the build directory being `.sam-build` instead of `.aws-sam`

Note: Some of the output from the container may be mangled due to #1359 

```

2021-06-13 15:15:34,637 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-13 15:15:34,638 | Using config file: samconfig.toml, config environment: default
2021-06-13 15:15:34,639 | Expand command line arguments to:
2021-06-13 15:15:34,639 | --template_file=/dev/project/modules/frontend/.sam-build/template.yaml --warm_containers=LAZY --env_vars=server/.env.json --host=127.0.0.1 --port=3000 --layer_cache_basedir=/Users/andrew/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2021-06-13 15:15:34,711 | local start-api command is called
2021-06-13 15:15:34,754 | Collected default values for parameters: {'env': 'staging', 'domain': '*.staging.project.com'}
2021-06-13 15:15:34,791 | 6 stacks found in the template
2021-06-13 15:15:34,791 | Collected default values for parameters: {'env': 'staging', 'domain': '*.staging.project.com'}
2021-06-13 15:15:34,825 | 6 resources found in the stack 
2021-06-13 15:15:34,825 | Collected default values for parameters: {'env': 'staging', 'domain': '*.staging.project.com'}
2021-06-13 15:15:34,859 | Found Serverless function with name='FrontendLambda' and CodeUri='FrontendLambda'
2021-06-13 15:15:34,859 | --base-dir is not presented, adjusting uri FrontendLambda relative to /dev/project/modules/frontend/.sam-build/template.yaml
2021-06-13 15:15:34,867 | Collected default values for parameters: {'env': 'staging', 'domain': '*.staging.project.com'}
2021-06-13 15:15:34,901 | Collected default values for parameters: {'env': 'staging', 'domain': '*.staging.project.com'}
2021-06-13 15:15:34,933 | Detected Inline Swagger definition
2021-06-13 15:15:34,933 | Extracted Function ARN: arn:aws:lambda:us-east-1:123456789012:function:FrontendLambda:FrontendLambdaAlias
2021-06-13 15:15:34,934 | Extracted Function ARN: arn:aws:lambda:us-east-1:123456789012:function:FrontendLambda:FrontendLambdaAlias
2021-06-13 15:15:34,934 | Lambda function integration not found in Swagger document at path='/embed.js' method='get'
2021-06-13 15:15:34,934 | Lambda function integration not found in Swagger document at path='/assets/{proxy+}' method='get'
2021-06-13 15:15:34,934 | Extracted Function ARN: arn:aws:lambda:us-east-1:123456789012:function:FrontendLambda:FrontendLambdaAlias
2021-06-13 15:15:34,934 | Extracted Function ARN: arn:aws:lambda:us-east-1:123456789012:function:FrontendLambda:FrontendLambdaAlias
2021-06-13 15:15:34,934 | Found '4' APIs in resource 'ApiGatewayApi'
2021-06-13 15:15:34,934 | Found '2' API Events in Serverless function with name 'FrontendLambda'
2021-06-13 15:15:34,934 | Removed duplicates from '6' Explicit APIs and '0' Implicit APIs to produce '2' APIs
2021-06-13 15:15:34,934 | 2 APIs found in the template
2021-06-13 15:15:34,941 | Mounting FrontendLambda at http://127.0.0.1:3000/ [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
2021-06-13 15:15:34,942 | Mounting FrontendLambda at http://127.0.0.1:3000/{proxy+} [DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT]
2021-06-13 15:15:34,942 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2021-06-13 15:15:34,942 | Localhost server is starting up. Multi-threading = True
2021-06-13 15:15:34  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2021-06-13 15:18:09,775 | Constructed String representation of Event to invoke Lambda. Event: {"body": null, "headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "Accept-Encoding": "gzip, deflate, br", "Accept-Language": "en-US,en;q=0.9", "Cache-Control": "max-age=0", "Connection": "keep-alive", "Dnt": "1", "Host": "localhost:3000", "Sec-Ch-Ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\"", "Sec-Ch-Ua-Mobile": "?0", "Sec-Fetch-Dest": "document", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "none", "Sec-Fetch-User": "?1", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Cache-Control": ["max-age=0"], "Connection": ["keep-alive"], "Dnt": ["1"], "Host": ["localhost:3000"], "Sec-Ch-Ua": ["\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"91\", \"Chromium\";v=\"91\""], "Sec-Ch-Ua-Mobile": ["?0"], "Sec-Fetch-Dest": ["document"], "Sec-Fetch-Mode": ["navigate"], "Sec-Fetch-Site": ["none"], "Sec-Fetch-User": ["?1"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "localhost:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/", "protocol": "HTTP/1.1", "requestId": "186039ad-f326-4c5c-a8f4-c8064c380494", "requestTime": "13/Jun/2021:22:15:34 +0000", "requestTimeEpoch": 1623622534, "resourceId": "123456", "resourcePath": "/", "stage": "default"}, "resource": "/", "stageVariables": null, "version": "1.0"}
2021-06-13 15:18:09,775 | Found one Lambda function with name 'FrontendLambda'
2021-06-13 15:18:09,775 | Invoking main.handler (nodejs12.x)
2021-06-13 15:18:09,776 | Environment variables overrides data is standard format
2021-06-13 15:18:09,776 | Loading AWS credentials from session with profile 'None'
2021-06-13 15:18:09,788 | Resolving code path. Cwd=/dev/project/modules/frontend/.sam-build, CodeUri=/dev/project/modules/frontend/.sam-build/FrontendLambda
2021-06-13 15:18:09,788 | Resolved absolute path to code is /dev/project/modules/frontend/.sam-build/FrontendLambda
2021-06-13 15:18:09,788 | Code /dev/project/modules/frontend/.sam-build/FrontendLambda is not a zip/jar file
2021-06-13 15:18:09,788 | arn:aws:lambda:us-west-1:580247275435:layer:LambdaInsightsExtension:14 is already cached. Skipping download
2021-06-13 15:18:09,807 | Skip pulling image and use local one: samcli/lambda:nodejs12.x-9d5c439e26f1965d5376469ff.

2021-06-13 15:18:09,807 | Mounting /dev/project/modules/frontend/.sam-build/FrontendLambda as /var/task:ro,delegated inside runtime container
2021-06-13 15:18:12,964 | Starting a timer for 15 seconds for function 'FrontendLambda'
START RequestId: 829282c5-28e7-471c-a097-2bd839342858 Version: $LATEST
2021-06-13T22:18:13.063Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'main'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'main'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:100:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:999:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)","    at Module.load (internal/modules/cjs/loader.js:863:32)","    at Function.Module._load (internal/modules/cjs/loader.js:708:14)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)","    at internal/main/run_main_module.js:17:47"]}
time="2021-06-13T22:18:13.075" level=panic msg="ReplyStream not available"
2021/06/13 22:18:13 http: panic serving 127.0.0.1:54246: &{0xc0000f6000 map[] 2021-06-13 22:18:13.0756118 +0000 UTC m=+0.112672001 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0001b61e0)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc000232070)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc0000f6000, 0xc00001ea50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc000232000, 0xc000000000, 0xc000337588, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc0000f6000, 0xc000000000, 0xc000337588, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
go.amzn.com/lambda/rapi/rendering.RenderInteropError(0x9097c0, 0xc00007a0e0, 0xc00021c300, 0x902b60, 0xc00005e2f0)
        /LambdaRuntimeLocal/lambda/rapi/rendering/rendering.go:292 +0x9a
go.amzn.com/lambda/rapi/handler.(*initErrorHandler).ServeHTTP(0xc00005e0b0, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /LambdaRuntimeLocal/lambda/rapi/handler/initerror.go:52 +0x519
net/http.HandlerFunc.ServeHTTP(0xc00000c3c0, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000068120, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00005e040, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.RuntimeReleaseMiddleware.func1.1(0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:100 +0xea
net/http.HandlerFunc.ServeHTTP(0xc00000c1c0, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AccessLogMiddleware.func1.1(0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:77 +0x170
net/http.HandlerFunc.ServeHTTP(0xc00000c1e0, 0x9097c0, 0xc00007a0e0, 0xc00021c300)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AppCtxMiddleware.func1.1(0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:66 +0x77
net/http.HandlerFunc.ServeHTTP(0xc00001e300, 0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000068120, 0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x118
net/http.HandlerFunc.ServeHTTP(0xc00000c420, 0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0000680c0, 0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00005e0d0, 0x9097c0, 0xc00007a0e0, 0xc00021c200)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0000680c0, 0x9097c0, 0xc00007a0e0, 0xc0001c6500)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2b2
net/http.serverHandler.ServeHTTP(0xc00007a000, 0x9097c0, 0xc00007a0e0, 0xc0001c6500)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0001b61e0, 0x90a800, 0xc0001c2280)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c
2021-06-13T22:18:13.077Z        undefined       ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (internal/errors.js:609:14)","    at Socket.socketOnEnd (_http_client.js:458:23)","    at Socket.emit (events.js:326:22)","    at endReadableNT (_stream_readable.js:1241:12)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]}
time="2021-06-13T22:18:13.085" level=error msg="Init failed" InvokeID= error="Runtime exited with error: exit status 129"
time="2021-06-13T22:18:13.086" level=error msg="INIT DONE failed: Runtime.ExitError"
2021-06-13 15:18:13,584 | Unable to find Click Context for getting session_id.
2021-06-13 15:18:13,585 | Invalid lambda response received: Lambda response must be valid json
2021-06-13 15:18:13 127.0.0.1 - - [13/Jun/2021 15:18:13] "GET / HTTP/1.1" 502 -
```

### Expected result:
`sam local start-api` should work with the output of `sam build` without issue, loading the source code into `/var/task`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: 11.3.1
2. `sam --version`: 1.24.1
3. AWS region: us-west-1

`Add --debug flag to command you are running`

**Comment by abecks** [comment]
Closing as this appears to actually be Docker and possibly Big Sur related. Docker inspect reveals the correct folder is mounted as a volume, yet it still appears empty. Will report back in case anyone else has this issue in the future.

**Comment by mattparrilla** [comment]
@abecks would love that report! How did you resolve?

**Comment by abecks** [comment]
> @abecks would love that report! How did you resolve?

Was a while ago and I don't exactly remember but I believe it was related to a setting in Docker using experimental virtualization in MacOS and I either turned it off or on.  Sorry I can't be more helpful.
