### ISSUE TITLE
Running `sam build` for a CDK Dockerfile gives `TypeError: expected str, bytes or os.PathLike object, not NoneType`

### ISSUE THREAD

**Issue by matt-dalton** [aws/aws-sam-cli#2961]
This is either a bug or I'm doing something wrong.
### Description:
I'm trying to run `sam build --use-container` on a template I've created from CDK for a dockerised lambda. When I try and build it, I get:

```
Starting Build inside a container
Building codeuri: /Users/me/projects/cdk-sam-example runtime: None metadata: {'aws:cdk:path': 'CdkSamExampleStack/GetExchanges/Resource'} functions: ['GetExchanges5D09AEEB']
Building image for GetExchanges5D09AEEB function
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 210, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 315, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 169, in build
    return build_strategy.build()
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 41, in build
    result.update(self._build_functions(self._build_graph))
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 52, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 118, in build_single_function_definition
    result = self._build_function(
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 500, in _build_function
    return self._build_lambda_image(function_name=function_name, metadata=metadata)  # type: ignore
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 322, in _build_lambda_image
    docker_context_dir = pathlib.Path(self._base_dir, docker_context).resolve()
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 1041, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 682, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/Cellar/python@3.8/3.8.7/Frameworks/Python.framework/Versions/3.8/lib/python3.8/pathlib.py", line 666, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Steps to reproduce:
I'm basically following [these instructions](https://docs.aws.amazon.com/cdk/latest/guide/sam.html), except I've chosen python as my template language.

At step 3, instead of adding the recommended code I've added 
```
PROJECT_ROOT = "/".join(__file__.split("/")[:-2]) # I checked and I get the same error if I hardcode this

aws_lambda.DockerImageFunction(
            self,
            'GetUrl',
            code=aws_lambda.DockerImageCode.from_image_asset(
                PROJECT_ROOT,
                cmd=["test_fn.get_url"]
            ),
            timeout=cdk.Duration.seconds(300)
        )
```

### Observed result:

Then I also added a Dockerfile to the root
```
FROM public.ecr.aws/lambda/python:3.8

# Taken from https://github.com/python-poetry/poetry/discussions/1879#discussioncomment-216865
ENV PYTHONUNBUFFERED=1 \
    # prevents python creating .pyc files
    PYTHONDONTWRITEBYTECODE=1 \
    # poetry
    # https://python-poetry.org/docs/configuration/#using-environment-variables
    POETRY_VERSION=1.1.6 \
    # make poetry install to this location
    POETRY_HOME="/opt/poetry" \
    # make poetry create the virtual environment in the project's root
    # it gets named `.venv`
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    # do not ask any interactive question
    POETRY_NO_INTERACTION=1 \
    \
    # paths
    # this is where our requirements + virtual environment will live
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"


# prepend poetry and venv to path
ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3.8 -

COPY pyproject.toml ./
COPY poetry.lock ./
COPY financial_data financial_data

RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

# Command can be overwritten by providing a different command in the template directly.
CMD ["test_fn.get_url"]
```

Then instead of step 8 I want to create a local image using `sam build --use-container`, but I get the error above.

### Expected result:
I would expect the container to build. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`:SAM CLI, version 1.24.1
3. AWS region: eu-west-1

`Add --debug flag to command you are running`
Before error above:
```
2021-06-16 17:32:29,477 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-16 17:32:29,478 | Using config file: samconfig.toml, config environment: default
2021-06-16 17:32:29,478 | Expand command line arguments to:
2021-06-16 17:32:29,478 | --template_file=/Users/me/projects/cdk-sam-example/template.yaml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2021-06-16 17:32:29,613 | 'build' command is called
2021-06-16 17:32:29,613 | Starting Build inside a container
2021-06-16 17:32:29,632 | No Parameters detected in the template
2021-06-16 17:32:29,680 | 3 stacks found in the template
2021-06-16 17:32:29,680 | No Parameters detected in the template
2021-06-16 17:32:29,706 | 3 resources found in the stack 
2021-06-16 17:32:29,706 | No Parameters detected in the template
2021-06-16 17:32:29,728 | Found Lambda function with name='GetUrlB1312616' and Imageuri='123456789012.dkr.ecr.us-east-1.localhost/aws-cdk/assets:5dce5eeacdadf9e8bc6b195422c4cc6681b8218b8d1f6abd77565b9915e2b521'
2021-06-16 17:32:29,728 | --base-dir is not presented, adjusting uri . relative to /Users/me/projects/cdk-sam-example/template.yaml
2021-06-16 17:32:29,728 | No Parameters detected in the template
2021-06-16 17:32:29,755 | Instantiating build definitions
2021-06-16 17:32:29,759 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(None, /Users/me/projects/cdk-sam-example, Image, , 5f99c0dd-5db2-4d1e-a655-d8ccf8612f54, {'aws:cdk:path': 'CdkSamExampleStack/GetUrl/Resource'}, {}, []), Function: Function(name='GetUrlB1312616', functionname='GetUrlB1312616', runtime=None, memory=None, timeout=300, handler=None, imageuri='1000000000.dkr.ecr.us-east-1.localhost/aws-cdk/assets:5kjgkgkgkkjksfhafadfd77565b9915e2b521', packagetype='Image', imageconfig={'Command': ['test_fn.get_url']}, codeuri='/Users/me/projects/cdk-sam-example', environment=None, rolearn='arn:aws:lambda:us-east-1:123456789012:function:GetUrlServiceRole998E7A6C', layers=[], events=None, metadata={'aws:cdk:path': 'CdkSamExampleStack/GetUrl/Resource'}, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-06-16 17:32:29,760 | Building codeuri: /Users/me/projects/cdk-sam-example runtime: None metadata: {'aws:cdk:path': 'CdkSamExampleStack/GetUrl/Resource'} functions: ['GetUrlB1312616']
2021-06-16 17:32:29,760 | Building to following folder /Users/me/projects/cdk-sam-example/.aws-sam/build/GetUrlB1312616
2021-06-16 17:32:29,760 | Building image for GetUrlB1312616 function
2021-06-16 17:32:29,760 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '249072dd-a03c-4d4c-9592-a0d7a76cdaad', 'installationId': 'f3850aeb-9f9a-4b6f-8665-5cce5b3c5ab7', 'sessionId': '9361157d-689e-4bc7-9c2b-3e28a0b660a1', 'executionEnvironment': 'CLI',
```

**Comment by hawflau** [comment]
Hi @matt-dalton, thanks for reporting. The instructions you followed does not work because CDK does not populate the required resource metadata for image-type Lambda function. I'd recommend you to try our [AWS SAM CLI with CDK integration](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk.html). After installing, you should be able to build by running:
```
sam-beta-cdk build
```

Please let us know if it works for you!

**Comment by hawflau** [comment]
Linking to the related GH issue on CDK - https://github.com/aws/aws-cdk/issues/14593
Closing this issue due to inactivity. Feel free to reopen if you still have questions.
