### ISSUE TITLE
sam-beta-cdk raises an error without any additional context

### ISSUE THREAD

**Issue by jabalsad** [aws/aws-sam-cli#2968]
### Description:
`sam-beta-cdk` raises an error when trying to `start-api` or `invoke` locally. I'm hoping I don't have to post the entire CDK stack template here because it is large.

### Steps to reproduce:
1. download and install: `brew install aws-sam-cli-beta-cdk` (osx)
2. run `sam-beta-cdk local start-api`

### Observed result:
```
› sam-beta-cdk local start-api --debug
2021-06-17 16:35:40,390 | Determining project type...
2021-06-17 16:35:40,390 | The project is a CDK project.
2021-06-17 16:35:40,434 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-06-17 16:35:40,439 | CDK Toolkit found at ./node_modules/aws-cdk/bin/cdk
2021-06-17 16:35:40,439 | Synthesizing CDK App
2021-06-17 16:35:40,439 | command: ['./node_modules/aws-cdk/bin/cdk', 'synth', '--no-staging', '-o', '.aws-sam/.cdk-out']
2021-06-17 16:35:51,424 | Cloud assembly synthed at .aws-sam/.cdk-out
2021-06-17 16:35:51,424 | _validate_cloud_assembly: .aws-sam/.cdk-out
2021-06-17 16:35:51,431 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'c87edbda-20b4-4869-9a03-c866c6fc96f7', 'installationId': '4d5c1751-ca4e-4c25-8c05-f33973bc5430', 'sessionId': '37acf4f4-8fd2-4b40-a68e-67100f4fa95a', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.10', 'samcliVersion': '1.22.0.dev202104291816', 'metricSpecificAttributes': {'projectType': 'CDK'}, 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam-beta-cdk local start-api', 'duration': 10994, 'exitReason': 'KeyError', 'exitCode': 255}}]}
2021-06-17 16:35:51,670 | Telemetry response: 200
Traceback (most recent call last):
  File "/usr/local/bin/sam-beta-cdk", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 174, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 141, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/utils/helpers.py", line 30, in wrapper
    project = iac_plugin.get_project(lookup_paths)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 116, in get_project
    project = self._get_project_from_cloud_assembly(cloud_assembly_dir)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 207, in _get_project_from_cloud_assembly
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 207, in <listcomp>
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 222, in _build_stack
    self._build_resources_section(assets, ca_stack, cloud_assembly, section, section_dict)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202104291816/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 280, in _build_resources_section
    asset = assets[asset_path]
KeyError: '/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.92b31737b3dd47bb510f50634eaec000886b4a4c4988aa68e481619a4c928163'
```

### Expected result:
It starts the API

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: OSX
2. `sam --version`: `SAM CLI, version 1.22.0.dev202104291816``
3. AWS region: `us-east-1`

`Add --debug flag to command you are running`

**Comment by wchengru** [comment]
hey @jabalsad , thanks for reporting this issue!
To help us figuring out the root cause, can you please check what asset is under path `{your project path}/.aws-sam/.cdk-out/asset.92b31737b3dd47bb510f50634eaec000886b4a4c4988aa68e481619a4c928163'`
And also, can you please run `cat {your project path}/.aws-sam/.cdk-out/*.template.json | grep aws:asset:path` so that we can see if the metadate in template file is correct?

**Comment by jabalsad** [comment]
There is a `index.js` file under that asset path (it's 12,000 lines so didn't want to paste here).

```
› cat .aws-sam/.cdk-out/*.template.json | grep aws:asset:path
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.69aeff140f3d9ca35d661fd9af358cbaa3776d1b98579cafff700bd664e01176",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.69aeff140f3d9ca35d661fd9af358cbaa3776d1b98579cafff700bd664e01176",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.69aeff140f3d9ca35d661fd9af358cbaa3776d1b98579cafff700bd664e01176",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.69aeff140f3d9ca35d661fd9af358cbaa3776d1b98579cafff700bd664e01176",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.69aeff140f3d9ca35d661fd9af358cbaa3776d1b98579cafff700bd664e01176",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/.aws-sam/.cdk-out/asset.92b31737b3dd47bb510f50634eaec000886b4a4c4988aa68e481619a4c928163",
        "aws:asset:path": "/Users/jleroux/w/stedi/go/src/github.com/stedi/LedgerService/node_modules/@aws-cdk/custom-resources/lib/provider-framework/runtime",
```

**Comment by wchengru** [comment]
Thanks @jabalsad ! How large is your `cdk.json` file? Do you mind sharing the content if it isn't too large or not containing any private content.

**Comment by jabalsad** [comment]
The `cdk.json` file is small:

```
{
  "app": "npx ts-node ./bin/app.ts",
  "context": {
    "@aws-cdk/core:enableStackNameDuplicates": true,
    "@aws-cdk/core:newStyleStackSynthesis": true
  }
}
```

**Comment by jabalsad** [comment]
I'm guessing you're more interested in the actual template?

**Comment by straygar** [comment]
Not sure why, but this workaround at least allows you to continue using `sam-beta-cdk`:
```
"@aws-cdk/core:newStyleStackSynthesis": false
```

**Comment by grifhammeramazon** [comment]
I have run into this same issue when trying to run `sam-beta-cdk build --cdk-app "npx ts-node bin/test.ts"`.

**Comment by pseudo-su** [comment]
I've also run into this issue when trying to use `sam-beta-cdk` to run my golang serverless application locally

The branch where I'm trying to convert to using the CDK on the my project is here. Using `newStyleStackSynthesis ` has not helped me.

https://github.com/pseudo-su/golang-serverless-cdk-template/pull/1

**Comment by moelasmar** [comment]
SAM CLI's CDK support went into GA yesterday with some changes. Now sam-cli won't run cdk but user will have to run and provide the path. This should solve this problem. Please let us know if you have more questions.
Please find more details [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-getting-started.html)
