### ISSUE TITLE
Could not connect to the endpoint URL (to S3 bucket) on sam package command

### ISSUE THREAD

**Issue by hv-rruiz** [aws/aws-sam-cli#2977]
### Description:

Hi all,

I'm running into an issue when running the **package** command.

When running the command, it'll fail w/ a: 
_socket.gaierror: [Errno 8] nodename nor servname provided, or not known error_.

It will also try to connect to a S3 bucket location where the URL is slightly modified, which is making it break.
Could not connect to the endpoint URL: _"https://devops-artifacts-bucket-UUID.s3.us-west-2export.amazonaws.com/services/service/b647ec2f33bbee9203714052fb139f8a"_
Where _export_ is getting inserted into the url, which is invalid, and is breaking the process.

### Steps to reproduce:

sam package --template_file=/location/to/template.yaml --output_template_file=deploy/packaged.yaml --s3_bucket=devops-artifacts-bucket-UUID --s3_prefix=services/service-here

### Observed result:

```bash
2021-06-23 10:05:08,445 | Unable to export
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/opt/homebrew/Cellar/python@3.8/3.8.10/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 323, in send
    urllib_response = conn.urlopen(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPSConnection object at 0x1071ebe50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 121, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/packageable_resources.py", line 143, in do_export
    uploaded_url = upload_local_artifacts(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/utils.py", line 172, in upload_local_artifacts
    return zip_and_upload(local_path, uploader, extension)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/utils.py", line 190, in zip_and_upload
    return uploader.upload_with_dedup(zip_file, precomputed_md5=md5_hash, extension=extension)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 145, in upload_with_dedup
    return self.upload(file_name, remote_path)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 87, in upload
    if not self.force_upload and self.file_exists(remote_path):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/samcli/lib/package/s3_uploader.py", line 159, in file_exists
    self.s3.head_object(Bucket=self.bucket_name, Key=remote_path)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/client.py", line 691, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/client.py", line 711, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
    should_retry = self._should_retry(attempt_number, response,
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
    checker_response = checker(attempt_number, response,
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
    return self._check_caught_exception(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 200, in _do_get_response
    http_response = self._send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 269, in _send
    return self.http_session.send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 352, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: 
"https://devops-artifacts-bucket-UUID.s3.us-west-2export.amazonaws.com/services/service/b647ec2f33bbee9203714052fb139f8a"
2021-06-23 10:05:08,462 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '8630bbe1-b89f-4d82-ac3a-eb4fe0a71291', 
'installationId': 'ba07de02-088e-4467-90e5-a1b1091e51c8', 'sessionId': 'c230e60f-d293-4571-84f4-3453d408220a', 'executionEnvironment': 'CLI', 'ci': False, 
'pyversion': '3.8.10', 'samcliVersion': '1.24.1', 'awsProfileProvided': False, 
'debugFlagProvided': True, 'region': '', 'commandName': 'sam package', 'duration': 16820, 
'exitReason': 'ExportFailedError', 'exitCode': 1}}]}
2021-06-23 10:05:08,719 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Unable to upload artifact ./deploy/dependencies referenced by ContentUri parameter of DependenciesLayer resource.
Could not connect to the endpoint URL: 
"https://devops-artifacts-bucket-UUID.s3.us-west-2export.amazonaws.com/services/service/b647ec2f33bbee9203714052fb139f8a"
```

### Expected result:

The package command to work, and all artifacts upload to the S3 bucket. 
This was working previously. It could be an issue w/ macOS and a recent update.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur v11.2.2 (M1)
2. `sam --version`: SAM CLI, version 1.24.1
3. AWS region: us-west-2

Any ideas as to what could be causing this behavior? Thank you!

**Comment by hv-rruiz** [comment]
Turns out the AWS_DEFAULT_REGION env variable was edited locally on my machine, which messed up the url. Sorry for the post!
