### ISSUE TITLE
"Please install sqlite3 package manually" but I have installed it.

### ISSUE THREAD

**Issue by tylerlong** [aws/aws-sam-cli#3013]
### Description:

"Please install sqlite3 package manually" but I have installed it.

### Steps to reproduce:

https://github.com/tylerlong/sam-app-demo

```
sam build && sam local invoke NewFunction -e events/event.json
```

### Observed result:

```
sam build && sam local invoke NewFunction -e events/event.json --debug
Building codeuri: /Users/tyler.liu/src/ts/sam-app-demo/hello-world runtime: nodejs14.x metadata: {} functions: ['HelloWorldFunction', 'NewFunction']
Running NodejsNpmBuilder:NpmPack
Running NodejsNpmBuilder:CopyNpmrc
Running NodejsNpmBuilder:CopySource
Running NodejsNpmBuilder:NpmInstall
Running NodejsNpmBuilder:CleanUpNpmrc

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided
    
2021-07-01 12:08:51,366 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-01 12:08:51,366 | Using config file: samconfig.toml, config environment: default
2021-07-01 12:08:51,366 | Expand command line arguments to:
2021-07-01 12:08:51,366 | --template_file=/Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/template.yaml --event=events/event.json --function_logical_id=NewFunction --no_event --layer_cache_basedir=/Users/tyler.liu/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2021-07-01 12:08:51,367 | local invoke command is called
2021-07-01 12:08:51,375 | No Parameters detected in the template
2021-07-01 12:08:51,416 | 3 stacks found in the template
2021-07-01 12:08:51,417 | No Parameters detected in the template
2021-07-01 12:08:51,440 | 3 resources found in the stack 
2021-07-01 12:08:51,440 | No Parameters detected in the template
2021-07-01 12:08:51,463 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-07-01 12:08:51,463 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to /Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/template.yaml
2021-07-01 12:08:51,464 | Found Serverless function with name='NewFunction' and CodeUri='NewFunction'
2021-07-01 12:08:51,464 | --base-dir is not presented, adjusting uri NewFunction relative to /Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/template.yaml
2021-07-01 12:08:51,474 | Found one Lambda function with name 'NewFunction'
2021-07-01 12:08:51,474 | Invoking app.newHandler (nodejs14.x)
2021-07-01 12:08:51,474 | Environment variables overrides data is standard format
2021-07-01 12:08:51,474 | Loading AWS credentials from session with profile 'None'
2021-07-01 12:08:51,486 | Resolving code path. Cwd=/Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build, CodeUri=/Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/NewFunction
2021-07-01 12:08:51,486 | Resolved absolute path to code is /Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/NewFunction
2021-07-01 12:08:51,486 | Code /Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/NewFunction is not a zip/jar file
2021-07-01 12:08:51,503 | Skip pulling image and use local one: amazon/aws-sam-cli-emulation-image-nodejs14.x:rapid-1.24.1.

2021-07-01 12:08:51,503 | Mounting /Users/tyler.liu/src/ts/sam-app-demo/.aws-sam/build/NewFunction as /var/task:ro,delegated inside runtime container
2021-07-01 12:08:52,003 | Starting a timer for 3 seconds for function 'NewFunction'
START RequestId: 532ba6d5-3ed1-4674-8b18-e9d14a041740 Version: $LATEST
2021-07-01T19:08:53.741Z        undefined       ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"Please install sqlite3 package manually","stack":["Error: Please install sqlite3 package manually","    at ConnectionManager._loadDialectModule (/var/task/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:88:15)","    at new ConnectionManager (/var/task/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)","    at new SqliteDialect (/var/task/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)","    at new Sequelize (/var/task/node_modules/sequelize/lib/sequelize.js:334:20)","    at Object.<anonymous> (/var/task/node_modules/ringcentral-chatbot/dist/models/sequelize.js:12:19)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:14)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:92:18)","    at Object.<anonymous> (/var/task/node_modules/ringcentral-chatbot/dist/models/Bot.js:16:42)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:14)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:92:18)","    at Object.<anonymous> (/var/task/node_modules/ringcentral-chatbot/dist/models/index.js:19:12)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)"]}
time="2021-07-01T19:08:53.747" level=panic msg="ReplyStream not available"
2021/07/01 19:08:53 http: panic serving 127.0.0.1:50584: &{0xc00013e000 map[] 2021-07-01 19:08:53.747549909 +0000 UTC m=+1.748889415 panic <nil> ReplyStream not available <nil> <nil> }
goroutine 41 [running]:
net/http.(*conn).serve.func1(0xc0000be1e0)
        /usr/local/go/src/net/http/server.go:1800 +0x139
panic(0x866640, 0xc0000ee0e0)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/sirupsen/logrus.Entry.log(0xc00013e000, 0xc0000a2330, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:259 +0x335
github.com/sirupsen/logrus.(*Entry).Log(0xc0000ee000, 0xc000000000, 0xc0000f7588, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/entry.go:287 +0xeb
github.com/sirupsen/logrus.(*Logger).Log(0xc00013e000, 0xc000000000, 0xc0000f7588, 0x1, 0x1)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:193 +0x7d
github.com/sirupsen/logrus.(*Logger).Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/logger.go:234
github.com/sirupsen/logrus.Panic(...)
        /go/pkg/mod/github.com/sirupsen/logrus@v1.6.0/exported.go:129
go.amzn.com/lambda/rapi/rendering.RenderInteropError(0x9097c0, 0xc0000dc1c0, 0xc0000d4500, 0x902b60, 0xc0000961a0)
        /LambdaRuntimeLocal/lambda/rapi/rendering/rendering.go:292 +0x9a
go.amzn.com/lambda/rapi/handler.(*initErrorHandler).ServeHTTP(0xc00018c0a0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /LambdaRuntimeLocal/lambda/rapi/handler/initerror.go:52 +0x519
net/http.HandlerFunc.ServeHTTP(0xc000182380, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc000180120, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00018c030, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.RuntimeReleaseMiddleware.func1.1(0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:100 +0xea
net/http.HandlerFunc.ServeHTTP(0xc000182180, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AccessLogMiddleware.func1.1(0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:77 +0x170
net/http.HandlerFunc.ServeHTTP(0xc0001821a0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4500)
        /usr/local/go/src/net/http/server.go:2041 +0x44
go.amzn.com/lambda/rapi/middleware.AppCtxMiddleware.func1.1(0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /LambdaRuntimeLocal/lambda/rapi/middleware/middleware.go:66 +0x77
net/http.HandlerFunc.ServeHTTP(0xc00018a2d0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc000180120, 0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:70 +0x513
github.com/go-chi/chi.(*Mux).Mount.func1(0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:298 +0x118
net/http.HandlerFunc.ServeHTTP(0xc0001823e0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).routeHTTP(0xc0001800c0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:431 +0x278
net/http.HandlerFunc.ServeHTTP(0xc00018c0c0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4400)
        /usr/local/go/src/net/http/server.go:2041 +0x44
github.com/go-chi/chi.(*Mux).ServeHTTP(0xc0001800c0, 0x9097c0, 0xc0000dc1c0, 0xc0000d4300)
        /go/pkg/mod/github.com/go-chi/chi@v4.1.2+incompatible/mux.go:86 +0x2b2
net/http.serverHandler.ServeHTTP(0xc00019a000, 0x9097c0, 0xc0000dc1c0, 0xc0000d4300)
        /usr/local/go/src/net/http/server.go:2836 +0xa3
net/http.(*conn).serve(0xc0000be1e0, 0x90a800, 0xc0000c22c0)
        /usr/local/go/src/net/http/server.go:1924 +0x86c
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2962 +0x35c
2021-07-01T19:08:53.749Z        undefined       ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"socket hang up","code":"ECONNRESET","stack":["Error: socket hang up","    at connResetException (internal/errors.js:628:14)","    at Socket.socketOnEnd (_http_client.js:499:23)","    at Socket.emit (events.js:387:35)","    at endReadableNT (internal/streams/readable.js:1317:12)","    at processTicksAndRejections (internal/process/task_queues.js:82:21)"]}
time="2021-07-01T19:08:53.759" level=error msg="Init failed" InvokeID= error="Runtime exited with error: exit status 129"
time="2021-07-01T19:08:53.76" level=error msg="INIT DONE failed: Runtime.ExitError"
2021-07-01 12:08:53,956 | Cleaning all decompressed code dirs
2021-07-01 12:08:53,958 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'a21fc39b-d5d8-4975-8933-08bbbc776389', 'installationId': 'c6e31722-acda-4282-a011-7dcd88ad68ea', 'sessionId': '5f450b72-fb5e-4c21-8d48-6a5be40d5f6b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.24.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'duration': 2591, 'exitReason': 'success', 'exitCode': 0}}]}
2021-07-01 12:08:55,143 | Telemetry response: 200
2021-07-01 12:08:55,144 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-01 12:08:55,144 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': '5d22ca34-18ce-4443-b9f8-8df7337434e2', 'installationId': 'c6e31722-acda-4282-a011-7dcd88ad68ea', 'sessionId': '5f450b72-fb5e-4c21-8d48-6a5be40d5f6b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.24.1', 'runtimes': ['nodejs14.x']}}]}
2021-07-01 12:08:55,375 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:

Not sure but at least is should NOT complain "Please install sqlite3 package manually".

I have installed it already: https://github.com/tylerlong/sam-app-demo/blob/main/hello-world/package.json#L14

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 10.14.6
2. `sam --version`: SAM CLI, version 1.24.1
3. AWS region: local test only

`Add --debug flag to command you are running`

**Comment by tylerlong** [comment]
And the code works well without SAM. So I believe it is a sam env issue.
