### ISSUE TITLE
Partial Credential Error

### ISSUE THREAD

**Issue by adityarai** [aws/aws-sam-cli#3017]
Hi, I'm new to serverless architecture. I have installed aws sam, sam init hello world example and build the code. When I run sam local start-api and hit the url in the browser I get the 500 error and PartialCredentialsError in cli.
I have aws_access_key_id and  aws_secret_access_key configured in ~/.aws/credentials
I'm using Ubuntu 20.04
SAM CLI, version 1.24.1
aws-cli/2.2.13 Python/3.8.8 Linux/5.8.0-59-generic exe/x86_64.ubuntu.20 prompt/off

Error:

sam validate --debug
2021-07-04 17:47:40,889 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-04 17:47:40,889 | Using config file: samconfig.toml, config environment: default
2021-07-04 17:47:40,889 | Expand command line arguments to:
2021-07-04 17:47:40,889 | --template_file=/home/adi/Documents/projects/sam-app/template.yaml 
2021-07-04 17:47:40,949 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '74bc2465-a5bf-4b26-ab2c-19a48fedff65', 'installationId': 'a2c68812-31ae-43b2-b9ae-e631963e22b1', 'sessionId': 'bcd80e66-14a4-434f-be22-79df123d7033', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.24.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'duration': 59, 'exitReason': 'PartialCredentialsError', 'exitCode': 255}}]}
2021-07-04 17:47:42,411 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 153, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 90, in wrapper
  File "samcli/commands/validate/validate.py", line 37, in cli
  File "samcli/commands/validate/validate.py", line 53, in do_cli
  File "boto3/__init__.py", line 93, in client
  File "boto3/session.py", line 263, in client
  File "botocore/session.py", line 826, in create_client
  File "botocore/session.py", line 431, in get_credentials
  File "botocore/credentials.py", line 1975, in load_credentials
  File "botocore/credentials.py", line 1102, in load
  File "botocore/credentials.py", line 1137, in fetch_credentials
botocore.exceptions.PartialCredentialsError: Partial credentials found in env, missing: AWS_SECRET_ACCESS_KEY
[117996] Failed to execute script __main_

**Comment by wchengru** [comment]
Hi @adityarai , it seems that your credential configuration is not complete. Can you please try `aws configure` with AWS CLI to set the credentials up, and then run `echo $AWS_SECRET_ACCESS_KEY` to verify it?

**Comment by adityarai** [comment]
Hi @wchengru , I have set up the credentials again and when I run echo $AWS_SECRET_ACCESS_KEY, nothing displays.
![Screen-07-05 14-18-35](https://user-images.githubusercontent.com/1521692/124444504-4bb93e00-dd9c-11eb-903e-39d60161b720.png)

**Comment by wchengru** [comment]
Can you please try setting the credentials as environment variables as this document? https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html

**Comment by moelasmar** [comment]
Hello @adityarai 
If you still have any questions, please reopen the issue.
