### ISSUE TITLE
SAM container build fails if started from a sibling container

### ISSUE THREAD

**Issue by paul-michalik** [aws/aws-sam-cli#3062]
### Description:

Running custom build type (`makefile`) with `sam build --use-container` from within a container (sibling container) fails with the message `Error: CustomMakeBuilder:MakeBuild - Makefile not found at /tmp/samcli/source/Makefile`  . The same command suceeds if run on the host system directly. 

### Steps to reproduce:

1. Create a Linux container image (called `dev-image` in this report) that contains all tools required to run AWS SAM and build and deploy .NET 5.0 and C++ Lambda functions using custom (provided) Lambda runtime.
2. On a Linux or Windows host system (does not matter) start the container from `dev-image` and mount the source code into the container. Forward the communication socket from the host system to allow running sibling containers: `docker run -v /var/run/docker.sock:/var/run/docker.sock`. Make sure the file system permissions of the source code and the Unix socket are sufficent to run sibling containers on the host system.
3. In the `dev-image` container (or on the host system, does not really matter) build a container image `sam-builder-image` (for sake of the bug report) based on `public.ecr.aws/sam/build-provided.al2` that will be used by SAM to build the Lambdas. The image contains .NET 5.0 SDK, C++ tools and compilers, etc.
3. In the `dev-image` container run `sam build <other-options-irrelevant-for-this-report> --use-container sam-builder-image` using the Makefile method.  

### Observed result:

```
2021-07-15 10:45:59,445 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-15 10:45:59,447 | Using config file: samconfig.toml, config environment: default
2021-07-15 10:45:59,447 | Expand command line arguments to:
2021-07-15 10:45:59,447 | --template_file=/home/developer/wrk/navvis.map.srv.taskrunner/template.yaml --build_dir=/tmp/navvis.map.srv.taskrunner/build/dev-map-5794/Unix/.aws-sam --cache_dir=/tmp/navvis.map.srv.taskrunner/build/dev-map-5794/Unix/.aws-sam/cache --use_container --build_image=('navvisgmbh/build-dotnet-5.0:latest',) --resource_logical_id=TaskrunnerApiCreateTask 
2021-07-15 10:45:59,496 | 'build' command is called
2021-07-15 10:45:59,497 | Starting Build inside a container
2021-07-15 10:45:59,569 | Collected default values for parameters: {'ParCustomDomain': 'None', 'ParBasePath': '', 'ParDotnetRuntimeVersion': 5.0}
2021-07-15 10:45:59,616 | Unable to resolve property DestinationArn: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiLogs.Arn')]). Leaving as is.
2021-07-15 10:45:59,617 | Unable to resolve property Stream: OrderedDict([('Fn::GetAtt', 'Tasks.StreamArn')]). Leaving as is.
2021-07-15 10:45:59,618 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'Tasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,619 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleBatchEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,619 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleDbStreamEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,620 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiCreateTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,620 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiDeleteTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,621 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,621 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,622 | 14 stacks found in the template
2021-07-15 10:45:59,622 | Collected default values for parameters: {'ParCustomDomain': 'None', 'ParBasePath': '', 'ParDotnetRuntimeVersion': 5.0}
2021-07-15 10:45:59,666 | Unable to resolve property DestinationArn: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiLogs.Arn')]). Leaving as is.
2021-07-15 10:45:59,668 | Unable to resolve property Stream: OrderedDict([('Fn::GetAtt', 'Tasks.StreamArn')]). Leaving as is.
2021-07-15 10:45:59,669 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'Tasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,669 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleBatchEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,669 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleDbStreamEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,670 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiCreateTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,670 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiDeleteTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,671 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,671 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,671 | 14 resources found in the stack 
2021-07-15 10:45:59,672 | Collected default values for parameters: {'ParCustomDomain': 'None', 'ParBasePath': '', 'ParDotnetRuntimeVersion': 5.0}
2021-07-15 10:45:59,717 | Unable to resolve property DestinationArn: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiLogs.Arn')]). Leaving as is.
2021-07-15 10:45:59,719 | Unable to resolve property Stream: OrderedDict([('Fn::GetAtt', 'Tasks.StreamArn')]). Leaving as is.
2021-07-15 10:45:59,719 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'Tasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,720 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleBatchEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,720 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleDbStreamEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,720 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiCreateTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,721 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiDeleteTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,721 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,722 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,722 | Found Serverless function with name='TaskrunnerApiCreateTask' and CodeUri='.'
2021-07-15 10:45:59,722 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,724 | Found Serverless function with name='TaskrunnerApiDeleteTask' and CodeUri='.'
2021-07-15 10:45:59,724 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,726 | Found Serverless function with name='TaskrunnerApiGetTask' and CodeUri='.'
2021-07-15 10:45:59,726 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,728 | Found Serverless function with name='TaskrunnerApiGetTasks' and CodeUri='.'
2021-07-15 10:45:59,728 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,730 | Found Serverless function with name='TasksHandleDbStreamEvents' and CodeUri='.'
2021-07-15 10:45:59,730 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,732 | Found Serverless function with name='TasksHandleBatchEvents' and CodeUri='.'
2021-07-15 10:45:59,732 | --base-dir is not presented, adjusting uri . relative to /home/developer/wrk/navvis.map.srv.taskrunner/template.yaml
2021-07-15 10:45:59,734 | Collected default values for parameters: {'ParCustomDomain': 'None', 'ParBasePath': '', 'ParDotnetRuntimeVersion': 5.0}
2021-07-15 10:45:59,780 | Unable to resolve property DestinationArn: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiLogs.Arn')]). Leaving as is.
2021-07-15 10:45:59,782 | Unable to resolve property Stream: OrderedDict([('Fn::GetAtt', 'Tasks.StreamArn')]). Leaving as is.
2021-07-15 10:45:59,783 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'Tasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,783 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleBatchEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,784 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TasksHandleDbStreamEvents.Arn')]). Leaving as is.
2021-07-15 10:45:59,784 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiCreateTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,785 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiDeleteTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,785 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTask.Arn')]). Leaving as is.
2021-07-15 10:45:59,785 | Unable to resolve property Value: OrderedDict([('Fn::GetAtt', 'TaskrunnerApiGetTasks.Arn')]). Leaving as is.
2021-07-15 10:45:59,788 | Instantiating build definitions
2021-07-15 10:45:59,809 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(provided.al2, /home/developer/wrk/navvis.map.srv.taskrunner, Zip, , 6365a2da-47c0-4c55-bf1a-c96a588cbeee, {'BuildMethod': 'makefile'}, {}, []), Function: Function(name='TaskrunnerApiCreateTask', functionname='ParResourceNamePrefix-TaskrunnerApiCreateTask', runtime='provided.al2', memory=256, timeout=10, handler='bootstrap::Handler::CreateTaskAsync', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/developer/wrk/navvis.map.srv.taskrunner', environment=None, rolearn='ParHandleApiEventsLambdaExecRoleArn', layers=[], events={'TaskCreated': {'Type': 'Api', 'Properties': {'RestApiId': 'TaskrunnerApi', 'Method': 'POST', 'Path': '/tasks'}}}, metadata={'BuildMethod': 'makefile'}, inlinecode=None, codesign_config_arn=None, stack_path=''))
2021-07-15 10:45:59,809 | Building codeuri: /home/developer/wrk/navvis.map.srv.taskrunner runtime: provided.al2 metadata: {'BuildMethod': 'makefile'} functions: ['TaskrunnerApiCreateTask']
2021-07-15 10:45:59,810 | Building to following folder /tmp/navvis.map.srv.taskrunner/build/dev-map-5794/Unix/.aws-sam/TaskrunnerApiCreateTask
2021-07-15 10:46:02,146 | Failed to download image with name navvisgmbh/build-dotnet-5.0:latest
2021-07-15 10:46:02,147 | Failed to download a new navvisgmbh/build-dotnet-5.0:latest image. Invoking with the already downloaded image.
2021-07-15 10:46:02,148 | Mounting /home/developer/wrk/navvis.map.srv.taskrunner as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Running workflow 'CustomMakeBuilder'
Running CustomMakeBuilder:CopySource
CustomMakeBuilder:CopySource succeeded
Running CustomMakeBuilder:MakeBuild
CustomMakeBuilder:MakeBuild failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 73, in execute
    self.manifest_check()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 62, in manifest_check
    raise MakeFileNotFoundError("Makefile not found at {}".format(self.manifest_path))
aws_lambda_builders.workflows.custom_make.exceptions.MakeFileNotFoundError: Makefile not found at /tmp/samcli/source/Makefile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 75, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Makefile not found at /tmp/samcli/source/Makefile
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 73, in execute
    self.manifest_check()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 62, in manifest_check
    raise MakeFileNotFoundError("Makefile not found at {}".format(self.manifest_path))
aws_lambda_builders.workflows.custom_make.exceptions.MakeFileNotFoundError: Makefile not found at /tmp/samcli/source/Makefile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 75, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Makefile not found at /tmp/samcli/source/Makefile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: CustomMakeBuilder:MakeBuild - Makefile not found at /tmp/samcli/source/Makefile
2021-07-15 10:46:02,706 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "CustomMakeBuilder:MakeBuild - Makefile not found at /tmp/samcli/source/Makefile"}}

Build Failed
2021-07-15 10:46:03,010 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '6209b7ca-5685-4f29-bf08-087818de2536', 'installationId': '957fe48b-4b92-4b99-a4e7-d78c0b8c779b', 'sessionId': '7a1119ec-8c91-4656-914e-059b83873c21', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.11', 'samcliVersion': '1.26.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': 'eu-central-1', 'commandName': 'sam build', 'duration': 3562, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2021-07-15 10:46:03,778 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: CustomMakeBuilder:MakeBuild - Makefile not found at /tmp/samcli/source/Makefile
```

### Expected result:

Expected the build to succeed as if run on the host system, i.e. `sam build <other-options-irrelevant-for-this-report> --use-container sam-builder-image` succeeds on the host system but fails when started in running `dev-image` container.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 (using Docker Desktop with WSL2 backend), Ubuntu Linux 20.04, Ubuntu Linux 18.04 (in WSL2 and in a VM)
2. `sam --version`: SAM CLI, version 1.25.0
3. AWS region: eu-central-1

`Add --debug flag to command you are running`

**Comment by aahung** [comment]
duplicate: #2863
