### ISSUE TITLE
env.global.parameters break sam deploy

### ISSUE THREAD

**Issue by Indigenuity** [aws/aws-sam-cli#3089]
### Description:
Using `[stage.global.parameters]` or any other env name in `samconfig.toml` causes `sam deploy` to fail with an inscrutable error message

### Steps to reproduce:
Create a `samconfig.toml` with a blank line after version:

```
version = 0.1
[stage.global.parameters]
stack_name = "stage-auth-keys-cron"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-yadayada"
s3_prefix = "stage-auth-keys-cron"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides=[
  "SecurityGroupIds=stage-lambda-sg-ids",
  "SubnetIds=stage-private-app-subnet-ids",
  "TargetBucket=my-stage-bucket",
  "DbSecretName=my-stage-creds"
]
```
Then, run `sam deploy --config-env stage`.  Note that running `sam local invoke --config-env stage` does NOT break.  So `deploy` and `local invoke` have different behavior when parsing `samconfig.toml`

### Observed result:
```
% sam deploy --config-env stage --debug
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1257, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1589, in full_process_value
    value = self.process_value(ctx, value)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1579, in process_value
    return self.type_cast_value(ctx, value)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1568, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/core.py", line 1565, in _convert
    return self.type(value, self, ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.24.1/libexec/lib/python3.8/site-packages/click/types.py", line 412, in convert
    value = value.lower()
AttributeError: 'Bool' object has no attribute 'lower'
```

### Expected result:
I would expect `sam deploy` to be able to parse the same file as `sam local invoke`.  I would also expect `[env.global.parameters]` to cover the `deploy` command the same way `[env.deploy.parameters]` does.

And at the very least I would expect an error that tells you there was a problem when parsing `samconfig.toml`.  It took a long time to figure out how to reproduce the problem because there's no exception catching going on

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Big Sur
2. `sam --version`:
```
% sam --version
SAM CLI, version 1.24.1
```
3. AWS region: us-east-1

**Comment by mingkun2020** [comment]
Hi @Indigenuity, thanks for reporting but I cannot reproduce this issue locally, could you try it with the samcli's latest version?

**Comment by CoshUS** [comment]
Closing as this issue is inactive.
Feel free to leave more information below and I can reopen this issue.
