### ISSUE TITLE
[pipelines]: sam pipeline bootstrap crashes when resource creation starts

### ISSUE THREAD

**Issue by hffmnn** [aws/aws-sam-cli#3107]
### Description:

I ran `sam pipeline bootstrap`  to test the new pipeline feature. After answering all questions , the creation of the resources fails with

```
Should we proceed with the creation? [y/N]: y
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/commands/pipeline/bootstrap/cli.py", line 113, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/commands/pipeline/bootstrap/cli.py", line 205, in do_cli
    bootstrapped: bool = environment.bootstrap(confirm_changeset=confirm_changeset)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage.py", line 163, in bootstrap
    environment_resources_template_body = Stage._read_template(STAGE_RESOURCES_CFN_TEMPLATE)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage.py", line 226, in _read_template
    with open(template_path, "r", encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage_resources.yaml'
```

Looks like a template is missing.

### Steps to reproduce:

1. Run `sam pipeline bootstrap`
2. Answer questions
3. Proceed with resource creation

### Observed result:

```
sam pipeline bootstrap --debug                                                                                                                                                                                  
2021-07-22 09:59:57,646 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-07-22 09:59:57,647 | Using config file: samconfig.toml, config environment: default
2021-07-22 09:59:57,647 | Expand command line arguments to:
2021-07-22 09:59:57,647 | --interactive --confirm_changeset 

sam pipeline bootstrap generates the required AWS infrastructure resources to connect
to your CI/CD system. This step must be run for each deployment stage in your pipeline,
prior to running the sam pipeline init command.

We will ask for [1] stage definition, [2] account details, and
[3] references to existing resources in order to bootstrap these pipeline resources.

[1] Stage definition
Enter a name for this stage. This will be referenced later when you use the sam pipeline init command:
Stage name: dev

[2] Account details
The following AWS credential sources are available to use:
To know more about configuration AWS credentials, visit the link below:
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html                
	1 - ...
	2 - ...
	3 - ...
	4 - ...
	5 - ...
	6 - ...
        7 - ...
	8 - ...
	9 - ...
	10 - ...
	11 - ...
	12 - ...
	q - Quit and configure AWS credentials
Select a credential source to associate with this stage: 10
Enter MFA code for arn:aws:iam::<account>:mfa/<user>: 
Associated account <account> with stage dev.

Enter the region in which you want these resources to be created [eu-west-1]: 
Enter the pipeline IAM user ARN if you have previously created one, or we will create one for you []: 

[3] Reference application build resources
Enter the pipeline execution role ARN if you have previously created one, or we will create one for you []: 
Enter the CloudFormation execution role ARN if you have previously created one, or we will create one for you []: 
Please enter the artifact bucket ARN for your Lambda function. If you do not have a bucket, we will create one for you []: 
Does your application contain any IMAGE type Lambda functions? [y/N]: n

[4] Summary
Enter MFA code for arn:aws:iam::<account>:mfa/<user>: 
Below is the summary of the answers:
	1 - Account: <account>
	2 - Stage name: dev
	3 - Region: eu-west-1
	4 - Pipeline user: [to be created]
	5 - Pipeline execution role: [to be created]
	6 - CloudFormation execution role: [to be created]
	7 - Artifacts bucket: [to be created]
	8 - ECR image repository: [skipped]
Press enter to confirm the values above, or select an item to edit the value: 

This will create the following required resources for the 'dev' environment: 
	- Pipeline IAM user
	- Pipeline execution role
	- CloudFormation execution role
	- Artifact bucket
Should we proceed with the creation? [y/N]: y
2021-07-22 10:00:45,705 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'd3be4ee6-f9a1-4a9b-b3b6-a2358836c3e9', 'installationId': 'c1a9cde3-23bb-49d0-8b66-8d024db4d1d5', 'sessionId': '7c7c9631-38cc-497f-913a-388a532e716a', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.27.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam pipeline bootstrap', 'duration': 48056, 'exitReason': 'FileNotFoundError', 'exitCode': 255}}]}
2021-07-22 10:00:46,648 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/commands/pipeline/bootstrap/cli.py", line 113, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/commands/pipeline/bootstrap/cli.py", line 205, in do_cli
    bootstrapped: bool = environment.bootstrap(confirm_changeset=confirm_changeset)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage.py", line 163, in bootstrap
    environment_resources_template_body = Stage._read_template(STAGE_RESOURCES_CFN_TEMPLATE)
  File "/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage.py", line 226, in _read_template
    with open(template_path, "r", encoding="utf-8") as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/Cellar/aws-sam-cli/1.27.1/libexec/lib/python3.8/site-packages/samcli/lib/pipeline/bootstrap/stage_resources.yaml'
```

### Expected result:

The resources get created.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS 11.4
2. `sam --version`: SAM CLI, version 1.27.1 Installed via `brew`
3. AWS region: eu-west-1

**Comment by OperationalFallacy** [comment]
SAMe problem :(

**Comment by aahung** [comment]
Upgrading 1.27.2 solves this problem.

**Comment by hffmnn** [comment]
Thanks. That did it.
