### ISSUE TITLE
Adding resource of type AWS::SecretsManager::Secret causes deployment process to hang

### ISSUE THREAD

**Issue by keithaws** [aws/aws-sam-cli#3128]
### Description:

When adding a resource of type AWS::SecretsManager::Secret to template.yaml, the `sam deploy` command hangs at "Waiting for changeset to be created.." The process eventually times out and the deployment process does not complete. The stack created by SAM gets stuck in the "REVIEW_IN_PROGRESS" status in CloudFormation.

### Steps to reproduce:

Follow the steps on this page to create a sample Hello World application. I reproduced this with the nodejs14.x runtime:

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html

Before running `sam build`, add the following resource to template.yaml:

```yaml
ExampleKey:
    Type: AWS::SecretsManager:Secret
```

Attempt to run `sam deploy --guided` or `sam deploy` with a samconfig.toml file.

### Observed result:

The `sam deploy` command hangs at "Waiting for changeset to be created.." The `sam` process eventually crashes with a stack trace.

### Expected result:

The `sam deploy` command should deploy an application and create a new SecretsManager secret.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS
2. `sam --version`: 1.27.2
3. AWS region: Observed in us-west-2 and us-east-1

`Add --debug flag to command you are running` (Relevant part pasted)
```
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 290, in wait_for_changeset
    waiter.wait(ChangeSetName=changeset_id, StackName=stack_name, WaiterConfig=waiter_config)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 362, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter ChangeSetCreateComplete failed: Max attempts exceeded
```

**Comment by sriram-mv** [comment]
I just tried to reproduce this, but with a python app. I was not able to repro it.

```
Waiting for changeset to be created..

CloudFormation stack changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                           LogicalResourceId                                   ResourceType                                        Replacement
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                               ExampleKey                                          AWS::SecretsManager::Secret                         N/A
+ Add                                               HelloWorldFunctionHelloWorldPermissionProd          AWS::Lambda::Permission                             N/A
+ Add                                               HelloWorldFunctionRole                              AWS::IAM::Role                                      N/A
+ Add                                               HelloWorldFunction                                  AWS::Lambda::Function                               N/A
+ Add                                               ServerlessRestApiDeployment47fc2d5f9d               AWS::ApiGateway::Deployment                         N/A
+ Add                                               ServerlessRestApiProdStage                          AWS::ApiGateway::Stage                              N/A
+ Add                                               ServerlessRestApi                                   AWS::ApiGateway::RestApi                            N/A
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-west-2:xxxxxx:changeSet/samcli-deploy<xx>


2021-07-30 15:01:21 - Waiting for stack create/update to complete

CloudFormation events from changeset
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                      ResourceType                                        LogicalResourceId                                   ResourceStatusReason
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                                  AWS::IAM::Role                                      HelloWorldFunctionRole                              -
CREATE_IN_PROGRESS                                  AWS::SecretsManager::Secret                         ExampleKey                                          -
CREATE_IN_PROGRESS                                  AWS::IAM::Role                                      HelloWorldFunctionRole                              Resource creation Initiated
CREATE_IN_PROGRESS                                  AWS::SecretsManager::Secret                         ExampleKey                                          Resource creation Initiated
CREATE_COMPLETE                                     AWS::SecretsManager::Secret                         ExampleKey                                          -
CREATE_COMPLETE                                     AWS::IAM::Role                                      HelloWorldFunctionRole                              -
CREATE_IN_PROGRESS                                  AWS::Lambda::Function                               HelloWorldFunction                                  -
CREATE_IN_PROGRESS                                  AWS::Lambda::Function                               HelloWorldFunction                                  Resource creation Initiated
CREATE_COMPLETE                                     AWS::Lambda::Function                               HelloWorldFunction                                  -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::RestApi                            ServerlessRestApi                                   -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::RestApi                            ServerlessRestApi                                   Resource creation Initiated
CREATE_COMPLETE                                     AWS::ApiGateway::RestApi                            ServerlessRestApi                                   -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::Deployment                         ServerlessRestApiDeployment47fc2d5f9d               -
CREATE_IN_PROGRESS                                  AWS::Lambda::Permission                             HelloWorldFunctionHelloWorldPermissionProd          -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::Deployment                         ServerlessRestApiDeployment47fc2d5f9d               Resource creation Initiated
CREATE_IN_PROGRESS                                  AWS::Lambda::Permission                             HelloWorldFunctionHelloWorldPermissionProd          Resource creation Initiated
CREATE_COMPLETE                                     AWS::ApiGateway::Deployment                         ServerlessRestApiDeployment47fc2d5f9d               -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::Stage                              ServerlessRestApiProdStage                          -
CREATE_IN_PROGRESS                                  AWS::ApiGateway::Stage                              ServerlessRestApiProdStage                          Resource creation Initiated
CREATE_COMPLETE                                     AWS::ApiGateway::Stage                              ServerlessRestApiProdStage                          -
CREATE_COMPLETE                                     AWS::Lambda::Permission                             HelloWorldFunctionHelloWorldPermissionProd          -
CREATE_COMPLETE                                     AWS::CloudFormation::Stack                          myapp                                             -
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by sriram-mv** [comment]
Verified that with nodejs14.x it does hang.

**Comment by keithaws** [comment]
The original SAM application I worked on that led me to discover this issue used functions with the java11 runtime.

**Comment by keithaws** [comment]
Good catch. Why would this fail with node but work with Python?

**Comment by wchengru** [comment]
It seems Python has the same issue with `AWS::SecretsManager:Secret`.
