### ISSUE TITLE
OSError: The config file .pylintrc doesn't exist! when running `make pr`

### ISSUE THREAD

**Issue by kingram6865** [aws/aws-sam-cli#3149]
### Description:

I am making sam-cli for an arm64 installation. The compilation is failing
Also there are no clear instructions on what the usable results of `make pr` should be
and where those usable results will reside.

### Steps to reproduce:

1. clone repo
2. cd to aws-sam-cli-src
3. sudo make pr

### Observed result:

```
Installing collected packages: aws-sam-cli
  Attempting uninstall: aws-sam-cli
    Found existing installation: aws-sam-cli 1.27.2
    Can't uninstall 'aws-sam-cli'. No files were found to uninstall.
  Running setup.py develop for aws-sam-cli
Successfully installed aws-sam-cli
# Linter performs static analysis to catch latent bugs
pylint --rcfile .pylintrc samcli
Traceback (most recent call last):
  File "/usr/local/bin/pylint", line 8, in <module>
    sys.exit(run_pylint())
  File "/usr/local/lib/python3.8/dist-packages/pylint/__init__.py", line 22, in run_pylint
    PylintRun(sys.argv[1:])
  File "/usr/local/lib/python3.8/dist-packages/pylint/lint/run.py", line 298, in __init__
    linter.read_config_file(verbose=self.verbose)
  File "/usr/local/lib/python3.8/dist-packages/pylint/config/option_manager_mixin.py", line 261, in read_config_file
    raise OSError("The config file {:s} doesn't exist!".format(config_file))
OSError: The config file .pylintrc doesn't exist!
make: *** [Makefile:37: lint] Error 1
```

### Expected result:

I expected to either complete the process with `make install` or to type `sam --version` and receive version information

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu Server 20.04
2. `sam --version`: latest repo clone
3. AWS region: irrelevant

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@kingram6865 It is not clear to me what you are trying to achieve. You can follow our [Development Guide](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md) which goes over some of the details.

If you are trying to install on ARM to use SAM CLI unless you are contributing, you can just `pip install` (into a venv) since we don't have an ARM installers at the moment. I wouldn't do this from source at all.

**Comment by kingram6865** [comment]
> @kingram6865 It is not clear to me what you are trying to achieve. You can follow our [Development Guide](https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md) which goes over some of the details.
> 
> If you are trying to install on ARM to use SAM CLI unless you are contributing, you can just `pip install` (into a venv) since we don't have an ARM installers at the moment. I wouldn't do this from source at all.

Ok. Makes sense. 
I was simply trying to compile a version of the sam cli to run on my RPi4 which I uses as an edge server, since the linux install is for x86.

I'll follow your recommendation to pip install.
