### ISSUE TITLE
Build fails from another angle.

### ISSUE THREAD

**Issue by kingram6865** [aws/aws-sam-cli#3151]
### Description:

I'm trying every which way but loose to compile samcli for my system.
This is the system I want to run it on. It should compile and run

So this bug complains about _sqlite3 in the unit tests.

### Steps to reproduce:

Follow the instructions in https://github.com/aws/aws-sam-cli/blob/develop/DEVELOPMENT_GUIDE.md

### Observed result:

```
--------------------------------------------------------------------
Your code has been rated at 10.00/10 (previous run: 10.00/10, +0.00)

# mypy performs type check
mypy setup.py samcli tests
Success: no issues found in 493 source files
# Run unit tests
# Fail if coverage falls below 95%
pytest --cov samcli --cov-report term-missing --cov-fail-under 95 tests/unit
Traceback (most recent call last):
  File "/PUBLIC/DOWNLOADS/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 187, in console_main
    code = main()
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config = outcome.get_result()  # type: Config
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1280, in parse
    self._preparse(args, addopts=addopts)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 168, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 171, in exec_module
    exec(co, module.__dict__)
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/pytest_cov/plugin.py", line 6, in <module>
    import coverage
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/coverage/__init__.py", line 15, in <module>
    from coverage.control import Coverage, process_startup
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/coverage/control.py", line 20, in <module>
    from coverage.data import CoverageData, combine_parallel_data
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/coverage/data.py", line 17, in <module>
    from coverage.sqldata import CoverageData
  File "/PUBLIC/DOWNLOADS/.venv/lib/python3.7/site-packages/coverage/sqldata.py", line 15, in <module>
    import sqlite3
  File "/usr/local/lib/python3.7/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
make: *** [Makefile:11: test] Error 1
```

### Expected result:

A fully validated pull request that should be good because it is based on unchanged clone of this repo.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubunti Server 20.04
2. `sam --version`: NA
3. AWS region: NA

`Add --debug flag to command you are running`

**Comment by kingram6865** [comment]
I ran the it with `sudo make pr` and it completed.
