### ISSUE TITLE
Unable to run lambda function locally using the 'sam local start-api -t template_local.yaml' command

### ISSUE THREAD

**Issue by riyaagarwal-intuit** [aws/aws-sam-cli#3184]
I am trying to run lambda function locally using this sam command: " sam local start-api -t template_local.yaml"
But I am getting the 'FileExistsError'. I have tried deleting the 'target' folder and the '.m2' folder but I am still getting the same error. 
I have been running the lambda function smoothly couple of days ago. I have not made any configuration changes that might have caused this error.

Error:

```
Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 317, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 130, in invoke
    self.local_runtime.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 217, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 176, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 71, in create
    code_dir = self._get_code_dir(function_config.code_abs_path)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 279, in _get_code_dir
    decompressed_dir: str = _unzip_file(code_path)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 495, in _unzip_file
    unzip(filepath, temp_dir)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 99, in unzip
    extracted_path = _extract(file_info, output_dir, zip_ref)
  File "/usr/local/Cellar/aws-sam-cli/1.27.2/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 61, in _extract
    return zip_ref.extract(file_info, output_dir)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1630, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/Cellar/python@3.8/3.8.11/Frameworks/Python.framework/Versions/3.8/lib/python3.8/zipfile.py", line 1697, in _extract_member
    os.mkdir(targetpath)
FileExistsError: [Errno 17] File exists: '/var/folders/zh/p27g1r8x601bpsdx1hblvl380000gn/T/tmpebfm6_5n/license'
2021-08-19 18:09:15 127.0.0.1 - - [19/Aug/2021 18:09:15] "POST / HTTP/1.1" 502 -
```

**Comment by ssenchenko** [comment]
To be able to help you, we need to have more information to **reproduce** the issue. Exception text, unfortunately, is not enough.
Could you please use these [template](https://github.com/aws/aws-sam-cli/issues/new?assignees=&labels=&template=Bug_report.md&title=)?
You can also try to upgrade SAM CLI version and run it again.
