### ISSUE TITLE
[sam-beta-cdk] attempts to build CDK 'helper' lambdas which fails

### ISSUE THREAD

**Issue by malbertus** [aws/aws-sam-cli#3192]
### Description:
Performing a `sam-beta-cdk build` not only attempts to build my lambda function, but also a 'helper' lambda function created by CDK. The build fails. 

In this case i'm using Python for CDK as well as my lambda runtime, while the 'helper' function is some Node.js 12.x code being included by CDK as part of adding a CloudWatchLogGroup to an EventBridge rule.

A `cdk deploy` without a `sam-beta-cdk build` will successfully update the stack. This will obviously defeat the purpose of using the `sam-beta-cdk` tool but the point is to show that this is legitimate CDK code which will deploy correctly.

### Steps to reproduce:
1. Run `sam-beta-cdk build --use-container` prior to adding EventBridge rule target (which generates CDK 'helper' lambda)
2. Run `cdk deploy -a .aws-sam/build`
3. Successful deployment
4. Update `./my_stack/cdk.py` with the EventBridge rule target of CloudWatchLogGroup per code in additional information
5. Run `sam-beta-cdk build --use-container`
6. `my_lambda` builds correctly
7. Build error on the 'helper' lambda `npm ERR! Could not install from "../source" as it does not contain a package.json file.`

### Observed result:
```
2021-08-23 11:17:51,370 | IAC Plugin getting project...
2021-08-23 11:17:51,371 | CDK Toolkit found at /usr/local/bin/cdk
2021-08-23 11:17:51,371 | Synthesizing CDK App
2021-08-23 11:17:51,371 | command: ['/usr/local/bin/cdk', 'synth', '--no-staging', '-o', '.aws-sam/.cdk-out']
2021-08-23 11:17:59,738 | Cloud assembly synthed at .aws-sam/.cdk-out
2021-08-23 11:17:59,739 | _validate_cloud_assembly: .aws-sam/.cdk-out
2021-08-23 11:17:59,742 | Found assets: {'/Users/<my_username>/Documents/Code/my_lambda/my_lambda': <samcli.lib.iac.interface.S3Asset object at 0x103437250>, '/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime': <samcli.lib.iac.interface.S3Asset object at 0x103437280>}
2021-08-23 11:17:59,743 | ca-stack_name: my_lambda
2021-08-23 11:17:59,743 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-08-23 11:17:59,745 | Using config file: samconfig.toml, config environment: default
2021-08-23 11:17:59,745 | Expand command line arguments to:
2021-08-23 11:17:59,745 | --project_type=CDK --template_file=/Users/<my_username>/Documents/Code/my_lambda/template.yml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache --iac=<samcli.lib.iac.cdk.plugin.CdkPlugin object at 0x103341400> --project=<samcli.lib.iac.interface.Project object at 0x103348550> 
2021-08-23 11:17:59,851 | 'build' command is called
2021-08-23 11:17:59,851 | Starting Build inside a container
2021-08-23 11:17:59,851 | Collected default values for parameters: {}
2021-08-23 11:17:59,903 | 14 stacks found in the template
2021-08-23 11:17:59,903 | Collected default values for parameters: {}
2021-08-23 11:17:59,932 | 14 resources found in the stack my_lambda
2021-08-23 11:17:59,932 | Collected default values for parameters: {}
2021-08-23 11:17:59,962 | Found Lambda function with name='my_lambdaFC8C06E0' and CodeUri='/Users/<my_username>/Documents/Code/my_lambda/my_lambda'
2021-08-23 11:17:59,962 | --base-dir is not presented, adjusting uri /Users/<my_username>/Documents/Code/my_lambda/my_lambda relative to .aws-sam/.cdk-out
2021-08-23 11:17:59,962 | Found Lambda function with name='AWS679f53fac002430cb0da5b7982bd22872D164C4C' and CodeUri='/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime'
2021-08-23 11:17:59,962 | --base-dir is not presented, adjusting uri /private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime relative to .aws-sam/.cdk-out
2021-08-23 11:17:59,962 | Collected default values for parameters: {}
2021-08-23 11:18:00,069 | Instantiating build definitions
2021-08-23 11:18:00,073 | Same function build definition found, adding function (Previous: BuildDefinition(python3.8, /Users/<my_username>/Documents/Code/my_lambda/my_lambda, Zip, , bcaffc53-cbe0-4801-bd1b-c4f9fc0f473a, {'aws:cdk:path': 'my_lambda/my_lambda/Resource', 'aws:asset:path': '/Users/<my_username>/Documents/Code/my_lambda/my_lambda', 'aws:asset:property': 'Code'}, {}, []), Current: BuildDefinition(python3.8, /Users/<my_username>/Documents/Code/my_lambda/my_lambda, Zip, , 5c536d2c-dbc1-4140-97b6-df2e421f53bf, OrderedDict([('aws:cdk:path', 'my_lambda/my_lambda/Resource'), ('aws:asset:path', '/Users/<my_username>/Documents/Code/my_lambda/my_lambda'), ('aws:asset:property', 'Code')]), {}, []), Function: Function(function_id='my_lambda', name='my_lambdaFC8C06E0', functionname='my_lambda', runtime='python3.8', memory=None, timeout=None, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/<my_username>/Documents/Code/my_lambda/my_lambda', environment=None, rolearn='arn:aws:lambda:us-east-1:123456789012:function:my_lambdaServiceRole5361E547', layers=[], events=None, metadata=OrderedDict([('aws:cdk:path', 'my_lambda/my_lambda/Resource'), ('aws:asset:path', '/Users/<my_username>/Documents/Code/my_lambda/my_lambda'), ('aws:asset:property', 'Code')]), inlinecode=None, codesign_config_arn=None, stack_path='my_lambda'))
2021-08-23 11:18:00,074 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(nodejs12.x, /private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime, Zip, , 10241235-a850-4af2-b583-91ea458b6f28, OrderedDict([('aws:cdk:path', 'my_lambda/AWS679f53fac002430cb0da5b7982bd2287/Resource'), ('aws:asset:path', '/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime'), ('aws:asset:property', 'Code')]), {}, []), Function: Function(function_id='AWS679f53fac002430cb0da5b7982bd2287', name='AWS679f53fac002430cb0da5b7982bd22872D164C4C', functionname='AWS679f53fac002430cb0da5b7982bd22872D164C4C', runtime='nodejs12.x', memory=None, timeout=120, handler='index.handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime', environment=None, rolearn='arn:aws:lambda:us-east-1:123456789012:function:AWS679f53fac002430cb0da5b7982bd2287ServiceRoleC1EA0FF2', layers=[], events=None, metadata=OrderedDict([('aws:cdk:path', 'my_lambda/AWS679f53fac002430cb0da5b7982bd2287/Resource'), ('aws:asset:path', '/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime'), ('aws:asset:property', 'Code')]), inlinecode=None, codesign_config_arn=None, stack_path='my_lambda'))
2021-08-23 11:18:00,076 | Building codeuri: /Users/<my_username>/Documents/Code/my_lambda/my_lambda runtime: python3.8 metadata: {'aws:cdk:path': 'my_lambda/my_lambda/Resource', 'aws:asset:path': '/Users/<my_username>/Documents/Code/my_lambda/my_lambda', 'aws:asset:property': 'Code'} functions: ['my_lambda/my_lambda']
2021-08-23 11:18:00,076 | Building to following folder /Users/<my_username>/Documents/Code/my_lambda/.aws-sam/build/my_lambda/my_lambdaFC8C06E0

Fetching public.ecr.aws/sam/build-python3.8:latest Docker container image......
2021-08-23 11:18:02,905 | Mounting /Users/<my_username>/Documents/Code/my_lambda/my_lambda as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch --exists-action i
<SNIP>
Get my python packages
</SNIP>
Final incompatible: set()
Final missing wheels: set()
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
PythonPipBuilder:CopySource succeeded
2021-08-23 11:18:04,767 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
2021-08-23 11:18:04,768 | Build inside container was successful. Copying artifacts from container to host
2021-08-23 11:18:04,957 | Copying from container: /tmp/samcli/artifacts/. -> /Users/<my_username>/Documents/Code/my_lambda/.aws-sam/build/my_lambda/my_lambdaFC8C06E0
2021-08-23 11:18:05,269 | Build inside container succeeded
2021-08-23 11:18:05,271 | Building codeuri: /private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime runtime: nodejs12.x metadata: OrderedDict([('aws:cdk:path', 'my_lambda/AWS679f53fac002430cb0da5b7982bd2287/Resource'), ('aws:asset:path', '/private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime'), ('aws:asset:property', 'Code')]) functions: ['my_lambda/AWS679f53fac002430cb0da5b7982bd2287']
2021-08-23 11:18:05,271 | Building to following folder /Users/<my_username>/Documents/Code/my_lambda/.aws-sam/build/my_lambda/AWS679f53fac002430cb0da5b7982bd22872D164C4C

Fetching public.ecr.aws/sam/build-nodejs12.x:latest Docker container image......
2021-08-23 11:18:08,012 | Mounting /private/var/folders/rc/_bgd4ld905j302srlt4dxj480000gr/T/jsii-kernel-v5fqRM/node_modules/aws-cdk-lib/lib/custom-resources/lib/aws-custom-resource/runtime as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Running workflow 'NodejsNpmBuilder'
Running NodejsNpmBuilder:NpmPack
NODEJS packaging file:/tmp/samcli/source to /tmp/samcli/scratch
executing NPM: ['npm', 'pack', '-q', 'file:/tmp/samcli/source']
NodejsNpmBuilder:NpmPack failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 59, in execute
    tarfile_name = self.subprocess_npm.run(["pack", "-q", package_path], cwd=self.scratch_dir).splitlines()[-1]
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 70, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 59, in execute
    tarfile_name = self.subprocess_npm.run(["pack", "-q", package_path], cwd=self.scratch_dir).splitlines()[-1]
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 269, in run
    action.execute()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 70, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/__main__.py", line 126, in main
    mode=params.get("mode", None),
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/builder.py", line 125, in build
    return workflow.run()
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 76, in wrapper
    func(self, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib64/python3.7/site-packages/aws_lambda_builders/workflow.py", line 276, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log
2021-08-23 11:18:09,768 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 400, "message": "NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL\nnpm ERR! Could not install from \"../source\" as it does not contain a package.json file.\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log"}}

Build Failed
2021-08-23 11:18:09,982 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '56dfb7b2-bf80-4960-ba41-f51902154799', 'installationId': '85c36e27-3276-44c5-a5c9-b8c7b6a66c3f', 'sessionId': '3e8c29fb-c01a-45a4-9af3-9e333d5b90ac', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.11', 'samcliVersion': '1.22.0.dev202107140310', 'metricSpecificAttributes': {'projectType': 'CDK'}, 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam-beta-cdk build', 'duration': 10236, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2021-08-23 11:18:10,686 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: NodejsNpmBuilder:NpmPack - NPM Failed: npm ERR! code ENOLOCAL
npm ERR! Could not install from "../source" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-23T01_18_09_727Z-debug.log
```

### Expected result:
`sam-beta-cdk build` to recognise which lambda functions should go through the build process, and which are included by CDK as a 'helper' fuction, and ignore CDK helpers as appropriate.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Darwin x64 20.6.0 (macOS Big Sur 11.5.1)
2. `sam --version`: SAM CLI, version 1.22.0.dev202107140310
3. AWS region: ap-southeast-2

Code which causes the issue:
```
        my_lambda = _lambda.Function(
            scope=self,
            id="my_lambda",
            runtime=_lambda.Runtime.PYTHON_3_8,
            function_name="my_lambda",
            description="my_lambda",
            code=_lambda.Code.from_asset("./my_lambda"),
            handler="app.lambda_handler",
        )

        diagnostic_bus= eventbridge.EventBus(
            scope=self,
            id="diagnostic_bridge",
            event_bus_name="Diagnostic-Bridge"
        )

        event_logs = logs.LogGroup(
            scope=self,
            id="event-logs",
            log_group_name="/aws/events/my-events"
        )

        event_log_rule = eventbridge.Rule(
            scope=self,
            id="event-log-rule",
            rule_name="Event-Log-Rule",
            event_bus=diagnostic_bus,
            event_pattern=eventbridge.EventPattern(
                account=[self.account]
            )
        ) 

        event_log_rule.add_target(target.CloudWatchLogGroup(event_logs))
```

**Comment by malbertus** [comment]
Still a problem with SAM CLI, version 1.29.0.dev202108311500

**Comment by mildaniel** [comment]
Hi @malbertus, thanks for opening up the issue. The problem seems to be that Lambda Builders doesn't currently allow for Node.js functions to be built without a `package.json`. We are working on resolving this.

**Comment by maartenbrak-clearly** [comment]
Any update on this? I've run into exactly the same issue.

**Comment by cfrech-ctx** [comment]
I'm running into a similar issue where `sam-beta-cdk build` attempts to build a helper lambda that is part of the `aws-cdk.aws_s3_deployment` construct:

```
$ cdk --version
1.126.0 (build f004e1a)
```

```
$ sam-beta-cdk --version
SAM CLI, version 1.29.0.dev202108311500
```

```
Building codeuri: /private/var/folders/nn/xsjxvv6917d4j5020xwbnlg00000gp/T/jsii-kernel-2qzsF0/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda runtime: python3.7 metadata: OrderedDict([('aws:cdk:path', 'dwh-dev/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C/Resource'), ('aws:asset:path', '/private/var/folders/nn/xsjxvv6917d4j5020xwbnlg00000gp/T/jsii-kernel-2qzsF0/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda'), ('aws:asset:property', 'Code')]) functions: ['dwh-dev/Custom::CDKBucketDeployment8693BB64968944B69AAFB0CC9EB8756C']
requirements.txt file not found. Continuing the build without dependencies.
Running PythonPipBuilder:CopySource

Build Failed
Error: PythonPipBuilder:CopySource - [Errno 2] No such file or directory: '/private/var/folders/nn/xsjxvv6917d4j5020xwbnlg00000gp/T/jsii-kernel-2qzsF0/node_modules/@aws-cdk/aws-s3-deployment/lib/lambda'
```

Any ideas how to prevent that?

**Comment by moelasmar** [comment]
Thanks for raising this issue. From @cfrech-ctx comment, it seems that the missed package.json file is fixed, and it is something else, let me investigate the issue to know the root cause of it. 

@cfrech-ctx, @maartenbrak-clearly, @malbertus .. can I ask you if you were using `sam-beta-cdk build` to just test the beta version, or you are facing issues with using the build features in CDK ([Assets bundling option](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.BundlingOptions.html), and Runtime Lambda Function Constructs [Python](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-python.PythonFunction.html), [nodeJs](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-nodejs.NodejsFunction.html), [go](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-lambda-go.GoFunction.html)), and you want to use sam build to resolve it.

**Comment by cfrech-ctx** [comment]
In my case this problem blocks me from test-running my lambdas locally with SAM CDK. For regular builds/deploys, `cdk deploy` works just fine.

**Comment by moelasmar** [comment]
@cfrech-ctx .. `sam-beta-cdk build` is not always a requirement to do `sam-beta-cdk local invoke` .. can you give me more details about your project, what type of Lambda Function constructs you are using, and also the runtimes.
If it is possible to refer me to a github repo contains your project, It will help me in the investigation.

**Comment by moelasmar** [comment]
SAM CLI's CDK support went into GA yesterday. The new release include the fix of this issue.
You can find more details about the new CDK support in SAM CLI [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-getting-started.html)
