### ISSUE TITLE
`sam deploy --guided` is broken

### ISSUE THREAD

**Issue by nikoudel** [aws/aws-sam-cli#3248]
### Description:
Follwing the [Hello World](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html) tutorial leads to a failure. The `sam deploy --guided` command starts the deployment but it fails in CloudFormation at event `SamCliSourceBucketBucketPolicy`:

```
The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: AKFGYGY3FA73XCWS; S3 Extended Request ID: 5ewcyxA6Ru/HfNbTyMxxj0K3FK9pPVXSb5NfHEA5R+m12IQTJRXbhuqnoM3pJ8Qvx7bjnwq64Es=; Proxy: null)
```
The name of the bucket was `aws-sam-cli-managed-default-samclisourcebucket-1vfmiq67xl9wy`.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows and Linux
2. `sam --version`: SAM CLI, version 1.30.0
3. AWS region: eu-north-1

`Add --debug flag to command you are running`

```bash
sam deploy --guided --debug
2021-09-07 14:26:45,077 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-09-07 14:26:45,077 | Using config file: samconfig.toml, config environment: default
2021-09-07 14:26:45,077 | Expand command line arguments to:
2021-09-07 14:26:45,077 | --guided --template_file=C:\git\serena-mobile-app\scripts\aws\serena-api\.aws-sam\build\template.yaml --stack_name=sam-app --fail_on_empty_changeset

Configuring SAM deploy
======================

        Looking for config file [samconfig.toml] :  Not found

        Setting default arguments for 'sam deploy'
        =========================================
        Stack Name [sam-app]:
        AWS Region [eu-north-1]:
2021-09-07 14:26:47,292 | No Parameters detected in the template
2021-09-07 14:26:47,313 | 2 stacks found in the template
        #Shows you resources changes to be deployed and require a 'Y' to initiate deploy
        Confirm changes before deploy [y/N]:
        #SAM needs permission to be able to create roles to connect to the resources in your template
        Allow SAM CLI IAM role creation [Y/n]:
2021-09-07 14:26:53,049 | No Parameters detected in the template
2021-09-07 14:26:53,063 | 2 resources found in the stack
2021-09-07 14:26:53,063 | No Parameters detected in the template
2021-09-07 14:26:53,077 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-09-07 14:26:53,077 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\git\serena-mobile-app\scripts\aws\serena-api\.aws-sam\build\template.yaml
2021-09-07 14:26:53,077 | No Parameters detected in the template
2021-09-07 14:26:53,090 | Detected Inline Swagger definition
2021-09-07 14:26:53,091 | Auth checks done on swagger are not exhaustive!
        HelloWorldFunction may not have authorization defined, Is this okay? [y/N]: y
2021-09-07 14:26:57,625 | No Parameters detected in the template
2021-09-07 14:26:57,639 | 2 resources found in the stack
2021-09-07 14:26:57,639 | No Parameters detected in the template
2021-09-07 14:26:57,652 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2021-09-07 14:26:57,652 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\git\serena-mobile-app\scripts\aws\serena-api\.aws-sam\build\template.yaml
2021-09-07 14:26:57,653 | No function or layer definition found with code sign config, skipping
        Save arguments to configuration file [Y/n]:
        SAM configuration file [samconfig.toml]:
        SAM configuration environment [default]:

        Looking for resources needed for deployment:
2021-09-07 14:27:07,527 | Managed S3 stack [aws-sam-cli-managed-default] not found. Creating a new one.
        Creating the required resources...
2021-09-07 14:27:38,677 | Failed to create managed resources
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 107, in _create_or_get_stack
    stack = _create_stack(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\managed_cloudformation_stack.py", line 180, in _create_stack
    stack_waiter.wait(StackName=stack_id, WaiterConfig={"Delay": 15, "MaxAttempts": 60})
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 350, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
2021-09-07 14:27:38,678 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '8b1b3d7d-c7d5-4604-9960-45699f6cda10', 'installationId': '58645a43-492f-4d9f-b6d0-82c40598a125', 'sessionId': 'f8c3369a-2720-4a6a-a8c4-af5b8e11efd0', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.30.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'duration': 53600, 'exitReason': 'ManagedStackError', 'exitCode': 1}}]}
2021-09-07 14:27:39,398 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create managed resources: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
```
![image](https://user-images.githubusercontent.com/1636683/132340750-74e3eac6-bef1-44aa-97f7-ec583d9274ae.png)

**Comment by aelmanaa** [comment]
Same issue here

**Comment by sriram-mv** [comment]
Closing this issue in favor of https://github.com/aws/aws-sam-cli/issues/3243 so that we have one place to track the issue.
