### ISSUE TITLE
Problem with Lambda layers and --warm-containers after upgrading

### ISSUE THREAD

**Issue by spmacdonald** [aws/aws-sam-cli#3262]
After I upgraded to version `SAM CLI, version 1.29.0.dev202108311500` I get the following error when using the `--warm-containers EAGER` flag.  When I omit this flag the app works correctly:

```
% sam-beta-cdk local start-api --port 3001 --warm-containers EAGER --env-vars ../src/api/env.json
Synthesizing CDK App
Initializing the lambda functions containers.
AwsCliLayer is a local Layer in the template
Decompressing /Users/scott/code/data-collection/src/lambda-layers/python38/layer.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/python38/layer.zip
Image was not found.
Building image...python-layer is a local Layer in the template
python-layer is a local Layer in the template
Image was not found.
Building image...Image was not found.
Building image.....................................................................................................................................................................................
.
Skip pulling image and use local one: samcli/lambda:python3.8-6c5fd29c488fd2621c11904a7.

Skip pulling image and use local one: samcli/lambda:python3.8-6c5fd29c488fd2621c11904a7.

Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
Lambda functions containers initialization failed because of [Errno 2] No such file or directory: '/private/var/folders/yf/snzrgqyx2xd_7zypg5bf_v640000gn/T/jsii-kernel-7jbfMq/node_modules/@aws-cdk/lambda-layer-awscli/lib/layer.zip'
Error: Lambda functions containers initialization failed
```

Not sure how to debug this, I am going to try rolling back a version or two and seeing if that works

**Comment by aahung** [comment]
Is it still reproducible in 1.31.0?

**Comment by spmacdonald** [comment]
Sorry for the delayed response.  I just hit this again today.

Any tips on how to install version 1.31.0?  I followed the instructions on the homepage for Mac OS:

```
Warning: aws/tap/aws-sam-cli-beta-cdk 202108311500 is already installed and up-to-date.
To reinstall 202108311500, run:
  brew reinstall aws-sam-cli-beta-cdk
```

Still on `SAM CLI, version 1.29.0.dev202108311500`

**Comment by spmacdonald** [comment]
I have some new output to share:

```
.venv) scott@alpha infrastructure % sam-beta-cdk local start-api --port 3001 --warm-containers EAGER --env-vars ../src/api/env.json
Synthesizing CDK App
Initializing the lambda functions containers.
Decompressing /Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip
AwsCliLayer is a local Layer in the template
Decompressing /Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip
Image was not found.
Building image...Decompressing /Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip
Decompressing /Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip
Psycopg2Layer is a local Layer in the template
PandasLayer is a local Layer in the template
Psycopg2Layer is a local Layer in the template
PandasLayer is a local Layer in the template
Building image...Psycopg2Layer is a local Layer in the template
PandasLayer is a local Layer in the template
Building image...Building image...Psycopg2Layer is a local Layer in the template
PandasLayer is a local Layer in the template
Psycopg2Layer is a local Layer in the template
PandasLayer is a local Layer in the template
Building image...Building image........................................................................................................................
.Skip pulling image and use local one: samcli/lambda:python3.9-bebf7aaca3553b37553ae4383.

.Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container

Skip pulling image and use local one: samcli/lambda:python3.9-bebf7aaca3553b37553ae4383.

Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
..
...
.
Skip pulling image and use local one: samcli/lambda:python3.9-bebf7aaca3553b37553ae4383.

Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
Skip pulling image and use local one: samcli/lambda:python3.9-bebf7aaca3553b37553ae4383.

Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
Skip pulling image and use local one: samcli/lambda:python3.9-bebf7aaca3553b37553ae4383.

Mounting /Users/scott/code/Sparc/src/api as /var/task:ro,delegated inside runtime container
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/Sparc/src, is_recursive=False> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/Sparc/src/api, is_recursive=True> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers, is_recursive=False> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/Sparc/src/api, is_recursive=True> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip, is_recursive=True> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/Sparc/src, is_recursive=False> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip, is_recursive=True> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers/pandas-layer-1.3.3-py3.9.zip, is_recursive=True> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers, is_recursive=False> - it is already scheduled
2021-09-30 15:16:45 Unhandled exception in FSEventsEmitter
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/watchdog/observers/fsevents.py", line 310, in run
    _fsevents.add_watch(self, self.watch, self.events_callback, self.pathnames)
RuntimeError: Cannot add watch <ObservedWatch: path=/Users/scott/code/data-collection/src/lambda-layers/psycopg2-layer-2.9.1-py3.9.zip, is_recursive=True> - it is already scheduled
Lambda functions containers initialization failed because of [Errno 2] No such file or directory: '/private/var/folders/yf/snzrgqyx2xd_7zypg5bf_v640000gn/T/jsii-kernel-eSsymD/node_modules/@aws-cdk/lambda-layer-awscli/lib/layer.zip'
Error: Lambda functions containers initialization failed
```

**Comment by mildaniel** [comment]
The [CDK Support feature is now generally available](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-cdk-getting-started.html) and includes many improvements. Please try it and report back if a similar issue still exists.

**Comment by lucashuy** [comment]
Closing. Please feel free to reopen this issue or create a new one if you have any feedback or problems
