### ISSUE TITLE
Sam build fails on Ubuntu 20.04.3

### ISSUE THREAD

**Issue by Lewenhaupt** [aws/aws-sam-cli#3270]
### Description:

Using sam cli 1.21.1 in github actions started to fail building wheels on Ubuntu 20.04.3. It previously worked on Ubuntu 20.04.2 but github upgraded to 20.04.3 and there is no way to go back.

### Steps to reproduce:

Python 3.8.11
Run any python build using pypdf4 as a dependency using sam build on Ubuntu 20.04.3. It will fail to build the missing wheel.
--use-container will solve the issue but we do not wish to build inside container due to 500-issues against the AWS ECR.

### Observed result:

2021-09-09 10:00:16,932 | initial incompatible: {pypdf4==1.27.0(sdist)}
2021-09-09 10:00:16,932 | Downloading missing wheels: {pypdf4==1.27.0(sdist)}
2021-09-09 10:00:16,932 | calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp38 --dest /tmp/tmp82embo2b pypdf4==1.27.0
2021-09-09 10:00:17,559 | compatible wheels after second download pass: {idna==2.10(wheel), urllib3==1.26.6(wheel), certifi==2021.5.30(wheel), chardet==4.0.0(wheel), requests==2.25.1(wheel)}
2021-09-09 10:00:17,559 | Build missing wheels from sdists (C compiling True): {pypdf4==1.27.0(sdist)}
2021-09-09 10:00:17,560 | calling pip wheel --no-deps --wheel-dir /tmp/tmp82embo2b /tmp/tmp82embo2b/PyPDF4-1.27.0.tar.gz
2021-09-09 10:00:18,662 | compatible after building wheels (no C compiling): {idna==2.10(wheel), urllib3==1.26.6(wheel), certifi==2021.5.30(wheel), chardet==4.0.0(wheel), requests==2.25.1(wheel)}
2021-09-09 10:00:18,662 | Build missing wheels from sdists (C compiling False): {pypdf4==1.27.0(sdist)}
2021-09-09 10:00:18,662 | calling pip wheel --no-deps --wheel-dir /tmp/tmp82embo2b /tmp/tmp82embo2b/PyPDF4-1.27.0.tar.gz
2021-09-09 10:00:19,754 | compatible after building wheels (C compiling): {idna==2.10(wheel), urllib3==1.26.6(wheel), certifi==2021.5.30(wheel), chardet==4.0.0(wheel), requests==2.25.1(wheel)}
2021-09-09 10:00:19,754 | Final compatible: {idna==2.10(wheel), chardet==4.0.0(wheel), urllib3==1.26.6(wheel), requests==2.25.1(wheel), certifi==2021.5.30(wheel)}
2021-09-09 10:00:19,754 | Final incompatible: set()
2021-09-09 10:00:19,754 | Final missing wheels: {pypdf4==1.27.0(sdist)}
2021-09-09 10:00:19,780 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 39, in execute

Build Failed
    package_builder.build_dependencies(
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 145, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 226, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {pypdf4==1.27.0(sdist)}

### Expected result:

Expect sam build to be able to build the wheel from the sdist.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04.3
2. `sam --version`: 1.21
3. AWS region:

`Add --debug flag to command you are running`

**Comment by aahung** [comment]
Can you upgrade your sam-cli to 1.31.0 and try again? (Also upgrade your `pip` if you build without `--use-container`)

**Comment by Lewenhaupt** [comment]
Yeah we get exactly the same issue unfortunately:
pip 21.2.4 from /home/runner/.virtualenvs/.venv/lib/python3.8/site-packages/pip (python 3.8)
SAM CLI, version 1.31.0
Error: PythonPipBuilder:ResolveDependencies - {pypdf4==1.27.0(sdist)}

**Comment by aahung** [comment]
I can reproduce it on macOS as well. Not reproducible with `--use-container`.
