### ISSUE TITLE
aws-sam-cli 1.33.0 fails with compatible_runtime index out of range

### ISSUE THREAD

**Issue by zxiiro** [aws/aws-sam-cli#3328]
### Description:

Our CI started failing to run `sam build` after picking up the new 1.33.0 version with the following stack trace:

```
First compatible runtime has been chosen as build runtime
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/commands/build/command.py", line 210, in cli
    do_cli(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/commands/build/command.py", line 318, in do_cli
    artifacts = builder.build()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 172, in build
    return build_strategy.build()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 43, in build
    result.update(self._build_layers(self._build_graph))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 70, in _build_layers
    layer_build_results.update(self.build_single_layer_definition(layer_definition))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 167, in build_single_layer_definition
    layer.full_path: self._build_layer(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 455, in _build_layer
    build_runtime = compatible_runtimes[0]
IndexError: list index out of range
Error: Process completed with exit code 1.

```

### Steps to reproduce:

`pip install aws-sam-cli`
`sam build`

### Observed result:

```
First compatible runtime has been chosen as build runtime
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/commands/build/command.py", line 210, in cli
    do_cli(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/commands/build/command.py", line 318, in do_cli
    artifacts = builder.build()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 172, in build
    return build_strategy.build()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 43, in build
    result.update(self._build_layers(self._build_graph))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 70, in _build_layers
    layer_build_results.update(self.build_single_layer_definition(layer_definition))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 167, in build_single_layer_definition
    layer.full_path: self._build_layer(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 455, in _build_layer
    build_runtime = compatible_runtimes[0]
IndexError: list index out of range
Error: Process completed with exit code 1.

```

### Expected result:

Build proceeds.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
2. `sam --version`: 1.33.0
3. AWS region: N/A we are using GitHub Actions

**Comment by mgrandis** [comment]
Thanks for reporting this.
We are looking into it.

**Comment by mndeveci** [comment]
Hi @zxiiro, thanks for reporting this.

We have identified your issue and it happens if a custom build is defined for layer ([Example 2 with Makefile build here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html)) and no `CompatibleRuntimes` is defined. For a workaround, you can define a runtime in `CompatibleRuntimes` ([AWS::Serverless::LayerVersion](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-layerversion.html#sam-layerversion-compatibleruntimes), [AWS::Lambda::LayerVersion](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-layerversion.html#cfn-lambda-layerversion-compatibleruntimes)). That way build should succeed.

We will also patch AWS SAM CLI as soon as fix is completed.

Thanks!
