### ISSUE TITLE
sam-beta-cdk start-api doesn't find assets

### ISSUE THREAD

**Issue by revmischa** [aws/aws-sam-cli#3333]
### Description:
I have a CDK stack that has API gateways in nested stacks. Before I used nested stacks `start-api` would serve up my API just fine, but when I moved it to a nested stack it fails to find any assets.

### Steps to reproduce:
* Create API gateway in a nested stack and run start-api

I am running:
```
sam-beta-cdk local start-api --cdk-app 'ts-node bin/appTest.ts' -n locals.json --cdk-context LocalDev=true --warm-containers LAZY --profile dev --region eu-west-1 --port 4010 --debug
```

### Observed result:
```
2021-10-03 23:29:45,197 | IAC Plugin getting project...
2021-10-03 23:29:45,204 | CDK Toolkit found at /Users/cyber/dev/platform/node_modules/.bin/cdk
2021-10-03 23:29:45,204 | Synthesizing CDK App
2021-10-03 23:29:45,204 | command: ['/Users/cyber/dev/platform/node_modules/.bin/cdk', 'synth', '--no-staging', '--app', 'ts-node bin/appTest.ts', '-o', '.aws-sam/.cdk-out', '--context', 'LocalDev=true']
2021-10-03 23:30:06,954 | Cloud assembly synthed at .aws-sam/.cdk-out
2021-10-03 23:30:06,955 | _validate_cloud_assembly: .aws-sam/.cdk-out
2021-10-03 23:51:24,404 | Found assets: {}
Traceback (most recent call last):
  File "/usr/local/bin/sam-beta-cdk", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/utils/helpers.py", line 50, in wrapper
    iac_plugin, project = get_iac_plugin(project_type, kwargs, with_build)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/utils/helpers.py", line 40, in get_iac_plugin
    project = iac_plugin.get_project(lookup_paths)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 114, in get_project
    project = self._get_project_from_cloud_assembly(cloud_assembly_dir)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 211, in _get_project_from_cloud_assembly
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 211, in <listcomp>
    stacks: List[Stack] = [self._build_stack(cloud_assembly, ca_stack) for ca_stack in cloud_assembly.stacks]
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 232, in _build_stack
    self._build_resources_section(assets, ca_stack, cloud_assembly, section, section_dict)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/iac/cdk/plugin.py", line 292, in _build_resources_section
    asset = assets[asset_path]
KeyError: '/Users/cyber/dev/platform/packages/infra/.aws-sam/.cdk-out/asset.8f200934b57284f6f8494442a2e2603d66ee073debfffc76947c2871d2c3c407'
```

### Expected result:
I don't know why assets is an empty dict but I suspect it's because the API lives in a nested stack.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macos
2. `sam-beta-cdk --version`: `SAM CLI, version 1.29.0.dev202108311500`
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
@revmischa Thanks for reporting the issue. Can you share with us your CDK definition of the API Gateway and the nested stack?

**Comment by CoshUS** [comment]
Closing as no information was provided by requester. 
I will reopen the issue once CDK definition is shared.
