### ISSUE TITLE
aws sam build: Makefile not found

### ISSUE THREAD

**Issue by Lilja** [aws/aws-sam-cli#3360]
### Description:
We are using CDK to deploy our services and test with `sam local start-api` locally. This doesn't work whenever we write to the file, and we wish to have some sort of "hot reloading" to our go lambda.
I read somewhere that we need to run `sam build` in order for this to work.
We have this source directory: 
```
api/
  main.go
  infrastructure/
    cdk.json
    cdk.out/
    infra.py
    template.yaml
```

`sam build --template-file ./infrastructure/template.yaml`

<details>

<summary>Logs, click to expand</summary>

```
lilja in ~/c/u/c/api on master λ sam build --template-file ./infrastructure/template.yaml
Building codeuri: /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9 runtime: provided.al2 metadata: {'aws:cdk:path': 'cds-api/handler/Resource', 'aws:asset:path': '/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', 'aws:asset:property': 'Code'} architecture: x86_64 functions: ['handlerE1533BD5']
Running CustomMakeBuilder:CopySource
Running CustomMakeBuilder:MakeBuild

Build Failed
Error: CustomMakeBuilder:MakeBuild - Makefile not found at /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9/Makefile
lilja in ~/c/u/c/api on master λ
```

</details>

### Expected result:
The build to be run

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
2. `sam --version`:  SAM CLI, version 1.33.0
3. AWS region: -

`Add --debug flag to command you are running`

<details>

<summary>Debug logs of same command as above</summary>

```
lilja in ~/c/u/c/api on master λ sam build --template-file ./infrastructure/template.yaml --debug
2021-10-13 11:31:23,392 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2021-10-13 11:31:23,393 | Using config file: samconfig.toml, config environment: default
2021-10-13 11:31:23,393 | Expand command line arguments to:
2021-10-13 11:31:23,393 | --template_file=/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache
2021-10-13 11:31:23,502 | 'build' command is called
2021-10-13 11:31:23,585 | Collected default values for parameters: {}
2021-10-13 11:31:23,634 | 16 stacks found in the template
2021-10-13 11:31:23,635 | Collected default values for parameters: {}
2021-10-13 11:31:23,695 | 16 resources found in the stack
2021-10-13 11:31:23,695 | Collected default values for parameters: {}
2021-10-13 11:31:23,741 | Found Lambda function with name='handlerE1533BD5' and CodeUri='/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9'
2021-10-13 11:31:23,742 | --base-dir is not presented, adjusting uri /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9 relative to /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/template.yaml
2021-10-13 11:31:23,742 | Collected default values for parameters: {}
2021-10-13 11:31:23,796 | Instantiating build definitions
2021-10-13 11:31:23,802 | Same function build definition found, adding function (Previous: BuildDefinition(provided.al2, /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9, Zip, x86_64, , 219d7678-068d-435e-84ef-ef75a646c6de, {'aws:cdk:path': 'cds-api/handler/Resource', 'aws:asset:path': '/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', 'aws:asset:property': 'Code'}, {}, []), Current: BuildDefinition(provided.al2, /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9, Zip, x86_64, , e49f9938-1437-4968-adcd-c793558fc8c4, {'aws:cdk:path': 'cds-api/handler/Resource', 'aws:asset:path': '/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', 'aws:asset:property': 'Code'}, {}, []), Function: Function(name='handlerE1533BD5', functionname='handlerE1533BD5', runtime='provided.al2', memory=None, timeout=None, handler='bootstrap', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', environment={'Variables': {'INPUT_FILES_API_URL': 'https://24xvppfus0.execute-api.eu-west-1.amazonaws.com/prod', 'ACCOUNT_CONFIG_API_URL': 'https://account-config-api.master.stage.funnel.io'}}, rolearn='arn:aws:lambda:us-east-1:123456789012:function:handlerServiceRole187D5A5A', layers=[], events=None, metadata={'aws:cdk:path': 'cds-api/handler/Resource', 'aws:asset:path': '/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', 'aws:asset:property': 'Code'}, inlinecode=None, codesign_config_arn=None, architectures=None, stack_path=''))
2021-10-13 11:31:23,805 | Building codeuri: /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9 runtime: provided.al2 metadata: {'aws:cdk:path': 'cds-api/handler/Resource', 'aws:asset:path': '/Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9', 'aws:asset:property': 'Code'} architecture: x86_64 functions: ['handlerE1533BD5']
2021-10-13 11:31:23,805 | Building to following folder /Users/lilja/code/umbrella/customs-cds-app/api/.aws-sam/build/handlerE1533BD5
2021-10-13 11:31:23,809 | Loading workflow module 'aws_lambda_builders.workflows'
2021-10-13 11:31:23,821 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-10-13 11:31:23,823 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-10-13 11:31:23,825 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-10-13 11:31:23,827 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-10-13 11:31:23,829 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-10-13 11:31:23,832 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-10-13 11:31:23,835 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-10-13 11:31:23,838 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-10-13 11:31:23,866 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-10-13 11:31:23,866 | Found workflow 'CustomMakeBuilder' to support capabilities 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-10-13 11:31:23,923 | Running workflow 'CustomMakeBuilder'
2021-10-13 11:31:23,923 | Running CustomMakeBuilder:CopySource
2021-10-13 11:31:23,947 | CustomMakeBuilder:CopySource succeeded
2021-10-13 11:31:23,947 | Running CustomMakeBuilder:MakeBuild
2021-10-13 11:31:23,947 | CustomMakeBuilder:MakeBuild failed
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 73, in execute
    self.manifest_check()
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 62, in manifest_check
    raise MakeFileNotFoundError("Makefile not found at {}".format(self.manifest_path))
aws_lambda_builders.workflows.custom_make.exceptions.MakeFileNotFoundError: Makefile not found at /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9/Makefile

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 278, in run
    action.execute()
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/custom_make/actions.py", line 75, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Makefile not found at /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9/Makefile

Build Failed
2021-10-13 11:31:23,958 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'e6c7c830-fec0-4969-8304-d6258e16d699', 'installationId': 'c8b8baaa-db49-4cef-8127-749d7b2586fd', 'sessionId': '20336c98-10b2-46eb-a578-299077cfeceb', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.33.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'duration': 563, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2021-10-13 11:31:24,658 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: CustomMakeBuilder:MakeBuild - Makefile not found at /Users/lilja/code/umbrella/customs-cds-app/api/infrastructure/cdk.out/asset.8ce8ba350988666c072781785bc36e00683f16587425035efc4f7d786630efe9/Makefile
````

</details>

**Comment by hawflau** [comment]
@Lilja From the log you provided, it seems you are using `go1.x` runtime but a custom runtime (`provided` or `provided.al2`). Can you switch to `go1.x` runtime and try again?

Or, if you insist on using custom runtime, you should add a `Makefile`. See [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html) for more info
