### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by faridg18** [aws/aws-sam-cli#3361]
### Description:
I am having problems trying to run my lambda project, I keep getting unexpected token on the response.

### Observed result:

I am trying to run lambda functions on my local machine. I am using 
```sh
sam local start-api
```

the project compiles and runs but whenever I make a call to any route I get the following error:

```sh
Lambda returned empty body!
Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'errorMessage'} in {'errorType': 'Runtime.UserCodeSyntaxError', 'errorMessage': "SyntaxError: Unexpected token '.'"}
```

Also when I try to run sam validate

```sh
 sam validate
```

I get the following error, I don't know if it is related.

```sh
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListPolicies operation: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:
   Mac OS
2. `sam --version`:
   SAM CLI, version 1.12.0
3. AWS region:
   us-east-1

`Add --debug flag to command you are running`

**Comment by faridg18** [comment]
after updating sam cli I get the following error

```sh
2021-10-14 12:11:16,662 | Unable to find Click Context for getting session_id.
2021-10-14 12:11:16,662 | Lambda returned empty body!
2021-10-14 12:11:16,662 | Invalid lambda response received: Invalid API Gateway Response Keys: {'errorType', 'trace', 'errorMessage'} in {'errorType': 'Error', 'errorMessage': '/var/task/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header', 'trace': ['Error: /var/task/node_modules/argon2/lib/binding/napi-v3/argon2.node: invalid ELF header', '    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)', '    at Module.load (internal/modules/cjs/loader.js:937:32)', '    at Function.Module._load (internal/modules/cjs/loader.js:778:12)', '    at Module.require (internal/modules/cjs/loader.js:961:19)', '    at require (internal/modules/cjs/helpers.js:92:18)', '    at Object.<anonymous> (/var/task/node_modules/argon2/argon2.js:9:56)', '    at Module._compile (internal/modules/cjs/loader.js:1072:14)', '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)', '    at Module.load (internal/modules/cjs/loader.js:937:32)', '    at Function.Module._load (internal/modules/cjs/loader.js:778:12)', '    at Module.require (internal/modules/cjs/loader.js:961:19)', '    at require (internal/modules/cjs/helpers.js:92:18)', '    at Object.<anonymous> (/var/task/src/handlers/auth.js:5:16)', '    at Module._compile (internal/modules/cjs/loader.js:1072:14)', '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)', '    at Module.load (internal/modules/cjs/loader.js:937:32)']}
```
