### ISSUE TITLE
sam local invoke require gcloud login

### ISSUE THREAD

**Issue by Form1ca** [aws/aws-sam-cli#3364]
try repeat this [tutorial](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)

windows 10
SAM CLI, version 1.33.0

```

(base) PS C:\sam-app-2> sam build
Building codeuri: C:\sam-app-2\hello_world runtime: python3.8 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam\build
Built Template   : .aws-sam\build\template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Deploy: sam deploy --guided

```

```
(base) PS C:\sam-app-2> sam local invoke
Invoking app.lambda_handler (python3.8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image...ERROR: (gcloud.auth.docker-helper) There was a problem refreshing your current auth tokens: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
Please run:

  $ gcloud auth login

to obtain new credentials.

If you have already logged in with a different account:

    $ gcloud config set account ACCOUNT

to select an already authenticated account to use.
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\credentials\store.py", line 79, in _execute
    output = subprocess.check_output(
  File "subprocess.py", line 415, in check_output
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['C:\\Program Files (x86)\\Google\\Cloud SDK\\google-cloud-sdk\\bin\\docker-credential-gcloud.CMD', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\auth.py", line 264, in _resolve_authconfig_credstore
    data = store.get(registry)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\credentials\store.py", line 35, in get
    data = self._execute('get', server)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\credentials\store.py", line 93, in _execute
    raise errors.process_store_error(e, self.program)
docker.credentials.errors.StoreError: Credentials store docker-credential-gcloud exited with "".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\Formica\AppData\Roaming\Python\Python38\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 83, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 217, in wrapped_func
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 73, in create
    container = LambdaContainer(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\lambda_container.py", line 90, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers, architecture)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\lambda_container.py", line 223, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\lambda_image.py", line 157, in build
    self._build_image(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\lambda_image.py", line 257, in _build_image
    resp_stream = self.docker_client.api.build(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\build.py", line 261, in build
    self._set_auth_headers(headers)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\auth.py", line 310, in get_all_credentials
    auth_data[reg] = self._resolve_authconfig_credstore(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\auth.py", line 280, in _resolve_authconfig_credstore
    raise errors.DockerException(
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "".')
```

**Comment by hawflau** [comment]
@Form1ca AWS SAM CLI has nothing to do with gcloud. I'd suggest you check your Docker config file (`C:\ProgramData\Docker\config\daemon.json`). If there's any configuration related to gcloud auth, please consider remove it.

**Comment by CoshUS** [comment]
Closing as there is no response. Let me know if the issue persists.

**Comment by matusfaro** [comment]
For future readers, remove the key `credHelpers` entirely or just the entries with either `gcloud` or `gcr` from the `~/.docker/config.json` file.

`config.json` looks something like this:
```
...
   "credHelpers": {
     "asia.gcr.io": "gcr",
     "eu.gcr.io": "gcr",
     "gcr.io": "gcloud",
     "staging-k8s.gcr.io": "gcloud",
     "us.gcr.io": "gcloud"
   },
...
```
