### ISSUE TITLE
Change set is throwing an error while deploying the template.

### ISSUE THREAD

**Issue by Deepika-Raj** [aws/aws-sam-cli#3417]
### Description:

When I am deploying the template using SAM deploy. It is giving an error : 

**botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "DisableRollback", must be one of: ChangeSetName, StackName, ClientRequestToken**

I am not using either of **--disable-rollback | --no-disable-rollback** while deploying

### Steps to reproduce:

The command I am using : 

sam deploy --template-file packaged.yaml --stack-name <name of stack> --s3-bucket <name of bucket> --capabilities CAPABILITY_IAM --region $AWS_DEFAULT_REGION --parameter-overrides <list of parameters>

### Observed result:

Error with --debug flag:

Changeset created successfully. ***
2021-10-27 09:29:38,186 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'fb75737e-a71f-40ff-b874-f9c6d5b53f53', 'installationId': '47f3640c-0c6d-4159-9dac-4f18e6526b4d', 'sessionId': 'a629f491-1932-4811-b3b4-7532d1cdceb3', 'executionEnvironment': 'GitLab', 'ci': True, 'pyversion': '3.8.12', 'samcliVersion': '1.34.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'eu-west-1', 'commandName': 'sam deploy', 'duration': 16611, 'exitReason': 'ParamValidationError', 'exitCode': 255}}]}
2021-10-27 09:29:38,810 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/cli_validation/image_repository_validation.py", line 85, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 157, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/deploy/command.py", line 163, in cli
    do_cli(
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/deploy/command.py", line 317, in do_cli
    deploy_context.run()
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/deploy/deploy_context.py", line 161, in run
    return self.deploy(
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/deploy/deploy_context.py", line 265, in deploy
    self.deployer.execute_changeset(result["Id"], stack_name, disable_rollback)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 333, in execute_changeset
    return self._client.execute_change_set(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.8/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in input: "DisableRollback", must be one of: ChangeSetName, StackName, ClientRequestToken

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux
2. `sam --version`: 1.34.1
3. AWS region: eu-west-1

`Add --debug flag to command you are running`

**Comment by specious** [comment]
`pip install --user boto3==1.18.32` fixed this issue for me. I had `boto3==1.18.26` installed.

**Comment by btelman96** [comment]
I had `boto3-1.17.20` installed and ran into this issue. Now that I have the newer boto3 though it is no longer an issue for me.

```
Installing collected packages: botocore, s3transfer, boto3
  Attempting uninstall: botocore
    Found existing installation: botocore 1.20.20
    Uninstalling botocore-1.20.20:
      Successfully uninstalled botocore-1.20.20
  Attempting uninstall: s3transfer
    Found existing installation: s3transfer 0.3.4
    Uninstalling s3transfer-0.3.4:
      Successfully uninstalled s3transfer-0.3.4
  Attempting uninstall: boto3
    Found existing installation: boto3 1.17.20
    Uninstalling boto3-1.17.20:
      Successfully uninstalled boto3-1.17.20
Successfully installed boto3-1.18.32 botocore-1.21.65 s3transfer-0.5.0
```

Installing using that above command for `boto3==1.18.32` worked for me

I am using `SAM CLI, version 1.34.1` Installed via the installer on https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html

I previously came from Sam CLI version 1.15, so boto3 already existed. Not sure if that is needed to know, as updating it fixes issues that I had here.


One note though:
Unless I am not looking in the correct place, I don's see anywhere what version of boto3 is recommended or required for aws-sam-cli, or if it is even required at all.

**Comment by CoshUS** [comment]
Closing as the issue is due to boto3 installed version.
SAM CLI requirements can be found in https://github.com/aws/aws-sam-cli/blob/develop/requirements/base.txt

**Comment by specious** [comment]
> Closing as the issue is due to boto3 installed version. SAM CLI requirements can be found in https://github.com/aws/aws-sam-cli/blob/develop/requirements/base.txt

@CoshUS, thanks for taking a look. Those requirements [currently specify](https://github.com/aws/aws-sam-cli/blob/0f066b00748c80dd4bc98c4ead0c6892b90fafa7/requirements/base.txt#L5) `boto3~=1.18`.

At least minor version `1.18.32` is required.

**Comment by rodmaz** [comment]
Apparently it only works when we install `boto3` 1.18.32. Using a much more recent `boto3` version (1.26.19), it fails as well.
