### ISSUE TITLE
Docker is Asking to Connect to Google Cloud with properly installed SAM CLI

### ISSUE THREAD

**Issue by liamlindy** [aws/aws-sam-cli#3434]
### Description:

I am getting the following output when running a "Create SAM App in VS Code"

docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".')

It makes zero sense as A) there is an issue with a competing cloud vendor B) docker is running just fine on my local 

### Steps to reproduce:

I am using the VS Code steps outlined here(https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-mac.html) to develop Lambdas locally within VS Code

### Observed result:

```
2021-11-01 16:21:02 [INFO]: Running command: (not started) [/usr/local/bin/sam init --name sample-lambda --no-interactive --dependency-manager pip --runtime python3.8 --app-template hello-world --architecture x86_64]
2021-11-01 16:21:03 [INFO]: 
Cloning from https://github.com/aws/aws-sam-cli-app-templates

2021-11-01 16:22:13 [INFO]: Preparing to debug locally: Lambda "app.lambda_handler"
2021-11-01 16:22:13 [INFO]: Building SAM application...
2021-11-01 16:22:13 [INFO]: Running command: (not started) [/usr/local/bin/sam build --build-dir /tmp/aws-toolkit-vscode/vsctkEOpbj4/output --template /Users/liamlindy/aws-lambda-local/sample-lambda/template.yaml --manifest /tmp/aws-toolkit-vscode/vsctkEOpbj4/debug-requirements.txt]
2021-11-01 16:22:14 [INFO]: Building codeuri: /Users/liamlindy/aws-lambda-local/sample-lambda/hello_world runtime: python3.8 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']

2021-11-01 16:22:14 [INFO]: Running PythonPipBuilder:ResolveDependencies

2021-11-01 16:22:18 [INFO]: Running PythonPipBuilder:CopySource

2021-11-01 16:22:18 [INFO]: 
Build Succeeded

2021-11-01 16:22:18 [INFO]: 
Built Artifacts  : private/tmp/aws-toolkit-vscode/vsctkEOpbj4/output
Built Template   : private/tmp/aws-toolkit-vscode/vsctkEOpbj4/output/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke -t private/tmp/aws-toolkit-vscode/vsctkEOpbj4/output/template.yaml
[*] Deploy: sam deploy --guided --template-file private/tmp/aws-toolkit-vscode/vsctkEOpbj4/output/template.yaml
        

2021-11-01 16:22:18 [INFO]: Build complete.
2021-11-01 16:22:18 [INFO]: Starting SAM application locally
2021-11-01 16:22:18 [INFO]: AWS.running.command
Invoking app.lambda_handler (python3.8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image...Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/credentials/store.py", line 79, in _execute
    output = subprocess.check_output(
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/liamlindy/google-cloud-sdk/bin/docker-credential-gcloud', 'get']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/auth.py", line 264, in _resolve_authconfig_credstore
    data = store.get(registry)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/credentials/store.py", line 35, in get
    data = self._execute('get', server)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/credentials/store.py", line 93, in _execute
    raise errors.process_store_error(e, self.program)
docker.credentials.errors.StoreError: Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 157, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 83, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 221, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 90, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers, architecture)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 223, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 157, in build
    self._build_image(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 257, in _build_image
    resp_stream = self.docker_client.api.build(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/api/build.py", line 261, in build
    self._set_auth_headers(headers)
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/api/build.py", line 308, in _set_auth_headers
    auth_data = self._auth_configs.get_all_credentials()
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/auth.py", line 310, in get_all_credentials
    auth_data[reg] = self._resolve_authconfig_credstore(
  File "/usr/local/Cellar/aws-sam-cli/1.34.1/libexec/lib/python3.8/site-packages/docker/auth.py", line 280, in _resolve_authconfig_credstore
    raise errors.DockerException(
docker.errors.DockerException: Credentials store error: StoreError('Credentials store docker-credential-gcloud exited with "You do not currently have an active account selected. See https://cloud.google.com/sdk/docs/authorizing for more information.".')
Command stopped: "sam local invoke"
2021-11-01 16:22:21 [ERROR]: Timeout while waiting for command: "sam local invoke"
2021-11-01 16:22:21 [ERROR]: Failed to run SAM application locally: Timeout while waiting for command: "sam local invoke"
```
### Expected result:

Docker will connect to SAM and run locally 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac 
2. `sam --version`: 1.34.1
3. AWS region: US east 2

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
Seems like a local configuration issue. Do you have `gcloud` specified for public ECR repos in `~/.docker/config.json`?

**Comment by jfuss** [comment]
Closing. This can happen if you have logged into gcloud with Docker. This is not something we can address, as the error comes from the docker client.

To solve this, either  re-login or remove the login configuration for gcloud.
