### ISSUE TITLE
OSError: [Errno 36] File name too long

### ISSUE THREAD

**Issue by dkossako** [aws/aws-sam-cli#3441]
### Description:

Not able to download and call the layer locally.

### Steps to reproduce:

Command:
```
sam local invoke
```
with such template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: descr
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: index.handler
      Layers:
        - arn:aws:lambda:us-west-2:x:layer:api-layer:34
      Runtime: nodejs14.x
      Architectures:
        - x86_64

```

### Observed result:

It looks like aws sam tries to create alias, but instead of taking source file name, it takes its content:
```
Invoking index.handler (nodejs14.x)
Downloading arn:aws:lambda:us-west-2:x:layer:api-layer  [####################################]  14186737/14186737
Traceback (most recent call last):
  File "/home/daniel/.linuxbrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 157, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 83, in cli
    do_cli(
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 221, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 90, in __init__
    image = LambdaContainer._get_image(lambda_image, runtime, packagetype, imageuri, layers, architecture)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 223, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 130, in build
    downloaded_layers = self.layer_downloader.download_all(layers, self.force_image_build)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 77, in download_all
    layer_dirs.append(self.download(layer, force))
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/layers/layer_downloader.py", line 112, in download
    unzip_from_uri(
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 181, in unzip_from_uri
    unzip(layer_zip_path, unzip_output_dir, permission=0o700)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 99, in unzip
    extracted_path = _extract(file_info, output_dir, zip_ref)
  File "/home/daniel/.linuxbrew/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/local/lambdafn/zip.py", line 76, in _extract
    os.symlink(source, link_name)
OSError: [Errno 36] File name too long: '#!/usr/bin/env node\n"use strict";\n\nvar log = require("npmlog");\nvar _ = require("lodash");\nvar BuildSystem = require("../").BuildSystem;\nvar util = require("util");\nvar version = require("../package").version;\nvar logLevels = ["silly", "verbose", "info", "http", "warn", "error"];\n\nvar npmConfigData = require("rc")("npm");\nfor (var key of _.keys(npmConfigData)) {\n    if (_.startsWith(key, "cmake_js_")) {\n        var option = key.substr(9);\n        if (option.length === 1) {\n            process.argv.push("-" + option);\n        }\n        else {\n            process.argv.push("--" + option);\n        }\n        if (npmConfigData[key]) {\n            process.argv.push(npmConfigData[key]);\n        }\n    }\n}\n\nconsole.log(process.argv);\n\nvar yargs = require("yargs")\n    .usage("CMake.js " + version + "\\n\\nUsage: $0 [<command>] [options]")\n    .version(function () {\n        return version;\n    })\n    .command("install", "Install Node.js/io.js distribution files if needed")\n    .command("configure", "Configure CMake project")\n    .command("print-configure", "Print the configuration command")\n    .command("build", "Build the project (will configure first if required)")\n    .command("print-build", "Print the build command")\n    .command("clean", "Clean the project directory")\n    .command("print-clean", "Print the clean command")\n    .command("reconfigure", "Clean the project directory then configure the project")\n    .command("rebuild", "Clean the project directory then build the project")\n    .command("compile", "Build the project, and if build fails, try a full rebuild")\n    .options({\n        h: {\n            alias: "help",\n            demand: false,\n            describe: "show this screen",\n            type: "boolean"\n        },\n        l: {\n            alias: "log-level",\n            demand: false,\n            describe: "set log level (" + logLevels.join(", ") + "), default is info",\n            type: "string"\n        },\n        d: {\n            alias: "directory",\n            demand: false,\n            describe: "specify CMake project\'s directory (where CMakeLists.txt located)",\n            type: "string"\n        },\n        D: {\n            alias: "debug",\n            demand: false,\n            describe: "build debug configuration",\n            type: "boolean"\n        },\n        c: {\n            alias: "cmake-path",\n            demand: false,\n            describe: "path of CMake executable",\n            type: "string"\n        },\n        m: {\n            alias: "prefer-make",\n            demand: false,\n            describe: "use Unix Makefiles even if Ninja is available (Posix)",\n            type: "boolean"\n        },\n        x: {\n            alias: "prefer-xcode",\n            demand: false,\n            describe: "use Xcode instead of Unix Makefiles",\n            type: "boolean"\n        },\n        g: {\n            alias: "prefer-gnu",\n            demand: false,\n            describe: "use GNU compiler instead of default CMake compiler, if available (Posix)",\n            type: "boolean"\n        },\n        G: {\n            alias: "generator",\n            demand: false,\n            describe: "use specified generator",\n            type: "string"\n        },\n        t: {\n            alias: "toolset",\n            demand: false,\n            describe: "use specified toolset",\n            type: "string"\n        },\n        A: {\n            alias: "platform",\n            demand: false,\n            describe: "use specified platform name",\n            type: "string"\n        },\n        T: {\n            alias: "target",\n            demand: false,\n            describe: "only build the specified target",\n            type: "string"\n        },\n        C: {\n            alias: "prefer-clang",\n            demand: false,\n            describe: "use Clang compiler instead of default CMake compiler, if available (Posix)",\n            type: "boolean"\n        },\n        cc: {\n            demand: false,\n            describe: "use the specified C compiler",\n            type: "string"\n        },\n        cxx: {\n            demand: false,\n            describe: "use the specified C++ compiler",\n            type: "string"\n        },\n        r: {\n            alias: "runtime",\n            demand: false,\n            describe: "the runtime to use",\n            type: "string"\n        },\n        v: {\n            alias: "runtime-version",\n            demand: false,\n            describe: "the runtime version to use",\n            type: "string"\n        },\n        a: {\n            alias: "arch",\n            demand: false,\n            describe: "the architecture to build in",\n            type: "string"\n        },\n        "CD": {\n            demand: false,\n            describe: "Custom argument passed to CMake in format: -D<your-arg-here>",\n            type: "string"\n        },\n        i: {\n            alias: "silent",\n            describe: "Prevents CMake.js to print to the stdio",\n            type: "boolean"\n        },\n        O: {\n          alias: "out",\n          describe: "Specify the output directory to compile to, default is projectRoot/build",\n          type: "string"\n        }\n    });\nvar argv = yargs.argv;\n\n// If help, then print and exit:\n\nif (argv.h) {\n    console.info(yargs.help());\n    process.exit(0);\n}\n\n// Setup log level:\n\nif (argv.l && _.includes(logLevels, argv.l)) {\n    log.level = argv.l;\n    log.resume();\n}\n\nlog.silly("CON", "argv:");\nlog.silly("CON", util.inspect(argv));\n\nlog.verbose("CON", "Parsing arguments");\n\n// Extract custom cMake options\nvar customOptions = {};\n_.keys(argv).forEach(function (key) {\n    if (argv[key] && _.startsWith(key, "CD")) {\n        customOptions[key.substr(2)] = argv[key];\n    }\n});\n\nvar options = {\n    directory: argv.directory || null,\n    debug: argv.debug,\n    cmakePath: argv.c || null,\n    generator: argv.G,\n    toolset: argv.t,\n    platform: argv.A,\n    target: argv.T,\n    preferMake: argv.m,\n    preferXcode: argv.x,\n    preferGnu: argv.g,\n    preferClang: argv.C,\n    cCompilerPath: argv.cc,\n    cppCompilerPath: argv.cxx,\n    runtime: argv.r,\n    runtimeVersion: argv.v,\n    arch: argv.a,\n    cMakeOptions: customOptions,\n    silent: argv.i,\n    out: argv.O\n};\n\nlog.verbose("CON", "options:");\nlog.verbose("CON", util.inspect(options));\n\nvar command = _.first(argv._) || "build";\n\nlog.verbose("CON", "Running command: " + command);\n\nvar buildSystem = new BuildSystem(options);\n\nfunction ifCommand(c, f) {\n    if (c === command) {\n        f();\n        return true;\n    }\n    return false;\n}\n\nfunction exitOnError(promise) {\n    promise.catch(function () {\n        process.exit(1);\n    });\n}\n\nfunction install() {\n    exitOnError(buildSystem.install());\n}\nfunction configure() {\n    exitOnError(buildSystem.configure());\n}\nfunction printConfigure() {\n    exitOnError(buildSystem.getConfigureCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction build() {\n    exitOnError(buildSystem.build());\n}\nfunction printBuild() {\n    exitOnError(buildSystem.getBuildCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction clean() {\n    exitOnError(buildSystem.clean());\n}\nfunction printClean() {\n    exitOnError(buildSystem.getCleanCommand()\n        .then(function (command) {\n            console.info(command);\n        }));\n}\nfunction reconfigure() {\n    exitOnError(buildSystem.reconfigure());\n}\nfunction rebuild() {\n    exitOnError(buildSystem.rebuild());\n}\nfunction compile() {\n    exitOnError(buildSystem.compile());\n}\n\nvar done = ifCommand("install", install);\ndone = done || ifCommand("configure", configure);\ndone = done || ifCommand("print-configure", printConfigure);\ndone = done || ifCommand("build", build);\ndone = done || ifCommand("print-build", printBuild);\ndone = done || ifCommand("clean", clean);\ndone = done || ifCommand("print-clean", printClean);\ndone = done || ifCommand("reconfigure", reconfigure);\ndone = done || ifCommand("rebuild", rebuild);\ndone = done || ifCommand("compile", compile);\n\nif (!done) {\n    if (command) {\n        log.error("COM", "Unknown command: " + command);\n        process.exit(1);\n    }\n    else {\n        build();\n    }\n}\n' -> '/tmp/api-layer-34-eb81dda049/nodejs/node_modules/.bin/cmake-js'
```

### Expected result:

Correctly downloaded layer

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04
2. `sam --version`: SAM CLI, version 1.35.0
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
Hey @dkossako,
I wasn't able to reproduce the error. Can you provide the layer ZIP file that caused the issue?

**Comment by dkossako** [comment]
Sure: https://www55.zippyshare.com/v/renAMUZg/file.html

**Comment by CoshUS** [comment]
Seems like the zip file itself is incorrectly packaged. The `nodejs/node_modules/.bin/cmake-js` has the external attribute of `S_IFLNK  0120000` which is a symbolic link, but the content is just a script. 
If you try to unzip this with another tool like `unzip` in ubuntu, the same issue will occur.

Closing as this is not related to SAM CLI. Let me know if there are other issues.
