### ISSUE TITLE
sam logs can't errors out on named stagename

### ISSUE THREAD

**Issue by maplion** [aws/aws-sam-cli#3446]
### Description:
When I attempt to run the command `sam logs --stack-name <stack name> --include-traces --tail --profile <profile> --region us-east-1` against a stack with a named stage name (in this case "v1"), it errors out.

### Steps to reproduce:
Run the command `sam logs --stack-name <stack name> --include-traces --tail --profile <profile> --region us-east-1` after sam syncing an API Gateway with a named stage.

### Observed result:
I get the following error:

```shell
Experimental features are enabled for this session.
Visit the docs page to learn more about the AWS Beta terms https://aws.amazon.com/service-terms/.

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 157, in wrapped
  File "samcli/lib/telemetry/metric.py", line 122, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 87, in wrapper
  File "samcli/commands/_utils/experimental.py", line 198, in wrapped_func
  File "samcli/commands/_utils/experimental.py", line 198, in wrapped_func
  File "samcli/commands/_utils/experimental.py", line 198, in wrapped_func
  File "samcli/commands/logs/command.py", line 120, in cli
  File "samcli/commands/logs/command.py", line 171, in do_cli
  File "samcli/commands/logs/puller_factory.py", line 84, in generate_puller
  File "samcli/lib/observability/cw_logs/cw_log_group_provider.py", line 32, in for_resource
  File "samcli/commands/_utils/experimental.py", line 176, in wrapped_func
  File "samcli/lib/observability/cw_logs/cw_log_group_provider.py", line 104, in for_apigwv2_http_api
  File "botocore/client.py", line 388, in _api_call
  File "botocore/client.py", line 708, in _make_api_call
botocore.errorfactory.NotFoundException: An error occurred (NotFoundException) when calling the GetStage operation: Invalid stage identifier specified
```

I'm guessing that stage is not supported yet.  Is there a workaround?

### Expected result:
My sam logs connects and gives me near real-time log output. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
2. `sam --version`: 1.35.0
3. AWS region: us-east-1

`Add --debug flag to command you are running`

**Comment by CoshUS** [comment]
Hey @maplion,
Thanks for reporting the issue. Currently only `$default` stage for V2 and `Prod` stage for V1 are supported. We will look into adding option to specify named stages in the future.

**Comment by jcranendonk** [comment]
Serverless Framework creates a named stage when using a WebSocket event source, which means you can no longer listen to all logs for the stack. This is currently blocking me.

**Comment by maplion** [comment]
@jcranendonk If you're purely using AWS, I recommend switching to SAM [and incidentally, so do the developers over at Severless].  I switched to pure SAM templates and prefer it.  It doesn't take long to swap over either as most of it, save for variables, is the same and you get more flexibility with templates (e.g., you can use different templates for different ci-cd purposes) and you get bonus features like being able to use all sam accelerate has to offer.

**Comment by AndrazPustotnik** [comment]
Any solutions here? I am having the same issue (`Error: An error occurred (NotFoundException) when calling the GetStage operation: Invalid stage identifier specified`) when using `sam logs --stack-name MyStackName --tail` :/ Could it be the problem since I am running websocket? Because if I try with HelloWorld template it all works fine...

**Comment by brianjd** [comment]
I'm using pure SAM and ran into this issue when I added a websocket resources to the stack.
