### ISSUE TITLE
Cannot locally debug lambda because SAM does not copy transitive dependencies 

### ISSUE THREAD

**Issue by emaayan** [aws/aws-sam-cli#3486]
### Description:
when trying to debug a lambda function, SAM will fail if the code includes libraries that have transitive dependencies

### Steps to reproduce:
1. create a sample code that uses any aws sdk (v2) like s3
2. launch a local debug process in intellij 

### Observed result:
failure with the following exception 
java.lang.ExceptionInInitializerError
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Unable to load an HTTP implementation from any provider in the chain. You must declare a dependency on an appropriate HTTP implementation or pass in an SdkHttpClient explicitly to the client builder.
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:98)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.lambda$buildWithDefaults$1(DefaultSdkHttpClientBuilder.java:49)
	at java.base/java.util.Optional.orElseThrow(Unknown Source)
	at software.amazon.awssdk.core.internal.http.loader.DefaultSdkHttpClientBuilder.buildWithDefaults(DefaultSdkHttpClientBuilder.java:43)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.lambda$resolveSyncHttpClient$5(SdkDefaultClientBuilder.java:274)
	at java.base/java.util.Optional.orElseGet(Unknown Source)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.resolveSyncHttpClient(SdkDefaultClientBuilder.java:274)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.finalizeSyncConfiguration(SdkDefaultClientBuilder.java:225)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.syncClientConfiguration(SdkDefaultClientBuilder.java:158)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:27)
	at software.amazon.awssdk.services.s3.DefaultS3ClientBuilder.buildClient(DefaultS3ClientBuilder.java:22)
	at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:129)

### Expected result:
being able to debug 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 
2. `sam --version`: 1.35
3. AWS region: us-east-1

the reason for this is that copy dependency stage in maven.py only uses compile, meaning any transitive libraries such as http core that aws sdk uses behind the scenes won't get copied

**Comment by ssenchenko** [comment]
So sorry you encountered a bug! Thanks for reporting the issue, we will be investigating it further.
