### ISSUE TITLE
sam cli does not create AWS::ApiGateway::Stage when using AWS::Serverless::Api

### ISSUE THREAD

**Issue by saraiyakush** [aws/aws-sam-cli#3487]
### Description:
I am using a `sam` template to manage my API and Lambdas and when I try to deploy the template using `sam deploy`, sam does not create the api gateway Stage and I think that's why the ai gateway deployment resource is failing too.

### Steps to reproduce:
Here is my `template.yaml` file.
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DEMO API

Resources:
  DemoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DEMO API
      StageName: DEV
      TracingEnabled: true
      EndpointConfiguration: EDGE
      DefinitionUri: api.yaml

  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoFunction
      Description: Function to handle DEMO api calls
      Runtime: java11
      Handler: com.example::handle
      CodeUri: .
      Events:
        DemoPostEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DemoApi
            Path: '/'
            Method: POST
```
I ran
`sam build`
`sam package --output-template-file output-template-1.yaml --resolve-s3`
`sam deploy --template-file output-template-1.yaml --stack-name DEMO --capabilities CAPABILITY_IAM --region us-east-1 --debug --disable-rollback`

As you can see below, the change set shows a Stage with logical id `DemoApiDEVStage` will be created but there is no stage created after the stack is created.
For troubleshooting purposes, I used `--disable-rollback` flag and I verified that there is no stage created inside the new Demo api in the console.

### Observed result:
```
	Deploying with following values
	===============================
	Stack name                   : DEMO
	Region                       : us-east-1
	Confirm changeset            : False
	Disable rollback             : True
	Deployment s3 bucket         : None
	Capabilities                 : ["CAPABILITY_IAM"]
	Parameter overrides          : {}
	Signing Profiles             : {}

Initiating deployment
=====================
2021-11-22 14:13:11,305 | No Parameters detected in the template
2021-11-22 14:13:11,333 | 2 stacks found in the template
2021-11-22 14:13:11,333 | No Parameters detected in the template
2021-11-22 14:13:11,355 | 2 resources found in the stack 
2021-11-22 14:13:11,356 | No Parameters detected in the template
2021-11-22 14:13:12,370 | Stack with id DEMO does not exist

Waiting for changeset to be created..

CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Operation                                      LogicalResourceId                              ResourceType                                   Replacement                                  
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
+ Add                                          DemoApiDEVStage                                AWS::ApiGateway::Stage                         N/A                                          
+ Add                                          DemoApiDeploymentcb13dd876d                    AWS::ApiGateway::Deployment                    N/A                                          
+ Add                                          DemoApi                                        AWS::ApiGateway::RestApi                       N/A                                          
+ Add                                          DemoFunctionDemoPostEventPermissionDEV         AWS::Lambda::Permission                        N/A                                          
+ Add                                          DemoFunctionRole                               AWS::IAM::Role                                 N/A                                          
+ Add                                          DemoFunction                                   AWS::Lambda::Function                          N/A                                          
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:452295442916:changeSet/samcli-deploy1637570592/bbfa74d9-2f70-4770-8a7e-f818ae4a1430


2021-11-22 14:13:24 - Waiting for stack create/update to complete

CloudFormation events from stack operations
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                                 ResourceType                                   LogicalResourceId                              ResourceStatusReason                         
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                             AWS::ApiGateway::RestApi                       DemoApi                                        -                                            
CREATE_IN_PROGRESS                             AWS::IAM::Role                                 DemoFunctionRole                               Resource creation Initiated                  
CREATE_IN_PROGRESS                             AWS::IAM::Role                                 DemoFunctionRole                               -                                            
CREATE_COMPLETE                                AWS::ApiGateway::RestApi                       DemoApi                                        -                                            
CREATE_IN_PROGRESS                             AWS::ApiGateway::RestApi                       DemoApi                                        Resource creation Initiated                  
CREATE_IN_PROGRESS                             AWS::ApiGateway::Deployment                    DemoApiDeploymentcb13dd876d                    -                                            
CREATE_FAILED                                  AWS::ApiGateway::Deployment                    DemoApiDeploymentcb13dd876d                    No integration defined for method (Service:  
                                                                                                                                             AmazonApiGateway; Status Code: 400; Error    
                                                                                                                                             Code: BadRequestException; Request ID:       
                                                                                                                                             06323cd5-2a75-4083-bc5b-70a9baf831cf; Proxy: 
                                                                                                                                             null)                                        
CREATE_COMPLETE                                AWS::IAM::Role                                 DemoFunctionRole                               -                                            
CREATE_IN_PROGRESS                             AWS::Lambda::Function                          DemoFunction                                   -                                            
CREATE_IN_PROGRESS                             AWS::Lambda::Function                          DemoFunction                                   Resource creation Initiated                  
CREATE_COMPLETE                                AWS::Lambda::Function                          DemoFunction                                   -                                            
CREATE_IN_PROGRESS                             AWS::Lambda::Permission                        DemoFunctionDemoPostEventPermissionDEV         Resource creation Initiated                  
CREATE_IN_PROGRESS                             AWS::Lambda::Permission                        DemoFunctionDemoPostEventPermissionDEV         -                                            
CREATE_COMPLETE                                AWS::Lambda::Permission                        DemoFunctionDemoPostEventPermissionDEV         -                                            
CREATE_FAILED                                  AWS::CloudFormation::Stack                     DEMO                                           The following resource(s) failed to create:  
                                                                                                                                             [DemoApiDeploymentcb13dd876d].               
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2021-11-22 14:14:12,864 | Execute stack waiter exception
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 459, in wait_for_execute
    waiter.wait(StackName=stack_name, WaiterConfig=waiter_config)
  File "/usr/local/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.35.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 350, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "CREATE_FAILED" at least once
2021-11-22 14:14:12,868 | 
Failed to deploy. Automatic rollback disabled for this deployment.

Actions you can take next
=========================
[*] Fix issues and try deploying again
[*] Roll back stack to the last known stable state: aws cloudformation rollback-stack --stack-name DEMO
```

### Expected result:
A Stage with the name `DEV` should have been created **BEFORE** creating the deployment resource.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: `Mac`
2. `sam --version`: `SAM CLI, version 1.35.0`
3. AWS region: `us-east-1`

**Comment by wchengru** [comment]
Hi @saraiyakush , the error message shows that the method defined on your API has no integration details. Can you please check if your openapi file `api.yaml` includes the integration definitions.

**Comment by saraiyakush** [comment]
Hi @wchengru Yes my `api.yaml` file does have the `x-amazon-apigateway-integration` defined on the method. Here is a snippet from my yaml file.

```yaml
paths:
  '/entity':
    post:
      summary: 'Creates an entity'
      operationId: createEntity
      requestBody:
        $ref: '#/components/requestBodies/CreateEntityRequestBody'
      responses:
        <<: *error-responses
        '200':
          description: 'Successfully created entity'
          headers:
            <<: *access-control-headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEntityResponse'
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/create-entity-lambda-integration'
```
Under `components`, I have this
```yaml
x-amazon-apigateway-integrations:
    create-entity-lambda-integration:
      <<: *sa-lambda-integration
      requestTemplates:
        application/json: |
          {
            "type": "CreateEntityEvent",
          }
```
And I have declared the integration as an anchor
```yaml
sa-lambda-integration: &sa-lambda-integration
    type: aws
    httpMethod: POST
    uri:
      Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DemoFunction.Arn}/invocations'
    passthroughBehavior: when_no_templates
    responses:
      default:
        statusCode: 200
        responseTemplates:
          application/json: $input.body
        responseParameters: *api-gateway-integration-response-parameters
      '.*400.*':
        statusCode: 400
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*401.*':
        statusCode: 401
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*403.*':
        statusCode: 403
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*404.*':
        statusCode: 404
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*500.*':
        statusCode: 500
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
```

I also verified that I get the same error if I first resolve my YAML anchors and use that yaml.

Let me know if you need more information.

**Comment by saraiyakush** [comment]
To help you further, here are my complete `demo-template.yaml` and `demo-api.yaml` files. You should be able to use them as is to reproduce the issue.
`demo-api.yaml`
```yaml
openapi: 3.0.1
info:
  version: '1.0.0'
  title: 'Demo API'
servers:
  - url: 'localhost:3000'

# The following definitions will be used throughout the spec
x-definitions:
  # Common Access Control headers
  access-control-headers: &access-control-headers
    Access-Control-Allow-Origin:
      $ref: '#/components/headers/Access-Control-Allow-Origin'
    Access-Control-Allow-Methods:
      $ref: '#/components/headers/Access-Control-Allow-Methods'
    Access-Control-Allow-Headers:
      $ref: '#/components/headers/Access-Control-Allow-Headers'

  # Common error responses
  error-responses: &error-responses
    '400':
      $ref: '#/components/responses/400'
    '401':
      $ref: '#/components/responses/401'
    '403':
      $ref: '#/components/responses/403'
    '404':
      $ref: '#/components/responses/404'
    '500':
      $ref: '#/components/responses/500'

  # -- AWS API Gateway specific mappings --

  api-gateway-error-mapping: &api-gateway-error-mapping |
    #set( $root = $util.parseJson($input.path('$.errorMessage')) )
    {
      "error_code": $root.code,
      "error_Message": "$root.Message",
      "error_trace": "$root.trace",
      "aws_request_id": "$context.requestId"
    }

  # Common mappings for errors returns at API level (language=VTL)
  api-gateway-default-error-mapping: &api-gateway-default-error-mapping |
    {
      "error_Message": "$context.error.Message",
      "aws_request_id": "$context.requestId"
    }

  # Integration response parameters
  api-gateway-integration-response-parameters: &api-gateway-integration-response-parameters
    method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
    method.response.header.Access-Control-Allow-Headers: "'Content-Type,Cache-Control,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
    method.response.header.Access-Control-Allow-Origin: "'*'"
    method.response.header.Access-Control-Max-Age: 60

  # Gateway response parameters
  gateway-response-parameters: &gateway-response-parameters
    gatewayresponse.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
    gatewayresponse.header.Access-Control-Allow-Headers: "'Content-Type,Cache-Control,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
    gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
    gatewayresponse.header.Access-Control-Max-Age: 60

  # Common properties for apigateway Lambda integration
  demo-lambda-integration: &demo-lambda-integration
    type: aws
    httpMethod: POST
    uri:
      Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DemoFunction.Arn}/invocations'
    passthroughBehavior: when_no_templates
    responses:
      default:
        statusCode: 200
        responseTemplates:
          application/json: $input.body
        responseParameters: *api-gateway-integration-response-parameters
      '.*400.*':
        statusCode: 400
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*401.*':
        statusCode: 401
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*403.*':
        statusCode: 403
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*404.*':
        statusCode: 404
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters
      '.*500.*':
        statusCode: 500
        responseTemplates:
          application/json: *api-gateway-error-mapping
        responseParameters: *api-gateway-integration-response-parameters


paths:
  '/entity':
    post:
      operationId: createEntity
      responses:
        <<: *error-responses
        '200':
          description: 'Successfully created Entity'
          headers:
            <<: *access-control-headers
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateEntityResponse'
      x-amazon-apigateway-integration:
        $ref: '#/components/x-amazon-apigateway-integrations/demo-post-entitys-lambda-integration'


components:
  headers:
    Access-Control-Allow-Origin:
      schema:
        description: Specifying which web sites can participate in cross-origin resource sharing.
        type: string
    Access-Control-Allow-Methods:
      schema:
        description: Specifies the method or methods allowed when accessing the resource in response to a preflight request.
        type: string
    Access-Control-Allow-Headers:
      schema:
        description: Specifies which HTTP headers can be used during the actual request.
        type: string
  schemas:
    CreateEntityResponse:
      title: Create Entity Response
      description: Create Entity Response
      type: object
      required:
        - entity
      properties:
        entity:
          title: Entity
          description: Entity
          type: string
          example: 'PEFjdGl2YXRpb24+PEluZm8+PEhXQ29kZT5bMWZQcGVYR1ZaUGcxc2FDR0dndVdSNCtGZm85RGNrTEUxc0o4TlNHTzVxNlBPWjJkUjwvSFdDb2RlPjxVc2VyPlRlc3RVc2VyPC9Vc2VyPjxVc2VySUQ+RGVtb0FwcDwvVXNlcklEPjxPcmc+Qm9iY2F0IE5EU1U8L09yZz48T3JnSUQ+PC9PcmdJRD48Um9sZT5FbmdpbmVlcjwvUm9sZT48QXBwPlNlcnZpY2VBbmFseXplcjwvQXBwPjxBY3RpdmF0ZWRPbj4yMDIxLTExLTE2VDE0OjU1OjQxLjY4NDExODQtMDY6MDA8L0FjdGl2YXRlZE9uPjxBY3RpdmF0ZWRGb3I+MTA5NS4wMDowMDowMDwvQWN0aXZhdGVkRm9yPjwvSW5mbz48U2lnbmF0dXJlPmZuazdYUTJUa3dybjRFakViNEc4TzVCZGUrVnd0d0hNdWdcVJDWHRUYTFaSmIvdjNLUjRTRmdXMTFORWZ4M1ZNLzg1eUpZdzdJeGhsSm1SSEhieUhRPT08L1NpZ25hdHVyZT48U2lnbmVkQnk+Qm9iY2F0U2VydmVyPC9TaWduZWRCeT48L0FjdGl2YXRpb24+'
    Error:
      title: Demo Error
      description: Demo Error
      type: object
      required:
        - errorCode
        - errorMessage
        - awsRequestId
      properties:
        errorCode:
          title: HTTP Error Code
          description: HTTP Error Code
          type: integer
          example: 404
        errorMessage:
          title: Error Message
          description: Error Message
          type: string
          example: Not found
        awsRequestId:
          title: AWS Request Id
          description: AWS Request ID that can be retrieved from the request context
          type: string
          example: a12i03aksd10293A
  responses:
    '400':
      description: Bad request response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        <<: *access-control-headers
    '401':
      description: Unauthorized response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        <<: *access-control-headers
    '403':
      description: Forbidden response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        <<: *access-control-headers
    '404':
      description: Not Found response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        <<: *access-control-headers
    '500':
      description: Internal Server Error response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
      headers:
        <<: *access-control-headers

  # AWS API Gateway specific components
  x-amazon-apigateway-integrations:
    demo-post-entitys-lambda-integration:
      <<: *demo-lambda-integration
      requestTemplates:
        application/json: |
          {
            "type": "CreateEntityEvent"
          }


# Define available request validators
x-amazon-apigateway-request-validators:
  all:
    validateRequestBody: true
    validateRequestParameters: true
  params-only:
    validateRequestBody: false
    validateRequestParameters: true


# Enable global request validator
x-amazon-apigateway-request-validator: params-only


# Define global gateway responses
x-amazon-apigateway-gateway-responses:
  DEFAULT_4XX:
    responseParameters: *gateway-response-parameters
    responseTemplates:
      application/json: *api-gateway-default-error-mapping
  DEFAULT_5XX:
    responseParameters: *gateway-response-parameters
    responseTemplates:
      application/json: *api-gateway-default-error-mapping
```
`demo-template.yaml`
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo API

Resources:
  DemoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: Demo API
      StageName: DEV
      DefinitionUri: demo-api.yaml
  DemoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DemoFunction
      Description: Function to handle Demo api calls
      Runtime: java11
      Handler: com.example::handle
      CodeUri: .
      Events:
        DemoEvent:
          Type: Api
          Properties:
            RestApiId:
              Ref: DemoApi
            Path: /entity
            Method: POST
```

**Comment by saraiyakush** [comment]
So I think I figured out the root cause of why the stack was failing. Turns out it had nothing to do with `Stage` or `Deployment` but `sam deploy` command is unable to parse and transform a YAML that has anchors in it. In my `demo-api.yaml` if I explicitly write the `x-amazon-apigateway-integration` without using `<<:` or `$ref:` to the `components` section then sam was able to deploy my stack successfully.

So even though there is an issue with sam cli, this seems to be a separate issue. I will probably open another issue for that.

**Comment by jfuss** [comment]
@saraiyakush SAM CLI and SAM (`AWS::Serverless::*`) Resources does not resolve anchors and just passes this through to the service. This is a failure happening within the API Gateway service, which is not something we control. I can pass on the feature request to them however.

**Comment by saraiyakush** [comment]
Thanks @jfuss ! I will close this now.
