### ISSUE TITLE
Sam sync removes node_modules in lambda layer

### ISSUE THREAD

**Issue by cshenrik** [aws/aws-sam-cli#3494]
### Description: 
I have a sam application that contains a nodejs14.x Lambda function that references a Lambda layer with a library installed in `node_modules`. The first time I run `sam sync --watch`, all works fine. When I stop the watcher and restart it, it deletes the `node_modules` folder in `.aws-sam/auto-dependency-layer/SharedLayer/nodejs/node_modules` (where `SharedLayer` is my Lambda Layer). Consequently my Lambda function is broken.

My workaround is to modify the `manifest_hash` value of the Lambda layer in `.aws-sam/build.toml`, and make a dummy change in the code of the Lambda layer. This triggers the watcher, so it correctly builds and syncs the layer + dependent functions. 

### Steps to reproduce:
1) Clone this repo: https://github.com/cshenrik/accelerate-bug.
1) Run `sam sync --watch --stack-name <STACK_NAME>`.
1) Wait until the initial sync is done.
1) Exit the watcher by hitting ctrl + c.
1) Run `sam sync --watch --stack-name <STACK_NAME>` again.

Then `.aws-sam/auto-dependency-layer/SharedLayer/nodejs/node_modules` has been deleted, and the Lambda function is broken.  

### Observed result:
This is the output from running the second `sam sync` in step 5 (though with --debug):
```2021-11-24 20:34:31,079 | No Parameters detected in the template
2021-11-24 20:34:31,099 | 3 stacks found in the template
2021-11-24 20:34:31,099 | No Parameters detected in the template
2021-11-24 20:34:31,113 | 3 resources found in the stack 
2021-11-24 20:34:31,113 | No Parameters detected in the template
2021-11-24 20:34:31,126 | No Parameters detected in the template
2021-11-24 20:34:31,140 | --base-dir is not presented, adjusting uri shared/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,140 | Found Serverless function with name='SayHelloFunction' and CodeUri='say-hello/'
2021-11-24 20:34:31,140 | --base-dir is not presented, adjusting uri say-hello/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,140 | No Parameters detected in the template
2021-11-24 20:34:31,153 | --base-dir is not presented, adjusting uri shared/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,173 | Queued infra sync. Wating for in progress code syncs to complete...
2021-11-24 20:34:31,174 | Starting infra sync.
2021-11-24 20:34:31,184 | No Parameters detected in the template
2021-11-24 20:34:31,201 | 3 stacks found in the template
2021-11-24 20:34:31,201 | No Parameters detected in the template
2021-11-24 20:34:31,215 | 3 resources found in the stack 
2021-11-24 20:34:31,215 | No Parameters detected in the template
2021-11-24 20:34:31,228 | No Parameters detected in the template
2021-11-24 20:34:31,243 | --base-dir is not presented, adjusting uri shared/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,243 | Found Serverless function with name='SayHelloFunction' and CodeUri='say-hello/'
2021-11-24 20:34:31,243 | --base-dir is not presented, adjusting uri say-hello/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,243 | No Parameters detected in the template
2021-11-24 20:34:31,255 | --base-dir is not presented, adjusting uri shared/ relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,256 | Instantiating build definitions
2021-11-24 20:34:31,260 | Same function build definition found, adding function (Previous: BuildDefinition(nodejs14.x, /home/henrik/code/accelerate-bug/say-hello, Zip, , d4fbbd94-b684-4533-9386-944b156f0d9c, {}, {}, x86_64, []), Current: BuildDefinition(nodejs14.x, /home/henrik/code/accelerate-bug/say-hello, Zip, , d59cc2b5-5805-4e84-bb60-3d19648d581f, {}, {}, x86_64, []), Function: Function(name='SayHelloFunction', functionname='SayHelloFunction', runtime='nodejs14.x', memory=1024, timeout=3, handler='app.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/henrik/code/accelerate-bug/say-hello', environment=None, rolearn=None, layers=[<samcli.lib.providers.provider.LayerVersion object at 0x7f744d989fd0>], events={'HttpGet': {'Type': 'HttpApi', 'Properties': {'Path': '/say-hello', 'Method': 'get', 'ApiId': 'ServerlessHttpApi'}}}, metadata=None, inlinecode=None, codesign_config_arn=None, architectures=None, stack_path=''))
2021-11-24 20:34:31,260 | Same Layer build definition found, adding layer (Previous: LayerBuildDefinition(SharedLayer, /home/henrik/code/accelerate-bug/shared, , 3d1b6ddd-2760-449c-9d26-346390ef5a4f, nodejs14.x, ['nodejs14.x'], x86_64, {}), Current: LayerBuildDefinition(SharedLayer, /home/henrik/code/accelerate-bug/shared, , 489aa9fd-dd20-4134-bede-7fa22b03dc46, nodejs14.x, ['nodejs14.x'], x86_64, {}), Layer: <samcli.lib.providers.provider.LayerVersion object at 0x7f744d9890d0>)
2021-11-24 20:34:31,262 | Async execution started
2021-11-24 20:34:31,262 | Invoking function functools.partial(<bound method CachedOrIncrementalBuildStrategyWrapper.build_single_function_definition of <samcli.lib.build.build_strategy.CachedOrIncrementalBuildStrategyWrapper object at 0x7f744d88b910>>, <samcli.lib.build.build_graph.FunctionBuildDefinition object at 0x7f744d8861d0>)
2021-11-24 20:34:31,262 | Running incremental build for runtime nodejs14.x for build definition d4fbbd94-b684-4533-9386-944b156f0d9c
2021-11-24 20:34:31,262 | Invoking function functools.partial(<bound method CachedOrIncrementalBuildStrategyWrapper.build_single_layer_definition of <samcli.lib.build.build_strategy.CachedOrIncrementalBuildStrategyWrapper object at 0x7f744d88b910>>, <samcli.lib.build.build_graph.LayerBuildDefinition object at 0x7f744d886550>)
2021-11-24 20:34:31,263 | Running incremental build for runtime nodejs14.x for build definition 3d1b6ddd-2760-449c-9d26-346390ef5a4f
2021-11-24 20:34:31,263 | Waiting for async results
2021-11-24 20:34:31,264 | Manifest is not changed for 3d1b6ddd-2760-449c-9d26-346390ef5a4f, running incremental build
2021-11-24 20:34:31,264 | Building layer 'SharedLayer'
2021-11-24 20:34:31,264 | Loading workflow module 'aws_lambda_builders.workflows'
2021-11-24 20:34:31,264 | Manifest is not changed for d4fbbd94-b684-4533-9386-944b156f0d9c, running incremental build
2021-11-24 20:34:31,265 | Building codeuri: /home/henrik/code/accelerate-bug/say-hello runtime: nodejs14.x metadata: {} architecture: x86_64 functions: ['SayHelloFunction']
2021-11-24 20:34:31,265 | Building to following folder /home/henrik/code/accelerate-bug/.aws-sam/auto-dependency-layer/SayHelloFunction
2021-11-24 20:34:31,265 | Loading workflow module 'aws_lambda_builders.workflows'
2021-11-24 20:34:31,267 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2021-11-24 20:34:31,268 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-11-24 20:34:31,269 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2021-11-24 20:34:31,269 | Registering workflow 'GoDepBuilder' with capability 'Capability(language='go', dependency_manager='dep', application_framework=None)'
2021-11-24 20:34:31,271 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2021-11-24 20:34:31,273 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2021-11-24 20:34:31,274 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2021-11-24 20:34:31,277 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2021-11-24 20:34:31,279 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2021-11-24 20:34:31,280 | Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-11-24 20:34:31,280 | Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2021-11-24 20:34:31,280 | download_dependencies is False and dependencies_dir is None. Copying the source files into the artifacts directory. 
2021-11-24 20:34:31,280 | download_dependencies is False and dependencies_dir is None. Copying the source files into the artifacts directory. 
2021-11-24 20:34:31,281 | Running workflow 'NodejsNpmBuilder'
2021-11-24 20:34:31,282 | Running NodejsNpmBuilder:NpmPack
2021-11-24 20:34:31,282 | NODEJS packaging file:/home/henrik/code/accelerate-bug/shared to /tmp/tmpipo4gchb
2021-11-24 20:34:31,282 | executing NPM: ['npm', 'pack', '-q', 'file:/home/henrik/code/accelerate-bug/shared']
2021-11-24 20:34:31,282 | Running workflow 'NodejsNpmBuilder'
2021-11-24 20:34:31,285 | Running NodejsNpmBuilder:NpmPack
2021-11-24 20:34:31,285 | NODEJS packaging file:/home/henrik/code/accelerate-bug/say-hello to /tmp/tmp_7gtln35
2021-11-24 20:34:31,286 | executing NPM: ['npm', 'pack', '-q', 'file:/home/henrik/code/accelerate-bug/say-hello']
2021-11-24 20:34:31,555 | NODEJS packed to say-hello-1.0.0.tgz
2021-11-24 20:34:31,555 | NODEJS extracting to /tmp/tmp_7gtln35/unpacked
2021-11-24 20:34:31,556 | NODEJS packed to shared-1.0.0.tgz
2021-11-24 20:34:31,556 | NODEJS extracting to /tmp/tmpipo4gchb/unpacked
2021-11-24 20:34:31,557 | NodejsNpmBuilder:NpmPack succeeded
2021-11-24 20:34:31,557 | Running NodejsNpmBuilder:CopyNpmrc
2021-11-24 20:34:31,557 | NodejsNpmBuilder:CopyNpmrc succeeded
2021-11-24 20:34:31,558 | Running NodejsNpmBuilder:CopySource
2021-11-24 20:34:31,558 | NodejsNpmBuilder:NpmPack succeeded
2021-11-24 20:34:31,558 | Running NodejsNpmBuilder:CopyNpmrc
2021-11-24 20:34:31,558 | NodejsNpmBuilder:CopyNpmrc succeeded
2021-11-24 20:34:31,558 | Running NodejsNpmBuilder:CopySource
2021-11-24 20:34:31,559 | NodejsNpmBuilder:CopySource succeeded
2021-11-24 20:34:31,559 | Running NodejsNpmBuilder:CleanUpNpmrc
2021-11-24 20:34:31,559 | NodejsNpmBuilder:CleanUpNpmrc succeeded
2021-11-24 20:34:31,560 | NodejsNpmBuilder:CopySource succeeded
2021-11-24 20:34:31,560 | Running NodejsNpmBuilder:CleanUpNpmrc
2021-11-24 20:34:31,560 | NodejsNpmBuilder:CleanUpNpmrc succeeded
2021-11-24 20:34:31,562 | Async execution completed
2021-11-24 20:34:31,565 | Auto creating dependency layer for each function resource into a nested stack
2021-11-24 20:34:31,565 | No Parameters detected in the template
2021-11-24 20:34:31,580 | 3 resources found in the stack accelerate-bug
2021-11-24 20:34:31,580 | No Parameters detected in the template
2021-11-24 20:34:31,595 | No Parameters detected in the template
2021-11-24 20:34:31,610 | --base-dir is not presented, adjusting uri .aws-sam/auto-dependency-layer/SharedLayer relative to /home/henrik/code/accelerate-bug/template.yaml
2021-11-24 20:34:31,610 | Found Serverless function with name='SayHelloFunction' and CodeUri='.aws-sam/auto-dependency-layer/SayHelloFunction'
2021-11-24 20:34:31,610 | --base-dir is not presented, adjusting uri .aws-sam/auto-dependency-layer/SayHelloFunction relative to /home/henrik/code/accelerate-bug/template.yaml

Build Succeeded

Built Artifacts  : .aws-sam/auto-dependency-layer
Built Template   : .aws-sam/auto-dependency-layer/template.yaml
```

The output that follows the above shows the cloudformation update.

### Expected result:
I would expect it to not delete `node_modules` such that the Lambda function still works.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Fedora 33
2. `sam --version`: `SAM CLI, version 1.36.0`
3. AWS region: eu-west-1

**Comment by mndeveci** [comment]
Thanks for reporting this issue @cshenrik. What happens if you try to run `sam sync --watch --stack-name <STACK_NAME> --no-dependency-layer` at step 2 and 5, do you still see this issue?

**Comment by cshenrik** [comment]
@mndeveci: Yes, the same thing happens with `--no-dependency-layer`.

**Comment by mndeveci** [comment]
Thanks for the confirmation, we will include this in our backlog and start working on it.

**Comment by mndeveci** [comment]
I tried to re-produce this issue on my local machine by cloning your repository and running `sam sync --watch --stack-name {stack-name}`. First time I tried to invoke function I got an error that `@middy/core` library can't be found. When I checked the `package.json` file it was missing as a dependency there. I updated `package.json` to this;
```
{
  "name": "say-hello",
  "version": "1.0.0",
  "dependencies": {
    "@middy/core": "^2.5.3"
  }
}

```

Then I ran `sam sync --watch --stack-name {stack-name}` and tried to invoke function, which is succeeded. I killed the process and re-run it, after sync is completed I tried to invoke function again and it is succeeded.

Can you help me if I am missing any steps that you provided earlier? 

Thanks!

**Comment by cshenrik** [comment]
@mndeveci It makes sense to me that it works if you add the dependency to the `say-hello` function directly. I only have the middy dependency in the Lambda layer in the `shared` folder.

I'm trying to do what Eric Johnson wrote in his blog entry: https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/. In his approach the dependencies only seem to exist in the layer. If I add the dependency to the function itself, wouldn't I lose the benefits of having it in the layer?

**Comment by mndeveci** [comment]
@cshenrik my bad, I missed the layer definition in your original message. 

I was able to track down the issue, it is only affecting the layer build for `sam sync`. We are going to address that with a PR soon.

Thanks for reporting the issue!

**Comment by AndreyBespamyatnov** [comment]
Hello, I still can reproduce that issue, does anyone know any workarounds for that? thank you

**Comment by yudao** [comment]
I have the same behaviour than @AndreyBespamyatnov.
In waiting the next release I've installed my layer packages into my functions.
But I've noticed that the `node_modules` disappear too on the function if I play with the `layers` in the CloudFormation template.

First time all is well built and functional. Now I add/delete/associate/dissociate layers (even if I do not use them in my function), `node_modules` is deleted on the directory of my function into the `auto-dependency-layer` repository.

**Comment by moelasmar** [comment]
The PR is released in SAM CLI V 1.37.0

**Comment by Saeger** [comment]
Hi,

I am afraid to say that I still face the same issue as OP @cshenrik  even though I am using the latest and greatest (1.37.0)

`Response
{
  "errorType": "Error",
  "errorMessage": "Cannot find package 'axios' imported from /var/task/src/handlers/scheduled-management-report.js",
  "trace": [
    "Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'axios' imported from /var/task/src/handlers/scheduled-management-report.js",
    "    at new NodeError (internal/errors.js:322:7)",
    "    at packageResolve (internal/modules/esm/resolve.js:687:9)",
    "    at moduleResolve (internal/modules/esm/resolve.js:728:18)",
    "    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)",
    "    at Loader.resolve (internal/modules/esm/loader.js:89:40)",
    "    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)",
    "    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)",
    "    at link (internal/modules/esm/module_job.js:75:36)",
    "    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)",
    "    at /var/runtime/deasync.js:23:15"
  ]
}`

`Stack update succeeded. Sync infra completed.
Infra sync completed.`

`sam --version
SAM CLI, version 1.37.0`

`aws --version
aws-cli/2.4.8 Python/3.9.9 Darwin/21.1.0 source/x86_64 prompt/off`

**Comment by mndeveci** [comment]
Hi @Saeger ,

I tested the example above (https://github.com/cshenrik/accelerate-bug) and ran `sam sync` 2 times back to back, but I can confirm that `node_modules` folder still exist and function code successfully synced.

Can you try removing `.aws-sam` folder and retrying? If that doesn't solve the issue, can you list steps to reproduce it so that we can take a look at it more closely.

Thanks

**Comment by Saeger** [comment]
Right @mndeveci ! Deleting `.aws-sam` folder did the trick! Thanks :-)
