### ISSUE TITLE
[sam-beta-cdk] local start-api fails to invoke a lambda defined in another stack

### ISSUE THREAD

**Issue by toby-lego** [aws/aws-sam-cli#3521]
### Description:

I have my lambda functions and my API Gateway (v2) definition in two different stacks inside the same CDK project. When running `sam-beta-cdk local start-api` it starts up correctly but cannot find the name of the lambda function so fails to invoke the lambda at runtime.

### Steps to reproduce:
A set up similar to this will deploy correctly with CDK, and will start up with SAM local-api but the route will be registered without a name.

<details><summary>Example cdk stack</summary>

```typescript
import * as cdk from "@aws-cdk/core";
import * as lambda from "@aws-cdk/aws-lambda";
import * as apigwv2 from "@aws-cdk/aws-apigatewayv2";
import { LambdaProxyIntegration } from "@aws-cdk/aws-apigatewayv2-integrations";

// stack defining part of the backend functionality, grouping related resources
export class FunctionStack extends cdk.Stack {
  endpoint: lambda.Function;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.endpoint = new lambda.Function(this, "endpoint", {
      functionName: "endpoint",
      runtime: lambda.Runtime.NODEJS_14_X,
      handler: "index.handler",
      code: lambda.Code.fromAsset("./src/"),
    });
  }
}

// stack defining the api gateway with access policies etc
export class ApiGatewayStack extends cdk.Stack {
  private api: apigwv2.HttpApi;

  constructor(scope: cdk.Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    this.api = new apigwv2.HttpApi(this, "backend", {
      apiName: "backend"
    });
  }

  public AddRoute(
    path: string,
    methods: apigwv2.HttpMethod[],
    handler: lambda.IFunction
  ): void {
    this.api.addRoutes({
      integration: new LambdaProxyIntegration({
        handler,
      }),
      path,
      methods,
    });
  }
}

// setup in bin folder and all route declarations
const app = new cdk.App();
const backendServices = new FunctionStack(app, "FunctionStack");
const apiGateway = new ApiGatewayStack(app, "GatewayStack");

apiGateway.AddRoute("/invoke", [apigwv2.HttpMethod.POST], backendServices.endpoint);
```

</details>

### Observed result:
The CDK set up creates exports for the name of the lambda which aren't imported correctly in the API stack, the lambda is found but without the name it can't be invoked.

```
2021-12-07 16:39:19,916 | Found Lambda function with name='endpointE7B9679B' and CodeUri='.../src'
...
2021-12-07 16:39:19,937 | Unable to resolve property FunctionName: OrderedDict([('Fn::ImportValue', 'FunctionStack:ExportsOutputFnGetAttendpointE7B9679BArnABD04043')]). Leaving as is.
2021-12-07 16:39:19,937 | Unable to resolve property IntegrationUri: OrderedDict([('Fn::ImportValue', 'FunctionStack:ExportsOutputFnGetAttendpointE7B9679BArnABD04043')]). Leaving as is.
...
2021-12-07 16:39:20,033 | 1 APIs found in the template
2021-12-07 16:39:20,041 | Mounting None at http://127.0.0.1:3000/invoke [POST]
...
2021-12-07 16:39:20  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2021-12-07 16:44:50,576 | Constructed String representation of Event Version 2.0 to invoke Lambda. Event: {"version": "2.0", "routeKey": "POST /invoke", "rawPath": "/invoke", "rawQueryString": "", "cookies": [], "headers": {"Host": "127.0.0.1:3000", "User-Agent": "curl/7.77.0", "Accept": "*/*", "X-Forwarded-Proto": "http", "X-Forwarded-Port": "3000"}, "queryStringParameters": {}, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "http": {"method": "POST", "path": "/invoke", "protocol": "HTTP/1.1", "sourceIp": "127.0.0.1", "userAgent": "Custom User Agent String"}, "requestId": "cdc1cff4-454c-40e0-a2b7-dcec67a8b35b", "routeKey": "POST /invoke", "stage": "$default"}, "body": "", "pathParameters": {}, "stageVariables": null, "isBase64Encoded": false}
2021-12-07 16:44:50,576 | Exception on /invoke [POST]
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 316, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 107, in invoke
    function = self.provider.get(function_identifier)
  File "/usr/local/Cellar/aws-sam-cli-beta-cdk/202108311500/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 74, in get
    raise ValueError("Function name is required")
ValueError: Function name is required
2021-12-07 16:44:50 127.0.0.1 - - [07/Dec/2021 16:44:50] "POST /invoke HTTP/1.1" 502 -
```

### Expected result:
The function to be successfully invoked, or at least an error on start up to tell me this isn't supported.

This is where it fails to set the name correctly: https://github.com/aws/aws-sam-cli/blob/develop/samcli/lib/providers/cfn_api_provider.py#L459, the integration_resource.Properties is something like:

```
OrderedDict([('ApiId', 'backendCBA98286'),
             ('IntegrationType', 'AWS_PROXY'),
             ('IntegrationUri',
              OrderedDict([('Fn::ImportValue',
                            'FunctionStack:ExportsOutputFnGetAttendpointE7B9679BArnABD04043')])),
             ('PayloadFormatVersion', '2.0')])
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS
2. `sam --version`: SAM CLI, version 1.29.0.dev202108311500

**Comment by ssenchenko** [comment]
So sorry you encountered a bug! Thanks for reporting the issue, we will be investigating it further.

**Comment by moelasmar** [comment]
sam does not support testing multiple stacks. I tagged this issue as a feature request.

**Comment by jfuss** [comment]
Closing as this issue relates to a beta cli. Please open a new issue if this is still happening with production.
