### ISSUE TITLE
Issue with running SpringBoot Application using AWS Lambda in SAMCLI

### ISSUE THREAD

**Issue by shridha28** [aws/aws-sam-cli#3534]
Hello Team,

I am not able to test springboot application with AWS lambda in my local using SAM CLI, because it generates classes with very long names , which the SAM Cli  is not able to copy to tmp folder, when deploying as a docker container and I get an error as below :

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 157, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 83, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 175, in do_cli
    context.local_lambda_runner.invoke(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 221, in wrapped_func
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 71, in create
    code_dir = self._get_code_dir(function_config.code_abs_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 280, in _get_code_dir
    decompressed_dir: str = _unzip_file(code_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\runtime.py", line 496, in _unzip_file
    unzip(filepath, temp_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\zip.py", line 99, in unzip
    extracted_path = _extract(file_info, output_dir, zip_ref)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\lambdafn\zip.py", line 61, in _extract
    return zip_ref.extract(file_info, output_dir)
  File "zipfile.py", line 1630, in extract
  File "zipfile.py", line 1701, in _extract_member
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<username>\\AppData\\Local\\Temp\\tmphl495n3r\\org\\springframework\\boot\\autoconfigure\\integration\\IntegrationAutoConfiguration$IntegrationRSocketConfiguration$IntegrationRSocketClientConfiguration$RemoteRSocketServerAddressConfigured$TcpAddressConfigured.class'

This issue occurs only in Windows Operating System.

Is there a solution or a fix already available for this, in one of the solutions, it was advised to change the python file, but I am not good at python.

Please help!!
Thanks in advance.

**Comment by awood45** [comment]
Can you share what that other advised solution was? I'm admittedly not super familiar with Spring Boot and what it might be doing here so additional context may be helpful.

**Comment by mndeveci** [comment]
In addition to @awood45 's questions, would this work if you change windows settings to accept file paths over 260 characters?

**Comment by shridha28** [comment]
> Can you share what that other advised solution was? I'm admittedly not super familiar with Spring Boot and what it might be doing here so additional context may be helpful.

Hello @awood45, thanks for your response. SpringBoot generates classes with very long file names, which windows apparently fails to copy into the tmp folder. I fixed the issue by doing some changes in the zip.py as suggested here-> https://github.com/aws/aws-sam-cli/issues/2475. 

I wanted to know if this issue in zip.py is already fixed in any of the SAM Cli versions. 

Many thanks.

**Comment by sriram-mv** [comment]
I'm going to close this issue in favor of https://github.com/aws/aws-sam-cli/issues/4031, it has workarounds on how to make changes such that long file names are accepted on windows.

**Comment by DHAPARK** [comment]
This is a basic setup that allows you to run and test the server on Windows and Mac locally. Instead of testing in a local environment using Docker, follow the guide I've written to set up your development environment. It will be more convenient.

https://github.com/DHAPARK/ServerLessArchi
