### ISSUE TITLE
Permission problems when doing builds in a CI environment

### ISSUE THREAD

**Issue by twasink** [aws/aws-sam-cli#3556]
I'm getting permission errors using the sam build images on my Jenkins server (which itself is run as an ECS task, so it's docker-in-docker, if that makes a difference).

The build executes fine - but after the build process, it gets this error:

```
+ sam build
Building codeuri: /var/jenkins_home/workspace/.../hello_world runtime: python3.8 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
[*] Deploy: sam deploy --guided
        
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 142, in wrapped
    metric = Metric(metric_name)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 309, in __init__
    self._add_common_metric_attributes()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 332, in _add_common_metric_attributes
    self._data["installationId"] = self._gc.installation_id
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 351, in installation_id
    self.set_value(DefaultEntry.INSTALLATION_ID, value)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 273, in set_value
    self._set_value(config_entry, value, is_flag, flush)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 294, in _set_value
    self._write_config()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 324, in _write_config
    self.config_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
  File "/var/lang/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.aws-sam'
script returned exit code 1
```

This doesn't happen when running locally. It looks a lot like it's trying to go to `${HOME}/.aws-sam` - and the Jenkins server, running as it is as a daemon, doesn't have a home directory.

This happens with (at least) the current nodejs12.x, nodejs14.x, python3.8 and python 3.9 images. It does _not_ happen with the older images still up on Docker Hub (tested nodejs12.x and python3.8).

**Comment by hoffa** [comment]
Thanks for reporting this, and for the narrowing down the version.

As sanity check I verified `env` returns similar results on both `public.ecr.aws/sam/build-python3.8:1.33.0` and `public.ecr.aws/sam/build-python3.8:1.34.1`, so that seems fine.

1.34.1 introduced https://github.com/aws/aws-sam-cli/pull/3386, which did touch the code related to `.aws-sam`, but at cursory glance I don't see anything functionally different:

https://github.com/aws/aws-sam-cli/blob/575209e8788d71da357214f13559bf0ad4167946/samcli/cli/global_config.py#L96

https://github.com/aws/aws-sam-cli/blob/575209e8788d71da357214f13559bf0ad4167946/samcli/cli/global_config.py#L323-L324

Looking at the [code for `get_app_dir()`](https://github.com/pallets/click/blob/43e40c05a4b94c6aa497dc7bba62b7d69b7e35ec/src/click/utils.py#L421-L422), it essentially calls [`os.path.expanduser()`](https://docs.python.org/3/library/os.path.html#os.path.expanduser) on `~/.aws-sam`, which seems to replace `~` by `$HOME` or as fallback value in `/etc/passwd`.

Some questions:

1. Are the environment variables passed to the containers identical in both cases? i.e. `env` returns pretty much the same results for both 1.33 and 1.34.
1. Does `public.ecr.aws/sam/build-python3.8:1.33.0` create the `.aws-sam` directory at the root? I would assume if `$HOME` is missing, the behavior would be similar for both versions, and `self.config_dir` would correspond to the same path.

**Comment by twasink** [comment]
I recently had to come back and re-investigate this, as I needed to upgrade to support Node 18. The issue was definitely still occurring. I was able to resolve it by providing a HOME environment variable in the override – not `HOME=/root` as suggested though (the CI environment was running the docker container under the same UID as the Jenkins process, so /root wasn't writable), but `HOME=/var/tmp` worked.

It's still a regression from earlier behaviour, and an inbuilt assumption that the UID is root, but at least there's a workaround.
