### ISSUE TITLE
aws sam local invoke: The security token included in the request is expired

### ISSUE THREAD

**Issue by nmarquesantos** [aws/aws-sam-cli#3558]
### Description:
I am unable to run the example successfully on my local environment.

### Steps to reproduce:
1. sam init
2. choose option 1 (nodejs14)
3. Choose option **8 - Quick Start: Web Backend**
4. Run sam build in the folder
5. run `sam local invoke putItemFunction --event events/event-post-item.json` as stated in README.md

### Observed result:
 I'm met with the following exception stacktrace:
`{"errorType":"ExpiredTokenException","errorMessage":"The security token included in the request is expired","code":"ExpiredTokenException","message":"The security token included in the request is expired","time":"2021-12-31T22:34:14.650Z","requestId":"C7ABNNSISCR0N7VKIEDBBBP923VV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":true,"stack":["ExpiredTokenException: The security token included in the request is expired","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}`

### Expected result:
Expected the request to be successful

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur 11.4
2. `sam --version`: SAM CLI, version 1.36.0
3. AWS region: N/A (local machine)

**Comment by hoffa** [comment]
You need to `sam deploy` first (typically `sam deploy --guided` the first time) so that the resources exist in AWS. `sam local` only runs the specified functions locally; other resources they interact with are actual resources in your AWS account.

**Comment by hoffa** [comment]
So I tried this:

```bash
sam init --name sam-app --runtime nodejs14.x --dependency-manager npm --app-template quick-start-web
cd sam-app
sam build
sam deploy --guided
```

If you now try to run:

```bash
sam local invoke putItemFunction --event events/event-post-item.json
```

It'll fail with:

```text
2022-01-01T20:31:27.470Z	4ed8d93e-433e-4876-b4c2-65d105ab7ac6	ERROR	Invoke Error 	{"errorType":"ResourceNotFoundException","errorMessage":"Requested resource not found","code":"ResourceNotFoundException","message":"Requested resource not found","time":"2022-01-01T20:31:27.468Z","requestId":"AOCITAT7FEU03KCR7K8CDRKVNNVV4KQNSO5AEMVJF66Q9ASUAAJG","statusCode":400,"retryable":false,"retryDelay":41.32157284481265,"stack":["ResourceNotFoundException: Requested resource not found","    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:52:27)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:686:14)","    at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:688:12)","    at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"]}
```

The reason is that the `SAMPLE_TABLE` environment variable resolves to `SampleTable` locally (at glance potentially related to https://github.com/aws/aws-sam-cli/issues/1604), while the actual table name is something like `sam-app-SampleTable-F00BA4`, and so `docClient.put()` fails.

There's at least two ways to resolve this:

1. Replace `<TABLE-NAME>` in `env.json` by the deployed table's name, and run `sam local invoke putItemFunction --event events/event-post-item.json --env-vars env.json`.
1. Set [`TableName`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-simpletable.html#sam-simpletable-tablename) to `SampleTable`.

The README could definitely be a little clearer on the latter aspect.

Note that if you want to run a DynamoDB table locally, you could try this approach by @dmitriierkineroad: https://github.com/aws/aws-sam-cli/issues/3539#issuecomment-998436502.

**Comment by nmarquesantos** [comment]
thanks @hoffa 

yes i had to dig around and your steps helped.

docs could definitely be a little clearer for newcomers to sam especially

thanks mate!

**Comment by mildaniel** [comment]
Closing as it seems this issue is resolved. Please re-open if necessary.
