### ISSUE TITLE
Unable to create dynamo table with tags

### ISSUE THREAD

**Issue by alexgurman** [aws/aws-sam-cli#3573]
### Description:
Traying to create dynamo table using AWS::Serverless::SimpleTable, but getting an error if I specify any tags 

### Steps to reproduce:
Run sam build on the template

### Observed result:
PS C:\Work\Issues\AWS - SAM - dynamo table> sam build --debug
2022-01-07 12:32:12,548 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-07 12:32:12,548 | Using config file: samconfig.toml, config environment: default
2022-01-07 12:32:12,549 | Expand command line arguments to:
2022-01-07 12:32:12,549 | --template_file=C:\Work\Issues\AWS - SAM - dynamo table\template.yaml --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2022-01-07 12:32:13,015 | 'build' command is called
2022-01-07 12:32:13,015 | Collected default values for parameters: {'Stage': 'lcl', 'OCTOEnv': 'DEV', 'TerraformTableName': 'terraform-lock-nmgr', 'AwsRegion': 'us-east-1'}
2022-01-07 12:32:13,031 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'a5721518-a4a2-4333-98fe-b32aa4936575', 'installationId': '2bcffb07-fa0b-4ced-a5d9-096faedc8c99', 'sessionId': '148f4db1-85c8-4eaa-9341-3358208b9bf9', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.37.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 483, 'exitReason': 'InvalidSamDocumentException', 'exitCode': 255}}]}
2022-01-07 12:32:13,574 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\samlib\wrapper.py", line 68, in run_plugins
    parser.parse(template_copy, all_plugins)  # parse() will run all configured plugins
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\samlib\wrapper.py", line 102, in parse
    raise InvalidDocumentException(document_errors)
samtranslator.model.exceptions.InvalidDocumentException: [InvalidResourceException('TerraformDynamoTable', "Type of property 'Tags' is invalid.")]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 174, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 231, in do_cli
    with BuildContext(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 106, in __enter__
    self.set_up()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 112, in set_up
    self._stacks, remote_stack_full_paths = SamLocalStackProvider.get_stacks(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\providers\sam_stack_provider.py", line 242, in get_stacks
    current = SamLocalStackProvider(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\providers\sam_stack_provider.py", line 51, in __init__
    self._template_dict = self.get_template(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\providers\sam_base_provider.py", line 189, in get_template
    template_dict = SamTranslatorWrapper(template_dict, parameter_values=parameters_values).run_plugins()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\samlib\wrapper.py", line 70, in run_plugins
    raise InvalidSamDocumentException(
samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('TerraformDynamoTable', "Type of property 'Tags' is invalid.")] ('TerraformDynamoTable', "Type of property 'Tags' is invalid.")
PS C:\Work\Issues\AWS - SAM - dynamo table>

### Expected result:
Expected to see dynamo table created

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: us-east-1

`Add --debug fla
[Log.txt](https://github.com/aws/aws-sam-cli/files/7830662/Log.txt)
g to command you are running`
[cloudformation-terraformresources.txt](https://github.com/aws/aws-sam-cli/files/7830660/cloudformation-terraformresources.txt)

**Comment by mildaniel** [comment]
Hey @alexgurman, thanks for bringing this up. Are you able to provide the resource snippet so that we can try reproducing this issue?

**Comment by alexgurman** [comment]
all good, it's a duplicate
