### ISSUE TITLE
sam init with version 1.37.0 throws TypeError on Windows

### ISSUE THREAD

**Issue by VerdantFox** [aws/aws-sam-cli#3576]
### Description:
When running `sam init` (option 1) with SAM CLI installed from Windows MSI installer for SAM CLI version 1.37 a python TypeError is thrown. After uninstalling the version `1.37.0` and installing version `1.36.0`, all works as expected, no errors.

### Steps to reproduce:
1. Install SAM CLI version `1.37.0` with MSI installer.
2. Run `sam init`, selecting option 1

### Observed result:

```bash
$ sam init --debug
2022-01-10 12:54:54,717 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-10 12:54:54,717 | Using config file: samconfig.toml, config environment: default
2022-01-10 12:54:54,718 | Expand command line arguments to:
2022-01-10 12:54:54,718 | --package_type=Zip --output_dir=.
Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1
2022-01-10 12:55:00,591 |
Cloning from https://github.com/aws/aws-sam-cli-app-templates
2022-01-10 12:55:06,547 | Clone error, attempting to use an old clone from a previous run
2022-01-10 12:55:06,547 | Template is not provided in context, skip adding project type metric
2022-01-10 12:55:06,548 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '142afab3-240c-47b7-a404-22a1f3b7ba36', 'installationId': '2cf89870-a5d3-4ca4-b2ae-2c9f443eb172', 'sessionId': '5b0bef55-80ca-4cf0-adac-225f4cda50ad', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.37.0', 'awsProfileProvided': False, 
'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 11830, 'exitReason': 'TypeError', 'exitCode': 255}}]}
2022-01-10 12:55:06,835 | Telemetry response: 200
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 113, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 238, in cli 
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\__init__.py", line 323, in do_cli
    do_interactive(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 53, in do_interactive
    generate_application(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 84, in generate_application
    _generate_from_use_case(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\interactive_init_flow.py", line 133, in _generate_from_use_case
    preprocessed_options = templates.get_preprocessed_manifest(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 169, in get_preprocessed_manifest
    manifest_path = self.get_manifest_path()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\init\init_templates.py", line 127, in get_manifest_path
    return Path(self._git_repo.local_path, self.manifest_file_name)
  File "pathlib.py", line 1041, in __new__
  File "pathlib.py", line 682, in _from_parts
  File "pathlib.py", line 666, in _parse_args
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Expected result:
A `sam init` without thrown error. Again, note, after uninstalling version `1.37.0` and installing version `1.36.0` the `sam init` completes without any errors thrown.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by zlangner** [comment]
I'm experiencing the exact same problem with version 1.37.0. I'm also on Windows 10 but AWS region us-east-1. Reverting to 1.36.0 seems to be a good work around for now.

**Comment by vacuela** [comment]
I'm experiencing the exact same problem with version 1.37.0

**Comment by mildaniel** [comment]
Thanks for bringing this to our attention. We will look into this issue.

**Comment by bardoitch** [comment]
Hi,
Stuck in the same problem.
How can i revert version?

**Comment by mims92** [comment]
Versions below doesn't work either.

**Comment by Bhagavan13** [comment]
> I'm experiencing the exact same problem with version 1.37.0 Back to 1.36.0 works

Could you please tell me how to rollback to the 1.36.0 version

**Comment by ZAKGUN12** [comment]
Hello @Bhagavan13  ;
 
Just remove AWS SAM 1.37 from your system. And then you will download the old version from belove link. 

https://github.com/aws/aws-sam-cli/releases/tag/v1.36.0

**Comment by jagchat** [comment]
Experiencing same problem.

**Comment by hajali-amine** [comment]
Hello, I experienced the same issue with version 1.37.0.
When I reverted back to version 1.36.0 I was able to use `sam init` (Thanks @zlangner 😄)

I had the problem on Windows 11.
I uninstalled Sam 1.37 as mentioned in the [documentation](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-windows.html):
![image](https://user-images.githubusercontent.com/56449150/154342144-b2709a12-1fc7-453b-adb1-a17d289eba60.png)

And then installed the `.msi` from the link that @ZAKGUN12 provided 😄

**Comment by hajali-amine** [comment]
Tested the v1.38.0 and it works! 😄

**Comment by abecks** [comment]
Seeing this on 1.38.1 in the GitHub Actions container:

```
Invoking main.handler (nodejs14.x)
Exception on / [GET]
Traceback (most recent call last):
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 357, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 230, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 178, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 396, in create
    self._observer.watch(function_config)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/lib/utils/file_observer.py", line 203, in watch
    self._observers[function_config.packagetype].watch(resource)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/lib/utils/file_observer.py", line 351, in watch
    self._single_file_observer.watch(resource, self._group)
  File "/home/runner/work/_temp/setup-sam-i5KOgV/.venv/lib/python3.8/site-packages/samcli/lib/utils/file_observer.py", line 475, in watch
    path_obj = Path(resource)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rushabh-ufo** [comment]
I was facing this issue as my python version (3.11.3) and SAM CLI version (1.37.0).
I updated the SAM CLI (1.85.0) and it works well
