### ISSUE TITLE
Local layers are broken using ESM

### ISSUE THREAD

**Issue by iRoachie** [aws/aws-sam-cli#3600]
### Description:

Sam allows sharing modules using local lambda layers for nodejs by use of the `AWS::Serverless::LayerVersion` resource. 

When using the [newly released `.mjs`](https://aws.amazon.com/about-aws/whats-new/2022/01/aws-lambda-es-modules-top-level-await-node-js-14/) as your lambda handler, the handler fails to find the module in the layer.

### Steps to reproduce:

I've provided a repo with commonjs and esm versions where the bug can be observed - https://github.com/iRoachie/aws-sam-esm-layers-bug.

### Observed result:

```
sam local invoke ESMFunction --debug
2022-01-25 13:47:00,283 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-25 13:47:00,283 | Using config file: samconfig.toml, config environment: default
2022-01-25 13:47:00,283 | Expand command line arguments to:
2022-01-25 13:47:00,283 | --template_file=/Users/kyleroach/Desktop/layers-bug/template.yaml --function_logical_id=ESMFunction --no_event --layer_cache_basedir=/Users/kyleroach/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2022-01-25 13:47:00,283 | local invoke command is called
2022-01-25 13:47:00,286 | No Parameters detected in the template
2022-01-25 13:47:00,295 | There is no customer defined id or cdk path defined for resource NanoLayer, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,295 | There is no customer defined id or cdk path defined for resource CJSFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,295 | There is no customer defined id or cdk path defined for resource ESMFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,295 | 3 stacks found in the template
2022-01-25 13:47:00,295 | No Parameters detected in the template
2022-01-25 13:47:00,301 | There is no customer defined id or cdk path defined for resource NanoLayer, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,301 | There is no customer defined id or cdk path defined for resource CJSFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,301 | There is no customer defined id or cdk path defined for resource ESMFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,301 | 3 resources found in the stack 
2022-01-25 13:47:00,301 | No Parameters detected in the template
2022-01-25 13:47:00,308 | There is no customer defined id or cdk path defined for resource NanoLayer, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,308 | There is no customer defined id or cdk path defined for resource CJSFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,308 | There is no customer defined id or cdk path defined for resource ESMFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,308 | No Parameters detected in the template
2022-01-25 13:47:00,314 | There is no customer defined id or cdk path defined for resource NanoLayer, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,314 | There is no customer defined id or cdk path defined for resource CJSFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,314 | There is no customer defined id or cdk path defined for resource ESMFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,314 | --base-dir is not presented, adjusting uri ./nanoid relative to /Users/kyleroach/Desktop/layers-bug/template.yaml
2022-01-25 13:47:00,314 | Found Serverless function with name='CJSFunction' and CodeUri='hello-world/'
2022-01-25 13:47:00,314 | --base-dir is not presented, adjusting uri hello-world/ relative to /Users/kyleroach/Desktop/layers-bug/template.yaml
2022-01-25 13:47:00,314 | No Parameters detected in the template
2022-01-25 13:47:00,319 | There is no customer defined id or cdk path defined for resource NanoLayer, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,320 | There is no customer defined id or cdk path defined for resource CJSFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,320 | There is no customer defined id or cdk path defined for resource ESMFunction, so we will use the resource logical id as the resource id
2022-01-25 13:47:00,320 | --base-dir is not presented, adjusting uri ./nanoid relative to /Users/kyleroach/Desktop/layers-bug/template.yaml
2022-01-25 13:47:00,320 | Found Serverless function with name='ESMFunction' and CodeUri='hello-world/'
2022-01-25 13:47:00,320 | --base-dir is not presented, adjusting uri hello-world/ relative to /Users/kyleroach/Desktop/layers-bug/template.yaml
2022-01-25 13:47:00,356 | Found one Lambda function with name 'ESMFunction'
2022-01-25 13:47:00,356 | Invoking esm.lambdaHandler (nodejs14.x)
2022-01-25 13:47:00,356 | No environment variables found for function 'ESMFunction'
2022-01-25 13:47:00,356 | Environment variables overrides data is standard format
2022-01-25 13:47:00,356 | Loading AWS credentials from session with profile 'None'
2022-01-25 13:47:02,367 | Resolving code path. Cwd=/Users/kyleroach/Desktop/layers-bug, CodeUri=/Users/kyleroach/Desktop/layers-bug/hello-world
2022-01-25 13:47:02,367 | Resolved absolute path to code is /Users/kyleroach/Desktop/layers-bug/hello-world
2022-01-25 13:47:02,368 | Code /Users/kyleroach/Desktop/layers-bug/hello-world is not a zip/jar file
2022-01-25 13:47:02,368 | Code /Users/kyleroach/Desktop/layers-bug/nanoid is not a zip/jar file
2022-01-25 13:47:02,368 | NanoLayer is a local Layer in the template
2022-01-25 13:47:02,368 | Resolving code path. Cwd=/Users/kyleroach/Desktop/layers-bug, CodeUri=/Users/kyleroach/Desktop/layers-bug/nanoid
Building image........................
2022-01-25 13:47:05,347 | Skip pulling image and use local one: samcli/lambda:nodejs14.x-x86_64-77de677c4b0722c6507a33371.

2022-01-25 13:47:05,347 | Mounting /Users/kyleroach/Desktop/layers-bug/hello-world as /var/task:ro,delegated inside runtime container
2022-01-25 13:47:05,675 | Starting a timer for 3 seconds for function 'ESMFunction'
START RequestId: f49ab333-46c0-4b67-8631-883508d16385 Version: $LATEST
2022-01-25T17:47:06.866Z        undefined       ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"Cannot find package 'nanoid' imported from /var/task/esm.mjs\nDid you mean to import nanoid/index.cjs?","code":"ERR_MODULE_NOT_FOUND","stack":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'nanoid' imported from /var/task/esm.mjs","Did you mean to import nanoid/index.cjs?","    at new NodeError (internal/errors.js:322:7)","    at packageResolve (internal/modules/esm/resolve.js:687:9)","    at moduleResolve (internal/modules/esm/resolve.js:728:18)","    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)","    at Loader.resolve (internal/modules/esm/loader.js:89:40)","    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)","    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)","    at link (internal/modules/esm/module_job.js:75:36)","    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)","    at /var/runtime/deasync.js:23:15"]}
25 Jan 2022 17:47:06,956 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2022-01-25T17:47:08.047Z        undefined       ERROR   Uncaught Exception      {"errorType":"Error","errorMessage":"Cannot find package 'nanoid' imported from /var/task/esm.mjs\nDid you mean to import nanoid/index.cjs?","code":"ERR_MODULE_NOT_FOUND","stack":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'nanoid' imported from /var/task/esm.mjs","Did you mean to import nanoid/index.cjs?","    at new NodeError (internal/errors.js:322:7)","    at packageResolve (internal/modules/esm/resolve.js:687:9)","    at moduleResolve (internal/modules/esm/resolve.js:728:18)","    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)","    at Loader.resolve (internal/modules/esm/loader.js:89:40)","    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)","    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)","    at link (internal/modules/esm/module_job.js:75:36)","    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)","    at /var/runtime/deasync.js:23:15"]}
END RequestId: 6a7cad51-e138-4fd5-9e25-d2f6c7274ee5
REPORT RequestId: 6a7cad51-e138-4fd5-9e25-d2f6c7274ee5  Init Duration: 1.20 ms  Duration: 2323.00 ms    Billed Duration: 2323 ms Memory Size: 128 MB     Max Memory Used: 128 MB
{"errorType":"Error","errorMessage":"Cannot find package 'nanoid' imported from /var/task/esm.mjs\nDid you mean to import nanoid/index.cjs?","trace":["Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'nanoid' imported from /var/task/esm.mjs","Did you mean to import nanoid/index.cjs?","    at new NodeError (internal/errors.js:322:7)","    at packageResolve (internal/modules/esm/resolve.js:687:9)","    at moduleResolve (internal/modules/esm/resolve.js:728:18)","    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)","    at Loader.resolve (internal/modules/esm/loader.js:89:40)","    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)","    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:76:40)","    at link (internal/modules/esm/module_job.js:75:36)","    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:60:5)","    at /var/runtime/deasync.js:23:15"]}2022-01-25 13:47:08,263 | Cleaning all decompressed code dirs
2022-01-25 13:47:08,265 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '01c73b4f-3501-4df4-bd4a-e10558509957', 'installationId': '44eb74d8-8e21-489c-af32-453aaec4c2fb', 'sessionId': '2f29d49f-120d-4086-8417-29a098eeaf3b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.37.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 7981, 'exitReason': 'success', 'exitCode': 0}}]}
2022-01-25 13:47:08,983 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2022-01-25 13:47:08,984 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-25 13:47:08,984 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': 'bd0783d9-c0ff-4187-bfaf-5254f368188e', 'installationId': '44eb74d8-8e21-489c-af32-453aaec4c2fb', 'sessionId': '2f29d49f-120d-4086-8417-29a098eeaf3b', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.37.0', 'runtimes': ['nodejs14.x']}}]}
2022-01-25 13:47:09,536 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:

The function should execute successfully and return `hello <random-string>`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS 12.1
2. `sam --version`: 1.37.0
3. AWS region: us-east-2

`Add --debug flag to command you are running`

**Comment by qingchm** [comment]
Hi there @iRoachie thanks for the report! I was able to reproduce the issue using your repo, The ES invoke gave me "Cannot find package 'nanoid'" error as well. I will pull this issue into our tasks for further investigation! Thanks for your input and sample!

**Comment by davidprovan** [comment]
Any update on this one?

**Comment by prcongithub** [comment]
+1

**Comment by roger-marley-lrn** [comment]
+1

**Comment by moelasmar** [comment]
The root cause of this issue is Lambda with ESM does not support dependencies in layers right now. 
You can check [this workaround](https://github.com/vibe/aws-esm-modules-layer-support) that suggests a way to resolve this issue in AWS Lambda.
This approach can be also used in `sam local` commands. I confirmed that it solved your issue. These are the commands that I executed:
```
$ git clone https://github.com/iRoachie/aws-sam-esm-layers-bug.git
$ cd aws-sam-esm-layers-bug/nanoid/nodejs
$ npm install 
$ cd ../../hello-world/
$ ln -s /opt/nodejs/node_modules node_modules
$ cd ..
$ sam local invoke ESMFunction
Invoking esm.lambdaHandler (nodejs14.x)
NanoLayer is a local Layer in the template
Building image........................
Skip pulling image and use local one: samcli/lambda:nodejs14.x-x86_64-77de677c4b0722c6507a33371.

Mounting /Volumes/workplace/aws-sam-esm-layers-bug/hello-world as /var/task:ro,delegated inside runtime container
START RequestId: 02d7c16a-4a23-4423-8b6b-0fe33db717fb Version: $LATEST
END RequestId: 02d7c16a-4a23-4423-8b6b-0fe33db717fb
REPORT RequestId: 02d7c16a-4a23-4423-8b6b-0fe33db717fb	Init Duration: 0.08 ms	Duration: 194.68 ms	Billed Duration: 195 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
"hello KwFc8i12FDdh3ruFO0rh4"

$ sam local invoke ESMFunction

Invoking cjs.lambdaHandler (nodejs14.x)
NanoLayer is a local Layer in the template
Building image........................
Skip pulling image and use local one: samcli/lambda:nodejs14.x-x86_64-77de677c4b0722c6507a33371.

Mounting /Volumes/workplace/aws-sam-esm-layers-bug/hello-world as /var/task:ro,delegated inside runtime container
START RequestId: c5d5777d-041d-495f-ad5e-433ad38cadd1 Version: $LATEST
END RequestId: c5d5777d-041d-495f-ad5e-433ad38cadd1
REPORT RequestId: c5d5777d-041d-495f-ad5e-433ad38cadd1	Init Duration: 0.15 ms	Duration: 183.89 ms	Billed Duration: 184 ms	Memory Size: 128 MB	Max Memory Used: 128 MB	
"hello BUnU6R1q13NJ06-0z0uoa"
```

**Comment by moelasmar** [comment]
Please let me know if this workaround helps you to resolve your issue.

**Comment by iRoachie** [comment]
Would be awesome if sam-cli could do this automatically. It already knows the local path via `ContentUri` on the layer.

**Comment by moelasmar** [comment]
This solution is a workaround till Lambda fix this issue from their side, so I do not think we should provide this workaround to  SAM CLI. Anyway I will discuss with the team if we shall provide this workaround in SAM CLI.
