### ISSUE TITLE
SAM 1.37.0 - running sam logs causes ValueError: Required parameter name not set exception

### ISSUE THREAD

**Issue by andyeff** [aws/aws-sam-cli#3604]
### Description:

When using SAM 1.37.0, and attempting to check lambda cloudwatch logs using `sam logs`, a ValueError "Required parameter name not set" exception is thrown. The same command in SAM 1.33.0 works OK

### Steps to reproduce:

Run `sam logs -n <name of lambda function>`

### Observed result:

```bash
~ sam.137 logs -n my-example-lambda --debug
2022-01-26 16:50:57,498 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-26 16:50:57,498 | Using config file: samconfig.toml, config environment: default
2022-01-26 16:50:57,498 | Expand command line arguments to:
2022-01-26 16:50:57,498 | --name=('my-example-lambda',) --start_time=10m ago
You can now use 'sam logs' without --name parameter, which will pull the logs from all supported resources in your stack.
2022-01-26 16:50:57,774 | Getting logical id of the all resources for stack 'None'
2022-01-26 16:50:57,774 | Fetching stack (None) resources
2022-01-26 16:50:57,806 | Template is not provided in context, skip adding project type metric
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 166, in wrapped
  File "samcli/lib/telemetry/metric.py", line 124, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 87, in wrapper
  File "samcli/commands/_utils/experimental.py", line 197, in wrapped_func
  File "samcli/commands/_utils/experimental.py", line 197, in wrapped_func
  File "samcli/commands/_utils/experimental.py", line 197, in wrapped_func
  File "samcli/commands/logs/command.py", line 120, in cli
  File "samcli/commands/logs/command.py", line 167, in do_cli
  File "samcli/commands/logs/logs_context.py", line 104, in get_resource_information
  File "samcli/commands/logs/logs_context.py", line 128, in _fetch_resources_from_stack
  File "samcli/lib/utils/cloudformation.py", line 75, in get_resource_summaries
  File "boto3/resources/factory.py", line 474, in create_resource
  File "boto3/resources/base.py", line 119, in __init__
ValueError: Required parameter name not set
[26588] Failed to execute script __main__
```

### Expected result:

Cloudwatch log output e.g.
```
~ sam.133 logs -n my-example-lambda -s "2 mins ago"
2022/01/26/[$LATEST]1526f8a8a7e943c6b88ddd87f29a081c 2022-01-26T16:50:39.149000 START RequestId: e11efdd9-b97f-4783-b2bf-fbcf63ce4659 Version: $LATEST
...
2022/01/26/[$LATEST]1526f8a8a7e943c6b88ddd87f29a081c 2022-01-26T16:50:40.271000 END RequestId: e11efdd9-b97f-4783-b2bf-fbcf63ce4659
```
For reference, this is the debug output when running with SAM CLI 1.33.0:

```bash
~ sam.133 logs -n my-example-lambda -s "1 mins ago" --debug
2022-01-26 16:53:34,427 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-01-26 16:53:34,427 | Using config file: samconfig.toml, config environment: default
2022-01-26 16:53:34,427 | Expand command line arguments to:
2022-01-26 16:53:34,427 | --name=my-example-lambda --start_time=1 mins ago
2022-01-26 16:53:34,649 | 'logs' command is called
2022-01-26 16:53:34,710 | Fetching logs from CloudWatch with parameters {'logGroupName': '/aws/lambda/my-example-lambda ', 'interleaved': True, 'startTime': 1643215954670}
2022-01-26 16:53:35,298 | Calling mapper (<samcli.lib.observability.cw_logs.cw_log_formatters.CWColorizeErrorsFormatter object at 0x7f8a2bb54110>) for event (<samcli.lib.observability.cw_logs.cw_log_event.CWLogEvent object at 0x7f8a2bb63d90>)
2022-01-26 16:53:35,298 | Calling mapper (<samcli.lib.observability.cw_logs.cw_log_formatters.CWJsonFormatter object at 0x7f8a2bb635d0>) for event (<samcli.lib.observability.cw_logs.cw_log_event.CWLogEvent object at 0x7f8a2bb63d90>)
2022-01-26 16:53:35,298 | Calling mapper (<samcli.lib.observability.cw_logs.cw_log_formatters.CWKeywordHighlighterFormatter object at 0x7f8a2bb633d0>) for event (<samcli.lib.observability.cw_logs.cw_log_event.CWLogEvent object at 0x7f8a2bb63d90>)
2022-01-26 16:53:35,298 | Calling mapper (<samcli.lib.observability.cw_logs.cw_log_formatters.CWPrettyPrintFormatter object at 0x7f8a2bb639d0>) for event (<samcli.lib.observability.cw_logs.cw_log_event.CWLogEvent object at 0x7f8a2bb63d90>)
2022-01-26 16:53:35,298 | Calling consumer (<samcli.commands.logs.console_consumers.CWConsoleEventConsumer object at 0x7f8a2bb63590>) for event (<samcli.lib.observability.cw_logs.cw_log_event.CWLogEvent object at 0x7f8a2bb63d90>)
... (log output begins)
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 using WSL 2 and Ubuntu 20.04
2. `sam --version`: SAM CLI, version 1.37.0
3. AWS region: eu-west-2

**Comment by qingchm** [comment]
Hi there @andyeff to resolve your problem here you would simply provide an extra parameter --stack-name and provide the name of your stack which this function is a part of. Please let me know if this unblocks you! I believe this difference comes from our latest accelerate project that the logs command now supports many new features, you can read more about it here! https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/accelerate-monitoring.html#accelerate-logs. Meanwhile I will check with the team to verify this is a regression and discuss how to avoid people from getting confused by this!

**Comment by andyeff** [comment]
Hi @qingchm  - I can confirm amending my input to `sam logs --stack-name my-lambda-stack -n LogicalLambdaName` works - thank you for this!

I suspect maybe I did not read the changelogs well enough to see the issue here. It feels like the 1.33.0 behaviour of being able to use the long-form lambda name and no stack name is quite useful.  
For this to work in 1.37.0, I had to remember what the logical name of my lambda was, rather than the display name that I / others would see in the console. So in my example, `-n my-example-lambda` would become -n `rLambda` as that is what I named it logically in the cloudformation template.

It feels like this change between the SAM versions makes it more aligned with Cloudformation, which I suppose seems reasonable.

**Comment by praneetap** [comment]
Try `sam logs --tail --include-traces --beta-features` and let me know how you like it!

**Comment by qingchm** [comment]
@andyeff I believe actually both logical ID and the CFN actual resource name works! You can still input the actual name but just with an additional stack name provided! Let me know how it turns out!

**Comment by andyeff** [comment]
Thanks both - can confirm this is working very well. I'm especially liking the new `sam sync` functionality :)
