### ISSUE TITLE
Lambda sam invoke with UnicodeDecodeError: 'utf-8' codec can't decode

### ISSUE THREAD

**Issue by NoaNextInsurance** [aws/aws-sam-cli#3615]
### Description:
Lambda sam invoke with UnicodeDecodeError: 'utf-8' codec can't decode

### Steps to reproduce:
I try to invoke a Lambda using SAM CLI, after build had succeeded
The lambda event is a parquet file, and it seems that the failure occurs in the "get_event" phase, As you can see in the logs below. 
When tying to run the same Lambda function with the same parquet file in the console- there i no failure. 

please see the logs below:  
  _sam local invoke "noa_pre_etl" -e event.parquet  
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 85, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 149, in do_cli
    event_data = _get_event(event)
  File "/usr/local/Cellar/aws-sam-cli/1.37.0/libexec/lib/python3.8/site-packages/samcli/commands/local/invoke/cli.py", line 220, in _get_event
    return fp.read()
  File "/usr/local/Cellar/python@3.8/3.8.12_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb4 in position 7: invalid start byte_

### Observed result:
invoke failure

### Expected result:
invoke succeeded

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MAC/IOS
2. `sam --version`: 1.37.0
3. AWS region: Oregon

**Comment by wchengru** [comment]
Thanks for letting us know this issue!
According to [this](https://docs.aws.amazon.com/lambda/latest/dg/lambda-services.html), AWS Lambda does not support Parquet file as an event. Please consider converting the event into a JSON file.

**Comment by wchengru** [comment]
I will close this issue because Parquet events are not yet supported by AWS Lambda. Please reopen it if you have any further questions or requests.

**Comment by NoaNextInsurance** [comment]
@wchengru how come when I am using the AWS console it does work?

**Comment by wchengru** [comment]
@NoaNextInsurance Thanks for the update! Can you please provide us a simple example of Parquet event without including any private data of user, for us to reproduce this issue. I will reopen this issue, and keep investigating it.

**Comment by hottayusuke** [comment]
me too. Windows team can't work.
WIN 10

**Comment by mndeveci** [comment]
Thanks for reporting this issue.

Can you please provide us the input file (which doesn't include any private data) so that we can try to re-produce it?

You can also use [SAM Accelerate](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/accelerate.html) to deploy your function in the cloud, and invoke with the payload which might not be supported by `sam local`.

**Comment by mingkun2020** [comment]
Closing. Feel free to reopen if there is more information on this issue.
