### ISSUE TITLE
An error occurred (AccessDenied) when calling the PutObject operation: Access Denied

### ISSUE THREAD

**Issue by kiriti999** [aws/aws-sam-cli#3698]
### Description:
Access denied error while running sam deploy. 
Note: Using root account and provided full public access on s3 bucket as well

### Steps to reproduce:
 sam deploy --debug --region eu-west-1

### Observed result:
sam deploy --debug --region eu-west-1
```
2022-03-01 14:09:44,592 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-03-01 14:09:44,593 | Using config file: samconfig.toml, config environment: default
2022-03-01 14:09:44,593 | Expand command line arguments to:
2022-03-01 14:09:44,594 | --template_file=D:\workspace\node\dbscriptsliquibase\template.yaml --fail_on_empty_changeset --confirm_changeset --disable_rollback --stack_name=dbscriptsliquibase --s3_bucket=aws-sam-cli-managed-default-samclisourcebucket-1ojhaimphuj19 --s3_prefix=dbscriptsliquibase --parameter_overrides={'Environment': 'qa', 'AccountId': '553856789961', 'Region': 'eu-west-1', 'Location': 'euw1', 'AppName': 'dbscriptsliquibase', 'VpcSg': 'sg-0e7c40083c916ebfa', 'LogRetention': '1'} --capabilities=['CAPABILITY_NAMED_IAM']
2022-03-01 14:09:44,880 | Collected default values for parameters: {'Environment': 'qa', 'AccountId': 553856789961, 'Region': 'eu-west-1', 'Location': 'euw1', 'AppName': 'dbscriptsliquibase', 'VpcSg': 'sg-0e7c40083c916ebfa', 'LogRetention': 1}
2022-03-01 14:09:44,900 | There is no customer defined id or cdk path defined for resource CreateUsersApiFunction, so we will use the resource logical id as the resource id
2022-03-01 14:09:44,901 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-03-01 14:09:44,902 | 2 stacks found in the template
2022-03-01 14:09:44,991 | There is no customer defined id or cdk path defined for resource CreateUsersApiFunction, so we will use the resource logical id as the resource id
2022-03-01 14:09:44,992 | Sam customer defined id is more priority than other IDs. Customer defined id for resource CreateUsersApiFunction is CreateUsersApiFunction
2022-03-01 14:09:45,965 | Unable to export
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\packageable_resources.py", line 127, in export
    self.do_export(resource_id, resource_dict, parent_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\packageable_resources.py", line 149, in do_export
    uploaded_url = upload_local_artifacts(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\utils.py", line 171, in upload_local_artifacts
    return zip_and_upload(local_path, uploader, extension)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\utils.py", line 189, in zip_and_upload
    return uploader.upload_with_dedup(zip_file, precomputed_md5=md5_hash, extension=extension)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\s3_uploader.py", line 143, in upload_with_dedup
    return self.upload(file_name, remote_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\s3_uploader.py", line 122, in upload
    raise ex
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\package\s3_uploader.py", line 114, in upload
    future.result()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\s3transfer\futures.py", line 103, in result
    return self._coordinator.result()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\s3transfer\futures.py", line 266, in result
    raise self._exception
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\s3transfer\tasks.py", line 139, in __call__
    return self._execute_main(kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\s3transfer\tasks.py", line 162, in _execute_main
    return_value = self._main(**kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\s3transfer\upload.py", line 757, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied
```

### Expected result:
stack should be deployed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 11
2. `sam --version`: 1.4.0
3. AWS region: eu-west-1

Template:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM Template for dbscriptsliquibase application

Globals:
  Function:
    CodeUri: ./src/handlers
    Timeout: 10
    Runtime: nodejs14.x
    Environment:
      Variables:
        NODE_ENV: "production"
        HOST: !Sub "{{resolve:secretsmanager:/${Environment}/${AppName}/dbInfo:SecretString:host}}"
        PORT: !Sub "{{resolve:secretsmanager:/${Environment}/${AppName}/dbInfo:SecretString:port}}"
        USER: !Sub "{{resolve:secretsmanager:/${Environment}/${AppName}/dbInfo:SecretString:username}}"
        PASSWORD: !Sub "{{resolve:secretsmanager:/${Environment}/${AppName}/dbInfo:SecretString:password}}"
        DATABASE: !Sub "{{resolve:secretsmanager:/${Environment}/${AppName}/dbInfo:SecretString:dbname}}"
        CONNECTION_TIMEOUT: "20000"
        LIMIT_MAX_VALUE: "500"
        AWSREGION: "eu-west-1"
        AWS_API_VERSION: "2012-11-05"
    VpcConfig:
      SecurityGroupIds:
        - !Ref VpcSg
      SubnetIds:
        - subnet-05ea2dab834e8a06c
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowHeaders: "'Access-Control-Allow-Headers, Origin, Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'"
      AllowMethods: "'GET, POST'"
Parameters:
  Environment:
    Type: String
    Default: qa
    AllowedValues:
      - dev
      - qa
      - prod
    Description: Enter dev, qa, or prod. Default is dev.
  AccountId:
    Type: Number
    Default: 553856789961
  Region:
    Type: String
    Default: eu-west-1
  Location:
    Type: String
    Default: euw1
  AppName:
    Type: String
    Default: "dbscriptsliquibase"
  VpcSg:
    Type: String
    Default: sg-0e7c40083c916ebfa
  LogRetention:
    Type: Number
    Default: 1

Resources:
  CreateUsersApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AppName}-createUsersApi-${Environment}-${Location}-lambda"
      Handler: createUsers.createUsersApiHandler
      Policies:
        - AdministratorAccess
      Architectures:
        - x86_64
      Events:
        AssignUsers:
          Type: Api
          Properties:
            Path: /assign-users
            Method: post
        UnassignUsers:
          Type: Api
          Properties:
            Path: /unassign-users
            Method: post

```            
samconfig.toml:

```
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dbscriptsliquibase"
s3_prefix = "dbscriptsliquibase"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"qa\" AccountId=\"553856789961\" Region=\"eu-west-1\" Location=\"euw1\" AppName=\"dbscriptsliquibase\" VpcSg=\"sg-0e7c40083c916ebfa\" LogRetention=\"1\""
image_repositories = []
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ojhaimphuj19"
```

S3 bucket policy:

```
{
    "Version": "2012-10-17",
    "Id": "BucketPolicy",
    "Statement": [
        {
            "Sid": "AllAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "*"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::dbscriptsliquibase",
                "arn:aws:s3:::dbscriptsliquibase/*"
            ]
        }
    ]
}
```

`Add --debug flag to command you are running`

**Comment by kiriti999** [comment]
It was bucket issue which got resolved by passing `--s3-bucket dbscriptsliquibase`
