### ISSUE TITLE
"samdev local start-api" fails following "samdev init"

### ISSUE THREAD

**Issue by evgeny-roubinchtein** [aws/aws-sam-cli#3711]
### Description:
If I run `samdev init`, and then follow up with `samdev local start-api`, I
get an error.

### Steps to reproduce:
I did the following:

1. Following the Contributing guide, used pyenv to create a virtualenv which
I called `samcli-python3.8` based on a version of Python I got by running `pyenv install 3.8.12`

2. Activated my virtualenv with `pyenv activate samcli-python3.8`, cloned
the repo, and then ran `cd; samdev init`.  I selected the "Hello World"
template with a Python3.8 runtime and Zip packaging.

3. I then ran `samdev local start-api --warm-containers EAGER 2>&1 | tee log`

### Observed result:
```
Initializing the lambda functions containers.
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image...
Failed to build Docker Image
Traceback (most recent call last):
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/build?t=public.ecr.aws%2Fsam%2Femulation-python3.8%3Arapid-1.40.1-x86_64&q=False&nocache=False&rm=True&forcerm=False&pull=True&platform=linux%2Famd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/host/home/zhenya/aws-sam-cli/samcli/local/docker/lambda_image.py", line 269, in _build_image
    for log in resp_stream:
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 354, in _stream_helper
    yield self._result(response, json=decode)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error processing tar file(exit status 1): lchown /Dockerfile: invalid argument")
Lambda functions containers initialization failed because of Building Image failed.
Error: Lambda functions containers initialization failed
```
AFAICT, there is no `<image>:<tag>` `sam/emulation-python3.8:rapid-1.40.1-x86_64``
in repo `public.ecr.aws`.  Is that the root cause?

### Expected result:
I would like "it to work": you know, give me a server that listens on port
3000 and to which I can POST/GET to get my "hello world" greeting.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux (Arch)
2. `samdev --version`: SAM CLI, version 1.40.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

```
2022-03-04 22:30:32,833 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-03-04 22:30:32,833 | Using config file: samconfig.toml, config environment: default
2022-03-04 22:30:32,833 | Expand command line arguments to:
2022-03-04 22:30:32,833 | --template_file=/run/host/home/zhenya/sam-app/template.yaml --warm_containers=EAGER --host=127.0.0.1 --port=3000 --static_dir=public --layer_cache_basedir=/run/host/home/zhenya/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2022-03-04 22:30:32,903 | local start-api command is called
2022-03-04 22:30:32,908 | No Parameters detected in the template
2022-03-04 22:30:32,926 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,927 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,927 | 2 stacks found in the template
2022-03-04 22:30:32,928 | No Parameters detected in the template
2022-03-04 22:30:32,940 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,941 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,941 | 2 resources found in the stack 
2022-03-04 22:30:32,941 | No Parameters detected in the template
2022-03-04 22:30:32,954 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,954 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-03-04 22:30:32,955 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2022-03-04 22:30:32,955 | --base-dir is not presented, adjusting uri hello_world/ relative to /run/host/home/zhenya/sam-app/template.yaml
2022-03-04 22:30:32,956 | watch resource /run/host/home/zhenya/sam-app/template.yaml
2022-03-04 22:30:32,956 | Create Observer for resource /run/host/home/zhenya/sam-app/template.yaml with recursive True
2022-03-04 22:30:32,957 | watch resource /run/host/home/zhenya/sam-app/template.yaml's parent /run/host/home/zhenya/sam-app
2022-03-04 22:30:32,958 | Create Observer for resource /run/host/home/zhenya/sam-app with recursive False
2022-03-04 22:30:32,962 | Initializing the lambda functions containers.
2022-03-04 22:30:32,963 | Async execution started
2022-03-04 22:30:32,963 | Invoking function functools.partial(<function InvokeContext._initialize_all_functions_containers.<locals>.initialize_function_container at 0x7f46c0a4bb80>, Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='python3.8', memory=None, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/run/host/home/zhenya/sam-app/hello_world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], stack_path=''))
2022-03-04 22:30:32,964 | Waiting for async results
2022-03-04 22:30:32,967 | No environment variables found for function 'HelloWorldFunction'
2022-03-04 22:30:32,967 | Environment variables overrides data is standard format
2022-03-04 22:30:32,967 | Loading AWS credentials from session with profile 'None'
2022-03-04 22:30:32,979 | Resolving code path. Cwd=/run/host/home/zhenya/sam-app, CodeUri=/run/host/home/zhenya/sam-app/hello_world
2022-03-04 22:30:32,980 | Resolved absolute path to code is /run/host/home/zhenya/sam-app/hello_world
2022-03-04 22:30:32,981 | watch resource /run/host/home/zhenya/sam-app/hello_world
2022-03-04 22:30:32,981 | Create Observer for resource /run/host/home/zhenya/sam-app/hello_world with recursive True
2022-03-04 22:30:32,981 | watch resource /run/host/home/zhenya/sam-app/hello_world's parent /run/host/home/zhenya/sam-app
2022-03-04 22:30:32,982 | Code /run/host/home/zhenya/sam-app/hello_world is not a zip/jar file
2022-03-04 22:30:32,984 | Image was not found.
2022-03-04 22:30:32,985 | Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image...
2022-03-04 22:30:33,383 | Failed to build Docker Image
Traceback (most recent call last):
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/build?t=public.ecr.aws%2Fsam%2Femulation-python3.8%3Arapid-1.40.1-x86_64&q=False&nocache=False&rm=True&forcerm=False&pull=True&platform=linux%2Famd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/run/host/home/zhenya/aws-sam-cli/samcli/local/docker/lambda_image.py", line 269, in _build_image
    for log in resp_stream:
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 354, in _stream_helper
    yield self._result(response, json=decode)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 267, in _result
    self._raise_for_status(response)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/run/host/home/zhenya/.pyenv/versions/3.8.12/envs/samcli-python3.8/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("Error processing tar file(exit status 1): lchown /Dockerfile: invalid argument")
2022-03-04 22:30:33,385 | Exception raised during the execution
2022-03-04 22:30:33,386 | Lambda functions containers initialization failed because of Building Image failed.
2022-03-04 22:30:33,386 | Terminating all running warm containers
2022-03-04 22:30:33,386 | Cleaning all decompressed code dirs
2022-03-04 22:30:33,398 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'be04b4e2-7ebf-45aa-8d53-33dd3ce02611', 'installationId': '4e4e252d-1f6b-4dfe-b04d-35a646ce5b05', 'sessionId': 'c8141f83-186f-4861-8c2d-0b2a8097f33f', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.12', 'samcliVersion': '1.40.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'samdev local start-api', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 565, 'exitReason': 'ContainersInitializationException', 'exitCode': 1}}]}
2022-03-04 22:30:33,559 | Telemetry response: 200
Error: Lambda functions containers initialization failed
```

**Comment by evgeny-roubinchtein** [comment]
@jfuss Yes, it probably was my Docker configuration.  I have since stopped using SAM, opting instead for vanilla CloudFormation templates: I don't _always_ want an OpenAPI generated for my API Gateway, but, last time I checked, SAM _only_ does OpenAPI.  Closing.
