### ISSUE TITLE
Dependencies are not working with sam sync using esbuild

### ISSUE THREAD

**Issue by henrik-billy** [aws/aws-sam-cli#3759]
### Description:
Runtime dependencies are not included when using sam sync and esbuild.

### Steps to reproduce:

1. Do a sam init for a hello world project with Typescript.
2. Add a runtime dependency and use that in app.ts.
3. Do a sam build + sam deploy --guided.
4. Check that the HTTP endpoint works.
5. Run sam sync and wait for "Infra sync completed.".
4. Check that the HTTP endpoint works.This time it gives an internal server error. 

### Observed result:
The logs say:

`{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'uuid'\nRequire stack:\n- /var/task/app.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'uuid'","Require stack:","- /var/task/app.js","- /var/runtime/UserFunction.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:202:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)","    at Object.<anonymous> (/var/runtime/index.js:43:30)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function.Module._load (internal/modules/cjs/loader.js:790:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)","    at internal/main/run_main_module.js:17:47"]}`

### Expected result:
A successful response.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu
6. `sam --version`: 1.40.1
7. AWS region: eu-north-1

`Add --debug flag to command you are running`

**Comment by henrik-billy** [comment]
Hi @mildaniel,
This is indeed a duplicate of #3707. 
Adding `--no-dependency-layer` fixes the problem.
