### ISSUE TITLE
sam sync runs into infinite error loop `cannot find esbuild` when npm dependencies are changed and does no longer create node_modules even on clean re-run

### ISSUE THREAD

**Issue by passionkind** [aws/aws-sam-cli#3772]
### Description:

When using `sam sync` there is no dependencies layer being created. However, when I run `sam deploy` first and then `sam sync` there is an initial `node_modules` folder in a layer. But changing dependencies afterwards will remove the layer, not create a new one and fail with an error as `esbuild` can no longer be found.

### Steps to reproduce:

follow https://aws.amazon.com/blogs/compute/building-typescript-projects-with-aws-sam-cli/

#### 🟢 `sam init` 
[sam-init.log](https://github.com/aws/serverless-application-model/files/8336556/sam-init.log)

<details>
    <summary>file structure</summary>

<pre>
└──     events/
 │  └────     event.json
 └──     hello-world/
 │  └────     tests/
 │  │  └────     unit/
 │  │  │  └────     test-handler.test.ts
 │  ├────     .eslintignore
 │  ├────     .eslintrc.js
 │  ├────     .npmignore
 │  ├────     .prettierrc.js
 │  ├────     app.ts
 │  ├────     jest.config.ts
 │  ├────     package.json
 │  └────     tsconfig.json
 ├──     .gitignore
 ├──     README.md
 └──     template.yaml
</pre>

</details>

-----

#### 🟢 `sam build` 
[sam-build.log](https://github.com/aws/serverless-application-model/files/8336557/sam-build.log)

I did not need to change template.yaml as it already contained the `Metadata` part mentioned in the docs

<details>
    <summary>file structure</summary>
<pre>
└──     .aws-sam/
 │  └────     build/
 │  │  └────     HelloWorldFunction/
 │  │  │  ├────     app.js
 │  │  │  └────     app.js.map
 │  │  └────     template.yaml
 │  └────     build.toml
 └──     events/
 │  └────     event.json
 └──     hello-world/
 │  └────     tests/
 │  │  └────     unit/
 │  │  │  └────     test-handler.test.ts
 │  ├────     .eslintignore
 │  ├────     .eslintrc.js
 │  ├────     .npmignore
 │  ├────     .prettierrc.js
 │  ├────     app.ts
 │  ├────     jest.config.ts
 │  ├────     package.json
 │  └────     tsconfig.json
 ├──     .gitignore
 ├──     README.md
 └──     template.yaml
</pre>
</details>

-----

#### 🟢 `sam deploy --guided` 
[sam-deploy.log](https://github.com/aws/serverless-application-model/files/8336558/sam-deploy.log)

no changes in file structure

-----

#### ❌ `sam sync --stack-name node-modules-test-6 --watch` (fails after dependencies are changed)

[sam-sync.log](https://github.com/aws/serverless-application-model/files/8336560/sam-sync.log)

- calling the lambda now works as expected and `node_modules` exist for expected layer id. 
- changing code also works fine and results in changed return message from lambda function.

But installing a dependency (`@aws-sdk/client-s3`) will result in an error loop due to missing `esbuild`. The `/deps/xyz` folder will be empty.

<details>
    <summary>file structure</summary>
<pre>
└──     .aws-sam/
 │  └────     auto-dependency-layer/
 │  │  └────     HelloWorldFunction/
 │  │  │  ├────     app.js
 │  │  │  └────     app.js.map
 │  │  └────     HelloWorldFunction19d43fc4DepLayer/
 │  │  │  └────     nodejs/
 │  │  │  └────     AWS_SAM_CLI_README
 │  │  ├────     nested_template.yaml
 │  │  └────     template.yaml
 │  └────     build/
 │  │  └────     HelloWorldFunction/
 │  │  │  ├────     app.js
 │  │  │  └────     app.js.map
 │  │  └────     template.yaml
 │  └────     cache/
 │  └────     deps/
 │  │  └────     6f9fcb11-f1f8-439c-a68e-7a57d7bf4835/
 │  │  │  └────     node_modules/ << ✅ contains expected modules
 │  └────     build.toml
 └──     events/
 │  └────     event.json
 └──     hello-world/
 │  └────     node_modules/
 │  └────     tests/
 │  │  └────     unit/
 │  │  │  └────     test-handler.test.ts
 │  ├────     .eslintignore
 │  ├────     .eslintrc.js
 │  ├────     .npmignore
 │  ├────     .prettierrc.js
 │  ├────     app.ts
 │  ├────     jest.config.ts
 │  ├────     package.json
 │  └────     tsconfig.json
 ├──     .gitignore
 ├──     README.md
 ├──     samconfig.toml
 └──     template.yaml
</pre>
</details>

**Log excerpt**

```bash
Code sync encountered an error.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 230, in execute
    version = self.subprocess_esbuild.run(args, cwd=self.scratch_dir)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 93, in run
    invoke_esbuild = [self.esbuild_binary()] + args
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 64, in esbuild_binary
    raise EsbuildExecutionError(message="cannot find esbuild")
aws_lambda_builders.workflows.nodejs_npm_esbuild.esbuild.EsbuildExecutionError: Esbuild Failed: cannot find esbuild

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 302, in run
    action.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 232, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Esbuild Failed: cannot find esbuild

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 740, in _build_function_in_process
    builder.build(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/builder.py", line 164, in build
    return workflow.run()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 96, in wrapper
    func(self, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 309, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: NodejsNpmEsbuildBuilder:EsbuildCheckVersion - Esbuild Failed: cannot find esbuild

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/sync/sync_flow_executor.py", line 335, in _sync_flow_execute_wrapper
    dependent_sync_flows = sync_flow.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/sync/sync_flow.py", line 291, in execute
    self.gather_resources()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/sync/flows/zip_function_sync_flow.py", line 93, in gather_resources
    build_result = builder.build()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 510, in build
    result.update(super().build())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 520, in build_single_function_definition
    return self._incremental_build_strategy.build_single_function_definition(build_definition)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 419, in build_single_function_definition
    return self._delegate_build_strategy.build_single_function_definition(build_definition)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 654, in _build_function
    return self._build_function_in_process(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.40.1/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 757, in _build_function_in_process
    raise BuildError(wrapped_from=ex.__class__.__name__, msg=str(ex)) from ex
samcli.lib.build.exceptions.BuildError: NodejsNpmEsbuildBuilder:EsbuildCheckVersion - Esbuild Failed: cannot find esbuild
Syncing Lambda Function HelloWorldFunction...
Manifest is not changed for af9e866d-e660-457a-8861-371c48d0b747, running incremental build
Building codeuri: /Users/bastian/development/awssam/node-modules-test-3/hello-world runtime: nodejs14.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}} architecture: x86_64 functions: ['HelloWorldFunction']
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:EsbuildCheckVersion
```

-----

#### ⚠️ delete `.aws-sam` and re-run `sam sync --stack-name node-modules-test-6 --watch`
[sam-sync-retry.log](https://github.com/aws/serverless-application-model/files/8336566/sam-sync-retry.log)

This won't create any new layers / update node_modules and keep the initial layer in the cloud for running the function, which will throw as the dependency cannot be found.

The folder `deps` will remain empty.

### Workaround 

- using `--no-dependency-layer` seems to work fine 

### Expected result:

- dependency layers are being re-created when node_modules change
- `esbuild` should be available after dependency changes and not cause `sync` to error
- initial `sam sync` should probably also create a layer without having to run `sam deploy` first (or it should be explicitly mentioned)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```bash
Machine: 
- Mac mini (M1, 2020)
- Chip Apple M1
- Memory 16 GB
- Startup Disk Macintosh HD

System:
macOS version: 12.3
Node manager:  fnm
Node version:  v14.18.2
SAM version:   SAM CLI, version 1.40.1
AWS-Region:    eu-central-1
```

### Additional notes

- it would be very helpful if the following lines could be disabled from `--debug` output (was like 2/3 of all logs during sync)
```
Found the same SyncFlow in queue. Skip adding.
No Parameters detected in the template
There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
```

**Comment by mildaniel** [comment]
Hey @passionkind, thanks for bringing this to our attention and providing clear repro steps. I will investigate this issue and try to provide an update. 

Also, moving this issue to the aws-sam-cli repo.

**Comment by mildaniel** [comment]
>  Should /var/folders/9p/_yfdq0814fl22vb7sggcmx1w0000gn/T/tmp53wpxrb8 exist after the NodejsNpmEsbuildBuilder:NpmCI step?

It actually shouldn't. This is a "clean" directory where we perform build steps before moving everything to the correct artifacts directory. The `npm ci` time is certainly interesting though as it might be skipping some dependencies for some reason. Would you be able to pull down the layer zip and provide the contents of it?

**Comment by passionkind** [comment]
I deleted the stack and just checked if there are still any layers available. I have 4 remaining and all of them only contain a single file `AWS_SAM_CLI_README` 

I'll try to go through it again and try to download all layers I can find for the new stack.

**Comment by passionkind** [comment]
I went through the tutorial again and have 2 layers

01: before I added another module through `npm install ...` 
https://file.io/KW1MBtYb1WJH (had to upload it somewhere else as it's too large for a github comment)

02: after I ran `npm install` and the sync failed
[02-layer-test6c2ce484-HelloWorldFunction19d43fc4-DepLayer-2d3dcc09-3735-4a3a-a096-5a90fbbde355.zip](https://github.com/aws/aws-sam-cli/files/8336966/02-layer-test6c2ce484-HelloWorldFunction19d43fc4-DepLayer-2d3dcc09-3735-4a3a-a096-5a90fbbde355.zip)


I wonder if that temporary folder should not exist after `npm ci`, how is npm supposed to find `esbuild` when it's a devDependency. How is `esbuild` being resolved?

```
Error: Cannot find module 'esbuild'
Require stack:
- /private/var/folders/9p/_yfdq0814fl22vb7sggcmx1w0000gn/T/tmpjkp5uteb/tmpend4f3za
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/private/var/folders/9p/_yfdq0814fl22vb7sggcmx1w0000gn/T/tmpjkp5uteb/tmpend4f3za:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/private/var/folders/9p/_yfdq0814fl22vb7sggcmx1w0000gn/T/tmpjkp5uteb/tmpend4f3za'
  ]
}
```

Could you point me to the source of `Running NodejsNpmEsbuildBuilder:NpmCI` ? Maybe it helps me to better understand what's going on and provide you further details.

**Comment by mildaniel** [comment]
`NodejsNpmEsbuildBuilder:NpmCI` is done in the aws-lambda-builders package, not in the cli. Unfortunately the way lambda builders is designed we have to keep using that scratch directory for the time being. The executable should be found through the installation or globally through the user's system. It was recently updated not to always use `npm ci` but to default to `npm install` unless `npm ci` was explicitly stated. For `sam sync` we should probably always be using install since it should always be used in development. I'm not sure if that will address this issue, likely not, but I will need to take a deeper look.

**Comment by passionkind** [comment]
A little update:

I've just set up my brand new Mac. I didn't copy/paste/restore as I usually do. I wanted to have a really clean start, so I reinstalled everything manually and paid special attention to not follow any bad practices just because the system is supposed to run as I wish right now (am I the only one who's falling into that pit sometimes? 🙈)

And I can confirm that the result is the exact same: `Esbuild Failed: cannot find esbuild`.

What systems are you guys using at AWS to run in. Or do you meanwhile experience the same issue?

**Comment by staleks** [comment]
I have the same issue :(

OS: macOS Monterey v12.4

AWS SAM CLI: Installed using Homebrew
`
$ sam --version
SAM CLI, version 1.33.0
`

ESBuild: Installed using Homebrew
`
$ esbuild --version
0.14.43
` 

I've followed the procedure for `sam init`.
Which template source would you like to use? - 1 - AWS Quick Start Templates
What package type would you like to use? - 1 - Zip (artifact is a zip uploaded to S3)
Which runtime would you like to use? - 1 - nodejs14.x

I've named the app "demo"

Cloning from https://github.com/aws/aws-sam-cli-app-templates

AWS quick start application templates: - 2 - Hello World Example TypeScript
`
    -----------------------
    Generating application:
    -----------------------
    Name: demo
    Runtime: nodejs14.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world-typescript
    Output Directory: .
    
    Next steps can be found in the README file at ./demo/README.md
`

And then whey I try to invoke `sam build`, I'm getting following error

`
Building codeuri: /Users/aleksandarstoisavljevic/work-novacode/aws-sam/demo/hello-world runtime: nodejs14.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}} architecture: x86_64 functions: ['HelloWorldFunction']
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 153, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 122, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 210, in cli
    do_cli(
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/commands/build/command.py", line 318, in do_cli
    artifacts = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 172, in build
    return build_strategy.build()
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 42, in build
    result.update(self._build_functions(self._build_graph))
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 53, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 120, in build_single_function_definition
    result = self._build_function(
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 551, in _build_function
    config = get_workflow_config(runtime, code_dir, self._base_dir, specified_workflow=specified_build_workflow)
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/workflow_config.py", line 260, in get_workflow_config
    selector = get_selector(
  File "/usr/local/Cellar/aws-sam-cli/1.33.0/libexec/lib/python3.8/site-packages/samcli/lib/build/workflow_config.py", line 133, in get_selector
    raise UnsupportedBuilderException("'{}' does not have a supported builder".format(specified_workflow))
samcli.lib.build.workflow_config.UnsupportedBuilderException: 'esbuild' does not have a supported builder
`

**Comment by mndeveci** [comment]
@staleks thanks for confirming this is resolved with newer version of SAM CLI. We did a bug-fix in lambda-builders which fixed an issue about not copying `node_modules` if it is already present in the source folder, that might fix this issue as well.

@passionkind can you update and check if newer version of SAM CLI resolves the issue for you as well?

**Comment by passionkind** [comment]
Finally had a chance to try it again and yes, it works as expected 🙏👏 thanks a lot!
