### ISSUE TITLE
SAM CLI on Windows / WSL2 and Ubuntu

### ISSUE THREAD

**Issue by shopizer-ecommerce** [aws/aws-sam-cli#3823]
<!-- Make sure we don't have an existing Issue that reports the bug you are seeing (both open and closed). 
I Followed installation and procedure
for Linux mentioned https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

### Description:
An error occured during the execution of sam local invoke

START RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14 Version: $LATEST
{"statusCode":200,"body":"{\"message\":\"hello world\"}"}END RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14
REPORT RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14  Init Duration: 0.28 ms  Duration: 188.03 ms     Billed Duration: 189 ms                                           Memory Size: 128 MB      Max Memory Used: 128 MB
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 146, in wrapped
  File "samcli/lib/iac/cdk/utils.py", line 27, in is_cdk_project
  File "samcli/lib/iac/cdk/utils.py", line 73, in _relevant_cdk_files_are_present
FileNotFoundError: [Errno 2] No such file or directory
[11624] Failed to execute script __main__

### Steps to reproduce:
Install SAM from WSL2 ubuntu 

unzip aws-sam-cli-linux-x86_64.zip -d sam-installation
sudo ./sam-installation/install

sam init

Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
        1 - Hello World Example
        2 - Multi-step workflow
        3 - Serverless API
        4 - Scheduled task
        5 - Standalone function
        6 - Data processing
        7 - Infrastructure event management
        8 - Machine Learning
Template: 1

 Use the most popular runtime and package type? (Python and zip) [y/N]: N

Which runtime would you like to use?
        1 - dotnet6
        2 - dotnet5.0
        3 - dotnetcore3.1
        4 - go1.x
        5 - java11
        6 - java8.al2
        7 - java8
        8 - nodejs14.x
        9 - nodejs12.x
        10 - python3.9
        11 - python3.8
        12 - python3.7
        13 - python3.6
        14 - ruby2.7
Runtime: 9

What package type would you like to use?
        1 - Zip
        2 - Image
Package type: 1

Based on your selections, the only dependency manager available is npm.
We will proceed copying the template using npm.

Project name [sam-app]:

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: nodejs12.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world
    Output Directory: .

    Next steps can be found in the README file at ./sam-app/README.md

    Commands you can use next
    =========================
    [*] Create pipeline: cd sam-app && sam pipeline init --bootstrap
    [*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
    
    cd sam-app
    sam build
    sam local invoke

### Observed result:
Hello world app and existing app displays an error in sam local invoke and sam build

### Expected result:
Hello worls simple sam app running without errors

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 entreprise with WSL2 and Ubuntu 20.0.4
2. `sam --version`:SAM CLI, version 1.46.0
3. AWS region:ca-central-1

`Add --debug flag to command you are running`

sam build --debug
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1257, in invoke
  File "click/core.py", line 700, in make_context
  File "click/core.py", line 1048, in parse_args
  File "click/core.py", line 1630, in handle_parse_result
  File "click/core.py", line 123, in invoke_param_callback
  File "samcli/cli/cli_config_file.py", line 132, in configuration_callback
FileNotFoundError: [Errno 2] No such file or directory
[16582] Failed to execute script __main__

**Comment by moelasmar** [comment]
@shopizer-ecommerce  .. could you please add a description for your issue?

**Comment by shopizer-ecommerce** [comment]
Sorry, i thought i already submitted the whole story. Anyway here is what i have experienced

OS windows 10 entreprise
WSL2 ubuntu 20
Docker desktop with WSL2 option

Followed the installation for Linux as described in the documentation https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-install-linux.html

SAM cli version
/usr/local/bin/sam --version
SAM CLI, version 1.46.0

Ran sam init hello world (option 1)

Tried 2 different runtimes
8 - nodejs14.x
9 - nodejs12.x

   -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: nodejs12.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world
    Output Directory: .
    


sam local invoke fails as well as subsequent sam build commands

Invoking app.lambdaHandler (nodejs12.x)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs12.x
Building image........................................................................................................
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs12.x:rapid-1.46.0-x86_64.

Mounting /mnt/c/WebDevelopment/repo/sam/sam-app/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
START RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14 Version: $LATEST
{"statusCode":200,"body":"{\"message\":\"hello world\"}"}END RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14
REPORT RequestId: a406a014-84c7-45b0-ba59-3eda6e001c14  Init Duration: 0.28 ms  Duration: 188.03 ms     Billed Duration: 189 ms                                           Memory Size: 128 MB      Max Memory Used: 128 MB
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 146, in wrapped
  File "samcli/lib/iac/cdk/utils.py", line 27, in is_cdk_project
  File "samcli/lib/iac/cdk/utils.py", line 73, in _relevant_cdk_files_are_present
FileNotFoundError: [Errno 2] No such file or directory
[11624] Failed to execute script __main__

**Comment by moelasmar** [comment]
thanks @shopizer-ecommerce for the update.

**Comment by Rabadash8820** [comment]
Looking at the source code, the line that's failing is calling `os.getcwd()`. Based on [this SO post](https://stackoverflow.com/questions/23889636/error-while-executing-os-getcwd), `getcwd` can fail if its inside a deleted directory, which maybe happens here if the directory is removed after the Function ends?

**Comment by qingchm** [comment]
@Rabadash8820 thanks for the investigation. Can you confirm that this problem still exists and we should restart some investigation on this?

**Comment by ireznik** [comment]
@qingchm issue still exists with aws-sam-cli version 1.80.0 on WSL 2 with Ubuntu 20.04.3 and Docker version 20.10.24, build 297e128

**Comment by alfarok** [comment]
+1 for the same issue

**Comment by josefernandezatceiba** [comment]
+1

**Comment by itsenov-work** [comment]
Same issue on WSL2, sam version 1.94.0, Ubuntu version 20.04

**Comment by chriseugenerodriguez** [comment]
I am having same issue with sam version 1.132.0, Windows 10
