### ISSUE TITLE
StackSet resource is not supported in SERVICE_MANAGED permission model

### ISSUE THREAD

**Issue by jeffmarcinko** [aws/aws-sam-cli#3872]
### Description:
The `sam deploy` command fails to deploy a template containing an `AWS::CloudFormation::StackSet` resource with the PermissionModel property value `SERVICE_MANAGED`.  This prevents the user from leveraging the AWS Organizations integration to deploy to a target OU instead of a list of AWS Account IDs.

### Steps to reproduce:

1. Enable trusted access in your AWS Organization for CloudFormation
2. Create a SAM template containing a single `AWS::CloudFormation::StackSet` resource
3. Set the PermissionModel property value to `SERVICE_MANAGED`
4. Set the DeploymentTargets property to deploy to an OU within the AWS Organization

```yaml
StackInstancesGroup:
      - DeploymentTargets:
          OrganizationalUnitIds:
          - ou-abcd-abcdefghi
        Regions:
        - us-east-1
```
5. Execute `sam deploy` 

### Observed result:
The Changeset is created successfully but the stack fails to deploy with the error `Transform is not supported in SERVICE_MANAGED permission model`

```
sam deploy \
--template-file build/packaged-stackset-template.yaml \
--stack-name oudeploy-stackset \
--no-fail-on-empty-changeset \
--capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
--region us-east-1 \
--debug

2022-05-10 11:44:04,691 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-05-10 11:44:04,692 | Using config file: samconfig.toml, config environment: default
2022-05-10 11:44:04,692 | Expand command line arguments to:
2022-05-10 11:44:04,692 | --template_file=/sam-stacksets/ou_deploy_hello_world/build/packaged-stackset-template.yaml --stack_name=oudeploy-stackset --capabilities=('CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', 'CAPABILITY_AUTO_EXPAND') 
2022-05-10 11:44:05,032 | No Parameters detected in the template
2022-05-10 11:44:05,058 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldStackSet is oudeploystackset
2022-05-10 11:44:05,059 | 0 stacks found in the template
2022-05-10 11:44:16,435 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldStackSet is oudeploystackset
2022-05-10 11:44:16,436 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldStackSet is oudeploystackset

        Deploying with following values
        ===============================
        Stack name                   : oudeploy-stackset
        Region                       : us-east-1
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : None
        Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM", "CAPABILITY_AUTO_EXPAND"]
        Parameter overrides          : {}
        Signing Profiles             : {}

Initiating deployment
=====================
2022-05-10 11:44:16,460 | No Parameters detected in the template
2022-05-10 11:44:16,481 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldStackSet is oudeploystackset
2022-05-10 11:44:16,489 | 0 stacks found in the template
2022-05-10 11:44:16,490 | No Parameters detected in the template
2022-05-10 11:44:16,512 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldStackSet is oudeploystackset
2022-05-10 11:44:16,533 | 1 resources found in the stack 
2022-05-10 11:44:16,889 | Stack with id oudeploy-stackset does not exist

Waiting for changeset to be created..

CloudFormation stack changeset
---------------------------------------------------------------------------------------------------------------------------------------------
Operation                           LogicalResourceId                   ResourceType                        Replacement                       
---------------------------------------------------------------------------------------------------------------------------------------------
+ Add                               HelloWorldStackSet                  AWS::CloudFormation::StackSet       N/A                               
---------------------------------------------------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:xxxxxxxxxxxx:changeSet/samcli-deploy1652197456/a4c6958f-899b-4e73-8eb0-528f556ca65d


2022-05-10 11:44:28 - Waiting for stack create/update to complete

CloudFormation events from stack operations
---------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                      ResourceType                        LogicalResourceId                   ResourceStatusReason              
---------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                  AWS::CloudFormation::StackSet       HelloWorldStackSet                  -                                 
CREATE_FAILED                       AWS::CloudFormation::StackSet       HelloWorldStackSet                  Resource handler returned         
                                                                                                            message: "Transform is not        
                                                                                                            supported in SERVICE_MANAGED      
                                                                                                            permission model (Service:        
                                                                                                            CloudFormation, Status Code: 400, 
                                                                                                            Request ID: a824f328-d736-440b-84 
                                                                                                            10-ccc8ff5b2a1b)" (RequestToken:  
                                                                                                            0bc7bb19-7aff-0814-1991-cc278e5b6 
                                                                                                            37d, HandlerErrorCode:            
                                                                                                            InvalidRequest)                   
ROLLBACK_IN_PROGRESS                AWS::CloudFormation::Stack          oudeploy-stackset                   The following resource(s) failed  
                                                                                                            to create: [HelloWorldStackSet].  
                                                                                                            Rollback requested by user.       
DELETE_COMPLETE                     AWS::CloudFormation::StackSet       HelloWorldStackSet                  -                                 
ROLLBACK_COMPLETE                   AWS::CloudFormation::Stack          oudeploy-stackset                   -                                 
---------------------------------------------------------------------------------------------------------------------------------------------
2022-05-10 11:46:47,791 | Execute stack waiter exception
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.48.0/libexec/lib/python3.8/site-packages/samcli/lib/deploy/deployer.py", line 459, in wait_for_execute
    waiter.wait(StackName=stack_name, WaiterConfig=waiter_config)
  File "/usr/local/Cellar/aws-sam-cli/1.48.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 54, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.48.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 351, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
2022-05-10 11:46:47,802 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'ab23cecb-57e9-4c17-899c-85cc5ea7b038', 'installationId': 'ac70b707-0b71-4d5f-9b3f-69b79b670717', 'sessionId': 'db0d4c72-a196-46b2-9816-522c0ebb067a', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.48.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 163113, 'exitReason': 'DeployFailedError', 'exitCode': 1}}]}
2022-05-10 11:46:48,867 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create/update the stack: oudeploy-stackset, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
```

### Expected result:
SAM should have deployed the StackSet to the accounts in the target AWS Organizations OU in the specified region(s).

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudformation-stackset.html#cfn-cloudformation-stackset-permissionmodel

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Big Sur 11.6.5
6. `sam --version`: `SAM CLI, version 1.48.0`
7. AWS region: us-east-1

**Comment by mndeveci** [comment]
This might be coming from CFN during deployment, can you share a template where we can re-produce the issue?

Or for alternative, if you have this line (`Transform: AWS::Serverless-2016-10-31`) in your template, can you remove and try to re-deploy?

**Comment by jeffmarcinko** [comment]
I removed the ```Transform: AWS::Serverless-2016-10-31``` from the source template and attempted to deploy again.  The stack failed with the same error message:

Here is the stackset template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  HelloWorldStackSet:
    Type: AWS::CloudFormation::StackSet
    Properties:
      AutoDeployment:
        Enabled: true
        RetainStacksOnAccountRemoval: false
      StackSetName: oudeploystackset
      PermissionModel: SERVICE_MANAGED
      Capabilities: 
        - CAPABILITY_IAM
        - CAPABILITY_AUTO_EXPAND
      StackInstancesGroup:
        - DeploymentTargets:
            OrganizationalUnitIds:
              - ou-abc-abcdefghi
          Regions:
            - us-east-1
      TemplateURL: ./build/packaged-template.yaml
    Metadata:
      SamResourceId: oudeploystackset
```


```
---------------------------------------------------------------------------------------------------------------------------------------------
ResourceStatus                      ResourceType                        LogicalResourceId                   ResourceStatusReason              
---------------------------------------------------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS                  AWS::CloudFormation::StackSet       HelloWorldStackSet                  -                                 
CREATE_FAILED                       AWS::CloudFormation::StackSet       HelloWorldStackSet                  Resource handler returned         
                                                                                                            message: "Transform is not        
                                                                                                            supported in SERVICE_MANAGED      
                                                                                                            permission model (Service:        
                                                                                                            CloudFormation, Status Code: 400, 
                                                                                                            Request ID: 2e80eacb-46b0-49ac-   
                                                                                                            bdbc-04f9637b3b90)"               
                                                                                                            (RequestToken: b211c7cd-          
                                                                                                            ac87-3c31-4ba6-3752b702dd2b,      
                                                                                                            HandlerErrorCode: InvalidRequest) 
ROLLBACK_IN_PROGRESS                AWS::CloudFormation::Stack          oudeploy-stackset                   The following resource(s) failed  
                                                                                                            to create: [HelloWorldStackSet].  
                                                                                                            Rollback requested by user. 

```

**Comment by mndeveci** [comment]
Thanks for testing that use case. But since error is coming from CFN deployment and SAM or SAM CLI is not involved in that part, I believe this is coming from CFN side. 

I am resolving this issue for now but feel free to re-open or create a new issue if this problem originated from SAM or SAM CLI.
