### ISSUE TITLE
Error: Can't find application template hello-world-typescript - check valid values in interactive init

### ISSUE THREAD

**Issue by rajansharma3097** [aws/aws-sam-cli#3883]
After upgrading SAM CLI to version 1.50.0 from 1.47.0, `sam init` stopped working for `nodejs16.x` runtime and `Hello World Example TypeScript` template. We are getting the following error:

`Error: Can't find application template hello-world-typescript - check valid values in interactive init`

Environment: Windows 10

Can anyone please help me with this asap?

**Comment by mndeveci** [comment]
I was also able to create the application through interactive flow like below;
```
❯ sam init

You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.

Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
	1 - Hello World Example
	2 - Multi-step workflow
	3 - Serverless API
	4 - Scheduled task
	5 - Standalone function
	6 - Data processing
	7 - Infrastructure event management
	8 - Machine Learning
Template: 1

Use the most popular runtime and package type? (Python and zip) [y/N]: n

Which runtime would you like to use?
	1 - dotnet6
	2 - dotnet5.0
	3 - dotnetcore3.1
	4 - go1.x
	5 - java11
	6 - java8.al2
	7 - java8
	8 - nodejs16.x
	9 - nodejs14.x
	10 - nodejs12.x
	11 - python3.9
	12 - python3.8
	13 - python3.7
	14 - python3.6
	15 - ruby2.7
	16 - rust (provided.al2)
Runtime: 8

What package type would you like to use?
	1 - Zip
	2 - Image
Package type: 1

Based on your selections, the only dependency manager available is npm.
We will proceed copying the template using npm.

Select your starter template
	1 - Hello World Example
	2 - Hello World Example TypeScript
Template: 2

Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: n

Project name [sam-app]: hw-ts-test

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)

    -----------------------
    Generating application:
    -----------------------
    Name: hw-ts-test
    Runtime: nodejs16.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world-typescript
    Output Directory: .

    Next steps can be found in the README file at ./hw-ts-test/README.md


    Commands you can use next
    =========================
    [*] Create pipeline: cd hw-ts-test && sam pipeline init --bootstrap
    [*] Validate SAM template: sam validate
    [*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
```

**Comment by rajansharma3097** [comment]
@mndeveci thanks for your prompt reply. I've tried the first command that you shared but I'm still getting the error that I was getting with `sam init` only. Even I've installed node 16.15.9 version.

`sam init --runtime nodejs16.x --app-template hello-world-typescript --name hello-world-ts --package-type Zip --dependency-manager npm --no-interactive                                                                                                                                                                                

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)                               Error: Can't find application template hello-world-typescript - check valid values in interactive init.`

**Comment by nickadam** [comment]
I had the same problem in windows. I traced the cli and found the git command it's failing on. I was able to fix it by setting git longpaths true.
```
git.exe clone https://github.com/aws/aws-sam-cli-app-templates aws-sam-cli-app-templates                          ─╯
Cloning into 'aws-sam-cli-app-templates'...
remote: Enumerating objects: 5500, done.
remote: Counting objects: 100% (1569/1569), done.
remote: Compressing objects: 100% (430/430), done. eceiving objects:   0% (1/5500)
remote: Total 5500 (delta 1362), reused 1193 (delta 1138), pack-reused 3931
Receiving objects: 100% (5500/5500), 21.08 MiB | 38.89 MiB/s, done.
Resolving deltas: 100% (3686/3686), done.
error: unable to create file dotnetcore3.1/cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet/{{cookiecutter.project_name}}/test/{{cookiecutter.project_name}}.Tests/{{cookiecutter.project_name}}.Tests.csproj: Filename too long
fatal: cannot create directory at 'provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/{{cookiecutter.project_name}}/HelloWorldFunction/src/main/resources/META-INF/native-image/com.amazonaws/aws-lambda-java-core': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

The fix (run from elevated prompt to configure for --system)
```
git config --system core.longpaths true
```

**Comment by nickadam** [comment]
Evidently that was only part of the problem. Setting core.longpaths to true fixed the clone issue but there is another issue with, [shutil.rmtree](https://github.com/aws/aws-sam-cli/blob/main/samcli/lib/utils/git_repo.py#L147). It seems this has problems with long paths as well.

```
PS > & "C:\Program Files\Amazon\AWSSAMCLI\runtime\python.exe"
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import shutil
>>> shutil.rmtree('C:\\Users\\nickadam\\AppData\\Local\\Temp\\tmp3ajhkgd2\\aws-sam-cli-app-templates')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "shutil.py", line 740, in rmtree
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  [Previous line repeated 2 more times]
  File "shutil.py", line 618, in _rmtree_unsafe
  File "shutil.py", line 616, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\nickadam\\AppData\\Local\\Temp\\tmp3ajhkgd2\\aws-sam-cli-app-templates\\dotnetcore3.1\\cookiecutter-aws-sam-quick-start-cloudwatch-events-dotnet\\{{cookiecutter.project_name}}\\test\\{{cookiecutter.project_name}}.Tests\\{{cookiecutter.project_name}}.Tests.csproj'
```

I was able to work around this by creating a C:\tmp folder and setting my TEMP environment variable.

```powershell
mkdir C:\tmp
$Env:TEMP = "C:\tmp"
```

**Comment by mndeveci** [comment]
Can you take a look at what is been suggested in this issue (https://github.com/aws/aws-sam-cli/issues/3781) and if they work for you as well?

If there is another setting that we might recommend customers please let us know so that we can update that issue as well.

For long term, we will be thinking about how to warn this proactively so that customers will have a way to resolve this issue.

**Comment by nickadam** [comment]
@mndeveci yup that worked too. Thanks!

**Comment by mndeveci** [comment]
Thanks for confirming. I will be resolving this and leave the other one open for now. Please let us know if the recommended actions in other issue (https://github.com/aws/aws-sam-cli/issues/3781) is not resolving your problem.
