### ISSUE TITLE
FileNotFoundError during local Lambda test build

### ISSUE THREAD

**Issue by farkas-istvan** [aws/aws-sam-cli#3885]
### Description:
I try to build my project with SAM, but the during the JavaGradleWorkflow:JavaGradleCopyArtifacts it fails. It says it can not find a file, which is actually exist.

### Steps to reproduce:
It is only occure in windows operating system. We created a java 11 gradle project, where we created an API Gateway Request Handler. There is some business code in it, and this hadler was uploaded to AWS Lambda, and we could use it there, and it is working there. Now we want to locally test is with IntelliJ Toolkit, but it can't work out, because of the problem during the build process. Then we tried to build it via command line, with the following command: `sam build Function --template C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\temp-template.yaml --build-dir C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build --debug`.

### Observed result:
The following stacktrace:
`
sam build Function --template C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\temp-template.yaml --build-dir C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build --debug
2022-05-17 15:34:21,643 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-05-17 15:34:21,643 | Using config file: samconfig.toml, config environment: default
2022-05-17 15:34:21,643 | Expand command line arguments to:
2022-05-17 15:34:21,643 | --template_file=C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\temp-template.yaml --build_dir=C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build --resource_logical_id=Function --cache_dir=.aws-sam\cache
2022-05-17 15:34:22,620 | 'build' command is called
2022-05-17 15:34:22,620 | No Parameters detected in the template
2022-05-17 15:34:22,637 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
2022-05-17 15:34:22,652 | 1 stacks found in the template
2022-05-17 15:34:22,652 | No Parameters detected in the template
2022-05-17 15:34:22,652 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
2022-05-17 15:34:22,652 | 1 resources found in the stack
2022-05-17 15:34:22,652 | No Parameters detected in the template
2022-05-17 15:34:22,668 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
2022-05-17 15:34:22,668 | Found Serverless function with name='Function' and CodeUri='C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting'
2022-05-17 15:34:22,668 | --base-dir is not presented, adjusting uri C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting relative to C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\temp-template.yaml
2022-05-17 15:34:22,668 | No Parameters detected in the template
2022-05-17 15:34:22,668 | There is no customer defined id or cdk path defined for resource Function, so we will use the resource logical id as the resource id
Test the latest build changes for Java runtime 'SAM_CLI_BETA_MAVEN_SCOPE_AND_LAYER=1 sam build'. These changes will replace the existing flow on 1st of April 2022. Check https://github.com/aws/aws-sam-cli/issues/3639 for more information.
2022-05-17 15:34:22,683 | Instantiating build definitions
2022-05-17 15:34:22,683 | No previous build graph found, generating new one
2022-05-17 15:34:22,683 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(java11, C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting, Zip, , 628f6844-863b-4fc2-9d5b-b3543105b9d0, {}, {}, x86_64, []), Function: Function(function_id='Function', name='Function', functionname='Function', runtime='java11', memory=512, timeout=29, handler='hu.downelacs.awslambdajavaskeleton.makegreeting.ApiGatewayRequestHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Projects\\hardfew-aws-lambda-java-skeleton-service\\aws-lambda-java-skeleton-make-greeting', environment={'Variables': {'JAVA_TOOL_OPTIONS': '-XX:MaxMetaspaceSize=128m'}}, rolearn=None, layers=[], events=None, metadata={'SamResourceId': 'Function'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-05-17 15:34:22,683 | Building codeuri: C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting runtime: java11 metadata: {} architecture: x86_64 functions: ['Function']
2022-05-17 15:34:22,683 | Building to following folder C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function
2022-05-17 15:34:22,683 | Looking for a supported build workflow in following directories: ['C:\\Projects\\hardfew-aws-lambda-java-skeleton-service\\aws-lambda-java-skeleton-make-greeting', 'C:\\Projects\\hardfew-aws-lambda-java-skeleton-service\\aws-lambda-java-skeleton-make-greeting\\build\\generated\\sources\\annotationProcessor\\java\\main\\.aws-sam']
2022-05-17 15:34:22,683 | Loading workflow module 'aws_lambda_builders.workflows'
2022-05-17 15:34:22,699 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2022-05-17 15:34:22,715 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2022-05-17 15:34:22,715 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2022-05-17 15:34:22,715 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2022-05-17 15:34:22,731 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2022-05-17 15:34:22,746 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2022-05-17 15:34:22,746 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2022-05-17 15:34:22,746 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2022-05-17 15:34:22,762 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2022-05-17 15:34:22,762 | Found workflow 'JavaGradleWorkflow' to support capabilities 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2022-05-17 15:34:23,338 | Running workflow 'JavaGradleWorkflow'
2022-05-17 15:34:23,355 | Running JavaGradleWorkflow:GradleBuild
2022-05-17 15:34:29,741 | JavaGradleWorkflow:GradleBuild succeeded
2022-05-17 15:34:29,741 | Running JavaGradleWorkflow:JavaGradleCopyArtifacts
2022-05-17 15:34:29,741 | Creating target folders at C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\bin
2022-05-17 15:34:29,741 | Copying directory metadata from source (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\bin) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\bin)
2022-05-17 15:34:29,741 | Copying source file (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\bin\aws-lambda-java-skeleton-make-greeting) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\bin\aws-lambda-java-skeleton-make-greeting)
2022-05-17 15:34:29,741 | Copying source file (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\bin\aws-lambda-java-skeleton-make-greeting.bat) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\bin\aws-lambda-java-skeleton-make-greeting.bat)
2022-05-17 15:34:29,757 | Creating target folders at C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu
2022-05-17 15:34:29,758 | Copying directory metadata from source (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\hu) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu)
2022-05-17 15:34:29,758 | Creating target folders at C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs
2022-05-17 15:34:29,758 | Copying directory metadata from source (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\hu\downelacs) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs)
2022-05-17 15:34:29,758 | Creating target folders at C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs\awslambdajavaskeleton
2022-05-17 15:34:29,758 | Copying directory metadata from source (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\hu\downelacs\awslambdajavaskeleton) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs\awslambdajavaskeleton)
2022-05-17 15:34:29,758 | Creating target folders at C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs\awslambdajavaskeleton\makegreeting
2022-05-17 15:34:29,758 | Copying directory metadata from source (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\hu\downelacs\awslambdajavaskeleton\makegreeting) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs\awslambdajavaskeleton\makegreeting)
2022-05-17 15:34:29,758 | Copying source file (C:\Users\user1\AppData\Local\Temp\tmpkctluo8i\4bb0072234e535ca2e544998f2bd95f9e86a7789\build\distributions\lambda-build\hu\downelacs\awslambdajavaskeleton\makegreeting\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class) to destination (C:\Projects\hardfew-aws-lambda-java-skeleton-service\aws-lambda-java-skeleton-make-greeting\build\generated\sources\annotationProcessor\java\main\.aws-sam\build\Function\hu\downelacs\awslambdajavaskeleton\makegreeting\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class)
2022-05-17 15:34:29,758 | JavaGradleWorkflow:JavaGradleCopyArtifacts failed
Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 78, in _copy_artifacts
    self.os_utils.copytree(lambda_build_output, self.artifacts_dir)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java\utils.py", line 44, in copytree
    copytree(source, destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  [Previous line repeated 1 more time]
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 79, in copytree
    shutil.copy2(new_source, new_destination)
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 302, in run
    action.execute()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 71, in execute
    self._copy_artifacts()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 80, in _copy_artifacts
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'
2022-05-17 15:34:29,774 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'ad2db09e-ccdd-4d81-8e92-6c9b90357c1d', 'installationId': 'c5649b1d-57bb-4a33-b9db-c65ebbf7b59b', 'sessionId': '76bbc56a-2c04-473a-97d5-4b61e23764c7', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.47.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 8125, 'exitReason': 'FileNotFoundError', 'exitCode': 255}}]}
2022-05-17 15:34:30,517 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 78, in _copy_artifacts
    self.os_utils.copytree(lambda_build_output, self.artifacts_dir)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java\utils.py", line 44, in copytree
    copytree(source, destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 76, in copytree
    copytree(new_source, new_destination, ignore=ignore, include=include)
  [Previous line repeated 1 more time]
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\utils.py", line 79, in copytree
    shutil.copy2(new_source, new_destination)
  File "shutil.py", line 435, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 302, in run
    action.execute()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 71, in execute
    self._copy_artifacts()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\java_gradle\actions.py", line 80, in _copy_artifacts
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 743, in _build_function_in_process
    builder.build(
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\builder.py", line 164, in build
    return workflow.run()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 96, in wrapper
    func(self, *args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 309, in run
    raise WorkflowFailedError(workflow_name=self.NAME, action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError: JavaGradleWorkflow:JavaGradleCopyArtifacts - [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 47, in mkdir_temp
    yield temp_dir
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 654, in _build_function
    return self._build_function_in_process(
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 760, in _build_function_in_process
    raise BuildError(wrapped_from=ex.__class__.__name__, msg=str(ex)) from ex
samcli.lib.build.exceptions.BuildError: JavaGradleWorkflow:JavaGradleCopyArtifacts - [Errno 2] No such file or directory: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 174, in cli
    do_cli(
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 251, in do_cli
    ctx.run()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 191, in run
    build_result = builder.build()
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 654, in _build_function
    return self._build_function_in_process(
  File "contextlib.py", line 131, in __exit__
  File "c:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 54, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "shutil.py", line 740, in rmtree
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  [Previous line repeated 5 more times]
  File "shutil.py", line 618, in _rmtree_unsafe
  File "shutil.py", line 616, in _rmtree_unsafe
FileNotFoundError: [WinError 3] A rendszer nem találja a megadott elérési utat: 'C:\\Users\\user1\\AppData\\Local\\Temp\\tmpkctluo8i\\4bb0072234e535ca2e544998f2bd95f9e86a7789\\build\\distributions\\lambda-build\\hu\\downelacs\\awslambdajavaskeleton\\makegreeting\\ApiGatewayRequestHandler$PostGreetingRequestParameters$PostGreetingRequestParametersBuilder.class'
`

### Expected result:
SAM should finish the build process without error.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 10 Home [build: 19043.1706]
2. `sam --version`: SAM CLI, version 1.50.0
3. AWS region: eu-central-1
4. Java version: Java Corretto-11.0.15.9.1 (build 11.0.15+9-LTS)

**Comment by torresxb1** [comment]
Thanks for bringing this to our attention! Could you include a basic sample template and handler, and anything else necessary, so that we could try reproducing this?

Also, does this only happen in Windows (i.e. it doesn't happen in MacOs, Linux, etc.), or have you only tried in Windows?

**Comment by farkas-istvan** [comment]
Thank you for the answer! We've tried it on a Mac system and 2 windows computers, and it worked well in MacOs, but the problem came out on the 2 windows systems. I'll send you the template.yml and a handler, but I need a few days. I'll send these on this week. Thank you!

**Comment by farkas-istvan** [comment]
Sorry for the late answer. I tried to reproduce it, but I get a different error now. I created an example project which are very similar to our lambda projects. Could you please check it out, if you could run locally a function on Windows 10 
with SAM 1.50 and with Java Corretto-11.

Here is my project link: https://github.com/farkas-istvan/aws_sam_error_example

Now my current error is:
`sam build Function --template C:\Projects\aws_sam_error_example\module_1\build\generated\sources\annotationProcessor\java\main.aws-sam\temp-template.yaml --build-dir C:\Projects\aws_sam_error_example\module_1\build\generated\sources\annotationProcessor\java\main.aws-sam\build
Error: Template file not found at C:\Projects\aws_sam_error_example\module_1\build\generated\sources\annotationProcessor\java\main.aws-sam\temp-template.yaml`

And the other project has the same error now, which I mentioned previously in the ticket.

**Comment by qingchm** [comment]
"main.aws-sam" I think the current error is due to missing a separator here! main\.aws-sam

**Comment by sriram-mv** [comment]
I'm not able to repro the issue with the template.yaml that you have provided, its referring to built artifacts that do not exist. Were you able to find a solution?

**Comment by farkas-istvan** [comment]
Thank you for your check. We couldn't solve it and we didn't have time to deal with it since then and I apologize for it. For now maybe that would be the best if we would close this issue, and when we will have more resource to collect more and accurate informations, we would create a new ticket or maybe reopen this one.
