### ISSUE TITLE
sam build fails on OSError: [WinError 1920] The file cannot be accessed by the system

### ISSUE THREAD

**Issue by avolcoff** [aws/aws-sam-cli#3906]
OS: Windows 10
Added a python lambda to a template that worked fine with dotnet lambdas
when running "sam build" I'm receiving this error :

```
2022-05-26 16:35:13,258 | Running incremental build for runtime python3.9 for build definition fae9ede7-6965-472a-bc31-5a635d098d4d
2022-05-26 16:35:13,260 | Cache is invalid, running build and copying resources to function build definition of fae9ede7-6965-472a-bc31-5a635d098d4d
2022-05-26 16:35:13,260 | Building codeuri: C:\Users\<USER>\source\repos\Pipeline\src\Lambda\StringToLowerFunction runtime: python3.9 metadata: {} architecture: x86_64 functions: ['StringToLowerFunction']
2022-05-26 16:35:13,261 | Building to following folder C:\Users\<USER>\source\repos\Pipeline\serverless\.aws-sam\build\StringToLowerFunction
2022-05-26 16:35:13,261 | Loading workflow module 'aws_lambda_builders.workflows'
2022-05-26 16:35:13,262 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2022-05-26 16:35:13,315 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '94149d57-a355-4cc1-a553-54e5325f1c91', 'installationId': 'ed21163f-46c1-493d-8670-28eeded60413', 'sessionId': 'a51d3a73-56fa-4209-8bc6-d518cccb00ee', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.50.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 32670, 'exitReason': 'OSError', 'exitCode': 255}}]}
2022-05-26 16:35:14,275 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 174, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 251, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 191, in run
    build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 510, in build
    result.update(super().build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 527, in build_single_function_definition
    return self._cached_build_strategy.build_single_function_definition(build_definition)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 265, in build_single_function_definition
    build_result = self._delegate_build_strategy.build_single_function_definition(build_definition)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 654, in _build_function
    return self._build_function_in_process(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 743, in _build_function_in_process
    builder.build(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\builder.py", line 164, in build
    return workflow.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 66, in wrapper
    valid_path = binary_checker.validator.validate(executable_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\validator.py", line 46, in validate
    p = subprocess.Popen(
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 1920] The file cannot be accessed by the system
```

seems like the build is trying to access a folder that it did not create yet here:
C:\Users\<USER>\source\repos\Pipeline\serverless\.aws-sam\build\StringToLowerFunction

**Comment by avolcoff** [comment]
I now see that the hello world example that is generated using "sam init" also breaks on the same error when I run "sam build" on it

**Comment by mingkun2020** [comment]
Thanks @avolcoff  for reporting the issue, could you provide an example application for us to investigate further?

**Comment by hawflau** [comment]
Hey @avolcoff, could you please check if there's any permission issue to create files or directory in your project folder?

**Comment by hulchenko** [comment]
The error is:
`OSError: [WinError 1920] The file cannot be accessed by the system`

Couple possible solutions:

1. Update or re-install Python with final version
2. Uninstall Python and install directly from Microsoft Store
3. Try changing installation path for Python, avoid using C:\Users\*

**Comment by srikanthreddipalli9** [comment]
I tried the possible solutions mentioned, but had no luck. Still facing the same issue.

"C:\Program Files\Amazon\AWSSAMCLI\bin\sam.cmd" build --template C:\newpyprojects\sldsla\template.yaml --build-dir C:\newpyprojects\sldsla\.aws-sam\build
Building codeuri: C:\newpyprojects\sldsla\slacode runtime: python3.9 metadata: {} architecture: x86_64 functions: ['sdfslapf1']
requirements.txt file not found. Continuing the build without dependencies.
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 182, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 262, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 248, in run
    build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 219, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 75, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 85, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 156, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 655, in _build_function
    return self._build_function_in_process(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 744, in _build_function_in_process
    builder.build(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\builder.py", line 164, in build
    return workflow.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 66, in wrapper
    valid_path = binary_checker.validator.validate(executable_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\validator.py", line 46, in validate
    p = subprocess.Popen(
  File "subprocess.py", line 858, in __init__
  File "subprocess.py", line 1311, in _execute_child
OSError: [WinError 1920] The file cannot be accessed by the system
SAM Build has failed: Command did not exit successfully, exit code: 1
testspf1 has failed: Command did not exit successfully, exit code: 1

**Comment by Larry0ua** [comment]
Seen the same issue locally. It seems that sam tries to execute non-installed Python executable stub Windows creates as a substitute for applications from Windows Store. Try locating `samcli\runtime\Lib\site-packages\aws_lambda_builders\workflows\python_pip\validator.py` and adding `print(cmd)` just before line 46 to see what it is going to execute before failure.

In my case reinstalling Python from Windows Store worked.

**Comment by qingchm** [comment]
@Larry0ua Thanks for the input here! @avolcoff Does the comment help with your issue?

**Comment by arivol** [comment]
uninstalling python from windows and then reinstalling the python 3.9 from Microsoft web store fixed the issue
Thanks!
