### ISSUE TITLE
Bug: Fail building my sam project, other project build successfully 

### ISSUE THREAD

**Issue by yuvalco** [aws/aws-sam-cli#3937]
### Description:
When using 
` sam build --parallel --cached --use-container`
      ModuleNotFoundError: No module named toolz

### Steps to reproduce:
trying to build my project

### Observed result:

```Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-download-gmqoeucq/unification_ded956b4416742f5bef6478314587c79/setup.py", line 5, in <module>
          import unification
        File "/tmp/pip-download-gmqoeucq/unification_ded956b4416742f5bef6478314587c79/unification/__init__.py", line 1, in <module>
          from .core import unify, reify
        File "/tmp/pip-download-gmqoeucq/unification_ded956b4416742f5bef6478314587c79/unification/core.py", line 3, in <module>
          from toolz.compatibility import iteritems, map
      ModuleNotFoundError: No module named 'toolz'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/var/lang/bin/python3.8 -m pip install --upgrade pip' command.
```

I tried to upgrading pip, install, uninstall, python, sam cli, and all sorts of things but none seems to work.
sam cli uses python that it's install on it"s own and I also can't seem to upgrade it's pip, but I am not sure that really the problem here since other sam projects works just fine. 

### Expected result:

successfully building my project.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS Monterey 12.4 chip m1
2. `sam --version`:1.51.0
3. AWS region:us-east-1

`Add --debug flag to command you are running`

**Comment by yuvalco** [comment]
Seems like a problem with requirements.txt
