### ISSUE TITLE
Bug: Cannot use layers with !Get and !GetAtt in the same function

### ISSUE THREAD

**Issue by Art-S-D** [aws/aws-sam-cli#3983]
### Description:

I tried to create a lambda using this template:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  ArnSentryLayer:
    Type: String
    Default: arn:aws:lambda:eu-west-1:943013980633:layer:SentryPythonServerlessSDK:18

Resources:
  AwsLambdaPowertoolsPythonLayer:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:eu-west-1:057560766410:applications/aws-lambda-powertools-python-layer-extras
        SemanticVersion: 1.25.6
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: FunctionName
      CodeUri: lambda/
      Handler: api.lambda_handler
      Runtime: python3.9
      Architectures:
        - arm64
      Layers:
        - !GetAtt AwsLambdaPowertoolsPythonLayer.Outputs.LayerVersionArn
        - !Ref ArnSentryLayer
```

### Observed result:

I get the following error:

```
Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 829, in __call__
  File "click/core.py", line 782, in main
  File "click/core.py", line 1259, in invoke
  File "click/core.py", line 1066, in invoke
  File "click/core.py", line 610, in invoke
  File "click/decorators.py", line 73, in new_func
  File "click/core.py", line 610, in invoke
  File "samcli/lib/telemetry/metric.py", line 166, in wrapped
  File "samcli/lib/telemetry/metric.py", line 124, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 87, in wrapper
  File "samcli/commands/build/command.py", line 201, in cli
  File "samcli/commands/build/command.py", line 260, in do_cli
  File "samcli/commands/build/build_context.py", line 166, in __enter__
  File "samcli/commands/build/build_context.py", line 189, in set_up
  File "samcli/lib/providers/sam_function_provider.py", line 68, in __init__
  File "samcli/lib/providers/sam_function_provider.py", line 222, in _extract_functions
  File "samcli/lib/providers/sam_function_provider.py", line 542, in _parse_layer_info
  File "samcli/lib/providers/sam_function_provider.py", line 688, in _locate_layer_from_ref
samcli.lib.providers.exceptions.InvalidLayerReference: Layer References need to be of type 'AWS::Serverless::LayerVersion' or 'AWS::Lambda::LayerVersion'
[2086] Failed to execute script __main__
```

It works if I only use the lambda powertools layer or if I only use the sentry layer, but not when i try to use both.

### Expected result:

I should be able to create my lambda with these two layers

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows 10 (WSL)
2. `sam --version`: 1.52.0
3. AWS region: eu-west-1

**Comment by Art-S-D** [comment]
Found a workaround for this, which is to use `!Sub ${ArnSentryLayer}` instead of `!Ref ArnSentryLayer`
