### ISSUE TITLE
Bug: Error attempting to publish a template containing an AWS::Serverless::Function that has a FunctionUrlConfig

### ISSUE THREAD

**Issue by mbklein** [aws/aws-sam-cli#3987]
### Note

It is possible that this is an issue with the [Serverless Application Repository CreateApplication API](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/applications.html#CreateApplication) itself, or maybe the python SDK. But since `FunctionUrlConfig` is a documented part of the `AWS::Serverless::Function` model, I'd expect it to work all the way up the stack. If this bug report belongs somewhere other than in the SAM CLI, feel free to point the way and I'll report it there instead/also.

### Description:

I have a SAM template that contains a `AWS::Serverless::Function` resource. The resource has a [`FunctionUrlConfig`](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-functionurlconfig.html). `sam build`, `sam validate`, and `sam deploy` work just fine, and I am able to deploy a working copy of my application and access it via the Lambda function URL.

However, when I try to `sam publish` my application to the Serverless Application Repository, I get an error saying `property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function`.

### Steps to reproduce:

Try to `sam publish` an application that contains an `AWS::Serverless::Function` resource with a `FunctionUrlConfig` configured.

### Observed result:

```
$ sam publish --debug --profile staging --template package.yml
2022-06-21 17:54:20,266 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-06-21 17:54:20,267 | Using config file: samconfig.toml, config environment: default
2022-06-21 17:54:20,267 | Expand command line arguments to:
2022-06-21 17:54:20,267 | --template_file=/path/to/my/app/package.yml 
Publish Failed
2022-06-21 17:54:21,493 | Failed to publish application to serverlessrepo
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/serverlessrepo/publish.py", line 45, in publish_application
    response = sar_client.create_application(**request)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the CreateApplication operation: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [IiifFunction] is invalid. property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/samcli/commands/publish/command.py", line 86, in do_cli
    publish_output = publish_application(template_data)
  File "/usr/local/Cellar/aws-sam-cli/1.52.0/libexec/lib/python3.8/site-packages/serverlessrepo/publish.py", line 50, in publish_application
    raise _wrap_client_error(e)
serverlessrepo.exceptions.ServerlessRepoClientError: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [IiifFunction] is invalid. property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function
2022-06-21 17:54:21,497 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '38261a43-0e04-4e1b-bd61-872b25958835', 'installationId': 'a036baf0-1f1e-49c6-925d-51b3e9736150', 'sessionId': '5ec802e3-f043-4891-9750-b3aaf633832d', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.52.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam publish', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 1230, 'exitReason': 'ServerlessRepoClientError', 'exitCode': 1}}]}
2022-06-21 17:54:21,826 | Telemetry response: 200
Error: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [IiifFunction] is invalid. property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function
Please follow the instructions in https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-publishing-applications.html
```

### Expected result:

I expected the application to be published to the Serverless Application Repository.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 12.3.1
2. `sam --version`: `SAM CLI, version 1.52.0` (also attempted using nightly build version `1.52.0.dev202206200903`)
3. AWS region: `us-east-1`

**Comment by mbklein** [comment]
I have determined (by packaging the app with `sam package` and then trying to publish with `aws serverlessrepo create-application` that the issue is upstream of `sam-cli`.

```
$ aws serverlessrepo create-application ...[required parameters]... --template-body file://./package.yml

An error occurred (BadRequestException) when calling the CreateApplication operation: Invalid Serverless Application Specification document. Number of errors found: 1. Errors: Resource with id [IiifFunction] is invalid. property FunctionUrlConfig not defined for resource of type AWS::Serverless::Function
```

Closing this issue.
