### ISSUE TITLE
SAM Accelerate fails to resolve dependencies during build

### ISSUE THREAD

**Issue by dgard1981** [aws/aws-sam-cli#4054]

**Comment by jfuss** [comment]
@dgard1981 Thanks for the issue. So not super clear why this is happening as this should just work. PyPi doesn't look like it has an outage but maybe there was some failures going on. Could you retry?

Another thing to check: Is `pip` installed for `python3.8`?

> Note that requests is installed and available to my chosen runtime, python3.8.

This doesn't matter, as this is installed on your machine and for your system which may not be compatible with Lambda. So what our builder does is tries to download or build the dependencies that specifically target Lambda. The error you are getting is saying that process failed (though not the best error message...).

**Comment by dgard1981** [comment]
@jfuss, Thanks for your reply.

Understood that it doesn't matter about package availability on my local system. I thought that would be the case but mentioned it just in case.

With regards to the issue... It's not just a recent issue, but rather one that I've had since the beginning with SAM. It's not just `sync` either, but `build` to. The difference is thought that I can use a container by specifying `build -u`, and that works.

I'm not connected to any corporate VPN, which I know can sometimes cause unexpected issues with these sort of things.

And to confirm, `pip` is definitely installed for `python3.8`.

Do you have any other ideas about what may be causing this issue?

**Comment by jfuss** [comment]
@dgard1981 It would make sense this happens outside of `sam sync` and also in `sam build`, as the logic is shared. I haven't experienced this myself. The only time I have had something similar was throttling applied by PyPi but I thought that had a different error message. 

I'll connect with the team today to see if others have come across this. 

In the meantime, does this happen all the time or just "randomly"?

Something to try:
Can you run the `pip` command we are using in our builders. From the output it looks like `pip download -r /home/dgard/sam-tutorial/hello_world/requirements.txt --dest /tmp/tmpba33lles --exists-action i`? You can change the `--dest` value to something else. What I am after is 1) Does this command actually work 2) What is the contents of the `--dest` folder (which should include dependencies). 

I am actually surprised the `pip` commad doesn't have the `whl` we are after. Will take a deeper look at https://github.com/aws/aws-lambda-builders which has all our building logic for different languages.

**Comment by jfuss** [comment]
@dgard1981 That is good to hear! I am going to leave this open for now and assign to myself so I have a reminder to see what we can improve in the output here. I thought we surface pip details but this is something we should improve so others aren't stuck wondering as well.

**Comment by adammabrouk** [comment]
I think I'm experiencing the same problem with `sam build --parallel` and it seems to behave randomly, in the beginning it was rare but recently it started to be very often ( 2 out of each 5 builds fail ).

I get this message when it fails : 
```
Running PythonPipBuilder:CopySource

Build Failed
Error: PythonPipBuilder:ResolveDependencies - WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/download.py", line 135, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/legacy_resolve.py", line 265, in _get_abstract_dist_for
    return self.preparer.prepare_editable_requirement(req)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 554, in prepare_editable_requirement
    abstract_dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 95, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/sdist.py", line 40, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 568, in prepare_metadata
    self._set_requirement()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 386, in _set_requirement
    if isinstance(parse_version(self.metadata["Version"]), Version):
  File "/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl/packaging/version.py", line 56, in parse
    return Version(version)
  File "/usr/share/python-wheels/packaging-20.3-py2.py3-none-any.whl/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```
**Below is a list of all the libraries required across all my lambdas ( In case you can identify if the problem comes from a specific one )**

```
dataclasses-json==0.5.2
pytest==6.1.2
numpy==1.20.1
boto3==1.16.25
moto==1.3.16
pytest-mock==3.5.1
requests-mock==1.8.0
pandas==1.3.4
opencv-python-headless==4.5.5.62
pillow==9.0.1
pycrypto==2.6.1
aiohttp==3.8.1
aiohttp-retry==2.5.2
requests==2.25.1
```

**These are my environment details:**
- OS: WSL Ubuntu 20.04 
- SAM CLI version: 1.53.0
- Python version : 3.8
- Pip Version : 22.2.2

**Comment by e88z4** [comment]
I am having this issue as well with --use-container option. The sam build works fine locally with my virtual environment. 

```
Starting Build use cache
Starting Build inside a container
Cache is invalid, running build and copying resources for following functions (CreateSecurityGroupFunction)
Building codeuri: /home/felix/bitbucket/sam-af-augmentation-create-security-group/security-group-creation-app/create_security_group_function runtime: python3.11 metadata: {} architecture: x86_64 functions: CreateSecurityGroupFunction

Fetching public.ecr.aws/sam/build-python3.11:latest-x86_64 Docker container image......
Mounting /home/felix/bitbucket/sam-af-augmentation-create-security-group/security-group-creation-app/create_security_group_function as /tmp/samcli/source:ro,delegated, inside runtime container

Build Failed
Running PythonPipBuilder:ResolveDependencies
Error: PythonPipBuilder:ResolveDependencies - Could not satisfy the requirement: requests
```

I have sam cli version 1.93.0
