### ISSUE TITLE
Bug: local start-api with Layers doesn't work

### ISSUE THREAD

**Issue by SantjagoCorkez** [aws/aws-sam-cli#4095]
### Description:

As of https://aws.amazon.com/blogs/compute/working-with-aws-lambda-and-lambda-layers-in-aws-sam/ I'm trying the same approach for development both layers and lambda functions locally.

The `template.yaml` so far looks like:
```
Resources:
  DBSupportLayer:
    Type: AWS::ServerLess::LayerVersion
    Properties:
      LayerName: DataBase_Support_Layer
      Description: DB (Aurora::PostgreSQL, SQLAlchemy, Alembic) support layer
      ContentUri: ../layers/support/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy: Retain
  SupplementalItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/src/lambdas/supplemental_items/
      Handler: lambda_handler.lambda_handler
      Layers:
        - !Ref DBSupportLayer
      Runtime: python3.9
      Environment:
        Variables:
          PG_ENGINE_URL: ""
      Events:
        SupplementalItemsGet:
          Type: Api
          Properties:
            Path: "/supplemental_items"
            Method: get
```

When I start the API locally the output is:
```
2022-08-02 17:14:36,752 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-08-02 17:14:36,753 | Using config file: samconfig.toml, config environment: qa
2022-08-02 17:14:36,753 | Expand command line arguments to:
2022-08-02 17:14:36,753 | --template_file=/.../template.yaml --env_vars=env_vars.json --docker_network=bridge --host=127.0.0.1 --port=3000 --static_dir=public --layer_cache_basedir=/home/andy/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2022-08-02 17:14:36,801 | local start-api command is called
2022-08-02 17:14:36,825 | Collected default values for parameters: {'Env': 'qa'}
2022-08-02 17:14:36,837 | There is no customer defined id or cdk path defined for resource DBSupportLayer, so we will use the resource logical id as the resource id
2022-08-02 17:14:36,838 | There is no customer defined id or cdk path defined for resource SupplementalItemsFunction, so we will use the resource logical id as the resource id
2022-08-02 17:14:36,839 | 0 stacks found in the template
2022-08-02 17:14:36,839 | Collected default values for parameters: {'Env': 'qa'}
2022-08-02 17:14:36,850 | There is no customer defined id or cdk path defined for resource DBSupportLayer, so we will use the resource logical id as the resource id
2022-08-02 17:14:36,851 | There is no customer defined id or cdk path defined for resource SupplementalItemsFunction, so we will use the resource logical id as the resource id
2022-08-02 17:14:36,852 | 7 resources found in the stack
2022-08-02 17:14:36,856 | Found Serverless function with name='SupplementalItemsFunction' and CodeUri='lambda/src/lambdas/supplemental_items/'
2022-08-02 17:14:36,856 | --base-dir is not presented, adjusting uri lambda/src/lambdas/supplemental_items/ relative to /.../template.yaml
2022-08-02 17:14:36,867 | Found '1' API Events in Serverless function with name 'SupplementalItemsFunction'
2022-08-02 17:14:36,867 | Detected Inline Swagger definition
2022-08-02 17:14:36,868 | Lambda function integration not found in Swagger document at path='/supplemental_items' method='get'
2022-08-02 17:14:36,868 | Found '0' APIs in resource 'ServerlessRestApi'
2022-08-02 17:14:36,868 | Removed duplicates from '0' Explicit APIs and '6' Implicit APIs to produce '6' APIs
2022-08-02 17:14:36,868 | 4 APIs found in the template
2022-08-02 17:14:36,875 | Mounting SupplementalItemsFunction at http://127.0.0.1:3000/supplemental_items [GET]
2022-08-02 17:14:36,875 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. You only need to restart SAM CLI if you update your AWS SAM template
2022-08-02 17:14:36,875 | Localhost server is starting up. Multi-threading = True
2022-08-02 17:14:36  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2022-08-02 17:14:44,817 | Constructed String representation of Event to invoke Lambda. Event: {"body": null, "headers": {"Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "Accept-Encoding": "gzip, deflate, br", "Accept-Language": "en-US,en;q=0.9", "Cache-Control": "max-age=0", "Connection": "keep-alive", "Host": "127.0.0.1:3000", "Sec-Ch-Ua": "\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\"", "Sec-Ch-Ua-Mobile": "?0", "Sec-Ch-Ua-Platform": "\"Windows\"", "Sec-Fetch-Dest": "document", "Sec-Fetch-Mode": "navigate", "Sec-Fetch-Site": "none", "Sec-Fetch-User": "?1", "Upgrade-Insecure-Requests": "1", "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9"], "Cache-Control": ["max-age=0"], "Connection": ["keep-alive"], "Host": ["127.0.0.1:3000"], "Sec-Ch-Ua": ["\".Not/A)Brand\";v=\"99\", \"Google Chrome\";v=\"103\", \"Chromium\";v=\"103\""], "Sec-Ch-Ua-Mobile": ["?0"], "Sec-Ch-Ua-Platform": ["\"Windows\""], "Sec-Fetch-Dest": ["document"], "Sec-Fetch-Mode": ["navigate"], "Sec-Fetch-Site": ["none"], "Sec-Fetch-User": ["?1"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/supplemental_items", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "127.0.0.1:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/supplemental_items", "protocol": "HTTP/1.1", "requestId": "8f712e38-bff9-4b19-bb27-3a05c31de406", "requestTime": "02/Aug/2022:22:14:36 +0000", "requestTimeEpoch": 1659478476, "resourceId": "123456", "resourcePath": "/supplemental_items", "stage": "Prod"}, "resource": "/supplemental_items", "stageVariables": null, "version": "1.0"}
2022-08-02 17:14:44,817 | Found one Lambda function with name 'SupplementalItemsFunction'
2022-08-02 17:14:44,817 | Invoking lambda_handler.lambda_handler (python3.9)
2022-08-02 17:14:44,817 | Environment variables overrides data is standard format
2022-08-02 17:14:44,817 | Loading AWS credentials from session with profile 'None'
2022-08-02 17:14:44,826 | Resolving code path. Cwd=/..., CodeUri=/.../lambda/src/lambdas/supplemental_items
2022-08-02 17:14:44,826 | Resolved absolute path to code is /.../lambda/src/lambdas/supplemental_items
2022-08-02 17:14:44,830 | Code /.../lambda/src/lambdas/supplemental_items is not a zip/jar file
2022-08-02 17:14:44,830 | Cleaning all decompressed code dirs
2022-08-02 17:14:44,830 | Exception on /supplemental_items [GET]
Traceback (most recent call last):
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/providers/provider.py", line 276, in _compute_layer_name
    _, layer_name, layer_version = arn.rsplit(":", 2)
ValueError: not enough values to unpack (expected 3, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/andy/env/p39/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/apigw/local_apigw_service.py", line 357, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/telemetry/metric.py", line 230, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/lambdafn/runtime.py", line 177, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/docker/lambda_container.py", line 93, in __init__
    image = LambdaContainer._get_image(
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/docker/lambda_container.py", line 236, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/docker/lambda_image.py", line 136, in build
    downloaded_layers = self.layer_downloader.download_all(layers, self.force_image_build)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/layers/layer_downloader.py", line 77, in download_all
    layer_dirs.append(self.download(layer, force))
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/local/layers/layer_downloader.py", line 102, in download
    layer_path = Path(self.layer_cache).resolve().joinpath(layer.name)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/providers/provider.py", line 327, in name
    self._name = LayerVersion._compute_layer_name(self.is_defined_within_template, self.arn)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/providers/provider.py", line 278, in _compute_layer_name
    raise InvalidLayerVersionArn(arn + " is an Invalid Layer Arn.") from ex
samcli.commands.local.cli_common.user_exceptions.InvalidLayerVersionArn: DBSupportLayer is an Invalid Layer Arn.
2022-08-02 17:14:44 127.0.0.1 - - [02/Aug/2022 17:14:44] "GET /supplemental_items HTTP/1.1" 502 -
```

### Steps to reproduce:
The same as invoking a local API with a layer as of current official instruction but for Python

### Observed result:
Local layers either `.zip` packages or directories are not attached to locally running API; Layers aren't resolved correctly in a local environment.

### Expected result:
Locally provided Layer (either a packaged ZIP or a raw directory) attached to locally running APIs

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Linux Ubuntu VERSION="20.04.4 LTS (Focal Fossa)"
2. `sam --version`: SAM CLI, version 1.53.0
3. AWS region: N/A

**Comment by jfuss** [comment]
@SantjagoCorkez This should work and should be caught by https://github.com/aws/aws-sam-cli/blob/ff85336ee995c98d3bcabfbdf2d9c156d5fc111e/samcli/lib/providers/provider.py#L272

Are you using `sam build` at all? If so, did you run `sam build` after any changes to code or the template?

**Comment by SantjagoCorkez** [comment]
Sure, I did.

```
$ ~/env/p39/bin/sam build --help
Usage: sam build [OPTIONS] [RESOURCE_LOGICAL_ID]

  Use this command to build your AWS Lambda Functions source code to
  generate artifacts that target AWS Lambda's execution environment.

  Supported Resource Types
  ------------------------
  1. AWS::Serverless::Function

  2. AWS::Lambda::Function

  Supported Runtimes
```

Layers are not supported by `sam build` command.

The output is:
```
$ ~/env/p39/bin/sam build
Your template contains a resource with logical ID "ServerlessRestApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
Building codeuri: /.../lambda/src/lambdas/supplemental_items runtime: python3.9 metadata: {} architecture: x86_64 functions: SupplementalItemsFunction
requirements.txt file not found. Continuing the build without dependencies.
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
[*] Deploy: sam deploy --guided
```

I've searched thoroughly through my template and found nothing about the warning displayed at the beginning of the `sam build` command output.

**Comment by SantjagoCorkez** [comment]
This is the resulting structure:

```
$ ls -l .aws-sam
total 4
drwxrwxrwx 1 andy andy  512 Aug  3 12:31 build
-rwxrwxrwx 1 andy andy 1372 Aug  3 12:31 build.toml
drwxrwxrwx 1 andy andy  512 Aug  2 15:47 deps
```

```
$ ls -l .aws-sam/build
total 5
drwxrwxrwx 1 andy andy  512 Aug  3 12:31 SupplementalItemsFunction
-rwxrwxrwx 1 andy andy 5844 Aug  3 12:31 template.yaml
```

```
$ ls -l .aws-sam/build/SupplementalItemsFunction/
total 0
-rwxrwxrwx 1 andy andy 435 Aug  3 10:29 lambda_handler.py
```

```
$ ls -l .aws-sam/deps/
total 0
```

**Comment by jfuss** [comment]
@SantjagoCorkez Layers are support by `sam build` but looks like that help text needs to be updated. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html

This should work. Let me build out an example locally to try this out more concretely. 

We do have tests for this case: https://github.com/aws/aws-sam-cli/blob/develop/tests/integration/local/invoke/test_integrations_cli.py#L741 unless something happened recently that broke them (and we didn't catch it).

**Comment by jfuss** [comment]
@SantjagoCorkez Is the template you provided above the one at `.aws-sam/build/template.yaml`?

**Comment by jfuss** [comment]
I think I noticed the issue. In your template you have `Type: AWS::ServerLess::LayerVersion` but should be `Type: AWS::Serverless::LayerVersion` (no capital L in Serverless)

**Comment by SantjagoCorkez** [comment]
I run it as following:

`~/env/p39/bin/sam build -t scratch/template.yaml -s .`

The contents of `scratch/template.yaml`:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Desc
Globals:
  Function:
    Timeout: 120
    MemorySize: 128

Parameters:
  Env:
    Type: String
    Default: qa
    AllowedValues:
      - qa
      - dev
      - prod
    Description: Enter the Environment name to deploy into.

Resources:
  DBSupportLayer:
    Type: AWS::ServerLess::LayerVersion
    Properties:
      LayerName: DB_Support_Layer
      Description: DB (Aurora::PostgreSQL, SQLAlchemy, Alembic) support layer
      ContentUri: ../layers/db_support/
      CompatibleRuntimes:
        - python3.9
      CompatibleArchitectures:
        - x86_64
      RetentionPolicy: Retain

  APILayer:
    Type: AWS::ServerLess::LayerVersion
    Properties:
      LayerName: APILayer
      Description: API shared code layer
      ContentUri: ../layers/shared/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Retain

  SupplementalItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/src/lambdas/supplemental_items/
      Handler: lambda_handler.lambda_handler
      Layers:
        - !Ref DBSupportLayer
        - !Ref APILayer
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSDataWrangler-Python39:9
      Runtime: python3.9
      Environment:
        Variables:
          PG_ENGINE_URL: ""
      Events:
        SupplementalItemsGet:
          Type: Api
          Properties:
            Path: "/supplemental_items"
            Method: get

Outputs:
  SupplementalItemsFunction:
    Description: "Supplemental Items Lambda Function ARN"
    Value: !GetAtt SupplementalItemsFunction.Arn
  SupplementalItemsFunctionIamRole:
    Description: "Implicit IAM Role created for Supplemental Items  function"
    Value: !GetAtt SupplementalItemsFunctionRole.Arn
  DBSupportLayer:
    Value: !GetAtt DBSupportLayer.Arn
  DBSupportLayerIamRole:
    Value: !GetAtt DBSupportLayerRole.Arn
  APILayer:
    Value: !GetAtt APILayer.Arn
  APILayerIamRole:
    Value: !GetAtt APILayerRole.Arn
```

The output if I point to a layer explicitly:
```
$ ~/env/p39/bin/sam build -t scratch/template.yaml -s . DBSupportLayer
Your template contains a resource with logical ID "ServerlessRestApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
DBSupportLayer not found. Possible options in your template: ['SupplementalItemsFunction']
Traceback (most recent call last):
  File "/home/andy/env/p39/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/command.py", line 182, in cli
    do_cli(
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/command.py", line 262, in do_cli
    ctx.run()
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/build_context.py", line 227, in run
    self.get_resources_to_build(),
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/build_context.py", line 215, in get_resources_to_build
    return self.resources_to_build
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/build_context.py", line 425, in resources_to_build
    self.collect_build_resources(self._resource_identifier)
  File "/home/andy/env/p39/lib/python3.9/site-packages/samcli/commands/build/build_context.py", line 467, in collect_build_resources
    raise ResourceNotFound(f"Unable to find a function or layer with name '{resource_identifier}'")
samcli.local.lambdafn.exceptions.ResourceNotFound: Unable to find a function or layer with name 'DBSupportLayer'
```

**Comment by SantjagoCorkez** [comment]
> I think I noticed the issue. In your template you have `Type: AWS::ServerLess::LayerVersion` but should be `Type: AWS::Serverless::LayerVersion` (no capital L in Serverless)

Thanks. Did the trick. I've missed a typo there.

**Comment by SantjagoCorkez** [comment]
The issue is void since the reason is a typo.
