### ISSUE TITLE
SAM validate resulting in botocore.parsers.ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed: b''

### ISSUE THREAD

**Issue by kevendi** [aws/aws-sam-cli#4106]
### Description:

I am attempting to run "sam deploy" to deploy these sample SAM projects - 

- Hello World Example
- Serverless API

The error I receive is a follows - 

`Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\cdk_support_decorators.py", line 38, in wrapped
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 39, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\validate.py", line 61, in do_cli
    validator.is_valid()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\validate\lib\sam_template_validator.py", line 58, in is_valid
    managed_policy_map = self.managed_policy_loader.load()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\translator\managed_policy_translator.py", line 35, in load
    self._load_policies_from_iam()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\metrics\method_decorator.py", line 96, in wrapper_cw_timer
    exec_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samtranslator\translator\managed_policy_translator.py", line 27, in _load_policies_from_iam
    for page in page_iterator:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\client.py", line 898, in _make_api_call
    http, parsed_response = self._make_request(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\client.py", line 921, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\endpoint.py", line 199, in _send_request
    success_response, exception = self._get_response(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\endpoint.py", line 241, in _get_response
    success_response, exception = self._do_get_response(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\endpoint.py", line 308, in _do_get_response
    parsed_response = parser.parse(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\parsers.py", line 249, in parse
    parsed = self._do_error_parse(response, shape)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\parsers.py", line 556, in _do_error_parse
    root = self._parse_xml_string_to_dom(xml_contents)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\parsers.py", line 505, in _parse_xml_string_to_dom
    raise ResponseParserError(
botocore.parsers.ResponseParserError: Unable to parse response (no element found: line 1, column 0), invalid XML received. Further retries may succeed:
b''
`

I also noticed the same error is received when using "sam validate". I have verified that the YAML is successful for both template YAML files.

### Steps to reproduce:
I am using - 
Python 3.9.11
SAM CLI version 1.53.0
AWS CLI version 2.6.3
Windows 10
Error is recived when running sam validate or sam deploy commands within the Hello World and Serverless API template projects.

### Expected result:
Successful creation/deployment of SAM stack to AWS

**Comment by jfuss** [comment]
@kevendi Does this still happen? From the output, it looks like this is happening from calling IAM and Boto3 is failing on response. Not sure if there was a service issue going on at this time, but can't repro on my side.

**Comment by kevendi** [comment]
@jfuss Hi, I was able to get this working. My AWS creds file had an error in the access key. This can be closed. Thanks.

**Comment by jfuss** [comment]
@kevendi Glad you got it resolved.
