### ISSUE TITLE
Bug: AWS Sam Hello World Failed with AdministratorAccess

### ISSUE THREAD

**Issue by rayjan0114** [aws/aws-sam-cli#4109]
### Description:
I have some templates that fail to work with sam, but work with Cloudformation GUI Retry.
I tried a lot of things and it turns out that I cannot even work with Hello World example now.
I am using my own account with AdministratorAccess policy

### Steps to reproduce:
`sam init`
```
Which template source would you like to use?
	1 - AWS Quick Start Templates
	2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
	1 - Hello World Example
	2 - Multi-step workflow
	3 - Serverless API
	4 - Scheduled task
	5 - Standalone function
	6 - Data processing
	7 - Infrastructure event management
	8 - Machine Learning
Template: 1

Use the most popular runtime and package type? (Python and zip) [y/N]: y

Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: y
```

`cd sam-app; sam build`
Build Succeeded

`sam deploy --guided --profile myprofile --debug`

### Observed result:
```
2022-08-10 00:11:16,547 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-08-10 00:11:16,547 | Using config file: samconfig.toml, config environment: default
2022-08-10 00:11:16,547 | Expand command line arguments to:
2022-08-10 00:11:16,547 | --guided --template_file=/Users/raychang/test/sam-app/.aws-sam/build/template.yaml --fail_on_empty_changeset --stack_name=sam-app
2022-08-10 00:11:16,715 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction

Configuring SAM deploy
======================

	Looking for config file [samconfig.toml] :  Not found

	Setting default arguments for 'sam deploy'
	=========================================
	Stack Name [sam-app]:
	AWS Region [ap-northeast-1]: eu-west-2
2022-08-10 00:11:26,144 | No Parameters detected in the template
2022-08-10 00:11:26,164 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-08-10 00:11:26,164 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-08-10 00:11:26,165 | 0 stacks found in the template
	#Shows you resources changes to be deployed and require a 'Y' to initiate deploy
	Confirm changes before deploy [y/N]: y
	#SAM needs permission to be able to create roles to connect to the resources in your template
	Allow SAM CLI IAM role creation [Y/n]: y
	#Preserves the state of previously provisioned resources when an operation fails
	Disable rollback [y/N]: y
2022-08-10 00:11:28,912 | No Parameters detected in the template
2022-08-10 00:11:28,927 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2022-08-10 00:11:28,927 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-08-10 00:11:28,927 | 2 resources found in the stack
2022-08-10 00:11:28,927 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2022-08-10 00:11:28,927 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to /Users/raychang/test/sam-app/.aws-sam/build/template.yaml
2022-08-10 00:11:28,927 | Detected Inline Swagger definition
2022-08-10 00:11:28,927 | Auth checks done on swagger are not exhaustive!
	HelloWorldFunction may not have authorization defined, Is this okay? [y/N]: y
2022-08-10 00:11:31,005 | 2 resources found in the stack
2022-08-10 00:11:31,006 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2022-08-10 00:11:31,006 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to /Users/raychang/test/sam-app/.aws-sam/build/template.yaml
2022-08-10 00:11:31,006 | No function or layer definition found with code sign config, skipping
	Save arguments to configuration file [Y/n]: y
	SAM configuration file [samconfig.toml]:
	SAM configuration environment [default]:

	Looking for resources needed for deployment:
2022-08-10 00:11:34,237 | Managed S3 stack [aws-sam-cli-managed-default] not found. Creating a new one.
	Creating the required resources...
2022-08-10 00:12:25,833 | Failed to create managed resources
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/managed_cloudformation_stack.py", line 110, in _create_or_get_stack
    stack = _create_stack(
  File "/usr/local/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/managed_cloudformation_stack.py", line 183, in _create_stack
    stack_waiter.wait(StackName=stack_id, WaiterConfig={"Delay": 15, "MaxAttempts": 60})
  File "/usr/local/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 55, in wait
    Waiter.wait(self, **kwargs)
  File "/usr/local/Cellar/aws-sam-cli/1.53.0/libexec/lib/python3.8/site-packages/botocore/waiter.py", line 375, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_FAILED" at least once
2022-08-10 00:12:25,839 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '5ba2cca6-39b8-41e4-96a9-6aefe1e2005d', 'installationId': '570946b8-39db-409d-9310-f7fd3c2ad3df', 'sessionId': '490b6aa0-1755-4526-a985-1958039984eb', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.53.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 69293, 'exitReason': 'ManagedStackError', 'exitCode': 1}}]}
2022-08-10 00:12:26,547 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create managed resources: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_FAILED" at least once
```

![image](https://user-images.githubusercontent.com/47523852/183708041-abd99208-5168-418a-a614-ea8765a42b4f.png)

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS-12.1-x86_64-i386-64bit
2. `sam --version`: 1.53.0
3. AWS region: eu-west-2

### Other things I have tried
 1. brew install aws-sam-cli again
 2. delete cloudformation stack and sam deploy -g again
 3. reset AWS credential with a new token and key
 4. try using sam installed by either x86 brew and arm brew (I am using M1 mac)
 5. upgrade aws-cli

**Comment by jfuss** [comment]
@rayjan0114 Are you sure the policy attached on the profile you were using is AdministratorAccess?

I just tried in a fresh region in a personal account and everything works as expected. Given the failure in CloudFormation, it doesn't appear you have access for operations on S3 (DeleteBucketPolicy or PutBucketPolicy).

**Comment by Wolven531** [comment]
Just got this today, and landed on this issue. Clean install of AWS SAM, trying to setup a NodeJS v. 16 hello world app.

Environment

- Windows 11 (PowerShell)
- SAM CLI v. 1.53.0

Output

![image](https://user-images.githubusercontent.com/2125913/184431797-6382e49a-be5a-4467-a3e6-f6cd81ca4dda.png)

![image](https://user-images.githubusercontent.com/2125913/184431681-612dcb27-8316-479a-a1a0-25945b39342e.png)

![image](https://user-images.githubusercontent.com/2125913/184431701-e5ae0f8e-9e53-4fd4-aa6a-419c2799960f.png)

**Comment by Wolven531** [comment]
It's worth noting that after changing the readonly attribute of the `AWS SAM` directory, some service reverts the change and re-applies the readonly attribute - which is likely contributing to (if not the sole cause) of this issue

![image](https://user-images.githubusercontent.com/2125913/184432884-eeb2102d-31a0-4321-bb78-f2465f0eadab.png)

**Comment by Wolven531** [comment]
Searching around a bit, I found this fix for my issue (which is specific to PowerShell users) - https://github.com/aws/aws-sam-cli/issues/4031#issuecomment-1183633630

Pasting here for convenience and in case anyone else lands on this w/ PowerShell

The issue is long PATH values in PS; the fix is running the following command in PS

`New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force`

**Comment by jfuss** [comment]
@Wolven531 Your issue does not related to the original authors. The original authors problem was failing to deploy the SAM CLI managed stack and "AdministratorAccess" is referring to IAM permissions.

The issue you seem to be facing is around long paths, which SAM CLI needs enabled on Windows for `sam init` to work. To keep things focused on the original issues, please respond in #4031 or create a new issue with the problem you are still having (if needed).

**Comment by Wolven531** [comment]
To clarify: My issue is unrelated to this issue and was resolved. Thanks for the response!

**Comment by rayjan0114** [comment]
@jfuss Thanks for the reply!! I really appreciate it.

Yes, I own the account and give myself AdministratorAcess
The same process can work before and in another account.
After a certain time, everything crashes, so I delete every cloudformation stacks and everything on S3 to start over with a basic Hello World example.

The thing is, I can't even create aws-sam-cli-managed-default now



<img width="1334" alt="image" src="https://user-images.githubusercontent.com/47523852/184473807-ee5591b3-6a3d-4854-a5cc-61cdef37d525.png">

**Comment by jfuss** [comment]
@rayjan0114 Just to confirm, you have deleted the `aws-sam-cli-managed-default` stack correct? After that was deleted, you tried `sam deploy --guided --profile myprofile --debug` again?

**Comment by rayjan0114** [comment]
Yes, I had deleted everything on S3 and all stacks on cloudformation before I tried `sam deploy --guided --profile myprofile --debug`

**Comment by jfuss** [comment]
@rayjan0114 Can you attach the logs from the failure? Is it still creating the stack but rolling back?

**Comment by jfuss** [comment]
Using the same profile, are you able to add a bucket policy to an S3 bucket directly? Assuming the latest failure is similar, it seems like the profile you are using is incorrect. Seeing if you can do those actions with the same profile (through AWS CLI) could help pinpoint if this is an issue with your credentials or something deeper with SAM CLI.

**Comment by rayjan0114** [comment]
You are right @jfuss , Its something deeper than sam cli
Thank you so much!
I turns out that I cannot succeed with `aws s3api list-buckets`
I tried to create a new access key and it still doesn't work
Finally, I created a new user and everything is back to normal
