### ISSUE TITLE
Bug: WSL Python 3.9 not working (SAM BUILD)

### ISSUE THREAD

**Issue by srburton** [aws/aws-sam-cli#4145]
### Description:
I can no longer build an application build with sam

### Observed result:

```
Building codeuri: /mnt/c/Users/srburton/Documents/GitHub/ZupIT/appsec-dast-lambda/.build/dev/src runtime: python3.9 metadata: {} architecture: x86_64 functions: DastFunction
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pip/_internal/main.py", line 10, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/entrypoints.py", line 4, in <module>
    from pip._internal.cli.main import main
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._internal.cli.parser import ConfigOptionParser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/parser.py", line 12, in <module>
    from pip._internal.configuration import Configuration, ConfigurationError
  File "/usr/lib/python3/dist-packages/pip/_internal/configuration.py", line 26, in <module>
    from pip._internal.utils.logging import getLogger
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/logging.py", line 27, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/misc.py", line 39, in <module>
    from pip._internal.locations import get_major_minor_version
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/__init__.py", line 14, in <module>
    from . import _distutils, _sysconfig
  File "/usr/lib/python3/dist-packages/pip/_internal/locations/_distutils.py", line 9, in <module>
    from distutils.cmd import Command as DistutilsCommand
ModuleNotFoundError: No module named 'distutils.cmd'
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: WSL (Ubuntu)
2. `sam --version`: SAM CLI, version 1.55.0
3. AWS region: us-east-1
4. Python: 
```
lrwxrwxrwx 1 root root      10 Mar 25 09:41 /usr/bin/python3 -> python3.10
-rwxr-xr-x 1 root root 5905480 Jun 29 09:14 /usr/bin/python3.10
lrwxrwxrwx 1 root root      34 Jun 29 09:14 /usr/bin/python3.10-config -> x86_64-linux-gnu-python3.10-config
-rwxr-xr-x 1 root root 5142408 Apr 18 23:32 /usr/bin/python3.8
-rwxr-xr-x 1 root root 5302896 May 23 18:57 /usr/bin/python3.9
lrwxrwxrwx 1 root root      17 Mar 25 09:41 /usr/bin/python3-config -> python3.10-config

```

`Add --debug flag to command you are running`

**Comment by jfuss** [comment]
@srburton What version of `pip` are you running? Looks like something going on within the `pip` and `distutils`version installed.

**Comment by moelasmar** [comment]
Closing given no response
