### ISSUE TITLE
Bug: esbuild not found when installed as local project dependency

### ISSUE THREAD

**Issue by kstolp** [aws/aws-sam-cli#4183]
### Description:
When esbuild is installed in the project locally (`npm install esbuild`), `sam build` fails.
`sam build` works only when installing `esbuild` globally (`npm -g install esbuild`).
Introduced in SAM v1.56.0.

### Steps to reproduce:
1. Start with a Typescript project, using node v14.20.0.
2. Have `esbuild` listed in the projects `devDependencies`.
3. Run `npm install`.
4. Run `sam build --debug`.

### Observed result:

The build fails with:
```
Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be
 included as a project dependency.
```

Full debug output:
```
$ sam build --debug
2022-09-01 13:59:15,725 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-01 13:59:15,725 | Using config file: samconfig.toml, config environment: default
2022-09-01 13:59:15,725 | Expand command line arguments to:
2022-09-01 13:59:15,725 | --template_file=/home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache
2022-09-01 13:59:15,839 | 'build' command is called
2022-09-01 13:59:15,849 | Collected default values for parameters: {'ApiHostedZone': 'kms.sh'}
2022-09-01 13:59:15,865 | There is no customer defined id or cdk path defined for resource Birds, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,865 | There is no customer defined id or cdk path defined for resource Foxes, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,865 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,867 | 0 stacks found in the template
2022-09-01 13:59:15,867 | Collected default values for parameters: {'ApiHostedZone': 'kms.sh'}
2022-09-01 13:59:15,880 | There is no customer defined id or cdk path defined for resource Birds, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,880 | There is no customer defined id or cdk path defined for resource Foxes, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,880 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-09-01 13:59:15,881 | 3 resources found in the stack
2022-09-01 13:59:15,881 | Found Serverless function with name='Birds' and CodeUri='.'
2022-09-01 13:59:15,881 | --base-dir is not presented, adjusting uri . relative to /home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml
2022-09-01 13:59:15,881 | Found Serverless function with name='Foxes' and CodeUri='.'
2022-09-01 13:59:15,881 | --base-dir is not presented, adjusting uri . relative to /home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml
2022-09-01 13:59:15,893 | Your template contains a resource with logical ID "ServerlessHttpApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
2022-09-01 13:59:15,893 | 3 resources found in the stack
2022-09-01 13:59:15,894 | Found Serverless function with name='Birds' and CodeUri='.'
2022-09-01 13:59:15,894 | Found Serverless function with name='Foxes' and CodeUri='.'
2022-09-01 13:59:15,894 | Found Serverless function with name='Birds' and CodeUri='.'
2022-09-01 13:59:15,894 | --base-dir is not presented, adjusting uri . relative to /home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml
2022-09-01 13:59:15,894 | Found Serverless function with name='Foxes' and CodeUri='.'
2022-09-01 13:59:15,894 | --base-dir is not presented, adjusting uri . relative to /home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml
2022-09-01 13:59:15,895 | Instantiating build definitions
2022-09-01 13:59:15,895 | No previous build graph found, generating new one
2022-09-01 13:59:15,895 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(nodejs14.x, /home/kevin/projects/aws-project-templates/sam-app-template-api, Zip, , be82a090-047d-447a-999f-043e96c12888, {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True}}, {}, x86_64, []), Function: Function(function_id='Birds', name='Birds', functionname='Env-animal-api-birds', runtime='nodejs14.x', memory=None, timeout=3, handler='src/handlers/birds.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/kevin/projects/aws-project-templates/sam-app-template-api', environment={'Variables': {'env': 'Env'}}, rolearn=None, layers=[], events={'AnimalApi': {'Type': 'HttpApi', 'Properties': {'Path': '/birds', 'Method': 'GET', 'ApiId': 'ServerlessHttpApi'}}}, metadata={'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True}, 'SamResourceId': 'Birds'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-09-01 13:59:15,895 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(nodejs14.x, /home/kevin/projects/aws-project-templates/sam-app-template-api, Zip, , 54a85548-c708-4850-be85-477d356326a2, {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True}}, {}, x86_64, []), Function: Function(function_id='Foxes', name='Foxes', functionname='Env-animal-api-foxes', runtime='nodejs14.x', memory=None, timeout=3, handler='src/handlers/foxes.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/home/kevin/projects/aws-project-templates/sam-app-template-api', environment={'Variables': {'env': 'Env'}}, rolearn=None, layers=[], events={'AnimalApi': {'Type': 'HttpApi', 'Properties': {'Path': '/foxes', 'Method': 'GET', 'ApiId': 'ServerlessHttpApi'}}}, metadata={'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True}, 'SamResourceId': 'Foxes'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-09-01 13:59:15,897 | Building codeuri: /home/kevin/projects/aws-project-templates/sam-app-template-api runtime: nodejs14.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True}} architecture: x86_64 functions: Birds
2022-09-01 13:59:15,898 | Building to following folder /home/kevin/projects/aws-project-templates/sam-app-template-api/.aws-sam/build/Birds
2022-09-01 13:59:15,898 | Loading workflow module 'aws_lambda_builders.workflows'
2022-09-01 13:59:15,900 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2022-09-01 13:59:15,901 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2022-09-01 13:59:15,902 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2022-09-01 13:59:15,903 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2022-09-01 13:59:15,905 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2022-09-01 13:59:15,906 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2022-09-01 13:59:15,907 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2022-09-01 13:59:15,908 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2022-09-01 13:59:15,909 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2022-09-01 13:59:15,910 | Found workflow 'NodejsNpmEsbuildBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2022-09-01 13:59:15,910 | executing NPM: ['npm', 'bin']
2022-09-01 13:59:16,050 | Lambda Builders found the following esbuild properties:
{"minify": true, "target": "es2020", "sourcemap": true, "entry_points": ["src/handlers/birds"]}
2022-09-01 13:59:16,050 | Running workflow 'NodejsNpmEsbuildBuilder'
2022-09-01 13:59:16,050 | Running NodejsNpmEsbuildBuilder:CopySource
2022-09-01 13:59:16,051 | Creating target folders at /tmp/tmpekkdggyy/src
2022-09-01 13:59:16,051 | Copying directory metadata from source (/home/kevin/projects/aws-project-templates/sam-app-template-api/src) to destination (/tmp/tmpekkdggyy/src)
2022-09-01 13:59:16,051 | Creating target folders at /tmp/tmpekkdggyy/src/handlers
2022-09-01 13:59:16,051 | Copying directory metadata from source (/home/kevin/projects/aws-project-templates/sam-app-template-api/src/handlers) to destination (/tmp/tmpekkdggyy/src/handlers)
2022-09-01 13:59:16,051 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/src/handlers/foxes.ts) to destination (/tmp/tmpekkdggyy/src/handlers/foxes.ts)
2022-09-01 13:59:16,051 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/src/handlers/birds.ts) to destination (/tmp/tmpekkdggyy/src/handlers/birds.ts)
2022-09-01 13:59:16,052 | File (.git) is in ignored set, skipping it
2022-09-01 13:59:16,052 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/README.md) to destination (/tmp/tmpekkdggyy/README.md)
2022-09-01 13:59:16,052 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/template.yaml) to destination (/tmp/tmpekkdggyy/template.yaml)
2022-09-01 13:59:16,052 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/package-lock.json) to destination (/tmp/tmpekkdggyy/package-lock.json)
2022-09-01 13:59:16,052 | File (.aws-sam) is in ignored set, skipping it
2022-09-01 13:59:16,052 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/typedoc.json) to destination (/tmp/tmpekkdggyy/typedoc.json)
2022-09-01 13:59:16,052 | Creating target folders at /tmp/tmpekkdggyy/events
2022-09-01 13:59:16,052 | Copying directory metadata from source (/home/kevin/projects/aws-project-templates/sam-app-template-api/events) to destination (/tmp/tmpekkdggyy/events)
2022-09-01 13:59:16,052 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/events/event-get-all-items.json) to destination (/tmp/tmpekkdggyy/events/event-get-all-items.json)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/events/event-post-item.json) to destination (/tmp/tmpekkdggyy/events/event-post-item.json)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/events/event-get-by-id.json) to destination (/tmp/tmpekkdggyy/events/event-get-by-id.json)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/events/event.json) to destination (/tmp/tmpekkdggyy/events/event.json)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/.eslintrc.js) to destination (/tmp/tmpekkdggyy/.eslintrc.js)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/tsconfig.json) to destination (/tmp/tmpekkdggyy/tsconfig.json)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/.gitignore) to destination (/tmp/tmpekkdggyy/.gitignore)
2022-09-01 13:59:16,053 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/.eslintignore) to destination (/tmp/tmpekkdggyy/.eslintignore)
2022-09-01 13:59:16,054 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/package.json) to destination (/tmp/tmpekkdggyy/package.json)
2022-09-01 13:59:16,054 | Creating target folders at /tmp/tmpekkdggyy/tests
2022-09-01 13:59:16,054 | Copying directory metadata from source (/home/kevin/projects/aws-project-templates/sam-app-template-api/tests) to destination (/tmp/tmpekkdggyy/tests)
2022-09-01 13:59:16,054 | Creating target folders at /tmp/tmpekkdggyy/tests/unit
2022-09-01 13:59:16,054 | Copying directory metadata from source (/home/kevin/projects/aws-project-templates/sam-app-template-api/tests/unit) to destination (/tmp/tmpekkdggyy/tests/unit)
2022-09-01 13:59:16,054 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/tests/unit/test-handler.test.ts) to destination (/tmp/tmpekkdggyy/tests/unit/test-handler.test.ts)
2022-09-01 13:59:16,054 | File (node_modules) is in ignored set, skipping it
2022-09-01 13:59:16,054 | Copying source file (/home/kevin/projects/aws-project-templates/sam-app-template-api/samconfig.toml) to destination (/tmp/tmpekkdggyy/samconfig.toml)
2022-09-01 13:59:16,054 | NodejsNpmEsbuildBuilder:CopySource succeeded
2022-09-01 13:59:16,054 | Running NodejsNpmEsbuildBuilder:NpmInstall
2022-09-01 13:59:16,054 | NODEJS installing in: /tmp/tmpekkdggyy
2022-09-01 13:59:16,054 | executing NPM: ['npm', 'install', '-q', '--no-audit', '--no-save', '--unsafe-perm', '--production']
2022-09-01 13:59:18,114 | NodejsNpmEsbuildBuilder:NpmInstall succeeded
2022-09-01 13:59:18,114 | Running NodejsNpmEsbuildBuilder:EsbuildBundle
2022-09-01 13:59:18,115 | NODEJS building ['/tmp/tmpekkdggyy/src/handlers/birds'] using esbuild to /home/kevin/projects/aws-project-templates/sam-app-template-api/.aws-sam/build/Birds
2022-09-01 13:59:18,115 | Using the following default args: ['--bundle', '--platform=node', '--outdir=/home/kevin/projects/aws-project-templates/sam-app-template-api/.aws-sam/build/Birds', '--format=cjs']
2022-09-01 13:59:18,115 | Found the following args in the config: ['--minify', '--sourcemap', '--target=es2020']
2022-09-01 13:59:18,115 | checking for esbuild in: ['/tmp/tmpekkdggyy/node_modules/.bin']
2022-09-01 13:59:18,115 | potential esbuild binaries: []
2022-09-01 13:59:18,115 | NodejsNpmEsbuildBuilder:EsbuildBundle failed
Traceback (most recent call last):
  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 92, in execute
  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 90, in run
  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 58, in esbuild_binary
aws_lambda_builders.workflows.nodejs_npm_esbuild.exceptions.EsbuildExecutionError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 301, in run
  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 94, in execute
aws_lambda_builders.actions.ActionFailedError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.

Build Failed
2022-09-01 13:59:18,152 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-01 13:59:18,152 | Unable to find Click Context for getting session_id.
2022-09-01 13:59:18,153 | Sending Telemetry: {'metrics': [{'events': {'requestId': '23ee347a-90e2-467f-829e-1a799a0273c4', 'installationId': '4ee049b7-ca8f-4f5f-b210-893dd20968e1', 'sessionId': 'a629ffb5-fc05-47de-b582-5a9277e58cd6', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.56.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'nodejs-npm-esbuild', 'thread_id': 140141385082688, 'time_stamp': '2022-09-01 20:59:15.898'}]}}}]}
2022-09-01 13:59:18,153 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'cfdac12f-ce3f-4f36-810b-20381a55ff2c', 'installationId': '4ee049b7-ca8f-4f5f-b210-893dd20968e1', 'sessionId': 'a629ffb5-fc05-47de-b582-5a9277e58cd6', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.56.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'f325fa72aaae48558c091faf869eeb38d3329b08bc4494c84471382e65f5b2d1', 'initialCommit': None}, 'duration': 2426, 'exitReason': 'WorkflowFailedError', 'exitCode': 1, 'stackTrace': 'Traceback (most recent call last):\n  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 92, in execute\n  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 90, in run\n  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/esbuild.py", line 58, in esbuild_binary\naws_lambda_builders.workflows.nodejs_npm_esbuild.exceptions.EsbuildExecutionError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "aws_lambda_builders/workflow.py", line 301, in run\n  File "aws_lambda_builders/workflows/nodejs_npm_esbuild/actions.py", line 94, in execute\naws_lambda_builders.actions.ActionFailedError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "samcli/lib/build/app_builder.py", line 760, in _build_function_in_process\n  File "aws_lambda_builders/builder.py", line 164, in build\n  File "aws_lambda_builders/workflow.py", line 95, in wrapper\n  File "aws_lambda_builders/workflow.py", line 308, in run\naws_lambda_builders.exceptions.WorkflowFailedError: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "samcli/commands/build/build_context.py", line 252, in run\n  File "samcli/lib/build/app_builder.py", line 221, in build\n  File "samcli/lib/build/build_strategy.py", line 80, in build\n  File "samcli/lib/build/build_strategy.py", line 90, in _build_functions\n  File "samcli/lib/build/build_strategy.py", line 174, in build_single_function_definition\n  File "samcli/lib/build/app_builder.py", line 668, in _build_function\n  File "samcli/lib/build/app_builder.py", line 763, in _build_function_in_process\nsamcli.lib.build.exceptions.BuildError: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/../samcli/lib/telemetry/metric.py", line 129, in wrapped\n  File "/../samcli/lib/utils/version_checker.py", line 41, in wrapped\n  File "/../samcli/cli/main.py", line 87, in wrapper\n  File "/../samcli/commands/build/command.py", line 201, in cli\n  File "/../samcli/commands/build/command.py", line 262, in do_cli\n  File "/../samcli/commands/build/build_context.py", line 297, in run\nsamcli.commands.exceptions.UserException: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n', 'exceptionMessage': 'samcli.commands.exceptions.UserException: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.\n'}}]}
2022-09-01 13:59:18,317 | Telemetry response: 200
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.
2022-09-01 13:59:18,345 | Telemetry response: 200
zsh: exit 1     sam build --debug
```

### Expected result:
The build to succeed, using the locally installed esbuild package (`./node_modules/.bin/esbuild`).

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Arch Linux
5. `sam --version`: SAM CLI, version 1.56.0
6. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by mildaniel** [comment]
Hi @kstolp, thanks for reaching out. As of version 1.56.0 of the CLI, `sam build` will now install dependencies using the production flag to be consistent with how it's currently done for normal Node.js builds. This will make the installation faster and result in less bloat being installed. If you'd like, you can move `esbuild` to be a non-dev dependency and it should work as expected. Since esbuild will bundle your code, it won't be packaged in your Lambda.

**Comment by nixilla** [comment]
I had the same issue with `aws-sam-cli@1.68.0`. I fixed it with `pip install --upgrade aws_lambda_builders`

It came with this error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
aws-sam-cli 1.68.0 requires aws-lambda-builders==1.23.1, but you have aws-lambda-builders 1.24.0 which is incompatible.
Successfully installed aws_lambda_builders-1.24.0
```
but it is working now

**Comment by zetaraku** [comment]
I'm using 1.73.0 and the issue still persists.

**Comment by danhnguyeen** [comment]
> Hi @kstolp, thanks for reaching out. As of version 1.56.0 of the CLI, `sam build` will now install dependencies using the production flag to be consistent with how it's currently done for normal Node.js builds. This will make the installation faster and result in less bloat being installed. If you'd like, you can move `esbuild` to be a non-dev dependency and it should work as expected. Since esbuild will bundle your code, it won't be packaged in your Lambda.

This option worked for me. But it seems it only works if we put `handler` file in root directory. If we put it into a sub folder, this issue appears again.

**Comment by khanakia** [comment]
I have installed the `esbuild` globally but still getting error 
```
Starting Build use cache                                                                                                                        
Manifest file is changed (new hash: cc7897f17d8f6c63c87295841bd7d6ec) or dependency folder (.aws-sam/deps/ae4bdc01-6372-4bb9-b6ea-04a081dbb9cb) 
is missing for (HelloWorldFunction), downloading dependencies and copying/building source                                                       
Building codeuri: /Users/khanakia/D1/www/projects/analyzify/analyzify_shopify_op_runner/op_webhook_processor_lambda/op runtime: nodejs18.x      
metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': False, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}}    
architecture: x86_64 functions: HelloWorldFunction                                                                                              
Running NodejsNpmEsbuildBuilder:CopySource                                                                                                      
Running NodejsNpmEsbuildBuilder:NpmInstall                                                                                                      
Running NodejsNpmEsbuildBuilder:EsbuildBundle                                                                                                   

Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Could not resolve "axios"

    app.ts:2:18:
      2 │ import axios from 'axios';
        ╵                   ~~~~~~~

  You can mark the path "axios" as external to exclude it from the bundle, which will remove this error.

1 error

```

**Comment by oldbettie** [comment]
same issue here.. I tried installing globally and get this issue.

```
Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Could not resolve "@serverless-chrome/lambda"

    app.ts:2:45:
      2 │ ...t launchChrome, { LaunchedChrome } from "@serverless-chrome/lambda"
        ╵                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@serverless-chrome/lambda" as external to exclude it from the bundle, which will remove this error.

1 error
SAM Build has failed: Command did not exit successfully, exit code: 1
20 has failed: Command did not exit successfully, exit code: 1
```
