### ISSUE TITLE
Bug: UnboundLocalError: local variable 'layer_reference' referenced before assignment

### ISSUE THREAD

**Issue by joshbegin** [aws/aws-sam-cli#4200]
### Description:
Layers break Sam Sync unless referenced in Global section of template

### Steps to reproduce:
1. Create "Hello World" Node16 app from `sam init` or pull from repo: https://github.com/joshbegin/test-layers
2. Deploy app
3. Add this to your lambda resource:  
`Layers:`
`      - !Sub arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:18`
5. Run `sam sync --stack-name <your stack> --watch`

### Observed result:
Sync fails with this error: ```Failed to sync infra. Code sync is paused until template/stack is fixed.
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/watch_manager.py", line 190, in _execute_infra_sync
    self._execute_infra_context()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/watch_manager.py", line 141, in _execute_infra_context
    self._build_context.set_up()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 190, in set_up
    self._function_provider = SamFunctionProvider(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 67, in __init__
    self.functions = SamFunctionProvider._extract_functions(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 235, in _extract_functions
    layers = SamFunctionProvider._parse_layer_info(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 519, in _parse_layer_info
    found_layer = SamFunctionProvider._locate_layer_from_nested(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.56.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 654, in _locate_layer_from_nested
    LOG.debug("Resolved layer: %s in current stack %s", layer_reference, stack.stack_path)
UnboundLocalError: local variable 'layer_reference' referenced before assignment```

### Expected result:
Sam Sync succeeds

### Workaround:
Moving Layers to `Global` section of template succeeds and adds layers correctly, but is not desirable since all lambdas do not need the same layers.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOs
2. `sam --version`: 1.56.0
6. AWS region: us-east-1

**Comment by mndeveci** [comment]
Thanks for reporting this issue. I confirm this is a bug, we tried to resolve the given layer reference assuming it is a `!Ref` to a layer inside the template but it fails.

I will be raising a draft which addresses this issue.

**Comment by mndeveci** [comment]
The changes have been merged, this should be fixed in the next SAM CLI release.

**Comment by hawflau** [comment]
Closing as the fix has been released in SAM v1.57.0
