### ISSUE TITLE
Bug: Containerized Build Fails with NPM Network Issue

### ISSUE THREAD

**Issue by kcsparksmm** [aws/aws-sam-cli#4217]
### Description:

Building with the --use-container option results in a network error during the NodejsNpmBuilder:NpmInstall workflow.

### Steps to reproduce:

1) Create a WSL instance with Ubuntu 20.04
2) run sam init with the Serverless API quickstart template
3) choose node16 as runtime
4) run build command with -u flag

### Observed result:

```Build Failed
2022-09-09 15:26:58,995 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-09 15:26:58,996 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'c9ca5d11-4b1d-47c5-897a-dabd1bef9d36', 'installationId': '77538678-259b-428e-857a-c78400af7339', 'sessionId': '6ad1fddb-c0ad-4bb0-90a4-af04d868fe41', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.56.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '246f6a6fd7bc0f0474d69868a33db253f00723ac0aba7f9d663d7d6e4ab75fe5', 'initialCommit': None}, 'duration': 439097, 'exitReason': 'BuildInsideContainerError', 'exitCode': 1, 'stackTrace': 'Traceback (most recent call last):\n  File "samcli/commands/build/build_context.py", line 252, in run\n  File "samcli/lib/build/app_builder.py", line 221, in build\n  File "samcli/lib/build/build_strategy.py", line 80, in build\n  File "samcli/lib/build/build_strategy.py", line 90, in _build_functions\n  File "samcli/lib/build/build_strategy.py", line 174, in build_single_function_definition\n  File "samcli/lib/build/app_builder.py", line 654, in _build_function\n  File "samcli/lib/build/app_builder.py", line 836, in _build_function_on_container\n  File "samcli/lib/build/app_builder.py", line 868, in _parse_builder_response\nsamcli.lib.build.exceptions.BuildInsideContainerError: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.\nnpm ERR! code ENOTFOUND\nnpm ERR! syscall getaddrinfo\nnpm ERR! errno ENOTFOUND\nnpm ERR! network request to https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network \'proxy\' config is set properly.  See: \'npm help config\'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-09-09T22_19_47_941Z-debug-0.log\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/../samcli/lib/telemetry/metric.py", line 129, in wrapped\n  File "/../samcli/lib/utils/version_checker.py", line 41, in wrapped\n  File "/../samcli/cli/main.py", line 87, in wrapper\n  File "/../samcli/commands/build/command.py", line 201, in cli\n  File "/../samcli/commands/build/command.py", line 262, in do_cli\n  File "/../samcli/commands/build/build_context.py", line 297, in run\nsamcli.commands.exceptions.UserException: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.\nnpm ERR! code ENOTFOUND\nnpm ERR! syscall getaddrinfo\nnpm ERR! errno ENOTFOUND\nnpm ERR! network request to https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network \'proxy\' config is set properly.  See: \'npm help config\'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-09-09T22_19_47_941Z-debug-0.log\n', 'exceptionMessage': "samcli.commands.exceptions.UserException: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.\nnpm ERR! code ENOTFOUND\nnpm ERR! syscall getaddrinfo\nnpm ERR! errno ENOTFOUND\nnpm ERR! network request to https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org\nnpm ERR! network This is a problem related to network connectivity.\nnpm ERR! network In most cases you are behind a proxy or have bad network settings.\nnpm ERR! network \nnpm ERR! network If you are behind a proxy, please make sure that the\nnpm ERR! network 'proxy' config is set properly.  See: 'npm help config'\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /root/.npm/_logs/2022-09-09T22_19_47_941Z-debug-0.log\n"}}]}
2022-09-09 15:26:58,996 | Unable to find Click Context for getting session_id.
2022-09-09 15:26:58,998 | Sending Telemetry: {'metrics': [{'events': {'requestId': 'b72d7861-d55b-4798-b8f6-e7144178bbda', 'installationId': '77538678-259b-428e-857a-c78400af7339', 'sessionId': '6ad1fddb-c0ad-4bb0-90a4-af04d868fe41', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.56.1', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'nodejs-npm', 'thread_id': 139931072153408, 'time_stamp': '2022-09-09 22:19:40.298'}]}}}]}
2022-09-09 15:26:59,392 | Telemetry response: 200
2022-09-09 15:26:59,400 | Telemetry response: 200
Error: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.
npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-9.0.7.tgz failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-09T22_19_47_941Z-debug-0.log```


### Expected result:
<!-- Describe what you expected. -->
Sam to Build properly.


### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04 LTS using WSL
2. `sam --version`: 1.56.1
3. AWS region: us-west-2

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Hi, thanks for opening this issue! Can you double check your WSL/Docker network settings and make sure its able to talk to the internet correctly? This appears to be related to network connectivity with npm and not directly related to SAM CLI.

**Comment by kcsparksmm** [comment]
You were right. I installed Docker on my WSL instance, but to use containerization out of the box you need to install on Windows and use the WSL extension. Thanks
