### ISSUE TITLE
Bug: TITLE

### ISSUE THREAD

**Issue by cscetbon** [aws/aws-sam-cli#4226]
### Description:

Invoking locally sam with template hello-world-typescript fails

### Steps to reproduce:

```
$ sam init -r nodejs16.x -p Zip --app-template hello-world-typescript --no-tracing --name sam-app-ts
$ cd sam-app-ts
$ sam local invoke 
Invoking app.lambdaHandler (nodejs16.x)
Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs16.x:rapid-1.56.1-x86_64.

Mounting /Downloads/tests/sam-app-ts/hello-world as /var/task:ro,delegated inside runtime container
START RequestId: ab3c5059-84d1-4648-9726-159497ad3830 Version: $LATEST
2022-09-13T03:00:00.572Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
13 Sep 2022 03:00:00,668 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2022-09-13T03:00:01.489Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
END RequestId: c4c81065-292a-4c8b-adf1-5a160061ba19
REPORT RequestId: c4c81065-292a-4c8b-adf1-5a160061ba19	Init Duration: 1.11 ms	Duration: 1839.22 ms	Billed Duration: 1840 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}%
```

### Observed result:

Fails with _**Error: Cannot find module 'app'**_

### Expected result:

Should work like template hello-world does

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac OS Monterey 12.6
2. If using SAM CLI, `sam --version`:  SAM CLI, version 1.56.1
3. AWS region: us-west-2

`Add --debug flag to any SAM CLI commands you are running`

```
2022-09-12 23:02:41,642 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-12 23:02:41,642 | Using config file: samconfig.toml, config environment: default
2022-09-12 23:02:41,642 | Expand command line arguments to:
2022-09-12 23:02:41,642 | --template_file=/Downloads/tests/sam-app-ts/template.yaml --no_event --layer_cache_basedir=/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2022-09-12 23:02:41,642 | local invoke command is called
2022-09-12 23:02:41,645 | No Parameters detected in the template
2022-09-12 23:02:41,654 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-09-12 23:02:41,654 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-12 23:02:41,654 | 0 stacks found in the template
2022-09-12 23:02:41,654 | No Parameters detected in the template
2022-09-12 23:02:41,660 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-09-12 23:02:41,660 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-09-12 23:02:41,660 | 2 resources found in the stack
2022-09-12 23:02:41,660 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2022-09-12 23:02:41,660 | --base-dir is not presented, adjusting uri hello-world/ relative to /Downloads/tests/sam-app-ts/template.yaml
2022-09-12 23:02:41,691 | Found one Lambda function with name 'HelloWorldFunction'
2022-09-12 23:02:41,691 | Invoking app.lambdaHandler (nodejs16.x)
2022-09-12 23:02:41,691 | No environment variables found for function 'HelloWorldFunction'
2022-09-12 23:02:41,691 | Loading AWS credentials from session with profile 'None'
2022-09-12 23:02:41,698 | Resolving code path. Cwd=/Downloads/tests/sam-app-ts, CodeUri=/Downloads/tests/sam-app-ts/hello-world
2022-09-12 23:02:41,698 | Resolved absolute path to code is /Downloads/tests/sam-app-ts/hello-world
2022-09-12 23:02:41,698 | Code /Downloads/tests/sam-app-ts/hello-world is not a zip/jar file
2022-09-12 23:02:41,711 | Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs16.x:rapid-1.56.1-x86_64.

2022-09-12 23:02:41,711 | Mounting /Downloads/tests/sam-app-ts/hello-world as /var/task:ro,delegated inside runtime container
2022-09-12 23:02:41,977 | Starting a timer for 3 seconds for function 'HelloWorldFunction'
START RequestId: 18f59270-47e0-4a19-a263-79ebdf9a8978 Version: $LATEST
2022-09-13T03:02:42.937Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
13 Sep 2022 03:02:43,038 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 129
2022-09-13T03:02:43.880Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}
END RequestId: 085b8781-36c8-480a-aa21-79a99791b72d
REPORT RequestId: 085b8781-36c8-480a-aa21-79a99791b72d	Init Duration: 1.38 ms	Duration: 1873.62 ms	Billed Duration: 1874 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs","trace":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:951:17)","    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:976:21)","    at async start (file:///var/runtime/index.mjs:1137:23)","    at async file:///var/runtime/index.mjs:1143:1"]}2022-09-12 23:02:44,108 | Cleaning all decompressed code dirs
2022-09-12 23:02:44,151 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '4ea26ca7-cf3d-4d52-9840-50d5026a3327', 'installationId': '84b67f45-9dc0-4b12-93a8-e8a6f6f48b1d', 'sessionId': '8d0cffea-988f-41fe-b7ad-9d98d628537d', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.14', 'samcliVersion': '1.56.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '44fcbe8b2ec1b0561b597067145f99fff68e24de52152b8b6290fe84054eaec4', 'initialCommit': None}, 'duration': 2508, 'exitReason': 'success', 'exitCode': 0, 'stackTrace': None, 'exceptionMessage': None}}]}
2022-09-12 23:02:44,597 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2022-09-12 23:02:44,598 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-12 23:02:44,598 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': '949f4a75-710e-498b-a716-ffa7c822c31a', 'installationId': '84b67f45-9dc0-4b12-93a8-e8a6f6f48b1d', 'sessionId': '8d0cffea-988f-41fe-b7ad-9d98d628537d', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.14', 'samcliVersion': '1.56.1', 'runtimes': ['nodejs16.x']}}]}
2022-09-12 23:02:45,048 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

**Comment by cscetbon** [comment]
@lucashuy I can confirm that running `sam build` before fixes the problem. I see that it's said in the README of the new app. I suppose we can close this issue or make it more explicit somehow ...

**Comment by lucashuy** [comment]
Thanks for confirming that `sam build` works! Since the instructions to run `sam build` are already in the README of the cloned template app, we don't have any plans to make this more explicit for now. If you have any other feedback about running and building Typescript apps, or about SAM/SAM CLI in general please create a new issue or reopen this one for more discussion
