### ISSUE TITLE
Bug: SSL error when calling AWS domains

### ISSUE THREAD

**Issue by dapestegui** [aws/aws-sam-cli#4245]
### Description:

When trying to test locally or verify a Python lambda SAM fails with SSL Error. Also telemetry fails with the same error. 

If AWS_CA_BUNDLE is set to a proper certificate (i.e. /opt/homebrew/etc/ca-certificates/cert.pem) all commands work correctly. Seems to be bundled python set the SSL certificate to /opt/homebrew/etc/openssl@1.1/cert.pem thus failing with AWS domains. 

### Steps to reproduce:

1. Build a Python 3.9 lambda with sam build
2. Execute sam validate or sam local invoke

### Observed result:

`
2022-09-20 20:15:41 Loading policies from IAM...
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 176, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 126, in wrapped
    return_value = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/cdk_support_decorators.py", line 38, in wrapped
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 39, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 61, in do_cli
    validator.is_valid()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 58, in is_valid
    managed_policy_map = self.managed_policy_loader.load()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/translator/managed_policy_translator.py", line 35, in load
    self._load_policies_from_iam()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
    exec_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/translator/managed_policy_translator.py", line 27, in _load_policies_from_iam
    for page in page_iterator:
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 475, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://iam.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
% sam validate --debug                                       
2022-09-20 20:18:40,976 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-09-20 20:18:40,976 | Using config file: samconfig.toml, config environment: default
2022-09-20 20:18:40,976 | Expand command line arguments to:
2022-09-20 20:18:40,976 | --template_file=template.yaml 
2022-09-20 20:18:41 Loading policies from IAM...
2022-09-20 20:18:45,363 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '0c09e218-acb7-4f3d-b8da-7fb3709fc6b8', 'installationId': '9fdde113-d752-4b4c-8409-0a341efb39ba', 'sessionId': '59888d68-c1a8-43f7-bbee-508e61081f63', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.14', 'samcliVersion': '1.57.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam validate', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '18778c4fc880a458a6015763f503d9f049b2a3d771df31685f96230deaad90cd', 'initialCommit': None}, 'duration': 4386, 'exitReason': 'SSLError', 'exitCode': 255}}]}
2022-09-20 20:18:45,796 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /metrics (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 448, in send
    urllib_response = conn.urlopen(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/opt/homebrew/Cellar/python@3.8/3.8.14/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 176, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 126, in wrapped
    return_value = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/cli/main.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/_utils/cdk_support_decorators.py", line 38, in wrapped
    return func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 39, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 61, in do_cli
    validator.is_valid()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 58, in is_valid
    managed_policy_map = self.managed_policy_loader.load()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/translator/managed_policy_translator.py", line 35, in load
    self._load_policies_from_iam()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/metrics/method_decorator.py", line 96, in wrapper_cw_timer
    exec_result = func(*args, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/samtranslator/translator/managed_policy_translator.py", line 27, in _load_policies_from_iam
    for page in page_iterator:
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/paginate.py", line 269, in __iter__
    response = self._make_request(current_kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/paginate.py", line 357, in _make_request
    return self._method(**current_kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 514, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 921, in _make_api_call
    http, parsed_response = self._make_request(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/client.py", line 944, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.57.0/libexec/lib/python3.8/site-packages/botocore/httpsession.py", line 475, in send
    raise SSLError(endpoint_url=request.url, error=e)
botocore.exceptions.SSLError: SSL validation failed for https://iam.amazonaws.com/ [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

`

### Expected result:

SAM is able to connect correctly to all AWS domains. 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Monterey
3. `sam --version`: 1.57.0
4. AWS region: us-west-2 / us-east-1

**Comment by sriram-mv** [comment]
Thanks for the report! Based on ```If AWS_CA_BUNDLE is set to a proper certificate (i.e. /opt/homebrew/etc/ca-certificates/cert.pem) all commands work correctly. Seems to be bundled python set the SSL certificate to /opt/homebrew/etc/openssl@1.1/cert.pem thus failing with AWS domains.```

Is this setting you have to change with the latest version of SAM CLI? do you see the same issue if you pip installed aws-sam-cli or only with homebrew?

**Comment by hawflau** [comment]
closing due to inactivity for a while. Feel free to re-open if it's still an issue
