### ISSUE TITLE
Bug: Race Condition During Simultaneous Stack Creation/Deletion : Stack creation fails: "Error occurred while GetObject. S3 Error Code: NoSuchKey."

### ISSUE THREAD

**Issue by jadamsoneko** [aws/aws-sam-cli#4307]
### Description:
The deploy of SAM stack fails if a different stack from same template is being deleted at the same time. This is due to SAM's attempts to re-use resources. This holds true for stacks with lambda functions, but possibly other resource types.

This is important to us because we run automated stack creation/deletion during testing and we have intermittent failures during these tests.

### Steps to reproduce:
Create stack from template: 
`sam deploy --stack-name race-condition-1 --force-upload --debug`
After stack creation is completed, create a new stack from the same template:
`sam deploy --stack-name race-condition-2 --force-upload --debug`
While deploy is occurring, but after initial resource upload or initial resource check occurs, delete original stack:
`sam delete --stack-name race-condition-1 --no-prompts --region us-east-1`
Deploy of second stack will fail with message Stack creation fails: "Error occurred while GetObject. S3 Error Code: NoSuchKey."

### Observed result:

Short Output:
```
CREATE_FAILED             AWS::Lambda::Function     GenerateLinkFunction      Resource handler
                                                                              returned message:
                                                                              "Error occurred while
                                                                              GetObject. S3 Error
                                                                              Code: NoSuchKey. S3
                                                                              Error Message: The
                                                                              specified key does not
                                                                              exist. (Service:
                                                                              Lambda, Status Code:
                                                                              400, Request ID: ****)"
                                                                              (RequestToken: *****,
                                                                              HandlerErrorCode:
                                                                              InvalidRequest)
```

Full Output:

Command Prompt Window 1:

```

C:\work\sam>sam deploy --stack-name race-condition-1 --debug
2022-10-06 12:23:33,421 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-10-06 12:23:33,421 | Using config file: samconfig.toml, config environment: default
2022-10-06 12:23:33,422 | Expand command line arguments to:
2022-10-06 12:23:33,422 | --template_file=C:\work\sam\template.yml --stack_name=race-condition-1 --fail_on_empty_changeset --s3_bucket=sam-test-tmp --capabilities=['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
2022-10-06 12:23:33,968 | No Parameters detected in the template
2022-10-06 12:23:34,008 | There is no customer defined id or cdk path defined for resource GenerateLinkFunction, so we will use the resource logical id as the resource id
2022-10-06 12:23:34,009 | 0 stacks found in the template
2022-10-06 12:23:34,140 | There is no customer defined id or cdk path defined for resource GenerateLinkFunction, so we will use the resource logical id as the resource id
2022-10-06 12:23:34,141 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
Uploading to f921256065605593396edf28043fc8e1  1146 / 1146  (100.00%)

        Deploying with following values
        ===============================
        Stack name                   : race-condition-1
        Region                       : us-east-1
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : sam-test-tmp
        Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
        Parameter overrides          : {}
        Signing Profiles             : {}

Initiating deployment
=====================
2022-10-06 12:23:34,620 | No Parameters detected in the template
2022-10-06 12:23:34,636 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
2022-10-06 12:23:34,636 | 0 stacks found in the template
2022-10-06 12:23:34,637 | No Parameters detected in the template
2022-10-06 12:23:34,651 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
2022-10-06 12:23:34,651 | 1 resources found in the stack
2022-10-06 12:23:34,926 | Stack with id race-condition-1 does not exist
2022-10-06 12:23:35,259 | File with same data already exists at 6bf83ebd9fe9d6271977240c8ff46c6a.template, skipping upload

Waiting for changeset to be created..
CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------
Operation                 LogicalResourceId         ResourceType              Replacement
-----------------------------------------------------------------------------------------------------
+ Add                     GenerateLinkFunctionRol   AWS::IAM::Role            N/A
                          e
+ Add                     GenerateLinkFunction      AWS::Lambda::Function     N/A
-----------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:822361296175:changeSet/samcli-deploy1665073414/11fb8bee-4816-472f-812a-da52bc6ad0fc


2022-10-06 12:23:46 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 0.5 seconds)
-----------------------------------------------------------------------------------------------------
ResourceStatus            ResourceType              LogicalResourceId         ResourceStatusReason
-----------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS        AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
CREATE_IN_PROGRESS        AWS::IAM::Role            GenerateLinkFunctionRol   Resource creation
                                                    e                         Initiated
CREATE_COMPLETE           AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
CREATE_IN_PROGRESS        AWS::Lambda::Function     GenerateLinkFunction      -
CREATE_IN_PROGRESS        AWS::Lambda::Function     GenerateLinkFunction      Resource creation
                                                                              Initiated
CREATE_COMPLETE           AWS::Lambda::Function     GenerateLinkFunction      -
CREATE_COMPLETE           AWS::CloudFormation::St   race-condition-1          -
                          ack
-----------------------------------------------------------------------------------------------------

Successfully created/updated stack - race-condition-1 in us-east-1

2022-10-06 12:24:22,126 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '08f09a31-6889-44d5-a125-47d47ee245da', 'installationId': '5325d7b5-2305-429e-ad6b-6195748285c0', 'sessionId': '6afa6cad-4641-4da3-808c-b820f42bfbee', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.53.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 48704, 'exitReason': 'success', 'exitCode': 0}}]}
2022-10-06 12:24:22,597 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

C:\work\sam>sam delete --stack-name race-condition-1 --no-prompts --debug --region us-east-1
2022-10-06 12:24:54,451 | Using config file: samconfig.toml, config environment: default
2022-10-06 12:24:54,452 | Expand command line arguments to:
2022-10-06 12:24:54,453 | --stack_name=race-condition-1 --no_prompts
2022-10-06 12:24:56,506 | Config file location: C:\work\sam\samconfig.toml
2022-10-06 12:24:56,506 | Loading configuration values from [default.['deploy'].parameters] (env.command_name.section) in config file at 'C:\work\sam\samconfig.toml'...
2022-10-06 12:24:56,509 | Configuration values successfully loaded.
2022-10-06 12:24:56,511 | Configuration values are: {'s3_bucket': 'sam-test-tmp', 'capabilities': ['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND'], 'region': 'us-east-1'}
2022-10-06 12:24:56,840 | Input stack is deployed, continue deleting
2022-10-06 12:24:56,988 | Stack with id race-condition-1-23bc8fcf-CompanionStack does not exist
2022-10-06 12:24:57,214 |       - Deleting S3 object with key f921256065605593396edf28043fc8e1
2022-10-06 12:24:57,261 | Deleted s3 object with key f921256065605593396edf28043fc8e1 successfully
2022-10-06 12:24:57,318 | Could not find the S3 file with the key 5b498f284865808bad06592e41b11bc0.template
2022-10-06 12:24:57,318 |       - Could not find and delete the S3 object with the key 5b498f284865808bad06592e41b11bc0.template
        - Deleting Cloudformation stack race-condition-1
2022-10-06 12:25:28,368 | Deleted Cloudformation stack: race-condition-1

Deleted successfully

```

Command Prompt Window 2:

```
C:\work\sam>sam deploy --stack-name race-condition-2 --debug
2022-10-06 12:24:50,621 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-10-06 12:24:50,622 | Using config file: samconfig.toml, config environment: default
2022-10-06 12:24:50,622 | Expand command line arguments to:
2022-10-06 12:24:50,622 | --template_file=C:\work\sam\template.yml --stack_name=race-condition-2 --fail_on_empty_changeset --s3_bucket=sam-test-tmp --capabilities=['CAPABILITY_IAM', 'CAPABILITY_AUTO_EXPAND']
2022-10-06 12:24:51,096 | No Parameters detected in the template
2022-10-06 12:24:51,134 | There is no customer defined id or cdk path defined for resource GenerateLinkFunction, so we will use the resource logical id as the resource id
2022-10-06 12:24:51,135 | 0 stacks found in the template
2022-10-06 12:24:51,256 | There is no customer defined id or cdk path defined for resource GenerateLinkFunction, so we will use the resource logical id as the resource id
2022-10-06 12:24:51,256 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
2022-10-06 12:24:51,534 | File with same data already exists at f921256065605593396edf28043fc8e1, skipping upload

        Deploying with following values
        ===============================
        Stack name                   : race-condition-2
        Region                       : us-east-1
        Confirm changeset            : False
        Disable rollback             : False
        Deployment s3 bucket         : sam-test-tmp
        Capabilities                 : ["CAPABILITY_IAM", "CAPABILITY_AUTO_EXPAND"]
        Parameter overrides          : {}
        Signing Profiles             : {}

Initiating deployment
=====================
2022-10-06 12:24:51,555 | No Parameters detected in the template
2022-10-06 12:24:51,567 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
2022-10-06 12:24:51,567 | 0 stacks found in the template
2022-10-06 12:24:51,568 | No Parameters detected in the template
2022-10-06 12:24:51,580 | Sam customer defined id is more priority than other IDs. Customer defined id for resource GenerateLinkFunction is GenerateLinkFunction
2022-10-06 12:24:51,581 | 1 resources found in the stack
2022-10-06 12:24:51,819 | Stack with id race-condition-2 does not exist
2022-10-06 12:24:52,070 | File with same data already exists at 6bf83ebd9fe9d6271977240c8ff46c6a.template, skipping upload

Waiting for changeset to be created..
CloudFormation stack changeset
-----------------------------------------------------------------------------------------------------
Operation                 LogicalResourceId         ResourceType              Replacement
-----------------------------------------------------------------------------------------------------
+ Add                     GenerateLinkFunctionRol   AWS::IAM::Role            N/A
                          e
+ Add                     GenerateLinkFunction      AWS::Lambda::Function     N/A
-----------------------------------------------------------------------------------------------------

Changeset created successfully. arn:aws:cloudformation:us-east-1:822361296175:changeSet/samcli-deploy1665073491/7c32bfad-30f7-4eff-a7d8-cd0b351228ee


2022-10-06 12:25:03 - Waiting for stack create/update to complete

CloudFormation events from stack operations (refresh every 0.5 seconds)
-----------------------------------------------------------------------------------------------------
ResourceStatus            ResourceType              LogicalResourceId         ResourceStatusReason
-----------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS        AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
CREATE_IN_PROGRESS        AWS::IAM::Role            GenerateLinkFunctionRol   Resource creation
                                                    e                         Initiated
CREATE_COMPLETE           AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
CREATE_IN_PROGRESS        AWS::Lambda::Function     GenerateLinkFunction      -
CREATE_IN_PROGRESS        AWS::Lambda::Function     GenerateLinkFunction      Resource creation
                                                                              Initiated
CREATE_FAILED             AWS::Lambda::Function     GenerateLinkFunction      Resource handler
                                                                              returned message:
                                                                              "Error occurred while
                                                                              GetObject. S3 Error
                                                                              Code: NoSuchKey. S3
                                                                              Error Message: The
                                                                              specified key does not
                                                                              exist. (Service:
                                                                              Lambda, Status Code:
                                                                              400, Request ID: 6d0a08
                                                                              04-7e0a-4562-8a86-9767d
                                                                              be21746)"
                                                                              (RequestToken: eb511b29
                                                                              -9f32-a587-0797-9a6fdc1
                                                                              ce5e2,
                                                                              HandlerErrorCode:
                                                                              InvalidRequest)
ROLLBACK_IN_PROGRESS      AWS::CloudFormation::St   race-condition-2          The following
                          ack                                                 resource(s) failed to
                                                                              create:
                                                                              [GenerateLinkFunction].
                                                                              Rollback requested by
                                                                              user.
DELETE_IN_PROGRESS        AWS::Lambda::Function     GenerateLinkFunction      -
DELETE_COMPLETE           AWS::Lambda::Function     GenerateLinkFunction      -
DELETE_IN_PROGRESS        AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
DELETE_COMPLETE           AWS::IAM::Role            GenerateLinkFunctionRol   -
                                                    e
ROLLBACK_COMPLETE         AWS::CloudFormation::St   race-condition-2          -
                          ack
-----------------------------------------------------------------------------------------------------
2022-10-06 12:26:14,879 | Execute stack waiter exception
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\deploy\deployer.py", line 482, in wait_for_execute
    waiter.wait(StackName=stack_name, WaiterConfig=waiter_config)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 55, in wait
    Waiter.wait(self, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\botocore\waiter.py", line 375, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once
2022-10-06 12:26:14,903 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'e9c218d2-d449-46e8-9941-40eea009ad8d', 'installationId': '5325d7b5-2305-429e-ad6b-6195748285c0', 'sessionId': '54a2d74d-115a-42e5-99bc-8b833e4a192f', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.53.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': 'us-east-1', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN'}, 'duration': 84281, 'exitReason': 'DeployFailedError', 'exitCode': 1}}]}
2022-10-06 12:26:15,405 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Failed to create/update the stack: race-condition-2, Waiter StackCreateComplete failed: Waiter encountered a terminal failure state: For expression "Stacks[].StackStatus" we matched expected path: "ROLLBACK_COMPLETE" at least once

```

### Expected Result
Expected stack creation to complete successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Microsoft Windows 10 Pro, Version	10.0.19044 Build 19044
2. If using SAM CLI, `sam --version`: SAM CLI, version 1.53.0
3. AWS region: us-east-1

`Add --debug flag to any SAM CLI commands you are running`

**Comment by mndeveci** [comment]
SAM CLI uses the hash of the function ZIP files when uploading them to S3 bucket, which helps us to de-dup the uploading. Which causes a collision for your use case.

In order to resolve this issue, you can use `--s3-prefix` (or using `s3_prefix` in `samconfig.toml` file) which will add a prefix to the resources that is uploaded to S3. In that way, when you deploy your first stack, resources will be uploaded with a prefix. And you can deploy your second stack with a different prefix, while deleting the first one.

- Deploy with `first-stack` S3 prefix
`sam deploy --stack-name race-condition-1 --force-upload --debug --s3-prefix first-stack`
- Deploy with `second-stack` S3 prefix
`sam deploy --stack-name race-condition-2 --force-upload --debug --s3-prefix second-stack`
- When you delete the first stack, it will delete the S3 files with `first-stack` prefix, so that second stack can continue deployment.
`sam delete --stack-name race-condition-1 --no-prompts --region us-east-1`

Please let us know if you have further questions.

Thanks!

**Comment by jadamsoneko** [comment]
Thank you!
