### ISSUE TITLE
Bug: sam build does not use certain commit from requirements.txt but only newest version

### ISSUE THREAD

**Issue by Cayllen** [aws/aws-sam-cli#4330]
When using `sam build --template ./template.yaml --build-dir .aws-sam/build`

and my requirements.txt looks like this:
`git+https://github.com/collective/icalendar.git@68dc8b18caf0806d2fa1a8e0f06027329ad96c4c`

I do not get the repository at this commit but actually just at the newest tag (5.0.0) https://github.com/collective/icalendar/tags 
This does not happen when installing the package via pip

I therefore assume this is an issue with `sam build`?

Environment:
- newest aws sam cli version
- mac os
- python 3.8

**Comment by mndeveci** [comment]
Thanks for reporting this issue. I will check details with our pip builder, but it might not support building dependencies from source. 

In the meantime, you can also use custom build (Makefile approach) which is defined here to unblock your use case; https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-custom-runtimes.html

**Comment by mndeveci** [comment]
I was able to work on this issue, but when I add that git link to my `requirements.txt` file, it was able to download the dependencies.

requirements.txt;
```
git+https://github.com/collective/icalendar.git@68dc8b18caf0806d2fa1a8e0f06027329ad96c4c
```

When I run `sam build`, I can see some dependencies downloaded into function's built folder (btw, you don't need to provide `--template` and `--build-dir` with those values, since they are already default ones).
```
ls -ltra .aws-sam/build/HelloWorldFunction
total 88
-rw-r--r--   1 user  wheel      0 26 Oct 22:32 __init__.py
-rw-r--r--   1 user  wheel   1151 26 Oct 22:32 app.py
-rw-r--r--   1 user  wheel     99 26 Oct 22:34 requirements.txt
drwxr-xr-x  13 user  wheel    416 26 Oct 22:34 icalendar
drwxr-xr-x   8 user  wheel    256 26 Oct 22:34 icalendar-5.0.0.dist-info
drwxr-xr-x  13 user  wheel    416 26 Oct 22:34 dateutil
drwxr-xr-x   8 user  wheel    256 26 Oct 22:34 python_dateutil-2.8.2.dist-info
drwxr-xr-x   9 user  wheel    288 26 Oct 22:34 pytz
drwxr-xr-x   8 user  wheel    256 26 Oct 22:34 pytz-2022.5.dist-info
-rw-r--r--   1 user  wheel  34549 26 Oct 22:34 six.py
drwxr-xr-x   7 user  wheel    224 26 Oct 22:34 six-1.16.0.dist-info
drwxr-xr-x  13 user  wheel    416 26 Oct 22:34 .
drwxr-xr-x   4 user  wheel    128 26 Oct 22:34 ..
```

It looks like this is already been supported. Let me know if I am missing something to re-produce the issue.

Thanks!

**Comment by Cayllen** [comment]
Okay let me show it on the following screenshots:
The first screen shows the newest commit (6 days ago) including it's change
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/27898791/198827625-b78bfb45-6556-48d3-bb01-737feb875178.png">
This screen shows the git commit of the newest tag of the package (5.0.1) and its changes (7 days ago)
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/27898791/198827697-a48c93bd-de6d-4cd3-baf5-72eb79e87a34.png">

Now when I request the package at the newest commit, I only receive the repository at the newest tag but not actually not the commit I requested
`git+https://github.com/collective/icalendar.git@ca7af0d2fa2690dbf36d06cf11bfffdf0133249b`
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/27898791/198827909-b978a9d6-28b2-4753-af8f-67663b6a1d7d.png">

**Comment by mikegrima** [comment]
I just started experiencing this problem completely out of the blue this morning and I don't know how to overcome it.

I have a `requirements.txt` file that looks like this:

```
cloudaux @ git+https://github.com/mikegrima/cloudaux@TwoPointZero
click
PyYAML
marshmallow
retry
```

This is the error I receive:
```
2023-01-30 12:06:35,850 | Final missing wheels: {cloudaux==2.0.0(sdist)}
2023-01-30 12:06:36,393 | PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.71.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 51, in execute
    package_builder.build_dependencies(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.71.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 157, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.71.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/packager.py", line 262, in build_site_packages
    raise MissingDependencyError(packages_without_wheels)
aws_lambda_builders.workflows.python_pip.packager.MissingDependencyError: {cloudaux==2.0.0(sdist)}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.71.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 348, in run
    action.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.71.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/python_pip/actions.py", line 57, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: {cloudaux==2.0.0(sdist)}

Build Failed
```

As of yesterday this was working perfectly. As of this morning it's broken. I am running the latest `pip` (22.3.1) and `sam` (1.71.0).

**Comment by mikegrima** [comment]
Update: it looks like running the sam CLI with `--use-container` is working, but this wasn't the case previously. Previously this worked without any issues.
