### ISSUE TITLE
Bug: EndpointError: Endpoint URL must be a string, got object at getEndpointUrl

### ISSUE THREAD

**Issue by advsystems-larry** [aws/aws-sam-cli#4363]
### Description:
Attempting to run node.js code to connect to local DynamoDB via sam CLI.

Error occurs whether I am running sam invoke local command via powershell or WSL (Ubuntu 20.04.5).
Error occurs whether I use endpoint of localhost, 127.0.0.1, host.docker.internal, etc. in DynamoDBClient definition.
If I remove the endpoint from the DynamoDBClient definition the function will attempt to connect to AWS.
I can successfully connect to DynamoDB local instance via CLI.
The node.js code below executes within VSCode (run code) and 'npm test' CLI.

### Steps to reproduce:
Setup lambda-local network and DynamoDB:
`docker network create lambda-local`
`docker run -p 8000:8000 --network=lambda-local --name dynamodb-local amazon/dynamodb-local`

Create a table:
`aws dynamodb create-table     --endpoint-url http://localhost:8000     --table-name Table1     --attribute-definitions AttributeName=AAA,AttributeType=S AttributeName=BBB,AttributeType=S     --key-schema AttributeName=AAA,KeyType=HASH AttributeName=BBB,KeyType=RANGE     --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5     --tags Key=Owner,Value=aaa`

Run this code:
import { DynamoDBClient } from "@aws-sdk/client-dynamodb";
const REGION = "local"
const ddbClient = new DynamoDBClient({ region: REGION,  endpoint: 'http://host.docker.internal:8000', sslEnabled: false });
import { ListTablesCommand } from "@aws-sdk/client-dynamodb";
export const lambdaHandler = async (event, context) => {
    try {
            const data = await ddbClient.send(new ListTablesCommand({}));
            console.log(data);
        }
    catch (err) {
        console.error(err);
        return err;
    }
};

//run locally
lambdaHandler();

Via sam local invoke:
`
sam local invoke --docker-network lambda-local ListTablesFunction --debug
`

### Observed result:
$ sam local invoke --docker-network lambda-local ListTablesFunction --debug
2022-11-01 05:48:44,412 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-11-01 05:48:44,413 | Using config file: samconfig.toml, config environment: default
2022-11-01 05:48:44,413 | Expand command line arguments to:
2022-11-01 05:48:44,413 | --template_file=/mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/template.yaml --docker_network=lambda-local --function_logical_id=ListTablesFunction --no_event --layer_cache_basedir=/home/aaa/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2022-11-01 05:48:44,413 | local invoke command is called
2022-11-01 05:48:44,422 | No Parameters detected in the template
2022-11-01 05:48:44,436 | Sam customer defined id is more priority than other IDs. Customer defined id for resource ListTablesFunction is ListTablesFunction
2022-11-01 05:48:44,436 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-11-01 05:48:44,438 | 0 stacks found in the template
2022-11-01 05:48:44,438 | No Parameters detected in the template
2022-11-01 05:48:44,451 | Sam customer defined id is more priority than other IDs. Customer defined id for resource ListTablesFunction is ListTablesFunction
2022-11-01 05:48:44,451 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-11-01 05:48:44,451 | 2 resources found in the stack
2022-11-01 05:48:44,452 | Found Serverless function with name='ListTablesFunction' and CodeUri='ListTablesFunction'
2022-11-01 05:48:44,452 | --base-dir is not presented, adjusting uri ListTablesFunction relative to /mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/template.yaml
2022-11-01 05:48:44,460 | Found one Lambda function with name 'ListTablesFunction'
2022-11-01 05:48:44,460 | Invoking list-tables.lambdaHandler (nodejs16.x)
2022-11-01 05:48:44,460 | No environment variables found for function 'ListTablesFunction'
2022-11-01 05:48:44,461 | Loading AWS credentials from session with profile 'None'
2022-11-01 05:48:44,471 | Resolving code path. Cwd=/mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build, CodeUri=/mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/ListTablesFunction
2022-11-01 05:48:44,472 | Resolved absolute path to code is /mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/ListTablesFunction
2022-11-01 05:48:44,472 | Code /mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/ListTablesFunction is not a zip/jar file
2022-11-01 05:48:44,486 | Skip pulling image and use local one: public.ecr.aws/sam/emulation-nodejs16.x:rapid-1.61.0-x86_64.

2022-11-01 05:48:44,486 | Mounting /mnt/d/dev/workspaces/aaa/lambda-dynamodb-tutorial/.aws-sam/build/ListTablesFunction as /var/task:ro,delegated inside runtime container
2022-11-01 05:48:47,083 | Starting a timer for 30 seconds for function 'ListTablesFunction'
START RequestId: 116023a3-47d4-472b-91aa-0ceee7b97eb2 Version: $LATEST
    at resolveEndpoint (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/resolveEndpoint.js:26:48)1)12:46)s:26:50)ing, got object
END RequestId: 116023a3-47d4-472b-91aa-0ceee7b97eb2
REPORT RequestId: 116023a3-47d4-472b-91aa-0ceee7b97eb2  Init Duration: 0.13 ms  Duration: 6800.83 ms    Billed Duration: 6801 ms        Memory Size: 256 MB     Max Memory Used: 256 MB
{"name":"EndpointError"}2022-11-01 05:48:54,495 | Cleaning all decompressed code dirs
2022-11-01 05:48:54,512 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'b6a9385d-3f38-481a-b1f3-04481f1d2d9b', 'installationId': '430edefd-2d0a-48bf-8698-35b0d47312cd', 'sessionId': '25ca0a44-57ee-4bd8-b742-7c7c8a7eea40', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.61.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'b95da5f8160a063b84be7b26e24ce27dc1a9864b4be400526be2b6302e573a65', 'initialCommit': None}, 'duration': 10099, 'exitReason': 'success', 'exitCode': 0}}]}
2022-11-01 05:48:55,559 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2022-11-01 05:48:55,559 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-11-01 05:48:55,559 | Sending Telemetry: {'metrics': [{'runtimeMetric': {'requestId': '45a26d6e-e764-4153-8727-564464b6499c', 'installationId': '430edefd-2d0a-48bf-8698-35b0d47312cd', 'sessionId': '25ca0a44-57ee-4bd8-b742-7c7c8a7eea40', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.61.0', 'runtimes': ['nodejs16.x']}}]}
2022-11-01 05:48:56,367 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

The log within the docker container this spins up shows more details:
2022-11-01T09:48:53.884Z 116023a3-47d4-472b-91aa-0ceee7b97eb2 ERROR EndpointError: Endpoint URL must be a string, got object at getEndpointUrl (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/getEndpointUrl.js:17:11) at evaluateEndpointRule (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateEndpointRule.js:26:50) at evaluateRules (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateRules.js:11:89) at evaluateTreeRule (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateTreeRule.js:12:46) at evaluateRules (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateRules.js:20:81) at evaluateTreeRule (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateTreeRule.js:12:46) at evaluateRules (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateRules.js:20:81) at evaluateTreeRule (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateTreeRule.js:12:46) at evaluateRules (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/utils/evaluateRules.js:20:81) at resolveEndpoint (/var/task/node_modules/@aws-sdk/util-endpoints/dist-cjs/resolveEndpoint.js:26:48)

### Expected result:

Expecting to see the following as output in log:

{
  '$metadata': {
    httpStatusCode: 200,
    requestId: 'fded58d4-65fb-481a-b42d-bc26b93e0a19',
    extendedRequestId: undefined,
    cfId: undefined,
    attempts: 1,
    totalRetryDelay: 0
  },
  LastEvaluatedTableName: undefined,
  TableNames: [ 'Table1' ]
}

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11
2. `sam --version`: SAM CLI, version 1.61.0
3. AWS region: local

**Comment by hawflau** [comment]
Hey @advsystems-larry, thanks for raising the issue. However, the error was raised from [AWS SDK for Javascript](https://github.com/aws/aws-sdk-js-v3). Please check the [doc](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/interfaces/dynamodbclientconfig.html) of the DynamoDB Client, or raise an issue at the [aws-sdk-js-v3 repo](https://github.com/aws/aws-sdk-js-v3/issues) instead.

**Comment by advsystems-larry** [comment]
Thanks @hawflau.  As the issue only occurs when I run this via sam cli this is why I submitted here.  Please confirm I should raise issue elsewhere.

**Comment by hawflau** [comment]
I tried to reproduce the issue in both Mac OS and in Windows WSL, and didn't see the error you saw. So it doesn't seem like a SAM CLI issue to me. 

Which version of `@aws-sdk/client-dynamodb` are you using? just wondering if upgrading the version would resolve your issue

**Comment by moelasmar** [comment]
Closing due to inactivity. Feel free to re-open if your issue isn't resolved.
