### ISSUE TITLE
Bug: sam init Graal Java17 fails on sam build, Could not find al2-graalvm:gradle image

### ISSUE THREAD

**Issue by refacktor** [aws/aws-sam-cli#4406]
### Description:

sam init with hello world Graal Java 17 doesn't work (fails to Build).

### Steps to reproduce:

- install SAM CLI for Windows (reproduced on latest: v.1.62)
- sam init
- Choose options: 1, 1 - Hello World Example,  N, 6 - graalvm.java17 (provided.al2), 1- gradle, N
- sam build

### Observed result:

ERROR: samcli.local.docker.manager.DockerImagePullFailedException: Could not find al2-graalvm:gradle image locally and failed to pull it from docker.

### Expected result:

A binary should be created without errors.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: tested on two OS: Windows 10 Command Prompt and Windows 10 WSL2 Ubuntu, and the result is the same
2. `sam --version`: SAM CLI, version 1.62.0
3. AWS region: us-west-1

`Add --debug flag to command you are running`

```
# sam build --debug
2022-11-12 12:47:41,818 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-11-12 12:47:41,819 | Using config file: samconfig.toml, config environment: default
2022-11-12 12:47:41,822 | Expand command line arguments to:
2022-11-12 12:47:41,823 | --template_file=C:\temp\bugreport\sam-app\template.yaml --use_container --build_image=('al2-graalvm:gradle',) --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2022-11-12 12:47:43,664 | 'build' command is called
2022-11-12 12:47:43,664 | Starting Build inside a container
2022-11-12 12:47:43,672 | No Parameters detected in the template
2022-11-12 12:47:43,700 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-11-12 12:47:43,700 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-11-12 12:47:43,706 | 0 stacks found in the template
2022-11-12 12:47:43,706 | No Parameters detected in the template
2022-11-12 12:47:43,753 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-11-12 12:47:43,754 | There is no customer defined id or cdk path defined for resource ServerlessHttpApi, so we will use the resource logical id as the resource id
2022-11-12 12:47:43,758 | 2 resources found in the stack
2022-11-12 12:47:43,758 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2022-11-12 12:47:43,761 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to C:\temp\bugreport\sam-app\template.yaml
2022-11-12 12:47:43,769 | Your template contains a resource with logical ID "ServerlessHttpApi", which is a reserved logical ID in AWS SAM. It could result in unexpected behaviors and is not recommended.
2022-11-12 12:47:43,769 | 2 resources found in the stack
2022-11-12 12:47:43,770 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2022-11-12 12:47:43,771 | Instantiating build definitions
2022-11-12 12:47:43,774 | No previous build graph found, generating new one
2022-11-12 12:47:43,774 | Unique function build definition found, adding as new (Function Build Definition: BuildDefinition(provided.al2, C:\temp\bugreport\sam-app\HelloWorldFunction, Zip, , 9cabb488-0c5f-4211-9e7f-a4bba3cd6af6, {'BuildMethod': 'makefile'}, {}, x86_64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='provided.al2', memory=256, timeout=20, handler='helloworld.App::handleRequest', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\temp\\bugreport\\sam-app\\HelloWorldFunction', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'HttpApi', 'Properties': {'Path': '/hello', 'Method': 'get', 'ApiId': 'ServerlessHttpApi'}}}, metadata={'BuildMethod': 'makefile', 'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2022-11-12 12:47:43,778 | Building codeuri: C:\temp\bugreport\sam-app\HelloWorldFunction runtime: provided.al2 metadata: {'BuildMethod': 'makefile'} architecture: x86_64 functions: HelloWorldFunction
2022-11-12 12:47:43,783 | Building to following folder C:\temp\bugreport\sam-app\.aws-sam\build\HelloWorldFunction
2022-11-12 12:47:46,753 | Failed to download image with name al2-graalvm:gradle
2022-11-12 12:47:46,753 | Container was not created. Skipping deletion
2022-11-12 12:47:46,934 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-11-12 12:47:46,934 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '675738f5-7f27-42e2-a1d6-fe3b7c79a42f', 'installationId': '59075350-b5ce-496d-94ba-2f71c3166276', 'sessionId': '57c31b7e-bd0e-4ef1-be9a-8ca46b855ec2', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.62.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 5115, 'exitReason': 'DockerImagePullFailedException', 'exitCode': 255}}]}
2022-11-12 12:47:46,934 | Unable to find Click Context for getting session_id.
2022-11-12 12:47:46,941 | Sending Telemetry: {'metrics': [{'events': {'requestId': '0e7a4601-d564-4bbd-a0ac-12fa5bd26db7', 'installationId': '59075350-b5ce-496d-94ba-2f71c3166276', 'sessionId': '57c31b7e-bd0e-4ef1-be9a-8ca46b855ec2', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.62.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'provided-None', 'thread_id': 2556, 'time_stamp': '2022-11-12 20:47:43.792'}]}}}]}
2022-11-12 12:47:47,347 | Telemetry response: 200
2022-11-12 12:47:47,362 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localnpipe/v1.35/images/create?tag=gradle&fromImage=al2-graalvm%3Agradle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 160, in pull_image
    result_itr = self.docker_client.api.pull(image_name, tag=tag, stream=True, decode=True)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\image.py", line 415, in pull
    self._raise_for_status(response)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("pull access denied for al2-graalvm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 85, in create
    self.pull_image(image_name)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 163, in pull_image
    raise DockerImagePullFailedException(str(ex)) from ex
samcli.local.docker.manager.DockerImagePullFailedException: 404 Client Error: Not Found ("pull access denied for al2-graalvm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 176, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 126, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 86, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 177, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 257, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 252, in run
    build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 221, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 80, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 90, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 163, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 645, in _build_function
    return self._build_function_on_container(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 822, in _build_function_on_container
    self._container_manager.run(container)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 115, in run
    self.create(container)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 88, in create
    raise DockerImagePullFailedException(
samcli.local.docker.manager.DockerImagePullFailedException: Could not find al2-graalvm:gradle image locally and failed to pull it from docker.
```

**Comment by moelasmar** [comment]
There is some issue in the steps you followed to build this project that you can find in the README file generated in your local project based on [this file](https://github.com/aws/aws-sam-cli-app-templates/blob/master/provided.al2/graalvm/java11/cookiecutter-aws-sam-graalvm-gradle/%7B%7Bcookiecutter.project_name%7D%7D/README.md).
Before you execute `sam build`, you need to execute `docker build -t al2-graalvm:gradle .` to build the `al2-graalvm:gradle` image that will be used by SAM CLI to build this project.

**Comment by moelasmar** [comment]
Please let us know if you still have any issues

**Comment by refacktor** [comment]
Thank you, this worked.
