### ISSUE TITLE
`build --use-container` fails on Lima/macOS recently

### ISSUE THREAD

**Issue by sohtsuka** [aws/aws-sam-cli#4514]
### Description:

Building a SAM tutorial app inside Docker container fails with "operation not permitted" on recently created [Lima](https://github.com/lima-vm/lima) VMs.

### Steps to reproduce:

1. Setup SAM CLI and create Hello World Application following [the tutorial's step](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-getting-started-hello-world.html)
2. `brew install lima`
3. `limactl start --name docker-new https://raw.githubusercontent.com/lima-vm/lima/master/examples/docker.yaml`
4. Select "Open an editor to review or modify the current configuration"
5. To match the versions, replace `curl -fsSL https://get.docker.com | sh` with the following lines:
   ```
       export VERSION=20.10.21
       curl -fsSL https://get.docker.com | perl -pe 's/(containerd\.io)/$1=1.6.9-1/' | sh
   ```
6. Save the file and exit to create a new VM.
7. `DOCKER_HOST="unix://$HOME/.lima/docker-new/sock/docker.sock" sam build --use-container --debug`

### Observed result:

```
satoshi@Nightingale2 sam-app % DOCKER_HOST="unix://$HOME/.lima/docker-new/sock/docker.sock" sam build --use-container --debug
2022-12-24 21:01:34,962 | Config file location: /Users/satoshi/src/sam-app/samconfig.toml
2022-12-24 21:01:34,962 | Config file '/Users/satoshi/src/sam-app/samconfig.toml' does not exist
2022-12-24 21:01:34,966 | Using SAM Template at /Users/satoshi/src/sam-app/template.yaml
2022-12-24 21:01:35,021 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-12-24 21:01:35,021 | Using config file: samconfig.toml, config environment: default
2022-12-24 21:01:35,021 | Expand command line arguments to:
2022-12-24 21:01:35,021 | --template_file=/Users/satoshi/src/sam-app/template.yaml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-12-24 21:01:35,108 | 'build' command is called
2022-12-24 21:01:35,108 | Starting Build inside a container
2022-12-24 21:01:35,112 | No Parameters detected in the template
2022-12-24 21:01:35,119 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,119 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,119 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,119 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,120 | 0 stacks found in the template
2022-12-24 21:01:35,120 | No Parameters detected in the template
2022-12-24 21:01:35,125 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,125 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,125 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,125 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-12-24 21:01:35,125 | 4 resources found in the stack 
2022-12-24 21:01:35,125 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2022-12-24 21:01:35,125 | --base-dir is not presented, adjusting uri hello_world/ relative to /Users/satoshi/src/sam-app/template.yaml
2022-12-24 21:01:35,139 | 4 resources found in the stack 
2022-12-24 21:01:35,139 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2022-12-24 21:01:35,139 | Instantiating build definitions
2022-12-24 21:01:35,141 | Same function build definition found, adding function (Previous: BuildDefinition(python3.9, /Users/satoshi/src/sam-app/hello_world, Zip, , e58cb5f1-6ede-48be-a52b-215991627cbc, {}, {}, arm64, []), Current: BuildDefinition(python3.9, /Users/satoshi/src/sam-app/hello_world, Zip, , e513a092-0aa2-4fdb-9c33-961a688d5d69, {}, {}, arm64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='python3.9', memory=128, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/satoshi/src/sam-app/hello_world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['arm64'], function_url_config=None, stack_path=''))
2022-12-24 21:01:35,141 | Building codeuri: /Users/satoshi/src/sam-app/hello_world runtime: python3.9 metadata: {} architecture: arm64 functions: HelloWorldFunction
2022-12-24 21:01:35,142 | Building to following folder /Users/satoshi/src/sam-app/.aws-sam/build/HelloWorldFunction

Fetching public.ecr.aws/sam/build-python3.9:latest-arm64 Docker container image..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2022-12-24 21:02:42,939 | Mounting /Users/satoshi/src/sam-app/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch --exists-action i
Full dependency closure: {certifi==2022.12.7(wheel), idna==3.4(wheel), charset-normalizer==2.1.1(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel)}
initial compatible: {certifi==2022.12.7(wheel), idna==3.4(wheel), charset-normalizer==2.1.1(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel)}
initial incompatible: set()
Downloading missing wheels: set()
compatible wheels after second download pass: {certifi==2022.12.7(wheel), idna==3.4(wheel), charset-normalizer==2.1.1(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel)}
Build missing wheels from sdists (C compiling True): set()
compatible after building wheels (no C compiling): {certifi==2022.12.7(wheel), idna==3.4(wheel), charset-normalizer==2.1.1(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {certifi==2022.12.7(wheel), idna==3.4(wheel), charset-normalizer==2.1.1(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel)}
Final compatible: {charset-normalizer==2.1.1(wheel), certifi==2022.12.7(wheel), urllib3==1.26.13(wheel), requests==2.28.1(wheel), idna==3.4(wheel)}
Final incompatible: set()
Final missing wheels: set()
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
Copying source file (/tmp/samcli/source/requirements.txt) to destination (/tmp/samcli/artifacts/requirements.txt)
Copying source file (/tmp/samcli/source/__init__.py) to destination (/tmp/samcli/artifacts/__init__.py)
Copying source file (/tmp/samcli/source/app.py) to destination (/tmp/samcli/artifacts/app.py)
PythonPipBuilder:CopySource succeeded
2022-12-24 21:02:44,458 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
2022-12-24 21:02:44,458 | Build inside container was successful. Copying artifacts from container to host
2022-12-24 21:02:44,586 | Copying from container: /tmp/samcli/artifacts/. -> /Users/satoshi/src/sam-app/.aws-sam/build/HelloWorldFunction
2022-12-24 21:02:44,669 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-12-24 21:02:44,669 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '0370b064-ad70-4289-897b-834d7367cd2e', 'installationId': '0f6e00d2-ab34-495c-8178-91be73f9e710', 'sessionId': '8c8e4c2f-1db7-4ba7-bf49-5dcf5a936518', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.67.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 69649, 'exitReason': 'APIError', 'exitCode': 255}}]}
2022-12-24 21:02:44,669 | Unable to find Click Context for getting session_id.
2022-12-24 21:02:44,671 | Sending Telemetry: {'metrics': [{'events': {'requestId': 'd597bfb6-cf04-4504-8883-831fe6c51e0c', 'installationId': '0f6e00d2-ab34-495c-8178-91be73f9e710', 'sessionId': '8c8e4c2f-1db7-4ba7-bf49-5dcf5a936518', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.67.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'python-pip', 'thread_id': 4347790720, 'time_stamp': '2022-12-24 12:01:35.142'}]}}}]}
2022-12-24 21:02:45,406 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2022-12-24 21:02:45,407 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Traceback (most recent call last):
  File "docker/api/client.py", line 261, in _raise_for_status
  File "requests/models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/containers/2172baa55a9c11610b7e76ce7fa99e5037400aba5f78d13748dc1e14ba4bb17d/archive?path=%2Ftmp%2Fsamcli%2Fartifacts%2F.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/__main__.py", line 12, in <module>
  File "click/core.py", line 1130, in __call__
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 194, in wrapped
  File "samcli/lib/telemetry/metric.py", line 140, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 86, in wrapper
  File "samcli/commands/build/command.py", line 186, in cli
  File "samcli/commands/build/command.py", line 276, in do_cli
  File "samcli/commands/build/build_context.py", line 256, in run
  File "samcli/lib/build/app_builder.py", line 210, in build
  File "samcli/lib/build/build_strategy.py", line 80, in build
  File "samcli/lib/build/build_strategy.py", line 90, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 163, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 682, in _build_function
  File "samcli/lib/build/app_builder.py", line 942, in _build_function_on_container
  File "samcli/local/docker/container.py", line 374, in copy
  File "docker/models/containers.py", line 258, in get_archive
  File "docker/utils/decorators.py", line 19, in wrapped
  File "docker/api/container.py", line 734, in get_archive
  File "docker/api/client.py", line 263, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 500 Server Error: Internal Server Error ("remount-ro /home/satoshi.linux/.local/share/docker/overlay2/11c92b167e38222631755be31c33ebe72ad3bf3b6691900751ea4f7f50cb6689/merged/tmp/samcli/source, flags: 0x5021: operation not permitted")
[3465] Failed to execute script '__main__' due to unhandled exception!
```

### Expected result:

When I use the vm which was created previously (on November 22), the same app builds successfully.

```
satoshi@Nightingale2 sam-app % DOCKER_HOST="unix://$HOME/.lima/docker/sock/docker.sock" sam build --use-container --debug
2022-12-24 20:45:27,852 | Config file location: /Users/satoshi/src/sam-app/samconfig.toml
2022-12-24 20:45:27,852 | Config file '/Users/satoshi/src/sam-app/samconfig.toml' does not exist
2022-12-24 20:45:27,857 | Using SAM Template at /Users/satoshi/src/sam-app/template.yaml
2022-12-24 20:45:27,899 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-12-24 20:45:27,899 | Using config file: samconfig.toml, config environment: default
2022-12-24 20:45:27,899 | Expand command line arguments to:
2022-12-24 20:45:27,899 | --template_file=/Users/satoshi/src/sam-app/template.yaml --use_container --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2022-12-24 20:45:27,996 | 'build' command is called
2022-12-24 20:45:27,996 | Starting Build inside a container
2022-12-24 20:45:28,000 | No Parameters detected in the template
2022-12-24 20:45:28,007 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,007 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,007 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,007 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,008 | 0 stacks found in the template
2022-12-24 20:45:28,008 | No Parameters detected in the template
2022-12-24 20:45:28,013 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,013 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,013 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,013 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2022-12-24 20:45:28,013 | 4 resources found in the stack 
2022-12-24 20:45:28,013 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2022-12-24 20:45:28,013 | --base-dir is not presented, adjusting uri hello_world/ relative to /Users/satoshi/src/sam-app/template.yaml
2022-12-24 20:45:28,018 | 4 resources found in the stack 
2022-12-24 20:45:28,018 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2022-12-24 20:45:28,018 | Instantiating build definitions
2022-12-24 20:45:28,020 | Same function build definition found, adding function (Previous: BuildDefinition(python3.9, /Users/satoshi/src/sam-app/hello_world, Zip, , e58cb5f1-6ede-48be-a52b-215991627cbc, {}, {}, arm64, []), Current: BuildDefinition(python3.9, /Users/satoshi/src/sam-app/hello_world, Zip, , 265478dd-15e7-4f54-8796-01edbe80bb0a, {}, {}, arm64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='python3.9', memory=128, timeout=3, handler='app.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/satoshi/src/sam-app/hello_world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['arm64'], function_url_config=None, stack_path=''))
2022-12-24 20:45:28,020 | Building codeuri: /Users/satoshi/src/sam-app/hello_world runtime: python3.9 metadata: {} architecture: arm64 functions: HelloWorldFunction
2022-12-24 20:45:28,020 | Building to following folder /Users/satoshi/src/sam-app/.aws-sam/build/HelloWorldFunction

Fetching public.ecr.aws/sam/build-python3.9:latest-arm64 Docker container image...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2022-12-24 20:46:29,915 | Mounting /Users/satoshi/src/sam-app/hello_world as /tmp/samcli/source:ro,delegated inside runtime container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Running workflow 'PythonPipBuilder'
Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest /tmp/samcli/scratch --exists-action i
Full dependency closure: {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
initial compatible: {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
initial incompatible: set()
Downloading missing wheels: set()
compatible wheels after second download pass: {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
Build missing wheels from sdists (C compiling True): set()
compatible after building wheels (no C compiling): {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
Build missing wheels from sdists (C compiling False): set()
compatible after building wheels (C compiling): {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
Final compatible: {requests==2.28.1(wheel), urllib3==1.26.13(wheel), idna==3.4(wheel), certifi==2022.12.7(wheel), charset-normalizer==2.1.1(wheel)}
Final incompatible: set()
Final missing wheels: set()
PythonPipBuilder:ResolveDependencies succeeded
Running PythonPipBuilder:CopySource
Copying source file (/tmp/samcli/source/requirements.txt) to destination (/tmp/samcli/artifacts/requirements.txt)
Copying source file (/tmp/samcli/source/__init__.py) to destination (/tmp/samcli/artifacts/__init__.py)
Copying source file (/tmp/samcli/source/app.py) to destination (/tmp/samcli/artifacts/app.py)
PythonPipBuilder:CopySource succeeded
2022-12-24 20:46:31,564 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "result": {"artifacts_dir": "/tmp/samcli/artifacts"}}
2022-12-24 20:46:31,565 | Build inside container was successful. Copying artifacts from container to host
2022-12-24 20:46:31,721 | Copying from container: /tmp/samcli/artifacts/. -> /Users/satoshi/src/sam-app/.aws-sam/build/HelloWorldFunction
2022-12-24 20:46:31,843 | Build inside container succeeded
2022-12-24 20:46:31,844 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2022-12-24 20:46:31,844 | There is no customer defined id or cdk path defined for resource ApplicationResourceGroup, so we will use the resource logical id as the resource id
2022-12-24 20:46:31,844 | There is no customer defined id or cdk path defined for resource ApplicationInsightsMonitoring, so we will use the resource logical id as the resource id
2022-12-24 20:46:31,844 | 4 resources found in the stack 
2022-12-24 20:46:31,844 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
2022-12-24 20:46:31,890 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2022-12-24 20:46:31,890 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '1b47c844-fd8d-4661-958c-19e2e5423f3f', 'installationId': '0f6e00d2-ab34-495c-8178-91be73f9e710', 'sessionId': '2dad01ca-945a-4016-ab4b-f7ac68485f33', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.67.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 63992, 'exitReason': 'success', 'exitCode': 0}}]}
2022-12-24 20:46:31,891 | Unable to find Click Context for getting session_id.
2022-12-24 20:46:31,894 | Sending Telemetry: {'metrics': [{'events': {'requestId': '52b29b91-8fa0-4849-853b-51f5af919f43', 'installationId': '0f6e00d2-ab34-495c-8178-91be73f9e710', 'sessionId': '2dad01ca-945a-4016-ab4b-f7ac68485f33', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.67.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'python-pip', 'thread_id': 4307568000, 'time_stamp': '2022-12-24 11:45:28.020'}, {'event_name': 'BuildFunctionRuntime', 'event_value': 'python3.9', 'thread_id': 4307568000, 'time_stamp': '2022-12-24 11:46:31.846'}]}}}]}
2022-12-24 20:46:32,408 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2022-12-24 20:46:32,423 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Monterey (M1 MacBook)
2. `sam --version`: SAM CLI, version 1.67.0
3. AWS region: N/A

New VM environment:
```
satoshi@Nightingale2 sam-app % DOCKER_HOST="unix://$HOME/.lima/docker-new/sock/docker.sock" docker info                     
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.816GiB
 Name: lima-docker-new
 ID: QS4Q:QY6V:Z6HL:4RPV:5QMH:MXEU:W3AP:34HO:SGIA:4AI5:WV4P:PRUA
 Docker Root Dir: /home/satoshi.linux/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Old VM environment:
```
satoshi@Nightingale2 sam-app % DOCKER_HOST="unix://$HOME/.lima/docker/sock/docker.sock" docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.9.1)
  compose: Docker Compose (Docker Inc., v2.13.0)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.16)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.22.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.21
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 1c90a442489720eec95342e1789ee8a5e1b9536f
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
  rootless
  cgroupns
 Kernel Version: 5.15.0-56-generic
 Operating System: Ubuntu 22.04.1 LTS
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.816GiB
 Name: lima-docker
 ID: FMQ3:Y373:AEU7:AANR:TQUI:D5EY:OER6:LMW7:GCXF:OLB6:YPGQ:DXNZ
 Docker Root Dir: /home/satoshi.linux/.local/share/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by sohtsuka** [comment]
Sorry, I forgot that I changed the mount type in the VM created in the past. Adding `mountType: "9p"` at the reproducing step 5 solves the problem.

```
mountType: "9p" # add this
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```

Closing as this seems to be not a SAM CLI's problem.
