### ISSUE TITLE
Failed to upload artifiacts reference by ImageUri parameter

### ISSUE THREAD

**Issue by overide** [aws/aws-sam-cli#4520]
### Description:

While deploying container-based lambda function, I'm getting following error while uploading artifacts - 

"Error: Unable to upload artifact designfileprocessorfunction:python3.8-v1 referenced by ImageUri parameter of DesignFileProcessorFunction resource."

It was working fine earlier but for some reason, i had to delete the function deployed earlier after that I started getting this error. I tried `sam init` again in the fresh repo but it's not working. I can ensure that the credentials which are used for deployment have full access to S3 and other resources required because I used the same credentials earlier when it was working.

### Steps to reproduce:

Not sure what caused the issue in the first place. But what I did is the following - 

1. manually deleted the lambda function from the dashboard
2. manually deleted the ECR repository from the dashboard
3. manually deleted the template file uploaded to the s3 bucket
4. Deleted the created stack

And then I started getting this error

### Observed result:

```
57f2e9e285fe: Retrying in 1 second 
05e9f9113373: Retrying in 1 second 
48d63b5ff760: Retrying in 1 second 
42b083fe41be: Retrying in 1 second 
c72e93ffa43c: Retrying in 1 second 
12687c68cc5b: Waiting 
514002f9568e: Waiting 
0ddec189c7fb: Waiting 
1b3202e12ccc: Waiting 
ca7b239716ed: Waiting 
237a70518fc1: Waiting 
9c65f3d42a3e: Waiting 
6c9a1c0881ee: Waiting 
07bac42da939: Waiting 
2022-12-29 18:45:47,798 | Unable to export
Traceback (most recent call last):
  File "samcli/lib/package/ecr_uploader.py", line 93, in upload
  File "samcli/lib/docker/log_streamer.py", line 56, in stream_progress
  File "samcli/lib/docker/log_streamer.py", line 77, in _stream_write
samcli.lib.docker.log_streamer.LogStreamError: EOF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "samcli/lib/package/packageable_resources.py", line 274, in export
  File "samcli/lib/package/packageable_resources.py", line 288, in do_export
  File "samcli/lib/package/utils.py", line 120, in upload_local_image_artifacts
  File "samcli/lib/package/ecr_uploader.py", line 101, in upload
samcli.commands.package.exceptions.DockerPushFailedError: EOF

2022-12-29 18:45:47,825 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'c81b5b30-ab9a-4072-a129-17dfe0670a63', 'installationId': '0d06f16d-7073-4faa-b74e-ad4c6ba58237', 'sessionId': 'cebbd703-4f75-4505-a75d-cc2ab5d83b06', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.67.0', 'awsProfileProvided': True, 'debugFlagProvided': True, 'region': 'ap-south-1', 'commandName': 'sam deploy', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '1ced9284d1713fe599b6d493246f20def9585e2113b86009b48ee00e20d2e9e1', 'initialCommit': None}, 'duration': 78462, 'exitReason': 'ExportFailedError', 'exitCode': 1}}]}

2022-12-29 18:45:48,901 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: Unable to upload artifact designfileprocessorfunction:python3.8-v1 referenced by ImageUri parameter of DesignFileProcessorFunction resource.
EOF
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ubuntu 20.04.5
2. `sam --version`: 1.67.0
3. AWS region: ap-south-1

My Template file looks like this - 

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for design-file-processor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 10000
    Tracing: Active
    Environment:
      Variables:
        GDAL_DATA: /opt/share/gdal
        PROJ_LIB:  /opt/share/proj
        MONGODB_HOST: '******'
  Api:
    TracingEnabled: true

Resources:
  DesignFileProcessorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Policies:
      - AmazonS3FullAccess
      FunctionName: 'design-file-processor'
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        DesignFileProcessor:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /design-file-processor
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./design_file_processor
      DockerTag: python3.8-v1

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Fn::Join:
        - ''
        - - ApplicationInsights-SAM-
          - Ref: AWS::StackName
      AutoConfigurationEnabled: 'true'
    DependsOn: ApplicationResourceGroup
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DesignFileProcessorApi:
    Description: API Gateway endpoint URL for Prod stage for DesignFileProcessor function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/design-file-processor/"
  DesignFileProcessorFunction:
    Description: DesignFileProcessor Lambda Function ARN
    Value: !GetAtt DesignFileProcessorApi.Arn
  DesignFileProcessorFunctionIamRole:
    Description: Implicit IAM Role created for DesignFileProcessor function
    Value: !GetAtt DesignFileProcessorFunctionRole.Arn
```

**Comment by overide** [comment]
Got the issue, I had to delete the ECR repo stack for my function cloud formation dashboard. After doing this it started working as expected. Closing this issue
