### ISSUE TITLE
Bug: upgrading from node14 to node16 fails in sam build

### ISSUE THREAD

**Issue by wanisfahmyDE** [aws/aws-sam-cli#4533]
### Description:

After upgrading from node14, to node16. running `sam build` fails, stacktrace below.
switching back to node14 works again

### Steps to reproduce:

```bash
nvm use v16
npm install
npm run build
npm run test
sam build #fails
```

### Observed result:

```bash
2023-01-04 11:01:36,010 | Config file location: /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/samconfig.toml
2023-01-04 11:01:36,010 | Config file '/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/samconfig.toml' does not exist
2023-01-04 11:01:36,015 | Using SAM Template at /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/template.yaml
2023-01-04 11:01:36,159 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-01-04 11:01:36,159 | Using config file: samconfig.toml, config environment: default
2023-01-04 11:01:36,159 | Expand command line arguments to:
2023-01-04 11:01:36,159 | --template_file=/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache
2023-01-04 11:01:36,890 | 'build' command is called
2023-01-04 11:01:36,895 | Collected default values for parameters: {'AivenTokenSecretName': 'AivenTokenSecret', 'InitialAivenToken': 'INITIAL_AIVEN_TOKEN'}
2023-01-04 11:01:36,921 | There is no customer defined id or cdk path defined for resource AivenTokenSecret, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,921 | There is no customer defined id or cdk path defined for resource AiventTokenSecretRotationSchedule, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,921 | There is no customer defined id or cdk path defined for resource AivenTokenRotationFunction, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,921 | There is no customer defined id or cdk path defined for resource Permission, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,921 | 0 stacks found in the template
2023-01-04 11:01:36,922 | Collected default values for parameters: {'AivenTokenSecretName': 'AivenTokenSecret', 'InitialAivenToken': 'INITIAL_AIVEN_TOKEN'}
2023-01-04 11:01:36,928 | There is no customer defined id or cdk path defined for resource AivenTokenSecret, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,928 | There is no customer defined id or cdk path defined for resource AiventTokenSecretRotationSchedule, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,928 | There is no customer defined id or cdk path defined for resource AivenTokenRotationFunction, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,928 | There is no customer defined id or cdk path defined for resource Permission, so we will use the resource logical id as the resource id
2023-01-04 11:01:36,928 | 4 resources found in the stack
2023-01-04 11:01:36,928 | Found Serverless function with name='AivenTokenRotationFunction' and CodeUri='.'
2023-01-04 11:01:36,928 | --base-dir is not presented, adjusting uri . relative to /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/template.yaml
2023-01-04 11:01:36,977 | 4 resources found in the stack
2023-01-04 11:01:36,977 | Found Serverless function with name='AivenTokenRotationFunction' and CodeUri='.'
2023-01-04 11:01:36,981 | Instantiating build definitions
2023-01-04 11:01:36,982 | Same function build definition found, adding function (Previous: BuildDefinition(nodejs16.x, /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation, Zip, , 06814d06-3770-45e7-a20c-8339ca2c7ba2, {}, {}, x86_64, []), Current: BuildDefinition(nodejs16.x, /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation, Zip, , fa65ec29-255e-4bd5-88e4-cdeb64994471, {}, {}, x86_64, []), Function: Function(function_id='AivenTokenRotationFunction', name='AivenTokenRotationFunction', functionname='AivenTokenRotationFunction', runtime='nodejs16.x', memory=256, timeout=3, handler='dist/app.secretHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation', environment=None, rolearn=None, layers=[], events=None, metadata={'SamResourceId': 'AivenTokenRotationFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path=''))
2023-01-04 11:01:36,983 | Building codeuri: /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation runtime: nodejs16.x metadata: {} architecture: x86_64 functions: AivenTokenRotationFunction
2023-01-04 11:01:36,983 | Building to following folder /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
2023-01-04 11:01:36,984 | Loading workflow module 'aws_lambda_builders.workflows'
2023-01-04 11:01:37,000 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-01-04 11:01:37,004 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-01-04 11:01:37,007 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-01-04 11:01:37,011 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-01-04 11:01:37,019 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-01-04 11:01:37,025 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-01-04 11:01:37,039 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-01-04 11:01:37,042 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-01-04 11:01:37,051 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-01-04 11:01:37,051 | Found workflow 'NodejsNpmBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-01-04 11:01:37,051 | Running workflow 'NodejsNpmBuilder'
2023-01-04 11:01:37,052 | Running NodejsNpmBuilder:NpmPack
2023-01-04 11:01:37,052 | NODEJS packaging file:/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation to /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7
2023-01-04 11:01:37,052 | executing NPM: ['npm', 'pack', '-q', 'file:/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation']
2023-01-04 11:01:39,092 | NODEJS packed to aiven-token-rotation-1.0.0.tgz
2023-01-04 11:01:39,092 | NODEJS extracting to /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked
2023-01-04 11:01:39,097 | NodejsNpmBuilder:NpmPack succeeded
2023-01-04 11:01:39,097 | Running NodejsNpmBuilder:CopyNpmrcAndLockfile
2023-01-04 11:01:39,097 | package-lock.json copying in: /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package
2023-01-04 11:01:39,102 | NodejsNpmBuilder:CopyNpmrcAndLockfile succeeded
2023-01-04 11:01:39,102 | Running NodejsNpmBuilder:CopySource
2023-01-04 11:01:39,103 | Creating target folders at /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
2023-01-04 11:01:39,103 | Copying directory metadata from source (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction)
2023-01-04 11:01:39,103 | Copying source file (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/LICENSE) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/LICENSE)
2023-01-04 11:01:39,105 | Creating target folders at /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/dist
2023-01-04 11:01:39,105 | Copying directory metadata from source (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/dist) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/dist)
2023-01-04 11:01:39,105 | Copying source file (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/dist/app.js) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/dist/app.js)
2023-01-04 11:01:39,126 | Copying source file (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/README.md) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/README.md)
2023-01-04 11:01:39,127 | Copying source file (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/package-lock.json) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/package-lock.json)
2023-01-04 11:01:39,129 | Copying source file (/var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/tmpd4fugje7/unpacked/package/package.json) to destination (/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/package.json)
2023-01-04 11:01:39,131 | NodejsNpmBuilder:CopySource succeeded
2023-01-04 11:01:39,131 | Running NodejsNpmBuilder:NpmInstall
2023-01-04 11:01:39,131 | NODEJS installing in: /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
2023-01-04 11:01:39,131 | executing NPM: ['npm', 'install', '-q', '--no-audit', '--no-save', '--unsafe-perm', '--production']
2023-01-04 11:01:40,031 | NodejsNpmBuilder:NpmInstall failed
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 110, in execute
    self.subprocess_npm.run(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm WARN config production Use `--omit=dev` instead.
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
npm ERR! command failed
npm ERR! command sh /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/prepare-a2f3d961.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflow.py", line 301, in run
    action.execute()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 115, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: NPM Failed: npm WARN config production Use `--omit=dev` instead.
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
npm ERR! command failed
npm ERR! command sh /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/prepare-a2f3d961.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log

Build Failed
2023-01-04 11:01:40,089 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-01-04 11:01:40,089 | Unable to find Click Context for getting session_id.
2023-01-04 11:01:40,090 | Sending Telemetry: {'metrics': [{'events': {'requestId': 'c16a8afe-61c8-4d73-9c31-8951f761a122', 'installationId': '0378e67e-563f-45ba-b2f2-cfc63c59618e', 'sessionId': 'd1e3a92c-a8c1-4023-a4b9-94253f9ed416', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.16', 'samcliVersion': '1.67.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'nodejs-npm', 'thread_id': 4313924992, 'time_stamp': '2023-01-04 10:01:36.983'}]}}}]}
2023-01-04 11:01:40,090 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'df46d175-8bf8-4bed-b68c-3e951dd55679', 'installationId': '0378e67e-563f-45ba-b2f2-cfc63c59618e', 'sessionId': 'd1e3a92c-a8c1-4023-a4b9-94253f9ed416', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.16', 'samcliVersion': '1.67.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'cf52eca45e0aec61302e91b315c6efd12b059ae1a18ccbdcd443f0908e7fece6', 'initialCommit': None}, 'duration': 3929, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2023-01-04 11:01:40,787 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: NodejsNpmBuilder:NpmInstall - NPM Failed: npm WARN config production Use `--omit=dev` instead.
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
npm ERR! command failed
npm ERR! command sh /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/prepare-a2f3d961.sh

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log
2023-01-04 11:01:40,788 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
```

### Expected result:

Build succeeds

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOS 
2. `sam --version`: 1.67.0
3. AWS region: eu-central-1

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @wanisfahmyDE, thanks for reporting the issue. Could you please also provide a sample application to help reproduce the issue? At a minimum, knowing what your `template.yml` and `package.json` look like would be helpful.

**Comment by wanisfahmyDE** [comment]
Hey @hawflau,

Sure thing!

`template.yaml`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AivenTokenRotation

  SAM Template for AivenTokenRotation setup

Metadata:
  AWS::ServerlessRepo::Application:
    Name: aiven-token-rotation
    Description: Store and rotate a aiven token for use in e.g. github actions
    Author: xxx
    Labels: [ 'secrets', 'manager','aiven','rotation','token' ]
    HomePageUrl: xxx
    ReadmeUrl: README.md
    SemanticVersion: 0.0.1
    SourceCodeUrl: xxx
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE

Globals:
  Function:
    Timeout: 3

Parameters:
  AivenTokenSecretName:
    Description: Name of the secrets manager secret
    Type: String
    Default: AivenTokenSecret
  InitialAivenToken:
    Description: The aiven token which was created manually first
    Type: String
    Default: INITIAL_AIVEN_TOKEN

Resources:
  AivenTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref AivenTokenSecretName
      Description: Secret where the aiven token will be stored
      SecretString: !Ref InitialAivenToken
  AiventTokenSecretRotationSchedule:
    Type: AWS::SecretsManager::RotationSchedule
    Properties:
      SecretId: !Ref AivenTokenSecret
      RotationLambdaARN: !GetAtt AivenTokenRotationFunction.Arn
      RotateImmediatelyOnUpdate: True
      RotationRules:
        AutomaticallyAfterDays: 7
  AivenTokenRotationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AivenTokenRotationFunction
      Handler: dist/app.secretHandler
      Runtime: nodejs14.x
      MemorySize: 256
      Architectures:
        - x86_64
      Policies:
        - AWSSecretsManagerRotationPolicy:
            FunctionName: AivenTokenRotationFunction
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AivenTokenRotationFunction.Arn
      Principal: secretsmanager.amazonaws.com

Outputs:
  AivenTokenRotationFunction:
    Description: "Aiven Token Rotation Lambda Function ARN"
    Value: !GetAtt AivenTokenRotationFunction.Arn

```

`package.json`
```json
{
  "name": "aiven-token-rotation",
  "version": "1.0.0",
  "description": "Rotate Aiven Tokens via a Lambda function in conjunction with the AWS SecretsManager",
  "main": "dist/app.js",
  "repository": "xxx",
  "author": "idealo internet GmbH",
  "license": "MIT",
  "private": true,
  "files": [
    "dist/**/*.js"
  ],
  "dependencies": {
    "node-fetch": "^2.6.7"
  },
  "scripts": {
    "test": "jest",
    "test:cov": "jest --coverage",
    "prepack": "npm run build",
    "prebuild": "rimraf dist",
    "build": "tsc",
    "prepare": "husky install",
    "format": "prettier --write \"src/**/*.ts\"",
    "lint": "eslint 'src/**/*.ts'",
    "lint:json": "eslint 'src/**/*.ts' -f json -o eslint-report.json"
  },
  "devDependencies": {
    "@commitlint/cli": "^17.3.0",
    "@commitlint/config-conventional": "^16.2.1",
    "@tsconfig/node14": "^1.0.1",
    "@types/aws-lambda": "^8.10.94",
    "@types/jest": "^27.4.1",
    "@types/node": "^14.18.13",
    "@types/node-fetch": "^2.6.1",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.48.0",
    "aws-sdk": "^2.1117.0",
    "aws-sdk-mock": "^5.6.2",
    "eslint": "^8.31.0",
    "eslint-config-prettier": "^8.6.0",
    "http-request-mock": "^1.8.6",
    "husky": "^7.0.0",
    "jest": "^27.5.1",
    "jest-sonar": "^0.2.12",
    "lint-staged": "^13.1.0",
    "prettier": "^2.8.1",
    "pretty-quick": "^3.1.3",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.1.4",
    "typescript": "^4.9.4"
  }
}

```

**Comment by hawflau** [comment]
It looks like `npm` threw an error while `sam build` was running `npm install -q --no-audit --no-save --unsafe-perm --production` behind the scene:
```
2023-01-04 11:01:39,131 | NODEJS installing in: /Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
2023-01-04 11:01:39,131 | executing NPM: ['npm', 'install', '-q', '--no-audit', '--no-save', '--unsafe-perm', '--production']
2023-01-04 11:01:40,031 | NodejsNpmBuilder:NpmInstall failed
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/actions.py", line 110, in execute
    self.subprocess_npm.run(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.67.0/libexec/lib/python3.8/site-packages/aws_lambda_builders/workflows/nodejs_npm/npm.py", line 85, in run
    raise NpmExecutionError(message=err.decode("utf8").strip())
aws_lambda_builders.workflows.nodejs_npm.npm.NpmExecutionError: NPM Failed: npm WARN config production Use `--omit=dev` instead.
```

Can you look into the npm log (`/Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log`) to see if there's any insight?

**Comment by wanisfahmyDE** [comment]
Hey @hawflau not sure if it's really helpful, pasting here (ommitted all the silly reify mark deleted logs)
Thanks 

```bash
0 verbose cli /Users/wanis.fahmy/.nvm/versions/node/v16.17.1/bin/node /Users/wanis.fahmy/.nvm/versions/node/v16.17.1/bin/npm
1 info using npm@8.15.0
2 info using node@v16.17.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 warn config production Use `--omit=dev` instead.
8 timing config:load:cli Completed in 1ms
9 timing config:load:env Completed in 0ms
10 timing config:load:file:/Users/wanis.fahmy/Documents/idealo/repositories/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/.npmrc Completed in 0ms
11 timing config:load:project Completed in 4ms
12 timing config:load:file:/Users/wanis.fahmy/.npmrc Completed in 0ms
13 timing config:load:user Completed in 0ms
14 timing config:load:file:/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/etc/npmrc Completed in 0ms
15 timing config:load:global Completed in 0ms
16 timing config:load:validate Completed in 0ms
17 timing config:load:credentials Completed in 1ms
18 timing config:load:setEnvs Completed in 0ms
19 timing config:load Completed in 8ms
20 timing npm:load:configload Completed in 8ms
21 timing npm:load:mkdirpcache Completed in 1ms
22 timing npm:load:mkdirplogs Completed in 0ms
23 verbose title npm install
24 verbose argv "install" "--loglevel" "warn" "--no-audit" "--no-save" "--unsafe-perm" "--production"
25 timing npm:load:setTitle Completed in 6ms
26 timing config:load:flatten Completed in 1ms
27 timing npm:load:display Completed in 2ms
28 verbose logfile logs-max:10 dir:/Users/wanis.fahmy/.npm/_logs
29 verbose logfile /Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log
30 timing npm:load:logFile Completed in 3ms
31 timing npm:load:timers Completed in 0ms
32 timing npm:load:configScope Completed in 0ms
33 timing npm:load Completed in 20ms
34 timing arborist:ctor Completed in 0ms
35 silly logfile start cleaning logs, removing 1 files
36 silly logfile done cleaning log files
37 timing idealTree:init Completed in 140ms
38 timing idealTree:userRequests Completed in 0ms
39 silly idealTree buildDeps
40 timing idealTree:#root Completed in 0ms
41 timing idealTree:buildDeps Completed in 1ms
42 timing idealTree:fixDepFlags Completed in 0ms
43 timing idealTree Completed in 145ms
44 timing reify:loadTrees Completed in 148ms
45 timing reify:diffTrees Completed in 3ms
46 silly reify moves {}
47 timing reify:retireShallow Completed in 0ms
48 timing reify:createSparse Completed in 107ms
49 silly reify mark deleted [
49 silly reify   '/path/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction/node_modules/@ampproject/remapping'
.
.
. (repeated for all dependencies, omitted here)
49 silly reify ]
701 silly reify ]
702 timing reify:trashOmits Completed in 13ms
703 timing reify:loadBundles Completed in 0ms
704 timing reifyNode:node_modules/node-fetch/node_modules/webidl-conversions Completed in 18ms
705 timing reifyNode:node_modules/node-fetch/node_modules/whatwg-url Completed in 19ms
706 timing reifyNode:node_modules/node-fetch/node_modules/tr46 Completed in 19ms
707 timing reifyNode:node_modules/node-fetch Completed in 19ms
708 timing reify:unpack Completed in 20ms
709 timing reify:unretire Completed in 0ms
710 timing build:queue Completed in 4ms
711 timing build:link Completed in 0ms
712 timing build:deps Completed in 4ms
713 timing build Completed in 5ms
714 timing reify:build Completed in 5ms
715 timing reify:trash Completed in 62ms
716 timing reify Completed in 381ms
717 timing command:install Completed in 449ms
718 verbose stack Error: command failed
718 verbose stack     at ChildProcess.<anonymous> (/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
718 verbose stack     at ChildProcess.emit (node:events:513:28)
718 verbose stack     at maybeClose (node:internal/child_process:1093:16)
718 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
719 verbose pkgid aiven-token-rotation@1.0.0
720 verbose cwd path/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
721 verbose Darwin 21.6.0
722 verbose node v16.17.1
723 verbose npm  v8.15.0
724 error code 1
725 error path /path/aiven-token-rotation/.aws-sam/build/AivenTokenRotationFunction
726 error command failed
727 error command sh /var/folders/pv/7gv7r1796mbg50lgnxs5m2800000gp/T/prepare-a2f3d961.sh
728 verbose exit 1
729 timing npm Completed in 541ms
730 verbose code 1
731 error A complete log of this run can be found in:
731 error     /Users/wanis.fahmy/.npm/_logs/2023-01-04T10_01_39_486Z-debug-0.log

```

**Comment by hawflau** [comment]
@wanisfahmyDE Apologies for the delays. Can you check `/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/lib/node_modules/npm/npmrc`? as in:

```
5 timing config:load:file:/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 warn config production Use `--omit=dev` instead.
```

**Comment by wanisfahmyDE** [comment]
hey @hawflau, no worries!
funny behaviour: path exists up until `/Users/wanis.fahmy/.nvm/versions/node/v16.17.1/lib/node_modules/`
but then `/npm/npmrc` does not exit 😶

Any hints?

**Comment by mndeveci** [comment]
@wanisfahmyDE can you run `npm pack` in the project folder to see if there would be other hints for the problem?

Also, if you can send us a bare minimum project to re-produce this issue then we can try to re-produce it on our side. I've tried to create a function with your `package.json`, but I am getting some other errors (probably I am missing some other stuff).

**Comment by wanisfahmyDE** [comment]
`npm pack` result looks successful:

```bash
 aiven-token-rotation git:(main) ✗ npm pack

> aiven-token-rotation@1.0.0 prepack
> npm run build


> aiven-token-rotation@1.0.0 prebuild
> rimraf dist


> aiven-token-rotation@1.0.0 build
> tsc

npm notice
npm notice New major version of npm available! 8.15.0 -> 9.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.1
npm notice Run npm install -g npm@9.3.1 to update!
npm notice
npm notice
npm notice 📦  aiven-token-rotation@1.0.0
npm notice === Tarball Contents ===
npm notice 1.1kB LICENSE
npm notice 3.9kB README.md
npm notice 8.8kB dist/app.js
npm notice 1.5kB package.json
npm notice === Tarball Details ===
npm notice name:          aiven-token-rotation
npm notice version:       1.0.0
npm notice filename:      aiven-token-rotation-1.0.0.tgz
npm notice package size:  5.2 kB
npm notice unpacked size: 15.4 kB
npm notice shasum:        b50458929727d20654e73a26be27f4033eb927aa
npm notice integrity:     sha512-OkPtFHIMr4loY[...]SnxCtbZYTGYwA==
npm notice total files:   4
npm notice
aiven-token-rotation-1.0.0.tgz
npm notice
npm notice New major version of npm available! 8.15.0 -> 9.3.1
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.3.1
npm notice Run npm install -g npm@9.3.1 to update!
npm notice
```
@mndeveci I will try to jump to node18 directly to see if the problem persists

**Comment by mndeveci** [comment]
@wanisfahmyDE did you able to fix your issues with `nodejs18` runtime?

If not, can you please provide a small example so that we can try to re-produce on our side?

Thanks!

**Comment by sriram-mv** [comment]
@wanisfahmyDE we need a bare bones example, could you push up to a repo? This is the only we can continue to debug further. 

From your example

```
nvm use v16
npm install
npm run build
npm run test
sam build #fails
```

I was able to do a nvm use, but I need to know what the build, test are since they are arbitrary package scripts that could be mutating the file system.

sam build under the hood is also running npm. In short its running `npm pack` and `npm install`

Looking at the debug logs

```
2023-02-16 14:24:26,962 | executing NPM: ['npm', 'pack', '-q', 'file:/Users/.../sam-app/hello-world']

2023-02-16 14:24:27,322 | executing NPM: ['npm', 'install', '-q', '--no-audit', '--no-save', '--unsafe-perm', '--production']
```

Can you try running those commands in isolation outside of sam build and see if you run into the same issue?

**Comment by sriram-mv** [comment]
Closing since there has been no activity on this for a month, if this still an issue let us know and we can open it back up and continue investigation.

**Comment by wanisfahmyDE** [comment]
Hey @sriram-mv @mndeveci ,

Super sorry for the late response, I was out of office.

I just upgraded to node18 and it worked like a charm.

**Comment by tam-nguyen-yum** [comment]
I'm having the same problem with this when trying to update from node 14 to node 16 in local machine, but CircleCI (using Node 16) can build the lambda package successfully, below is my env:

```
$npm --version 
9.6.6

$node --version 
v16.20.0

$sam --version                         
SAM CLI, version 1.83.0
```
