### ISSUE TITLE
sam local start-api multiple cdk templates

### ISSUE THREAD

**Issue by jarnohenneman** [aws/aws-sam-cli#4555]
### Description:
When running 'sam local start-api -t cdk.out/ManualApiGateway.template.json' it starts the API Gateway and loads the first two functions from the template itself. It also finds/loads function X from another template, and knows it's called X.
But mounts it as None.

> Mounting AFunctionManualF495C7B0 at http://127.0.0.1:3000/A [GET]
> Mounting BFunctionManualA18650F4 at http://127.0.0.1:3000/B [GET]
> Mounting **None** at http://127.0.0.1:3000/X [DELETE, GET, PUT]

When I call the function it returns an error about the function name;
```
Exception on /X [DELETE]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 361, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 111, in invoke
    function = self.provider.get(function_identifier)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.68.0/libexec/lib/python3.8/site-packages/samcli/lib/providers/sam_function_provider.py", line 117, in get
    raise ValueError("Function name is required")
ValueError: Function name is required
```

I don't know if this is supported, or not - if It is I can create a bug report.

**Comment by mndeveci** [comment]
Hi @jarnohenneman 

Can you provide us a minimal example template that we can try to re-produce the issue?

**Comment by jarnohenneman** [comment]
Absolutely, here is a stripped down version of the project. 

https://github.com/jarnohenneman/cdk-question 

Build: `cdk synth --all`
Run: `sam local start-api  -t cdk.out/DefaultApiGateway.template.json`


Working endpoint; http://localhost:3000/actuator/health (GET) 
Not working endpoint; http://127.0.0.1:3000/example (GET)

**Comment by jarnohenneman** [comment]
Duplicate: #3627 & #3306.

Are there any plans to support this functionality, as it seems SAM can find the APIs cross stack/nested stack. It also sees all the methods of the API.

It gives us the ability to structure our project significantly better rather than putting all 100+ APIs in a single file.

**Comment by mndeveci** [comment]
Thanks for providing the example as well as finding the duplicates.

I will raise this with our product managers and will provide an update once we have some plans ready. I will be resolving this now for the sake of #3306

Let's follow the discussion in the other thread.
