### ISSUE TITLE
DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed: Specify which project file to use because this 'path/to/folder' contains more than one project file. (C#)

### ISSUE THREAD

**Issue by LeonardoX77** [aws/aws-sam-cli#4626]
### Description:
I'm trying to build a c# solution with the command `sam build`. Everything was working ok until I added a second solution to the same folder. Now I get this error:

`DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed: Specify which project file to use because this 'path/to/folder' contains more than one project file.
`

I can't see any option in [sam build arguments](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html) to specify a specific project, even argument `--config-file PATH`

### Steps to reproduce:
Just run `sam build `command in any folder which contains more than one c# solution

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
SAM CLI, version 1.70.1

```
# Paste the output of `sam --info` here
```
{
  "version": "1.70.1",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

`Add --debug flag to command you are running`

C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda>sam build --debug
2023-01-27 16:51:27,560 | Config file location: C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\samconfig.toml
2023-01-27 16:51:27,562 | Loading configuration values from [default.['build'].parameters] (env.command_name.section) in config file at 'C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\samconfig.toml'...
2023-01-27 16:51:27,574 | Configuration values successfully loaded.
2023-01-27 16:51:27,575 | Configuration values are: {}
2023-01-27 16:51:27,605 | Using SAM Template at C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\template.yaml
2023-01-27 16:51:28,141 | Using config file: samconfig.toml, config environment: default
2023-01-27 16:51:28,141 | Expand command line arguments to:
2023-01-27 16:51:28,141 | --template_file=C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\template.yaml --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2023-01-27 16:51:30,893 | 'build' command is called
2023-01-27 16:51:30,899 | No Parameters detected in the template
2023-01-27 16:51:30,983 | There is no customer defined id or cdk path defined for resource ApiGatewayApi, so we will use the resource logical id as the resource id
2023-01-27 16:51:30,984 | There is no customer defined id or cdk path defined for resource InsertInvoice, so we will use the resource logical id as the resource id
2023-01-27 16:51:30,984 | There is no customer defined id or cdk path defined for resource GetInvoice, so we will use the resource logical id as the resource id
2023-01-27 16:51:30,986 | 0 stacks found in the template
2023-01-27 16:51:30,987 | No Parameters detected in the template
2023-01-27 16:51:31,008 | There is no customer defined id or cdk path defined for resource ApiGatewayApi, so we will use the resource logical id as the resource id
2023-01-27 16:51:31,008 | There is no customer defined id or cdk path defined for resource InsertInvoice, so we will use the resource logical id as the resource id
2023-01-27 16:51:31,009 | There is no customer defined id or cdk path defined for resource GetInvoice, so we will use the resource logical id as the resource id
2023-01-27 16:51:31,010 | 3 resources found in the stack
2023-01-27 16:51:31,010 | Found Serverless function with name='InsertInvoice' and CodeUri='.'
2023-01-27 16:51:31,011 | --base-dir is not presented, adjusting uri . relative to C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\template.yaml
2023-01-27 16:51:31,011 | Found Serverless function with name='GetInvoice' and CodeUri='.'
2023-01-27 16:51:31,011 | --base-dir is not presented, adjusting uri . relative to C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\template.yaml
2023-01-27 16:51:31,018 | 3 resources found in the stack
2023-01-27 16:51:31,018 | Found Serverless function with name='InsertInvoice' and CodeUri='.'
2023-01-27 16:51:31,018 | Found Serverless function with name='GetInvoice' and CodeUri='.'
2023-01-27 16:51:31,019 | Instantiating build definitions
2023-01-27 16:51:31,022 | Same function build definition found, adding function (Previous: BuildDefinition(dotnetcore3.1, C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda, Zip, , ca6b24ad-d3ea-4b63-9c01-61361916f801, {}, {}, x86_64, []), Current: BuildDefinition(dotnetcore3.1, C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda, Zip, , 5019f10d-b830-47a4-9127-3d160c79f626, {}, {}, x86_64, []), Function: Function(function_id='InsertInvoice', name='InsertInvoice', functionname='InsertInvoiceFunction', runtime='dotnetcore3.1', memory=None, timeout=30, handler='QLDB.API.Lambda::QLDB.API.Lambda.Functions.InsertInvoice.InsertInvoiceFunction::FunctionHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Leo\\Projects\\QLDB-Coke\\QLDB-API\\QLDB.API.Lambda\\QLDB.API.Lambda', environment=None, rolearn=None, layers=[], events={'InsertInvoice': {'Type': 'Api', 'Properties': {'Path': '/insertInvoice', 'Method': 'post', 'RestApiId': 'ApiGatewayApi'}}}, metadata={'SamResourceId': 'InsertInvoice'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path=''))
2023-01-27 16:51:31,023 | Same function build definition found, adding function (Previous: BuildDefinition(dotnetcore3.1, C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda, Zip, , ca6b24ad-d3ea-4b63-9c01-61361916f801, {}, {}, x86_64, ['InsertInvoiceFunction']), Current: BuildDefinition(dotnetcore3.1, C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda, Zip, , 7c07a705-9713-4bd9-af2a-3601517fb94d, {}, {}, x86_64, []), Function: Function(function_id='GetInvoice', name='GetInvoice', functionname='GetInvoiceFunction', runtime='dotnetcore3.1', memory=None, timeout=30, handler='QLDB.API.Lambda::QLDB.API.Lambda.Functions.GetInvoice.GetInvoiceFunction::FunctionHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Leo\\Projects\\QLDB-Coke\\QLDB-API\\QLDB.API.Lambda\\QLDB.API.Lambda', environment=None, rolearn=None, layers=[], events={'GetInvoice': {'Type': 'Api', 'Properties': {'Path': '/getInvoice', 'Method': 'post', 'RestApiId': 'ApiGatewayApi'}}}, metadata={'SamResourceId': 'GetInvoice'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path=''))
2023-01-27 16:51:31,139 | Building codeuri: C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda runtime: dotnetcore3.1 metadata: {} architecture: x86_64 functions: InsertInvoice, GetInvoice
2023-01-27 16:51:31,140 | Building to following folder C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda\.aws-sam\build\InsertInvoice
2023-01-27 16:51:31,145 | Loading workflow module 'aws_lambda_builders.workflows'
2023-01-27 16:51:31,168 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-01-27 16:51:31,176 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-01-27 16:51:31,184 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-01-27 16:51:31,193 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-01-27 16:51:31,207 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-01-27 16:51:31,214 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-01-27 16:51:31,223 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-01-27 16:51:31,232 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-01-27 16:51:31,242 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-01-27 16:51:31,242 | Found workflow 'DotnetCliPackageBuilder' to support capabilities 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-01-27 16:51:31,246 | Running workflow 'DotnetCliPackageBuilder'
2023-01-27 16:51:31,246 | Running DotnetCliPackageBuilder:GlobalToolInstall
2023-01-27 16:51:31,254 | Entered synchronized block for updating Amazon.Lambda.Tools
2023-01-27 16:51:31,257 | Installing Amazon.Lambda.Tools Global Tool
2023-01-27 16:51:31,263 | executing dotnet: ['dotnet.exe', 'tool', 'install', '-g', 'Amazon.Lambda.Tools', '--ignore-failed-sources']
2023-01-27 16:51:31,712 |
2023-01-27 16:51:31,712 | Error installing probably due to already installed. Attempt to update to latest version.
2023-01-27 16:51:31,717 | executing dotnet: ['dotnet.exe', 'tool', 'update', '-g', 'Amazon.Lambda.Tools', '--ignore-failed-sources']
2023-01-27 16:51:48,381 | Tool 'amazon.lambda.tools' was reinstalled with the latest stable version (version '5.6.3').
2023-01-27 16:51:48,383 | DotnetCliPackageBuilder:GlobalToolInstall succeeded
2023-01-27 16:51:48,395 | Running DotnetCliPackageBuilder:RunPackageAction
2023-01-27 16:51:48,401 | Running `dotnet lambda package` in C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda
2023-01-27 16:51:48,403 | executing dotnet: ['dotnet.exe', 'lambda', 'package', '--output-package', 'C:\\Leo\\Projects\\QLDB-Coke\\QLDB-API\\QLDB.API.Lambda\\QLDB.API.Lambda\\.aws-sam\\build\\InsertInvoice\\QLDB.API.Lambda.zip', '--msbuild-parameters', '--runtime linux-x64']
2023-01-27 16:51:48,729 |
2023-01-27 16:51:48,730 | DotnetCliPackageBuilder:RunPackageAction failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\actions.py", line 107, in execute
    self.subprocess_dotnet.run(arguments, cwd=self.source_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\dotnetcli.py", line 67, in run
    raise DotnetCLIExecutionError(message=err.decode(encoding).strip())
aws_lambda_builders.workflows.dotnet_clipackage.dotnetcli.DotnetCLIExecutionError: Dotnet CLI Failed: Specify which project file to use because this 'C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda' contains more than one project file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 348, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\actions.py", line 114, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Dotnet CLI Failed: Specify which project file to use because this 'C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda' contains more than one project file.

Build Failed
2023-01-27 16:51:48,741 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-01-27 16:51:49,181 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-01-27 16:51:49,181 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '09094d7a-cf94-41c0-9b0f-e03ea15bc125', 'installationId': 'bbd244bd-9a58-4244-86d4-03534b3e0c1d', 'sessionId': '6b521e1a-f69f-4c2a-a7a9-a8087a3bc2c3', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.70.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': '2ab9b2455486f31c401fa9741e2c74ef74677231d899fd6bc4446eb546de1700', 'projectName': '319cb10ada7badf4bd720d874609313e06984e88414a69eff4b9e486d95d1c49', 'initialCommit': '7af0328ebb0c326c2d353465fb159bcd1db7a51ccc03ab78a38069c439b817d5'}, 'duration': 20600, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2023-01-27 16:51:49,181 | Unable to find Click Context for getting session_id.
2023-01-27 16:51:49,185 | Sending Telemetry: {'metrics': [{'events': {'requestId': '300b8666-0a71-4041-9fd4-2fd1c834a493', 'installationId': 'bbd244bd-9a58-4244-86d4-03534b3e0c1d', 'sessionId': '6b521e1a-f69f-4c2a-a7a9-a8087a3bc2c3', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.70.1', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildWorkflowUsed', 'event_value': 'dotnet-cli-package', 'thread_id': 6212, 'time_stamp': '2023-01-27 15:51:31.142'}]}}}]}
2023-01-27 16:51:50,157 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2023-01-27 16:51:50,173 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed: Specify which project file to use because this 'C:\Leo\Projects\QLDB-Coke\QLDB-API\QLDB.API.Lambda\QLDB.API.Lambda' contains more than one project file.

**Comment by qingchm** [comment]
Thanks for opening this issue, can we know what your QLDB.API.Lambda folder structure looks like?

**Comment by LeonardoX77** [comment]
Hi @qingchm, thanks for your response.
This is what my QLDB.API.Lambda folder structure looks like:
<DIR>          .aws-sam
<DIR>          .lambda-test-tool
           236 appSettings.json
           692 aws-lambda-tools-defaults.json
<DIR>          bin
<DIR>          Functions
<DIR>          obj
<DIR>          Properties
         1,598 QLDB.API.Lambda-ALL.csproj
         1,602 QLDB.API.Lambda.csproj
           329 samconfig.toml
         2,813 template.yaml

**Comment by qingchm** [comment]
```
         1,598 QLDB.API.Lambda-ALL.csproj
         1,602 QLDB.API.Lambda.csproj
```
Isn't this causing the issue? When your project contains more than one .csproj file I guess moving them to separate directories make sense? Is there a reason why they need to be in the QLDB.API.Lambda folder together?

**Comment by LeonardoX77** [comment]
Hi, well, it depends. Obviously there's no strong reason this project files must be together, but sometimes you know you need to open some dependencies source files in the solution just to debug some strange behaviours or any other reasons that make me put the different project files that open the same project in the same folder cause what it really doesn't make sense is to save the project file separated of the files it's referencing to. In my opinion sam command should include this basic option as dotnet fails internally because it's expecting this option but sam command doesn't support it.

**Comment by moelasmar** [comment]
Hello @LeonardoX77, 
Sorry for late reply. We are using `dotnet lambda package` command to build the dotnet lambda functions ([code](https://github.com/aws/aws-lambda-builders/blob/develop/aws_lambda_builders/workflows/dotnet_clipackage/actions.py#L110-L121))

Unfortunately, `lambda package` command does not contain an option to choose the project file, see the list of options here:
```
$ dotnet lambda help package
Amazon Lambda Tools for .NET Core applications (5.6.6)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet
	
package: 
   Command to package a Lambda project either into a zip file or docker image if --package-type is set to "image". The output can later be deployed to Lambda with either deploy-function command or with another tool.
	
   dotnet lambda package [arguments] [options]
   Arguments:
      <ZIP-FILE> The name of the zip file to package the project into
   Options:
      --disable-interactive                   When set to true missing required parameters will not be prompted for.
      --region                                The region to connect to AWS services, if not set region will be detected from the environment.
      --profile                               Profile to use to look up AWS credentials, if not set environment credentials will be used.
      --profile-location                      Optional override to the search location for Profiles, points at a shared credentials file.
      --aws-access-key-id                     The AWS access key id. Used when setting credentials explicitly instead of using --profile.
      --aws-secret-key                        The AWS secret key. Used when setting credentials explicitly instead of using --profile.
      --aws-session-token                     The AWS session token. Used when setting credentials explicitly instead of using --profile.
      -pl    | --project-location             The location of the project, if not set the current directory will be assumed.
      -cfg   | --config-file                  Configuration file storing default values for command line arguments.
      -pcfg  | --persist-config-file          If true the arguments used for a successful deployment are persisted to a config file.
      -c     | --configuration                Configuration to build with, for example Release or Debug.
      -f     | --framework                    Target framework to compile, for example netcoreapp3.1.
      -farch | --function-architecture        The architecture of the Lambda function. Valid values: x86_64 or arm64. Default is x86_64
      --msbuild-parameters                    Additional msbuild parameters passed to the 'dotnet publish' command. Add quotes around the value if the value contains spaces.
      -fl    | --function-layers              Comma delimited list of Lambda layer version arns
      -o     | --output-package               The zip file that will be created with compiled and packaged Lambda function.
      -dvc   | --disable-version-check        Disable the .NET Core version check. Only for advanced usage.
      -pt    | --package-type                 The deployment package type for Lambda function. Valid values: image, zip
      -it    | --image-tag                    Docker image name and tag in the 'name:tag' format.
      -df    | --dockerfile                   The docker file used to build the image. Default value is "Dockerfile".
      -dbo   | --docker-build-options         Additional options passed to the "docker build" command.
      -dbwd  | --docker-build-working-dir     The directory to execute the "docker build" command from.
      --docker-host-build-output-dir          If set a "dotnet publish" command is executed on the host machine before executing "docker build". The output can be copied into image being built.
      -ucfb  | --use-container-for-build      Use a local container to build the Lambda binary. A default image will be provided if none is supplied.
      -cifb  | --container-image-for-build    The container image tag (with version) to be used for building the Lambda binary.
      -cmd   | --code-mount-directory         Path to the directory to mount to the build container. Otherwise, look upward for a solution folder.
```

Based on that, I think SAM CLI could not support this feature, because of the limitation of the underneath tool.

**Comment by mildaniel** [comment]
I'm going to close this issue now but please open a new issue if anything else comes up. Hopefully the response from @moelasmar was sufficient.
