### ISSUE TITLE
Bug: SAM CLI, version 1.72.0 Failed to build Docker Image

### ISSUE THREAD

**Issue by AmonPeter** [aws/aws-sam-cli#4684]
### Description:

Getting below error when I `run sam local start-api` on MacOS Ventura 13.1
`
`

### Observed result:
````
 `2023-02-10 00:21:45,270 | Config file location: /Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/samconfig.toml
2023-02-10 00:21:45,270 | Config file '/Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/samconfig.toml' does not exist
2023-02-10 00:21:45,272 | Using SAM Template at /Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/template.yaml
2023-02-10 00:21:45,293 | Using config file: samconfig.toml, config environment: default
2023-02-10 00:21:45,293 | Expand command line arguments to:
2023-02-10 00:21:45,293 | --template_file=/Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/template.yaml --host=127.0.0.1 --port=3000 --static_dir=public --layer_cache_basedir=/Users/amonpeter/.aws-sam/layers-pkg --container_host=localhost --container_host_interface=127.0.0.1 
2023-02-10 00:21:45,355 | local start-api command is called
2023-02-10 00:21:45,357 | No Parameters detected in the template
2023-02-10 00:21:45,371 | Sam customer defined id is more priority than other IDs. Customer defined id for resource UserFunction is UserFunction
2023-02-10 00:21:45,371 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-10 00:21:45,371 | 0 stacks found in the template
2023-02-10 00:21:45,371 | No Parameters detected in the template
2023-02-10 00:21:45,380 | Sam customer defined id is more priority than other IDs. Customer defined id for resource UserFunction is UserFunction
2023-02-10 00:21:45,381 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-02-10 00:21:45,381 | 2 resources found in the stack 
2023-02-10 00:21:45,381 | Found Serverless function with name='UserFunction' and CodeUri='UserFunction'
2023-02-10 00:21:45,381 | --base-dir is not presented, adjusting uri UserFunction relative to /Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/template.yaml
2023-02-10 00:21:45,397 | Found '1' API Events in Serverless function with name 'UserFunction'
2023-02-10 00:21:45,397 | Detected Inline Swagger definition
2023-02-10 00:21:45,397 | Lambda function integration not found in Swagger document at path='/amon' method='get'
2023-02-10 00:21:45,397 | Found '0' APIs in resource 'ServerlessRestApi'
2023-02-10 00:21:45,397 | Removed duplicates from '0' Explicit APIs and '1' Implicit APIs to produce '1' APIs
2023-02-10 00:21:45,397 | 1 APIs found in the template
2023-02-10 00:21:45,405 | Mounting UserFunction at http://127.0.0.1:3000/amon [GET]
2023-02-10 00:21:45,405 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-02-10 00:21:45,405 | Localhost server is starting up. Multi-threading = True
2023-02-10 00:21:45  * Running on http://127.0.0.1:3000/ (Press CTRL+C to quit)
2023-02-10 00:21:52,278 | Constructed String representation of Event to invoke Lambda. Event: {"body": null, "headers": {"Accept": "*/*", "Host": "127.0.0.1:3000", "User-Agent": "curl/7.85.0", "X-Forwarded-Port": "3000", "X-Forwarded-Proto": "http"}, "httpMethod": "GET", "isBase64Encoded": false, "multiValueHeaders": {"Accept": ["*/*"], "Host": ["127.0.0.1:3000"], "User-Agent": ["curl/7.85.0"], "X-Forwarded-Port": ["3000"], "X-Forwarded-Proto": ["http"]}, "multiValueQueryStringParameters": null, "path": "/amon", "pathParameters": null, "queryStringParameters": null, "requestContext": {"accountId": "123456789012", "apiId": "1234567890", "domainName": "127.0.0.1:3000", "extendedRequestId": null, "httpMethod": "GET", "identity": {"accountId": null, "apiKey": null, "caller": null, "cognitoAuthenticationProvider": null, "cognitoAuthenticationType": null, "cognitoIdentityPoolId": null, "sourceIp": "127.0.0.1", "user": null, "userAgent": "Custom User Agent String", "userArn": null}, "path": "/amon", "protocol": "HTTP/1.1", "requestId": "060d3f62-cd5f-4b5a-a22b-78b91d9023c2", "requestTime": "09/Feb/2023:22:21:45 +0000", "requestTimeEpoch": 1675981305, "resourceId": "123456", "resourcePath": "/amon", "stage": "Prod"}, "resource": "/amon", "stageVariables": null, "version": "1.0"}
2023-02-10 00:21:52,278 | Found one Lambda function with name 'UserFunction'
2023-02-10 00:21:52,278 | Invoking com.app.budget.user.StreamLambdaHandler::handleRequest (java11)
2023-02-10 00:21:52,278 | No environment variables found for function 'UserFunction'
2023-02-10 00:21:52,278 | Loading AWS credentials from session with profile 'None'
2023-02-10 00:21:52,287 | Resolving code path. Cwd=/Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build, CodeUri=/Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/UserFunction
2023-02-10 00:21:52,287 | Resolved absolute path to code is /Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/UserFunction
2023-02-10 00:21:52,287 | Code /Users/amonpeter/Documents/Code/budget-app-lambda-functions/user/.aws-sam/build/UserFunction is not a zip/jar file
2023-02-10 00:21:52,295 | Local image was not found.
2023-02-10 00:21:52,295 | Removing rapid images for repo public.ecr.aws/sam/emulation-java11
Building image.....................
2023-02-10 00:21:57,601 | Failed to build Docker Image
NoneType: None
2023-02-10 00:21:57,603 | Cleaning all decompressed code dirs
2023-02-10 00:21:57,603 | Exception on /amon [GET]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/apigw/local_apigw_service.py", line 361, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/lib/telemetry/metric.py", line 323, in wrapped_func
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/lambdafn/runtime.py", line 188, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/lambdafn/runtime.py", line 84, in create
    container = LambdaContainer(
                ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_container.py", line 93, in __init__
    image = LambdaContainer._get_image(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_container.py", line 236, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 214, in build
    self._build_image(
  File "/opt/homebrew/Cellar/aws-sam-cli/1.72.0/libexec/lib/python3.11/site-packages/samcli/local/docker/lambda_image.py", line 328, in _build_image
    raise ImageBuildException("Error building docker image: {}".format(log["error"]))
samcli.commands.local.cli_common.user_exceptions.ImageBuildException: Error building docker image: The command '/bin/sh -c mv /var/rapid/aws-lambda-rie-x86_64 /var/rapid/aws-lambda-rie && chmod +x /var/rapid/aws-lambda-rie' returned a non-zero code: 1
`
```
`



### Expected result:
To Successfully hit localhost:3000/amon



### Additional environment details

<!-- Either provide the following info (for AWS SAM CLI v1.68.0 or before) or paste the output of `sam --info` (AWS SAM CLI v1.69.0 or after). -->


 `{
  "version": "1.72.0",
  "system": {
    "python": "3.11.1",
    "os": "macOS-13.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
`:

**Comment by AmonPeter** [comment]
Issue resolved after running ` brew install aws/tap/aws-sam-cli`
