### ISSUE TITLE
unable to invoke a local lambda function from sam local api

### ISSUE THREAD

**Issue by Powerleech** [aws/aws-sam-cli#4801]
Here is the template.json for sam:

```
		"Flask": {
			"Type": "AWS::Serverless::Function",
			"Properties": {
				"CodeUri": "api/",
				"Handler": "app.app",
				"Tracing": "Active",
				"Events": {
					"Whoami": {
						"Type": "Api",
						"Properties": {
							"Path": "/{proxy+}",
							"Method": "any",
							"RestApiId": {
								"Ref": "SibilusApi"
							}
						}
					}
				}
			}
		},
        "EmailSender": {
			"Type": "AWS::Serverless::Function",
			"Properties": {
				"FunctionName": "EmailSender",
				"CodeUri": "api/",
				"Handler": 
                  "src/email_sender_lambda_function.lambda_handler",
				"Tracing": "Active"
			}
		},
```

I then have another lambda function, that I wish to invoke from my flask application.

I start my api with `sam local start-api --docker-network sam-network`.

in my app.py I have:
```
import json
from flask_lambda import FlaskLambda
from flask_cors import CORS
import boto3

app = FlaskLambda(__name__)
CORS(app)


@app.route("/hello", methods=["GET"])
def hello():
    print("I am running")
    lambda_client = boto3.client("lambda", endpoint_url="http://localhost:3001", use_ssl=False)
    response = lambda_client.invoke(FunctionName="EmailSender", Payload = json.dumps({"event": "hello world"}))
    print(response)
    return {"hello": "world"}, 200
```

I started my other lambda function locally with 
`sam local start-lambda --docker-network sam-network`

Now I have the api on 
http://127.0.0.1:3000
, and I have my local lambda functions running on http://127.0.0.1:3001.

If I try to invoke the local lambda function from command line with a curl on port 3001, it works fine.

When I curl my api:
`curl http://localhost:3000/hello`
the flask application executes the `/hello` as expected

But my flask application cannot invoke my EmailSender function runnning locally in SAM:

error message
```
Traceback (most recent call last):
  File "/var/task/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/task/flask/app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/task/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/var/task/flask/app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/task/flask/app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/var/task/app.py", line 14, in hello
    response = lambda_client.invoke(FunctionName="EmailSender", Payload = json.dumps({"event": "hello world"}))
  File "/var/task/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/task/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/var/task/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/var/task/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/var/task/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/var/task/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/var/task/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/var/task/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/var/task/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/var/task/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/var/task/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/var/task/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/var/task/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/var/task/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/var/task/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/var/task/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/var/task/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/var/task/botocore/httpsession.py", line 484, in send
    raise EndpointConnectionError(endpoint_url=request.url, error=e)
botocore.exceptions.EndpointConnectionError: Could not connect to the endpoint URL: "http://localhost:3001/2015-03-31/functions/EmailSender/invocations"END RequestId: fc4d80cf-ec20-414a-a2bd-c9067ba964b1

```

Am I doing something wrong?

I realize that the problem might be the "localhost" part in the flask application, but I haven't been able to figure out what to put instead. If I use --docker-network, and tries the docker's internal ip, it wouldn't work.

Could anyone point me in the right direction?</div>

**Comment by hnnasit** [comment]
Thank you @Powerleech for opening the issue. My understanding is the flask application cannot invoke the EmailSender function because the function with the Flask application is run in a container and the endpoint  `http://localhost:3001` does not exist inside the container and so it needs to connect to the localhost outside. We will dive deeper and get back to you.

**Comment by mndeveci** [comment]
Hi @Powerleech ,

I think you can achieve this by using `host.docker.internal` instead of `localhost` due to reason that @hnnasit explained above.

For instance, I have 2 functions as written below;
```
import json
import boto3

# HelloMarsFunction
def lambda_handler(event, context):
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello mars",
        }),
    }

# HelloWorldFunction
def api_handler(event, context):
    print("I am running")
    lambda_client = boto3.client("lambda", endpoint_url="http://host.docker.internal:3001", use_ssl=False)
    response = lambda_client.invoke(FunctionName="HelloMarsFunction", Payload = json.dumps({"event": "hello world"}))
    payload = json.loads(response['Payload'].read())
    return {
        "statusCode": 200,
        "body": json.dumps({
            "message": "hello world",
            "lambda_call": payload,
        }),
    }
```
- `api_handler`: is invoked by API calls from `/hello` path
- `lambda_handler`: doesn't have any integration but it is been invoked by `api_handler` function as you can see above

I've changed `endpoint_url` to `http://host.docker.internal:3001` so that containers can communicate through host machine's ports. And with that I was able to invoke one function from another one.


```
❯ sam local start-api
Initializing the lambda functions containers.
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

Mounting /private/tmp/cli-4801/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

Mounting /private/tmp/cli-4801/sam-app/.aws-sam/build/HelloMarsFunction as /var/task:ro,delegated inside runtime container
Containers Initialization is done.
Mounting HelloWorldFunction at http://127.0.0.1:3000/hello [GET]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-03-10 17:37:38 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
2023-03-10 17:37:38 Press CTRL+C to quit
Invoking app.lambda_handler (python3.9)
Reuse the created warm container for Lambda function 'HelloWorldFunction'
Lambda function 'HelloWorldFunction' is already running
I am running
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'Werkzeug/2.2.3 Python/3.8.13', 'date': 'Sat, 11 Mar 2023 01:37:43 GMT', 'content-type': 'application/json', 'content-length': '60', 'connection': 'close'}, 'RetryAttempts': 0}, 'StatusCode': 200, 'Payload': <botocore.response.StreamingBody object at 0x7f52321e4d00>}
{'statusCode': 200, 'body': '{"message": "hello mars"}'}
END RequestId: d4e28463-5d5f-411c-8043-9974e5c966dd
REPORT RequestId: d4e28463-5d5f-411c-8043-9974e5c966dd	Init Duration: 0.30 ms	Duration: 633.14 ms	Billed Duration: 634 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
No Content-Type given. Defaulting to 'application/json'.
2023-03-10 17:37:43 127.0.0.1 - - [10/Mar/2023 17:37:43] "GET /hello HTTP/1.1" 200 -
```

```
❯ sam local start-lambda
Initializing the lambda functions containers.
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

Mounting /private/tmp/cli-4801/sam-app/.aws-sam/build/HelloMarsFunction as /var/task:ro,delegated inside runtime container
Local image is up-to-date
Using local image: public.ecr.aws/lambda/python:3.9-rapid-x86_64.

Mounting /private/tmp/cli-4801/sam-app/.aws-sam/build/HelloWorldFunction as /var/task:ro,delegated inside runtime container
Containers Initialization is done.
Starting the Local Lambda Service. You can now invoke your Lambda Functions defined in your template through the endpoint.
2023-03-10 17:37:41 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3001
2023-03-10 17:37:41 Press CTRL+C to quit
Invoking app.lambda_handler2 (python3.9)
Reuse the created warm container for Lambda function 'HelloMarsFunction'
Lambda function 'HelloMarsFunction' is already running
END RequestId: 6d91be59-7f60-4c5f-b19b-1b78c47d8a99
REPORT RequestId: 6d91be59-7f60-4c5f-b19b-1b78c47d8a99	Init Duration: 0.09 ms	Duration: 254.69 ms	Billed Duration: 255 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
2023-03-10 17:37:43 127.0.0.1 - - [10/Mar/2023 17:37:43] "POST /2015-03-31/functions/HelloMarsFunction/invocations HTTP/1.1" 200 -
```

```
❯ curl localhost:3000/hello
{"message": "hello world", "lambda_call": {"statusCode": 200, "body": "{\"message\": \"hello mars\"}"}}%
```

Please let us know if you have other questions.

**Comment by moelasmar** [comment]
Closing given no response. Please re-open or create a new issue if the suggested solution did not solve the problem.
