### ISSUE TITLE
Bug: docker error when trying to invoke function

### ISSUE THREAD

**Issue by RichiCoder1** [aws/aws-sam-cli#4818]
### Description:
When attempting to locally invoke a lambda, I'm getting an error about "Failed to build Docker Image".

### Steps to reproduce:
`sam local invoke -t .\build\template.yaml <entrypoint>`

### Observed result:
```
2023-03-06 00:01:11,469 | Config file location: C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\samconfig.toml
2023-03-06 00:01:11,470 | Config file 'C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\samconfig.toml' does not exist
2023-03-06 00:01:11,490 | Using config file: samconfig.toml, config environment: default
2023-03-06 00:01:11,490 | Expand command line arguments to:
2023-03-06 00:01:11,490 | --template_file=C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\template.yaml --function_logical_id=TestEntrypoint --no_event --layer_cache_basedir=C:\Users\richa\AppData\Roaming\AWS SAM\layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2023-03-06 00:01:11,491 | local invoke command is called
2023-03-06 00:01:11,495 | No Parameters detected in the template
2023-03-06 00:01:11,518 | Sam customer defined id is more priority than other IDs. Customer defined id for resource TestEntrypoint is TestEntrypoint
2023-03-06 00:01:11,518 | There is no customer defined id or cdk path defined for resource TypeFunction, so we will use the resource logical id as the resource id  
2023-03-06 00:01:11,518 | 0 stacks found in the template
2023-03-06 00:01:11,518 | No Parameters detected in the template
2023-03-06 00:01:11,532 | Sam customer defined id is more priority than other IDs. Customer defined id for resource TestEntrypoint is TestEntrypoint
2023-03-06 00:01:11,532 | There is no customer defined id or cdk path defined for resource TypeFunction, so we will use the resource logical id as the resource id  
2023-03-06 00:01:11,533 | 2 resources found in the stack
2023-03-06 00:01:11,533 | Found Serverless function with name='TestEntrypoint' and CodeUri='TypeFunction'
2023-03-06 00:01:11,533 | --base-dir is not presented, adjusting uri TypeFunction relative to C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\template.yaml
2023-03-06 00:01:11,533 | Found Serverless function with name='TypeFunction' and CodeUri='..'
2023-03-06 00:01:11,534 | --base-dir is not presented, adjusting uri .. relative to C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\template.yaml
2023-03-06 00:01:11,550 | Found one Lambda function with name 'TestEntrypoint'
2023-03-06 00:01:11,550 | Invoking dist/handlers.testEntrypoint (nodejs18.x)      
2023-03-06 00:01:11,550 | Loading AWS credentials from session with profile 'None'
2023-03-06 00:01:11,563 | Resolving code path. Cwd=C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build, CodeUri=C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\TypeFunction
2023-03-06 00:01:11,563 | Resolved absolute path to code is C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\TypeFunction
2023-03-06 00:01:11,563 | Code C:\src\richicoder1\cloudformation-cli-typescriptv2-plugin\example\build\TypeFunction is not a zip/jar file
2023-03-06 00:01:11,569 | Local image was not found.
2023-03-06 00:01:11,570 | Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs18.x
Building image...
2023-03-06 00:01:12,686 | Failed to build Docker Image
Traceback (most recent call last):
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\docker\api\client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http+docker://localnpipe/v1.35/build?t=public.ecr.aws%2Flambda%2Fnodejs%3A18-rapid-x86_64&q=False&nocache=False&rm=True&forcerm=False&pull=True&platform=linux%2Famd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\samcli\local\docker\lambda_image.py", line 319, in _build_image
    for log in resp_stream:
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\docker\api\client.py", line 354, in _stream_helper
    yield self._result(response, json=decode)
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\docker\api\client.py", line 267, in _result
    self._raise_for_status(response)
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\docker\api\client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "C:\Users\richa\.local\pipx\venvs\aws-sam-cli\lib\site-packages\docker\errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 502 Server Error: Bad Gateway ("b'Bad response from Docker engine'")
2023-03-06 00:01:12,691 | Cleaning all decompressed code dirs
2023-03-06 00:01:12,691 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-03-06 00:01:12,873 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '3529e1d4-b08a-4162-806e-fae637d2639c', 'installationId': '8235528a-ba69-4648-a63b-4cb88ac5b161', 'sessionId': '2d38a6c5-14d2-46a9-b752-88dd8e17125f', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.10.9', 'samcliVersion': '1.76.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': '6d4dc5bb46b13d42e5abbdf21c925d4ad5ee0261bc8b5b14bbba1c7ba718fcf1', 'projectName': '79e17e8bbc2ad1d8d09825ef61dd65abac87a0bef1ce5b54b642492011b2a47b', 'initialCommit': 'bef305d08dd75c45ace12dd13687ad146a44e57f18e8dc3e6ff088584b11ca28'}, 'duration': 1201, 'exitReason': 'ImageBuildException', 'exitCode': 1}}]}
2023-03-06 00:01:13,168 | Telemetry response: 200
Error: Building Image failed.
```

### Expected result:
Function is invoked successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Microsoft Windows 11 Pro, 10.0.22621 Build 22621
2. `sam --version`: AM CLI, version 1.76.0
3. AWS region: us-east-1

```
{
  "version": "1.76.0",
  "system": {
    "python": "3.10.9",
    "os": "Windows-10-10.0.22621-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "22.06.0-beta.0-917-gf888bd4531.m",
    "aws_cdk": "Not available",
    "terraform": "1.2.4"
  }
}
```
`docker --version`: `Docker version 20.10.22, build 3a2c30b`

### Additional Notes

Running `sam build --use-container` on the same project works.

Some google seems to indicate this issue is fixed in the `docker` python package >= 6.0.0

**Comment by RichiCoder1** [comment]
Went to try the same commands in WSL2 hoping there might be an issue, but ran into a different flavor of the same issue:

```
Invoking dist/handlers.testEntrypoint (nodejs18.x)
Local image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs18.x
Building image...
Failed to build Docker Image
Traceback (most recent call last):
  File "docker/api/client.py", line 261, in _raise_for_status
  File "requests/models.py", line 943, in raise_for_status
requests.exceptions.HTTPError: 502 Server Error: Bad Gateway for url: http+docker://localhost/v1.35/build?t=public.ecr.aws%2Flambda%2Fnodejs%3A18-rapid-x86_64&q=False&nocache=False&rm=True&forcerm=False&pull=True&platform=linux%2Famd64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "samcli/local/docker/lambda_image.py", line 319, in _build_image
  File "docker/api/client.py", line 354, in _stream_helper
  File "docker/api/client.py", line 267, in _result
  File "docker/api/client.py", line 263, in _raise_for_status
  File "docker/errors.py", line 31, in create_api_error_from_http_exception
docker.errors.APIError: 502 Server Error: Bad Gateway ("b'Bad response from Docker engine'")
```

**Comment by RichiCoder1** [comment]
Apparently it was related to this issue: https://github.com/docker/docker-py/issues/3063

Closing since I think it might be out of SAM's hands.
