### ISSUE TITLE
Bug: sam build - ResourceNotFound

### ISSUE THREAD

**Issue by edwardsunggoforward** [aws/aws-sam-cli#4843]
### Description:
I was trying to run Step 2 in this [webpage](https://aws.amazon.com/blogs/desktop-and-application-streaming/visualizing-appstream-2-0-session-latency-metrics-using-aws-lambda-amazon-kinesis-data-stream-and-amazon-opensearch-service/)

> To deploy the AWS SAM template:
> 
> Clone the solution repository using git:
> git clone https://github.com/aws-samples/appstream-session-latency-dashboard
> Build the AWS SAM project:
> sam build –use-container
> Deploy the project using AWS SAM:
> sam deploy –guided

When I run `sam build -use-container`, I got the error message. I am sure I have sam CLI installed. The version is 1.76.0

### Steps to reproduce:

Open terminal -> sam build -use-container -> error showed up

### Observed result:

```
2023-03-08 17:24:14,979 | Config file location: /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/samconfig.toml
2023-03-08 17:24:14,979 | Config file '/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/samconfig.toml' does not exist
2023-03-08 17:24:14,984 | Using SAM Template at /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/template.yaml
2023-03-08 17:24:15,016 | Using config file: samconfig.toml, config environment: default
2023-03-08 17:24:15,016 | Expand command line arguments to:
2023-03-08 17:24:15,016 | --template_file=/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2023-03-08 17:24:15,106 | 'build' command is called
2023-03-08 17:24:15,111 | Collected default values for parameters: {'OpensearchDomainEndpoint': 'example-xxxxxxxxxxxxx.us-east-1.es.amazonaws.com', 'OpensearchRegion': 'us-east-1', 'OpensearchIndex': 'indexdcv'}
2023-03-08 17:24:15,119 | There is no customer defined id or cdk path defined for resource PublishMetricsFunction, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,119 | There is no customer defined id or cdk path defined for resource DCVMetricsStream, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,119 | There is no customer defined id or cdk path defined for resource AppStreamToKinsisRole, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,119 | 0 stacks found in the template
2023-03-08 17:24:15,119 | Collected default values for parameters: {'OpensearchDomainEndpoint': 'example-xxxxxxxxxxxxx.us-east-1.es.amazonaws.com', 'OpensearchRegion': 'us-east-1', 'OpensearchIndex': 'indexdcv'}
2023-03-08 17:24:15,125 | There is no customer defined id or cdk path defined for resource PublishMetricsFunction, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,125 | There is no customer defined id or cdk path defined for resource DCVMetricsStream, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,125 | There is no customer defined id or cdk path defined for resource AppStreamToKinsisRole, so we will use the resource logical id as the resource id
2023-03-08 17:24:15,125 | 3 resources found in the stack 
2023-03-08 17:24:15,125 | Found Serverless function with name='PublishMetricsFunction' and CodeUri='Lambda_code/'
2023-03-08 17:24:15,125 | --base-dir is not presented, adjusting uri Lambda_code/ relative to /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/template.yaml
2023-03-08 17:24:15,154 | 3 resources found in the stack 
2023-03-08 17:24:15,154 | Found Serverless function with name='PublishMetricsFunction' and CodeUri='Lambda_code/'
2023-03-08 17:24:15,154 | Instantiating build definitions
2023-03-08 17:24:15,156 | Same function build definition found, adding function (Previous: BuildDefinition(python3.9, /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code, Zip, , 399f5a13-db00-410d-be15-a38f2cfff28f, {}, {}, x86_64, []), Current: BuildDefinition(python3.9, /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code, Zip, , b28634d9-83f0-4044-8def-eba8cbfc7250, {}, {}, x86_64, []), Function: Function(function_id='PublishMetricsFunction', name='PublishMetricsFunction', functionname='PublishMetricsFunction', runtime='python3.9', memory=256, timeout=10, handler='lambda_function.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code', environment={'Variables': {'OS_HOST': 'example-xxxxxxxxxxxxx.us-east-1.es.amazonaws.com', 'OS_INDEX_NAME': 'indexdcv', 'OS_REGION': 'us-east-1'}}, rolearn=None, layers=[<samcli.lib.providers.provider.LayerVersion object at 0x10425ce80>], events={'KinesisStream': {'Type': 'Kinesis', 'Properties': {'Stream': 'arn:aws:lambda:us-east-1:123456789012:function:DCVMetricsStream', 'BatchSize': 100, 'StartingPosition': 'TRIM_HORIZON', 'MaximumRetryAttempts': 2, 'MaximumBatchingWindowInSeconds': 10, 'FunctionResponseTypes': ['ReportBatchItemFailures']}}}, metadata={'SamResourceId': 'PublishMetricsFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path='', runtime_management_config=None))
2023-03-08 17:24:15,156 | Building codeuri: /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code runtime: python3.9 metadata: {} architecture: x86_64 functions: PublishMetricsFunction
2023-03-08 17:24:15,156 | Building to following folder /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction
2023-03-08 17:24:15,157 | Loading workflow module 'aws_lambda_builders.workflows'
2023-03-08 17:24:15,158 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-03-08 17:24:15,159 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-03-08 17:24:15,159 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-03-08 17:24:15,160 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-03-08 17:24:15,161 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-03-08 17:24:15,162 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-03-08 17:24:15,162 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-03-08 17:24:15,163 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-03-08 17:24:15,164 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-03-08 17:24:15,164 | Registering workflow 'RustCargoLambdaBuilder' with capability 'Capability(language='rust', dependency_manager='cargo', application_framework=None)'
2023-03-08 17:24:15,164 | Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-03-08 17:24:15,224 | Invalid executable for python at /usr/local/bin/python3
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 86, in wrapper
  File "aws_lambda_builders/workflows/python_pip/validator.py", line 52, in validate
aws_lambda_builders.exceptions.MisMatchRuntimeError: python executable found in your path does not match runtime. 
 Expected version: python3.9, Found a different version at /usr/local/bin/python3. 
 Possibly related: https://github.com/awslabs/aws-lambda-builders/issues/30
2023-03-08 17:24:15,265 | Running workflow 'PythonPipBuilder'
2023-03-08 17:24:15,265 | Running PythonPipBuilder:ResolveDependencies
2023-03-08 17:24:15,298 | calling pip download -r /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/requirements.txt --dest /var/folders/3r/smtqr99124l_wddj83r_mm240000gn/T/tmpg0dn7xl1 --exists-action i
2023-03-08 17:24:15,934 | Full dependency closure: {charset-normalizer==3.1.0(wheel), requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:15,935 | initial compatible: {requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:15,935 | initial incompatible: {charset-normalizer==3.1.0(wheel)}
2023-03-08 17:24:15,935 | Downloading missing wheels: {charset-normalizer==3.1.0(wheel)}
2023-03-08 17:24:15,935 | calling pip download --only-binary=:all: --no-deps --platform manylinux2014_x86_64 --implementation cp --abi cp39 --dest /var/folders/3r/smtqr99124l_wddj83r_mm240000gn/T/tmpg0dn7xl1 charset-normalizer==3.1.0
2023-03-08 17:24:16,267 | compatible wheels after second download pass: {charset-normalizer==3.1.0(wheel), requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:16,267 | Build missing wheels from sdists (C compiling True): set()
2023-03-08 17:24:16,268 | compatible after building wheels (no C compiling): {charset-normalizer==3.1.0(wheel), requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:16,268 | Build missing wheels from sdists (C compiling False): set()
2023-03-08 17:24:16,268 | compatible after building wheels (C compiling): {charset-normalizer==3.1.0(wheel), requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:16,268 | Final compatible: {charset-normalizer==3.1.0(wheel), requests==2.28.2(wheel), opensearch-py==2.2.0(wheel), certifi==2022.12.7(wheel), idna==3.4(wheel), six==1.16.0(wheel), urllib3==1.26.14(wheel), python-dateutil==2.8.2(wheel)}
2023-03-08 17:24:16,268 | Final incompatible: {charset-normalizer==3.1.0(wheel)}
2023-03-08 17:24:16,268 | Final missing wheels: set()
2023-03-08 17:24:16,312 | PythonPipBuilder:ResolveDependencies succeeded
2023-03-08 17:24:16,312 | Running PythonPipBuilder:CopySource
2023-03-08 17:24:16,313 | Copying source file (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/.DS_Store) to destination (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/.DS_Store)
2023-03-08 17:24:16,314 | Copying source file (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/requirements.txt) to destination (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/requirements.txt)
2023-03-08 17:24:16,314 | Creating target folders at /Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/opensearch_lib
2023-03-08 17:24:16,314 | Copying directory metadata from source (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/opensearch_lib) to destination (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/opensearch_lib)
2023-03-08 17:24:16,314 | Copying source file (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/opensearch_lib/__init__.py) to destination (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/opensearch_lib/__init__.py)
2023-03-08 17:24:16,315 | Copying source file (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/Lambda_code/lambda_function.py) to destination (/Users/edwardsung/Documents/Dev/infrastructure/cloudformation/appstream-session-latency-dashboard/.aws-sam/build/PublishMetricsFunction/lambda_function.py)
2023-03-08 17:24:16,315 | PythonPipBuilder:CopySource succeeded
2023-03-08 17:24:16,316 | There is no customer defined id or cdk path defined for resource PublishMetricsFunction, so we will use the resource logical id as the resource id
2023-03-08 17:24:16,316 | There is no customer defined id or cdk path defined for resource DCVMetricsStream, so we will use the resource logical id as the resource id
2023-03-08 17:24:16,316 | There is no customer defined id or cdk path defined for resource AppStreamToKinsisRole, so we will use the resource logical id as the resource id
2023-03-08 17:24:16,316 | 3 resources found in the stack 
2023-03-08 17:24:16,316 | Found Serverless function with name='PublishMetricsFunction' and CodeUri='Lambda_code/'

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
2023-03-08 17:24:16,320 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-03-08 17:24:16,390 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-03-08 17:24:16,390 | Unable to find Click Context for getting session_id.
2023-03-08 17:24:16,390 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'df2937d2-9d3d-4f6a-a432-01eaf93f3df1', 'installationId': '91f95589-46ae-4dd2-902b-8a58124fa7ce', 'sessionId': '7dbddd54-3370-47fe-b17b-9713837e8df5', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.76.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'b21ecd4fcf697af37d4cb648de616df90b3f981eb5595bda1bdd3d1d6defe04a', 'initialCommit': None}, 'duration': 1303, 'exitReason': 'success', 'exitCode': 0}}]}
2023-03-08 17:24:16,391 | Sending Telemetry: {'metrics': [{'events': {'requestId': '9459217f-359c-4f8f-82d3-b1ed5192cc69', 'installationId': '91f95589-46ae-4dd2-902b-8a58124fa7ce', 'sessionId': '7dbddd54-3370-47fe-b17b-9713837e8df5', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.13', 'samcliVersion': '1.76.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildFunctionRuntime', 'event_value': 'python3.9', 'thread_id': 8105066816, 'time_stamp': '2023-03-09 01:24:15.154'}, {'event_name': 'BuildWorkflowUsed', 'event_value': 'python-pip', 'thread_id': 8105066816, 'time_stamp': '2023-03-09 01:24:15.157'}]}}}]}
2023-03-08 17:24:16,554 | Telemetry response: 200
2023-03-08 17:24:16,556 | Telemetry response: 200
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Ventura 13.2.1
2. `sam --version`: 1.76.0
3. AWS region: us-west-2

```
# Paste the output of `sam --info` here
```
{
  "version": "1.76.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.2.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.23",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Thanks for reporting this issue @edwardsunggoforward !

It looks like your command have succeeded, you can see `Build Succeeded` output there. Can you explain a little bit more about what is failing for your use case?

**Comment by edwardsunggoforward** [comment]
Hey @mndeveci ,

Thanks for your quick response. This is the error message I got 
`–-use-container not found. Possible options in your template: ['PublishMetricsFunction']

Error: Unable to find a function or layer with name '–-use-container'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 148, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/build/command.py", line 186, in cli
  File "samcli/commands/build/command.py", line 279, in do_cli
  File "samcli/commands/build/build_context.py", line 237, in run
  File "samcli/commands/build/build_context.py", line 226, in get_resources_to_build
  File "samcli/commands/build/build_context.py", line 507, in resources_to_build
  File "samcli/commands/build/build_context.py", line 549, in collect_build_resources

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20ResourceNotFound
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20ResourceNotFound
`

And yes, I mistyped it. I still got the error message when I reran the command.

**Comment by mndeveci** [comment]
This is really weird, can you paste the exact command you run with its output? I am running following one and it executes as expected;
```
❯ sam build --use-container
Starting Build inside a container
Building codeuri: /private/tmp/cli-4843/appstream-session-latency-dashboard/Lambda_code runtime: python3.9 metadata: {} architecture: x86_64 functions: PublishMetricsFunction

Fetching public.ecr.aws/sam/build-python3.9:latest-x86_64 Docker container image......
Mounting /private/tmp/cli-4843/appstream-session-latency-dashboard/Lambda_code as /tmp/samcli/source:ro,delegated inside runtime container

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource
```

**Comment by edwardsunggoforward** [comment]
This is my input + output
` appstream-session-latency-dashboard % sam build –-use-container
–-use-container not found. Possible options in your template: ['PublishMetricsFunction']

Error: Unable to find a function or layer with name '–-use-container'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 148, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/build/command.py", line 186, in cli
  File "samcli/commands/build/command.py", line 279, in do_cli
  File "samcli/commands/build/build_context.py", line 237, in run
  File "samcli/commands/build/build_context.py", line 226, in get_resources_to_build
  File "samcli/commands/build/build_context.py", line 507, in resources_to_build
  File "samcli/commands/build/build_context.py", line 549, in collect_build_resources

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20ResourceNotFound
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20ResourceNotFound
`

**Comment by mndeveci** [comment]
Thanks for providing details, the dash character that you are using is still a different one, can you copy and paste the one that I am providing below?
```
sam build --use-container
```

**Comment by edwardsunggoforward** [comment]
It worked. Thank you so much sir. Sorry for the hassle.
