### ISSUE TITLE
Missing required parameter: --framework error when using sam build command

### ISSUE THREAD

**Issue by billou87** [aws/aws-sam-cli#4907]
### Description:

Hello, I'm trying to set up a build pipeline using ADO and I want to use the sam build command to test my template and packaging my project. But I always end up having this error when launching the sam build command on the developer powershell console. I'm currently using the .NET Serverless API template provided with the AWS Toolkit for Visual Studio. Template file was created from the serverless,template file from the project template. I'm using dotnet6 for this project.

Looks like the dotnet lambda package function that runs during command need that --framework parameter but I don't see a way to pass it from sam build parameters.

### Steps to reproduce:

Run the following command in developer powershell console, using Visual Studio 2022 Enterprise with serverless API AWS lambda template for .NET6.
` sam build --debug --template-file template.yml`
Also tried : 
` sam build --debug --template-file template.yml --beta-features`

### Observed result:

```
2023-03-22 12:39:34,344 | Using SAM Template at C:\Users\*****\Source\Repos\*****\src\*****.API\template.yml
2023-03-22 12:39:34,344 | Config file location: C:\Users\*****\Source\Repos\*****\src\*****.API\samconfig.toml
2023-03-22 12:39:34,345 | Config file 'C:\Users\*****\Source\Repos\*****\src\*****.API\samconfig.toml' does not exist
2023-03-22 12:39:34,498 | Using config file: samconfig.toml, config environment: default
2023-03-22 12:39:34,498 | Expand command line arguments to:
2023-03-22 12:39:34,498 | --template_file=C:\Users\*****\Source\Repos\*****\src\*****.API\template.yml --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache
2023-03-22 12:39:36,036 | 'build' command is called
2023-03-22 12:39:36,040 | No Parameters detected in the template
2023-03-22 12:39:36,077 | There is no customer defined id or cdk path defined for resource AspNetCoreFunction, so we will use the resource logical id as the resource id
2023-03-22 12:39:36,077 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-03-22 12:39:36,078 | Unable to resolve property Role: None. Leaving as is.
2023-03-22 12:39:36,079 | 0 stacks found in the template
2023-03-22 12:39:36,079 | No Parameters detected in the template
2023-03-22 12:39:36,103 | There is no customer defined id or cdk path defined for resource AspNetCoreFunction, so we will use the resource logical id as the resource id
2023-03-22 12:39:36,103 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-03-22 12:39:36,104 | Unable to resolve property Role: None. Leaving as is.
2023-03-22 12:39:36,104 | 2 resources found in the stack
2023-03-22 12:39:36,105 | Found Serverless function with name='AspNetCoreFunction' and CodeUri='.'
2023-03-22 12:39:36,105 | --base-dir is not presented, adjusting uri . relative to C:\Users\*****\Source\Repos\*****\src\*****.API\template.yml
2023-03-22 12:39:36,111 | 2 resources found in the stack
2023-03-22 12:39:36,111 | Found Serverless function with name='AspNetCoreFunction' and CodeUri='.'
2023-03-22 12:39:36,113 | Instantiating build definitions
2023-03-22 12:39:36,117 | Same function build definition found, adding function (Previous: BuildDefinition(dotnet6, C:\Users\*****\Source\Repos\*****\src\*****.API, Zip, , 74c7d00d-f2ff-4e72-b72a-33e7c0269704, {}, {}, x86_64, []), Current: BuildDefinition(dotnet6, C:\Users\*****\Source\Repos\*****\src\*****.API, Zip, , 5d8ec588-0ff0-4636-bd22-4becda330840, {}, {}, x86_64, []), Function: Function(function_id='AspNetCoreFunction', name='AspNetCoreFunction', functionname='AspNetCoreFunction', runtime='dotnet6', memory=256, timeout=30, handler='*****.API::*****.API.LambdaEntryPoint::FunctionHandlerAsync', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Users\\*****\\Source\\Repos\\*****\\src\\*****.API', environment=None, rolearn=None, layers=[], events={'ProxyResource': {'Type': 'Api', 'Properties': {'Path': '/{proxy+}', 'Method': 'ANY', 'RestApiId': 'ServerlessRestApi'}}, 'RootResource': {'Type': 'Api', 'Properties': {'Path': '/', 'Method': 'ANY', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'AspNetCoreFunction'}, inlinecode=None, codesign_config_arn=None, architectures=None, function_url_config=None, stack_path='', runtime_management_config=None))
2023-03-22 12:39:36,121 | Building codeuri: C:\Users\*****\Source\Repos\*****\src\*****.API runtime: dotnet6 metadata: {} architecture: x86_64 functions: AspNetCoreFunction
2023-03-22 12:39:36,122 | Building to following folder C:\Users\*****\source\repos\*****\src\*****.API\.aws-sam\build\AspNetCoreFunction
2023-03-22 12:39:36,126 | Loading workflow module 'aws_lambda_builders.workflows'
2023-03-22 12:39:36,138 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-03-22 12:39:36,144 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-03-22 12:39:36,150 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-03-22 12:39:36,161 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-03-22 12:39:36,173 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-03-22 12:39:36,181 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-03-22 12:39:36,189 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-03-22 12:39:36,197 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-03-22 12:39:36,204 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-03-22 12:39:36,205 | Found workflow 'DotnetCliPackageBuilder' to support capabilities 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-03-22 12:39:36,212 | Running workflow 'DotnetCliPackageBuilder'
2023-03-22 12:39:36,212 | Running DotnetCliPackageBuilder:GlobalToolInstall
2023-03-22 12:39:36,212 | Entered synchronized block for updating Amazon.Lambda.Tools
2023-03-22 12:39:36,213 | Installing Amazon.Lambda.Tools Global Tool
2023-03-22 12:39:36,213 | executing dotnet: ['dotnet.exe', 'tool', 'install', '-g', 'Amazon.Lambda.Tools', '--ignore-failed-sources']
2023-03-22 12:39:36,751 |
2023-03-22 12:39:36,752 | Error installing probably due to already installed. Attempt to update to latest version.
2023-03-22 12:39:36,752 | executing dotnet: ['dotnet.exe', 'tool', 'update', '-g', 'Amazon.Lambda.Tools', '--ignore-failed-sources']
2023-03-22 12:39:40,606 | C:\Users\*****\AppData\Local\Temp\579b86b9-2bab-4355-b4d2-2246b6917128\restore.csproj : warning NU1803: You are running the 'restore' operation with an 'HTTP' source, 'http://tfs.*****.ict:8080/tfs/*****%*****%20Projects/_packaging/In-house/nuget/v3/index.json'. Non-HTTPS access will be removed in a future version. Consider migrating to an 'HTTPS' source.
Tool 'amazon.lambda.tools' was reinstalled with the latest stable version (version '5.6.4').
2023-03-22 12:39:40,607 | DotnetCliPackageBuilder:GlobalToolInstall succeeded
2023-03-22 12:39:40,607 | Running DotnetCliPackageBuilder:RunPackageAction
2023-03-22 12:39:40,607 | Running `dotnet lambda package` in C:\Users\*****\source\repos\*****\src\*****.API
2023-03-22 12:39:40,607 | executing dotnet: ['dotnet.exe', 'lambda', 'package', '--output-package', 'C:\\Users\\*****\\source\\repos\\*****\\src\\*****.API\\.aws-sam\\build\\AspNetCoreFunction\\*****.API.zip', '--msbuild-parameters', '--runtime linux-x64']
2023-03-22 12:39:42,205 | Amazon Lambda Tools for .NET Core applications (5.6.4)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Missing required parameter: --framework
2023-03-22 12:39:42,205 | DotnetCliPackageBuilder:RunPackageAction failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\actions.py", line 107, in execute
    self.subprocess_dotnet.run(arguments, cwd=self.source_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\dotnetcli.py", line 66, inaws_lambda_builders.workflows.dotnet_clipackage.dotnetcli.DotnetCLIExecutionError: Dotnet CLI Failed:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 372, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\dotnet_clipackage\actions.py", line 114, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Dotnet CLI Failed:
```

### Expected result:
Sam build command succeeds with CloudFormation file and dotnet package to be deployed to S3.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: windows10
2. `sam --version`: 1.73.0
3. AWS region: us-east-2

```
# Paste the output of `sam --info` here
{
  "version": "1.73.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Thanks @billou87 for raising this issue. Could you please share with us the template you are using in this project?

**Comment by billou87** [comment]
Hi @moelasmar ,

Sure, it is the AWS Serverless Application with Tests (.NET Core - C#) template. It is available with the AWS toolkit for Visual Studio.

Thanks.

**Comment by billou87** [comment]
Hello, 

Just found out I got some case-sensitive file issue and config issue with Directory.Props.file that I added in the project. Got it to work now. Sorry for the inconvenience.
