### ISSUE TITLE
Bug: sam sync - NotADirectoryError

### ISSUE THREAD

**Issue by JadenSimon** [aws/aws-sam-cli#4911]
### Description:

Seeing this error when attempting to re-deploy a hello world app (nodejs16.x):
```
Error: [Errno 20] Not a directory: PosixPath('.aws-sam/deps/.DS_Store')
```

### Steps to reproduce:

Honestly I'm not entirely sure which steps are causing problems but this is roughly what I did:
1. Create a new SAM app
2. Deploy it
3. Make a code change and deploy again
4. Create another SAM app with the same runtime/template, append `-1` to the directory
    * You should have 2 application directories in your workspace: `lambda-nodejs16.x` and `lambda-nodejs16.x-1`
5. Deploy the new app to the same stack/bucket
6. Make a code change and deploy again -> `Error: [Errno 66] Directory not empty: '.aws-sam/build'`
    * Deleting `.aws-sam/build` and deploying results in the error mentioned in the issue

### Observed result:

There's a lot of output so here's a snippet I think might be helpful:
```
2023-03-22 16:05:59,245 | Entering sync context, previous state: SyncState(dependency_layer=False, resource_sync_states={}, latest_infra_sync_time=datetime.datetime(2023, 3, 22, 23, 0, 54, 485790)), current state: SyncState(dependency_layer=False, resource_sync_states={}, latest_infra_sync_time=datetime.datetime(2023, 3, 22, 23, 0, 54, 485790))
2023-03-22 16:05:59,390 | No Parameters detected in the template
2023-03-22 16:05:59,449 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-03-22 16:05:59,450 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-03-22 16:05:59,450 | 0 stacks found in the template
2023-03-22 16:05:59,450 | No Parameters detected in the template
2023-03-22 16:05:59,472 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-03-22 16:05:59,472 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-03-22 16:05:59,473 | 2 resources found in the stack 
2023-03-22 16:05:59,473 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2023-03-22 16:05:59,473 | --base-dir is not presented, adjusting uri hello-world/ relative to /test-workspace/lambda-nodejs16.x-1/template.yaml
2023-03-22 16:05:59,480 | 2 resources found in the stack 
2023-03-22 16:05:59,480 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2023-03-22 16:05:59,481 | Instantiating build definitions
2023-03-22 16:05:59,485 | Same function build definition found, adding function (Previous: BuildDefinition(nodejs16.x, /test-workspace/lambda-nodejs16.x-1/hello-world, Zip, , bbd6532e-4a45-4d76-a24d-df8207df7010, {}, {}, x86_64, []), Current: BuildDefinition(nodejs16.x, /test-workspace/lambda-nodejs16.x-1/hello-world, Zip, , 75ebb4bf-d1f9-4caf-8c1d-38f626e7d124, {}, {}, x86_64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='nodejs16.x', memory=128, timeout=3, handler='app.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='/test-workspace/lambda-nodejs16.x-1/hello-world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path='', runtime_management_config=None))
2023-03-22 16:05:59,487 | Async execution started
2023-03-22 16:05:59,487 | Invoking function functools.partial(<bound method ParallelBuildStrategy.build_single_function_definition of <samcli.lib.build.build_strategy.ParallelBuildStrategy object at 0x10df14640>>, <samcli.lib.build.build_graph.FunctionBuildDefinition object at 0x10ec9f880>)
2023-03-22 16:05:59,487 | Running incremental build for runtime nodejs16.x for following resources (HelloWorldFunction)
2023-03-22 16:05:59,488 | Waiting for async results
2023-03-22 16:05:59,488 | Manifest is not changed for (HelloWorldFunction), running incremental build
2023-03-22 16:05:59,488 | Building codeuri: /test-workspace/lambda-nodejs16.x-1/hello-world runtime: nodejs16.x metadata: {} architecture: x86_64 functions: HelloWorldFunction
2023-03-22 16:05:59,488 | Building to following folder /test-workspace/.aws-sam/build/HelloWorldFunction
```

### Expected result:

No errors. Or at least a better explanation for what I'm doing wrong.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.77.0",
  "system": {
    "python": "3.8.16",
    "os": "macOS-12.6.2-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "2.63.2 (build e08e34a)",
    "terraform": "Not available"
  }
}
```

**Comment by mndeveci** [comment]
Stack trace for the error;
```
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/watch_manager.py", line 228, in _execute_infra_sync
    infra_sync_result = self._execute_infra_context(first_sync)
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/watch_manager.py", line 167, in _execute_infra_context
    return self._infra_sync_executor.execute_infra_sync(first_sync)
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/sync/infra_sync_executor.py", line 163, in execute_infra_sync
    self._build_context.run()
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/commands/build/build_context.py", line 279, in run
    self._build_result = builder.build()
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/build/app_builder.py", line 214, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 393, in build
    return super().build()
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 603, in __exit__
    self._incremental_build_strategy._clean_redundant_dependencies()
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 509, in _clean_redundant_dependencies
    clean_redundant_folders(DEFAULT_DEPENDENCIES_DIR, uuids)
  File "/usr/local/Cellar/aws-sam-cli/1.77.0/libexec/lib/python3.8/site-packages/samcli/lib/build/build_strategy.py", line 55, in clean_redundant_folders
    shutil.rmtree(pathlib.Path(base_dir, full_dir_path.name))
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 718, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 631, in _rmtree_safe_fd
    onerror(os.scandir, path, sys.exc_info())
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 627, in _rmtree_safe_fd
    with os.scandir(topfd) as scandir_it:
NotADirectoryError: [Errno 20] Not a directory: PosixPath('.aws-sam/deps/.DS_Store')
```
