### ISSUE TITLE
Bug: sam build - AttributeError

### ISSUE THREAD

**Issue by Savops** [aws/aws-sam-cli#4915]
### Description:
Plugin 'ServerlessAppPlugin' raised an exception: 'NoneType' object has no attribute 'get'

### Steps to reproduce:
Error raised when trying to sam build

### Observed result:
```
2023-03-23 12:46:26,616 | Config file location: /home/user/samconfig.toml
2023-03-23 12:46:26,616 | Loading configuration values from [default.['build'].parameters] (env.command_name.section) in config file at '/home/user/samconfig.toml'...
2023-03-23 12:46:26,622 | Configuration values successfully loaded.
2023-03-23 12:46:26,622 | Configuration values are: {}
2023-03-23 12:46:26,653 | Using SAM Template at /home/user/template.yaml
2023-03-23 12:46:26,705 | Using config file: samconfig.toml, config environment: default
2023-03-23 12:46:26,705 | Expand command line arguments to:
2023-03-23 12:46:26,705 | --template_file=/home/user/template.yaml --build_dir=.aws-sam/build --cache_dir=.aws-sam/cache 
2023-03-23 12:46:26,895 | 'build' command is called
2023-03-23 12:46:26,927 | Collected default values for parameters: {'EnvType': 'dev'}
2023-03-23 12:46:26 Plugin 'ServerlessAppPlugin' raised an exception: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "samtranslator/plugins/sam_plugins.py", line 132, in act
  File "samtranslator/metrics/method_decorator.py", line 98, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 102, in on_before_transform_template
  File "samtranslator/sdk/template.py", line 35, in iterate
  File "samtranslator/sdk/resource.py", line 26, in __init__
AttributeError: 'NoneType' object has no attribute 'get'
2023-03-23 12:46:26,941 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-03-23 12:46:26,942 | Template is not provided in context, skip adding project type metric
2023-03-23 12:46:26,955 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '21f7a81d-6946-44ab-a344-b547c8f89e1a', 'installationId': '97cb8b1b-7b1b-40cd-995a-c20298937ef7', 'sessionId': 'a1967df5-6359-4c11-96ca-2becaba9602e', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.10', 'samcliVersion': '1.73.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'gitOrigin': None, 'projectName': '9f9aca7eb962d89a51b2bd1b6259d417af3f9e060469e1ab559bd428b1c619ab', 'initialCommit': None}, 'duration': 236, 'exitReason': 'AttributeError', 'exitCode': 255}}]}
2023-03-23 12:46:27,948 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

Error: 'NoneType' object has no attribute 'get'
Traceback:
  File "click/core.py", line 1055, in main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "click/decorators.py", line 84, in new_func
  File "click/core.py", line 760, in invoke
  File "samcli/lib/telemetry/metric.py", line 183, in wrapped
  File "samcli/lib/telemetry/metric.py", line 150, in wrapped
  File "samcli/lib/utils/version_checker.py", line 41, in wrapped
  File "samcli/cli/main.py", line 92, in wrapper
  File "samcli/commands/build/command.py", line 207, in cli
  File "samcli/commands/build/command.py", line 277, in do_cli
  File "samcli/commands/build/build_context.py", line 176, in __enter__
  File "samcli/commands/build/build_context.py", line 185, in set_up
  File "samcli/lib/providers/sam_stack_provider.py", line 258, in get_stacks
  File "samcli/lib/providers/sam_stack_provider.py", line 54, in __init__
  File "samcli/lib/providers/sam_base_provider.py", line 189, in get_template
  File "samcli/lib/samlib/wrapper.py", line 73, in run_plugins
  File "samcli/lib/samlib/wrapper.py", line 130, in parse
  File "samtranslator/plugins/sam_plugins.py", line 138, in act
  File "samtranslator/plugins/sam_plugins.py", line 132, in act
  File "samtranslator/metrics/method_decorator.py", line 98, in wrapper_cw_timer
  File "samtranslator/plugins/application/serverless_app_plugin.py", line 102, in on_before_transform_template
  File "samtranslator/sdk/template.py", line 35, in iterate
  File "samtranslator/sdk/reso
urce.py", line 26, in __init__
```

### Expected result:
Build completed

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: xUbuntu 20.04
2. `sam --version`: 1.73
3. AWS region: us-east-2 (Ohio)

```
# Paste the output of `sam --info` here
```
{
  "version": "1.73.0",
  "system": {
    "python": "3.7.10",
    "os": "Linux-5.19.0-35-generic-x86_64-with-debian-bookworm-sid"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

**Comment by moelasmar** [comment]
Thanks @Savops for raising this issue.
Could you please share a template that we can use to reproduce this issue.

**Comment by Savops** [comment]
Here is the template we're using - 

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Calls Denic APIs and returns results back to tier 2

Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 20
    Handler: lambda_function.lambda_handler

Parameters:
  EnvType:
    Default: dev
    Type: String
    AllowedValues:
      - prod
      - staging
      - dev
    
Conditions:
  IsProduction: !Equals 
    - !Ref EnvType
    - prod

  IsStaging: !Equals
    - !Ref EnvType
    - staging

  IsDev: !Equals
     - !Ref EnvType
     - dev

  IsStagingOrProduction: !Or
    - !Condition IsProduction
    - !Condition IsStaging

Mappings:
  AccountRegion:
    us-east-2:
      "531454079470": "us-east-2.531454079470"
      "237413793994": "us-east-2.237413793994"
    us-west-2:
      "531454079470": "us-west-2.531454079470"
      "237413793994": "us-west-2.237413793994"
    us-east-1:
      "531454079470": "us-east-1.531454079470"
      "237413793994": "us-east-1.237413793994"

  LayerVersions:
    "us-east-2.531454079470":
      "Gnup": arn:aws:lambda:us-east-2:531454079470:layer:GNUP:1
      "Gnup37": arn:aws:lambda:us-east-2:531454079470:layer:GNUP-3-7:1
      "GenerateAuthCode": arn:aws:lambda:us-east-2:531454079470:layer:generate-auth-code:3
      "denicSdk": arn:aws:lambda:us-east-2:531454079470:layer:denic-sdk:1
      "Paramiko": arn:aws:lambda:us-east-2:531454079470:layer:paramiko:8
      "PhoneAndAddressValidation": arn:aws:lambda:us-east-2:531454079470:layer:phone-and-address-validation:2
      "Qldb": arn:aws:lambda:us-east-2:531454079470:layer:qldb:1
      "Rdap": arn:aws:lambda:us-east-2:531454079470:layer:rdap:4
      "Requests": arn:aws:lambda:us-east-2:531454079470:layer:requests:1
      "SavGeneralIncludes": arn:aws:lambda:us-east-2:531454079470:layer:sav-general-includes:31
      "StatusCode": arn:aws:lambda:us-east-2:531454079470:layer:status-code:1
      "TldExtraction": arn:aws:lambda:us-east-2:531454079470:layer:tld-extraction:6
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-east-2:531454079470:layer:get-pending-delete-domains-layer:3
      "IDNCheck": arn:aws:lambda:us-east-2:531454079470:layer:idn-check:1
    "us-east-2.237413793994":
      "Gnup": arn:aws:lambda:us-east-2:237413793994:layer:GNUP:4
      "Gnup37": arn:aws:lambda:us-east-2:237413793994:layer:GNUP-3-7:4
      "GenerateAuthCode": arn:aws:lambda:us-east-2:237413793994:layer:generate-auth-code:6
      "denicSdk": arn:aws:lambda:us-east-2:237413793994:layer:denic-sdk:4
      "Paramiko": arn:aws:lambda:us-east-2:237413793994:layer:paramiko:2
      "PhoneAndAddressValidation": arn:aws:lambda:us-east-2:237413793994:layer:phone-and-address-validation:5
      "Qldb": arn:aws:lambda:us-east-2:237413793994:layer:qldb:4
      "Rdap": arn:aws:lambda:us-east-2:237413793994:layer:rdap:7
      "Requests": arn:aws:lambda:us-east-2:237413793994:layer:requests:4
      "SavGeneralIncludes": arn:aws:lambda:us-east-2:237413793994:layer:sav-general-includes:64
      "StatusCode": arn:aws:lambda:us-east-2:237413793994:layer:status-code:4
      "TldExtraction": arn:aws:lambda:us-east-2:237413793994:layer:tld-extraction:16
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-east-2:237413793994:layer:get-pending-delete-domains-layer:8
      "IDNCheck": arn:aws:lambda:us-east-2:237413793994:layer:idn-check:1
    "us-east-1.531454079470":
      "Gnup": arn:aws:lambda:us-east-1:531454079470:layer:GNUP:1
      "Gnup37": arn:aws:lambda:us-east-1:531454079470:layer:GNUP-3-7:1
      "GenerateAuthCode": arn:aws:lambda:us-east-1:531454079470:layer:generate-auth-code:2
      "denicSdk": arn:aws:lambda:us-east-1:531454079470:layer:denic-sdk:1
      "Paramiko": arn:aws:lambda:us-east-1:531454079470:layer:paramiko:1
      "PhoneAndAddressValidation": arn:aws:lambda:us-east-1:531454079470:layer:phone-and-address-validation:2
      "Qldb": arn:aws:lambda:us-east-1:531454079470:layer:qldb:1
      "Rdap": arn:aws:lambda:us-east-1:531454079470:layer:rdap:2
      "Requests": arn:aws:lambda:us-east-1:531454079470:layer:requests:1
      "SavGeneralIncludes": arn:aws:lambda:us-east-1:531454079470:layer:sav-general-includes:20
      "StatusCode": arn:aws:lambda:us-east-1:531454079470:layer:status-code:1
      "TldExtraction": arn:aws:lambda:us-east-1:531454079470:layer:tld-extraction:4
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-east-1:531454079470:layer:get-pending-delete-domains-layer:4
      "IDNCheck": arn:aws:lambda:us-east-1:531454079470:layer:idn-check:1
    "us-east-1.237413793994":
      "Gnup": arn:aws:lambda:us-east-1:237413793994:layer:GNUP:1
      "Gnup37": arn:aws:lambda:us-east-1:237413793994:layer:GNUP-3-7:1
      "GenerateAuthCode": arn:aws:lambda:us-east-1:237413793994:layer:generate-auth-code:1
      "denicSdk": arn:aws:lambda:us-east-1:237413793994:layer:denic-sdk:1
      "Paramiko": arn:aws:lambda:us-east-1:237413793994:layer:paramiko:1
      "PhoneAndAddressValidation": arn:aws:lambda:us-east-1:237413793994:layer:phone-and-address-validation:1
      "Qldb": arn:aws:lambda:us-east-1:237413793994:layer:qldb:1
      "Rdap": arn:aws:lambda:us-east-1:237413793994:layer:rdap:1
      "Requests": arn:aws:lambda:us-east-1:237413793994:layer:requests:1
      "SavGeneralIncludes": arn:aws:lambda:us-east-1:237413793994:layer:sav-general-includes:4
      "StatusCode": arn:aws:lambda:us-east-1:237413793994:layer:status-code:1
      "TldExtraction": arn:aws:lambda:us-east-1:237413793994:layer:tld-extraction:1
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-east-1:237413793994:layer:get-pending-delete-domains-layer:2
      "IDNCheck": arn:aws:lambda:us-east-1:237413793994:layer:idn-check:1
    "us-west-2.531454079470":
      "Gnup": arn:aws:lambda:us-west-2:531454079470:layer:GNUP:2
      "Gnup37": arn:aws:lambda:us-west-2:531454079470:layer:GNUP-3-7:2
      "GenerateAuthCode": arn:aws:lambda:us-west-2:531454079470:layer:generate-auth-code:2
      "denicSdk": arn:aws:lambda:us-west-2:531454079470:layer:denic-sdk:2
      "PhoneAndAddressValidation": arn:aws:lambda:us-west-2:531454079470:layer:phone-and-address-validation:2
      "Qldb": arn:aws:lambda:us-west-2:531454079470:layer:qldb:2
      "Rdap": arn:aws:lambda:us-west-2:531454079470:layer:rdap:2
      "Requests": arn:aws:lambda:us-west-2:531454079470:layer:requests:2
      "SavGeneralIncludes": arn:aws:lambda:us-west-2:531454079470:layer:sav-general-includes:9
      "StatusCode": arn:aws:lambda:us-west-2:531454079470:layer:status-code:2
      "TldExtraction": arn:aws:lambda:us-west-2:531454079470:layer:tld-extraction:2
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-west-2:531454079470:layer:get-pending-delete-domains-layer:1
      "IDNCheck": arn:aws:lambda:us-west-2:531454079470:layer:idn-check:1
    "us-west-2.237413793994":
      "Gnup": arn:aws:lambda:us-west-2:237413793994:layer:GNUP:2
      "Gnup37": arn:aws:lambda:us-west-2:237413793994:layer:GNUP-3-7:2
      "GenerateAuthCode": arn:aws:lambda:us-west-2:237413793994:layer:generate-auth-code:2
      "denicSdk": arn:aws:lambda:us-west-2:237413793994:layer:denic-sdk:2
      "PhoneAndAddressValidation": arn:aws:lambda:us-west-2:237413793994:layer:phone-and-address-validation:2
      "Qldb": arn:aws:lambda:us-west-2:237413793994:layer:qldb:2
      "Rdap": arn:aws:lambda:us-west-2:237413793994:layer:rdap:2
      "Requests": arn:aws:lambda:us-west-2:237413793994:layer:requests:2
      "SavGeneralIncludes": arn:aws:lambda:us-west-2:237413793994:layer:sav-general-includes:9
      "StatusCode": arn:aws:lambda:us-west-2:237413793994:layer:status-code:2
      "TldExtraction": arn:aws:lambda:us-west-2:237413793994:layer:tld-extraction:2
      "GetPendingDeleteDomainsLayer": arn:aws:lambda:us-west-2:237413793994:layer:get-pending-delete-domains-layer:1
      "IDNCheck": arn:aws:lambda:us-west-2:237413793994:layer:idn-check:1

Resources:


  CredentialDenicFifoQueueContainerized:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: !If [IsDev, tier_3_credential_id_530_containerized.fifo, tier_3_credential_id_437_containerized.fifo]
    ContentBasedDeduplication: false
    FifoQueue: true
    MessageRetentionPeriod: 2400

  StartMicroservice:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: start-tier-3-denic
      InlineCode: |
        import json
        import boto3
        import os

        def lambda_handler(event, context):
            operation_id = event['Records'][0]['body']
            sfn = boto3.client('stepfunctions')
            sfn.start_execution(
                    stateMachineArn = os.environ['STEP_FUNCTION_ARN'],
                    input=json.dumps(operation_id)
                )

            return {
                'body': operation_id
            }
      Handler: index.lambda_handler
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/main-lambda
      Architectures: [arm64]
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvType
          STEP_FUNCTION_ARN: !GetAtt MainStateMachine.Arn
      Events:
        Credential530Event:
          Type: SQS
          Properties:
            Queue: !GetAtt CredentialDenicFifoQueueContainerized.Arn
            BatchSize: 1

  StateMachineFailureAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions: 
        - !ImportValue sns-topic-step-function-failures
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt MainStateMachine.Arn
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 0
      MetricName: ExecutionsFailed
      Namespace: AWS/States
      Period: 60
      TreatMissingData: notBreaching

  StateMachineTimedOutAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions: 
        - !ImportValue sns-topic-step-function-failures
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt MainStateMachine.Arn
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 0
      MetricName: ExecutionsTimedOut
      Namespace: AWS/States
      Period: 60
      TreatMissingData: notBreaching

  StateMachineThrottledAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsProduction
    Properties:
      AlarmActions: 
        - !ImportValue sns-topic-step-function-failures
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: StateMachineArn
          Value: !GetAtt MainStateMachine.Arn
      EvaluationPeriods: 1
      Statistic: Sum
      Threshold: 0
      MetricName: ExecutionsThrottled
      Namespace: AWS/States
      Period: 60
      TreatMissingData: notBreaching

  MainStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name: tier-3-denic
      DefinitionUri: ./step-functions/tier-3-denic.asl.json
      DefinitionSubstitutions:
        CallDenicApi-Arn: !GetAtt CallDenicApi.Arn
        GetRequestDataFromDynamo-Arn: !ImportValue global-get-request-data-from-dynamo
        GetConnectionDetailsFromRds-Arn: !ImportValue global-get-connection-details-from-rds
        SetStatusToInProgressInDynamo-Arn: !ImportValue global-set-status-to-in-progress-in-dynamo
        SetStatusToCompletedInDynamo-Arn: !ImportValue global-set-status-to-completed-in-dynamo
        SetStatusToFailedInDynamo-Arn: !ImportValue global-set-status-to-failed-in-dynamo
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/main-step-function

  CallDenicApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: call-denic-api
      CodeUri: ./lambdas/call-denic-api
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/main-lambda
      Architectures: [arm64]
      Environment:
        Variables:
          ENVIRONMENT: !Ref EnvType
      Timeout: 300
      Layers: 
        - !FindInMap [LayerVersions, !FindInMap [AccountRegion, !Ref "AWS::Region", !Ref "AWS::AccountId"], SavGeneralIncludes]
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue vpc-sg
        SubnetIds:
          - !ImportValue private-subnet-1
          - !ImportValue private-subnet-2
        `
```

**Comment by mildaniel** [comment]
Thanks for reporting and providing your template. We'll try to reproduce the issue.

**Comment by mildaniel** [comment]
Hey @Savops, it looks like for the first resource
```
CredentialDenicFifoQueueContainerized:
Type: AWS::SQS::Queue
Properties:
    QueueName: !If [IsDev, tier_3_credential_id_530_containerized.fifo, tier_3_credential_id_437_containerized.fifo]
    ContentBasedDeduplication: false
    FifoQueue: true
    MessageRetentionPeriod: 2400
```
there's no indentation after the logical ID. Try indenting the resource body and the issue should be resolved.

**Comment by qingchm** [comment]
@Savops Closing the issue here as it seems like the above suggestion will help with your issue. Please feel free to re-open the issue and engage us if the suggestion doesn't fix the problem for you!
