### ISSUE TITLE
Bug: AWS Lambda Hello World Example Typescript: "sam local invoke" gives Error: Cannot find module 'app'

### ISSUE THREAD

**Issue by DaCao** [aws/aws-sam-cli#4997]
### Description:
I am trying to deploy an AWS Lambda function with `sam` using AWS's Hello World Example Typescript template, and the example template is not working.  I am pretty sure this is a bug in AWS. 

### Steps to reproduce:

It is very easy to replicate: 

I am in an EC2 instance with ubuntu. Just run: 

`sam init`

and follow this configuration: 
```

Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1

Choose an AWS Quick Start application template
        1 - Hello World Example
        2 - Multi-step workflow
        3 - Serverless API

        ...

Template: 1

Use the most popular runtime and package type? (Python and zip) [y/N]: N

Which runtime would you like to use?
        1 - aot.dotnet7 (provided.al2)
        2 - dotnet6
        3 - dotnet5.0
        4 - dotnetcore3.1
        5 - go1.x
        6 - go (provided.al2)
        7 - graalvm.java11 (provided.al2)
        8 - graalvm.java17 (provided.al2)
        9 - java11
        10 - java8.al2
        11 - java8
        12 - nodejs18.x
        13 - nodejs16.x
        14 - nodejs14.x
        15 - nodejs12.x

Runtime: 14

What package type would you like to use?
        1 - Zip
        2 - Image
Package type: 1

Based on your selections, the only dependency manager available is npm.
We will proceed copying the template using npm.

Select your starter template
        1 - Hello World Example
        2 - Hello World Example TypeScript
Template: 2

Would you like to enable X-Ray tracing on the function(s) in your application?  [y/N]: N

Would you like to enable monitoring using CloudWatch Application Insights?
For more info, please view https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-application-insights.html [y/N]: N

Project name [sam-app]: 

    -----------------------
    Generating application:
    -----------------------
    Name: sam-app
    Runtime: nodejs14.x
    Architectures: x86_64
    Dependency Manager: npm
    Application Template: hello-world-typescript
    Output Directory: .
    Configuration file: sam-app/samconfig.toml
    
    Next steps can be found in the README file at sam-app/README.md
        
```

Now we get this template: 
```
ubuntu@ip-111-31-16-16:~/MyAPP/lambda$ tree sam-app/
sam-app/
├── README.md
├── events
│   └── event.json
├── hello-world
│   ├── app.ts
│   ├── jest.config.ts
│   ├── package.json
│   ├── tests
│   │   └── unit
│   │       └── test-handler.test.ts
│   └── tsconfig.json
├── samconfig.toml
└── template.yaml

4 directories, 9 files
```

Now if I go into `/sam-app` and just run: 
```
ubuntu@ip-111-31-16-16:~/MyAPP/lambda/sam-app$ sam local invoke --event events/event.json
```

I get this error: `Error: Cannot find module 'app'`; the full message is here: 

```
ubuntu@ip-111-31-16-16:~/MyApp/lambda/sam-app$ sam local invoke --event events/event.json
Invoking app.lambdaHandler (nodejs14.x)
Local image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs14.x
Building image..............................................................................................................................................................
Using local image: public.ecr.aws/lambda/nodejs:14-rapid-x86_64.

Mounting /home/ubuntu/MyApp/lambda/sam-app/hello-world as /var/task:ro,delegated, inside runtime container
START RequestId: 4a6ba3fe-f24c-4f10-9840-e66c2abafc50 Version: $LATEST
2023-04-10T18:13:12.492Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
10 Apr 2023 18:13:12,511 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2023-04-10T18:13:12.641Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
END RequestId: 2865c9f0-be40-47a2-b050-796ebd0aeaec

REPORT RequestId: 2865c9f0-be40-47a2-b050-796ebd0aeaec  Init Duration: 0.65 ms  Duration: 472.07 ms     Billed Duration: 473 ms Memory Size: 128 MB   Max Memory Used: 128 MB

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","trace":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
```

Note that in the `sam init` step, in this step: 
```
Select your starter template
        1 - Hello World Example
        2 - Hello World Example TypeScript
Template: 2

```
If only I had chosen 1 instead of 2, and keep everything else the same, I would not get this error. I would get a successfully-run test message.

What the hell, AWS?  

Someone has pointed out that "Runtime: nodejs14.x" is hitting the end of its life soon. 
I haved tried nodejs18.x and nodejs16.x as well. They show the same error. 

### Observed result:

```
ubuntu@ip-111-31-16-16:~/MyApp/lambda/sam-app$ sam local invoke --event events/event.json
Invoking app.lambdaHandler (nodejs14.x)
Local image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-nodejs14.x
Building image..............................................................................................................................................................
Using local image: public.ecr.aws/lambda/nodejs:14-rapid-x86_64.

Mounting /home/ubuntu/MyApp/lambda/sam-app/hello-world as /var/task:ro,delegated, inside runtime container
START RequestId: 4a6ba3fe-f24c-4f10-9840-e66c2abafc50 Version: $LATEST
2023-04-10T18:13:12.492Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
10 Apr 2023 18:13:12,511 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
2023-04-10T18:13:12.641Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","stack":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
END RequestId: 2865c9f0-be40-47a2-b050-796ebd0aeaec

REPORT RequestId: 2865c9f0-be40-47a2-b050-796ebd0aeaec  Init Duration: 0.65 ms  Duration: 472.07 ms     Billed Duration: 473 ms Memory Size: 128 MB   Max Memory Used: 128 MB

{"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js","trace":["Runtime.ImportModuleError: Error: Cannot find module 'app'","Require stack:","- /var/runtime/UserFunction.js","- /var/runtime/Runtime.js","- /var/runtime/index.js","    at _loadUserApp (/var/runtime/UserFunction.js:225:13)","    at Object.module.exports.load (/var/runtime/UserFunction.js:300:17)","    at Object.<anonymous> (/var/runtime/index.js:43:34)","    at Module._compile (internal/modules/cjs/loader.js:1114:14)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)","    at Module.load (internal/modules/cjs/loader.js:979:32)","    at Function.Module._load (internal/modules/cjs/loader.js:819:12)","    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)","    at internal/main/run_main_module.js:17:47"]}
```

### Expected result:
Some successfully run test message

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Ubuntu 22.04.2 LTS
2. `sam --version`:  SAM CLI, version 1.79.0
3. AWS region:  ap-northeast-1 Tokyo

```
# Paste the output of `sam --info` here

{
  "version": "1.79.0",
  "system": {
    "python": "3.7.10",
    "os": "Linux-5.19.0-1022-aws-x86_64-with-debian-bookworm-sid"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.21",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

```

`Add --debug flag to command you are running`

**Comment by hnnasit** [comment]
Hi @DaCao, did you run `sam build` command before running `sam local invoke --event events/event.json`? `sam build`  transpiles the code from TypeScript to JavaScript using esbuild bundler. `sam local invoke` should work after running build and the following output can be expected:
```
{"statusCode":200,"body":"{\"message\":\"hello world\"}"}
```

**Comment by DaCao** [comment]
> Hi @DaCao, did you run `sam build` command before running `sam local invoke --event events/event.json`? `sam build` transpiles the code from TypeScript to JavaScript using esbuild bundler. `sam local invoke` should work after running build and the following output can be expected:
> 
> ```
> {"statusCode":200,"body":"{\"message\":\"hello world\"}"}
> ```

Thank you very much for the answer. I see why Javascript works directly without `sam build`.  For Typescript I need `sam build` to transpile the code from TypeScript to JavaScript.
