### ISSUE TITLE
Bug: Native AOT functions with .Net7 not building on Windows

### ISSUE THREAD

**Issue by branog68** [aws/aws-sam-cli#5011]
I wanted to build my native AOT lambda function with .net 7 on Windows 11, but I got the following error:
```
sam --debug build
2023-04-13 18:08:56,526 | Return available internal hook packages
Building codeuri: c:\Software\FreeFinanceInterface\src\FreeFinanceInterface runtime: provided.al2 metadata: {'BuildMethod': 'dotnet7'} architecture: x86_64 functions: FreeFinanceApiFunction
Running DotnetCliPackageBuilder:GlobalToolInstall

Tool 'amazon.lambda.tools' was reinstalled with the latest stable version (version '5.6.5').
Running DotnetCliPackageBuilder:RunPackageAction
Amazon Lambda Tools for .NET Core applications (5.6.5)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Architecture not provided, defaulting to x86_64 for container build image.
Executing publish command
Starting container for native AOT build using build image: public.ecr.aws/sam/build-dotnet7:latest-x86_64.
Unknown error executing command: Could not find a part of the path 'C:\tmp\source\src\FreeFinanceInterface'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Amazon.Common.DotNetCli.Tools.Utilities.FindProjectFileInDirectory(String directory) in C:\build\src\Amazon.Common.DotNetCli.Tools\Utilities.cs:line 266
   at Amazon.Common.DotNetCli.Tools.Utilities.HasExplicitSelfContainedFlag(String projectLocation, String msBuildParameters) in C:\build\src\Amazon.Common.DotNetCli.Tools\Utilities.cs:line 245
   at Amazon.Lambda.Tools.LambdaDotNetCLIWrapper.<>c__DisplayClass5_0.<GetPublishArguments>b__0() in C:\build\src\Amazon.Lambda.Tools\LambdaDotNetCLIWrapper.cs:line 321
   at Amazon.Lambda.Tools.LambdaDotNetCLIWrapper.GetPublishArguments(String projectLocation, String outputLocation, String targetFramework, String configuration, String msbuildParameters, String architecture, IList`1 publishManifests, Boolean isNativeAot) in C:\build\src\Amazon.Lambda.Tools\LambdaDotNetCLIWrapper.cs:line 350
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, String architecture, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, Boolean isNativeAot, Nullable`1 useContainerForBuild, String containerImageForBuild, String codeMountDirectory, String& publishLocation, String& zipArchivePath) in C:\build\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 82
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync() in C:\build\src\Amazon.Lambda.Tools\Commands\PackageCommand.cs:line 231
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\build\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 47

Build Failed
Error: DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed:
```

I assume an error in the container image public.ecr.aws/sam/build-dotnet7:latest-x86_64. 2 weeks ago, the build was running without any errors. I saw, a new container image was created on April, 7th. I didn't change any parameters or any configuration in my project since the last successful build.

1. OS: Windows 11
2. `sam --info`:
```
{
  "version": "1.79.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.22621-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.21",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}
```
4. AWS region: eu-west-1

I could reproduce the problem with the "HelloWorld"-Application too ([Building serverless .NET applications on AWS Lambda using .NET 7](https://aws.amazon.com/de/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/))

**Comment by branog68** [comment]
> dotnet lambda deploy-function

 is working. The problem happens in sam build. I don't have any path C:\tmp\source on my computer. I think, this is an error message from the container image.

**Comment by jfuss** [comment]
@branog68 hmm..

Can you describe how you have things setup? `sam build` only mounts the `CodeUri` directory, so I am thinking that `FreeFinanceInterface` is in a different directory that isn't getting mounted.

**Comment by branog68** [comment]
I'm starting 'sam build' from the directory, that contains the project. 'CodeUri' is in my template the current directory. 
But I could reproduce it with the sample project from [Building serverless .NET applications on AWS Lambda using .NET 7](https://aws.amazon.com/de/blogs/compute/building-serverless-net-applications-on-aws-lambda-using-net-7/) too. Here the output of 'sam --debug build'
```
2023-04-13 19:21:09,688 | Return available internal hook packages
Building codeuri: c:\Software\LambdaNativeAot\src\LambdaNativeAot runtime: provided.al2 metadata: {'BuildMethod': 'dotnet7'} architecture: x86_64 functions: HelloWorldFunction
Running DotnetCliPackageBuilder:GlobalToolInstall

Tool 'amazon.lambda.tools' was reinstalled with the latest stable version (version '5.6.5').
Running DotnetCliPackageBuilder:RunPackageAction
Amazon Lambda Tools for .NET Core applications (5.6.5)
Project Home: https://github.com/aws/aws-extensions-for-dotnet-cli, https://github.com/aws/aws-lambda-dotnet

Architecture not provided, defaulting to x86_64 for container build image.
Executing publish command
Starting container for native AOT build using build image: public.ecr.aws/sam/build-dotnet7:latest-x86_64.
Unknown error executing command: Could not find a part of the path 'C:\tmp\source'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Amazon.Common.DotNetCli.Tools.Utilities.FindProjectFileInDirectory(String directory) in C:\build\src\Amazon.Common.DotNetCli.Tools\Utilities.cs:line 266
   at Amazon.Common.DotNetCli.Tools.Utilities.HasExplicitSelfContainedFlag(String projectLocation, String msBuildParameters) in C:\build\src\Amazon.Common.DotNetCli.Tools\Utilities.cs:line 245
   at Amazon.Lambda.Tools.LambdaDotNetCLIWrapper.<>c__DisplayClass5_0.<GetPublishArguments>b__0() in C:\build\src\Amazon.Lambda.Tools\LambdaDotNetCLIWrapper.cs:line 321
   at Amazon.Lambda.Tools.LambdaDotNetCLIWrapper.GetPublishArguments(String projectLocation, String outputLocation, String targetFramework, String configuration, String msbuildParameters, String architecture, IList`1 publishManifests, Boolean isNativeAot) in C:\build\src\Amazon.Lambda.Tools\LambdaDotNetCLIWrapper.cs:line 350
   at Amazon.Lambda.Tools.LambdaPackager.CreateApplicationBundle(LambdaToolsDefaults defaults, IToolLogger logger, String workingDirectory, String projectLocation, String configuration, String targetFramework, String msbuildParameters, String architecture, Boolean disableVersionCheck, LayerPackageInfo layerPackageInfo, Boolean isNativeAot, Nullable`1 useContainerForBuild, String containerImageForBuild, String codeMountDirectory, String& publishLocation, String& zipArchivePath) in C:\build\src\Amazon.Lambda.Tools\LambdaPackager.cs:line 82
   at Amazon.Lambda.Tools.Commands.PackageCommand.PerformActionAsync() in C:\build\src\Amazon.Lambda.Tools\Commands\PackageCommand.cs:line 231
   at Amazon.Common.DotNetCli.Tools.Commands.BaseCommand`1.ExecuteAsync() in C:\build\src\Amazon.Common.DotNetCli.Tools\Commands\BaseCommand.cs:line 47

Build Failed
Error: DotnetCliPackageBuilder:RunPackageAction - Dotnet CLI Failed:
```
It seems to be the same error.

**Comment by jfuss** [comment]
@branog68 Got it. I don't see any issues on mac running `sam build --use-container`.

Does this still fail if you provide `--use-container`?

The difference I see is relates to the following, which was run on my machine.
```
Tool 'amazon.lambda.tools' (version '5.6.5') was successfully installed.
Running DotnetCliPackageBuilder:RunPackageAction
Amazon Lambda Tools for .NET Core applications (5.6.4)
```
It looks like the build might have been with 5.6.4.

**Comment by branog68** [comment]
Hi @jfuss, thank you for the advice. If I use the option `--use-container`, I don't get `the error`. (I get another error because I'm using a reference to another project, but this could be solved.) But the sense of this project is, to run a native code on AWS, not in a container. Therefore, it should be deployed as a zip. 
Can you build your project without the option `--use-container`?
Regarding the different versions, I see the same message as you.

**Comment by branog68** [comment]
Sorry, this was a problem with my windows-configuration. Now it works.
