### ISSUE TITLE
sam 1.80 authorizer support doesn't work then the authorizer is defined with a FunctionArn

### ISSUE THREAD

**Issue by ylilarry** [aws/aws-sam-cli#5037]
### Description:

The new `sam local start-api` authorizer support works only if the authorizer function is defined in the same template. It breaks if the function is defined by a FunctionArn.

For example:

      Auth: # Uses the UserAppTokenAuthorizer to identify the session user.
        ApiKeyRequired: false
        DefaultAuthorizer: UserAppTokenAuthorizer
        Authorizers:
          UserAppTokenAuthorizer:
            FunctionPayloadType: REQUEST
            FunctionArn: arn:aws:lambda:us-east-1:887279901853:function:UserAppTokenAuthorizer
            Identity:
              ReauthorizeEvery: 300
              Headers: ["X-FAST-API-KEY"] # This is important

Breaks with an error saying `SAM: UserAppTokenAuthorizer not found`.
    
        Traceback (most recent call last):
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
            response = self.full_dispatch_request()
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
            rv = self.handle_user_exception(e)
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
            rv = self.dispatch_request()
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
            return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/samcli/local/apigw/local_apigw_service.py", line 675, in _request_handler
            self._invoke_parse_lambda_authorizer(lambda_authorizer, auth_lambda_event, route_lambda_event, route)
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/samcli/local/apigw/local_apigw_service.py", line 745, in _invoke_parse_lambda_authorizer
            lambda_auth_response = self._invoke_lambda_function(lambda_authorizer.lambda_name, auth_lambda_event)
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/samcli/local/apigw/local_apigw_service.py", line 610, in _invoke_lambda_function
            self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer, stderr=self.stderr)
          File "/Users/yu/lab/FastchargeAPI/.venv/lib/python3.9/site-packages/samcli/commands/local/lib/local_lambda.py", line 121, in invoke
            raise FunctionNotFound("Unable to find a Function with name '{}'".format(function_identifier))
        samcli.local.lambdafn.exceptions.FunctionNotFound: Unable to find a Function with name 'UserAppTokenAuthorizer'

Note that using a custom Identity header is important for reproducing the error. Without that, you will get HTTP 401 instead of HTTP 502,

### Workaround

Downgrade to sam 1.79 solved the problem

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
    
    {
      "version": "1.80.0",
      "system": {
        "python": "3.9.16",
        "os": "macOS-13.2.1-arm64-arm-64bit"
      },
      "additional_dependencies": {
        "docker_engine": "20.10.24",
        "aws_cdk": "Not available",
        "terraform": "Not available"
      }
    }

**Comment by lucashuy** [comment]
Thanks for reporting this. Since this is within the context of local testing (`sam local start-api`), functions that are deployed remotely shouldn't be considered for invocation so this makes sense to handle gracefully.

**Comment by lucashuy** [comment]
Thanks for suggesting that idea, we can create a fix so that the authorizer won't fail with a stack trace if it references a deployed Lambda function (since local testing is suppose to be done locally) for now. We can also take other other half in as a request for an option to turn on or off this behaviour.

**Comment by mndeveci** [comment]
Fix is released with [SAM CLI v1.81.0 version](https://github.com/aws/aws-sam-cli/releases/tag/v1.81.0), resolving this issue
