### ISSUE TITLE
Bug: sam build doesn't work with python packages installed with git+https url.

### ISSUE THREAD

**Issue by mbtx2** [aws/aws-sam-cli#5122]
### Description:
When using a url to install a python package via a git+https url, sam build fails.

For instance, if you have this in your requirements.txt file:

`a_package @ git+https://a_git_api_key@github.com/a_repo_name/a_repo_name.git@main#egg=a_package[an_extra]&subdirectory=a_subdir`

sam build fails, although pip is able to install this requirements.txt file without error, so this is a fully-supported pip install string.  Have tried with @main, @a_tag, etc., doesn't work.

Error:

```
Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Unable to retrieve name/version for package: a_package
```

### Steps to reproduce:
In a Lambda project, put a git+https package url in the requirements.txt file.  run sam build.  You will get the error:

```Running PythonPipBuilder:ResolveDependencies

Build Failed
Error: PythonPipBuilder:ResolveDependencies - Unable to retrieve name/version for package: a_package```


### Observed result:

`2023-05-07 16:03:27,826 | PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "aws_lambda_builders/workflow.py", line 369, in run
  File "aws_lambda_builders/workflows/python_pip/actions.py", line 54, in execute
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 156, in build_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 256, in build_site_packages
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 280, in _download_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 363, in _download_all_dependencies
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 363, in <setcomp>
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 512, in __init__
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 554, in _calculate_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 625, in get_package_name_and_version
  File "aws_lambda_builders/workflows/python_pip/packager.py", line 608, in _get_pkg_info_filepath
aws_lambda_builders.workflows.python_pip.packager.UnsupportedPackageError: Unable to retrieve name/version for package: a_package

Build Failed`



### Expected result:
Should be able to install git+https package without error.  If pip can install it, sam should also be able to.



### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

{
  "version": "1.80.0",
  "system": {
    "python": "3.7.10",
    "os": "Linux-5.15.0-70-generic-x86_64-with-debian-bookworm-sid"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.18",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

**Comment by hnnasit** [comment]
Hi @mbtx2, thanks for opening the issue. Moving this issue to lambda builders repository. We will investigate it further.
