### ISSUE TITLE
Bug: esbuild looks for binary before `npm install` requiring esbuild to be globally installed instead of being a dependency.

### ISSUE THREAD

**Issue by SebBrookfield** [aws/aws-sam-cli#5147]
### Description:
When running a sam build which uses esbuild, the binary is attempted to be located before the local packages.json install.
This which means esbuild needs to be installed globally and fails if it's only installed as a package.json dependency.

SAM tries to find the esbuild binary in the method _get_esbuild_subprocess which runs `npm root` to locate the npm bin path.
This runs before `npm install`, so the command is run against an empty scratch directory, causing the npm bin path to be the global node_modules.
Ideally, it should search for the esbuild binary after `npm install`, and if it cannot find the esbuild binary, it should use the global flag `npm root -g` and search for esbuild there.

The following bug is related, but not the same.
https://github.com/aws/aws-sam-cli/issues/4183

### Steps to reproduce:
1) Ensure you've removed esbuild globally. `npm uninstall -g esbuild`
2) SAM init the hello-world-typescript template. `sam init --runtime nodejs18.x --dependency-manager npm --app-template hello-world-typescript`
3) Run `sam build`
4) Observe "Esbuild Failed: Cannot find esbuild."

### Observed result:
2023-05-10 15:37:11,340 | Config file location: C:\Development\Playgrounds\sam-app\samconfig.toml
2023-05-10 15:37:11,341 | Loading configuration values from [default.['build'].parameters] (env.command_name.section) in config file at 'C:\Development\Playgrounds\sam-app\samconfig.toml'...
2023-05-10 15:37:11,344 | Configuration values successfully loaded.
2023-05-10 15:37:11,345 | Configuration values are: {'stack_name': 'sam-app', 'cached': True, 'parallel': True}
2023-05-10 15:37:11,348 | Using SAM Template at C:\Development\Playgrounds\sam-app\template.yaml
2023-05-10 15:37:11,407 | Using config file: samconfig.toml, config environment: default
2023-05-10 15:37:11,407 | Expand command line arguments to:
2023-05-10 15:37:11,408 | --template_file=C:\Development\Playgrounds\sam-app\template.yaml --parallel --build_dir=.aws-sam\build --cache_dir=.aws-sam\cache --cached
2023-05-10 15:37:11,836 | 'build' command is called
2023-05-10 15:37:11,836 | Starting Build use cache
2023-05-10 15:37:11,839 | No Parameters detected in the template
2023-05-10 15:37:11,855 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-05-10 15:37:11,855 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-05-10 15:37:11,856 | 0 stacks found in the template
2023-05-10 15:37:11,856 | No Parameters detected in the template
2023-05-10 15:37:11,866 | There is no customer defined id or cdk path defined for resource HelloWorldFunction, so we will use the resource logical id as the resource id
2023-05-10 15:37:11,866 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-05-10 15:37:11,867 | 2 resources found in the stack
2023-05-10 15:37:11,867 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2023-05-10 15:37:11,867 | --base-dir is not presented, adjusting uri hello-world/ relative to C:\Development\Playgrounds\sam-app\template.yaml
2023-05-10 15:37:11,870 | 2 resources found in the stack
2023-05-10 15:37:11,871 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2023-05-10 15:37:11,871 | Found Serverless function with name='HelloWorldFunction' and CodeUri='hello-world/'
2023-05-10 15:37:11,871 | --base-dir is not presented, adjusting uri hello-world/ relative to C:\Development\Playgrounds\sam-app\template.yaml
2023-05-10 15:37:11,873 | Instantiating build definitions
2023-05-10 15:37:11,876 | Same function build definition found, adding function (Previous: BuildDefinition(nodejs18.x, C:\Development\Playgrounds\sam-app\hello-world, Zip, , 8277d8ca-a61c-4b38-8dc4-22ba103bd6ca, {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}}, {}, x86_64, []), Current: BuildDefinition(nodejs18.x, C:\Development\Playgrounds\sam-app\hello-world, Zip, , 7db4b072-628f-4fa6-9407-6f0a70d2f3a3, {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}}, {}, x86_64, []), Function: Function(function_id='HelloWorldFunction', name='HelloWorldFunction', functionname='HelloWorldFunction', runtime='nodejs18.x', memory=None, timeout=3, handler='app.lambdaHandler', imageuri=None, packagetype='Zip', imageconfig=None, codeuri='C:\\Development\\Playgrounds\\sam-app\\hello-world', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api', 'Properties': {'Path': '/hello', 'Method': 'get', 'RestApiId': 'ServerlessRestApi'}}}, metadata={'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}, 'SamResourceId': 'HelloWorldFunction'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, stack_path='', runtime_management_config=None))
2023-05-10 15:37:11,878 | Async execution started
2023-05-10 15:37:11,878 | Invoking function functools.partial(<bound method ParallelBuildStrategy.build_single_function_definition of <samcli.lib.build.build_strategy.ParallelBuildStrategy object at 0x00000137B7E5F070>>, <samcli.lib.build.build_graph.FunctionBuildDefinition object at 0x00000137B7E801F0>)
2023-05-10 15:37:11,880 | Running incremental build for runtime nodejs18.x for following resources (HelloWorldFunction)
2023-05-10 15:37:11,880 | Waiting for async results
2023-05-10 15:37:11,881 | Manifest file is changed (new hash: 77b01a75144f046a870865bfc2f12ea5) or dependency folder (.aws-sam\deps\8277d8ca-a61c-4b38-8dc4-22ba103bd6ca) is missing for (HelloWorldFunction), downloading dependencies and copying/building source
2023-05-10 15:37:11,882 | Building codeuri: C:\Development\Playgrounds\sam-app\hello-world runtime: nodejs18.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}} architecture: x86_64 functions: HelloWorldFunction
2023-05-10 15:37:11,882 | Building to following folder C:\Development\Playgrounds\sam-app\.aws-sam\build\HelloWorldFunction
2023-05-10 15:37:11,884 | Loading workflow module 'aws_lambda_builders.workflows'
2023-05-10 15:37:11,887 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-05-10 15:37:11,891 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-05-10 15:37:11,895 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-05-10 15:37:11,901 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-05-10 15:37:11,904 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-05-10 15:37:11,906 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-05-10 15:37:11,908 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-05-10 15:37:11,911 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-05-10 15:37:11,913 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-05-10 15:37:11,915 | Registering workflow 'RustCargoLambdaBuilder' with capability 'Capability(language='rust', dependency_manager='cargo', application_framework=None)'
2023-05-10 15:37:11,916 | Found workflow 'NodejsNpmEsbuildBuilder' to support capabilities 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-05-10 15:37:11,917 | executing NPM: ['npm.cmd', 'root']
2023-05-10 15:37:13,105 | Lambda Builders found the following esbuild properties:
{"minify": true, "target": "es2020", "sourcemap": true, "entry_points": ["app.ts"]}
2023-05-10 15:37:13,119 | Running workflow 'NodejsNpmEsbuildBuilder'
2023-05-10 15:37:13,119 | Running NodejsNpmEsbuildBuilder:CopySource
2023-05-10 15:37:13,120 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\.eslintignore) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\.eslintignore)
2023-05-10 15:37:13,121 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\.eslintrc.js) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\.eslintrc.js)
2023-05-10 15:37:13,123 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\.npmignore) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\.npmignore)
2023-05-10 15:37:13,125 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\.prettierrc.js) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\.prettierrc.js)
2023-05-10 15:37:13,126 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\app.ts) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\app.ts)
2023-05-10 15:37:13,127 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\jest.config.ts) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\jest.config.ts)
2023-05-10 15:37:13,129 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\package.json) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\package.json)
2023-05-10 15:37:13,130 | Creating target folders at C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tests
2023-05-10 15:37:13,130 | Copying directory metadata from source (C:\Development\Playgrounds\sam-app\hello-world\tests) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tests)
2023-05-10 15:37:13,131 | Creating target folders at C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tests\unit
2023-05-10 15:37:13,131 | Copying directory metadata from source (C:\Development\Playgrounds\sam-app\hello-world\tests\unit) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tests\unit)
2023-05-10 15:37:13,132 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\tests\unit\test-handler.test.ts) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tests\unit\test-handler.test.ts)
2023-05-10 15:37:13,133 | Copying source file (C:\Development\Playgrounds\sam-app\hello-world\tsconfig.json) to destination (C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\tsconfig.json)
2023-05-10 15:37:13,136 | NodejsNpmEsbuildBuilder:CopySource succeeded
2023-05-10 15:37:13,136 | Running NodejsNpmEsbuildBuilder:NpmInstall
2023-05-10 15:37:13,136 | NODEJS installing in: C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5
2023-05-10 15:37:13,136 | executing NPM: ['npm.cmd', 'install', '-q', '--no-audit', '--no-save', '--unsafe-perm', '--production']
2023-05-10 15:37:17,345 | NodejsNpmEsbuildBuilder:NpmInstall succeeded
2023-05-10 15:37:17,345 | Running NodejsNpmEsbuildBuilder:EsbuildBundle
2023-05-10 15:37:17,347 | NODEJS building ['C:\\Users\\sbrooks\\AppData\\Local\\Temp\\tmpvt0dbp_5\\app.ts'] using esbuild to C:\Development\Playgrounds\sam-app\.aws-sam\build\HelloWorldFunction
2023-05-10 15:37:17,348 | Using the following default args: ['--bundle', '--platform=node', '--outdir=C:\\Development\\Playgrounds\\sam-app\\.aws-sam\\build\\HelloWorldFunction', '--format=cjs']
2023-05-10 15:37:17,349 | Found the following args in the config: ['--minify', '--sourcemap', '--target=es2020']
2023-05-10 15:37:17,349 | checking for esbuild in: ['C:\\Users\\sbrooks\\node_modules\\.bin']
2023-05-10 15:37:17,357 | potential esbuild binaries: []
2023-05-10 15:37:17,357 | NodejsNpmEsbuildBuilder:EsbuildBundle failed
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm_esbuild\actions.py", line 98, in execute
    self._subprocess_esbuild.run(args, cwd=self._working_directory)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm_esbuild\esbuild.py", line 89, in run
    invoke_esbuild = [self.esbuild_binary()] + args
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm_esbuild\esbuild.py", line 56, in esbuild_binary
    raise EsbuildExecutionError(
aws_lambda_builders.workflows.nodejs_npm_esbuild.exceptions.EsbuildExecutionError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 370, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\nodejs_npm_esbuild\actions.py", line 100, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.
2023-05-10 15:37:17,375 | Exception raised during the execution
2023-05-10 15:37:17,376 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-05-10 15:37:17,555 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-05-10 15:37:17,555 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '24400c45-438c-435d-8c58-cfbefe73feee', 'installationId': 'f346919b-0e3a-454e-9546-ba65303458b9', 'sessionId': '7cab9785-cfa0-41f5-8211-1e1cf3830062', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.76.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': '593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3', 'initialCommit': None}, 'duration': 5969, 'exitReason': 'WorkflowFailedError', 'exitCode': 1}}]}
2023-05-10 15:37:17,555 | Unable to find Click Context for getting session_id.
2023-05-10 15:37:17,557 | Sending Telemetry: {'metrics': [{'events': {'requestId': '981acd81-a7de-4be2-8e41-197a3a873e52', 'installationId': 'f346919b-0e3a-454e-9546-ba65303458b9', 'sessionId': '7cab9785-cfa0-41f5-8211-1e1cf3830062', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.76.0', 'metricSpecificAttributes': {'events': [{'event_name': 'BuildFunctionRuntime', 'event_value': 'nodejs18.x', 'thread_id': 31552, 'time_stamp': '2023-05-10 14:37:11.872'}, {'event_name': 'BuildWorkflowUsed', 'event_value': 'nodejs-npm', 'thread_id': 31552, 'time_stamp': '2023-05-10 14:37:11.881'}, {'event_name': 'BuildWorkflowUsed', 'event_value': 'nodejs-npm-esbuild', 'thread_id': 31552, 'time_stamp': '2023-05-10 14:37:11.882'}]}}}]}
2023-05-10 15:37:18,062 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
2023-05-10 15:37:18,156 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: Cannot find esbuild. esbuild must be installed on the host machine to use this feature. It is recommended to be installed on the PATH, but can also be included as a project dependency.

### Expected result:
Build succeeded.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

{
  "version": "1.82.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  }
}

**Comment by mndeveci** [comment]
Hi there,

I've tried to verify the issue by running the steps that you provided. I've confirmed that I don't have `esbuild` available in the path by running `which esbuild`. And ran `sam build` afterwards. As you can see below, it is succeeded;
```
╭─ /tmp/test-esbuild/sam-app                                                                                                                                                                                                          Node 18.15.0 11:08:03 am
╰─❯ which esbuild
esbuild not found
╭─ /tmp/test-esbuild/sam-app                                                                                                                                                                                                          Node 18.15.0 11:08:06 am
╰─❯ sam build
Building codeuri: /private/tmp/test-esbuild/sam-app/hello-world runtime: nodejs18.x metadata: {'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2020', 'Sourcemap': True, 'EntryPoints': ['app.ts']}} architecture: x86_64 functions: HelloWorldFunction
Running NodejsNpmEsbuildBuilder:CopySource
Running NodejsNpmEsbuildBuilder:NpmInstall
Running NodejsNpmEsbuildBuilder:EsbuildBundle

Sourcemap set without --enable-source-maps, adding --enable-source-maps to function HelloWorldFunction NODE_OPTIONS

You are using source maps, note that this comes with a performance hit! Set Sourcemap to false and remove NODE_OPTIONS: --enable-source-maps to disable source maps.


Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Validate SAM template: sam validate
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {{stack-name}} --watch
[*] Deploy: sam deploy --guided
```

I will try to re-produce this on Windows, in the meantime please let me know if you have more details.

**Comment by SebBrookfield** [comment]
Hi mndeveci,

If you do a debug build, where does it suggest its getting the esbuild binary from?
I'm getting `checking for esbuild in: ['C:\\Users\\sbrooks\\node_modules\\.bin']`
Since the scratch directory is `C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5`, it should be looking at `C:\Users\sbrooks\AppData\Local\Temp\tmpvt0dbp_5\node_modules\.bin` if it was using the esbuild from the npm install.

**Comment by hnnasit** [comment]
Closing this issue as this cannot be reproduced and this has been inactive for a while. Feel free to open a new issue if you still have any questions/concerns.
