### ISSUE TITLE
PythonPipBuilder:ResolveDependencies 'utf-8' issue in sam build with python 3.10

### ISSUE THREAD

**Issue by blookot** [aws/aws-sam-cli#5259]
Hi,

I've created a project with sam init, populated my python files, and everything works (build & deploy) when using python 3.8 or python 3.9.13, but when using python 3.10.11, I'm getting this error:

```PythonPipBuilder:ResolveDependencies - 'utf-8' codec can't decode byte 0xe9 in position 67: invalid continuation byte```

(I checked my requirements.txt file is properly utf-8 encoded)
I suppose there is a "regression"? using python 3.10 template maybe?
Dumping here the whole debug log of sam build:

```
2023-06-05 12:18:08,654 | Running PythonPipBuilder:ResolveDependencies
2023-06-05 12:18:08,736 | calling pip download -r C:\Users\xxx\requirements.txt --dest C:\Users\yyy\AppData\Local\Temp\tmpystx6_3f --exists-action i
2023-06-05 12:18:12,265 | PythonPipBuilder:ResolveDependencies raised unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflow.py", line 369, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\actions.py", line 51, in execute
    package_builder.build_dependencies(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 156, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path, artifacts_dir_path, scratch_dir_path)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 256, in build_site_packages
    wheels, packages_without_wheels = self._download_dependencies(scratch_directory, requirements_filepath)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 280, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 362, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\aws_lambda_builders\workflows\python_pip\packager.py", line 719, in download_all_dependencies
    stdout = out.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 67: invalid continuation byte
2023-06-05 12:18:12,296 | Exception raised during the execution
```

**Comment by blookot** [comment]
Hi @jfuss 
obviously I'm running on Windows ;-) Windows 10 pro 64bits.

I started from the hello world sample (from sam init) and changed the app.py with just one module import (twilio).
I did a `pip install twilio` 

ok, while writing this, I found the issue & workaround, although it doesn't work 100% of the time. Quite strange...

The `pip freeze > requirements.txt` that was working in python 3.8 doesn't work anymore in 3.9 & 3.10, because (msot likely) the output file is encoded in "UTF-16 with BOM". 
So I deleted the requirements file, changed the command to `pip freeze | Out-File -Encoding UTF8 requirements.txt` and now the sam build works!

**Comment by jfuss** [comment]
@blookot Is this closable then? Hard to tell if there is action on us anymore.

**Comment by blookot** [comment]
Well... I guess we can, although I'm still seeing unpredictable behavior around this...

**Comment by chokecoDev** [comment]
Hi, ensure that the path to your project does not contain accented characters (á, é, í, ó, ú), or other unusual characters.
I had a character Í in the path, and after removing it, the command executed successfully.
