### ISSUE TITLE
Getting "SAM CLI has an invalid version" error when trying to debug a lambda in Visual Studio Code using the SAM CLI

### ISSUE THREAD

**Issue by paultipper** [aws/aws-sam-cli#5340]
### Description:
I'm getting a "SamLaunchRequestError: SAM CLI has an invalid version [InvalidSamCliVersion]" when trying to launch an aws-sam/direct-invoke debug configuration in Visual Studio Code. I'm running on a MacBook Pro running MacOs 13.4 (Ventura).

### Steps to reproduce:

1. Install Visual Studio Code
2. Install the latest version of the AWS Toolkit
3. Install the latest version of the SAM CLI (I installed version 1,.86.1 using the brew utility).
4. Create the following debug configuration in the .vscode/launch.json file (adapt as required):

`{
            "type": "aws-sam",
            "request": "direct-invoke",
            "name": "SAM debugger test",
            "invokeTarget": {
                "target": "code",
                "projectRoot": "${workspaceFolder}/api/lambdas",
                "lambdaHandler": "yourlambda.handler"
            },
            "lambda": {
                "runtime": "python3.8",
                "payload": {},
                "environmentVariables": {}
            }
}`

5. Go into the debug page and launch the "SAM debugger test" configuration. 

### Observed result:
After about 30 seconds, a pop-up error message will be displayed with the following error:

Your SAM CLI version does not meet requirements (0.47.0\xA0\u2264\xA0version\xA0<\xA02.0.0). Update your SAM CLI.

The AWS Toolkit logs will show something like this:

`...
2023-06-12 11:07:14 [INFO]: SAM CLI location (from settings): /usr/local/bin/sam
2023-06-12 11:08:16 [ERROR]: SamLaunchRequestError: SAM CLI has an invalid version [InvalidSamCliVersion]
2023-06-12 11:11:34 [INFO]: telemetry: sent batch (size=10)
2023-06-12 11:17:02 [WARN]: SAM debug: missing AWS credentials (Toolkit is not connected)
2023-06-12 11:18:02 [ERROR]: SamLaunchRequestError: SAM CLI has an invalid version [InvalidSamCliVersion]
2023-06-12 11:21:35 [INFO]: telemetry: sent batch (size=1)
2023-06-12 11:26:35 [INFO]: telemetry: sent batch (size=2)
`

### Expected result:
The debug session should be launched successfully within Visual Studio Code

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: MacOs 13.4 (22F66)
6. `sam --version`: 1.86.1
7. AWS region: us-east-1

# Paste the output of `sam --info` here
```
11:33 $ sam --info
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 461, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python@3.8/3.8.17/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1348, in getresponse
    response.begin()
  File "/usr/local/Cellar/python@3.8/3.8.17/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python@3.8/3.8.17/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python@3.8/3.8.17/Frameworks/Python.framework/Versions/3.8/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/packages/six.py", line 770, in reraise
    raise value
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/Cellar/aws-sam-cli/1.86.1/libexec/lib/python3.8/site-packages/urllib3/connectionpool.py", line 357, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)

```
I was able to debug Lambda functions in Visual Studio Code successfully as recently as last Friday, but it's broken now.

**Comment by justinmk3** [comment]
Can you confirm what `/usr/local/bin/sam --version` (not `sam --version`) shows?

The `sam --info` exception may be related to the docker version. Can you post the result of:

    docker --version

**Comment by mildaniel** [comment]
As @justinmk3 mentioned, it would be helpful knowing the version of Docker you are currently using.

**Comment by mndeveci** [comment]
Hey @paultipper 

We had some issues related to docker integration recently. They should be resolved by now, can you re-try the issue and see if it is fixed by now?

Thanks!

**Comment by mndeveci** [comment]
Resolving this due to inactivity, feel free to comment or create a new issue if you are still experiencing this problem.

**Comment by tungduonglx** [comment]
Upgrading to docker engine  24.0.6 works for me
