### ISSUE TITLE
Bug: sam build - FileNotFoundError

### ISSUE THREAD

**Issue by JonathanGladwin** [aws/aws-sam-cli#5451]
Hello,

I have a spring boot service and i want to deploy to AWS Lambda via SAM template. I am following this link and i get below error, i couldn't find the fix, could you please help?

https://www.baeldung.com/spring-boot-aws-lambda

template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30

Resources:
  ProfileApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.example.awstest.handler.AWSLambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: GET
```
Error:

```
PS C:\codebase\AWSTest> sam build
Building codeuri: C:\codebase\AWSTest runtime: java17 metadata: {} architecture: x86_64 functions: ProfileApiFunction
Running JavaGradleWorkflow:GradleBuild
Running JavaGradleWorkflow:JavaGradleCopyArtifacts

Error: [WinError 3] The system cannot find the path specified: 'C:\\Users\\priya\\AppData\\Local\\Temp\\tmpsolhkr39\\07230cecfa8b4e4ba160938c8f44c28909e51e57\\build\\distributions\\lambda-build\\com\\amazonaws\\services\\lambda\\runtime\\events\\CognitoUserPoolPreTokenGenerationEvent$ClaimsOverrideDetails$ClaimsOverrideDetailsBuilder.class'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 179, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 275, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 281, in run
    self._build_result = builder.build()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 215, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 81, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 91, in _build_functions
    function_build_results.update(self.build_single_function_definition(build_definition))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 164, in build_single_function_definition
    result = self._build_function(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 702, in _build_function
    return self._build_function_in_process(
  File "contextlib.py", line 131, in __exit__
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\osutils.py", line 55, in mkdir_temp
    shutil.rmtree(temp_dir)
  File "shutil.py", line 740, in rmtree
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  File "shutil.py", line 613, in _rmtree_unsafe
  [Previous line repeated 7 more times]
  File "shutil.py", line 618, in _rmtree_unsafe
  File "shutil.py", line 616, in _rmtree_unsafe

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20FileNotFoundError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20FileNotFoundError
PS C:\codebase\AWSTest>
```

Entire Github project has uploaded here:
https://github.com/JonathanGladwin/awstest

**Comment by mndeveci** [comment]
Thanks for raising this issue.

I've tried your example on MacOS and I was able to build the application. Looking at the error, it might be coming from the Window's path limitation (default might be 256 chars). See this Microsoft page for details: https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry

Can you try to apply their recommendation to increase the maximum path and re-try building your application?

**Comment by JonathanGladwin** [comment]
Hi, Thank you! I am running into another issue. I did, "sam build" and then i tried to run locally using "sam local start-api", and it is running on "http://127.0.0.1:3000". Then I tried, to reach to the end point in Postman, giving http://127.0.0.1:3000/searchAll, it keeps trying to get me response, but finally observed below "Gateway timeout" error:

  ```
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:185) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]

2023-07-06T04:05:03.338Z ERROR 14 --- [           main] c.a.s.proxy.AwsProxyExceptionHandler     : Called exception handler for:

com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 20000ms timeout
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:210) ~[task/:na]
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257) ~[task/:na]
        at com.example.awstest.handler.AWSLambdaHandler.handleRequest(AWSLambdaHandler.java:36) ~[task/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:903) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:238) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:185) ~[aws-lambda-java-runtime-interface-client-2.3.1-SNAPSHOT.jar:2.3.1-SNAPSHOT]

com.amazonaws.serverless.exceptions.ContainerInitializationException: Could not initialize framework within the 20000ms timeout
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxy(LambdaContainerHandler.java:210)
        at com.amazonaws.serverless.proxy.internal.LambdaContainerHandler.proxyStream(LambdaContainerHandler.java:257)
        at com.example.awstest.handler.AWSLambdaHandler.handleRequest(AWSLambdaHandler.java:36)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$StreamMethodRequestHandler.handleRequest(EventHandlerLoader.java:379)
        at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:903)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:238)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:190)
        at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:185)
END RequestId: 3cd7bff4-fff8-4373-b5ac-4913b0a55c76
REPORT RequestId: 3cd7bff4-fff8-4373-b5ac-4913b0a55c76  Init Duration: 0.10 ms   Duration: 33313.85 ms   Billed Duration: 33314 mMemory Size: 2048 MB     Max Memory Used: 2048 MB
2023-07-05 23:05:04 127.0.0.1 - - [05/Jul/2023 23:05:04] "GET /searchAll HTTP/1.1" 502 -
```

**Comment by JonathanGladwin** [comment]
This error got fixed "SAM BUILD - Error: [WinError 3] The system cannot find the path specified".
I enabled HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled

**Comment by JonathanGladwin** [comment]
Thank you so much!

**Comment by marchmikej** [comment]
I had the same issue and this fixed for me to.  Thank you!!!

**Comment by mndeveci** [comment]
Glad that it worked for you, resolving this issue now

**Comment by UnfabledX** [comment]
@dnarwade1991 I had the same issue.. and I don't know how to fix it
