### ISSUE TITLE
Bug: sam local invoke - TypeError ( Error: request() got an unexpected keyword argument 'chunked' )

### ISSUE THREAD

**Issue by rohilpinto** [aws/aws-sam-cli#5457]
### Description:

Hi I'm new to Sam & I'm facing an issue. I created a hello world template using sam init python3.9 as runtime. After executing sam build I do sam local invoke HelloWorldFunction which throws an error **Error: request() got an unexpected keyword argument 'chunked'**. I have docker installed and it is running in the bg

### Steps to reproduce:

sam init ( helloWorld template & lastest python runtime ) 
sam build
sam local invoke HelloWorldFunction

### Observed result:

PS H:\allmycode\aws-sam\aws-mysql-test\rds-test> sam local invoke HelloWorldFunction --debug        
2023-07-06 19:19:16,696 | Config file location: H:\allmycode\aws-sam\aws-mysql-test\rds-test\samconfig.toml
2023-07-06 19:19:16,700 | Loading configuration values from [default.['local', 'invoke'].parameters] (env.command_name.section) in config file at
'H:\allmycode\aws-sam\aws-mysql-test\rds-test\samconfig.toml'...
2023-07-06 19:19:16,706 | Configuration values successfully loaded.
2023-07-06 19:19:16,707 | Configuration values are: {'stack_name': 'rds-test'}
2023-07-06 19:19:16,714 | Using SAM Template at H:\allmycode\aws-sam\aws-mysql-test\rds-test\.aws-sam\build\template.yaml
2023-07-06 19:19:16,738 | Using config file: samconfig.toml, config environment: default
2023-07-06 19:19:16,740 | Expand command line arguments to:
2023-07-06 19:19:16,742 | --template_file=H:\allmycode\aws-sam\aws-mysql-test\rds-test\.aws-sam\build\template.yaml --function_logical_id=HelloWorldFunction --no_event
--layer_cache_basedir=C:\Users\Rohil\AppData\Roaming\AWS SAM\layers-pkg --container_host=localhost --container_host_interface=127.0.0.1
2023-07-06 19:19:16,746 | local invoke command is called
2023-07-06 19:19:16,752 | No Parameters detected in the template
2023-07-06 19:19:16,779 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2023-07-06 19:19:16,782 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-07-06 19:19:16,784 | 0 stacks found in the template
2023-07-06 19:19:16,787 | No Parameters detected in the template
2023-07-06 19:19:16,809 | Sam customer defined id is more priority than other IDs. Customer defined id for resource HelloWorldFunction is HelloWorldFunction
2023-07-06 19:19:16,812 | There is no customer defined id or cdk path defined for resource ServerlessRestApi, so we will use the resource logical id as the resource id
2023-07-06 19:19:16,816 | 2 resources found in the stack
2023-07-06 19:19:16,818 | Found Serverless function with name='HelloWorldFunction' and CodeUri='HelloWorldFunction'
2023-07-06 19:19:16,820 | --base-dir is not presented, adjusting uri HelloWorldFunction relative to H:\allmycode\aws-sam\aws-mysql-test\rds-test\.aws-sam\build\template.yaml
2023-07-06 19:19:16,831 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-07-06 19:19:16,989 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': '61ab1086-37ce-48dd-a0ea-28fbe5a66d83', 'installationId': '73310f42-9ab4-40e5-bbef-882c9867c614', 'sessionId':    
'73825e9f-90a8-4399-9dcc-86b5cd7e3dcd', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.8.8', 'samcliVersion': '1.86.1', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region':   
'', 'commandName': 'sam local invoke', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin': None, 'projectName': 'd18dc0263c7ee7f2d71b0b2ec4ebb67d58c29959caed602042d043c1a8dc2e2a',
'initialCommit': None}, 'duration': 93, 'exitReason': 'TypeError', 'exitCode': 255}}]}
2023-07-06 19:19:17,687 | HTTPSConnectionPool(host='aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443): Read timed out. (read timeout=0.1)

Error: request() got an unexpected keyword argument 'chunked'
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 100, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\invoke\cli.py", line 183, in do_cli
    with InvokeContext(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\local\cli_common\invoke_context.py", line 265, in __enter__
    if not self._container_manager.is_docker_reachable:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\manager.py", line 54, in is_docker_reachable
    return utils.is_docker_reachable(self.docker_client)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\utils.py", line 90, in is_docker_reachable
    docker_client.ping()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(

An unexpected error was encountered while executing "sam local invoke".

### Expected result:

I want it to work similar to the video i have linked below which i'm usign to learn sam
 https://www.youtube.com/watch?v=5HvEeAtmiHI&t=227s

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)
Processor	Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz   3.40 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

1. OS: Windows 10 64 bit
2. `sam --version`: SAM CLI, version 1.86.1
3. AWS region:

```
# Paste the output of `sam --info` here
PS H:\allmycode\aws-sam\aws-mysql-test\rds-test> sam --info
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1054, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1613, in parse_args
    rest = super().parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 58, in print_info
    "additional_dependencies": gather_additional_dependencies_info(),
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 37, in gather_additional_dependencies_info
    "docker_engine": _gather_docker_info(),
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\system_info.py", line 60, in _gather_docker_info
    if is_docker_reachable(client):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\utils.py", line 90, in is_docker_reachable
    docker_client.ping()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\client.py", line 187, in ping
    return self.api.ping(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\daemon.py", line 166, in ping
    return self._result(self._get(self._url('/_ping'))) == 'OK'
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\docker\api\client.py", line 230, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\urllib3\connectionpool.py", line 496, in _make_request
    conn.request(
TypeError: request() got an unexpected keyword argument 'chunked'
```

`Add --debug flag to command you are running`

**Comment by rohilpinto** [comment]
https://stackoverflow.com/questions/76630314/sam-local-invoke-helloworldfucntion-gives-typeerror-error-request-got-an-un/76630421#76630421

Upgrading my sam CLI from 1.86.1 to 1.89.0 worked

**Comment by emmanuelU17** [comment]
Just a random suggestion, I think the version when you try installing from winget needs to be looked at as as it is version 1.85.0
