### ISSUE TITLE
Bug: macOS `sam local start-api` invoke gives: "rosetta error: failed to open elf at"

### ISSUE THREAD

**Issue by riklemmers** [aws/aws-sam-cli#5606]
### Description:
On macOS when trying to run a Go Lambda locally with `sam build` and `sam local start-api` it returns an error after invoking it.  
```
rosetta error: failed to open elf at
```

### Steps to reproduce:

Using a simple Go lambda, main.go:
```go
package main

import (
	"context"
	"net/http"

	"github.com/aws/aws-lambda-go/events"
	"github.com/aws/aws-lambda-go/lambda"
)

func handleRequest(ctx context.Context, request events.APIGatewayV2HTTPRequest) (events.APIGatewayV2HTTPResponse, error) {
	return events.APIGatewayV2HTTPResponse{
		StatusCode: http.StatusOK,
		Body:       "{\"message\":\"ok\"}",
		Headers: map[string]string{
			"Content-Type": "application/json",
		},
	}, nil
}

func main() {
	lambda.Start(handleRequest)
}
```

template.yml
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for running Lambdas locally

Globals:
  Function:
    Timeout: 3
    Runtime: go1.x
    MemorySize: 512
    Architectures:
      - x86_64

Resources:
  RegistrationApiFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: ./cmd/registrationApiFunction/
      Handler: main
      Events:
        RegistrationEndpoint:
          Type: HttpApi
          Properties:
            Path: '/api/registration'
            Method: POST

```

Run `sam build --debug`
```
2023-07-25 12:27:48,836 | Found Serverless function with name='RegistrationApiFunction' and CodeUri='./cmd/registrationApiFunction/'
2023-07-25 12:27:48,837 | Instantiating build definitions
2023-07-25 12:27:48,838 | Same function build definition found, adding function (Previous: BuildDefinition(go1.x,
/Users/foo/dev/project/cmd/registrationApiFunction, Zip, , 6625876c-369f-4670-9b9d-be403df6be4d, {}, {}, x86_64, []), Current: BuildDefinition(go1.x,
/Users/foo/dev/project/cmd/registrationApiFunction, Zip, , e8c5019c-0524-4e8c-bf1f-ecde84d676a7, {}, {}, x86_64, []), Function:
Function(function_id='RegistrationApiFunction', name='RegistrationApiFunction', functionname='RegistrationApiFunction', runtime='go1.x', memory=512, timeout=3, handler='main', imageuri=None,
packagetype='Zip', imageconfig=None, codeuri='/Users/foo/dev/project/cmd/registrationApiFunction', environment=None, rolearn=None, layers=[],
events={'RegistrationEndpoint': {'Type': 'HttpApi', 'Properties': {'Path': '/api/registration', 'Method': 'POST', 'ApiId': 'ServerlessHttpApi'}}}, metadata={'SamResourceId': 'RegistrationApiFunction'},
inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None, function_build_info=<FunctionBuildInfo.BuildableZip: ('BuildableZip', 'Regular ZIP function which can be build
with SAM CLI')>, stack_path='', runtime_management_config=None))
2023-07-25 12:27:48,840 | Building codeuri: /Users/foo/dev/project/cmd/registrationApiFunction runtime: go1.x metadata: {} architecture: x86_64 functions:
RegistrationApiFunction
2023-07-25 12:27:48,841 | Building to following folder /Users/foo/dev/project/.aws-sam/build/RegistrationApiFunction
2023-07-25 12:27:48,841 | Loading workflow module 'aws_lambda_builders.workflows'
2023-07-25 12:27:48,842 | Registering workflow 'CustomMakeBuilder' with capability 'Capability(language='provided', dependency_manager=None, application_framework=None)'
2023-07-25 12:27:48,843 | Registering workflow 'DotnetCliPackageBuilder' with capability 'Capability(language='dotnet', dependency_manager='cli-package', application_framework=None)'
2023-07-25 12:27:48,844 | Registering workflow 'GoModulesBuilder' with capability 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-07-25 12:27:48,845 | Registering workflow 'JavaGradleWorkflow' with capability 'Capability(language='java', dependency_manager='gradle', application_framework=None)'
2023-07-25 12:27:48,846 | Registering workflow 'JavaMavenWorkflow' with capability 'Capability(language='java', dependency_manager='maven', application_framework=None)'
2023-07-25 12:27:48,848 | Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
2023-07-25 12:27:48,849 | Registering workflow 'NodejsNpmEsbuildBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm-esbuild', application_framework=None)'
2023-07-25 12:27:48,850 | Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
2023-07-25 12:27:48,851 | Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
2023-07-25 12:27:48,852 | Registering workflow 'RustCargoLambdaBuilder' with capability 'Capability(language='rust', dependency_manager='cargo', application_framework=None)'
2023-07-25 12:27:48,852 | Found workflow 'GoModulesBuilder' to support capabilities 'Capability(language='go', dependency_manager='modules', application_framework=None)'
2023-07-25 12:27:48,858 | Running workflow 'GoModulesBuilder'
2023-07-25 12:27:48,859 | Running GoModulesBuilder:Build
2023-07-25 12:27:49,083 | GoModulesBuilder:Build succeeded
2023-07-25 12:27:49,085 | There is no customer defined id or cdk path defined for resource RegistrationApiFunction, so we will use the resource logical id as the resource id
2023-07-25 12:27:49,085 | 2 resources found in the stack
2023-07-25 12:27:49,085 | Found Serverless function with name='RegistrationApiFunction' and CodeUri='./cmd/registrationApiFunction/'

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml
```

Start local api with `sam local start-api`
```
Mounting RegistrationApiFunction at http://127.0.0.1:3000/api/registration [POST]
You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected instantly/automatically. If you used
sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-07-25 10:26:39 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
2023-07-25 10:26:39 Press CTRL+C to quit
```

Send a POST request to the endpoint:
`curl -X POST http://127.0.0.1:3000/api/registration -d "{}"`

### Observed result:

The error is:
```
[ERROR] (rapid) Init failed error=Runtime exited with error: signal: trace/breakpoint trap InvokeID=
rosetta error: failed to open elf at
```

Complete output from calling the function via the API endpoint. `sam local start-api --debug`
```
2023-07-25 12:31:21,808 | Constructed Event Version 2.0 to invoke Lambda. Event: {'version': '2.0', 'routeKey': 'POST /api/registration', 'rawPath': '/api/registration', 'rawQueryString': '', 'cookies':
[], 'headers': {'Host': '127.0.0.1:3000', 'User-Agent': 'curl/7.88.1', 'Accept': '*/*', 'Content-Length': '2', 'Content-Type': 'application/x-www-form-urlencoded', 'X-Forwarded-Proto': 'http',
'X-Forwarded-Port': '3000'}, 'requestContext': {'accountId': '123456789012', 'apiId': '1234567890', 'http': {'method': 'POST', 'path': '/api/registration', 'protocol': 'HTTP/1.1', 'sourceIp': '127.0.0.1',
'userAgent': 'Custom User Agent String'}, 'requestId': '5cfdc08c-fd2b-4faf-9cd9-410b3fba595a', 'routeKey': 'POST /api/registration', 'stage': '$default', 'time': '25/Jul/2023:10:31:13 +0000', 'timeEpoch':
1690281073, 'domainName': 'localhost', 'domainPrefix': 'localhost'}, 'body': '{}', 'pathParameters': {}, 'stageVariables': None, 'isBase64Encoded': False}
2023-07-25 12:31:21,813 | Found one Lambda function with name 'RegistrationApiFunction'
2023-07-25 12:31:21,814 | Invoking main (go1.x)
2023-07-25 12:31:21,814 | No environment variables found for function 'RegistrationApiFunction'
2023-07-25 12:31:21,815 | Loading AWS credentials from session with profile 'None'
2023-07-25 12:31:21,823 | Resolving code path. Cwd=/Users/foo/dev/project/.aws-sam/build,
CodeUri=/Users/foo/dev/project/.aws-sam/build/RegistrationApiFunction
2023-07-25 12:31:21,824 | Resolved absolute path to code is /Users/foo/dev/project/.aws-sam/build/RegistrationApiFunction
2023-07-25 12:31:21,824 | Code /Users/foo/dev/project/.aws-sam/build/RegistrationApiFunction is not a zip/jar file
2023-07-25 12:31:23,969 | Local image is up-to-date
2023-07-25 12:31:23,988 | Using local image: public.ecr.aws/lambda/go:1-rapid-x86_64.

2023-07-25 12:31:23,989 | Mounting /Users/foo/dev/project/.aws-sam/build/RegistrationApiFunction as /var/task:ro,delegated, inside runtime container
2023-07-25 12:31:24,161 | Starting a timer for 3 seconds for function 'RegistrationApiFunction'
START RequestId: 56833e69-7239-4277-b57f-6dafd572dbdb Version: $LATEST
rosetta error: failed to open elf at
25 Jul 2023 10:31:24,298 [ERROR] (rapid) Init failed error=Runtime exited with error: signal: trace/breakpoint trap InvokeID=
rosetta error: failed to open elf at
END RequestId: 818c675f-61e1-405d-8b94-49d1d286295f
REPORT RequestId: 818c675f-61e1-405d-8b94-49d1d286295f	Init Duration: 0.44 ms	Duration: 24.23 ms	Billed Duration: 25 ms	Memory Size: 512 MB	Max Memory Used: 512 MB
2023-07-25 12:31:24,402 | Cleaning all decompressed code dirs
2023-07-25 12:31:24,404 | Unable to find Click Context for getting session_id.
2023-07-25 12:31:24,405 | Invalid lambda response received: Lambda response must be valid json
2023-07-25 12:31:24 127.0.0.1 - - [25/Jul/2023 12:31:24] "POST /api/registration HTTP/1.1" 502 -
```

### Expected result:

No error, and a working local running Lambda function.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOS Ventura 13.4.1 (c)
2. `sam --version`: SAM CLI, version 1.93.0
3. AWS region: none (running it locally)

`sam --info`
```json
{
  "version": "1.93.0",
  "system": {
    "python": "3.11.4",
    "os": "macOS-13.4.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.2",
    "aws_cdk": "Not available",
    "terraform": "1.5.3"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`go version go1.20.6 darwin/arm64`. 
Chip: Apple M2 Pro

**Comment by moelasmar** [comment]
Hello @riklemmers, thanks for raising this issue. 
I am not able to reproduce this issue on our M1 Mac environment 

- Was this use case working for you before? if yes, could you please for which SAM CLI Version.
- Can I ask you to update the template to run on Arm64 architecture, and try the same steps again, and let us know if does it work or not. I want to make sure that this issue is related to running X86_64 image on a ARM64 architecture or something else.
- Can you try to run `softwareupdate --install-rosetta` and retry your steps and let us know if fixed your problem or not.

**Comment by riklemmers** [comment]
Hi @moelasmar thanks for your reply.  
- I have never tried to use the aws-sam-cli before, so I never had this working.
- After updating the template with architecture `arm64` and running `sam build` and `sam local start-api` then invoking the endpoint I get the following error:
```
Invoking main (go1.x)
Exception on /api/registration [POST]
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/samcli/local/apigw/local_apigw_service.py", line 714, in
_request_handler
    lambda_response = self._invoke_lambda_function(route.function_name, route_lambda_event)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/samcli/local/apigw/local_apigw_service.py", line 612, in
_invoke_lambda_function
    self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer, stderr=self.stderr)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/samcli/commands/local/lib/local_lambda.py", line 138, in invoke
    validate_architecture_runtime(function)
  File "/opt/homebrew/Cellar/aws-sam-cli/1.93.0/libexec/lib/python3.11/site-packages/samcli/lib/utils/architecture.py", line 59, in
validate_architecture_runtime
    raise UnsupportedRuntimeArchitectureError(
samcli.commands.local.lib.exceptions.UnsupportedRuntimeArchitectureError: Runtime go1.x is not supported on 'arm64' architecture
2023-07-26 09:11:20 127.0.0.1 - - [26/Jul/2023 09:11:20] "POST /api/registration HTTP/1.1" 502 -
```
- Running `softwareupdate --install-rosetta` unfortunately did not fix my problems (not on x86_64 or on arm64.)

**Comment by moelasmar** [comment]
from the exception it seems that Go is not supported on arm64 architecture. Can I ask to use any other runtime with both architectures and let us know if it works or not.

**Comment by raythx98** [comment]
I am also facing the same issue as @riklemmers in Apple M1 Pro, here's my machine settings:

```
OS: macOS Ventura 13.4.1 (c)
sam --version: SAM CLI, version 1.93.0
AWS region: none (running it locally)
go version: go1.20.2 darwin/amd64
```
I have tried:
- run `softwareupdate --install-rosetta`
---
## Steps to reproduce using provided templates:
``` bash
sam init -a x86_64 --base-image amazon/go1.x-base
```
Then in the newly created project,
```
sam build
sam local start-api --debug
```
Executing the request `curl --location '127.0.0.1:3000/hello' --data ''` results in the following error 
``` shell
2023-07-27 14:34:20,367 | Constructed Event 1.0 to invoke Lambda. Event:
{'version': '1.0', 'httpMethod': 'GET', 'body': None, 'resource': '/hello',
'requestContext': {'resourceId': '123456', 'apiId': '1234567890',
'resourcePath': '/hello', 'httpMethod': 'GET', 'requestId':
'1ce918de-69f3-44d6-adce-af88e2e312a4', 'accountId': '123456789012', 'stage':
'Prod', 'identity': {'apiKey': None, 'userArn': None,
'cognitoAuthenticationType': None, 'caller': None, 'userAgent': 'Custom User
Agent String', 'user': None, 'cognitoIdentityPoolId': None,
'cognitoAuthenticationProvider': None, 'sourceIp': '127.0.0.1', 'accountId':
None}, 'extendedRequestId': None, 'path': '/hello', 'protocol': 'HTTP/1.1',
'domainName': '127.0.0.1:3000', 'requestTimeEpoch': 1690439650, 'requestTime':
'27/Jul/2023:06:34:10 +0000'}, 'queryStringParameters': None,
'multiValueQueryStringParameters': None, 'headers': {'User-Agent':
'PostmanRuntime/7.32.3', 'Accept': '*/*', 'Postman-Token':
'f5df5d4a-b0fa-44f6-b501-451a4ac23be4', 'Host': '127.0.0.1:3000',
'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive',
'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '3000'}, 'multiValueHeaders':
{'User-Agent': ['PostmanRuntime/7.32.3'], 'Accept': ['*/*'], 'Postman-Token':
['f5df5d4a-b0fa-44f6-b501-451a4ac23be4'], 'Host': ['127.0.0.1:3000'],
'Accept-Encoding': ['gzip, deflate, br'], 'Connection': ['keep-alive'],
'X-Forwarded-Proto': ['http'], 'X-Forwarded-Port': ['3000']}, 'pathParameters':
None, 'stageVariables': None, 'path': '/hello', 'isBase64Encoded': False}
2023-07-27 14:34:20,387 | Found one Lambda function with name 'HelloWorldFunction'
2023-07-27 14:34:20,388 | Invoking Container created from helloworldfunction:go1.x-v1
2023-07-27 14:34:20,427 | Reuse the created warm container for Lambda function 'HelloWorldFunction'
2023-07-27 14:34:20,436 | Lambda function 'HelloWorldFunction' is already running
2023-07-27 14:34:20,438 | Starting a timer for 5 seconds for function 'HelloWorldFunction'
rosetta error: failed to open elf at
27 Jul 2023 06:34:20,552 [ERROR] (rapid) Init failed error=Runtime exited with error: signal: trace/breakpoint trap InvokeID=
rosetta error: failed to open elf at
END RequestId: 0a8e48dd-4bd4-4f63-8e00-fcda35da4fe1
REPORT RequestId: 0a8e48dd-4bd4-4f63-8e00-fcda35da4fe1	Init Duration: 0.77 ms	Duration: 82.97 ms	Billed Duration: 83 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
2023-07-27 14:34:20,542 | Unable to find Click Context for getting session_id.
2023-07-27 14:34:20,547 | Invalid lambda response received: Lambda response must be valid json
2023-07-27 14:34:20 127.0.0.1 - - [27/Jul/2023 14:34:20] "GET /hello HTTP/1.1" 502 -
```

> Can I ask to use any other runtime with both architectures and let us know if it works or not.
Python is working fine for me, but my use case requires using `Go` so I hope to get some support on this

Let me know if you require additional information

**Comment by riklemmers** [comment]
After reading the docs at [Building Lambda functions with Go](https://docs.aws.amazon.com/lambda/latest/dg/lambda-golang.html) I see now that the `go1.x` runtime is being deprecated.  
When switching to the `provided.al2` Custom Runtime and using the [sample](https://github.com/aws-samples/sessions-with-aws-sam/blob/master/go-al2/README.md) to update my template and build, I got things working on both `x86_64` and `amd64`.  
  
So this doesn't fix the original issue, however as this is being deprecated I will migrate my functions to the new runtime and I don't require a fix.

**Comment by moelasmar** [comment]
thanks @riklemmers for the deep dive, It was not on top of my head that the `go1.x` runtime will be deprecated by the end of this year. 
@raythx98 could you please check if migrating to `provided.al2` solves your problem or not, and update us if you have any other issues.

**Comment by raythx98** [comment]
The workaround of using `provided.al2` is fine, thanks

**Comment by moelasmar** [comment]
Thanks @raythx98 for confirming that it is working for you. I discussed this problem with the team, and our recommendation is to migrate to `provided.al2`,  as `Go1.x` will deprecated by the end of the year.

**Comment by moelasmar** [comment]
I will close this issue based on the previous recommendation, and please open a new issue, if you have any other problem or question. Thanks
