### ISSUE TITLE
sam build results in "TypeError: unhashable type: 'collections.OrderedDict'"

### ISSUE THREAD

**Issue by Denis-D-M** [aws/aws-sam-cli#5607]
OS Windows 11
`sam --version`
SAM CLI, version 1.93.0

`sam build -t .\template-src.yaml`

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 120, in yaml_parse
    return cast(Dict, json.loads(yamlstr, object_pairs_hook=OrderedDict))
  File "json\__init__.py", line 370, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\__main__.py", line 12, in <module>
    cli(prog_name="sam")
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1655, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 920, in make_context
    self.parse_args(ctx, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1378, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2360, in handle_parse_result
    value = self.process_value(ctx, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 2322, in process_value
    value = self.callback(ctx, self, value)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\options.py", line 85, in get_or_default_template_file_name
    template_data = get_template_data(result)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\_utils\template.py", line 54, in get_template_data
    return yaml_parse(fp.read())
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 127, in yaml_parse
    return cast(Dict, yaml.safe_load(yamlstr))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 51, in get_single_data
    return self.construct_document(node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 55, in construct_document
    data = self.construct_object(node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 111, in _dict_constructor
    return OrderedDict(loader.construct_pairs(node))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 111, in _dict_constructor
    return OrderedDict(loader.construct_pairs(node))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 111, in _dict_constructor
    return OrderedDict(loader.construct_pairs(node))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 111, in _dict_constructor
    return OrderedDict(loader.construct_pairs(node))
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\yaml\constructor.py", line 100, in construct_object
    data = constructor(self, node)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\yamlhelper.py", line 111, in _dict_constructor
    return OrderedDict(loader.construct_pairs(node))
TypeError: unhashable type: 'collections.OrderedDict'

**Comment by moelasmar** [comment]
Thanks @Denis-D-M for raising this issue. Could you please share your template with us to reproduce this issue.

**Comment by Denis-D-M** [comment]
Hey @moelasmar, sorry for a delayed response, but I think I got it figured out, the indention was the issue:
it was
```
Resources:
  LambdaName:
  Type: AWS::Serverless::Function
  Properties:
    FunctionName: ...
```
instead of 
```
Resources:
  LambdaName:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ...
```
After applying this fix and deploying it using octopus, I was able to see another template related issue, but it was clear and unrelated to this..
However, when I fixed that, or when I tried to revert these changes, ON LOCAL I was still getting the same error, which is strange to me..
On the octopus server there is SAM CLI, version 1.46.0
On my local, as I said previously is SAM CLI, version 1.93.0
I tried to re-install python, as I saw that it might be related, but even after I deleted python, I still have the same error, and I can build other projects.
Any ideas?

**Comment by moelasmar** [comment]
could you share the new template that has this issue, and the error you are facing.

**Comment by moelasmar** [comment]
Closing due to inactivity, if there is any new information, please create another issue explaining the problem and we can diagnose from there.
