### ISSUE TITLE
aws quick templates not cloning

### ISSUE THREAD

**Issue by tantelman** [aws/aws-sam-cli#5665]
I'm getting the below error when selecting aws quick templates. 

$ sam init                                                                    

You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.                                                       

Which template source would you like to use?
        1 - AWS Quick Start Templates       
        2 - Custom Template Location        
Choice: 1                                   

Cloning from https://github.com/aws/aws-sam-cli-app-templates (process may take a moment)

Based on your selections, the only Template available is Hello World Example.
We will proceed to selecting the Template as Hello World Example.

Use the most popular runtime and package type? (Python and zip) [y/N]:

Others on my team are able to pick from a list of templates like 'DynamoDB' but I cannot. How do I resolve?

**Comment by lucashuy** [comment]
Hi, checking in with you to see if you are still experiencing this problem or not and if you are able to try the debugging steps above so that we can better triage this issue.

**Comment by sntxrr** [comment]
I'm experiencing something very similar to this:

```
keycloak-admin-dev-tools:~/environment $ sam init --debug
2023-08-10 21:51:12,012 | Telemetry endpoint configured to be https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-08-10 21:51:12,013 | Using config file: samconfig.toml, config environment: default
2023-08-10 21:51:12,014 | Expand command line arguments to:
2023-08-10 21:51:12,014 | --package_type=Zip --output_dir=. 

You can preselect a particular runtime or package type when using the `sam init` experience.
Call `sam init --help` to learn more.

Which template source would you like to use?
        1 - AWS Quick Start Templates
        2 - Custom Template Location
Choice: 1
2023-08-10 21:51:14,184 | Template is not provided in context, skip adding project type metric
2023-08-10 21:51:14,185 | Sending Telemetry: {'metrics': [{'commandRun': {'requestId': 'd75446b4-9ead-46da-8ffb-c793c165448e', 'installationId': '220a5dfb-ffdb-46c5-bf70-d686b255edea', 'sessionId': '232fb8bb-c0bf-48d7-b71f-521330cf4dba', 'executionEnvironment': 'CLI', 'ci': False, 'pyversion': '3.7.16', 'samcliVersion': '1.40.0', 'awsProfileProvided': False, 'debugFlagProvided': True, 'region': '', 'commandName': 'sam init', 'duration': 2171, 'exitReason': 'JSONDecodeError', 'exitCode': 255}}]}
2023-08-10 21:51:14,219 | Telemetry response: 200
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/__init__.py", line 128, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/samcli/lib/telemetry/metric.py", line 166, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "/usr/local/lib/python3.7/site-packages/samcli/lib/telemetry/metric.py", line 124, in wrapped
    return_value = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/samcli/lib/utils/version_checker.py", line 41, in wrapped
    actual_result = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/samcli/cli/main.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/__init__.py", line 274, in cli
    extra_context,
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/__init__.py", line 359, in do_cli
    no_input,
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/interactive_init_flow.py", line 65, in do_interactive
    location_opt_choice,
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/interactive_init_flow.py", line 94, in generate_application
    architecture,
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/interactive_init_flow.py", line 134, in _generate_from_use_case
    runtime_or_base_image, app_template, package_type_filter_value, dependency_manager
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/init_templates.py", line 176, in get_preprocessed_manifest
    manifest_body = self._get_manifest()
  File "/usr/local/lib/python3.7/site-packages/samcli/commands/init/init_templates.py", line 221, in _get_manifest
    manifest_body = json.loads(body)
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

keycloak-admin-dev-tools:~/environment $ sam --info
{
  "version": "1.40.0"
}
keycloak-admin-dev-tools:~/environment $
```

I'm running this from the AWS Lambda Workshop, on a freshly created Cloud9 instance.

**Comment by lucashuy** [comment]
Would it be possible to update SAM CLI in that environment? I noticed that the version that is installed is `1.40.0`, which is over a year old now. The current version is `1.95.0`, if updating to that version still exhibits the same problem let us know and we can further diagnose things.

**Comment by lucashuy** [comment]
Closing due to inactivity, if there is any new information, please create another issue explaining the problem and we can diagnose from there.
