### ISSUE TITLE
sam local start-api --warm-containers doesn't work on docker

### ISSUE THREAD

**Issue by piotrburant** [aws/aws-sam-cli#5678]
SAM CLI, version 1.94.0

### Description:
I use sam local start-api in docker to run integration tests of mu stack locally. It work ok without --warm-containers option but doesn't with it. I receive error when access api endpoint:
```Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/lib/python3.10/site-packages/samcli/local/apigw/local_apigw_service.py", line 714, in _request_handler
    lambda_response = self._invoke_lambda_function(route.function_name, route_lambda_event)
  File "/usr/lib/python3.10/site-packages/samcli/local/apigw/local_apigw_service.py", line 612, in _invoke_lambda_function
    self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer, stderr=self.stderr)
  File "/usr/lib/python3.10/site-packages/samcli/commands/local/lib/local_lambda.py", line 144, in invoke
    self.local_runtime.invoke(
  File "/usr/lib/python3.10/site-packages/samcli/lib/telemetry/metric.py", line 324, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/samcli/local/lambdafn/runtime.py", line 189, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/usr/lib/python3.10/site-packages/samcli/local/lambdafn/runtime.py", line 405, in create
    self._observer.watch(function_config)
  File "/usr/lib/python3.10/site-packages/samcli/lib/utils/file_observer.py", line 207, in watch
    self._observers[function_config.packagetype].watch(resource)
  File "/usr/lib/python3.10/site-packages/samcli/lib/utils/file_observer.py", line 394, in watch
    self._single_file_observer.watch(resource, self._group)
  File "/usr/lib/python3.10/site-packages/samcli/lib/utils/file_observer.py", line 521, in watch
    raise FileObserverException("Can not observe non exist path")
```

I've checked it and there is incorrect path in file_observer.py:518 in resource variable. It has path from my local computer, not from docker which starts the sam local api. When I hardcode it to docker path in file_observer.py then it works.

When I add -v param to sam local start-api command with docker path, then it doesn't affect resource variable value in above file.

It works ok in both scenarios when running on my local env, not inside docker.

**Comment by lucashuy** [comment]
Thanks for reporting this. Closing this issue due to inactivity, please create new issue with more details if you come across any more issues.

**Comment by cford1080** [comment]
@jfuss @lucashuy
I just ran into this issue today, so I can provide more info if you'd like to reopen this issue.

I'm using version [1.109 of this image](https://gallery.ecr.aws/sam/build-provided.al2), and I've confirmed version 1.109.0 of the SAM CLI running inside the container.

I believe the issue with `warm-containers` is somewhat related to [this closed issue](https://github.com/aws/aws-sam-cli/issues/3520#issuecomment-1235442385) around `docker-volume-basedir`.

I have a `template.yml` at the root of my project directory, and the `CodeUri` is `./build/function`. If I omit the warm containers option from start-api, everything works fine. However, I would like to speed up my tests by keeping the lambda warm. If I simply add the warm containers option to the start-api command, I see the same exception reported by OP:
`samcli.lib.utils.file_observer.FileObserverException: Can not observe non exist path`

However, if I take the suggestion provided in the comment I linked from the volume issue, everything (almost) works as expected, and the exception no longer occurs. I state `almost` b/c the container spun up to execute the lambda doesn't get cleaned up when the sam container goes down, and this also results in docker being unable to clean up the network. The failure to cleanup does not happen when omitting `warm-containers`.

**Comment by lucashuy** [comment]
Hi @cford1080, can you create a new issue with those details, along with a reproducible project? At first glance, it looks to be a working directory "de-sync", since the paths that SAM CLI sees and interacts with are relative to the Docker container it is running in, however the Docker containers SAM CLI would normally spin up have bind mounts/paths that are relative to the host machine.
