### ISSUE TITLE
Bug: flask error when trying to use dynamodb client or resource

### ISSUE THREAD

**Issue by CynanX** [aws/aws-sam-cli#5841]
### Description:
I have a lambda that I invoke via an API HTTP API gateway. Within AWS this runs without error.

When running this under `sam local start-api` it crashes with a flask error.

If I comment out the line creating a DynamoDB client or resource, the error goes away.

It appears that there is an issue within AWS SAM.

##### `./source_code/lambda_function.py`:

```python
import boto3

def lambda_handler(event, context):
    dynamo_resource = boto3.resource('dynamodb', endpoint_url='http://localhost:8000')

    return {
        "body": "sample messagee",
        "headers": {
            "content-type": "application/json"
        },
        "statusCode": 200
    }
```

##### `./source_code/requirements.txt`:

```
boto3
```

##### `./template.yaml`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SampleLambda

  Sample SAM Template for SampleLambda

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  AwsApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      Name: Basic AWS API Gateway
      StageName: dev

  SampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: source_code/
      Handler: lambda_function.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            ApiId: !Ref AwsApiGateway
            Path: /{proxy+}
            Method: GET
```

#### Running:

```
docker run -d -p 8000:8000 --name dynamo-local amazon/dynamodb-local -jar DynamoDBLocal.jar -inMemory -sharedDb
sam build
sam local start-api --debug
curl -X GET http://127.0.0.1:3000/sample
```

### Observed result:
```
2023-08-24 10:04:14,742 | Config file location: /Users/mark/git/sample/samconfig.toml
2023-08-24 10:04:14,744 | Loading configuration values from [default.['local', 'start-api'].parameters] (env.command_name.section) in config file at
'/Users/mark/git/sample/samconfig.toml'...
2023-08-24 10:04:14,745 | Configuration values successfully loaded.
2023-08-24 10:04:14,745 | Configuration values are: {'stack_name': 'SampleLambda', 'warm_containers': 'EAGER'}
2023-08-24 10:04:14,748 | Using SAM Template at /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:04:14,764 | Using config file: samconfig.toml, config environment: default
2023-08-24 10:04:14,764 | Expand command line arguments to:
2023-08-24 10:04:14,765 | --template_file=/Users/mark/git/sample/.aws-sam/build/template.yaml --host=127.0.0.1 --port=3000 --static_dir=public
--layer_cache_basedir=/Users/mark/.aws-sam/layers-pkg --warm_containers=EAGER --container_host=localhost --container_host_interface=127.0.0.1
2023-08-24 10:04:14,827 | local start-api command is called
2023-08-24 10:04:14,829 | No Parameters detected in the template
2023-08-24 10:04:14,844 | There is no customer defined id or cdk path defined for resource AwsApiGateway, so we will use the resource logical id as the resource id
2023-08-24 10:04:14,844 | Sam customer defined id is more priority than other IDs. Customer defined id for resource SampleLambda is SampleLambda
2023-08-24 10:04:14,845 | 0 stacks found in the template
2023-08-24 10:04:14,845 | No Parameters detected in the template
2023-08-24 10:04:14,854 | There is no customer defined id or cdk path defined for resource AwsApiGateway, so we will use the resource logical id as the resource id
2023-08-24 10:04:14,854 | Sam customer defined id is more priority than other IDs. Customer defined id for resource SampleLambda is SampleLambda
2023-08-24 10:04:14,855 | 2 resources found in the stack
2023-08-24 10:04:14,855 | Found Serverless function with name='SampleLambda' and CodeUri='SampleLambda'
2023-08-24 10:04:14,856 | --base-dir is not presented, adjusting uri SampleLambda relative to /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:04:14,856 | watch resource /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:04:14,857 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build/template.yaml with recursive True
2023-08-24 10:04:14,858 | watch resource /Users/mark/git/sample/.aws-sam/build/template.yaml's parent
/Users/mark/git/sample/.aws-sam/build
2023-08-24 10:04:14,859 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build with recursive False
2023-08-24 10:04:14,868 | Initializing the lambda functions containers.
2023-08-24 10:04:14,869 | Async execution started
2023-08-24 10:04:14,869 | Invoking function functools.partial(<function InvokeContext._initialize_all_functions_containers.<locals>.initialize_function_container at 0x1078a28b0>, Function(function_id='SampleLambda',
name='SampleLambda', functionname='SampleLambda', runtime='python3.11', memory=128, timeout=3, handler='lambda_function.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None,
codeuri='/Users/mark/git/sample/.aws-sam/build/SampleLambda', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'HttpApi', 'Properties': {'ApiId':
'AwsApiGateway', 'Path': '/{proxy+}', 'Method': 'GET'}}}, metadata={'SamResourceId': 'SampleLambda'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None,
function_build_info=<FunctionBuildInfo.BuildableZip: ('BuildableZip', 'Regular ZIP function which can be build with SAM CLI')>, stack_path='', runtime_management_config=None))
2023-08-24 10:04:14,871 | Waiting for async results
2023-08-24 10:04:14,877 | No environment variables found for function 'SampleLambda'
2023-08-24 10:04:14,877 | Loading AWS credentials from session with profile 'None'
2023-08-24 10:04:15,351 | Resolving code path. Cwd=/Users/mark/git/sample/.aws-sam/build,
CodeUri=/Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:04:15,353 | Resolved absolute path to code is /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:04:16,205 | watch resource /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:04:16,205 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build/SampleLambda with recursive True
2023-08-24 10:04:16,207 | watch resource /Users/mark/git/sample/.aws-sam/build/SampleLambda's parent
/Users/mark/git/sample/.aws-sam/build
2023-08-24 10:04:16,208 | Code /Users/mark/git/sample/.aws-sam/build/SampleLambda is not a zip/jar file
2023-08-24 10:04:21,466 | Local image is up-to-date
2023-08-24 10:04:21,498 | Using local image: public.ecr.aws/lambda/python:3.11-rapid-x86_64.

2023-08-24 10:04:21,500 | Mounting /Users/mark/git/sample/.aws-sam/build/SampleLambda as /var/task:ro,delegated, inside runtime container
2023-08-24 10:04:21,835 | Async execution completed
2023-08-24 10:04:21,835 | Containers Initialization is done.
2023-08-24 10:04:21,836 | Detected Inline Swagger definition
2023-08-24 10:04:21,836 | Parsing Swagger document using 3.0 specification
2023-08-24 10:04:21,837 | Lambda function integration not found in Swagger document at path='/{proxy+}' method='get'
2023-08-24 10:04:21,837 | Found '0' APIs in resource 'AwsApiGateway'
2023-08-24 10:04:21,838 | Found '0' authorizers in resource 'AwsApiGateway'
2023-08-24 10:04:21,838 | Found '1' API Events in Serverless function with name 'SampleLambda'
2023-08-24 10:04:21,839 | Removed duplicates from '1' Explicit APIs and '0' Implicit APIs to produce '1' APIs
2023-08-24 10:04:21,839 | 1 APIs found in the template
2023-08-24 10:04:21,840 | Mounting SampleLambda at http://127.0.0.1:3000/{proxy+} [GET]
2023-08-24 10:04:21,841 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected
instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-08-24 10:04:21,842 | Localhost server is starting up. Multi-threading = True
2023-08-24 10:04:21 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
2023-08-24 10:04:21 Press CTRL+C to quit
2023-08-24 10:04:36,366 | Constructed Event Version 2.0 to invoke Lambda. Event: {'version': '2.0', 'routeKey': 'GET /{proxy+}', 'rawPath': '/sample', 'rawQueryString': '', 'cookies': [], 'headers': {'Host':
'127.0.0.1:3000', 'User-Agent': 'curl/8.1.2', 'Accept': '*/*', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '3000'}, 'requestContext': {'accountId': '123456789012', 'apiId': '1234567890', 'http': {'method':
'GET', 'path': '/sample', 'protocol': 'HTTP/1.1', 'sourceIp': '127.0.0.1', 'userAgent': 'Custom User Agent String'}, 'requestId': '16e1c244-c263-41eb-be8a-8ebda6c68993', 'routeKey': 'GET /{proxy+}', 'stage': 'dev',
'time': '24/Aug/2023:09:04:14 +0000', 'timeEpoch': 1692867854, 'domainName': 'localhost', 'domainPrefix': 'localhost'}, 'body': '', 'pathParameters': {'proxy': 'sample'}, 'stageVariables': None, 'isBase64Encoded':
False}
2023-08-24 10:04:36,369 | Found one Lambda function with name 'SampleLambda'
2023-08-24 10:04:36,369 | Invoking lambda_function.lambda_handler (python3.11)
2023-08-24 10:04:36,370 | No environment variables found for function 'SampleLambda'
2023-08-24 10:04:36,371 | Resolving code path. Cwd=/Users/mark/git/sample/.aws-sam/build,
CodeUri=/Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:04:36,372 | Resolved absolute path to code is /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:04:36,385 | Reuse the created warm container for Lambda function 'SampleLambda'
2023-08-24 10:04:36,393 | Lambda function 'SampleLambda' is already running
2023-08-24 10:04:36,394 | Starting a timer for 3 seconds for function 'SampleLambda'
START RequestId: 3f282ed1-503d-4e88-9aa6-08aadd362e60 Version: $LATEST
2023-08-24 10:04:39,395 | Function 'SampleLambda' timed out after 3 seconds
END RequestId: 3f282ed1-503d-4e88-9aa6-08aadd362e60
REPORT RequestId: 3f282ed1-503d-4e88-9aa6-08aadd362e60	Init Duration: 1.53 ms	Duration: 3000.00 ms	Billed Duration: 3000 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
2023-08-24 10:04:39,528 | Exception on /sample [GET]
Traceback (most recent call last):
  File "flask/app.py", line 2529, in wsgi_app
  File "flask/app.py", line 1825, in full_dispatch_request
  File "flask/app.py", line 1823, in full_dispatch_request
  File "flask/app.py", line 1799, in dispatch_request
  File "samcli/local/apigw/local_apigw_service.py", line 714, in _request_handler
  File "samcli/local/apigw/local_apigw_service.py", line 612, in _invoke_lambda_function
  File "samcli/commands/local/lib/local_lambda.py", line 144, in invoke
  File "samcli/lib/telemetry/metric.py", line 324, in wrapped_func
  File "samcli/local/lambdafn/runtime.py", line 201, in invoke
  File "samcli/local/docker/container.py", line 354, in wait_for_result
  File "samcli/lib/utils/retry.py", line 30, in wrapper
  File "samcli/local/docker/container.py", line 334, in wait_for_http_response
  File "json/__init__.py", line 357, in loads
  File "json/decoder.py", line 337, in decode
  File "json/decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-08-24 10:04:39 127.0.0.1 - - [24/Aug/2023 10:04:39] "GET /sample HTTP/1.1" 502 -
```

### Expected result:
```
2023-08-24 10:06:31,361 | Config file location: /Users/mark/git/sample/samconfig.toml
2023-08-24 10:06:31,363 | Loading configuration values from [default.['local', 'start-api'].parameters] (env.command_name.section) in config file at
'/Users/mark/git/sample/samconfig.toml'...
2023-08-24 10:06:31,363 | Configuration values successfully loaded.
2023-08-24 10:06:31,364 | Configuration values are: {'stack_name': 'SampleLambda', 'warm_containers': 'EAGER'}
2023-08-24 10:06:31,366 | Using SAM Template at /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:06:31,381 | Using config file: samconfig.toml, config environment: default
2023-08-24 10:06:31,381 | Expand command line arguments to:
2023-08-24 10:06:31,382 | --template_file=/Users/mark/git/sample/.aws-sam/build/template.yaml --host=127.0.0.1 --port=3000 --static_dir=public
--layer_cache_basedir=/Users/mark/.aws-sam/layers-pkg --warm_containers=EAGER --container_host=localhost --container_host_interface=127.0.0.1
2023-08-24 10:06:31,446 | local start-api command is called
2023-08-24 10:06:31,448 | No Parameters detected in the template
2023-08-24 10:06:31,461 | There is no customer defined id or cdk path defined for resource AwsApiGateway, so we will use the resource logical id as the resource id
2023-08-24 10:06:31,462 | Sam customer defined id is more priority than other IDs. Customer defined id for resource SampleLambda is SampleLambda
2023-08-24 10:06:31,462 | 0 stacks found in the template
2023-08-24 10:06:31,463 | No Parameters detected in the template
2023-08-24 10:06:31,472 | There is no customer defined id or cdk path defined for resource AwsApiGateway, so we will use the resource logical id as the resource id
2023-08-24 10:06:31,472 | Sam customer defined id is more priority than other IDs. Customer defined id for resource SampleLambda is SampleLambda
2023-08-24 10:06:31,473 | 2 resources found in the stack
2023-08-24 10:06:31,473 | Found Serverless function with name='SampleLambda' and CodeUri='SampleLambda'
2023-08-24 10:06:31,474 | --base-dir is not presented, adjusting uri SampleLambda relative to /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:06:31,474 | watch resource /Users/mark/git/sample/.aws-sam/build/template.yaml
2023-08-24 10:06:31,475 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build/template.yaml with recursive True
2023-08-24 10:06:31,477 | watch resource /Users/mark/git/sample/.aws-sam/build/template.yaml's parent
/Users/mark/git/sample/.aws-sam/build
2023-08-24 10:06:31,477 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build with recursive False
2023-08-24 10:06:31,490 | Initializing the lambda functions containers.
2023-08-24 10:06:31,490 | Async execution started
2023-08-24 10:06:31,491 | Invoking function functools.partial(<function InvokeContext._initialize_all_functions_containers.<locals>.initialize_function_container at 0x107e628b0>, Function(function_id='SampleLambda',
name='SampleLambda', functionname='SampleLambda', runtime='python3.11', memory=128, timeout=3, handler='lambda_function.lambda_handler', imageuri=None, packagetype='Zip', imageconfig=None,
codeuri='/Users/mark/git/sample/.aws-sam/build/SampleLambda', environment=None, rolearn=None, layers=[], events={'HelloWorld': {'Type': 'HttpApi', 'Properties': {'ApiId':
'AwsApiGateway', 'Path': '/{proxy+}', 'Method': 'GET'}}}, metadata={'SamResourceId': 'SampleLambda'}, inlinecode=None, codesign_config_arn=None, architectures=['x86_64'], function_url_config=None,
function_build_info=<FunctionBuildInfo.BuildableZip: ('BuildableZip', 'Regular ZIP function which can be build with SAM CLI')>, stack_path='', runtime_management_config=None))
2023-08-24 10:06:31,493 | Waiting for async results
2023-08-24 10:06:31,501 | No environment variables found for function 'SampleLambda'
2023-08-24 10:06:31,501 | Loading AWS credentials from session with profile 'None'
2023-08-24 10:06:31,927 | Resolving code path. Cwd=/Users/mark/git/sample/.aws-sam/build,
CodeUri=/Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:06:31,929 | Resolved absolute path to code is /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:06:32,278 | watch resource /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:06:32,279 | Create Observer for resource /Users/mark/git/sample/.aws-sam/build/SampleLambda with recursive True
2023-08-24 10:06:32,280 | watch resource /Users/mark/git/sample/.aws-sam/build/SampleLambda's parent
/Users/mark/git/sample/.aws-sam/build
2023-08-24 10:06:32,281 | Code /Users/mark/git/sample/.aws-sam/build/SampleLambda is not a zip/jar file
2023-08-24 10:06:36,455 | Local image is up-to-date
2023-08-24 10:06:36,480 | Using local image: public.ecr.aws/lambda/python:3.11-rapid-x86_64.

2023-08-24 10:06:36,481 | Mounting /Users/mark/git/sample/.aws-sam/build/SampleLambda as /var/task:ro,delegated, inside runtime container
2023-08-24 10:06:36,869 | Async execution completed
2023-08-24 10:06:36,871 | Containers Initialization is done.
2023-08-24 10:06:36,872 | Detected Inline Swagger definition
2023-08-24 10:06:36,874 | Parsing Swagger document using 3.0 specification
2023-08-24 10:06:36,874 | Lambda function integration not found in Swagger document at path='/{proxy+}' method='get'
2023-08-24 10:06:36,875 | Found '0' APIs in resource 'AwsApiGateway'
2023-08-24 10:06:36,875 | Found '0' authorizers in resource 'AwsApiGateway'
2023-08-24 10:06:36,876 | Found '1' API Events in Serverless function with name 'SampleLambda'
2023-08-24 10:06:36,876 | Removed duplicates from '1' Explicit APIs and '0' Implicit APIs to produce '1' APIs
2023-08-24 10:06:36,876 | 1 APIs found in the template
2023-08-24 10:06:36,878 | Mounting SampleLambda at http://127.0.0.1:3000/{proxy+} [GET]
2023-08-24 10:06:36,879 | You can now browse to the above endpoints to invoke your functions. You do not need to restart/reload SAM CLI while working on your functions, changes will be reflected
instantly/automatically. If you used sam build before running local commands, you will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI if you update your AWS SAM template
2023-08-24 10:06:36,880 | Localhost server is starting up. Multi-threading = True
2023-08-24 10:06:36 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
2023-08-24 10:06:36 Press CTRL+C to quit
2023-08-24 10:06:46,159 | Constructed Event Version 2.0 to invoke Lambda. Event: {'version': '2.0', 'routeKey': 'GET /{proxy+}', 'rawPath': '/sample', 'rawQueryString': '', 'cookies': [], 'headers': {'Host':
'127.0.0.1:3000', 'User-Agent': 'curl/8.1.2', 'Accept': '*/*', 'X-Forwarded-Proto': 'http', 'X-Forwarded-Port': '3000'}, 'requestContext': {'accountId': '123456789012', 'apiId': '1234567890', 'http': {'method':
'GET', 'path': '/sample', 'protocol': 'HTTP/1.1', 'sourceIp': '127.0.0.1', 'userAgent': 'Custom User Agent String'}, 'requestId': '8952e0dc-887b-4284-b09d-4db27a746318', 'routeKey': 'GET /{proxy+}', 'stage': 'dev',
'time': '24/Aug/2023:09:06:31 +0000', 'timeEpoch': 1692867991, 'domainName': 'localhost', 'domainPrefix': 'localhost'}, 'body': '', 'pathParameters': {'proxy': 'sample'}, 'stageVariables': None, 'isBase64Encoded':
False}
2023-08-24 10:06:46,162 | Found one Lambda function with name 'SampleLambda'
2023-08-24 10:06:46,163 | Invoking lambda_function.lambda_handler (python3.11)
2023-08-24 10:06:46,164 | No environment variables found for function 'SampleLambda'
2023-08-24 10:06:46,165 | Resolving code path. Cwd=/Users/mark/git/sample/.aws-sam/build,
CodeUri=/Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:06:46,165 | Resolved absolute path to code is /Users/mark/git/sample/.aws-sam/build/SampleLambda
2023-08-24 10:06:46,174 | Reuse the created warm container for Lambda function 'SampleLambda'
2023-08-24 10:06:46,181 | Lambda function 'SampleLambda' is already running
2023-08-24 10:06:46,183 | Starting a timer for 3 seconds for function 'SampleLambda'
START RequestId: 071e0924-17b8-4206-9be9-aa5eb33fffca Version: $LATEST
END RequestId: 071e0924-17b8-4206-9be9-aa5eb33fffca
REPORT RequestId: 071e0924-17b8-4206-9be9-aa5eb33fffca	Init Duration: 1.20 ms	Duration: 2705.25 ms	Billed Duration: 2706 ms	Memory Size: 128 MB	Max Memory Used: 128 MB
2023-08-24 10:06:49,920 | Unable to find Click Context for getting session_id.
2023-08-24 10:06:49 127.0.0.1 - - [24/Aug/2023 10:06:49] "GET /sample HTTP/1.1" 200 -
```

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```json
{
  "version": "1.95.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-13.5.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.5",
    "aws_cdk": "Not available",
    "terraform": "1.3.7"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by hnnasit** [comment]
Hi @CynanX, thanks for reporting the issue. From the Traceback error, it seems like the lambda function times out after 3 seconds. Could you increase the `Timeout` under Globals and check if you still run into the same issue?

**Comment by CynanX** [comment]
Spot on.

I don't know why I didn't try that.. or I thought I did, and then... well anyway, thank you this solved the issue.

I then had another time out over 10 seconds and this was due to when running in sam, the lambda could not talk to the dynamodb I had running in another docker container, so I in the lambda you have to detect if you're running in SAM (using an environment variable) and switch the endpoint you're using.

e.g.

```
if SAM_LOCAL_ENVIRONMENT == "true":
    DYNAMO_RESOURCE = boto3.resource('dynamodb', endpoint_url='http://docker.for.mac.localhost:8000')
else:
    DYNAMO_RESOURCE = boto3.resource("dynamodb", region_name="eu-west-1")
```

Thanks again for the help.
