### ISSUE TITLE
Bug: `sam local start-lambda` encounters an exception after running the lambda's app code

### ISSUE THREAD

**Issue by sbchisholm** [aws/aws-sam-cli#6033]
### Description:
`sam local start-lambda` encounters the following exception after running lambda app code:
```
AttributeError: '_io.StringIO' object has no attribute 'buffer'
```
The application code runs without issue but then `sam` is hitting to the following exception (see traceback below).

### Steps to reproduce:
1. run sam using:  `sam local start-lambda`
1.  invoke the lambda on the local sam instance (in my case I'm using the `RequestResponse` invocation type)

### Observed result:
```
Exception on /2015-03-31/functions/FunctionName/invocations [POST]
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/steve/.local/lib/python3.8/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/steve/.local/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/steve/.local/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/local/lambda_service/local_lambda_invoke_service.py", line 169, in _invoke_request_handler
    self.lambda_runner.invoke(function_name, request_data, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 144, in invoke
    self.local_runtime.invoke(
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 324, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 201, in invoke
    container.wait_for_result(
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/local/docker/container.py", line 368, in wait_for_result
    stdout.write_bytes(response)
  File "/home/steve/.local/lib/python3.8/site-packages/samcli/lib/utils/stream_writer.py", line 35, in write_bytes
    self._stream.buffer.write(output)
AttributeError: '_io.StringIO' object has no attribute 'buffer'
2023-10-04 11:42:18 10.99.0.7 - - [04/Oct/2023 11:42:18] "POST /2015-03-31/functions/FunctionName/invocations HTTP/1.1" 500 -
```

### Expected result:
HTTP 200 return code

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

```
{
  "version": "1.98.0",
  "system": {
    "python": "3.8.14",
    "os": "Linux-6.1.53-1-MANJARO-x86_64-with-glibc2.34"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.5",
    "aws_cdk": "Not available",
    "terraform": "1.1.6"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by mildaniel** [comment]
Does this issue happen on just version 1.98.0 or on previous version also?

**Comment by sbchisholm** [comment]
Previous versions I was running into a different bug #5799, the last version that was working for me was 1.94.

**Comment by darhsu** [comment]
When running `sam local start-api` I hit the same error as @sbchisholm.

Pulling the fix at #6034 worked

**Comment by GeeWee** [comment]
I get the same error as well with the latest version of the CLI (1.99)

**Comment by PhilBroadbent** [comment]
I'm seeing this on 1.100.0 but interestingly not on `nodejs14.x`, only on `nodejs16.x` / `nodejs18.x` - I'm not sure if that's helpful but FYI in case

**Comment by Runeword** [comment]
I get the same error with 1.99.0 and 1.100.0

**Comment by OrRosenblatt** [comment]
Getting the same issue with SAM CLI v1.100.0, when running the command `sam local start-api`. It seems to be triggered when `[ERROR] (rapid) Init failed InvokeID= error=Runtime exited without providing a reason` is thrown:

`sam --info`:
```
{
  "version": "1.100.0",
  "system": {
    "python": "3.12.0",
    "os": "macOS-13.6-x86_64-i386-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.6",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

Error stack trace:
```
2023-11-06 09:18:17,186 | Failed to deserialize response from RIE, returning the raw response as is                                                         
2023-11-06 09:18:18,191 | Exception on /api/customer-details [POST]                                                                                         
Traceback (most recent call last):                                                                                                                          
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/flask/app.py", line 1455, in wsgi_app                                    
    response = self.full_dispatch_request()                                                                                                                 
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/flask/app.py", line 869, in full_dispatch_request                        
    rv = self.handle_user_exception(e)                                                                                                                      
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                      
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/flask/app.py", line 867, in full_dispatch_request                        
    rv = self.dispatch_request()                                                                                                                            
         ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/flask/app.py", line 852, in dispatch_request                             
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)                                                                                
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/local/apigw/local_apigw_service.py", line 719, in _request_handler
    lambda_response = self._invoke_lambda_function(route.function_name, route_lambda_event)                                                                 
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/local/apigw/local_apigw_service.py", line 612, in                 
_invoke_lambda_function                                                                                                                                     
    self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer, stderr=self.stderr)                                                    
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/commands/local/lib/local_lambda.py", line 144, in invoke          
    self.local_runtime.invoke(                                                                                                                              
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/lib/telemetry/metric.py", line 324, in wrapped_func               
    return_value = func(*args, **kwargs)                                                                                                                    
                   ^^^^^^^^^^^^^^^^^^^^^                                                                                                                    
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/local/lambdafn/runtime.py", line 201, in invoke                   
    container.wait_for_result(                                                                                                                              
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/local/docker/container.py", line 368, in wait_for_result          
    stdout.write_bytes(response)                                                                                                                            
  File "/usr/local/Cellar/aws-sam-cli/1.100.0/libexec/lib/python3.12/site-packages/samcli/lib/utils/stream_writer.py", line 35, in write_bytes              
    self._stream.buffer.write(output)                                                                                                                       
    ^^^^^^^^^^^^^^^^^^^                                                                                                                                     
AttributeError: '_io.StringIO' object has no attribute 'buffer'                                                                                             
2023-11-06 09:18:18 127.0.0.1 - - [06/Nov/2023 09:18:18] "POST /api/customer-details HTTP/1.1" 502 -
```

**Comment by awardrts** [comment]
Just a heads up, we are seeing the same issue only with Node 18, and while utilizing the `mssql` library. The issue appears when the SQL query is issued. We see the [test](https://ci.appveyor.com/project/AWSSAMCLI/aws-sam-cli-canary-windows/builds/48469265) on the code merged to attempt to fix this is failing. 

Can we please have an update when a fixed build will be available? Is there anything else we can provide from our side to help resolve the issue? This is currently a blocker for local development.
