### ISSUE TITLE
Bug: sam build - RuntimeError

### ISSUE THREAD

**Issue by ssl200606** [aws/aws-sam-cli#6058]
### Description:

Running:  sam build --use-container --debug
Error: Container does not exist. Cannot get logs for this container

### Steps to reproduce:

Using AWS SAM CLI to run example template:
sam build --use-container --debug

### Observed result:

Error: Container does not exist. Cannot get logs for this container
Traceback:
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\cli_config_file.py", line 297, in wrapper
    return func(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 184, in wrapped
    raise exception  # pylint: disable=raising-bad-type
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\telemetry\metric.py", line 149, in wrapped
    return_value = func(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\version_checker.py", line 42, in wrapped
    actual_result = func(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\cli\main.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 171, in cli
    do_cli(
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\command.py", line 260, in do_cli
    ctx.run()
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\commands\build\build_context.py", line 281, in run
    self._build_result = builder.build()
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 217, in build
    return ApplicationBuildResult(build_graph, build_strategy.build())
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 394, in build
    return super().build()
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 81, in build
    result.update(self._build_functions(self._build_graph))
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 400, in _build_functions
    return self._run_builds_async(
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 416, in _run_builds_async
    async_results = async_context.run_async()
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 131, in run_async
    return run_given_tasks_async(self._async_tasks, event_loop)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 90, in run_given_tasks_async
    return event_loop.run_until_complete(_run_given_tasks_async(tasks, event_loop, executor))
  File "asyncio\base_events.py", line 616, in run_until_complete
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\utils\async_utils.py", line 58, in _run_given_tasks_async
    raise result
  File "concurrent\futures\thread.py", line 57, in run
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 427, in build_single_function_definition
    return self._delegate_build_strategy.build_single_function_definition(build_definition)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 573, in build_single_function_definition
    return self._cached_build_strategy.build_single_function_definition(build_definition)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 282, in build_single_function_definition
    build_result = self._delegate_build_strategy.build_single_function_definition(build_definition)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\build_strategy.py", line 164, in build_single_function_definition
    result = self._build_function(
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 697, in _build_function
    return self._build_function_on_container(
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\lib\build\app_builder.py", line 950, in _build_function_on_container
    container.wait_for_logs(stdout=stdout_stream, stderr=stderr_stream)
  File "C:\Amazon\AWSSAMCLI\runtime\lib\site-packages\samcli\local\docker\container.py", line 383, in wait_for_logs
    raise RuntimeError("Container does not exist. Cannot get logs for this container")

An unexpected error was encountered while executing "sam build".
Search for an existing issue:
https://github.com/aws/aws-sam-cli/issues?q=is%3Aissue+is%3Aopen+Bug%3A%20sam%20build%20-%20RuntimeError
Or create a bug report:
https://github.com/aws/aws-sam-cli/issues/new?template=Bug_report.md&title=Bug%3A%20sam%20build%20-%20RuntimeError

### Expected result:

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  Windows 10
2. `sam --version`:  SAM CLI, version 1.98.0
3. AWS region:  us-east-1

```
# Paste the output of `sam --info` here
```
C:\projects\sam-app>sam --info
{
  "version": "1.98.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

`Add --debug flag to command you are running`  --debug added.

**Comment by lucashuy** [comment]
Thanks for opening this issue. Have you experienced this problem before on earlier versions of SAM CLI? I am not able to reproduce this crash using the following SAM CLI and Docker:
```
C:\Users\Administrator\Desktop\missingcontainer>sam --info
{
  "version": "1.98.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.17763-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.6",
    "aws_cdk": "Not available",
    "terraform": "1.5.0"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```
Could you try upgrading your Docker Desktop version? I currently have 4.24.1, which has Docker Engine 24.0.6 installed.

**Comment by ssl200606** [comment]
Sorry for the late reply.  I use my home PC with docker 24.x and it works.
Somehow, my work PC is a locked down PC with many policies applied.  I
can't use: sam build command to build Lambda function directly with error
timeout on the https://....  This is why I choose to run: sam build
--use-container instead.  Note that is called Docker Business Desktop
10.21.  I'm not sure if this is the same version as the one from Docker Hub?

Thank you Lucas for getting back to me fast.

**Comment by lucashuy** [comment]
Thanks for providing some more context. Is the error message about the missing container the error you saw on your home PC, and went away after you upgrade to Docker Engine 24? Or is the missing container error from your work PC?

If its the missing container error from your work PC, can you paste the full `sam build --use-container --debug` log here inside of code blocks?
````
```
<sam build logs>
```
````

**Comment by ssl200606** [comment]
Sorry for the late reply.  My work PC had a hardware issue and was replaced
with the new one.My Docker version is still the same. I
installed Python 3.11.6 for Windows on my local PC.  I still get the same
error message but it created images in Docker.

REPOSITORY                            TAG             IMAGE ID
 CREATED        SIZE
public.ecr.aws/sam/build-python3.11   latest-x86_64   aa1ad848cba7   45
hours ago   1.89GB

C:\projects\sam-app>sam --info
{
  "version": "1.98.0",
  "system": {
    "python": "3.8.8",
    "os": "Windows-10-10.0.19041-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "20.10.22",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

C:\projects\sam-app>sam build --use-container --debug
2023-10-20 10:20:34,376 | Config file location:
C:\projects\sam-app\samconfig.toml
2023-10-20 10:20:34,383 | Loading configuration values from
[default.['build'].parameters] (env.command_name.section) in
config file at 'C:\projects\sam-app\samconfig.toml'...
2023-10-20 10:20:34,387 | Configuration values successfully loaded.
2023-10-20 10:20:34,389 | Configuration values are: {'stack_name':
'sam-app', 'cached': True, 'parallel': True}
2023-10-20 10:20:34,412 | Using SAM Template at
C:\projects\sam-app\template.yaml
2023-10-20 10:20:34,453 | Using config file: samconfig.toml, config
environment: default
2023-10-20 10:20:34,456 | Expand command line arguments to:
2023-10-20 10:20:34,458 | --template_file=C:\projects\sam-app\template.yaml
--use_container --parallel --mount_with=READ
--build_dir=.aws-sam\build --cache_dir=.aws-sam\cache --cached
2023-10-20 10:20:34,787 | 'build' command is called
2023-10-20 10:20:34,790 | Starting Build use cache
2023-10-20 10:20:34,793 | Starting Build inside a container
2023-10-20 10:20:34,801 | No Parameters detected in the template
2023-10-20 10:20:34,958 | There is no customer defined id or cdk path
defined for resource HelloWorldFunction, so we
will use the resource logical id as the resource id
2023-10-20 10:20:34,961 | There is no customer defined id or cdk path
defined for resource ServerlessRestApi, so we will
use the resource logical id as the resource id
2023-10-20 10:20:34,965 | 0 stacks found in the template
2023-10-20 10:20:34,969 | No Parameters detected in the template
2023-10-20 10:20:35,017 | There is no customer defined id or cdk path
defined for resource HelloWorldFunction, so we
will use the resource logical id as the resource id
2023-10-20 10:20:35,022 | There is no customer defined id or cdk path
defined for resource ServerlessRestApi, so we will
use the resource logical id as the resource id
2023-10-20 10:20:35,025 | 2 resources found in the stack
2023-10-20 10:20:35,027 | Found Serverless function with
name='HelloWorldFunction' and CodeUri='hello_world/'
2023-10-20 10:20:35,030 | --base-dir is not presented, adjusting uri
hello_world/ relative to
C:\projects\sam-app\template.yaml
2023-10-20 10:20:35,054 | 2 resources found in the stack
2023-10-20 10:20:35,057 | Found Serverless function with
name='HelloWorldFunction' and CodeUri='hello_world/'
2023-10-20 10:20:35,065 | Instantiating build definitions
2023-10-20 10:20:35,068 | No previous build graph found, generating new one
2023-10-20 10:20:35,072 | Unique function build definition found, adding as
new (Function Build Definition:
BuildDefinition(python3.11, C:\projects\sam-app\hello_world, Zip, ,
051b4404-0f67-427c-a619-7fa27c0ff2f4, {}, {},
x86_64, []), Function: Function(function_id='HelloWorldFunction',
name='HelloWorldFunction',
functionname='HelloWorldFunction', runtime='python3.11', memory=None,
timeout=3, handler='app.lambda_handler',
imageuri=None, packagetype='Zip', imageconfig=None,
codeuri='C:\\projects\\sam-app\\hello_world', environment=None,
rolearn=None, layers=[], events={'HelloWorld': {'Type': 'Api',
'Properties': {'Path': '/hello', 'Method': 'get',
'RestApiId': 'ServerlessRestApi'}}}, metadata={'SamResourceId':
'HelloWorldFunction'}, inlinecode=None,
codesign_config_arn=None, architectures=['x86_64'],
function_url_config=None,
function_build_info=<FunctionBuildInfo.BuildableZip: ('BuildableZip',
'Regular ZIP function which can be build with SAM
CLI')>, stack_path='', runtime_management_config=None))
2023-10-20 10:20:35,086 | Async execution started
2023-10-20 10:20:35,093 | Invoking function functools.partial(<bound method
ParallelBuildStrategy.build_single_function_definition of
<samcli.lib.build.build_strategy.ParallelBuildStrategy object
at 0x00000197AE6E8EE0>>,
<samcli.lib.build.build_graph.FunctionBuildDefinition object at
0x00000197AC64EA30>)
2023-10-20 10:20:35,098 | Running incremental build for runtime python3.11
for following resources (HelloWorldFunction)
2023-10-20 10:20:35,102 | Waiting for async results
2023-10-20 10:20:35,141 | Cache is invalid, running build and copying
resources for following functions
(HelloWorldFunction)
2023-10-20 10:20:35,145 | Building codeuri: C:\projects\sam-app\hello_world
runtime: python3.11 metadata: {}
architecture: x86_64 functions: HelloWorldFunction
2023-10-20 10:20:35,149 | Building to following folder
C:\projects\sam-app\.aws-sam\build\HelloWorldFunction

Fetching public.ecr.aws/sam/build-python3.11:latest-x86_64 Docker container
image.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
2023-10-20 10:24:27,992 | Mounting C:\projects\sam-app\hello_world as
/tmp/samcli/source:ro,delegated, inside runtime
container
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'CustomMakeBuilder' with capability
'Capability(language='provided', dependency_manager=None,
application_framework=None)'
Registering workflow 'DotnetCliPackageBuilder' with capability
'Capability(language='dotnet', dependency_manager='cli-package',
application_framework=None)'
Registering workflow 'GoModulesBuilder' with capability
'Capability(language='go', dependency_manager='modules',
application_framework=None)'
Registering workflow 'JavaGradleWorkflow' with capability
'Capability(language='java', dependency_manager='gradle',
application_framework=None)'
Registering workflow 'JavaMavenWorkflow' with capability
'Capability(language='java', dependency_manager='maven',
application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability
'Capability(language='nodejs', dependency_manager='npm',
application_framework=None)'
Registering workflow 'NodejsNpmEsbuildBuilder' with capability
'Capability(language='nodejs', dependency_manager='npm-esbuild',
application_framework=None)'
Registering workflow 'PythonPipBuilder' with capability
'Capability(language='python', dependency_manager='pip',
application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability
'Capability(language='ruby', dependency_manager='bundler',
application_framework=None)'
Registering workflow 'RustCargoLambdaBuilder' with capability
'Capability(language='rust', dependency_manager='cargo',
application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities
'Capability(language='python', dependency_manager='pip',
application_framework=None)'
Running workflow 'PythonPipBuilder'
 Running PythonPipBuilder:ResolveDependencies
calling pip download -r /tmp/samcli/source/requirements.txt --dest
/tmp/samcli/scratch --exists-action i
PythonPipBuilder:ResolveDependencies failed
Traceback (most recent call last):
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/actions.py",
line 64, in execute
    package_builder.build_dependencies(
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 158, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path,
artifacts_dir_path, scratch_dir_path)
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 259, in build_site_packages
    wheels, packages_without_wheels =
self._download_dependencies(scratch_directory, requirements_filepath)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 283, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 365, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 801, in download_all_dependencies
    raise NoSuchPackageError(str(package_name))
aws_lambda_builders.workflows.python_pip.packager.NoSuchPackageError: Could
not satisfy the requirement: requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflow.py",
line 371, in run
    action.execute()
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/actions.py",
line 70, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Could not satisfy the
requirement: requests
Builder workflow failed
Traceback (most recent call last):
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/actions.py",
line 64, in execute
    package_builder.build_dependencies(
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 158, in build_dependencies
    self._dependency_builder.build_site_packages(requirements_path,
artifacts_dir_path, scratch_dir_path)
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 259, in build_site_packages
    wheels, packages_without_wheels =
self._download_dependencies(scratch_directory, requirements_filepath)

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 283, in _download_dependencies
    deps = self._download_all_dependencies(requirements_filename, directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 365, in _download_all_dependencies
    self._pip.download_all_dependencies(requirements_filename, directory)
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/packager.py",
line 801, in download_all_dependencies
    raise NoSuchPackageError(str(package_name))
aws_lambda_builders.workflows.python_pip.packager.NoSuchPackageError: Could
not satisfy the requirement: requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflow.py",
line 371, in run
    action.execute()
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflows/python_pip/actions.py",
line 70, in execute
    raise ActionFailedError(str(ex))
aws_lambda_builders.actions.ActionFailedError: Could not satisfy the
requirement: requests

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/__main__.py",
line 117, in main
    builder.build(
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/builder.py",
line 170, in build
    return workflow.run()
           ^^^^^^^^^^^^^^
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflow.py",
line 115, in wrapper
    func(self, *args, **kwargs)
  File
"/usr/local/opt/sam-cli/lib/python3.11/site-packages/aws_lambda_builders/workflow.py",
line 378, in run
    raise WorkflowFailedError(workflow_name=self.NAME,
action_name=action.NAME, reason=str(ex))
aws_lambda_builders.exceptions.WorkflowFailedError:
PythonPipBuilder:ResolveDependencies - Could not satisfy the requirement:
requests
2023-10-20 10:24:59,954 | Build inside container returned response
{"jsonrpc": "2.0", "id": 1, "error": {"code": 400,
"message": "PythonPipBuilder:ResolveDependencies - Could not satisfy the
requirement: requests"}}
2023-10-20 10:25:01,760 | Exception raised during the execution

Build Failed
2023-10-20 10:25:01,779 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-10-20 10:25:02,262 | Telemetry endpoint configured to be
https://aws-serverless-tools-telemetry.us-west-2.amazonaws.com/metrics
2023-10-20 10:25:02,264 | Sending Telemetry: {'metrics': [{'commandRun':
{'requestId':
'03d06821-f1e3-47e1-91b4-3e1806f53e18', 'installationId':
'5149d408-2cda-45a1-bb38-fa090a161f80', 'sessionId':
'66c67e8c-63b8-4a72-9cb6-edd738152af2', 'executionEnvironment': 'CLI',
'ci': False, 'pyversion': '3.8.8',
'samcliVersion': '1.98.0', 'awsProfileProvided': False,
'debugFlagProvided': True, 'region': '', 'commandName': 'sam
build', 'metricSpecificAttributes': {'projectType': 'CFN', 'gitOrigin':
None, 'projectName':
'593ab2ca51e925b9f6c2f258bc55ed5926cf6d2c78239a685d65907e4ec7edd3',
'initialCommit': None}, 'duration': 267324,
'exitReason': 'BuildInsideContainerError', 'exitCode': 1}}]}
2023-10-20 10:25:02,265 | Unable to find Click Context for getting
session_id.
2023-10-20 10:25:02,277 | Sending Telemetry: {'metrics': [{'events':
{'requestId':
'c6072f1a-5674-4b9b-876d-a9ba750d8b77', 'installationId':
'5149d408-2cda-45a1-bb38-fa090a161f80', 'sessionId':
'66c67e8c-63b8-4a72-9cb6-edd738152af2', 'executionEnvironment': 'CLI',
'ci': False, 'pyversion': '3.8.8',
'samcliVersion': '1.98.0', 'commandName': 'sam build',
'metricSpecificAttributes': {'events': [{'event_name':
'SamConfigFileExtension', 'event_value': '.toml', 'thread_id':
'10ea9353be324b3b8228ab38dcabb003', 'time_stamp':
'2023-10-20 14:20:34.376', 'exception_name': None}, {'event_name':
'SamConfigFileExtension', 'event_value': '.toml',
'thread_id': 'cfef4c0697864cd2bf358ddcde8da293', 'time_stamp': '2023-10-20
14:20:34.453', 'exception_name': None},
{'event_name': 'BuildWorkflowUsed', 'event_value': 'python-pip',
'thread_id': '4f62721643a64f77a02e102f6e282336',
'time_stamp': '2023-10-20 14:20:35.063', 'exception_name': None},
{'event_name': 'BuildFunctionRuntime', 'event_value':
'python3.11', 'thread_id': 'eef2937cb61d406dbfa477bf20ea4735',
'time_stamp': '2023-10-20 14:20:35.065',
'exception_name': None}, {'event_name': 'BuildWorkflowUsed', 'event_value':
'python-pip', 'thread_id':
'36d357fa5bc04eb6aa6282c37aeb50ad', 'time_stamp': '2023-10-20
14:20:35.155', 'exception_name': None}]}}}]}
2023-10-20 10:25:02,693 | Telemetry response: 200
2023-10-20 10:25:02,710 | HTTPSConnectionPool(host='
aws-serverless-tools-telemetry.us-west-2.amazonaws.com', port=443):
Read timed out. (read timeout=0.1)
Error: PythonPipBuilder:ResolveDependencies - Could not satisfy the
requirement: requests
