### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'xxxxx'

### ISSUE THREAD

**Issue by bfoura** [aws/aws-sam-cli#6116]
### Description:

We have updated sam to last version 1.99 ( with `brew install aws-sam-cli`).
Now wen we run any sam command, `sam --version` for example, we get a **ModuleNotFoundError** error 

### Steps to reproduce:
Just update sam to last version 1.99 ( with `brew install aws-sam-cli`). 

### Observed result:

```
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 5, in <module>
    from samcli.cli.main import cli
  File "/usr/local/Cellar/aws-sam-cli/1.99.0/libexec/lib/python3.12/site-packages/samcli/cli/main.py", line 12, in <module>
    from samcli.cli.context import Context
  File "/usr/local/Cellar/aws-sam-cli/1.99.0/libexec/lib/python3.12/site-packages/samcli/cli/context.py", line 14, in <module>
    from samcli.lib.utils.sam_logging import (
  File "/usr/local/Cellar/aws-sam-cli/1.99.0/libexec/lib/python3.12/site-packages/samcli/lib/utils/sam_logging.py", line 9, in <module>
    from rich.logging import RichHandler
  File "/usr/local/Cellar/aws-sam-cli/1.99.0/libexec/lib/python3.12/site-packages/rich/logging.py", line 15, in <module>
    from .traceback import Traceback
  File "/usr/local/Cellar/aws-sam-cli/1.99.0/libexec/lib/python3.12/site-packages/rich/traceback.py", line 23, in <module>
    from pygments.lexers import guess_lexer_for_filename
ModuleNotFoundError: No module named 'pygments'
```

### Expected result:

Getting sam version, or any other sam commands results 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

We are on MacOS Ventura 13.5.2
We are not atble to run any other sam commands.

**Comment by bfoura** [comment]
I found this documentation [page](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/manage-sam-cli-versions.html#manage-sam-cli-versions-homebrew) that says that we should not use homebrew anymore. Instead we should use the official package installer. Now sam is working as expected.
