### ISSUE TITLE
Bug: sam build - ValueError [Errno 13] Permission denied: '/tmp/samcli/scratch'

### ISSUE THREAD

**Issue by piyush-bhuwalka** [aws/aws-sam-cli#6192]
### Description:

We are using  sam build --use-container --build-image repo/testing:5.6.4 --debug and it fails with permission denied. Inside the build image, we want to use another user which is not the root. But on switching the user, sam build starts failing with permission denied error

### Steps to reproduce:

Use the below DOCKERFILE to build the image needed to reproduce
```
FROM docker:23.0-cli

ENV PYTHON_BUILD_PACKAGES="\
readline-dev \
zlib-dev \
bzip2-dev \
sqlite-dev \
libc-dev \
linux-headers \
libxslt-dev \
libxml2-dev \
openssl-dev \
"

USER root

ENV DEBIAN_FRONTEND noninteractive

ARG SETUP_TOOLS_VERSION=65.5.1

RUN addgroup -S newuser && adduser -S newuser -G newuser \
&& chown -R newuser:newuser /home/newuser

RUN apk --quiet --no-cache --no-progress --update add musl-dev gcc python3 python3-dev libffi-dev bash curl=8.4.0-r0 nghttp2-libs=1.57.0-r0 && \
        python3 -m ensurepip --upgrade && \
        pip3 install "cython<3.0.0" wheel && pip3 install pyyaml==5.4.1 --no-build-isolation && \
        pip3 install -U awscli aws-sam-cli && \
        pip3 install setuptools==65.5.1 Flask==2.3.2 && \
        apk del python3-dev gcc musl-dev libffi-dev && \
        sam --version && \
        chown -R  newuser:newuser /tmp

USER newuser

ENTRYPOINT [ "/bin/bash" ]`

```

We want to use "newuser" and not the root user for the build image. But we are unable to do it`

### Observed result:

Detailed logs are
```
Registering workflow 'RustCargoLambdaBuilder' with capability 'Capability(language='rust', dependency_manager='cargo', application_framework=None)'
Found workflow 'PythonPipBuilder' to support capabilities 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Builder crashed
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/aws_lambda_builders/__main__.py", line 117, in main
    builder.build(
  File "/usr/lib/python3.11/site-packages/aws_lambda_builders/builder.py", line 149, in build
    os.makedirs(scratch_dir)
  File "<frozen os>", line 225, in makedirs
PermissionError: [Errno 13] Permission denied: '/tmp/samcli/scratch'
2023-11-02 20:12:06,517 | Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"code": 500, "message": "[Errno 13] Permission denied: '/tmp/samcli/scratch'"}}                  
2023-11-02 20:12:06,521 | Builder crashed                                                                                                                                                                 
2023-11-02 20:12:06,850 | Exception raised during the execution    

Error: [Errno 13] Permission denied: '/tmp/samcli/scratch'
Traceback:
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "click/decorators.py", line 92, in new_func
  File "click/core.py", line 783, in invoke
  File "samcli/lib/telemetry/metric.py", line 184, in wrapped
  File "samcli/lib/telemetry/metric.py", line 149, in wrapped
  File "samcli/lib/utils/version_checker.py", line 42, in wrapped
  File "samcli/cli/main.py", line 95, in wrapper
  File "samcli/commands/build/command.py", line 170, in cli
  File "samcli/commands/build/command.py", line 266, in do_cli
  File "samcli/commands/build/build_context.py", line 281, in run
  File "samcli/lib/build/app_builder.py", line 217, in build
  File "samcli/lib/build/build_strategy.py", line 394, in build
  File "samcli/lib/build/build_strategy.py", line 81, in build
  File "samcli/lib/build/build_strategy.py", line 400, in _build_functions
  File "samcli/lib/build/build_strategy.py", line 416, in _run_builds_async
  File "samcli/lib/utils/async_utils.py", line 131, in run_async
  File "samcli/lib/utils/async_utils.py", line 90, in run_given_tasks_async
  File "asyncio/base_events.py", line 616, in run_until_complete
  File "samcli/lib/utils/async_utils.py", line 58, in _run_given_tasks_async
  File "concurrent/futures/thread.py", line 57, in run
  File "samcli/lib/build/build_strategy.py", line 427, in build_single_function_definition
  File "samcli/lib/build/build_strategy.py", line 164, in build_single_function_definition
  File "samcli/lib/build/app_builder.py", line 697, in _build_function
  File "samcli/lib/build/app_builder.py", line 955, in _build_function_on_container
  File "samcli/lib/build/app_builder.py", line 1004, in _parse_builder_response`

```

### Expected result:

SAM Build to work successfully

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: macOs Monterey
2. `sam --version`: SAM CLI, version 1.96.0
3. AWS region: us-east-1

```
# Paste the output of `sam --info` here

{
  "version": "1.96.0",
  "system": {
    "python": "3.8.13",
    "os": "macOS-12.0.1-arm64-arm-64bit"
  },
  "additional_dependencies": {
    "docker_engine": "24.0.5",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}

```

`Add --debug flag to command you are running`

**Comment by moelasmar** [comment]
Thanks @piyush-bhuwalka for raising this issue. I will investigate it and update you.

**Comment by valerena** [comment]
Closing this issue since there's a way to make this work (`--mount-with WRITE`) and there hasn't been a response in a while. Please open a new issue if you're still experiencing this issue after the previously given suggestion.
