### ISSUE TITLE
Bug: When running sam deploy in github ci/cd, got error Unable to export., TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by jf001z4084** [aws/aws-sam-cli#6629]
### Description:
Our github CI/CD pipeline running `sam deploy` command in ubuntu environment to deploy our lambda function, we found the it failed and report error: Unable to export.

### Observed result:

```
2024-01-31 17:23:33,745 | Sam customer defined id is more priority than other IDs. Customer defined id for resource AuthFunction is AuthFunction
2024-01-31 17:23:36,377 | Unable to export
Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/opt/cfn-lint/libexec/lib/python3.12/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/linuxbrew/.linuxbrew/opt/cfn-lint/libexec/lib/python3.12/site-packages/botocore/awsrequest.py", line 91, in request
    if headers.get('Expect', b'') == b'100-continue':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 807, in get
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/_collections.py", line 261, in __getitem__
    return ", ".join(val[1:])
           ^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bytes found

```

### Expected result:

We expect the lambda function could be deployed successfully.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu
2. `sam --version`: 1.108
3. AWS region: us-west-2

```
# Paste the output of `sam --info` here
```
Unable to export
```

`Add --debug flag to command you are running`

```
  File "/home/linuxbrew/.linuxbrew/opt/cfn-lint/libexec/lib/python3.12/site-packages/botocore/httpsession.py", line 464, in send
    urllib_response = conn.urlopen(
                      ^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/home/linuxbrew/.linuxbrew/opt/cfn-lint/libexec/lib/python3.12/site-packages/botocore/awsrequest.py", line 91, in request
    if headers.get('Expect', b'') == b'100-continue':
       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen _collections_abc>", line 807, in get
  File "/home/linuxbrew/.linuxbrew/opt/python-urllib3/lib/python3.12/site-packages/urllib3/_collections.py", line 261, in __getitem__
    return ", ".join(val[1:])
           ^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, bytes found
```

**Comment by acdha** [comment]
The same thing happens with the Mac Homebrew package, as well. It looks like they recently orphaned that install mechanism as the instructions now say you have to use the .pkg files provided on https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html.

**Comment by jf001z** [comment]
thanks a lot checking the document now.

**Comment by mndeveci** [comment]
We recommend using our native installers which won't have any dependency on the system python version and libraries. https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html

Can you update your installation with the ones that is provided in the documentation to see if it is going to resolve your problem?

Thanks

**Comment by markokimpel** [comment]
The first party installer does not have said problem.

My environment:
- Ubuntu
- The homebrew installer, version 1.108.0, showed the error @jf001z4084 reported
- The AWS provided installer, also version 1.108.0, does not show the error

**Comment by gihanw** [comment]
> The first party installer does not have said problem.
> 
> My environment:
> 
>     * Ubuntu
> 
>     * The homebrew installer, version 1.108.0, showed the error @jf001z4084 reported
> 
>     * The AWS provided installer, also version 1.108.0, does not show the error

This saved my day
