### ISSUE TITLE
Bug: Error: .NET binaries for Lambda function are not correctly installed

### ISSUE THREAD

**Issue by nibblesnbits** [aws/aws-sam-cli#6733]
### Description:

When running a brand new Lambda Annotations project via `sam local start-api`, the first request logs out `Error: .NET binaries for Lambda function are not correctly installed in the /var/task directory of the image when the image was built. The /var/task directory is missing the required .deps.json file.`, along with a py stacktrace.

### Steps to reproduce:

```sh
mkdir my-lambda
cd my-lambda
dotnet new install Amazon.Lambda.Templates
dotnet new serverless.Annotations
cd src/my-lambda
sam local start-api --template-file serverless.template --debug
# now hit http://localhost:3000 from a browser
```

### Observed result:

```log
2024-02-22 20:35:40,329 | No config file found in this directory.
2024-02-22 20:35:40,345 | OSError occurred while reading TOML file: [Errno 2] No such file or
directory: 'D:\\The-UnAd\\monov2\\serverless\\lambda-test\\src\\lambda-test\\samconfig.toml'
2024-02-22 20:35:40,345 | Config file location:
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\samconfig.toml
2024-02-22 20:35:40,345 | Config file
'D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\samconfig.toml' does not exist
2024-02-22 20:35:40,361 | OSError occurred while reading TOML file: [Errno 2] No such file or
directory: 'D:\\The-UnAd\\monov2\\serverless\\lambda-test\\src\\lambda-test\\samconfig.toml'
2024-02-22 20:35:40,361 | Using config file: samconfig.toml, config environment: default
2024-02-22 20:35:40,361 | Expand command line arguments to:
2024-02-22 20:35:40,361 |
--template_file=D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
--host=127.0.0.1 --port=3000 --static_dir=public
--layer_cache_basedir=C:\Users\sgcol\AppData\Roaming\AWS SAM\layers-pkg
--container_host=localhost --container_host_interface=127.0.0.1
2024-02-22 20:35:40,707 | local start-api command is called
2024-02-22 20:35:40,707 | No Parameters detected in the template
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsDefaultGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsAddGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsSubtractGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsMultiplyGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsDivideGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | There is no customer defined id or cdk path defined for resource
ServerlessHttpApi, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,770 | 0 stacks found in the template
2024-02-22 20:35:40,770 | No Parameters detected in the template
2024-02-22 20:35:40,785 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsDefaultGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,785 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsAddGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,785 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsSubtractGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,785 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsMultiplyGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,801 | There is no customer defined id or cdk path defined for resource
lambdatestFunctionsDivideGenerated, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,801 | There is no customer defined id or cdk path defined for resource
ServerlessHttpApi, so we will use the resource logical id as the resource id
2024-02-22 20:35:40,801 | 6 resources found in the stack
2024-02-22 20:35:40,801 | Found Serverless function with
name='lambdatestFunctionsDefaultGenerated' and CodeUri='.'
2024-02-22 20:35:40,801 | --base-dir is not presented, adjusting uri . relative to
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
2024-02-22 20:35:40,801 | Found Serverless function with name='lambdatestFunctionsAddGenerated'
and CodeUri='.'
2024-02-22 20:35:40,801 | --base-dir is not presented, adjusting uri . relative to
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
2024-02-22 20:35:40,801 | Found Serverless function with
name='lambdatestFunctionsSubtractGenerated' and CodeUri='.'
2024-02-22 20:35:40,801 | --base-dir is not presented, adjusting uri . relative to
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
2024-02-22 20:35:40,801 | Found Serverless function with
name='lambdatestFunctionsMultiplyGenerated' and CodeUri='.'
2024-02-22 20:35:40,801 | --base-dir is not presented, adjusting uri . relative to
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
2024-02-22 20:35:40,801 | Found Serverless function with
name='lambdatestFunctionsDivideGenerated' and CodeUri='.'
2024-02-22 20:35:40,801 | --base-dir is not presented, adjusting uri . relative to
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test\serverless.template
2024-02-22 20:35:40,820 | Found '1' API Events in Serverless function with name
'lambdatestFunctionsDefaultGenerated'
2024-02-22 20:35:40,821 | Found '1' API Events in Serverless function with name
'lambdatestFunctionsAddGenerated'
2024-02-22 20:35:40,822 | Found '1' API Events in Serverless function with name
'lambdatestFunctionsSubtractGenerated'
2024-02-22 20:35:40,823 | Found '1' API Events in Serverless function with name
'lambdatestFunctionsMultiplyGenerated'
2024-02-22 20:35:40,824 | Found '1' API Events in Serverless function with name
'lambdatestFunctionsDivideGenerated'
2024-02-22 20:35:40,825 | Detected Inline Swagger definition
2024-02-22 20:35:40,826 | Parsing Swagger document using 3.0 specification
2024-02-22 20:35:40,827 | Found '0' authorizers in resource 'ServerlessHttpApi'
2024-02-22 20:35:40,827 | Lambda function integration not found in Swagger document at
path='/subtract/{x}/{y}' method='get'
2024-02-22 20:35:40,828 | Lambda function integration not found in Swagger document at
path='/add/{x}/{y}' method='get'
2024-02-22 20:35:40,829 | Lambda function integration not found in Swagger document at
path='/divide/{x}/{y}' method='get'
2024-02-22 20:35:40,830 | Lambda function integration not found in Swagger document at
path='/multiply/{x}/{y}' method='get'
2024-02-22 20:35:40,831 | Lambda function integration not found in Swagger document at path='/'
method='get'
2024-02-22 20:35:40,832 | Found '0' APIs in resource 'ServerlessHttpApi'
2024-02-22 20:35:40,832 | authorizer not found or disabled, returning early
2024-02-22 20:35:40,832 | Removed duplicates from '0' Explicit APIs and '5' Implicit APIs to
produce '5' APIs
2024-02-22 20:35:40,832 | 5 APIs found in the template
2024-02-22 20:35:40,843 | Mounting lambdatestFunctionsDivideGenerated at
http://127.0.0.1:3000/divide/{x}/{y} [GET]
2024-02-22 20:35:40,845 | Mounting lambdatestFunctionsMultiplyGenerated at
http://127.0.0.1:3000/multiply/{x}/{y} [GET]
2024-02-22 20:35:40,846 | Mounting lambdatestFunctionsAddGenerated at
http://127.0.0.1:3000/add/{x}/{y} [GET]
2024-02-22 20:35:40,847 | Mounting lambdatestFunctionsDefaultGenerated at
http://127.0.0.1:3000/ [GET]
2024-02-22 20:35:40,848 | Mounting lambdatestFunctionsSubtractGenerated at
http://127.0.0.1:3000/subtract/{x}/{y} [GET]
2024-02-22 20:35:40,849 | You can now browse to the above endpoints to invoke your functions.
You do not need to restart/reload SAM CLI while working on your functions, changes will be
reflected instantly/automatically. If you used sam build before running local commands, you
will need to re-run sam build for the changes to be picked up. You only need to restart SAM CLI
if you update your AWS SAM template
2024-02-22 20:35:40,850 | Localhost server is starting up. Multi-threading = True
2024-02-22 20:35:40,851 | Setting SIGTERM interrupt handler
2024-02-22 20:35:40 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
2024-02-22 20:35:40 Press CTRL+C to quit
2024-02-22 20:35:47,663 | Constructed Event Version 2.0 to invoke Lambda. Event: {'version':
'2.0', 'routeKey': 'GET /', 'rawPath': '/', 'rawQueryString': '', 'cookies': [], 'headers':
{'Host': '127.0.0.1:3000', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:124.0)
Gecko/20100101 Firefox/124.0', 'Accept':
'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8',
'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'Connection':
'keep-alive', 'Upgrade-Insecure-Requests': '1', 'Sec-Fetch-Dest': 'document', 'Sec-Fetch-Mode':
'navigate', 'Sec-Fetch-Site': 'none', 'Sec-Fetch-User': '?1', 'X-Forwarded-Proto': 'http',
'X-Forwarded-Port': '3000'}, 'requestContext': {'accountId': '123456789012', 'apiId':
'1234567890', 'http': {'method': 'GET', 'path': '/', 'protocol': 'HTTP/1.1', 'sourceIp':
'127.0.0.1', 'userAgent': 'Custom User Agent String'}, 'requestId':
'bb1c1ee4-1c4b-49c3-ad49-f6e5debce347', 'routeKey': 'GET /', 'stage': '$default', 'time':
'23/Feb/2024:01:35:40 +0000', 'timeEpoch': 1708652140, 'domainName': 'localhost',
'domainPrefix': 'localhost'}, 'body': '', 'pathParameters': {}, 'stageVariables': None,
'isBase64Encoded': False}
2024-02-22 20:35:47,663 | Found one Lambda function with name
'lambdatestFunctionsDefaultGenerated'
2024-02-22 20:35:47,663 | Invoking
lambda-test::lambda_test.Functions_Default_Generated::Default (dotnet8)
2024-02-22 20:35:47,663 | No environment variables found for function
'lambdatestFunctionsDefaultGenerated'
2024-02-22 20:35:47,663 | Loading AWS credentials from session with profile 'None'
2024-02-22 20:35:47,679 | Resolving code path.
Cwd=D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test,
CodeUri=D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test
2024-02-22 20:35:47,679 | Resolved absolute path to code is
D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test
2024-02-22 20:35:47,694 | Code D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test is not
a zip/jar file
2024-02-22 20:35:49,157 | Local image is up-to-date
2024-02-22 20:35:49,165 | Checking free port on 127.0.0.1:8348
2024-02-22 20:35:49,171 | Using local image: public.ecr.aws/lambda/dotnet:8-rapid-x86_64.

2024-02-22 20:35:49,173 | Mounting D:\The-UnAd\monov2\serverless\lambda-test\src\lambda-test as
/var/task:ro,delegated, inside runtime container
2024-02-22 20:35:50,076 | Starting a timer for 30 seconds for function
'lambdatestFunctionsDefaultGenerated'
2024-02-22 20:35:50,079 | Getting lock for the key localhost-8348
2024-02-22 20:35:50,080 | Waiting to retrieve the lock (localhost-8348) to start invocation
START RequestId: 948f6afa-39b2-434b-9134-6a48e591cc5a Version: $LATEST
Error: .NET binaries for Lambda function are not correctly installed in the /var/task directory of the image when the image was built. The /var/task directory is missing the required .deps.json file.
23 Feb 2024 01:35:51,104 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 105 InvokeID=
23 Feb 2024 01:35:51,105 [ERROR] (rapid) Invoke failed error=Runtime exited with error: exit status 105 InvokeID=aa73205b-97fd-4f5d-988a-186780b776e1
23 Feb 2024 01:35:51,105 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure
2024-02-22 20:35:51,111 | [Container state] OOMKilled False
2024-02-22 20:35:51,468 | Cleaning all decompressed code dirs
2024-02-22 20:35:51,469 | Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 1463,
in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 872, in
full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 870, in
full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 855, in
dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\apigw\local_apigw_service.py",
line 724, in _request_handler
    lambda_response = self._invoke_lambda_function(route.function_name, route_lambda_event)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\apigw\local_apigw_service.py",
line 617, in _invoke_lambda_function
    self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer,
stderr=self.stderr)
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\local\lib\local_lambda.py",
line 147, in invoke
    self.local_runtime.invoke(
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\telemetry\metric.py", line 325, in
wrapped_func
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\lambdafn\runtime.py", line 214,
in invoke
    container.wait_for_result(
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\container.py", line 433,
in wait_for_result
    response, is_image = self.wait_for_http_response(full_path, event, stdout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\utils\retry.py",
line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program
Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\container.py", line 405,
in wait_for_http_response
    if "image" in resp.headers["Content-Type"]:
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\requests\structures.py",
line 52, in __getitem__
    return self._store[key.lower()][1]
           ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'content-type'
2024-02-22 20:35:51,481 | Lambda execution failed (<InternalServerError '500: Internal Server
Error'>,)
2024-02-22 20:35:51 127.0.0.1 - - [22/Feb/2024 20:35:51] "GET / HTTP/1.1" 502 -
2024-02-22 20:35:51 127.0.0.1 - - [22/Feb/2024 20:35:51] "GET /favicon.ico HTTP/1.1" 403 -
```

### Expected result:

200 response

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows 11 Pro 23H2
4. `sam --version`: SAM CLI, version 1.110.0
5. AWS region: us-east-2

```
{
  "version": "1.110.0",
  "system": {
    "python": "3.11.7",
    "os": "Windows-10-10.0.22631-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "25.0.3",
    "aws_cdk": "Not available",
    "terraform": "1.7.3"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by lucashuy** [comment]
Hi, dotnet projects need to be built before being run with our local commands. This can be done with `sam build`. I can reproduce the error you get on a project that has not been built, can you try building the dotnet8 and dotnet6 projects you used before trying `sam local start-api`?
