### ISSUE TITLE
SAM local invocation with CDK generated template with typescript not able to find module index (index.mjs)

### ISSUE THREAD

**Issue by Schwar999** [aws/aws-sam-cli#7048]
### Issue
I'm trying to test a typescript lambda test made with CDK using SAM local invocation.

I did sam local "invoke -t stack.template.json" to test lambda, but I got the following error: "Error: Cannot find module 'index'“, ‘Require stack:’,”- /var/runtime/index.mjs Error."
The configuration in tsconfig.ts uses a CommonJS module with a ES2020 target. 

I am trying to figure out why this error occurred, and I am thinking that SAM probably tried to invoke ES2020 modules instead of CommonJS.
I want to change the SAM local invocation so it can resolve to CommonJS.

I confirmed the result in a console, and it said that "index.js" was made using "cdk deploy", not "index.mjs".

**Error code**
```
user@e5a3a4120a93:~/app/cdk$ sam local invoke func -t ./cdk.out/stack.template.json  --container-host host.docker.internal
Invoking index.handler (nodejs18.x)
arn:aws:lambda:ap-northeast-1:580247275435:layer:LambdaInsightsExtension:78 is already cached. Skipping download
Local image is up-to-date
Using local image: samcli/lambda-nodejs:18-x86_64-2fad385d3004a32911b20c629.

2024-05-09T11:58:15.991Z        undefined       ERROR   Uncaught Exception      {"errorType":"Runtime.ImportModuleError","errorMessage":"Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs","stack":["Runtime.ImportModuleError: Error: Cannot find module 'index'","Require stack:","- /var/runtime/index.mjs","    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)","    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)","    at async start (file:///var/runtime/index.mjs:1282:23)","    at async file:///var/runtime/index.mjs:1288:1"]}   
09 May 2024 11:58:16,018 [ERROR] (rapid) Init failed error=Runtime exited with error: exit status 129 InvokeID=
09 May 2024 11:58:16,521 [ERROR] (rapid) Invoke failed error=ErrAgentNameCollision InvokeID=5cf7740b-0b0c-4b8d-9733-514b9147aa3e

{"errorType": "Runtime.ImportModuleError", "errorMessage": "Error: Cannot find module 'index'\nRequire stack:\n- /var/runtime/index.mjs", "trace": ["Runtime.ImportModuleError: Error: Cannot find module 'index'", "Require stack:", "- /var/runtime/index.mjs", "    at _loadUserApp (file:///var/runtime/index.mjs:1087:17)", "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1119:21)", "    at async start (file:///var/runtime/index.mjs:1282:23)", "    at async file:///var/runtime/index.mjs:1288:1"]}
```

**tsconfig.json**

```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "lib": ["es2020"],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "noEmit": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "typeRoots": ["./node_modules/@types"]
  },
  "exclude": ["node_modules", "cdk.out"]
}

```

**ENV**
Docker
- SAM CLI, version 1.116.0
- CDK 2.141.0 (build 3d1c06e)
- aws-cli/2.15.41 Python/3.11.8 Linux/5.15.133.1-microsoft-standard-WSL2 exe/x86_64.debian.12 prompt/off
- node v18.19.0
- npm version 9.2.0

**Comment by hawflau** [comment]
Hey @Schwar999, thanks for raising the issue.

To help us reproduce the issue, can you please share your Lambda Function Construct in CDK and corresponding Lambda Function Resource in synth-ed template?

**Comment by Schwar999** [comment]
@hawflau 
Thank you for your reply.

Here are some of my codes. 
Would you be able to analyze them?

stack.ts
```
import { Duration, Stack, StackProps } from "aws-cdk-lib";
import { Construct } from "constructs";
import { Topic } from "aws-cdk-lib/aws-sns";
import { SqsSubscription } from "aws-cdk-lib/aws-sns-subscriptions";
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
import { Architecture, LambdaInsightsVersion, Runtime, Tracing } from "aws-cdk-lib/aws-lambda";
import { Config } from "./config";
import { SubnetType, Vpc } from "aws-cdk-lib/aws-ec2";
import { Queue, QueuePolicy } from "aws-cdk-lib/aws-sqs";
import { SqsEventSource } from "aws-cdk-lib/aws-lambda-event-sources";
import { RetentionDays } from "aws-cdk-lib/aws-logs";
import { Effect, PolicyStatement, ServicePrincipal } from "aws-cdk-lib/aws-iam";
import { QueueProps } from "aws-cdk-lib/aws-sqs/lib/queue";

export class TestStack extends Stack {
  constructor(scope: Construct, id: string, props: TestStackProps, config: Config) {
    super(scope, id, props);

    const vpc = Vpc.fromLookup(this, "test-vpc", { vpcId: config.testVpcId });

    const funcLambda = new NodejsFunction(this, `func`, {
      memorySize: 256,
      vpc: vpc,
      vpcSubnets: vpc.selectSubnets({ subnetType: config.testVpcSubnetType as SubnetType }),
      allowPublicSubnet: config.testVpcSubnetType === "Public",
      runtime: Runtime.NODEJS_18_X,
      timeout: Duration.seconds(config.pushNotifier.func.lambdaAndQueueVisibilityTimeoutSeconds),
      environment: {
        ENV_NAME: config.env,
        LOG_LEVEL: config.logLevel,
      },
      architecture: Architecture.X86_64,
      insightsVersion: LambdaInsightsVersion.fromInsightVersionArn(config.lambdaInsightsArn),
      logRetention: RetentionDays.ONE_YEAR,
      tracing: Tracing.ACTIVE,
    });

```

lambda.ts
```
import { Context, SQSEvent, SQSRecord } from "aws-lambda";
import got from "got";
import { defaultLogger, getLogger } from "./logger";
import { captureLambdaHandler, Tracer } from "@aws-lambda-powertools/tracer";
import middy from "@middy/core";

let logger = defaultLogger;

export const handler = middy(async (event: SQSEvent, context: Context) => {
  logger = getLogger(context);
  const sqsRecord: SQSRecord = event.Records[0];
  const sqsBody: ConsumeMessage = JSON.parse(sqsRecord.body);
  return notifySingle(sqsRecord.messageId, sqsBody.endpoint, sqsBody.payload);
}).use(captureLambdaHandler(tracer));
```

**Comment by mndeveci** [comment]
I've tried to reproduce this issue however I was able to invoke the function locally.

Here is the folder structure;
```
.
├── README.md
├── bin
│   └── cdk-local.ts
├── cdk.json
├── jest.config.js
├── lib
│   ├── cdk-local-stack.func.ts
│   └── cdk-local-stack.ts
├── package-lock.json
├── package.json
└── tsconfig.json
```

Here are the contents of the files;
`bin/cdk-local.ts`
```
#!/usr/bin/env node
import 'source-map-support/register';
import * as cdk from 'aws-cdk-lib';
import { CdkLocalStack } from '../lib/cdk-local-stack';

const app = new cdk.App();
new CdkLocalStack(app, 'CdkLocalStack', {});
```

`lib/cdk-local-stack.ts`
```
export interface Response {
    result: number;
}

export const handler = async (event: {}): Promise<Response> => {
    const result = {
        result: 10,
    };

    return result;
};
```

`lib/cdk-local-stack.func.ts`
```
import * as cdk from 'aws-cdk-lib';
import { Architecture, Runtime, Tracing } from 'aws-cdk-lib/aws-lambda';
import { NodejsFunction } from 'aws-cdk-lib/aws-lambda-nodejs';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { Construct } from 'constructs';

export class CdkLocalStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // The code that defines your stack goes here

    const funcLambda = new NodejsFunction(this, `func`, {
      memorySize: 256,
      runtime: Runtime.NODEJS_18_X,
      architecture: Architecture.X86_64,
      logRetention: RetentionDays.ONE_YEAR,
      tracing: Tracing.ACTIVE,
    });
  }
}

```

I've used your `tsconfig.json` file. I am running `cdk synth` and then `sam local invoke --template cdk.out/CdkLocalStack.template.json func` and I can invoke function locally.

Can you provide a reproducible example?

**Comment by lucashuy** [comment]
Closing the issue, please reopen or create a new issue if you encounter any other problems.
