### ISSUE TITLE
Bug: Got issue when using 1.116.0_1 for deployment

### ISSUE THREAD

**Issue by Chris-wa-He** [aws/aws-sam-cli#7051]
### Description:

sam deploy is with issue in version 1.116.0_1 which is installed by HomeBrew

### Steps to reproduce:

1. Install aws-sam-cli by HomeBrew
2. run sam deploy

### Observed result:

2024-05-11 15:44:27 Command 'deploy' is not configured correctly. Unable to import 'samcli.commands.deploy'
Traceback (most recent call last):
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/cli/command.py", line 264, in get_command
    mod = importlib.import_module(pkg_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/commands/deploy/__init__.py", line 6, in <module>
    from .command import cli  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/commands/deploy/command.py", line 10, in <module>
    from samcli.cli.cli_config_file import ConfigProvider, configuration_option, save_params_option
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/cli/cli_config_file.py", line 20, in <module>
    from samcli.lib.config.samconfig import DEFAULT_CONFIG_FILE_NAME, DEFAULT_ENV, SamConfig
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/lib/config/samconfig.py", line 13, in <module>
    from samcli.lib.telemetry.event import EventTracker
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/lib/telemetry/event.py", line 16, in <module>
    from samcli.lib.telemetry.telemetry import Telemetry
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/samcli/lib/telemetry/telemetry.py", line 7, in <module>
    import requests
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/usr/local/Cellar/aws-sam-cli/1.116.0_1/libexec/lib/python3.12/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
Usage: sam [OPTIONS] COMMAND [ARGS]...
Try 'sam -h' for help.

Error: No such command 'deploy'.

### Expected result:

sam deploy is running normally.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
3. `sam --version`: 1.116.0_1
4. AWS region:

```
2024-05-11 15:54:05 Command info not available
Usage: sam [OPTIONS] COMMAND [ARGS]...
Try 'sam -h' for help.

Error: No such command 'info'.
```

`Add --debug flag to command you are running`

**Comment by hawflau** [comment]
Hi @Chris-wa-He thanks for raising the issue.

I tried to install SAM CLI via homebrew and did not see any issue running `sam deploy`. It looks like you don't have `certifi` installed. I'd suggest you to try to reinstall (either via homebrew or use our [installer](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html)). 

Note that the aws-sam-cli formula on homebrew is not maintained by us. If you still see any issue from homebrew installation, please reach out to [homebrew-core](https://github.com/Homebrew/homebrew-core/tree/master). There is no action we can do from our side.
