### ISSUE TITLE
`'str' object has no attribute 'decode'` when `PortAlreadyInUse` error is raised.

### ISSUE THREAD

**Issue by DiscreteTom** [aws/aws-sam-cli#7244]
https://github.com/aws/aws-sam-cli/blob/5570367805bc94e43755e31a493b7cb93677dde3/samcli/local/docker/container.py#L392

Remove `.decode()` to resolve this issue.

**Comment by lucashuy** [comment]
Thanks for reporting this, just so that we can reproduce this, can you fill out the bug template? We just want to confirm before removing the decode as this is the first we are seeing about this, and could be a breaking change if the decode was removed.

````
<!-- Make sure we don't have an existing Issue that reports the bug you are seeing (both open and closed). 
If you do find an existing Issue, re-open or add a comment to that Issue instead of creating a new one. -->

### Description:
<!-- Briefly describe the bug you are facing.-->



### Steps to reproduce:
<!-- Provide detailed steps to replicate the bug, including steps from third party tools (CDK, etc.) -->



### Observed result:
<!-- Please provide command output with `--debug` flag set. -->



### Expected result:
<!-- Describe what you expected. -->



### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

<!-- Either provide the following info (for AWS SAM CLI v1.68.0 or before) or paste the output of `sam --info` (AWS SAM CLI v1.69.0 or after). -->

1. OS:
2. `sam --version`:
3. AWS region:

```
# Paste the output of `sam --info` here
```

`Add --debug flag to command you are running`

````

**Comment by DiscreteTom** [comment]
### Description:


`sam local start-api` got `'str' object has no attribute 'decode'` when `PortAlreadyInUse` error is raised.

### Steps to reproduce:


This issue occurs when requesting the local mock api (e.g. `curl http://localhost:3000/v1/pets`) after `sam local start-api`. Still trying to find a stable way to reproduce this issue.

Theoretically `PortAlreadyInUse` shouldn't happen because the following function

https://github.com/aws/aws-sam-cli/blob/2548a62b27810c5a362ddd8c0e13e2e430b43dc5/samcli/local/docker/utils.py#L54

but sometimes it indeed happened. And when it happened, the `ex.explanation` is a string and the above error occur.

I fixed this in my local `container.py` script and it works nicely.

### Observed result:


Since I haven't find a stable way to reproduce this, here is the only remained info from a sceenshot I took earlier.

```
    container.start(input_data=input_data)
File 'C:\ProgramFiles\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\container.py",line 378, in
    raise PortAlreadyInUse(ex.explanation.decode()) from ex
                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'decode'
2024-07-12 14:27:57 127.0.0.1 - - [12/Jul/2024 14:27:57] "GET /v1/pets HTTP/1.1" 502 -
2024-07-12 14:27:57 127.0.0.1 - - [12/Jul/2024 14:27:57] "GET /favicon.ico HTTP/1.1" 403 -
```

This should be a `PortAlreadyInUse` error and users could see which port is occupied. But now that error is interrupted by the `AttributeError`.

### Expected result:


The actual error should be the `PortAlreadyInUse`. After I fixed this issue, the output is like:

```
2024-07-12 17:29:50,791 | arn:aws:lambda:ap-southeast-1:753240598075:layer:LambdaAdapterLayerX86:22 is already cached. Skipping download
2024-07-12 17:29:50,806 | Checking free port on 127.0.0.1:8725
2024-07-12 17:29:50,813 | Using local image: samcli/lambda-java:17-x86_64-d97bac8a5baa36a91f3a926a4.

2024-07-12 17:29:50,814 | Mounting E:\code\xxx-springboot-web-aws-adapter\.aws-sam\build\PetstoreFunction as /var/task:ro,delegated, inside runtime container
2024-07-12 17:29:50,949 | [Container state] OOMKilled False
2024-07-12 17:29:50,987 | Cleaning all decompressed code dirs
2024-07-12 17:29:50,991 | Exception on /v1/pets [GET]
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\api\client.py", line 265, in _raise_for_status
    response.raise_for_status()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/v1.35/containers/72819bb0596b8c412be705008ec84816a1a4361382fbfc90ee0750a7a0016781/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\flask\app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\apigw\local_apigw_service.py", line 724, in _request_handler
    lambda_response = self._invoke_lambda_function(route.function_name, route_lambda_event)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\apigw\local_apigw_service.py", line 617, in _invoke_lambda_function
    self.lambda_runner.invoke(lambda_function_name, event_str, stdout=stdout_writer, stderr=self.stderr)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\local\lib\local_lambda.py", line 149, in invoke
    self.local_runtime.invoke(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\telemetry\metric.py", line 325, in wrapped_func
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\lambdafn\runtime.py", line 203, in invoke
    container = self.run(container, function_config, debug_context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\lambdafn\runtime.py", line 153, in run
    self._container_manager.run(container)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\manager.py", line 118, in run
    container.start(input_data=input_data)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\container.py", line 379, in start
    raise ex
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\local\docker\container.py", line 375, in start
    real_container.start()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\models\containers.py", line 417, in start
    return self.client.api.start(self.id, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\utils\decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\api\container.py", line 1135, in start
    self._raise_for_status(res)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\api\client.py", line 267, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localnpipe/v1.35/containers/72819bb0596b8c412be705008ec84816a1a4361382fbfc90ee0750a7a0016781/start: Internal Server Error ("Ports are not available: exposing port TCP      
127.0.0.1:8725 -> 0.0.0.0:0: listen tcp 127.0.0.1:8725: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted.")
2024-07-12 17:29:51,023 | Lambda execution failed (<InternalServerError '500: Internal Server Error'>,)
```

But why the `PortAlreadyInUse` was throwed? That's another topic... still investigating...

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)



1. OS: Windows
2. `sam --version`: 1.113.0
3. AWS region: test locally

```
{
  "version": "1.113.0",
  "system": {
    "python": "3.11.8",
    "os": "Windows-10-10.0.19044-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

`Add --debug flag to command you are running`

**Comment by lucashuy** [comment]
Sorry about the delay in response, this is something that we can fix by conditionally checking for the type. Just wanted to ask, do you recall if this was with Docker Desktop, or with a Docker Desktop alternative?

Interesting that the explanation property would have changed from a bytes array to an already decoded string

**Comment by DiscreteTom** [comment]
If I recall it correctly, should be Docker Desktop.

**Comment by msancraian** [comment]
If this helps, I found a way to replicate this constantly: I am calling `sam local invoke --template sam.jvm.yaml -d 5005`.
If port 5005 is already used by another process, I get the error described in this ticket: 
```
Error: 'str' object has no attribute 'decode'
....
 File "/opt/homebrew/Cellar/aws-sam-cli/1.145.2/libexec/lib/python3.14/site-packages/samcli/local/docker/container.py", line 447, in start
    raise PortAlreadyInUse(ex.explanation.decode()) from ex
```

**Comment by dcabib** [comment]
I've done a deep dive into this issue and found the root cause. TL;DR: it's a compatibility issue between SAM CLI and different versions of the `docker-py` library.

The code in `container.py:451` assumes `ex.explanation` is always a `bytes` object and calls `.decode()` on it:

```python
except docker.errors.APIError as ex:
    if "Ports are not available" in str(ex):
        raise PortAlreadyInUse(ex.explanation.decode()) from ex  # Boom!
```

However, in newer versions of `docker-py`, `ex.explanation` is already a `str`, so calling `.decode()` on it throws an `AttributeError`. This completely masks the actual "port already in use" error that we're trying to report to the user.

This explains why some users see it and others don't - it depends on which version of `docker-py` is installed. The behavior changed somewhere along the way from returning bytes to returning strings.

## Additional Bug Found

While replicating this issue locally, I discovered an additional bug on line 450: the code checks for `"Ports are not available"` (capital P), but Docker may return `"ports are not available"` (lowercase p). This case sensitivity issue means that in some scenarios, the condition never matches and users get a generic error instead of the helpful port-specific message.

## Proposed Fix

We need to handle both cases gracefully. I'd recommend adding a helper function to keep things clean:

```python
# In samcli/local/docker/utils.py
def safe_decode_docker_message(message):
    """
    Safely decode a Docker API message that might be bytes or str.
    
    Handles compatibility between different docker-py versions where
    ex.explanation changed from bytes to str.
    """
    if isinstance(message, bytes):
        return message.decode('utf-8')
    return message
```

Then update `container.py:450-451` to fix both issues:

```python
from samcli.local.docker.utils import safe_decode_docker_message

except docker.errors.APIError as ex:
    # Use case-insensitive check to catch both "Ports" and "ports"
    if "ports are not available" in str(ex).lower():
        raise PortAlreadyInUse(safe_decode_docker_message(ex.explanation)) from ex
    raise ex
```

This way we're compatible with both old and new versions of `docker-py`, handle case variations in Docker error messages, and users will actually see the helpful error message about which port is in use instead of a cryptic `AttributeError`.

Happy to submit a PR for this if it looks good to the maintainers! Let me know.

---

**Note for @msancraian**: The fix would also solve your specific case with `sam local invoke -d 5005` when port 5005 is already occupied.
