### ISSUE TITLE
SAM Build Not Mounting Lambda Code in `/var/task` During `sam local start api` on Windows

### ISSUE THREAD

**Issue by pedrocimp** [aws/aws-sam-cli#7478]
### Description:
When using `sam build` and running `sam local start api` or `sam local invoke`, SAM builds the Lambda image on the fly. However, it seems that the Lambda code is not being mounted correctly in `/var/task`, which results in an empty directory. This prevents the Lambda from executing properly.

### Context:
I expect SAM to mount the built Lambda sources from `dist/` into `/var/task` inside the container. However, the `/var/task` directory is empty, making it impossible to execute the Lambda function via `sam local start api`.

I've tried multiple solutions but couldn't resolve this issue. It might be related to switching from a Linux development environment to a Windows environment.

In my `template.yml`, I point the `CodeUri` to the compiled code in the `dist/` directory, like this:

```yaml
CodeUri: dist/lambdas/myFunction/
```

### Expected behavior:
The compiled Lambda code should be mounted into `/var/task` inside the container to allow the Lambda function to execute properly.

### Environment:
- **Operating System**: Windows
- **SAM CLI Version**: Tested with version 1.120
- **Docker Version**: 26.1.0-rd
- **Docker setup**: Running on WSL2
- **Custom Lambda Image**: Defined in `template.yml`

### Steps to reproduce:
1. Run `sam build`.
2. Start the Lambda function using either `sam local start api` or `sam local invoke`.
3. Inspect the container, and observe that `/var/task` is empty.

### Possible suggestions or fixes:
- Ensure that SAM properly mounts the Lambda code into the `/var/task` directory during execution on Windows.
- Investigate if the issue is related to file mounting differences between Linux and Windows.

Thank you for your help!

**Comment by sidhujus** [comment]
Hi thanks for raising this issue! Could you provide the output generated by sam cli when running the commands with the `--debug` flag?

**Comment by pedrocimp** [comment]
sam local start-api --warm-containers LAZY --host 0.0.0.0 -p 13000 --docker-network my_network --container-host 127.0.0.1 --template template.yml --env-vars tests/resources/environment.json --log-file logs.txt --invoke-image myprivaterepo/public.ecr.aws/lambda/nodejs:20

**Comment by pedrocimp** [comment]
I don't use sam build for building my project and generating the /dist folder, my project is built with npx tsc --project tsconfig.build.json .
Maybe there is a link with my issue ?
Thanks :)

**Comment by pedrocimp** [comment]
@aaythapa @sidhujus any news ?

**Comment by gamaleonardo** [comment]
I'm facing the same issue :( Any news on this topic?

**Comment by gamaleonardo** [comment]
> I don't use sam build for building my project and generating the /dist folder, my project is built with npx tsc --project tsconfig.build.json . Maybe there is a link with my issue ? Thanks :)

I don't think so because I'm building the project with sam build and it doesn't work.

**Comment by clocobhupesh** [comment]
did you guys found any solution

**Comment by leonartdoss** [comment]
> did you guys found any solution

No, I changed my approach and now I'm running SAM directly from Windows.

**Comment by samuraime** [comment]
I'm experiencing a similar issue on Mac when calling either `sam local start-api` or `sam local invoke HelloWorldFunction --event events/event.json`.
The app comes from SAM hello world app, can be successfully deployed. No luck in local.

```
{
  "errorType": "Runtime.ImportModuleError",
  "errorMessage": "Error: Cannot find module 'app'\nRequire stack:\n- /var/runtime/index.mjs",
  "trace": [
    "Runtime.ImportModuleError: Error: Cannot find module 'app'",
    "Require stack:",
    "- /var/runtime/index.mjs",
    "    at _loadUserApp (file:///var/runtime/index.mjs:1109:17)",
    "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1148:21)",
    "    at async start (file:///var/runtime/index.mjs:1335:23)",
    "    at async file:///var/runtime/index.mjs:1342:1"
  ]
}

```

have you solved your issue? @gener1c-code

**Comment by RyanMartin-Carewell** [comment]
I appear to be having the same issue. `sam local invoke` claims to mount my build directory to /var/task, but it's not present inside the Docker container during the runtime. node-config fails due to missing .json files, then the handler crashes due to undefined reads.

```
 % sam local invoke AutoshipApiFunction -e test/as_api/events/healthcheck.json
No current session found, using default AWS::AccountId                                                                                                                                                                 
Invoking index.handler (nodejs22.x)                                                                                                                                                                                    
Local image is up-to-date                                                                                                                                                                                              
Using local image: public.ecr.aws/lambda/nodejs:22-rapid-x86_64.                                                                                                                                                       
                                                                                                                                                                                                                       
Mounting /Users/ryan.martin/Projects/service-autoship/.aws-sam/build/AutoshipApiFunction as /var/task:ro,delegated, inside runtime container                                                                           
START RequestId: 33f0f007-dca9-4c09-a615-75d2ec94cece Version: $LATEST
{"timestamp":"2025-08-12T21:29:55.375Z","level":"ERROR","message":"WARNING: NODE_ENV value of 'staging' did not match any deployment config file names."}
{"timestamp":"2025-08-12T21:29:55.407Z","level":"ERROR","message":"WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode"}
{"timestamp":"2025-08-12T21:29:55.408Z","level":"ERROR","message":"WARNING: No configurations found in configuration directory:/var/task/config"}
{"timestamp":"2025-08-12T21:29:55.408Z","level":"ERROR","message":"WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment."}
{"timestamp":"2025-08-12T21:29:55.412Z","level":"ERROR","message":{"errorType":"TypeError","errorMessage":"Cannot read properties of undefined (reading 'prototype')","stackTrace":["TypeError: Cannot read properties of undefined (reading 'prototype')","    at node_modules/@feathersjs/feathers/lib/service.js (file:///var/task/index.mjs:21177:105)","    at __require2 (file:///var/task/index.mjs:17:53)","    at node_modules/@feathersjs/feathers/lib/events.js (file:///var/task/index.mjs:21221:21)","    at __require2 (file:///var/task/index.mjs:17:53)","    at node_modules/@feathersjs/feathers/lib/application.js (file:///var/task/index.mjs:21431:20)","    at __require2 (file:///var/task/index.mjs:17:53)","    at node_modules/@feathersjs/feathers/lib/index.js (file:///var/task/index.mjs:21599:25)","    at __require2 (file:///var/task/index.mjs:17:53)","    at file:///var/task/index.mjs:279375:31","    at ModuleJob.run (node:internal/modules/esm/module_job:274:25)"]}}
12 Aug 2025 21:29:55,508 [ERROR] (rapid) Init failed InvokeID= error=Runtime exited with error: exit status 129
12 Aug 2025 21:29:55,511 [ERROR] (rapid) Invoke failed error=Runtime exited with error: exit status 129 InvokeID=421310a0-b668-4087-8575-b19bb38628b3
12 Aug 2025 21:29:55,511 [ERROR] (rapid) Invoke DONE failed: Sandbox.Failure
```

Diagnosis is made more difficult because the failed rapid container doesn't leave a trace in my Docker Desktop. So, there's no way to restart the container for examination.

**Comment by danielmacho72** [comment]
It seems there was a workaround : using WSL to run SAM

Workaround: https://github.com/aws/aws-sam-cli/issues/7807

However, I tested and it does not work... :/
