### ISSUE TITLE
SAM Build error: NodejsNpmBuilder:NpmPack raised unhandled exception

### ISSUE THREAD

**Issue by mpetrolati** [aws/aws-sam-cli#7503]
Since version 1.124.0 I can no longer build an aws sam template with a lambda function inside in nodejs

log:
`
Running workflow 'NodejsNpmBuilder'
2024-09-23 14:17:50,494 |  Running NodejsNpmBuilder:NpmPack
2024-09-23 14:17:50,495 | NODEJS packaging file:C:\......\.aws-dist to
C:\Users\<userfolder>\AppData\Local\Temp\tmpr_e2iwel
2024-09-23 14:17:50,497 | executing NPM: ['npm.cmd', 'pack', '-q',
'file:C:\\...\\.aws-dist']
2024-09-23 14:17:52,527 | NODEJS packed to <nomefile>-api-1.4.4.tgz
2024-09-23 14:17:52,528 | NODEJS extracting to C:\Users\<userfolder>\AppData\Local\Temp\tmpr_e2iwel\unpacked
2024-09-23 14:17:52,530 | NodejsNpmBuilder:NpmPack raised unhandled exception
Traceback (most recent call last):
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\aws_lambda_builders\workflow.py", line 374, in run
    action.execute()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\aws_lambda_builders\workflows\nodejs_npm\actions.py",
line 68, in execute
    extract_tarfile(tarfile_path, self.artifacts_dir)
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\aws_lambda_builders\utils.py", line 230, in
extract_tarfile
    with tarfile.open(tarfile_path, "r:*") as tar:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "tarfile.py", line 1835, in open
  File "tarfile.py", line 1903, in gzopen
  File "gzip.py", line 192, in __init__
FileNotFoundError: [Errno 2] No such file or directory:
'C:\\Users\\M9A61~1.PET\\AppData\\Local\\Temp\\tmpr_e2iwel\\livesign-api-1.4.4.tgz'`

I can't put the whole project as an example but if needed I can create a simpler one to see if the problem persists.

I installed the previous version of sam 1.123.0 and the problem does not occur

1. OS: Win 11
2. `sam --version`: 1.124.0
3. AWS region: eu-south-1

```
{
  "version": "1.124.0",
  "system": {
    "python": "3.12.6",
    "os": "Windows-11-10.0.22631-SP0"
  },
  "additional_dependencies": {
    "docker_engine": "Not available",
    "aws_cdk": "Not available",
    "terraform": "Not available"
  },
  "available_beta_feature_env_vars": [
    "SAM_CLI_BETA_FEATURES",
    "SAM_CLI_BETA_BUILD_PERFORMANCE",
    "SAM_CLI_BETA_TERRAFORM_SUPPORT",
    "SAM_CLI_BETA_RUST_CARGO_LAMBDA"
  ]
}
```

**Comment by lucashuy** [comment]
Thanks for opening this. Unfortunately, I'm not able to reproduce this using a hello world Node.js 20 template. We'd appreciate a sample project that causes SAM CLI to fail for you to see if we're able to reproduce it.

If you have Docker installed, can you try to build using a container? You can do this with the `sam build -u` or `sam build --use-container` option. Curious if you see the same problem when using our Docker images.

**Comment by mpetrolati** [comment]
Hi,
I’ve created a sample project in this repository: https://github.com/mpetrolati/aws-sam-lambda-nestjs-build-error to replicate the issue.
I have installed the new SAM CLI version 1.125.0, but the issue persists.

**Comment by mpetrolati** [comment]
Hi, 
I have updated to the new version SAM CLI 1.126.0 but the issue persists with a different error:
`
Error: Install pypiwin32 package to enable npipe:// support
Traceback:
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\cli\cli_config_file.py", line 347, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\telemetry\metric.py", line 185, in wrapped
    raise exception  # pylint: disable=raising-bad-type
    ^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\telemetry\metric.py", line 150, in wrapped
    return_value = func(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\utils\version_checker.py", line 43, in wrapped
    actual_result = func(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\cli\main.py", line 95, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\build\command.py", line 169, in cli
    do_cli(
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\build\command.py", line 258, in do_cli
    ctx.run()
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\commands\build\build_context.py", line 259, in run
    builder = ApplicationBuilder(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\samcli\lib\build\app_builder.py", line 171, in __init__
    self._docker_client = docker_client if docker_client else docker.from_env(version=DOCKER_MIN_API_VERSION)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\client.py", line 94, in from_env
    return cls(
           ^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Amazon\AWSSAMCLI\runtime\Lib\site-packages\docker\api\client.py", line 174, in __init__
    raise DockerException(
`
