### ISSUE TITLE
Unable to build ruby function requiring a layer

### ISSUE THREAD

**Issue by pdlug** [aws/aws-sam-cli#911]
### Description

I have a ruby function that requires the "pg" gem which in turn requires having the PostgreSQL libraries to build since it's a native extension. Without SAM I've gotten this work building a layer and then using the docker image locally that built this layer to build the ruby gems. Works just great in production as well. Using `sam build --use-container` the build fails with the only error indicated: "2019-01-04 14:05:22 Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"message": "RubyBundlerBuilder:RubyBundle - Bundler Failed: ", "code": 400}}". 

I think there two possible causes:

1. It's not using the layer to build the gems.
2. The gem is not able to find the PostgreSQL libraries. In this case I've had to use environment variables in the past to set bundler configuration (ex: `env BUNDLE_BUILD__PG="--with-pg-config=/opt/bin/pg_config"`). It's not clear to me how this would work with SAM since the environment variables appear to be for runtime not build.

Here's how I do this process without SAM (happy to share more working code if this is helpful): https://gist.github.com/pdlug/5aba2555756b8f03ec3bc736912270fa

### Steps to reproduce

Start a ruby project with `sam`, add `gem 'pg'` to your `Gemfile'. Publish a PostgreSQL layer with the instructions above and add it to the layers. Execute `sam build --use-container`.

### Observed result

```
2019-01-04 14:04:47 Using SAM Template at /Users/paul/parse-xml-lambda/template.yaml
2019-01-04 14:04:47 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-04 14:04:47 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-04 14:04:47 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-04 14:04:47 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-04 14:04:47 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-04 14:04:47 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-04 14:04:47 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-04 14:04:47 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-04 14:04:47 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-04 14:04:47 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-04 14:04:47 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-04 14:04:47 Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
2019-01-04 14:04:47 Changing event name from before-call.apigateway to before-call.api-gateway
2019-01-04 14:04:47 Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
2019-01-04 14:04:47 Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
2019-01-04 14:04:47 Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
2019-01-04 14:04:47 Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
2019-01-04 14:04:47 Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
2019-01-04 14:04:47 Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
2019-01-04 14:04:47 Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
2019-01-04 14:04:47 Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
2019-01-04 14:04:47 Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
2019-01-04 14:04:47 'build' command is called
2019-01-04 14:04:47 Starting Build inside a container
2019-01-04 14:04:47 Looking for credentials via: env
2019-01-04 14:04:47 Looking for credentials via: assume-role
2019-01-04 14:04:47 Looking for credentials via: shared-credentials-file
2019-01-04 14:04:47 Found credentials in shared credentials file: ~/.aws/credentials
2019-01-04 14:04:47 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/endpoints.json
2019-01-04 14:04:47 Event choose-service-name: calling handler <function handle_service_name_alias at 0x103a01730>
2019-01-04 14:04:47 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/serverlessrepo/2017-09-08/service-2.json
2019-01-04 14:04:47 Event creating-client-class.serverlessapplicationrepository: calling handler <function add_generate_presigned_url at 0x1039c7620>
2019-01-04 14:04:47 The s3 config key is not a dictionary type, ignoring its value of: None
2019-01-04 14:04:48 Setting serverlessrepo timeout as (60, 60)
2019-01-04 14:04:48 Loading JSON file: /usr/local/Cellar/aws-sam-cli/0.10.0/libexec/lib/python3.7/site-packages/botocore/data/_retry.json
2019-01-04 14:04:48 Registering retry handlers for service: serverlessrepo
2019-01-04 14:04:48 No Parameters detected in the template
2019-01-04 14:04:48 2 resources found in the template
2019-01-04 14:04:48 Found Serverless function with name='HelloWorldFunction' and CodeUri='hello_world/'
2019-01-04 14:04:48 Trying paths: ['/Users/paul/.docker/config.json', '/Users/paul/.dockercfg']
2019-01-04 14:04:48 Found file at path: /Users/paul/.docker/config.json
2019-01-04 14:04:48 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-04 14:04:48 Config entry for key stackOrchestrator is not auth config
2019-01-04 14:04:48 Building resource 'HelloWorldFunction'
2019-01-04 14:04:48 Trying paths: ['/Users/paul/.docker/config.json', '/Users/paul/.dockercfg']
2019-01-04 14:04:48 Found file at path: /Users/paul/.docker/config.json
2019-01-04 14:04:48 Couldn't find auth-related section ; attempting to interpret as auth-only file
2019-01-04 14:04:48 Config entry for key stackOrchestrator is not auth config
2019-01-04 14:04:48 http://localhost:None "GET /v1.35/images/lambci/lambda:build-ruby2.5/json HTTP/1.1" 200 None
2019-01-04 14:04:48 Looking for auth config
2019-01-04 14:04:48 Looking for auth entry for 'docker.io'
2019-01-04 14:04:48 No entry found
2019-01-04 14:04:48 No auth config found
2019-01-04 14:04:48 http://localhost:None "POST /v1.35/images/create?tag=build-ruby2.5&fromImage=lambci%2Flambda HTTP/1.1" 200 None

Fetching lambci/lambda:build-ruby2.5 Docker container image......
2019-01-04 14:04:48 Mounting /Users/paul/parse-xml-lambda/hello_world as /tmp/samcli/source:ro inside runtime container
2019-01-04 14:04:48 http://localhost:None "POST /v1.35/containers/create HTTP/1.1" 201 90
2019-01-04 14:04:48 http://localhost:None "GET /v1.35/containers/2be52a08add11e3582cdf5942c4d6c787a3ad3ac3925c7f3bdb4c42db0b1f14f/json HTTP/1.1" 200 None
2019-01-04 14:04:48 http://localhost:None "GET /v1.35/containers/2be52a08add11e3582cdf5942c4d6c787a3ad3ac3925c7f3bdb4c42db0b1f14f/json HTTP/1.1" 200 None
2019-01-04 14:04:49 http://localhost:None "POST /v1.35/containers/2be52a08add11e3582cdf5942c4d6c787a3ad3ac3925c7f3bdb4c42db0b1f14f/start HTTP/1.1" 204 0
2019-01-04 14:04:49 http://localhost:None "GET /v1.35/containers/2be52a08add11e3582cdf5942c4d6c787a3ad3ac3925c7f3bdb4c42db0b1f14f/json HTTP/1.1" 200 None
2019-01-04 14:04:49 http://localhost:None "POST /containers/2be52a08add11e3582cdf5942c4d6c787a3ad3ac3925c7f3bdb4c42db0b1f14f/attach?stdout=1&stderr=1&logs=1&stream=1&stdin=0 HTTP/1.1" 101 0
Using the request object from command line argument
Loading workflow module 'aws_lambda_builders.workflows'
Registering workflow 'PythonPipBuilder' with capability 'Capability(language='python', dependency_manager='pip', application_framework=None)'
Registering workflow 'NodejsNpmBuilder' with capability 'Capability(language='nodejs', dependency_manager='npm', application_framework=None)'
Registering workflow 'RubyBundlerBuilder' with capability 'Capability(language='ruby', dependency_manager='bundler', application_framework=None)'
Found workflow 'RubyBundlerBuilder' to support capabilities 'Capability(language=u'ruby', dependency_manager=u'bundler', application_framework=None)'
'ruby' runtime has not been validated!
Running workflow 'RubyBundlerBuilder'
Running RubyBundlerBuilder:CopySource
RubyBundlerBuilder:CopySource succeeded
Running RubyBundlerBuilder:RubyBundle
Running bundle install in /tmp/samcli/artifacts
executing Bundler: ['bundle', 'install', '--without', 'development', 'test']
RubyBundlerBuilder:RubyBundle failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflow.py", line 164, in run
    action.execute()
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflows/ruby_bundler/actions.py", line 35, in execute
    raise ActionFailedError(str(ex))
ActionFailedError: Bundler Failed: 
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/__main__.py", line 98, in main
    options=params["options"])
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/builder.py", line 108, in build
    return workflow.run()
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflow.py", line 173, in run
    reason=str(ex))
WorkflowFailedError: RubyBundlerBuilder:RubyBundle - Bundler Failed: 
2019-01-04 14:05:22 Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"message": "RubyBundlerBuilder:RubyBundle - Bundler Failed: ", "code": 400}}
Build Failed
Error: RubyBundlerBuilder:RubyBundle - Bundler Failed: 
```
### Expected result

Expected gems for ruby function to be built using the ruby runtime and layers specified in `template.yaml`

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Mac
2. `sam --version`: 0.10.0

`Add --debug flag to command you are running`

**Comment by waheedi** [comment]
What is your bundler version? If you are running 1.17.2 it seems you have to update it to get bundler rolling.

**Comment by pdlug** [comment]
Bundler 2.0.1 locally but I'm not sure if SAM uses the bundler inside the container during the build. Not sure what feature(s) in bundler 2.0 would make a difference in this case.

**Comment by waheedi** [comment]
I believe the timeout error, is not related to bundler, I was having the
same issue yesterday, and still having it in my local machine, for some
reason time out error is all what i get.

**Comment by pdlug** [comment]
I don't see a timeout error. I tried bundler 1.17.3 and 2.0.1, same result.

**Comment by mycargus** [comment]
I get the same error with the same steps to reproduce. I've tried with bundler 1.17.3 and 2.0.1. My Gemfile only has the json_pure gem. No Gemfile.lock.

OS: Mac 10.14.2
sam --version: 0.10.0
ruby -v: 2.5.3p105
docker -v: 18.09.0, build 4d60db4

**Comment by waheedi** [comment]
@pdlug @mycargus can you run the bundle with verbose flag I see the command is: executing Bundler: ['bundle', 'install', '--without', 'development', 'test'] if you add verbose, I believe it will give you a more detailed message about the exact error, that happened, I believe it will be a timeout error. the way I solved this, was I ran my own local gem server and made Gemfile to lookup the local gem server. Hope that helps. The issue is most probably not related to aws-same-cli

**Comment by pdlug** [comment]
The `bundle install` command is being run by sam cli, not sure how I would override it. `bundle install` runs cleanly locally (not being run in container via sam cli).

**Comment by mycargus** [comment]
I've verified running `bundle install` inside the container works fine, though I'm not certain whether SAM invokes the same command.

```
docker run -v $(pwd):/var/task lambci/lambda:build-ruby2.5 bash -c "bundle install"
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/..
Using bundler 1.17.2
Fetching json_pure 2.1.0
Installing json_pure 2.1.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by mycargus** [comment]
Also I forced a bundler timeout and got this error message, as expected: `(Net::OpenTimeout)`. I'll try using a local gem server.

```
docker run -v $(pwd):/var/task lambci/lambda:build-ruby2.5 bash -c "bundle config timeout 0 && bundle install --without development test --verbose"
```

**Comment by mycargus** [comment]
`sam build --region us-east-1 --debug` works fine using a local gem server and adding this line to the top of Gemfile: `source "http://localhost:8808"`, as expected. It also still works when using `source "https://rubygems.org"`. 

`sam build --use-container --region us-east-1 --debug` using a local gem server and adding this line to the top of Gemfile: `source "http://localhost:8808" fails because bundler inside the docker container cannot connect to the host localhost, which makes sense I think. @waheedi what did you do to get this to work?

Thank you for your time.

**Comment by jfuss** [comment]
@pdlug Thanks for the issue. Going to break this down because there is a lot of details here.

### About Layers and `sam build`

I am not sure what your expectation is with adding a Layer. Currently build does not support building layers, we only support functions. I have an open [RFC](#840) for building layers through `sam build`. This support does not affect the functions through because Layers are a completely different resource.

### Using Env Vars

It doesn't appear that we have a way in `sam build` to add env vars into the container. I can't tell if that is needed for this, or just would have helped in getting around the problem. Could provide more details here on how this could be useful? Even if this doesn't solve the issue you are experiencing, it could be a good practice we follow to allow customization of the dependency managers inside the container.

### Versions of bundler

I don't believe this has anything to do with the initially issue. Unless there is some feature difference that is needed, I would expect the version of bundler to be irrelevant.

### Timeout

This seems possible but it doesn't look like we log enough data to help figure out the root issue here. We should add a way to enable verbose output of each dependency manager or have correct logging that would give us what bundler complained about.

I know that there are issues with PostgreSQL and building for Ruby, or at least what I recall from reading/talking to people. @awood45 Do you have any thoughts or ideas on what could be causing this?

**Comment by jfuss** [comment]
@mycargus Docker does not have access to your localhost on your machine. You can use `host.docker.internal` has the host name to allow docker to talk to your machine. This is currently only supported by Docker for Windows and Docker for Mac. You can follow: https://github.com/docker/for-linux/issues/264 for linux (there are workarounds there), or you can use `--docker-network host` to force the docker images to be on your computers host network.

**Comment by awood45** [comment]
I'd recommend if you have a layer that uses the 'pg' gem that you exclude it from your function `Gemfile`, and let the layer provide the gem at runtime.

Unfortunately, to the best of my knowledge `bundler` hasn't really anticipated the use case where you expect a subset of your dependencies to be provided from another source and always wants to include your full closure of dependencies.

**Comment by mycargus** [comment]
Thank you all for the helpful feedback. FWIW I've also reproduced the original error reported in this issue but without a Lambda layer. Just a bare bones Alexa skill with a Ruby Lambda function, and `sam build --use-container` fails.

**Comment by jfuss** [comment]
@mycargus Yes. With the current output, we can't really see why bundler is failing. So we will need to either reproduce locally (and add more detailed logging for the future) to really understand what is happening and why bundler is not happy.

**Comment by mycargus** [comment]
@jfuss Cool. I'll keep tinkering to see if I can figure it out. Thanks!

**Comment by mycargus** [comment]
For what it's worth, I figured out what I was doing wrong. From the README file generated by `sam init --runtime ruby2.5 --name hello-ruby-sam`:

```
AWS Lambda Ruby runtime requires a flat folder with all dependencies including the application.
```

I had placed my Gemfile outside the application directory.  🤦‍♂️ 

`sam build --use-container` works now that I've structured my project correctly.

**Comment by daveroberts** [comment]
I'm having a similar issue with the mysql2 gem.  `sam build --use-container` fails with `Bundler Failed` in the output.  It seems likely this is because the docker image doesn't have the required mysql libraries in order to build this native gem library.  What can be done to overcome this error?

**Comment by andrba** [comment]
similar to @mycargus finding, I had been having the same error until I found out that the location of the template matters.

`sam build --use-container --debug --template=../template.yaml` throws

```
RubyBundlerBuilder:RubyBundle failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflow.py", line 164, in run
    action.execute()
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflows/ruby_bundler/actions.py", line 35, in execute
    raise ActionFailedError(str(ex))
ActionFailedError: Bundler Failed:
Builder workflow failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/__main__.py", line 98, in main
    options=params["options"])
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/builder.py", line 108, in build
    return workflow.run()
  File "/usr/local/lib/python2.7/site-packages/aws_lambda_builders/workflow.py", line 173, in run
    reason=str(ex))
WorkflowFailedError: RubyBundlerBuilder:RubyBundle - Bundler Failed:
2019-01-30 16:52:50 Build inside container returned response {"jsonrpc": "2.0", "id": 1, "error": {"message": "RubyBundlerBuilder:RubyBundle - Bundler Failed: ", "code": 400}}
Build Failed
Error: RubyBundlerBuilder:RubyBundle - Bundler Failed:
```

while `sam build --use-container --debug --template=template.yaml` builds it successfully

**Comment by jasonmk** [comment]
Basically exactly the same thing I ran into with the mysql2 gem.  The issue is that the shared libraries that rubygems with native extensions require aren't there.

I put together some scripts to automatically build a precompiled version of the gem and a runtime layer for lambda.  You can find them here: https://github.com/jasonmk/lambda-gem-compiler.  However, I would love to see this become part of the SAM build process.  I know some people consider layers to be separate from a function, but if it's necessary for the function to run then it seems to me that it would make sense to have them share a build process.

**Comment by metaskills** [comment]
Not done a lot of reading on this thread but I've cooked up a way to use SAM & Ruby with native extensions using the current project as is. It did require a lot of learning and some outside scripting, but my large tent poles were:

* Using native extensions are the norm. Make it easy.
* Local development/test server/api using local platform and Docker must be easy.is a must. 

To that end, I have this starter bootstrap project that I still putting some polish and effort into. The git history (pull requests) shows the steps I've gone thru and outlines everything and some of the problems I've encountered.

https://github.com/757rb/hello-757rb-lambda

Hope that is helpful.

**Comment by CaDs** [comment]
@mycargus would it be possible for you to share your project's structure somewhere?
I'm having the same problem and, although I did as you suggested is still not working for me.

Thanks a lot.

**Comment by mycargus** [comment]
@CaDs I'm so sorry I've taken a month to respond. Here's a gist that will hopefully help. https://gist.github.com/mycargus/d86e9201feb43e39b3c7dfb4df451fe5

Lemme know if I can clarify anything!

**Comment by sriram-mv** [comment]
* SAM CLI now supports building layers directly as referenced in the template and you can choose a `BuildMethod` based on the runtime. There is also a custom Makefile builder which gives you tighter control on how to build artifacts for serverless functions.
